### ISSUE TITLE
VictoryStack TypeError when children includes VictoryAxis

### ISSUE THREAD

**Issue by jthetzel** [FormidableLabs/victory#1000]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Including `<VictoryAxis />` in `<VictoryStack />` results in error:
```
Uncaught TypeError: Cannot read property 'map' of undefined
    at VictoryStack.addLayoutData (victory.js:38013)
    at victory.js:38078
    at Array.map (<anonymous>)
    at VictoryStack.getNewChildren (victory.js:38077)
    at VictoryStack.render (victory.js:38140)
    at p._renderValidatedComponentWithoutOwnerOrContext (react-dom.min.js:13)
    at p._renderValidatedComponent (react-dom.min.js:13)
    at performInitialMount (react-dom.min.js:13)
    at p.mountComponent (react-dom.min.js:13)
    at Object.mountComponent (react-dom.min.js:14)
```
This is due to `childComponents` and `datasets` having different lengths at https://github.com/FormidableLabs/victory-chart/blob/cfec56e3a03bdb8d97dc5603c0006afe3199e45b/src/components/victory-stack/victory-stack.js#L181

### Reproduction

Fiddle: https://jsfiddle.net/oxbagvgj/3/ . Change `INCLUDE_AXIS` to `false` to resolve error and back to `true` to reproduce it.

**Comment by boygirl** [comment]
Sorry for the late reply, I’m out of the office until mid next week. The main issue here is that VictoryAxis should not be a child of VictoryStack, as it contributes no data to stack. Instead, you can nest VictoryAxis within VictoryChart as a sibling of VictoryStack rather than a child
