### ISSUE TITLE
Have storybook online: https://github.com/FormidableLabs/victory-chart/tree/master/.storybook

### ISSUE THREAD

**Issue by sibelius** [FormidableLabs/victory#1003]
I think it would be very useful to have all storybooks online, so we can easily check how changing props changes the components

**Comment by boygirl** [comment]
@sibelius check it out: https://www.chromaticqa.com/library?appId=5abd2c1b7c94b400209839e8

**Comment by alissaVrk** [comment]
this is 2 years old :(
any way to view the up to date one?

**Comment by asherccohen** [comment]
are there plans to host all of your storybook online?
