### ISSUE TITLE
Setting tickValues in VictoryAxis to anything other than `x` offsets them by 1

### ISSUE THREAD

**Issue by jeremytowne** [FormidableLabs/victory#1005]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

If I set the `tickValues` to something other than `x` will shift the axis labels down by 1 so they are aligned with the wrong data point. 
Ex:
```
const data = [
            {x: 0, xName: 'zero', y: 5},
            {x: 1, xName: 'one', y: 4},
            {x: 2, xName: 'two', y: 2},
            {x: 3, xName: 'three', y: 3},
            {x: 4, xName: 'four', y: 1}
          ]
...
<VictoryAxis 
      tickValues={data.map(d => d.xName)}
      tickFormat={d => `x: ${d}`}
/>
```
This will shift the x axis down like:
![image](https://user-images.githubusercontent.com/3877583/40183459-dff52ce0-59bb-11e8-9290-fa812d4e3228.png)

I found the workaround for this issue is to just use the `x` value for the `tickValue` and access the `data` again from the `tickFormat` based on `x`:
```
<VictoryAxis 
      tickValues={data.map(d => d.x)}
      tickFormat={d => `x: ${data[d].xName}`}
/>
```
### Reproduction

https://jsfiddle.net/jtowne03/L3ema49k/6/

**Comment by boygirl** [comment]
setting xName manually is not recommended. It is typically set by Victory when data is categorical. Victory computes a string map for categorical behavior that starts at one, so this is expected behavior.
