### ISSUE TITLE
VictorySelectionContainer fires onSelectionCleared even if there was no selection

### ISSUE THREAD

**Issue by ersinciftci** [FormidableLabs/victory#1007]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

VictorySelectionContainer fires onSelectionCleared whenever a chart is clicked, and absorbs the onClick event, so if a chart has both drag&drop selection and click-on-a-point type of single element selection, it doesn't work. So I think VictorySelectionContainer should check if a drag&drop selection is made previously, if not, should not absorb the onClick event.

**Comment by boygirl** [comment]
@ersinciftci I took a look, and this is a super simple fix. I will have a patch out for you this afternoon. I'm sorry this got delayed.

**Comment by boygirl** [comment]
@ersinciftci it is easy to make sure that `onSelectionCleared` will not fire if there is no selection, but the `onClick` event is still absorbed, because there is still an `onMouseDown` and `onMouseUp` event on the parent.

**Comment by ersinciftci** [comment]
@boygirl https://github.com/FormidableLabs/victory-chart/blob/b4a22dc67ac696a041448df74e2a4e84fc9e66f0/src/components/containers/victory-selection-container.js#L37 can we do something similar to what happens when `disable` prop of `VictorySelectionContainer` set `true`? It doesn't even call `SelectionHelpers.onMouseDown(evt, targetProps)`, so `evt.preventDefault();` is not called, if I understand the code correctly.

**Comment by boygirl** [comment]
But if we do that, then a selection can _never_ happen, because we need `onMouseDown` and `onMouseUp` to define the selection region. If it will work with you app, you could add a toggle that enables / disables selection, though

**Comment by ersinciftci** [comment]
Good point :) I actually tried to enable/disable the selection dynamically, but hit the same wall; in order to get onClick event, I need to disable the selection, but if I disable it, then I can never make a selection anymore.

Is it possible to fire `onClick` event if the `onMouseDown` and `onMouseUp` happens on the same cursor position?

**Comment by boygirl** [comment]
hmm... so, `onMouseDown` and `onMouseMove` set the cursor bounds, but `onMouseUp` is necessary to _clear_ them. Indeed, if you make it so that the usual `onMouseUp` event only fires when the points are different, the `onClick` event will fire. You could so this, and then have your `onClick` event do whatever you need it to _and also_ clear your coordinates. Let me make a quick example

**Comment by boygirl** [comment]
@ersinciftci check it out
https://codesandbox.io/s/xl29z88164

**Comment by boygirl** [comment]
@ersinciftci I'm going to close this issue, but let me know if that solution is incomplete for your needs. Thanks for collaborating with me on this problem. It was fun!

**Comment by ersinciftci** [comment]
@boygirl Thank you for spending time on this! So your example makes it possible to click anywhere on the chart and fire onClick event if the cursor position hasn't changed, but since its event target is `parent`, I can't get the datum of the points when they are clicked (I guess event target need to be `data`?). So I still can't get data from individual points when they are clicked. Any idea?

**Comment by boygirl** [comment]
Ah, I think I misunderstood. I was focused on event conflicts on the same event target. I will reopen this issue.

**Comment by boygirl** [comment]
Got it! You'll need to make sure that the `onMouseDown` event on the child target doesn't propagate to the parent target. Something like this.
```
events={[
  {
    childName: "all",
    target: "data",
    eventHandlers: {
      onMouseDown: (evt, props) => {
        evt.stopPropagation();
        myClickHandler(props);
      }
    }
  }
]}
```
If you still want to use `onClick` for your event, you can, but you will need to add an `onMouseDown` handler that stops propagation either way.

**Comment by boygirl** [comment]
Sure thing. Unfortunately, I don't think this makes sense as default behavior as it would necessitate adding events to any children of a chart using `VictorySelectionContainer`, and that could have some negative performance impacts for users who don't need it.

**Comment by ersinciftci** [comment]
Gotcha. In that case maybe we can add a new prop to `VictorySelectionContainer`, called `allowDataPointClick`, and set to `false` by default. But you are the boss :)

**Comment by boygirl** [comment]
Definitely something for me to think about more. In the meantime, I'm going to open an issue in `victory-docs` to add a guide or section in the FAQs about this.
