### ISSUE TITLE
'AllowDraw' on VictoryBrushContainer

### ISSUE THREAD

**Issue by gmorer** [FormidableLabs/victory#1010]
# New mini Feature

### The Problem

I'm actually using the VictoryBrushContainer and i want to disable the brush draw on new click, and want to be able to control my bush with only the drag and the resize, i ave checked your documentation and saw the `allowDrag` and the `allowResize` option but not an "`allowDraw`" 😢 

# Feature Requests

A new `allowDraw` option for the VictoryBrushContainer container.

### Description

An option that disable the creation of a "new" brush rect in the VictoryBrushContainer like `allowDrag` or `allowResize`

**Comment by boygirl** [comment]
@gmorer This actually works now: check out this example: https://codesandbox.io/s/k903m2l3mr

Please let me know if I've missed something about your requirements.

**Comment by gmorer** [comment]
Sorry you misunderstood me, what i'm trying to achieve is to disable the resize with a click outside the brush area, but to enable it just with the drag on the border even initialy (my chart start with an initial domain)

### exemple:
Bad comportment : [gyazo](https://gyazo.com/430b84ca24dce34226b3d3503fe6ff0c)
Good comportment : [gyazo](https://gyazo.com/d2d32ca4d5031b4a63c9e81ba46e280a)

**Comment by boygirl** [comment]
Oh, I see what you mean now. Thank you for providing examples. I will reopen this issue
