### ISSUE TITLE
VictoryLine changing color depending on x values

### ISSUE THREAD

**Issue by Juli0GT** [FormidableLabs/victory#1012]
Hi guys, I would like to know if there is any way that I can use a single VictoryLine that changes the stroke color depending on the x values? Or the only way to do it is creating two stack different VictoryLines with different x values?

Thanks a lot in advance.

**Comment by boygirl** [comment]
@Juli0GT you can also use a gradient for your stroke. Here are some similar examples with fills on `VictoryArea`:

https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory
https://formidable.com/open-source/victory/gallery/stream-graph/
