### ISSUE TITLE
Use Victory Voronoi container for Victory Pie

### ISSUE THREAD

**Issue by gokulramesh71** [FormidableLabs/victory#1014]
As Victory Pie cannot be wrapped under Victory Chart, can you help me in how to use Victory Voronoi Container in Victory Pie?

**Comment by boygirl** [comment]
@gokulramesh71 Unfortunately they are incompatible. VictoryVoronoiContainer relies on the idea of an x y coordinate plane that does not exist in VictoryPie

**Comment by rajatgng** [comment]
then how to implement that.

**Comment by trancongdung12** [comment]
@boygirl What I should do in Victory Pie like Victory Voronoi  ? Thanks
