### ISSUE TITLE
VictoryLegend should allow negative gutter and rowGutter

### ISSUE THREAD

**Issue by LMojica** [FormidableLabs/victory#1015]
### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
The `gutter` and `rowGutter` prop types for VictoryLegend are set to `CustomPropTypes.nonNegative`. I'm requesting that negative values be allowed for these props. The spacing between rows and columns in my legend is too large for my liking, even if I set `gutter` and `rowGutter` to 0. Setting them to a negative value does exactly what I want, but then I get errors in my console because the prop types are invalid. Can you please allow negative values for those props.

**Comment by boygirl** [comment]
Sure! I'll publish this change as a patch for `victory-core` today :)

**Comment by boygirl** [comment]
@LMojica published as `victory-core@22.1.5`. You should be able to pick it up with a fresh install of `victory`
