### ISSUE TITLE
VictoryBar - Removing X-Axis Labels From Chart

### ISSUE THREAD

**Issue by MrShedford** [FormidableLabs/victory#1016]
Hey guys, so I've been having trouble trying to figure out how to remove/hide the x-axis in VictoryBar. I want to hide it so I can replace it with my own labels (in the form of images) when rendered to the screen.

Is hiding the X-Axis currently supported by Victory Bar?

**Comment by MrShedford** [comment]
Figured it out, didn't know we could specify it with labels :) My bad!

**Comment by ron-camaron** [comment]
I'm looking to do the same. Replace xAxis labels for images. How did you do it?

**Comment by boygirl** [comment]
@ron-camaron you can make a custom label component and provide it as your `tickLabelComponent` on `VictoryAxis`. Here's a guide that should help you make a custom component: https://formidable.com/open-source/victory/guides/custom-components/#creating-new-components

As a reminder, whatever component you create will be rendered inside an `svg` tag, so if it is not an svg element, you will need to used `foreignObject`
