### ISSUE TITLE
Inconsistent VictoryScatter tooltips behavior

### ISSUE THREAD

**Issue by vmazare** [FormidableLabs/victory#1017]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of Victory
Using 0.24.0

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

This issue is reproducible in one of the gallery examples - https://formidable.com/open-source/victory/gallery/voronoi-tooltips-grouped/ . 
When hovering certain segments or areas that should trigger a tooltip, everything works as expected - the tooltips are displayed and hidden as you move the cursor around. The issue comes in when you hover a given VictoryScatter point. The tooltip is displayed correctly at all times for this case as well, but after moving the cursor away from given point and hovering the corresponding area or segment that should trigger a tooltip for it, the tooltip is not displayed, it's only displayed when you hover the actual point. 
Is this expected behavior? If yes, is there a way to customize VictoryTooltip so it always displays when you hover an eligible area or point, regardless if its point was previously hovered?

### Reproduction

Please see this gallery example for reproduction - https://formidable.com/open-source/victory/gallery/voronoi-tooltips-grouped/ . 
Steps for reproduction:
1. Hover a few random segments / areas to trigger tooltips. Make sure you don't accidentally hover any data points.
2. Select a random point and hover it. Should notice that the tooltip is displayed - expected behavior
3. Move the cursor away from said point, and hover a segment that should trigger the tooltip for the point from step 2. Should notice that tooltip for the point from step 2 is not displayed.

Thanks!

**Comment by AbhishekMandilkar** [comment]
@boygirl  I am still facing this issue 


Uploading Screen Recording 2024-06-03 at 12.39.05 PM.mov…
