### ISSUE TITLE
VictoryStack label with VictoryBar tooltip

### ISSUE THREAD

**Issue by younitee** [FormidableLabs/victory#1020]
Can either have VictoryStack with label or VictoryBar with tooltip but not both... is there a reason for this?

```javascript
<VictoryStack horizontal labels={names} labelComponent={<VictoryLabel />} >
    <VictoryBar data={lows} labels={lows => lows.y} labelComponent={<VictoryTooltip />} />
    <VictoryBar data={mediums} labels={mediums => mediums.y} labelComponent={<VictoryTooltip />} />
    <VictoryBar data={highs} labels={highs => highs.y} labelComponent={<VictoryTooltip />} />
    <VictoryBar data={alerts} labels={alerts => alerts.y} labelComponent={<VictoryTooltip />} />
</VictoryStack>
```

With this example, only the labels render at end of stack but tooltips do not.

**Comment by boygirl** [comment]
@younitee Yes, currently `VictoryStack` does not render any elements of its own, it just _modifies_ its children. So stack labels are actually labels on the top most bar. The conflict you're seeing is the `labelComponent` provided by `VictoryStack` overriding the one on `VictoryBar`. You can get around this by providing a custom `labelComponent` to `VictoryStack` that renders both a label and a tooltip. You can see an example of a custom tooltip / label here: https://formidable.com/open-source/victory/gallery/custom-tooltip-labels/

I'm going to close this issue, but please let me know if you still need help with this.
