### ISSUE TITLE
Optimize CI

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#1021]
On all victory repos

**Comment by boygirl** [comment]
From @ryan-roemer 
6, 8, 10 is a good list. We can optimize the travis build with things like:

- Remove the extra build command since `postinstall` does a full build already
- Switch to `yarn` with a `yarn.lock` file and use `yarn install --frozen-lockfile` for install speed. (The `npm install` is the slowest part of CI).

feel free to ticket out and I can help!

**Comment by ahashem** [comment]
@boygirl I can pick this issue and submit PR for it.

**Comment by boygirl** [comment]
@ahashem I'm sorry, this issue is out of date and should be closed, as this work has already been performed. My mistake.
