### ISSUE TITLE
Victory line chart zoomcontainer functionality, how to customize X axis time format (any specific time format except default in victory e.g. Apr 15, )

### ISSUE THREAD

**Issue by rsoni0809** [FormidableLabs/victory#1023]
Hello and thanks for this library. 

I am trying to implement Victory line chart VictoryZoomContainer with my customized data where time is coming as millisecond format e.g. 1523620018000. When from the documentation following line work on changing time format in x axis:
<VictoryChart width={400} height={400} scale={{x: "time"}} -- fixed time format as in Victorychart Doc: e.g. Apr 15
                       containerComponent={
                         <VictoryZoomContainer
                          dimension="x"
                          zoomDomain={this.state.zoomDomain}
                          onDomainChange={this.handleZoom}
                        />
Where scale={{x: "time"}} -- fixed time format as in Victorychart Doc: e.g. Apr 15

But I need to customize this format to from low and high range in this format: "mm-dd-yyyy HH:MM:SS"

Could you please help for above customization?

**Comment by boygirl** [comment]
@rsoni0809 You can format your times either in `VictoryAxis` using the `tickFormat` prop. It takes a function, and will receive each timestamp tick as an argument. It's then up to you to format it either using JS `Date` methods or a library like moment.js. If you need to format labels, you would do the same thing with your `labels` prop
