### ISSUE TITLE
After upgrade to 0.27.0, VictoryArea and VictoryLine no longer match up

### ISSUE THREAD

**Issue by kaiyoma** [FormidableLabs/victory#1024]
In our project, we render line graphs via a `VictoryArea` overlaid with a `VictoryLine`, like this:

![victory-0 26 1](https://user-images.githubusercontent.com/10719780/41247777-f3e474de-6d63-11e8-8699-9bbeb2859a14.png)

Without changing any of our code, if I upgrade from 0.26.1 to 0.27.0, the graphs now look like this:

![victory-0 27 0](https://user-images.githubusercontent.com/10719780/41247810-0b15a916-6d64-11e8-8c7e-620e097b25a5.png)

Here's a snippet of what we're doing in our code:

```
const sharedVictoryProps = {
  data: this.state.data,
  domain: {
    x: [this.props.startTime, this.props.endTime],
    y: [yAxisMin, yAxisMax],
  },
  height: this.props.height,
  interpolation: CURVE_TYPES[curveType],
  padding: 0,
  standalone: false,
  theme: VICTORY_THEME,
  width: this.props.containerWidth - 1,
  x: 'timestamp',
  y: 'value',
};

...

<VictoryArea
  {...sharedVictoryProps}
/>
<VictoryLine
  {...sharedVictoryProps}
/>

**Comment by boygirl** [comment]
Yikes! I'll take a look today

**Comment by boygirl** [comment]
Hi there, I just published a patch to `victory-core` that should correct this issue. You can pick it up with a fresh install of victory. The problem was occurring because we were forcing `VictoryArea`'s domain to include zero even when an explicit domain was provided.
