### ISSUE TITLE
Horizontal Bar Chart Axis Alignment/Padding

### ISSUE THREAD

**Issue by Ericky14** [FormidableLabs/victory#1027]
In a horizontal bar chart, is it possible to extend the bars in such a way that the left-most axis tick text is aligned right and the right-most tick text is aligned left?

<img width="748" alt="screen shot 2018-06-12 at 2 16 12 pm" src="https://user-images.githubusercontent.com/21248862/41308967-5461ce6e-6e4b-11e8-9351-6a54345f55f2.png">

What I mean is in this case have the 0 and the 70 completely over the bar and not half-way.

**Comment by boygirl** [comment]
@Ericky14 you can use functional styles on `VictoryAxis` like `style={{ tickLabels: { textAnchor: (tick, index, ticks) => index === ticks.length - 1 ? "end" : "start" } }}`

**Comment by Ericky14** [comment]
@boygirl Oh cool, didn't know ```text-anchor```, not much experience with svgs haha.
Also, that function doesn't quite work because ```ticks``` is undefined.
