### ISSUE TITLE
Aligning bars in between axes?

### ISSUE THREAD

**Issue by fwielstra** [FormidableLabs/victory#1028]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a date range bar chart (e.g. monthly data), and I'd like to be able to align the bars in between two ticks, instead of right alongside it. Here's an image showing how it currently looks:

![image](https://i.imgur.com/Cgv7hD7.png)

I'd like the bars to appear right in between the two axes. I've looked into domain padding, styles, etc and googled around a lot but it looks like I can only change the alignment around the vertical ticks themselves.

Or is there a way to style the underlying SVG? If so, is there an example of that somewhere?

**Comment by boygirl** [comment]
@fwielstra This issue has made me realize that `transforms` supplied to data components were not being applied to dataComponents correctly. I just released a fix. If you're able to update to the latest version of Victory and do a fresh npm install you should be able to pick up the patch release `victory-core@24.0.1`. Then you can do something like this:
```
<VictoryBar
  dataComponent={<Bar transform="translate(10)"/>}
   ...
/>
```

If you're not able to use the latest version of Victory for some reason, you can do something slightly more complicated:

```
class MyBar extends React.Component {
  render() {
    return <Bar {...this.props} x={this.props.x + 10}/>
  }
}

...
<VictoryBar
  dataComponent={<myBar/>}
  ...
/>
```

**Comment by fwielstra** [comment]
Hmm, I have the latest version now but that transform method doesn't seem to work. The subclass with a custom x parameter works great though, thanks!
