### ISSUE TITLE
VictoryLegend Weird Width/Layout

### ISSUE THREAD

**Issue by Ericky14** [FormidableLabs/victory#1032]
# Bugs and Questions

### Checklist

* [v] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [v] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [v] I am using the latest version of Victory

* [v] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using VictoryLegend to generate a legends component, the width of each legends item does not seem to get calculated correctly. Also, the text does not break into a new line on overflow.

### Reproduction

Use VictoryLegend.

```
            <VictoryLegend
                orientation='horizontal'
                gutter={20}
                data={data}
                x={0}
                y={aspectHeight - 25}
            />
```
```
data=[
  { name: 'Critical', symbol: { fill: color, type: 'square' }},
  { name: 'High', symbol: { fill: color, type: 'square' }},
  { name: 'Medium', symbol: { fill: color, type: 'square' }},
  { name: 'Low', symbol: { fill: color, type: 'square' }}
]
```

<img width="620" alt="screen shot 2018-06-25 at 6 32 32 pm" src="https://user-images.githubusercontent.com/21248862/41879125-33747214-78a6-11e8-87cd-814881a1d979.png">
<img width="696" alt="screen shot 2018-06-25 at 6 32 55 pm" src="https://user-images.githubusercontent.com/21248862/41879126-338450f8-78a6-11e8-98a5-2383c2a1b4c1.png">

**Comment by boygirl** [comment]
@Ericky14 

1) VictoryLegend does not automatically wrap on overflow, but you can specify `itemsPerRow` to get it to render several lines of items. How this works is that it will render `itemsPerRow` items in a row, and then render more in a second row and so on. 

2) Unfortunately Victory _approximates_ rather than measures test sizes for performance reasons. This means that the element widths can be a bit off.

**Comment by Ericky14** [comment]
@boygirl 
I was able to figure out a really good solution, thanks. :)

```
    renderChartLegend = () => {
        const { aspectHeight, chartLegend, values } = this.props;
        const { chartLegendHeight } = this.state;

        chartLegend.push(...chartLegend);
        chartLegend.push(...chartLegend);

        return (
            <foreignObject
                ref={this.setChartLegendContainerRef}
                y={280 - chartLegendHeight}>
                <Flex justifyContent='center'>
                    <ChartLegend
                        noDataFound={!values.length}
                        legends={chartLegend}
                        mx='50px'
                        onClick={this.onLegendClick}
                        seriesColors={this.props.colors}
                        width='94%' />
                </Flex>
            </foreignObject>
        );
    }

    setChartLegendContainerRef = (ref) => {
        if (ref) {
            const chartLegendRef = ref.firstChild.firstChild;

            if (chartLegendRef) {
                const chartLegendHeight = chartLegendRef.getBoundingClientRect().height;

                this.setState({ chartLegendHeight });
            }
        }
    }

...
 
    render () {
        const padding = {
            bottom: defaultPadding + this.state.chartLegendHeight,
            left: defaultPadding,
            right: defaultPadding,
            top: defaultPadding
        };
...
                        <Chart
                                domainPadding={{ x: 30 }}
                                padding={padding}
...
```
