### ISSUE TITLE
Typescript Support: maintain our own typings

### ISSUE THREAD

**Issue by StraightOuttaCrompton** [FormidableLabs/victory#1033]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using typescript and importing VictoryZoomContainer and VictoryBrushContainer I get the following errors 

[ts] Module '"victory"' has no exported member 'VictoryZoomContainer'
[ts] Module '"victory"' has no exported member 'VictoryBrushContainer'

### Reproduction
I tried reproducing the issue in sandbox but the error only sometimes appears. I am not sure why, but here is the sandbox anyway
https://codesandbox.io/s/94jn2qzylo

I have also created a git repo which contains the issue.
https://github.com/StraightOuttaCrompton/victory-typescript-example

Steps to replicate -
npm install
npm start

Should produce a compiler error in App.tsx stating "Module '"victory"' has no exported member 'VictoryZoomContainer'."

**Comment by boygirl** [comment]
@StraightOuttaCrompton I'm sorry, we don't publish typescript typings for Victory, but instead rely on the community. I would guess that the typings are out of date. I will change the title of this issue.

**Comment by StraightOuttaCrompton** [comment]
Is there someone in the community I can contact about it? Or is it possible I can try and resolve it myself?

**Comment by boygirl** [comment]
You could reach out to the contributors or make a PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/victory/index.d.ts

We will likely bring these types under our maintenance umbrella in the coming months. Sorry for the trouble in the meantime.

**Comment by StraightOuttaCrompton** [comment]
Ok, that's brilliant. Thank you for your hard work!

**Comment by redixhumayun** [comment]
I am facing the same issue with VictoryVoronoiContainer and VictoryTooltip. 

I tried working around this by defining the typings in my local index.d.ts file for @types/victory. But, that doesn't seem to fix the issue. Is there a workaround to this or do I simply have to wait for the typings file to be updated?

**Comment by StraightOuttaCrompton** [comment]
You'll have to make a pull request as @boygirl has suggested and edit the typings to make it work or wait until they start maintaining their own typings. I am planning on making a pull request at some point if I get time.

**Comment by bbshih** [comment]
@redixhumayun I've been pushing some PRs to update the types to the DefinitelyTyped repo, including a full VictoryTooltip interface that it was missing. There are a lot of issues in the current types that I've had to fix, the biggest I've encountered was ToolTips missing and I think VictoryTheme type is completely out of date.

**Comment by StraightOuttaCrompton** [comment]
This PR has solved the issue I was originally having 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27048

**Comment by SaphuA** [comment]
I wouldn't mind investing some time creating / updating typings while I'm using Victory. But I will only do this if the typings are to be maintained in this repo. What is the stance of Formidable on this matter?

**Comment by JayTurn** [comment]
I've recently run into this issue attempting to use VictoryCandlestick which appears to be missing from the DefinitelyTyped definitions.

@boygirl Before I consider writing a PR, is anyone currently working on this?

**Comment by boygirl** [comment]
@JayTurn sorry for the delay. This is not currently in progress

**Comment by mAAdhaTTah** [comment]
I made a couple of upstream changes to the types as well, but I will also mention that Victory's cloneElement heavy approach makes typing difficult. Props that take a component "instance" rather than just the component error on the missing props that are provided by Victory later. I'm open to upstreaming any fixes that solve this but I'm not sure how to approach besides just making everything optional, which doesn't feel right. Any ideas?

**Comment by JeffBaumgardt** [comment]
I know this is backlogged but it has also been over a year since update. I have made an addition to @types/victory to add in missing props but they have also pointed out that victory has started exporting types. So I was wondering what the overall status is of type in victory.

**Comment by boygirl** [comment]
@JeffBaumgardt apologies. This issue should be closed now. We recently completed a thorough audit of our types. I'm sure there are still places they could be improved, but they should be pretty complete at this point.
