### ISSUE TITLE
VictoryZoomContainer passes scroll and pinch events to browser

### ISSUE THREAD

**Issue by fwielstra** [FormidableLabs/victory#1034]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a VictoryZoomContainer with the following properties

    const zoomDomain = // ...
    <VictoryZoomContainer allowPan allowZoom={false} responsive={false} />

(additional details: it's combined with a `VictoryVoronoiContainer` using `createContainer`; horizontal zoomDomain is calculated based on available horizontal space, e.g. ~25% of the data if only 25% of the space is available. Additional detail: I've tried it in the iOS emulator, don't know / believe the real device's behaviour is different.)

What I'm noticing on mobile (iOS) is that when panning horizontally, the entire screen tries to move left / right (causing a bounce effect in my case). When enabling zoom, the pinch motion causes both the whole page and the chart to zoom in / out.

Is there a way to prevent these touch events from escaping the chart?

https://github.com/FormidableLabs/victory/issues/622 may be related, which seems to explicitly allow the events to bubble out if allowZoom is false.

**Comment by boygirl** [comment]
@fwielstra Thank you for this issue. Can you help me narrow it down a bit?
- Are you seeing this issue without `createContainter` + `VictoryVoronoiContainer`? 
- Does this only happen when `allowZoom={false}`?
- Does this only happen with `responsive={false}`?

**Comment by fwielstra** [comment]
Hi @boygirl , thank you for your reply and I apologise for not replying sooner, I was er, distracted by other work for a while.

I've tried to reproduce this issue again and I couldn't; I don't know if I've changed something in the chart (like what you've suggested) or the page itself, but I can't reproduce the issue anymore and things work as they should. Thank you for your reply!
