### ISSUE TITLE
VictoryAxis not plotting tick marker [Help Wanted / Potential Feature]

### ISSUE THREAD

**Issue by therise3107** [FormidableLabs/victory#1035]
```
  "victory": "^0.25.6",
  "node": "8.9.4",
  "npm": "5.7.1",
  
```
I'm trying to render area graph grouped with `VictoryGroup`. Here is my x-axis code with SS of my current graph.
```
    <VictoryAxis
      tickFormat={_.map(data, o => _.pick(o, 'day').day)}
      style={{
        axis: { stroke: colors.graph.axis },
        tickLabels: { ...labelStyles }
      }}
    />
```

<img width="700" alt="screen shot 2018-07-02 at 4 09 55 pm" src="https://user-images.githubusercontent.com/2356810/42159803-ac4c30a2-7e12-11e8-8472-5f4a171f75d1.png">

I want to render above graph similar to this one 
<img width="815" alt="screen shot 2018-07-02 at 4 14 07 pm" src="https://user-images.githubusercontent.com/2356810/42159984-4806d63c-7e13-11e8-891b-77b4c64ab23f.png">

Please let me know what I'm missing. Thanks in advance.

**Comment by boygirl** [comment]
@therise3107 try adding a style like this:

```
style={{
    axis: { stroke: colors.graph.axis },
    tickLabels: { ...labelStyles },
    ticks: { stroke: colors.graph.axis , size: 5 }
}}
```
