### ISSUE TITLE
Can't scroll page on touch device

### ISSUE THREAD

**Issue by jadus** [FormidableLabs/victory#1037]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

On a touch device it is not possible to scroll the page if you touch a victory element

### Reproduction

The gallery is a good example :
https://formidable.com/open-source/victory/gallery/
Just try to scroll the page on a smartphone

**Comment by boygirl** [comment]
@jadus I'm not able to reproduce this issue. Some elements in the gallery do have scroll events enabled (like the brush and zoom example), and these will capture the scroll event rather than scrolling the page. I haven't seen this behavior happen with other chart elements, though.

**Comment by jadus** [comment]
I've added <svg viewBox="0 0 400 400"> around my chart and standalone={false} width={400} height={400} in my component and it solves my problem, thanks.

**Comment by sinoridha** [comment]
I have faced the same issue. My solution for it is wrap the chart component with Svg. It will make your cart as svg, but it will reduce preformance of antimation process.

```
import Svg from 'react-native-svg';

<Svg width='100%' height={222}>
    <VictoryChart
        standalone={false}>
            <VictoryBar />
    </VictoryChart>
</Svg>
```

**Comment by yeomann** [comment]
this is still issue, atleast on android. I just test and implemented on IOS using simulator. i can't click using mouse and scroll but on Android real device, i can't scroll when i click on `victory-bar` component

**Comment by mpcen** [comment]
> this is still issue, atleast on android. I just test and implemented on IOS using simulator. i can't click using mouse and scroll but on Android real device, i can't scroll when i click on `victory-bar` component
> 
> UPDATE: i just did `<View pointerEvents="none">` around the victory component. all good 😄

After 3 hours, you have saved me! Thank you

**Comment by afacar** [comment]
> this is still issue, atleast on android. I just test and implemented on IOS using simulator. i can't click using mouse and scroll but on Android real device, i can't scroll when i click on `victory-bar` component
> 
> UPDATE: i just did `<View pointerEvents="none">` around the victory component. all good 😄

After many hours, you saved my charts :> Thank you

**Comment by nighto** [comment]
Where does this <View> components come from?

> Attempted import error: 'View' is not exported from 'victory'.

**Comment by nighto** [comment]
[Ok, seems to be something related to react-native](https://facebook.github.io/react-native/docs/view). But the issue affects normal React on Safari browser, without using react-native.

**Comment by nighto** [comment]
Ok, for future readers who are **not** using react-native, the solution is similar to what @sinoridha described but with native svg wrapper:

```jsx
<svg width='100%' height='50%'>
    <VictoryChart standalone={false} />
</svg>
```

**Comment by narinluangrath** [comment]
👋 Hi all,

In case people are looking at this issue for reference, the reason this happens is because `<VictoryContainer />` (which renders the `<div>` containing the chart) has a style prop of 
`{ pointerEvents: 'none', touchAction: 'none' }`. This is there for the reason @boygirl mentioned above. 

If you don't want this behavior, your can override it by providing your own `containerComponent`
```
<VictoryChart
  containerComponent={
    <VictoryContainer
      style={{
        pointerEvents: "auto",
        userSelect: "auto",
        touchAction: "auto"
      }}
    />
  }
>
  <VictoryLine />
</VictoryChart>
```

**Comment by calvinwoo** [comment]
The comment above led me in the right direction for my use case. The requirements for my mobile web app:
• users should be able to scroll if they touch the chart
• users should be able to touch the chart and interact with `VictoryVoronoiContainer`

Omitting the style overrides, except for `touch-action`, did the trick.

```
<VictoryChart
  containerComponent={
    <VictoryVoronoiContainer
      style={{
        touchAction: "auto"
      }}
    />
  }
>
```

**Comment by LouisLoiseau** [comment]
It seems like touchAction is not doing on my side, on the latest version. And any of the above solutions works for me.

**Comment by chriszrc** [comment]
> 👋 Hi all,
> 
> In case people are looking at this issue for reference, the reason this happens is because `<VictoryContainer />` (which renders the `<div>` containing the chart) has a style prop of `{ pointerEvents: 'none', touchAction: 'none' }`. This is there for the reason @boygirl mentioned above.
> 
> If you don't want this behavior, your can override it by providing your own `containerComponent`
> 
> ```
> <VictoryChart
>   containerComponent={
>     <VictoryContainer
>       style={{
>         pointerEvents: "auto",
>         userSelect: "auto",
>         touchAction: "auto"
>       }}
>     />
>   }
> >
>   <VictoryLine />
> </VictoryChart>
> ```

@boygirl I don't understand why this issue was closed. If the only containers that need to disable the pointer events are the voroni, zoom, etc., then why is this still present on the default container used by all the other charts? We need sensible defaults, not charts that don't work out of the box on mobile for the majority of people and time spent digging in github-
