### ISSUE TITLE
Toggle victory lines with legend

### ISSUE THREAD

**Issue by devth** [FormidableLabs/victory#1038]
# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I'd like to toggle the visibility of victory lines by pressing on the corresponding legend item. Would be awesome if this was a built in option but also curious how to build without it being natively supported. Trying specifying `events` on a `VictoryLegend` but nothing seems to be firing. I happen to be using Victory Native and tried `onPress`, `onPressIn` and `onClick`.

```js
                events={[
                  {
                    target: 'data',
                    eventHandlers: {
                      onPressIn: () => {
                        console.log('clicked');
                      }
                    }
                  }
                ]}
```

**Comment by boygirl** [comment]
@devth if you're using `VictoryLegend` as a child of `VictoryChart` you can add your events prop as a prop on `VictoryChart` and then address children of `VictoryChart` by name, and share events between children. `VictoryChart` uses `VictorySharedEvents` to do this. You can read about it here: https://formidable.com/open-source/victory/docs/victory-shared-events/. 

I'm confused as to why events on `VictoryLegend` wouldn't fire. The code you show looks correct, and should attach events to the _symbol_ on your legend (use `target: "labels"` to attach events to the text). 

I'm going to close this issue, as I don't think it's appropriate as a built in feature for `VictoryLegend`. If your issue with events in Victory Native persists, would you mind reopening your issue here: https://github.com/FormidableLabs/victory-native/issues ?

Thanks!

**Comment by devth** [comment]
Yep. Thanks!

**Comment by Morasta** [comment]
@devth : I'm currently working on something that sounds nearly identical. Did you end up with a solution and if so, do you have an example you'd be willing/able to share?

**Comment by devth** [comment]
No, I ended up building my own legend outside of Victory charts.

**Comment by jotak** [comment]
For the record and future people coming to this page, here's an implementation of interactive legend (typescript ; tested with victory 33.0.6). It's using both events and react state (for persisting show/hide) :

```typescript
import * as React from 'react';
import { VictoryArea, VictoryChart, VictoryLegend, VictoryAxis } from 'victory';

type DataPoint = {
  x: number | Date;
  y: number;
};

type Line = {
  name: string;
  color?: string;
  datapoints: DataPoint[];
};

const toVictoryData = (line: Line) => {
  return line.datapoints.map(dp => ({
    name: line.name,
    x: dp.x,
    y: dp.y
  }));
};

const toVictoryLegend = (line: Line) => {
  return line.color ? {
    name: line.name,
    symbol: {
      fill: line.color
    }
  } : { name: line.name };
};

type State = {
  hiddenSeries: Set<number>;
};

export default class InteractiveLegend extends React.Component<{}, State> {
  series: Line[];

  constructor(props: {}) {
    super(props);
    this.state = { hiddenSeries: new Set() };
    this.series = [
      {
        name: 'cats',
        color: '#c33',
        datapoints: [{ x: 0, y: 5 }, { x: 1, y: 8 }, { x: 2, y: 5 }]
      },
      {
        name: 'dogs',
        color: '#3c3',
        datapoints: [{ x: 0, y: 2 }, { x: 1, y: 4 }, { x: 2, y: 6 }]
      },
      {
        name: 'birds',
        color: '#33c',
        datapoints: [{ x: 0, y: 3 }, { x: 1, y: 1 }, { x: 2, y: 3 }]
      }
    ];
  }

  private buildEvents() {
    return this.series.map((_, idx) => {
      return {
        childName: ['legend'],
        target: ['data', 'labels'],
        eventKey: String(idx),
        eventHandlers: {
          onClick: () => {
            return [
              {
                childName: ['area-' + idx],
                target: 'data',
                eventKey: 'all',
                mutation: () => {
                  if (!this.state.hiddenSeries.delete(idx)) {
                    // Was not already hidden => add to set
                    this.state.hiddenSeries.add(idx);
                  }
                  this.setState({ hiddenSeries: new Set(this.state.hiddenSeries) });
                  return null;
                }
              }
            ];
          },
          onMouseOver: () => {
            return [
              {
                childName: ['area-' + idx],
                target: 'data',
                eventKey: 'all',
                mutation: props => {
                  return {
                    style: { ...props.style, strokeWidth: 4, fillOpacity: 0.5 }
                  };
                }
              }
            ];
          },
          onMouseOut: () => {
            return [
              {
                childName: ['area-' + idx],
                target: 'data',
                eventKey: 'all',
                mutation: () => {
                  return null;
                }
              }
            ];
          }
        }
      };
    });
  }

  render() {
    return (
      <div>
        <VictoryChart
          height={200}
          events={this.buildEvents()}
        >
          <VictoryAxis />
          {this.series.map((s, idx) => {
            if (this.state.hiddenSeries.has(idx)) {
              return undefined;
            }
            return (
              <VictoryArea
                key={'area-' + idx}
                name={'area-' + idx}
                data={toVictoryData(s)}
                style={{
                  data: {
                    fill: s.color,
                    fillOpacity: 0.2,
                    stroke: s.color,
                    strokeWidth: 2
                  }
                }}
              />
            );
          })}
          <VictoryLegend
            name={'legend'}
            data={this.series.map((s, idx) => {
              const item = toVictoryLegend(s);
              if (this.state.hiddenSeries.has(idx)) {
                return { ...item, symbol: { fill: '999' } };
              }
              return item;
            })}
            height={90}
          />
        </VictoryChart>
      </div>
    );
  }
}

```

**Comment by BradleyJrichardson** [comment]
this really should a built in feature

**Comment by CoderDark** [comment]
> # Feature Requests
> ### Checklist
> * [x]  I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist
> * [x]  I've searched open issues to make sure I'm not opening a duplicate issue
> 
> ### Description
> I'd like to toggle the visibility of victory lines by pressing on the corresponding legend item. Would be awesome if this was a built in option but also curious how to build without it being natively supported. Trying specifying `events` on a `VictoryLegend` but nothing seems to be firing. I happen to be using Victory Native and tried `onPress`, `onPressIn` and `onClick`.
> 
> ```js
>                 events={[
>                   {
>                     target: 'data',
>                     eventHandlers: {
>                       onPressIn: () => {
>                         console.log('clicked');
>                       }
>                     }
>                   }
>                 ]}
> ```

Yep I still can not get onPress or onPressIn to work on legends...
