### ISSUE TITLE
dotum of two charts

### ISSUE THREAD

**Issue by NugzarGaguliya** [FormidableLabs/victory#1039]
# Bugs and Questions

### Checklist

* [ + ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [ + ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ + ] I am using the latest version of Victory

* [ + ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Can not get dotum from two charts

### Reproduction

https://codesandbox.io/s/1mp39w9o7

# Feature Requests

### Checklist

* [ + ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ + ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

This is example of flyoutComponent that I use
https://gist.github.com/NugzarGaguliya/add3b1f3416f4dddb7f7da8766f6279a

this is for one chart
![one](https://files.gitter.im/FormidableLabs/victory/4a2A/image.png)

this is for two charts
![two](https://files.gitter.im/FormidableLabs/victory/GvmI/image.png)

what I need to implement
![need](https://files.gitter.im/FormidableLabs/victory/ouAJ/image.png)

**Comment by boygirl** [comment]
@NugzarGaguliya For this you will need to make a custom `labelComponent`. You can use `VictoryVoronoiContainer` to get the two points closest to the `x` position of your mouse. Here's an example of multi-point tooltip labels https://formidable.com/open-source/victory/gallery/multipoint-tooltip-labels/
This guide should help you get started with making a custom label component: https://formidable.com/open-source/victory/guides/custom-components/

Given what your flyout looks like, you might also have some luck using `VictoryLegend` as your label component.

**Comment by NugzarGaguliya** [comment]
Thanks

**Comment by jaikantshikray** [comment]
how we can get the index of first item returned from labels callback in datum object so i can show the date at the top of tooltip like the above screenshot
