### ISSUE TITLE
Capture onClick / onPress anywhere in a VictoryChart

### ISSUE THREAD

**Issue by devth** [FormidableLabs/victory#1040]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Simple question but I couldn't find an answer in the docs: how can I capture an `onClick` / `onPress` anywhere inside a `VictoryChart`? Struggling with putting `events` all over the place.

**Comment by boygirl** [comment]
@devth If you want your `onClick` event to trigger from anywhere on the chart, you should attach you event to the "parent" target. You can read more about the events prop here: https://formidable.com/open-source/victory/docs/common-props/#events. I'm going to close this issue, but please let me know if you are still stuck.

**Comment by devth** [comment]
@boygirl I confirmed this works on web but not on victory-native with `onPress` or `onPressIn`. Any ideas?

**Comment by devth** [comment]
Might be related to https://github.com/FormidableLabs/victory-native/issues/212

**Comment by gezichenshan** [comment]
onPressIn cannot work on "victory-native": "^35.0.1",
