### ISSUE TITLE
May I know how to do the victory line chart in real time?

### ISSUE THREAD

**Issue by JohnHour89** [FormidableLabs/victory#1043]
Hi, may I know how to do the line chart in real time? Below is the code:

`<div className="column">
          <div className="panel">
            <div className="chart-header">Temperature</div>
              <VictoryChart
                theme={VictoryTheme.material}
                width={1500}
              >
                <VictoryLine
                  style={{
                    data: { stroke: "#c43a31" },
                    parent: { border: "1px solid #ccc"}
                  }}
                  labelComponent={<VictoryTooltip />} 
                  data={temperatureData}
                  x="timestamp"
                  y="temperature"
                  labels={p => `${p.timestamp} $${p.temperature}`} 
                />
              </VictoryChart>
          </div>
        </div>`

Thank you.

**Comment by boygirl** [comment]
@JohnHour89 your code looks correct. Your chart should update as `temperatureData` changes.

**Comment by JohnHour89** [comment]
@boygirl Hi, it seems correct but the problem what I want is the graph data it will automatically update itself in the page, not like need to refresh the page then the graph data just can be update.
