### ISSUE TITLE
VictoryCursorContainer   cursorComponent Line color doesn't change

### ISSUE THREAD

**Issue by yogeshR5** [FormidableLabs/victory#1044]
# Bugs and Questions
VictoryCursorContainer cursorComponent Line color doesn't change and if x-axis value is string does not display proper given input data.

I attached screenshot link for without Line color but x-Axis value doesn't control it. 
https://drive.google.com/a/ewallsolutions.com/file/d/10oqP8EN3PIiu1KCxFzcLHPYFKmBJQ3nR/view?usp=drivesdk

I attached screenshot link for Line color but x-Axis value doesn't control it. 

https://drive.google.com/a/ewallsolutions.com/file/d/14uw1Q8CA6b3lKEaSN9n1Z5IZHmow209_/view?usp=drivesdk

### Checklist

* [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of Victory

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

using these modules

  "react-native": "0.55.4",
  "victory-native": "0.18.0",
  "react-native-svg": "^6.4.1",

my code is

<VictoryChart
                  padding={{ top: 23, bottom: 53, left: 40, right: 70 }}
                  height={320}
                  containerComponent={
                    <VictoryCursorContainer
                      cursorLabel={finalData =>
                        `${finalData.x}, ${finalData.y.toFixed(2)}`
                      }
                      cursorComponent={
                        <Line style={{ stroke: "red", strokeWidth: 3 }} />
                      }
                      cursorLabelComponent={
                        <VictoryLabel style={{ stroke: "#fff" }} />
                      }
                    />
                  }
                >

VictoryCursorContainer cursorComponent Line color doesn't change and if x-axis value is string does not display proper given input data.

I attached screenshot link for without Line color but x-Axis value doesn't control it. 
https://drive.google.com/a/ewallsolutions.com/file/d/10oqP8EN3PIiu1KCxFzcLHPYFKmBJQ3nR/view?usp=drivesdk

I attached screenshot link for Line color but x-Axis value doesn't control it. 

https://drive.google.com/a/ewallsolutions.com/file/d/14uw1Q8CA6b3lKEaSN9n1Z5IZHmow209_/view?usp=drivesdk

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

VictoryCursorContainer cursorComponent Line color doesn't change and if x-axis value is string does not display proper given input data.
I attached screenshot link for without Line color but x-Axis value doesn't control it. 
https://drive.google.com/a/ewallsolutions.com/file/d/10oqP8EN3PIiu1KCxFzcLHPYFKmBJQ3nR/view?usp=drivesdk

I attached screenshot link for Line color but x-Axis value doesn't control it. 

https://drive.google.com/a/ewallsolutions.com/file/d/14uw1Q8CA6b3lKEaSN9n1Z5IZHmow209_/view?usp=drivesdk

# Feature Requests

VictoryCursorContainer cursorComponent Line color doesn't change and if x-axis value is string does not display proper given input data.

I attached screenshot link for without Line color but x-Axis value doesn't control it. 
https://drive.google.com/a/ewallsolutions.com/file/d/10oqP8EN3PIiu1KCxFzcLHPYFKmBJQ3nR/view?usp=drivesdk

I attached screenshot link for Line color but x-Axis value doesn't control it. 

https://drive.google.com/a/ewallsolutions.com/file/d/14uw1Q8CA6b3lKEaSN9n1Z5IZHmow209_/view?usp=drivesdk

### Checklist

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

VictoryCursorContainer cursorComponent Line color doesn't change and if x-axis value is string does not display proper given input data.

I want change Line color and x-Axis proper has given input data to display

VictoryCursorContainer cursorComponent Line color doesn't change and if x-axis value is string does not display proper given input data.

I attached screenshot link for without Line color but x-Axis value doesn't control it. 
https://drive.google.com/a/ewallsolutions.com/file/d/10oqP8EN3PIiu1KCxFzcLHPYFKmBJQ3nR/view?usp=drivesdk

I attached screenshot link for Line color but x-Axis value doesn't control it. 

https://drive.google.com/a/ewallsolutions.com/file/d/14uw1Q8CA6b3lKEaSN9n1Z5IZHmow209_/view?usp=drivesdk

Please describe the feature you're requesting in detail.

  "react-native": "0.55.4",
  "victory-native": "0.18.0",
  "react-native-svg": "^6.4.1",

VictoryCursorContainer cursorComponent Line color doesn't change and if x-axis value is string does not display proper given input data.

I attached screenshot link for without Line color but x-Axis value doesn't control it. 
https://drive.google.com/a/ewallsolutions.com/file/d/10oqP8EN3PIiu1KCxFzcLHPYFKmBJQ3nR/view?usp=drivesdk

I attached screenshot link for Line color but x-Axis value doesn't control it. 

https://drive.google.com/a/ewallsolutions.com/file/d/14uw1Q8CA6b3lKEaSN9n1Z5IZHmow209_/view?usp=drivesdk

**Comment by boygirl** [comment]
@yogeshR5 VictoryCursorContainer will translate your mouse position into a data position. If you're using string data, Victory will convert your strings into an integer string map like `{1: "cat", 2: "dog"...}` and your domain will end up looking like `[1, 2]` or something. There isn't a way for your mouse position to be converted _back into string values_. Think about it this way, if your mouse position is half way  between "cat" and "dog", its value will be `1.5`. Victory wont know how to interpolate between "cat" and "dog". Even if your strings are something like "1" and "2", Victory won't assume that you want them converted to numbers if you've given them as strings. What you _can_ do is to add a `cursorLabel` function to `VictoryCursorContainer`. The function will be called with the data coordinates corresponding to your mouse position, and you can use that to return the appropriate label.

As for the line color: you should be able to provide a style to your `Line` component. It should be given like` cursorComponent={<Line style={{ stroke: "red" }}/>}`.  I'm going to close this issue now, but please let me know if that doesn't help.

Please note that it is very difficult to help when you don't provide any code samples with your issues. I will be able to provide better, faster help when you include code in your issues. The very best way to get help is by adding a reproduction in codesandbox. You can fork this sandbox to get started: https://codesandbox.io/s/kkv2jj2803
