### ISSUE TITLE
VictoryStack error with time series data

### ISSUE THREAD

**Issue by olivia-leach** [FormidableLabs/victory#1046]
### The Problem

`VictoryStack` appears to be mishandling time data - the error thrown is `Error: <path> attribute d: Expected number, "M NaN, 100\n      A…".`

I believe this is a new error, although I'm not sure when it broke. I was able to do this successfully in previous versions.

### Reproduction

https://codesandbox.io/s/pmj6lrz0w7

3 examples:
1. Time series with VictoryStack (broken)
2. Time series without VictoryStack (works)
3. Numerical data with VictoryStack (works)

Thanks for the great library!

**Comment by boygirl** [comment]
@olivia-leach sorry for the delay. I haven't been able to recreate this issue with time series data in the format:
```js
 data={[
  { x: new Date(1980, 1, 1), y: 3 },
  { x: new Date(1990, 1, 1), y: 1 },
 ...
]}
```

I think this may be an issue with formatting dates in `moment`. If the result is a string rather than a date object, that would be incompatible with the `time` scale.

**Comment by tkiethanom** [comment]
This seems like its still an issue with 30.4.1. Updated the previous code sandbox with the latest Victory version.

https://codesandbox.io/s/0ypwnjlz6n

**Comment by BrunoQuaresma** [comment]
I'm facing this issue in the latest version:

```
<VictoryChart scale={{ x: "time" }} height="150">
  <VictoryStack>
    <VictoryBar
      data={[
        { x: new Date('01/20/2020'), y: 34 },
        { x: new Date('01/19/2020'), y: 22 },
        { x: new Date('01/18/2020'), y: 52 }
      ]}
    />
    <VictoryBar
      data={[
        { x: new Date('01/20/2020'), y: 23 },
        { x: new Date('01/19/2020'), y: 12 },
        { x: new Date('01/18/2020'), y: 72 }
      ]}
    />
    <VictoryBar
      data={[
        { x: new Date('01/20/2020'), y: 32 },
        { x: new Date('01/19/2020'), y: 42 },
        { x: new Date('01/18/2020'), y: 91 }
      ]}
    />
  </VictoryStack>
</VictoryChart>
```

https://codesandbox.io/s/basic-victory-example-wovjd?fontsize=14&hidenavigation=1&theme=dark

**Comment by BrunoQuaresma** [comment]
I found the issue, to fix it you have to sort the data by the x axis. I did something like:

```
return data.sort((a, b) => {
      return +a.x - +b.x;
    });
```
