### ISSUE TITLE
X and Y datum properties are undefined in Label Formatting for custom x/y data accessors

### ISSUE THREAD

**Issue by wilkesybear** [FormidableLabs/victory#1047]
### The Problem

For series that define the X and Y data accessor properties to be attributes other than `'x'` and `'y'`, newer versions of Victory are no longer setting the `x` and `y` props on datum objects when passed into the `labels` formatting function *for newer releases of Victory (0.27+)*. 

Reproduction: https://codesandbox.io/s/9yzv32rj3r

On the first Bar series, the Y prop is `yy`, but the `labels` function is globally defined as `d => d.y`. You'll see an empty tooltip for the bottom bar's tooltip, but filled-in values for both.

The same is observable whether the `labels` & `labelComponent` is defined within the VictoryVoronoiContainer (as in the example) or if moved into each VictoryBar component

If you downgrade Victory from 0.27.2 to <0.27.0, this will work -- the `datum` object will always have filled in the `x`/`y` prop with the correct value, regardless of the data accessor name (although, the offset of the tooltip is incorrect on the stacked bars, as was fixed in 0.27.1)

### Reproduction

Reproduction (version 0.27.2): https://codesandbox.io/s/9yzv32rj3r

Same code, version 0.26.1, tooltip values working: https://codesandbox.io/s/9j98925jq4

**Comment by boygirl** [comment]
@wilkesybear Victory has moved to only adding `_x` and `_y` to user data so as to not wipe out the more commonly user-supplied `x` and `y` attributes. If you change your label function to `d => d._y` you should get the desired behavior. I apologize for the confusion. I will add an issue to our docs repo to make this clearer.

**Comment by wilkesybear** [comment]
One thing here that I'm struggling with is that the `_x` value is not necessarily the same value of the x that was passed in. Looking back at my example, it seems that `_x` inherits the _index_ of which x tick that value is for. So, if my x values were dates, I would instead get 1, 2, 3, ... for the `_x`, rather than an actual date value. This matters because formatting a tooltip may require the real x value (e.g. `Date: 01/01/2018`). With this new scheme, you'd need some extra LUT to map your from the new `_x` to the original. This feels like a step backward from the older versions, from my standpoint! If there's a better way to derive the actual `x` value, let me know! Thank you again
