### ISSUE TITLE
Support `colorScale` for `VictoryChart`

### ISSUE THREAD

**Issue by jacargentina** [FormidableLabs/victory#1048]
Demo is https://codesandbox.io/s/kxq1ypo1ov

The original code does not contains any `<VictoryGroup />`: it was added to make lines have colors; would be nice to have `<VictoryChart />` do the same, and not having to add extraneous elements just for applying the theme correctly

**Comment by 40x** [comment]
PR incoming soon

**Comment by becca-bailey** [comment]
Closing this issue since I do not believe we plan to implement it right now. If you need this feature, PRs are still welcome!
