### ISSUE TITLE
Duplicate tool tips when using line and scatter

### ISSUE THREAD

**Issue by JarLowrey** [FormidableLabs/victory#1052]
# Bugs and Questions

### Checklist

* [x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x ] I am using the latest version of Victory

* [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Two tool tips are created when using a VictoryLine and VictoryScatter together. Duplication bug.

![selection_123](https://user-images.githubusercontent.com/7429786/42857476-de87f6d0-89fe-11e8-96ea-e9c44aa58b73.png)

### Reproduction

Bug - https://codesandbox.io/s/3oxvkom1q
No bug (scatter removed) - https://codesandbox.io/s/3oxvkom1q

**Comment by boygirl** [comment]
@JarLowrey to get around this, you can use the `voronoiBlacklist` prop to ignore one of the components. You can read more about this prop here: https://formidable.com/open-source/victory/docs/victory-voronoi-container/#voronoiblacklist

**Comment by JarLowrey** [comment]
I am having an issue in my project where blacklisting the Scatter makes it impossible to hover over any additional lines. I have been [unable to duplicate](https://codesandbox.io/s/jn922z3y89) this bug in CodeSandBox. Do you have any ideas of what might be happening?

**Comment by JarLowrey** [comment]
I have gotten it working by placing all the the VictoryLine's after all of the VictoryScatter's. This does not duplicate in CodeSandBox, but is consistently reproducible across runs in my environment. Really weird.

**Comment by boygirl** [comment]
@JarLowrey that is super weird. I tried to reproduce this locally with a minimal example:

```
<VictoryChart
  containerComponent={
    <VictoryVoronoiContainer
      labels={(d) => `${d.y}`}
      voronoiBlacklist={["scatter"]}
    />
  }
>
  <VictoryLine name="line"/>
  <VictoryScatter name="scatter"/>
</VictoryChart>
```

But it is working as expected. What version of Victory are you using?
