### ISSUE TITLE
Version number jump from v0.27.2 to v30.x.x

### ISSUE THREAD

**Issue by CWolfs** [FormidableLabs/victory#1053]
I've noticed the version number recently jumped from `v0.27.2` to `v30.x.x`. It feels like this was not intended? I assume it should actually be `v0.30.x`?

I notice it's the same in NPM registry.

**Comment by boygirl** [comment]
@CWolfs this change is very intentional. You can read about it here:
https://formidable.com/blog/2018/victory-is-turning-thirty/

**Comment by CWolfs** [comment]
Ah great. Thanks for the link.
