### ISSUE TITLE
Custom colorScale for VictoryStack

### ISSUE THREAD

**Issue by redixhumayun** [FormidableLabs/victory#1056]
Feature Requests

* [X] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### Description
The docs state that the colorScale for the VictoryStack component operates based on index, unless they are explicitly specified in styles. (https://formidable.com/open-source/victory/docs/victory-stack/)

How do I define these explicitly in styles? I want the ability to assign a color to stacked bar chart depending on the y value of that bar. Is there currently a way to do this?

**Comment by boygirl** [comment]
@redixhumayun yes! You can use functional styles to color your bars. Check out this example code:

```
<VictoryStack
  colorScale={["tomato", "orange", "gold"]}
>
  <VictoryBar
  	style={{ data: { fill: (d) => d._y1 > 2 ? "red" : "navy" } }}
    data={[{x: "a", y: 2}, {x: "b", y: 3}, {x: "c", y: 5}]}
  />
  <VictoryBar
    data={[{x: "a", y: 1}, {x: "b", y: 4}, {x: "c", y: 5}]}
  />
  <VictoryBar
    style={{ data: { fill: (d) => d._y1 > 6 ? "pink" : "cyan" } }}
    data={[{x: "a", y: 3}, {x: "b", y: 2}, {x: "c", y: 6}]}
  />
</VictoryStack>
```

`d._y1` refers to the data corresponding to the top of the bar after the stacked layout is applied. you could also use `d._y0` for the bottom of the bar, or `d._y` for the original y value of the bar (pre-stacking)
