### ISSUE TITLE
VictoryBrushContainer: brush disappears even when defaultBrushArea set to disable

### ISSUE THREAD

**Issue by ddai85** [FormidableLabs/victory#1058]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When props for VictoryBrushContainer are set as:
`
defaultBrushArea="disable
brushDimension="x"
allowResize={false}
`
brush disappears onMouseDown that is not on the brush itself. Expected behavior for defaultBrushArea="disable" should be for the brush to remain at same brush domain.

### Reproduction

Bug is reproduced here:

https://codesandbox.io/s/kky0qz6pvr

**Comment by ddai85** [comment]
nevermind, don't need brushDimension prop if not resizing

**Comment by epegzz** [comment]
This is still a bug, can we re-open this ticket? :)

**Comment by becca-bailey** [comment]
Confirmed that this is still reproducible in the latest version of Victory.

**Comment by becca-bailey** [comment]
Closing in favor of #2111
