### ISSUE TITLE
Adding `VictoryZoomContainer` to stacked grouped charts ignores the `data` prop on `VictoryGroup`

### ISSUE THREAD

**Issue by torava** [FormidableLabs/victory#1067]
In some scenarios like when adding VictoryZoomContainer to this example https://formidable.com/open-source/victory/gallery/victory-portal-stacked-area/ I would expect it to allow zooming fluently but instead the whole chart breaks. My only modification was adding containerComponent to VictoryChart.

`<VictoryChart scale={{ x: "time" }} width={400} height={400} containerComponent={
  <VictoryZoomContainer
    zoomDimension="x"
  />
 }>`

**Comment by boygirl** [comment]
Oh! Yes, it looks like the `data` prop on `VictoryGroup` is not respected when nested in `VictoryStack` when `VictoryZoomContainer` is added. This is definitely a bug in the library. Thank you for uncovering this edge case. I'm going to update the title of your issue to be more specific.
