### ISSUE TITLE
Fold Animation for VictoryPie on load

### ISSUE THREAD

**Issue by punnkam** [FormidableLabs/victory#1068]
I've been trying to create a VictoryPie component that 'folds out' when the page loads. From another thread I found a possible solution to set state in the componentDidMount() and indicate the animation duration in the rendering of VictoryPie in order to create the animation. 
1. In the constructor
```
this.state = {
            pieData: [
                { x: 'a', y: 0, label: 'a'},
                { x: 'b', y: 0, label: 'b'},
                { x: 'c', y: 0, label: 'c'},
                { x: 'd', y: 100, label: 'd'}
            ]
        }
```

2. Setting State in componentDidMount()
```
componentDidMount() {
        this.setState = {
            pieData: [
                { x: 'a', y: 0, label: 'a'},
                { x: 'b', y: 30, label: 'b'},
                { x: 'c', y: 20, label: 'c'},
                { x: 'd', y: 30, label: 'd'}
            ]
        }
    }
```

3. Rendering out VictoryPie
```
render() {
       return (
            <Container className='pie-container' style={styles.pieContainer} fluid>
                <VictoryPie
                    innerRadius={80}
                    data={this.state.pieData}
                    colorScale={['tomato', 'gold', 'navy', 'grey']}
                    padAngle={2}
                    animate={{
                        duration: 2000
                    }}
                />
            </Container>
        )
}
```

All I seem to see after render is this chart:

![image](https://user-images.githubusercontent.com/41944993/43446576-73601e98-94d3-11e8-87d4-cbcdbc478ec3.png)

Quite new to React and Victory so still not very experienced

**Comment by 40x** [comment]
You are not setting the state correctly. `setState` is a function and not a variable like you assigned. Pass the updated `state` to the `setState` function instead.

**Comment by punnkam** [comment]
@40x Thanks man didn't spot that
