### ISSUE TITLE
Single `VictoryBar` Components Won't Change Width

### ISSUE THREAD

**Issue by nickzuber** [FormidableLabs/victory#1070]
### The Problem

When you have a graph that has `VictoryBar` components all on the same axis using `VictoryStack`, you cannot adjust the width/size of the bars.

Once you add other bars on a different axis, then you can change the widths and everything, so this problem only occurs when there's a _single_ stack of bars.

<img width="287" alt="screen shot 2018-08-01 at 12 23 07 pm" src="https://user-images.githubusercontent.com/10540865/43534556-aad30ee6-9585-11e8-9674-073c03f2d85c.png">

### Reproduction

https://codesandbox.io/embed/rm62zk4lzm

**Comment by boygirl** [comment]
@nickzuber thank you for this issue. I will get this fixed for the next release

**Comment by boygirl** [comment]
Actually, after taking a closer look at your sandbox, this is not an issue with the library.

The `width` prop on `VictoryBar` refers to the overall svg width, not the bar width. To define the bar width, you should add a `width` attribute to your data styles like 

`style={{ data: { width: 20 } }}`

You can add that prop on either `VictoryStack` or `VictoryBar`, or both, but conflicting styles defined on `VictoryBar` will take precedence.

**Comment by nickzuber** [comment]
@boygirl Ah I see, that definitely does the trick — thank you! I wish that could somehow be more clear in the docs

**Comment by boygirl** [comment]
@nickzuber Definitely. I'm thinking of adding a `barWidth` prop so that styles are restricted to valid svg styles
