### ISSUE TITLE
Add `onBrushCleared` prop for `VictoryBrushContainer`

### ISSUE THREAD

**Issue by Lehakos** [FormidableLabs/victory#1073]
# Bugs and questions

### Problem
When I set `defaultBrushArea="false"` to VictoryBrushContainer and click outside brush area, onBrushDomainChange receive full domain. But how I can detect that area was cleared with this data?
Maybe the domain has be like this: `{ x: [], y: [] }`, or you can introduce new prop `onBrushCleared`?

### Reproduction
https://codesandbox.io/s/jv18pxnw5

**Comment by boygirl** [comment]
@Lehakos yes, `onBrushCleared` sounds like a very reasonable addition. I will update the title of this issue.
