### ISSUE TITLE
Investigate inconsistent npm install behavior

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#108]
@neverfox describes some strange `npm install` behavior in #78. Investigate and fix if there is a consistent repro.

**Comment by neverfox** [comment]
This was NPM's 3.3.x's fault. NPM 3.5.x is necessary to avoid this bug. I think you can consider this closed as not a problem with victory.

**Comment by knowbody** [comment]
closing as it's not victory related bug as @neverfox mentioned.
