### ISSUE TITLE
Persian language(rtl) does not work in label props

### ISSUE THREAD

**Issue by ealimardaniii** [FormidableLabs/victory#1086]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I try to customize the label of VictoryBar to Show rtl language like Persian but does not work properly, and reverse the text that character could not connect together , what's the solution
I want to customize y Axis numbers and label of the chart to my local language(Persian)

### Reproduction

```javascript
<VictoryChart height={250} width={350}
                domainPadding={{ x: 50, y: [0, 20] }}
              >
               <VictoryBar
                  style={this.state.styleSummer}
                  data={[
                    { x: 'b', y: 20000, label: "bb" },
                  ]}
                  labelComponent={
                    <VictoryLabel labelPlacement="vertical" verticalAnchor="middle" text={"سلام"} />
                  }
                />
 </VictoryChart>
```

**Comment by boygirl** [comment]
@ealimardaniii I apologize for this oversight. I will add a `direction` prop to `VictoryLabel` with options "rtl" and "ltr" which will be passed down and applied to the rendered svg `<text/>` tag.

As an immediate solution, You can try adding `direction: "rtl"` to your label styles. I'm not sure whether this svg attribute will work as a style.

**Comment by boygirl** [comment]
@ealimardaniii does this output look correct?

```
<VictoryLabel direction="rtl" verticalAnchor="start"
  style={[{ fill: "red", fontSize: 20 }]}
  text={"سلام world"}
/>
```

<img width="114" alt="screen shot 2018-08-13 at 4 46 11 pm" src="https://user-images.githubusercontent.com/3719995/44064144-7a24ffc4-9f18-11e8-893c-a7a006dd4310.png">

**Comment by FatemeMirzaeii** [comment]
> 
> 
> @ealimardaniii does this output look correct?
> 
> ```js
> <VictoryLabel direction="rtl" verticalAnchor="start"
>   style={[{ fill: "red", fontSize: 20 }]}
>   text={"سلام world"}
> />
> ```
> 
> <img alt="screen shot 2018-08-13 at 4 46 11 pm" width="114" src="https://user-images.githubusercontent.com/3719995/44064144-7a24ffc4-9f18-11e8-893c-a7a006dd4310.png">

this really didn't solve the problem.
any update on this issue?

**Comment by sfalihi** [comment]
for anyone who has this problem yet:
 just use this library for conversion: 
https://www.npmjs.com/package/arabic-persian-reshaper

example for usage =>
```
data={[
    {
      label: reshaper.PersianShaper.convertArabic("سلام"),
      y: 1,
    },
]}
```
