### ISSUE TITLE
strokeWidth 0 is not respected for stacked bars

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#1089]
bars with zero height will still render a 1px stroke on stacked bars

**Comment by acharyakavita** [comment]
@carbonrobot I was not able to reproduce the issue.

Below is the code that I used 

```typescript
<VictoryChart 
        domainPadding={8}
        style={{parent: { border: "1px solid #ccc", margin: "2%", maxWidth: "40%" }}}
        theme={VictoryTheme.material} 
       >
        <VictoryStack labels={({ datum }) => datum._y1.toPrecision(2)}>
          <VictoryBar data={[]} />
          <VictoryBar data={[
            { x: 1, y: 2, label: "cat" },
            { x: 2, y: 5, label: "dog" },
            { x: 3, y: 3, label: "dog" },
            { x: 4, y: 5, label: "bird" },
            { x: 5, y: 7, label: "cat" },
          ]} />
          <VictoryBar data={[
          { x: 1, y: 2, label: "cat" },
          { x: 2, y: 5, label: "dog" },
          { x: 3, y: 3, label: "dog" },
          { x: 4, y: 10, label: "bird" },
          { x: 5, y: 5, label: "cat" }
          ]} />
        </VictoryStack>
      </VictoryChart>
``` 

which produces



![Image](https://github.com/FormidableLabs/victory/assets/42627321/930333d3-c118-4abd-b222-b852d7681598)

Here we can see a green border around red bars which is produced when we send no data, but on inspecting the stroke width is 0.
I am not sure if this is the right approach to reproduce this issue.

![Image](https://github.com/FormidableLabs/victory/assets/42627321/5a11d7e8-0a3f-493b-9866-ee597877824a)

We can remove the fill and stroke color if this is the right approach to reproduce.
