### ISSUE TITLE
Wrapped `VictoryTooltip` doesn't render

### ISSUE THREAD

**Issue by nickzuber** [FormidableLabs/victory#1090]
### The Problem

Trying to pass in a `VictoryTooltip` component as a `labelComponent` prop works totally fine and as expected. However, once you wrap the `VictoryTooltip` in a HoC of some kind, it will no longer render (even when passing all the props down).

### Reproduction

https://codesandbox.io/s/6yr2kx7p1k

**Comment by boygirl** [comment]
@nickzuber sorry for the confusion. `VictoryTooltip` has some default events that need to get picked up in order for it to render on mouseOver. You will need to add `defaultEvents` from `VictoryTooltip` to your wrapped component. This guide should help: https://formidable.com/open-source/victory/guides/tooltips/#wrapping-victorytooltip
