### ISSUE TITLE
VictoryPie renders the wrong colors when `data` changes

### ISSUE THREAD

**Issue by kaiyoma** [FormidableLabs/victory#1092]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a webapp that uses VictoryPie to display live streaming data that changes often. I'm noticing that when the `data` prop changes, the colors rendered on-screen for the slices are wrong until I mouse over the slices.

In my case, everything about `data` could change from one moment to the next: the number of entries, the labels, the values, and the colors.

I'm passing this prop to `VictoryPie`, as instructed by the docs:

```
  style={{
    data: {
      fill: datum => datum.fill,
    },
  }}
```

And my `onMouseOver` and `onMouseOut` handlers update the style like this:

```
  onPieceMouseOver = () => {
    return [{
      mutation: props => {
        return {
          style: {
            fill: chroma(props.datum.fill).brighten(0.4),
          },
        };
      },
    }];
  };

  onPieceMouseOut = () => {
    return [{
      mutation: props => {
        return {
          style: {
            fill: props.datum.fill,
          },
        };
      },
    }];
  };
```

### Reproduction

I don't have one yet. I wanted to post this first to see if I'm simply doing something wrong in the code. I can work on a sandbox if need be.

**Comment by kaiyoma** [comment]
I managed to come up with a sandbox: https://codesandbox.io/s/oq9nzyl5rz

This renders a pie with some data, then after two seconds, the pie gets updated with a new (but similar) dataset.

The problem seems to be that mousing over the slices somehow "taints" them, such that after the new `data` prop is sent to the component, one or more of the colors will be wrong, until you mouse over the slices again.

If you let the sandbox run without mousing over any of the slices, everything will work correctly and all neighboring slices will have unique colors. However, if you mouse over some slices in the two-second period before the second dataset arrives, you'll "taint" the slices and the new rendering will be wrong, as evidenced by neighboring slices having the same color. Mousing over the slices fixes the colors.

For the best results, load the sandbox, quickly mouse over the four largest slices (those between 10:00 and 12:00 in the pie), move the mouse off the pie, and wait for the re-rendering to occur. You'll probably notice two neighboring slices in that part of the pie with the same color, which is wrong. Mouse over all those pieces and the colors will fix themselves.

**Comment by boygirl** [comment]
@kaiyoma thank you for the reproduction. The problem is that in your `onMouseOut` handler you are setting your fill to `props.datum.fill`. Doing this uses the props that are current on the slice at the time of your mouseOut event, which is why the colors get stuck. Rather than setting a static fill there, you can either clear your styles all together like:

```
mutation: () => null
```
or set your fill to a function of datum like:
```
mutation: () => ({
  style: {
    fill: (datum) => datum.fill,
    strokeWidth: 0
  }
})
```
option one is probably better.

**Comment by kaiyoma** [comment]
Great, thanks so much! Option one indeed fixes the issue.
