### ISSUE TITLE
Don't put calculated values on `this`

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#110]
Go through components and refactor

**Comment by exogen** [comment]
I support this and think we should avoid setting arbitrary properties on `this`. But word of warning: `setState` is not synchronous, and the methods that set properties on `this` rely on the properties set by the previous methods. So one method calling `setState({ foo: "bar" })` and then the next accessing `this.state.foo` will *not* see that change. We should do it, but it'll be more than a simple change.

**Comment by boygirl** [comment]
I feel kind of conflicted about this. These things aren't really state, just things we need to calculate... Do they really belong in state?  Should we just calculate them all down in the render method, do it in whatever order we need, and pass in the values to the calculations that need them?

**Comment by exogen** [comment]
I don't mind if they aren't actually put on `state` because that has implications for the render lifecycle that we might not want. @boygirl Your solution sounds reasonable if we can do it cleanly! Maybe some of those methods could be moved to helpers in another file while we're at it.

**Comment by kenwheeler** [comment]
I prefer not to add anything to the instance, but there are certain scenarios where you might want to store something, like a setTimeout identifier or something, and that's when I usually do. I prefer that wholeheartedly over directly mutating state, and using setState triggers a render check. Alternatively, you could use the module closure to have a private var that you define prior to class creation, but I generally like putting it on the instance instead.

**Comment by kenwheeler** [comment]
@boygirl @exogen are there any drawbacks in your opinion around storing things in instance properties?

**Comment by kenwheeler** [comment]
Another option could be setting one property object, like state, that you would use to store anything that would fall into this category, for purposes of clarity and convention.

**Comment by knowbody** [comment]
hey I'm new to all this. If I understand it correctly we are mainly talking about the calculations which are assigned to the instance variables.

I do agree with `setState` although @kenwheeler has a point here, there are situations where is not the best thing to do. I think this SO thread is what Ken was talking about: http://stackoverflow.com/questions/25207703/instance-v-state-variables-in-react-js

From what I can see (correct me if I'm wrong) all of those calculations depend on `props`. I think exporting the calculation to a separate helper file as @exogen mentioned is a good idea.

So when the component is mounted for the first time we would call something like: `this.doCalculations(props)` and that would return a single object with all the properties needed and we put that into the component's `state`. And then we can make use of `componentWillReceiveProps(nextProps)`, do a check if the `props` actually have changed, if yes then `setState` with the newly calculated object.

**Comment by boygirl** [comment]
I think I'm with Ken about not using state based on an additional render check. We're already having trouble with animation perf. I do like the idea of splitting out the calculations into a separate file, and returning an object of just the values necessary for rendering, and pass that into the render methods.

```
render () {
  const calculatedValues = calculateValues(this.props);
  return this.renderData(calculatedValues);
```
no `state`, no instance properties, everybody wins?

**Comment by kenwheeler** [comment]
:thumbs_up:

**Comment by knowbody** [comment]
:+1:

**Comment by mindjuice** [comment]
FYI, calculating derived data from props is what https://github.com/rackt/reselect is for.

It was originally intended for use with Redux, but doesn't actually depend on it and can be used independently (although I haven't used it that way).

Not sure how you feel about incorporating another dependency though.
