### ISSUE TITLE
Design general event handling pattern

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#111]
- For interactivity
- Should be consistent between Radium and Victory

**Comment by gj262** [comment]
For `VictoryLine`, something similar to the style property format should work i.e.
```    
    /**
     * The event prop specifies event handlers for your line.
     * @examples {data: {onMouseOver: () => console.log('mouseover')}}
     */
    event: PropTypes.shape({
      parent: PropTypes.object,
      data: PropTypes.object,
      labels: PropTypes.object
    })
```

**Comment by boygirl** [comment]
@gj262 we were actually planning on the exact api you describe! We're still finalizing what the event handlers should be called _with_. We will definitely include the data point associated with a click, and it's x, y coordinate. Any other requests?

**Comment by gj262** [comment]
Sounds great to me. Let me know if I can help in anyway. Thanks.

**Comment by cpb** [comment]
Hi!

I have a suggestion: don't modify the existing components _too much_ in order to support general interactivity!

The insight comes from reading up on @gaearon's React DnD, and thinking of the refactoring patterns he uses to incrementally add more interactivity to his "Chess" example. See http://gaearon.github.io/react-dnd/docs-overview.html and http://gaearon.github.io/react-dnd/docs-tutorial.html

In https://github.com/FormidableLabs/victory-bar/pull/100 I suggest a design enhancement that enables users of victory-bar to substitute alternate implementations of ```Bar``` or ```BarLabel``` to support interaction.

Consider: https://github.com/cpb/victory-bar/commit/72b00af22e57aa65c4c4b8b90c21e075b45d3623#diff-3860df8740a869cde6dfb90663c634e3

Although the example I added in demo.jsx is trivial, it illustrates that we do not need to have, for example, ```VictoryBar``` know about the events the ```Bar```s are subscribing to.

**Comment by cpb** [comment]
Also added the suggested design pattern to victory-pie: https://github.com/FormidableLabs/victory-pie/pull/50

**Comment by cpb** [comment]
Although it takes adding redux and a bunch of boiler plate to the top of demo.jsx (happy to hear feedback about refactoring that, esp obvious stuff about "put it in a separate file ;-)") I've added an example to victory-pie that allows a user to click on pie slices to change their sizes.

This represents a full loop: user interactivity feeds back into the chart. https://github.com/cpb/victory-pie/commit/fef46bb2867ecf2c6c99da7f01c1b9d24f651fe5

I believe this demonstrates that injecting alternate sub component implementations enables general interactivity.

Now, as for what data is provided during the event. @boygirl suggests that victory should provide a certain amount of data, esp: x values at the point of clicking. That is a great convenience. However, it could be enabled by utility functions that take a certain component and the synthetic event and return contextualized information like an x value within the domain of the chart.

**Comment by boygirl** [comment]
@cpb we will be adding replaceable components via props as you suggest _i.e._ `BarComponent` for the flexibility it provides in general. I'll take a look at your PRs tonight, and figure out the best way to incorporate them 

We will _also_ add an events prop with roughly the following api:

```
events={{
  data: {onClick: onClickHandler(event, position, closestDataPoint*), ...},
  labels: {...},
  parent: {...}
}}
```
with anything in the event object getting assigned to the appropriate rendered component. like `<Bar {...props.events.data} />`

*closestDataPoint... We're still figuring out the most performant way to determine the closest data point to a given event

**Comment by cpb** [comment]
Fantastic news! Really looking forward to it!

**Comment by cpb** [comment]
Support for the injection of label components was already implemented for ```VictoryScatter``` and ```VictoryBar``` -- https://github.com/FormidableLabs/victory-chart/pull/98 ensures both interfaces are consistent.

https://github.com/FormidableLabs/victory-chart/issues/99 would bring ```VictoryLine``` to parity for injecting label dependencies.

**Comment by bebraw** [comment]
It would be great if you could provide chart specific events. I.e., line chart + hover on line. It would be fun to display data based on that.

**Comment by cpb** [comment]
Cool idea! Thanks for that input!
