### ISSUE TITLE
VictoryBar overlaps x axis

### ISSUE THREAD

**Issue by Ilario17** [FormidableLabs/victory#1111]
# Bugs and Questions

### The Problem

![schermata 2018-09-11 alle 16 24 01](https://user-images.githubusercontent.com/33326791/45366489-3ff2a080-b5df-11e8-9de2-3e55707bf932.png)

### Reproduction

```
<VictoryChart
	height={250}
	width={this.win.width - 20}
	//domainPadding={20}
	domain={domain} //  domain is { y: [minFromData - 500, maxFromData + 500 ]}
>
	<VictoryBar
		data={this.state.data}
		style={{
			data: { fill: COLOR_RED },
		}}
		alignment='start'
		barWidth={9}
	/>
</VictoryChart>
```

The image is quite explicit in illustrating the problem.

react-native: "0.56.0"
react-native-svg: "^6.5.2"
victory-native: "^30.3.0"

**Comment by boygirl** [comment]
@Ilario17 by default, `VictoryBar` has a baseline of 0. If you want to set your own baseline you can add a `y0` prop like:
`VictoryBar y0={() => minFromData - 500} .../>`
