### ISSUE TITLE
Showcase and outstanding issues with tooltips and y axis

### ISSUE THREAD

**Issue by fwielstra** [FormidableLabs/victory#1114]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hi guys, and especially @boygirl who has helped me tremendously over the past couple of months with some great and clear feedback and instructions!

First off I'd like to do something of a showcase of what we've done with Victory Charts. I work at Vandebron, a Dutch green energy company, and in the past months we've rebuilt our energy consumption dashboard, with Victory Charts being the centerpiece.

Now, I've had a number of issues over time to get the chart to display just so, however despite help from the Victory Charts community, there's a few issues that I haven't been able to fix.

The one is an issue where more than one tooltip is visible when hovering in just the right position. I asked about this in Gitter and tried the offered suggestions, but these didn't seem to work unfortunately.

The other issue is drawing the 0.0 line, [this answer](https://github.com/FormidableLabs/victory/issues/1087) said it would be a matter of setting the `crossAxis` property, but unfortunately this didn't seem to work; it's probably a combination of all the options I'm using.

### Reproduction

I have extracted all relevant code and some hardcoded data into a standalone repository based off of the create-react-app template; both issues can be reproduced there. The repo is at https://github.com/fwielstra/vdb-victory-chart

I've deployed this at http://fwielstra-vdb-victory-charts-example.s3-website-eu-west-1.amazonaws.com/, you can see the double tooltip issue there when hovering at Thursday 5 and Friday 6th of april, right at the top right of the Thursday 5th bar.

I really hope I'm not being annoying or anything with these questions, I know they're all well-documented and the support has been great! I've just not been able to provide a running example until now.

**Comment by becca-bailey** [comment]
Closing for now, we can re-open as a discussion if necessary.
