### ISSUE TITLE
Y position in VictoryTooltip does not affect it's position

### ISSUE THREAD

**Issue by isitrita** [FormidableLabs/victory#1115]
Hi, is it Possible to change position of voronoiTooltip, so it Y position would always be the same? I need to implement behaviour similar to https://www.google.co.za/search?q=ll 

I am trying to do, but y is still near point on chart
```
<VictoryChart
        scale={{ x: 'time' }}
        polar={false}
        height={140}
        padding={{
          top: 10,
          bottom: 15,
          left: 10,
          right: 40,
        }}
        domain={domain}
        theme={theme}
        containerComponent={
          <VictoryVoronoiContainer
            voronoiDimension="x"
            labels={d => `${d.y} ${new Date(d.x).toLocaleDateString()}`}
            labelComponent={<VictoryTooltip y={100}/>}
          />
        }
      >
```

**Comment by evandavid** [comment]
my solution:

`class CustomTooltip extends React.Component {
  render() {
    return (
      <g>
        <VictoryTooltip 
        {...this.props} y={100} 
        renderInPortal={false} 
        />
      </g>
    );
  }
}
`

`
<VictoryChart
        scale={{ x: 'time' }}
        polar={false}
        height={140}
        padding={{
          top: 10,
          bottom: 15,
          left: 10,
          right: 40,
        }}
        domain={domain}
        theme={theme}
        containerComponent={
          <VictoryVoronoiContainer
            voronoiDimension="x"
            labels={d => `${d.y} ${new Date(d.x).toLocaleDateString()}`}
            labelComponent={<CustomTooltip />}
          />
        }
      >
`
