### ISSUE TITLE
Better label positioning options for VictoryPie

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#1117]
Currently it requires some math to move labels to specific angles or offset by angle or radius.

There should be options for default label angle that correspond to the `startAngle`, `centroid`(current) and `endAngle` of the slice. This would fix issues like https://github.com/FormidableLabs/victory-native/issues/377

**Comment by sikolio** [comment]
I have made progress in this but there is a need to change the position by a % so the label ends inside the slice instead of just at the border. 

By the linter I can't go ahead and put a 0.9 multiplier or something, so I will push this as it is.
