### ISSUE TITLE
Feature: possibility to add top-left or top-right cornerRadius to VictoryBar

### ISSUE THREAD

**Issue by m-g-cencek** [FormidableLabs/victory#1119]
# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Currently, it is possible to add cornerRadius to either the top or bottom of a bar. I would like to be able to add a cornerRadius to a single corner, eg top-right. 

At the moment it is possible to pass such values to the cornerRadius prop:

```
type: function || number || { top: number || function, bottom: number || function }
```

I'd like to be able to pass such an object:

```
type: { topLeft: number || function, topRight: number || function, bottomRight: number || function,  bottomLeft: number || function }
```

**Comment by boygirl** [comment]
@m-g-cencek I like this solution generally. I think to avoid a breaking change, the prop would have to look like:

```
cornerRadius: PropTypes.oneOfType([
      PropTypes.number,
      PropTypes.func,
      PropTypes.shape({
        top: PropTypes.oneOfType([PropTypes.number, PropTypes.func]),
        topRight: PropTypes.oneOfType([PropTypes.number, PropTypes.func]),
        topLeft: PropTypes.oneOfType([PropTypes.number, PropTypes.func]),
        bottom: PropTypes.oneOfType([PropTypes.number, PropTypes.func]),
        bottomRight: PropTypes.oneOfType([PropTypes.number, PropTypes.func]),
        bottomLeft: PropTypes.oneOfType([PropTypes.number, PropTypes.func]),
      })
    ]),
```
