### ISSUE TITLE
Add `getPath` prop to `Bar` to allow users to create custom paths

### ISSUE THREAD

**Issue by m-g-cencek** [FormidableLabs/victory#1120]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue
☝️ I actually created an issue to add such a feature, though meanwhile, I'd like to ask whether there are some alternative routes to achieve the result mentioned below 👇 

### The Problem

I would like to add a cornerRadius to the top-right corner of the VictoryBar. Using cornerRadius would not work, as it applies radius to both top corners. Is there a way to pass the d prop to the VictoryBar path, which would generate a bar with the desired shape?

**Comment by boygirl** [comment]
@m-g-cencek currently there isn't a way to do this without 1) extending `Bar` or 2) writing your own bar component. I think the solution you suggest in https://github.com/FormidableLabs/victory/issues/1119 is a good one.
Another change we could make in Victory would be to add a `pathFunction` prop to `Bar` that could be used to customize the `d` prop passed to `Path` as you suggest. 'm going to change the title of this issue to reflect this change.
