### ISSUE TITLE
CodeSandBox for Getting Started section

### ISSUE THREAD

**Issue by captDaylight** [FormidableLabs/victory#1128]
On the "Getting Started" section of the docs, instead of only linking to the final code on github, it would be helpful to have a codesandbox template ready to go so that someone can follow along right away. I created a simple template [here](https://codesandbox.io/s/98pr3p8oxp) that is set up with react and victory. I'd be happy to make a PR to add it. Also here's the [final](https://codesandbox.io/s/8z80p4v2p2).

**Comment by boygirl** [comment]
@captDaylight that is a great idea. I'm going to move this issue to our docs repo. We're in the process of some larger changes there, so it might take a minute to get incorporated.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#581
