### ISSUE TITLE
Missing Date Tick on Bar Graph

### ISSUE THREAD

**Issue by captDaylight** [FormidableLabs/victory#1134]
I have very simple bar graph that seems to be missing a date tick along the x axis. I've made a simple example to [demonstrate the problem](https://codesandbox.io/s/xykr28lkz). First I have 4 data points, each with a different month going back 4 months. 
```
const getDateMinusMonth = monthDiff => {
  const date = new Date();
  date.setMonth(date.getMonth() - monthDiff);
  return date;
};
const tempData = [
  { x: new Date(), y: 5 }, 
  { x: getDateMinusMonth(1), y: 6 }, 
  { x: getDateMinusMonth(2), y: 7 }, 
  { x: getDateMinusMonth(3), y: 8 },
];
```

Then I put the data in the graph:

```
<VictoryChart scale={{ x: 'time' }}>
  <VictoryBar style={{ data: { fill: '#ff6b4a' } }} data={tempData} />
</VictoryChart>
```
Here's what the end result looks like, where you can see it's missing a month in the bottom left:
<img width="635" alt="screen shot 2018-10-03 at 5 24 55 pm" src="https://user-images.githubusercontent.com/700617/46440431-4cc36980-c731-11e8-9194-9c23ced03907.png">

**Comment by boygirl** [comment]
@captDaylight 
By default Victory lets d3 pick which `tickValues` to render if you're using numeric or time data (note, this is also what is causing your month names to not be centered on your bars). If you need specific values you can choose your own like so: 

```
<VictoryChart scale={{ x: 'time' }}>
   <VictoryAxis 
       tickValues={tempData.map(d => d.x)}
       tickFormat={(t) => t.toLocaleString("en-us", { month: "long" })}
   />
  <VictoryAxis dependentAxis />
  <VictoryBar style={{ data: { fill: '#ff6b4a' } }} data={tempData} />
</VictoryChart>
```

Here is an edited version of your sandbox too, for reference: https://codesandbox.io/s/102m66j3xq

**Comment by boygirl** [comment]
VictoryAxis doesn't actually have access to your data, it just knows the shared domain and range of the chart, so it does approximately this:
```
 tickValues = 
  props.tickValues || 
  d3.scale.domain(sharedDomain).range(sharedRange).ticks(props.tickCount);
```
