### ISSUE TITLE
No way to provide a component or HTML context to labels

### ISSUE THREAD

**Issue by marcrd** [FormidableLabs/victory#1138]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Can't get HTML or components rendering to the proper string representation in the `text` prop of `VictoryLabel`. 

Want to be able to provide a component context like:

```jsx
<VictoryLabel x={80} y={90} text={() => <MyTooltipTextComponent />} />
```

Example graph in use:

![screenshot 2018-10-05 13 17 37](https://user-images.githubusercontent.com/1328720/46549750-0b51cc00-c8a1-11e8-8f87-cf43d99fc717.png)

Use case: Have an app that uses a component for managing language translations (we provide it a key and returns the string based on the language setting). 

### Reproduction

You can see the ways it returns `[object Object]` vs the way it's specified in the docs: https://codesandbox.io/s/pjk64rn9yq

# Feature Requests

N/A (unless it's expected behavior to work this way)

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by boygirl** [comment]
@marcrd `VictoryLabel`'s `text` prop expects a string, an array of strings, or a function that returns strings. You have a few other options though:

1) Have a the text function perform the localization without returning an element
2) Use a custom label prop

Here are some examples:
```
// You can render any svg elements you like
const MyCustomLabel = props => {
  return <text {...props}>{"Hello World"}</text>;
};

// or wrap VictoryLabel
const MyCustomVictoryLabel = props => {
  return (
    <g>
      <VictoryLabel {...props} text="Hello World" />;
      <circle cx={props.x - 5} cy={props.y} r={3} fill="black" />
    </g>
  );
};

// you can also render html elements,
// but they must be wrapped in foreignObject since they will be rendered inside svg
const MyCustomHTMLLabel = props => {
  return (
    <foreignObject x={props.x} y={props.y}>
      <p>{"Hello World"}</p>
    </foreignObject>
  );
};
class App extends React.Component {
  render() {
    return (
      <VictoryChart>
        <VictoryLine />
        <VictoryLabel x={80} y={60} text={"Hello World"} />
        <MyCustomLabel x={80} y={90} />
        <MyCustomVictoryLabel x={80} y={110} />
        <MyCustomHTMLLabel x={80} y={130} />
      </VictoryChart>
    );
  }
}
```
Or a codesandbox if you prefer: https://codesandbox.io/s/18qz70jp3l

You can read more about custom components in Victory here: https://formidable.com/open-source/victory/guides/custom-components/

**Comment by chriszrc** [comment]
> https://codesandbox.io/s/18qz70jp3l

Fyi, in the codesandbox link above, the foreign object label is blank because apparently it needs some kind of width/height to render:

https://codesandbox.io/s/custom-labels-forked-gxx3u7?file=/index.js:886-910
