### ISSUE TITLE
Adding tick marks to VictoryBar charts

### ISSUE THREAD

**Issue by colin-young** [FormidableLabs/victory#1139]
I am trying to add some lines to my stacked bar chart. I've managed to do it [here](https://codesandbox.io/s/211865pmjn). The way I did it was to add a second stack group that draws:

1. An invisible bar
2. A zero-height bar with stroke defined
3. An invisible bar
4. A zero-height bar with stroke defined

It looks exactly like I want it to but it seems like a bit of a hack. Is there a better/easier way to achieve the same thing? I couldn't figure out a way to get the coordinates of the bars in order to directly draw a line on top of the bars. One note: in my actual implementation (which is in React Native) I don't need the horizontal/vertical switching -- I'm only displaying the chart horizontally.

**Comment by boygirl** [comment]
@colin-young 

That works, but an easier way to do it would be to create a custom `dataComponent` for `VictoryBar` that renders both the bar, and a line element showing your best and worst values. I've altered your codesandbox to explain: https://codesandbox.io/s/82j5njyxwl

**Comment by colin-young** [comment]
Thanks! That's much cleaner.
