### ISSUE TITLE
Date range Axis not getting applied correctly in Horizontal Bar Chart.

### ISSUE THREAD

**Issue by mihirsoni** [FormidableLabs/victory#1140]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

While using VictoryBar with horizontal property and date range, the range is not getting applied correctly to the axis. 

![Sample Iamge](https://i.imgur.com/zdI0r5G.png)

### Reproduction
This can be reproduced here  https://codesandbox.io/s/0vp866l29n

This example has two charts with exact same dataset, one without Horizontal property where else one is with Horizontal.

From my findings, it looks like [this](https://github.com/FormidableLabs/victory/blob/4cab96636e7b95710dc2caa6cbae5e49afa7f1b6/packages/victory-core/src/victory-util/wrapper.js#L161) guy is returning incorrect value for axis while in Horizontal mode.

**Comment by mihirsoni** [comment]
Here is another example using with simple dates and even if domain is provided it goes out of range and draws bra at misplaces.

**Comment by boygirl** [comment]
This should be fixed in the latest version
