### ISSUE TITLE
victory-pie uses native Object.assign and IE11 doesn't support this

### ISSUE THREAD

**Issue by daneilsan** [FormidableLabs/victory#1142]
### The Problem

I'm using this fantastic chart library and my intention is to support IE11. So far I have been able to use it happily but the pie chart seems to have a line that uses the native Object.assign method when browsers such as IE11 doesn't have it. I saw that you are using a polyfill in other places. It should be a matter of using it also there (I guess). For some reason, I'm not able to use a global polyfill in IE to circumvent the problem because other components (outside of victory chart) doesn't like the function for some reason. So in the end is just replace it locally.

### Reproduction

Here is an example but you wont be able to use it because the web doesn't even load on IE11.
https://codesandbox.io/s/1q15r1y0k3

The problematic line is located at victory-pie/es/helper-methods.js:110

var getLabelPosition = function (arc, slice, position) {
  var construct = {
    startAngle: position === "startAngle" ? slice.endAngle : slice.startAngle,
    endAngle: position === "endAngle" ? slice.startAngle : slice.endAngle
  };
  -var clonedArc = Object.assign({}, slice, construct);
 +var clonedArc = _assign({}, slice, construct);
  return arc.centroid(clonedArc);
};

**Comment by boygirl** [comment]
@daneilsan Thanks for this issue. I will audit for instances of `Object.assign` and replace with lodash `assign`
