### ISSUE TITLE
Vertical line on hover on VictoryLine

### ISSUE THREAD

**Issue by captDaylight** [FormidableLabs/victory#1143]
I have a design spec as shown below, I was wondering if anyone has an idea if it's possible to add a vertical sectional line through a VictoryLine graph. 

<img width="515" alt="screen shot 2018-10-15 at 2 23 04 pm" src="https://user-images.githubusercontent.com/700617/46970075-03a2dc00-d086-11e8-805c-929c85db60ec.png">

**Comment by boygirl** [comment]
@captDaylight yes, this is possible. You can use `VictoryCursorContainer`

**Comment by tamj0rd2** [comment]
What about if you're having to use a VictoryVoronoiContainer?

**Comment by ZoltanSzokodi** [comment]
Hi @julia-hitiq I am also looking for the same exact solution. Did you mange to find out wether it is possible with Victory?

**Comment by heythisispaul** [comment]
@ZoltanSzokodi I just had this same need, and was able to [compose a new container](https://formidable.com/open-source/victory/docs/create-container/) using `createContainer`:

    import {
      createContainer,
      VictoryCursorContainerProps,
      VictoryVoronoiContainerProps,

    } from "victory";

    const VictoryVoronoiCursorContainer = createContainer<VictoryCursorContainerProps, VictoryVoronoiContainerProps>('cursor', 'voronoi');

You can then use this as your container component for your chart, it will have the combined behaviors of both containers.

**Comment by dev-justtrade** [comment]
@julia-hitiq You can archieve that by using a scatter plus a line chart graph wrapped with a voronoicontainer (to make the scattered points active) and then render a custom dataComponent to create the circle with the vertical line.

```
const CirclePoint = props => {
  const { x, y, active } = props

  if (active) return (
    <g>
      <line x1={x} y1={0} x2={x} y2={500} stroke="#777777" stroke-dasharray={3} />
      <circle cx={x} cy={y} r="3" fill="#ffffff" />
    </g>)
  
  return
}
<VictoryChart
      containerComponent={
        <VictoryVoronoiContainer
          voronoiDimension="x"
        />
      }
    >
      <VictoryLine
        style={{
          data: { stroke: '#c43a31' },
          parent: { border: '1px solid #ccc' },
        }}
        data={data}
      />
      <VictoryScatter data={data} dataComponent={<CirclePoint />} />
    </VictoryChart>
```

**Comment by ErskinMichael** [comment]
> @julia-hitiq You can archieve that by using a scatter plus a line chart graph wrapped with a voronoicontainer (to make the scattered points active) and then render a custom dataComponent to create the circle with the vertical line.
> 
> ```
> const CirclePoint = props => {
>   const { x, y, active } = props
> 
>   if (active) return (
>     <g>
>       <line x1={x} y1={0} x2={x} y2={500} stroke="#777777" stroke-dasharray={3} />
>       <circle cx={x} cy={y} r="3" fill="#ffffff" />
>     </g>)
>   
>   return
> }
> <VictoryChart
>       containerComponent={
>         <VictoryVoronoiContainer
>           voronoiDimension="x"
>         />
>       }
>     >
>       <VictoryLine
>         style={{
>           data: { stroke: '#c43a31' },
>           parent: { border: '1px solid #ccc' },
>         }}
>         data={data}
>       />
>       <VictoryScatter data={data} dataComponent={<CirclePoint />} />
>     </VictoryChart>
> ```

Does anyone know how to achieve this in TypeScript? @dev-justtrade

**Comment by thclaes** [comment]
> > @julia-hitiq You can archieve that by using a scatter plus a line chart graph wrapped with a voronoicontainer (to make the scattered points active) and then render a custom dataComponent to create the circle with the vertical line.
> > ```
> > const CirclePoint = props => {
> >   const { x, y, active } = props
> > 
> >   if (active) return (
> >     <g>
> >       <line x1={x} y1={0} x2={x} y2={500} stroke="#777777" stroke-dasharray={3} />
> >       <circle cx={x} cy={y} r="3" fill="#ffffff" />
> >     </g>)
> >   
> >   return
> > }
> > <VictoryChart
> >       containerComponent={
> >         <VictoryVoronoiContainer
> >           voronoiDimension="x"
> >         />
> >       }
> >     >
> >       <VictoryLine
> >         style={{
> >           data: { stroke: '#c43a31' },
> >           parent: { border: '1px solid #ccc' },
> >         }}
> >         data={data}
> >       />
> >       <VictoryScatter data={data} dataComponent={<CirclePoint />} />
> >     </VictoryChart>
> > ```
> 
> Does anyone know how to achieve this in TypeScript? @dev-justtrade

Have you found the type of the props of circlePoint?
