### ISSUE TITLE
VictoryLabel ignores angle property when used as an axis label component

### ISSUE THREAD

**Issue by tebs1200** [FormidableLabs/victory#1145]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When used in a custom label component for VictoryAxis via `tickLabelComponent`, the `angle` property appears to be ignored.

The [documentation for VictoryLabel](https://formidable.com/open-source/victory/docs/victory-label/#angle) indicates that an angle prop should be used to modify the angle, but when it is specified it doesn't seem to have any impact on the label rotation.

### Reproduction

I've reproduced the issue in  [this sandbox](https://codesandbox.io/s/n0q6lmmj20).

On line 13, i've specified a numeric value of 45 for the label's angle, but the labels don't have any rotation applied.

**Comment by boygirl** [comment]
@tebs1200 thanks for the reproduction. That helps a ton. I'll take a look and try to get a fix out for you this week.

**Comment by boygirl** [comment]
@tebs1200 actually, I took a closet look at your sandbox, and I think the problem is not in Victory.

Your custom label currently:
```
const CustomTickLabel = props => {
  return <VictoryLabel angle={45} {...props}  />;
};
```
When you spread props _after_ `angle` the props supplied to `VictoryLabel` by `VictoryAxis` will override your angle (`VictoryAxis` will define a default angle).  Instead try:

```
const CustomTickLabel = props => {
  return <VictoryLabel angle={45} {...props}  />;
};
```

or even simpler ` tickLabelComponent={<VictoryLabel angle={45} />}`

**Comment by tebs1200** [comment]
Thanks!

switching the angle to be after the spread operator fixed the issue. Makes perfect sense in hindsight. Interestingly, I did check `props.angle` and it was undefined so I thought the order wouldn't matter. Looks like I need to do a bit more reading on the intricacies of the spread operator.

My code is a a simplified version of a more complex custom label so the first option (wrapping the label in a component) is what I'm after.

Thanks once again.
