### ISSUE TITLE
Events on VictoryScatter are not working as expected with dataComponent prop set

### ISSUE THREAD

**Issue by robinwkurtz** [FormidableLabs/victory#1146]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm unable to get any sort of response with events when using `dataComponent` on a `VictoryScatter`. If I remove the `dataComponent` prop I get results as expected.

I'm using `dataComponent` to influence the color of the dots... If there is a better way to adjust the color of the dot based on the value with outside logic or with another key within the data itself, I'm happy to drop `dataComponent`.

```
<VictoryScatter
    data={this.props.data}
    dataComponent={<ColorDots {...this.props} />}
    events={[{
        target: "data",
        eventHandlers: {
            onClick: () => {
                console.log('click');
                return [
                    {
                        target: "data",
                        mutation: (props) => {
                            console.log(props);
                            const fill = props.style && props.style.fill;
                            return fill === "black" ? null : { style: { fill: "black" } };
                        }
                    },
                ];
            }
        }
    }]}
/>
```

I've also tried to add an onClick within my `dataComponent` but that doesn't seem to work either.

```
class ColorDots extends React.Component<Props> {
  render() {
    const { x, y, datum } = this.props; // VictoryScatter supplies x, y and datum
    return (
      <Point
        size={1}
        x={x}
        y={y}
        onClick={() => console.log("Point click", datum._y)}
      />
    );
  }
}
```

Thanks!

### Reproduction

https://codesandbox.io/s/l7z1pmx7o9

Console logs are not showing up in Sandbox UI but within the browsers console...

# Feature Requests

### Checklist

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@robinwkurtz 

When you use a custom component, be sure that you are proxying all the props it needs from its parent like so:

```
class ColorDots extends React.Component<Props> {
  render() {
    return (
      <Point
        {...this.props} // all the props provided by VictoryScatter
        size={4} // Any overrides
      />
    );
  }
}
```
Here's an edit to your codesandbox so you can see it working: https://codesandbox.io/s/lxypw564wm

Also, to simplify your app, you can color your points individually without using a custom components by using the style prop like so: 

```
<VictoryScatter
  style={{ data: { fill: (d) => d.y > 2 ? "red" : "green" } }}
  ...
/>
```
