### ISSUE TITLE
Define color of each slice of Pie Chart

### ISSUE THREAD

**Issue by rweller59** [FormidableLabs/victory#1151]
I am trying to figure out the data model for defining the color of each slice of pie. Assume I have a data array = [{1,y}, {2,y}...] and creating pie chart based on y values. I would like to define a color for each data point. Could you please give me some insight on what the setup might look like.

```
<VictoryPie
      data={data}
      style={{
        data: {
          myColorStyle
        }
      }}
    />
```

Sorry, just discovered the ColorScale attribute:
```
<VictoryPie
      data={data}
      colorScale={["black", "red", "green", "#4cc9ff", "navy","black", "red", "green", "#4cc9ff", "navy",
      "black", "red", "green", "#4cc9ff", "navy","black", "red", "green", "#4cc9ff", "navy","black", "red", "green", "#4cc9ff", "navy" ]}
    />
```

**Comment by boygirl** [comment]
@rweller59 

You can also use functional styles to determine a color based on the y value of each data point like so:

```
<VictoryPie
  data={data}
  style={{
    data: { fill: (d) => myColorFunction(d.y) } 
  }}
...
/>
```
where `myColorFunction` should return a color name / hex string

**Comment by junhyuk-prestolabs** [comment]
```
<VictoryPie
  data={data}
  style={{
    data: { fill: ({ datum }) => myColorFunction(datum.y) } 
  }}
...
/>
```

slight typo
