### ISSUE TITLE
Bar Centering issue with Single Bar 

### ISSUE THREAD

**Issue by andrewhathaway** [FormidableLabs/victory#1153]
Following on from #722, @boygirl I think this issue has arisen again? I'm seeing this issue using the code below:

```
<VictoryChart data={[{ y: 150, x: new Date() }]} >
  <VictoryAxis 
    dependentAxis 
    orientation="left"
  />
  <VictoryAxis orientation="bottom" />
  
  <VictoryBar 
    style={{ data: { fill: "#c43a31", width: 200 } }}   
  />
</VictoryChart>
```

![image](https://user-images.githubusercontent.com/1188830/47268523-17e54e00-d54a-11e8-8c94-84cda3ee24fe.png)

Oddly, when using the following code:

```
<VictoryChart data={[{ y: 150, x: 1 }]}>
  <VictoryAxis 
    dependentAxis 
    orientation="left" 
  />
  <VictoryAxis 
    orientation="bottom" 
    tickValues={[1]} 
    scale="linear"
  />

  <VictoryBar  style={{ data: { fill: "#c43a31", width: 200 } }} />
</VictoryChart>
```

It renders the following:

![image](https://user-images.githubusercontent.com/1188830/47268616-f9cc1d80-d54a-11e8-800d-1d06863612f8.png)

But, change x from 1 to 1000 and:

![image](https://user-images.githubusercontent.com/1188830/47268628-1405fb80-d54b-11e8-9d0b-de7d3a5f24b7.png)

**Comment by boygirl** [comment]
@andrewhathaway Victory expects the data prop to be supplied to children of `VictoryChart`, and not to the chart itself. Give this a shot:

```
<VictoryChart>
  <VictoryBar
    data={[{ y: 150, x: new Date() }]} 
    style={{ data: { fill: "#c43a31", width: 200 } }}
  />
</VictoryChart>
```

**Comment by boygirl** [comment]
It does look like there's an issue with centering dates, though

**Comment by andrewhathaway** [comment]
Also the second example of changing `x` from `1` to `1000`?
