### ISSUE TITLE
When Axis tickFormat is an array, ZoomContainer causes the wrong tick labels to be shown

### ISSUE THREAD

**Issue by FlickStuart** [FormidableLabs/victory#1154]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When:
* using an time/date based axis with an array of pre-formatted labels for ticks, and
* using a zoom container the covers fewer than all of the ticks/data charted
the the tickValues do no longer line up with their equivalent position in tickFormat.

In the case of the fiddle below, month based ticks are correct based on the last two values in tickValues, but the labelling from tickFormat uses the first two values (n.b. there are a total of three ticks/labels).

This behaviour seems to have changed between versions 0.23.x and 0.24.0 - i.e. 0.23.0 it worked as expected.

### Reproduction

https://jsfiddle.net/ocx1zmL9/26/

Moving the map function from line 100 to the tickFormat property on line 159 will resolve the issue in this case - though computing labels on the fly isn't always possible.

Compared to v0.23.0
https://jsfiddle.net/c39186br/

**Comment by boygirl** [comment]
@FlickStuart would it possible to use a function for your tickValues like so:
`tickFormat={(value) => format(value, 'MMMM YYYY')}`. 
When I change that line, both fiddles behave in the same way. 

I did notice that the fiddle you have linked as `0.23.0` behaves _incorrectly_ compared to the other fiddle (axis ticks are incorrect compared to data)

**Comment by FlickStuart** [comment]
Using a function does work well (I should have highlighted that - sorry!).
It's really a bug that affects the use of a pre-formatted set of labels with a date based axis. (Sometimes it's not feasible to just format a date - though I suspect it's uncommon for everyone else).

Apologies - not sure what I did with those fiddles, but there were in a confusing/broken state - hopefully this makes the 'start of the month marker' (mis)alignment clearer:

Uses victory v30.5.0 https://jsfiddle.net/c39186br/1/ - start of date markers are 1 month out
![image](https://user-images.githubusercontent.com/39475167/48237676-8f611b80-e42c-11e8-8524-3ef1b1b01ca1.png)

Uses Victory v0.23.0 https://jsfiddle.net/c39186br/2
![image](https://user-images.githubusercontent.com/39475167/48237731-d7803e00-e42c-11e8-93b9-24b13e946d71.png)
