### ISSUE TITLE
Adding a container clips right side of chart

### ISSUE THREAD

**Issue by rossdack** [FormidableLabs/victory#1157]
I've defined a simple candlestick chart which renders as:

![screen shot 2018-10-24 at 12 51 21 pm](https://user-images.githubusercontent.com/34684873/47401245-42bee480-d78c-11e8-9d4e-6465394d81e8.png)

Specifying a container (to enable zoom for example) truncates the last candlestick, like so:
![screen shot 2018-10-24 at 12 58 51 pm](https://user-images.githubusercontent.com/34684873/47401327-97625f80-d78c-11e8-9685-72e3e122caf5.png)

```
<VictoryChart
                width={this.state.chartWidth}
                height={450}
                candleWidth={55}
                theme={VictoryTheme.material}
                scale={{ x: 'time' }}
                standalone
                domainPadding={{ x: 25 }}
                containerComponent={<VictoryZoomContainer style={{paddingRight: 100}} 
              >
...
```

Is this an issue or simply a usage error?

**Comment by boygirl** [comment]
@rossdack `VictoryZoomContainer` adds a clipPath to the chart area so that anything rendered outside of it wont show. This is how zooming out is accomplished. 

You can add padding to the clipPath it renders like so:

```
...
 containerComponent={
  <VictoryZoomContainer 
    clipContainerComponent={<VictoryClipContainer clipPadding={{ left: 10, right: 10 }} />}
  />
}
```
