### ISSUE TITLE
Multiple datasets with pie chart

### ISSUE THREAD

**Issue by rweller59** [FormidableLabs/victory#1160]
Is it possible to render multiple pie charts with the same center point in same container - an inner pie with an outer pie defining an inner radius > outer radius of inner pie. Thought I could do this wrapping with VictoryChart but its not compatible with pie chart.

**Comment by boygirl** [comment]
@rweller59 you can use `VictoryBar` with `polar` instead of `VictoryPie`. Here's a bit more detail: https://formidable.com/open-source/victory/docs/victory-bar/#polar

**Comment by boygirl** [comment]
@rweller59 Yes! something like that. You can use the `VictoryStack` wrapper to potentially make your life a bit easier, too. Let me know if you have any trouble getting it to work
