### ISSUE TITLE
VictoryStack horizontal and tooltips

### ISSUE THREAD

**Issue by horaceklai** [FormidableLabs/victory#1161]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

When making a horizontal VictoryStack, tooltips end up making my bars fatter when hovered upon

<VictoryChart
              domain={{ x: [0, 11], y: [-10, 10] }}
            >
            <VictoryStack>
              <VictoryBar
                labelComponent={
                  <VictoryTooltip/>
                }
                data={[
                  {x: 2, y: 5, label: "right-side-up"},
                  {x: 4, y: -6, label: "upside-down"},
                  {x: 6, y: 4, label: "tiny"},
                  {x: 8, y: -5, label: "or a little \n BIGGER"},
                  {x: 10, y: 7, label: "automatically"}
                ]}
              />
            </VictoryStack>
            </VictoryChart>

vs.

<VictoryChart
              domain={{ x: [0, 11], y: [-10, 10] }}
            >
            <VictoryStack horizontal>
              <VictoryBar
                labelComponent={
                  <VictoryTooltip/>
                }
                data={[
                  {x: 2, y: 5, label: "right-side-up"},
                  {x: 4, y: -6, label: "upside-down"},
                  {x: 6, y: 4, label: "tiny"},
                  {x: 8, y: -5, label: "or a little \n BIGGER"},
                  {x: 10, y: 7, label: "automatically"}
                ]}
              />
            </VictoryStack>
            </VictoryChart>

**Comment by boygirl** [comment]
@horaceklai I wasn't able to reproduce this issue locally using the latest version of Victory. I'm going to close this issue, but I will re-open it if you can provide a codesandbox reproduction or more steps to reproduce the issue.
