### ISSUE TITLE
VictoryLine doesn't line up with VictoryArea when you use domainPadding

### ISSUE THREAD

**Issue by scottdickerson** [FormidableLabs/victory#1165]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

If you graph a VictoryArea graph and a VictoryLine on the exact same data, they no longer line up, the VictoryLine seems like it's incorrectly being graphed "off" the y-value by a little bit when graphed on the same chart as a VictoryArea with a domainPadding value

Here's a picture of what it looks like, these are 3 different graphs on the same chart all using the same data, one VictoryArea, then two VictoryLine graphs on the top and bottom line of the VictoryArea:
![image](https://user-images.githubusercontent.com/6663002/47675609-6ae18580-db88-11e8-8ccd-151866ca3c2a.png)

On previous versions of victory (0.24) this looked good

### Reproduction

https://codesandbox.io/s/x6844601q

If you remove the domainPadding from the line props, the Line graphs renders correctly.

https://codesandbox.io/s/k2l1lwn565

**Comment by boygirl** [comment]
@scottdickerson `domainPadding` should be added to the outermost Victory component. In your case `VictoryChart`
