### ISSUE TITLE
TypeError: Reduce of empty array with no initial value with fixLabelOverlap and string values

### ISSUE THREAD

**Issue by HighSoftWare96** [FormidableLabs/victory#1167]
# TypeError: Reduce of empty array with no initial value with fixLabelOverlap and strings as x labels
### Checklist

* [-] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [-] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [-] I am using the latest version of Victory

* [-] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction
            <VictoryChart
              height={230}
              containerComponent={<VictoryZoomContainer zoomDimension="x" />}
              theme={VictoryTheme.material}
            >
              <VictoryAxis
                fixLabelOverlap={true}
              />
              <VictoryAxis dependentAxis />
              <VictoryArea
                data={[
                  {
                    x: "test1",
                    y: 12
                  },
                  {
                    x: "test2",
                    y: 30
                  }
                ]}
                x="x"
                y="y"
              />
            </VictoryChart>
            
### Checklist

* [-] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [-] I've searched open issues to make sure I'm not opening a duplicate issue

### Description
This problem occurs when I have string values for an axis of the graph, at the same time I use the prop fixLabelOverlap={true} and I try to zoom in the graph. This problem is occurs also in Victory native. 

How can I use fixLabelOverlap  to avoiding label overlap  and VictoryZoomContainer with data that have strings values?

**Comment by boygirl** [comment]
👍 @nikofrezz will you PR this change?

**Comment by nikofrezz** [comment]
Done!
