### ISSUE TITLE
minDomain / maxDomain props missing in type definitions

### ISSUE THREAD

**Issue by Ricki-BumbleDev** [FormidableLabs/victory#1168]
The props minDomain and maxDomain cannot be used when using TypeScript as they do not exist in the respective type definitions.

We currently use the following work around:
```
<VictoryChart
      {...{minDomain: {y: 29} as any}}
>
```

**Comment by boygirl** [comment]
@Ricki-BumbleDev I'm going to close this issue and reference it from the larger issue: https://github.com/FormidableLabs/victory/issues/1033
