### ISSUE TITLE
Numbers on Y axis should be in scientific notation if too long

### ISSUE THREAD

**Issue by bramvbilsen** [FormidableLabs/victory#1170]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am using very precise data, thus my floats can get very long. When I try to plot such data with labels on the Y axis, the labels get cut off because they are too long.

![screenshot from 2018-10-30 23 51 26](https://user-images.githubusercontent.com/16825392/47755493-be45f780-dc9e-11e8-825c-9d375d76ac85.png)

### Reproduction

https://codesandbox.io/embed/zrx1x221y3

# Feature Requests
It would be nice if there was a way to deal with this. For example, using the scientific notation if there is not enough room. Or perhaps allowing the user to provide alternative strings for the X values (I searched for this last option in the docs but did not find anything).

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by boygirl** [comment]
@bramvbilsen You can format your axis labels using the `tickFormat` prop on `VictoryAxis`. Here's a bit more information: https://formidable.com/open-source/victory/docs/victory-axis/#tickformat
