### ISSUE TITLE
VictroyBrushContainer drag problem if resizing VictoryChart

### ISSUE THREAD

**Issue by endwaa** [FormidableLabs/victory#1173]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

If you select an area with BrushContainer, then resize the screen and updates the VictoryChart component with the new width, the brush box will be able to move to its "old" width size. So if the screen width becomes less, the box will appear outside the chart. Similar if the screen is resized to a larger screen width, the box will not reach the end of the chart.

![bilde](https://user-images.githubusercontent.com/8463735/47951340-abae1580-df5f-11e8-85d6-db4386fd667c.png)
![bilde](https://user-images.githubusercontent.com/8463735/47951343-aea90600-df5f-11e8-819b-c91118c82960.png)

In both images the brush box is dragged to its end.

### Reproduction

Here is a codesandbox example: https://codesandbox.io/s/8489wypn28

**Comment by boygirl** [comment]
@endwaa Thanks for the reproduction, that helps a ton. I have some thoughts on what might be going on (caching some values related to the bounds).

**Comment by ferdaber** [comment]
For those who are still experiencing this issue, a quick fix is assigning a `key` to the component that renders the `<VictoryBrushContainer />` element so that all state is reset when the chart is resized.

**Comment by Kromtar** [comment]
> For those who are still experiencing this issue, a quick fix is assigning a `key` to the component that renders the `<VictoryBrushContainer />` element so that all state is reset when the chart is resized. An obvious one to use is the pixel value of your chart width (`key={width}`)

Thank you very much, you saved me from doing something very silly

**Comment by becca-bailey** [comment]
Closing in favor of #2111
