### ISSUE TITLE
Veroni Tool Tips not Working in External Window

### ISSUE THREAD

**Issue by cullenmcmahon** [FormidableLabs/victory#1176]
# Bugs and Questions

### Checklist

* [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ x] I am using the latest version of Victory

* [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Interesting sharing state issue when combining externalWindow/createportal and Victory.  I'm following this guide ( https://hackernoon.com/using-a-react-16-portal-to-do-something-cool-2a2d627b0202 ) but inserting victory in instead of a button.  Tooltips work in the base version, but in the new window they don't.

### Reproduction

https://codesandbox.io/s/qvwxm6p76

**Comment by boygirl** [comment]
@cullenmcmahon 

Very weird. I will have to take a closer look. Thank you for the reproduction.
