### ISSUE TITLE
add repetitive objects count to victory bar

### ISSUE THREAD

**Issue by hasanagh** [FormidableLabs/victory#1179]
For a certain data format it could be useful to view the repetition of an object added and viewed in a box plot:

for example,
[{"date":"2015-09-25","id":1},
{"date":"2015-09-25","id":2},
{"date":"2015-09-25","id":3},
{"date":"2015-09-25","id":4},
{"date":"2015-09-26","id":5},
{"date":"2015-09-30","id":6},
{"date":"2015-09-30","id":7}]

with this type of data, we could specify a value to count for its repetitions and then well have three bars 
1- 2015-09-25: value 4
2- 2015-09-26: value 1
3- 2015-09-30: value 2

**Comment by boygirl** [comment]
@hasanagh I think this is something that is a bit too specific to be built into Victory. Instead, it should be accomplished by processing your data before providing it to `VictoryBar`
