### ISSUE TITLE
Addional element line in VictoryLine chart

### ISSUE THREAD

**Issue by johnreytanquinco** [FormidableLabs/victory#1180]
In my chart I have 2 lines. One is an infinite horizontal line and the other with an arrow.
And to my question, is it possible to render a line with an arrow in VictoryLine component? Also, in addition, I would want to have a box(gray) below of the infinite line.

**The expected image is this one.**
![screenshot from 2018-11-12 20-21-35](https://user-images.githubusercontent.com/7284893/48347232-a156ee80-e6b8-11e8-80e8-0c3d06deec33.png)

**Actual/current result:**
![screenshot from 2018-11-13 10-24-50](https://user-images.githubusercontent.com/7284893/48386867-6db6ab80-e72e-11e8-8db6-03a98219011a.png)

**Comment by boygirl** [comment]
@johnreytanquinco Unfortunately there isn't an arrow component in Victory, but you can create a custom dataComponent for VictoryLine that renders both the line and an svg path element for the arrow head. Here's a guide that should help you get started with custom components: https://formidable.com/open-source/victory/guides/custom-components/

As for the gray box, you can accomplish that with `VictoryArea`

**Comment by johnreytanquinco** [comment]
@boygirl Thanks for your response.

But is it possible to just append the custom `dataComponent` inside VictoryLine? The reason behind is because my `x` value is in `Date` type and is already plotted correctly.

**main.js**
```
<VictoryLine
  style={{
    data: { stroke: '#c43a31' },
    parent: { border: '1px solid #ccc' }
  }}

  labels={['']}
  animate={{ duration: 0, onLoad: { duration: 0 } }}
  data={[
    { x: x1, y: y1 },
    { x: x2, y: y2 }
  ]}
  dataComponent={<Arrow />}
/>
```

This is my custom component:
**Arrow.js**
```
import React, { Component } from 'react'
import Svg, { Path } from 'react-native-svg'

export default class Arrow extends Component {
  render() {
	  return (
	  	<Svg height="100" width="100">
		    <Path d="M2 2 L2 11 L10 6 L2 2" stroke="black" />
		  </Svg>
	  );
	}
}
```
**PS:** Im just a newbie to RN and would appreciate your help. Thank you in advance

**Comment by boygirl** [comment]
@johnreytanquinco you have a couple options:

The best way to do it is to probably use a marker and `marker-end` but I'm not certain it's supported in `react-native-svg`. Here's the web version:
https://codesandbox.io/s/jznz8721y9

If that isn't working in RN, you can make your own path like so:
https://codesandbox.io/s/x5m74nzro

**Comment by johnreytanquinco** [comment]
@boygirl Thank you so much for your help.
The below example works for me:
>If that isn't working in RN, you can make your own path like so:
>https://codesandbox.io/s/x5m74nzro

Result:
![screenshot_20181122_132752](https://user-images.githubusercontent.com/7284893/48883374-87f13780-ee5a-11e8-8310-6ecb80249334.jpg)


The arrow head renders at the end of the line in my chart but not sure how to create a perfect arrow path and make it match to the direction of the line.

But this arrow head below looks perfect shape for me and is also following the direction of the line, still need to know to to accomplish this one using the first link above:
>https://codesandbox.io/s/jznz8721y9

I want to do it something like this.
![screenshot from 2018-11-22 13-26-20](https://user-images.githubusercontent.com/7284893/48883330-495b7d00-ee5a-11e8-81ff-13e5b0f63c49.png)

**Comment by boygirl** [comment]
@johnreytanquinco the markerEnd solution is really what you want. If you can't get the `Defs` / `markerEnd` solution working in `victory-native` / `react-native-svg` you will have to manually place and rotate your path so that it lines up with your arrow. You do have access to the `data` prop from your custom `data` component so you will be able to calculate the slope of the last two points of your line and determine the angle from there.

**Comment by johnreytanquinco** [comment]
@boygirl thank you for your response. Will just look on how I can calculate the scope of the two points of the line and create the arrow head.

Sorry for too much asking, but is there a support in VictoryLine to achieve an infinite line? Say I have and 2 points(x and y values), and I would like to generate a horizontal infinity line from it. 

Grayline is the expected output:
![](https://user-images.githubusercontent.com/7284893/48386867-6db6ab80-e72e-11e8-8db6-03a98219011a.png)
