### ISSUE TITLE
Grid lines overlay bars in example guide

### ISSUE THREAD

**Issue by zsherman** [FormidableLabs/victory#1183]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

It appears that grid lines are stacking on top of the actual graphs, I see this when following the getting started guide:

![image 2018-11-14 at 12 40 05 pm](https://user-images.githubusercontent.com/1152279/48501201-a7f57b00-e80a-11e8-8386-bdf3135bec19.png)

### Reproduction

I implemented the same example here and cannot seem to reproduce https://codesandbox.io/s/nwqom6o3wm 😕 

 I assumed there may have been some style conflicts locally (simply using storybook, which puts things in an iframe with no additional styles) so I double checked and everything looks *exactly* the same, no additional styles are being applied and I'm a bit confused as to what would cause this. As far as I know z-index isn't really applicable to svgs and the stacking is done differently.

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Thanks

Just wanted to also say thank you to @boygirl for your consistently hard work on an awesome library.

**Comment by boygirl** [comment]
@zsherman It's purely render order dependent, so if you put your axis children after the other children they will end up on top. Check it out: https://codesandbox.io/s/43vwn5zy3x

**Comment by zsherman** [comment]
🤦‍♂️ thank you!
