### ISSUE TITLE
animationWhitelist as a prop

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#1186]
_From @bear-junior on November 17, 2018 9:46_

Hi! :)

Is there any chance that animationWhitelist will be a prop for all charts with animate? Sometimes I don't want to have style animation, it's laggy sometimes, but for example I want to animate only height of bars and I have opacity on it, but I don't want to animate opacity.

_Copied from original issue: FormidableLabs/victory-native#418_

**Comment by boygirl** [comment]
@bear-junior Thanks for this issue. I think it's a good idea. I'm going to move this to the main victory repo, though since the work will be done there.

**Comment by boygirl** [comment]
This feature involves adding an `animationWhitelist` prop to all components that animate. When this prop is not provided, the existing fallback will be used.

**Comment by bear-junior** [comment]
🙏🏻🙏🏻🙏🏻

**Comment by michaelbridge** [comment]
👍 👍 👍

**Comment by boygirl** [comment]
Released as `victory@31.1.0`
