### ISSUE TITLE
Styling ticks in VictoryGroup

### ISSUE THREAD

**Issue by charklewis** [FormidableLabs/victory#1190]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

No styling of ticks is working when VictoryAxis is a child of VictoryGroup. I saw this note in the guides, does this mean you are not able to style ticks in this context?

> when a component is rendered as a child of another Victory component, or within a custom <svg> element with standalone={false} parent styles will be applied to the enclosing <g> tag. Many styles that can be applied to a parent <svg> will not be expressed when applied to a <g>.

I am looking to remove the axis line, change the tick labels (Jan, Feb etc) to a grey colour and enlarge their font size. 

### Reproduction

View sandbox here: https://codesandbox.io/s/xo162p56xp
_Style code adapted from: https://github.com/FormidableLabs/victory/issues/408_

**Comment by boygirl** [comment]
@charklewis I took a look at your sandbox, and the main issue was that `this.tickStyles` was not defined. Also, when you're using axes, it's better to use `VictoryChart` instead of `VictoryGroup` since it is designed to account for axis children. Here's an edited sandbox: https://codesandbox.io/s/xzv9v4y8wz
