### ISSUE TITLE
VictoryLine y-values change when new data points are added

### ISSUE THREAD

**Issue by hochmanjoel** [FormidableLabs/victory#1192]
* [Unsure ] This is a `victory-native` specific issue.
* [Yes] I have read through the FAQ
* [Yes] I am using the latest version of Victory
* [Yes] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`.
* [Absolutely] I've searched open issues to make sure I'm not opening a duplicate issue

Problem: I am trying to make a simple line graph that updates when I select new data. My VictoryLine does not appear to be recognizing my y-axis (VictoryAxis) as the dependent axis. In fact, the line functions almost the same when I completely remove both axis components. I am unsure how to get my line to reliably graph based on the actual given data. Specifics below.

Reproduction
System:
react-native: 0.55.4
react-native-svg: 6.5.0
victory-charts: 0.0.1
victory-native: 31.0.0

I am using the prop `allData` to pass in part of a redux store. The default redux store is structured:
![image](https://user-images.githubusercontent.com/22176573/49225737-bfbd2980-f3dc-11e8-9de7-1bc75abebbc3.png)

The two default points do not automatically appear on the graph (even when domains are removed from the axes). If I were to select 1, the graph would appear to start at 10 and go towards 1. If I were then to select 10, the y-intercept would move down towards 5 where it is supposed to be. Example images below:
![image](https://user-images.githubusercontent.com/22176573/49225921-2fcbaf80-f3dd-11e8-8d9d-75669c4f1ef3.png)
![image](https://user-images.githubusercontent.com/22176573/49225937-33f7cd00-f3dd-11e8-9b95-a72d49a7d74f.png)

Here is the code I am working with:
`import React from 'react';
import { View, StyleSheet, Text } from 'react-native';
import Svg from 'react-native-svg';
import { VictoryAxis, VictoryLine } from 'victory-native';

const MoodGraph = ({ allData }) => {

		return(
			<View>
				<Svg>
		        	<VictoryAxis //Select domain that works absolute then can eventually be filtered by range
		        		domain={{x: [new Date(2018, 11, 29, 13), new Date(2018, 11, 29)]}} //set domain to exclude first two state points (so victory line works with no visual errors)
		        		scale="time"
		        		standalone={false}
		        	/>
		        	<VictoryAxis dependentAxis
		        		domain={[0, 10]} //Adjust picker to selected domain
		        		orientation="left"
		        		standalone={false}
		        	/>
		        	<VictoryLine //Need this line to graph mood over time, experimenting with dif domains
		        		style={{ data: { stroke: "#000FFF"}}}
		        		data={allData}
		        		x="date"
		        		y= "rating" 
		        		scale= {{x: "time", y: "linear"}}      		
		        	/>
				</Svg>
			</View>
		);
	
};

const styles = StyleSheet.create({
	parent: {
		backgroundColor: "#000000",
		padding: 0
	},

});

export default MoodGraph;`

This is driving me crazy. Please help!!

**Comment by boygirl** [comment]
@hochmanjoel you should use the `VictoryChart` wrapper to keep the `domain` in sync between your axis and line components.

**Comment by hochmanjoel** [comment]
@boygirl That worked, but how would I turn off the visibility of the axes? Would I just set their color to #FFFFFF?
