### ISSUE TITLE
Export default styles from components

### ISSUE THREAD

**Issue by rudasoftware** [FormidableLabs/victory#1196]
# Feature Requests

### Checklist

* [Yes ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [Yes ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

It would be nice to export the default styles of components so they can be used as defaults for calculations.

The internal merging behavior is very good (allowing `theme`, adding styles at call site, receiving styles from parent(s), etc.), but the *result* of that merge is not inspectable. It only exists after rendering, and is closed over by the component (i.e. instantiating the component before `return` in render and looking at its `props.style` will NOT give the final style).

For instance, if I wanted to use `TextSize.approximateTextSize` on a `VictoryLabel` that is a first-level child of a `VictoryChart`, it will receive *only* its `defaultStyles` since it is not modified by `theme` or another enclosing component. I could copy and paste, but that is less maintainable and gets my DRY senses tingling.

I have thought about trying to drill into the inner `TSpan`, but it isn't a regular child (in the `props.children` sense). It is possible that some `ref` trickery might work, but that seems nontrivial to me (and it feels like another less maintainable monstrous hack).

I understand the desire to not export everything (encapsulation and whatnot), but I think this would be *less* potentially future-breaking than the copy-paste alternative. Also, it's not exposing "behavior" per se, because it's a value and not a function.

**Comment by rudasoftware** [comment]
Oh dear, I think I misunderstood the purpose of `getBaseProps` static methods.

It looks like the purpose of making them `static` was to pseudo-export component helper methods and default properties by allowing us to pass props and do more or less what I described?

Is that the case? If so, can that be added to the documentation somewhere? (It may already be there. If so, I totally missed it :/  )

**Comment by boygirl** [comment]
@rudasoftware I think this issue is actually specific to `VictoryLabel` which is a bit of an odd component since it doesn't do any theme merging. Would it solve your problem to add `defaultStyles` as a static on the component class? If so, that's a pretty simple and consequence free change.

**Comment by rudasoftware** [comment]
@boygirl, Yeah, that sounds very simple and sensible :)

I ran into this issue when trying to use a bare `VictoryLabel` not wrapped in anything that would attach to `theme`, so I guess that covers current (and currently conceivable) use cases.

**Comment by boygirl** [comment]
@rudasoftware Want to PR this change?

**Comment by rudasoftware** [comment]
Sure! I broke down and finally cloned a local repo recently, because I got tired of searching through the github source without a convenient `Go to Declaration` or `Find Usages`.

**Comment by rudasoftware** [comment]
Hmm, I could move the definition of `defaultStyles` into the class, or I could just `static defaultStyles = defaultStyles`.

The latter seems great, because no other changes are required, no additional `this` cluttering up methods that reference it... potentially at the expense of obviousness/ambiguity.

**Comment by boygirl** [comment]
I prefer `static defaultStyles = defaultStyles`

**Comment by rudasoftware** [comment]
Awesome! Me too.

**Comment by boygirl** [comment]
No tests required since this won't change any behavior. If you want you could add one asserting that an instance has that static, but I would accept the PR without

**Comment by rudasoftware** [comment]
Hmm, that seems kind of silly because it won't actually test anything "real". So yeah, I agree, I'll pass on that.

So, do people here usually submit PRs with a topic branch? I'm pretty new to OSS contribution...

**Comment by boygirl** [comment]
Yep, please fork and branch. I'm working in making this project friendlier for first time contributors, so thank you for asking. I would love to hear about anything else that is unclear or confusing.
