### ISSUE TITLE
VictoryLegend auto `itemsPerRow` based on desired width

### ISSUE THREAD

**Issue by rudasoftware** [FormidableLabs/victory#1197]
# Feature Requests

### Checklist

* [Yes ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [Yes ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Often, I my intentions are less "I want a specific number of items per row/column in a legend" and more "I want as many items in a row/column as it takes to not overflow a certain width/height" (depending on horizontal/vertical orientation).

As the number and length of items are typically not known in advance, devs have to either make their own automatic behavior or force the end user to manually specify `itemsPerRow` with a textbox or something.

Implementation would likely require a new `legendWidth` prop to disambiguate from `width` that drives the container component. Probably a width/height-neutral term? But `itemsPerRow` already implicitly means `itemsPerColumn` when `orientation={'vertical'}` (which is the default?)? Eh, semantics. I'd acquiesce to whatever is deemed "least surprising".

I currently have a (rather naive) wrapper that solves the problem iteratively, without accounting for is-title-inline-with-desired-dimension, assuming desired dimension to be whole-svg `width` minus whole-svg left/right `padding`.

I think you basically *have* to work iteratively, since all the fields in a column share the (max) length. Thus, the maximum row length isn't trivial to calculate in closed form.

I think it would be possible to adapt the approach into `VictoryLegend` itself.
With sufficient guidance on high-level architecture concerns and on test design, I'd love to help contribute to this!

**Comment by boygirl** [comment]
@rudasoftware I'd love to see your wrapper so I can get more of an idea on of how you'd expect this to work. I think at a minimum adding `legendWidth` and `legendHeight` props would be appropriate. When provided these could _determine_ the `itemsPerRow` if it was not provided. This seems like the least breaking API change. Would that work for you, or are you expecting more control?

**Comment by rudasoftware** [comment]
@boygirl, That prop interface sounds very appropriate!

I'll see if I can extract a clean JSFiddle from my design. I'm using `ramda` and recursion because I got bit hard by the FP bug when I migrated to React, haha, but I don't think I'm doing anything that couldn't easily be ported to `lodash`.

**Comment by boygirl** [comment]
<3 lodash

**Comment by rudasoftware** [comment]
GROSS IMPERATIVE, NON-POINTS-FREE-STYLE CODE AAAAAHHHHH
/jokes

**Comment by rudasoftware** [comment]
I think a great addition to contribution guidelines would be a style guide (e.g. use `lodash`, format ternaries/destructuring/newline-groupings like this, etc.) and an explanation of internal architecture (e.g. the rules of thumb for what to put in `modifyProps`, what in `getCalculatedProps`, etc. Order/location of operations kind of stuff).

**Comment by becca-bailey** [comment]
Closing this issue since I do not believe we plan to implement it right now. If you need this feature, PRs are still welcome!
