### ISSUE TITLE
Should shared dependencies live on the archetype or the individual package?

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#120]
This was brought up by @ascariandrea in a recent PR
https://github.com/FormidableLabs/victory-axis/pull/66

Having actual project dependencies (not dev) live on the archetype instead of the project itself might be a source of confusion / difficulty.

**Comment by coopy** [comment]
Currently, the application dependencies live in individual packages.

**Comment by dandelany** [comment]
I strongly feel that all dependencies should be included in the individual packages. IMHO having project dependencies that can't be found in the project's `package.json` is very confusing to those users who don't know about builder/archetypes, and mildly confusing to those that do :)

**Comment by coopy** [comment]
Deps live in the packages for now.
