### ISSUE TITLE
can't use just a Number for VictoryBar's y0

### ISSUE THREAD

**Issue by pkyeck** [FormidableLabs/victory#1201]
I'm using `"victory-native": "^31.0.0"` but it is the same for `victory`.

I don't want to add `y0` to every data-item but set it globally for my `VictoryBar`.
Docs say I can use `type: string || integer || array[string] || function` but doing a `y0={1}` is ignoring the `1` and uses `0` instead.

![screenshot 2018-12-13 at 11 56 12](https://user-images.githubusercontent.com/870980/49934240-1db63a80-fece-11e8-98d1-48baf5ced29c.png)

`y0={() => 1}` is working ...!?

![screenshot 2018-12-13 at 11 56 01](https://user-images.githubusercontent.com/870980/49934241-1db63a80-fece-11e8-90b7-1e5d756b8fc0.png)

Do I understand it correctly? Is this a bug? Or am I supposed to do it like this: `y0={() => 1}`?

**Comment by boygirl** [comment]
@pkyeck yes, you should define it as a function. The integer values are meant for accessing arrays. I will clarify the docs on this point.
