### ISSUE TITLE
React warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by luciomartinez** [FormidableLabs/victory#1205]
# Bugs and Questions

### Checklist

* [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of Victory

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Generation of `key` by name or id creates a new problem at React when multiple Children present. Note that this throws a warning at the console but the result is that only one child (the first one) will be rendered, hence is an actual error present to the user.

Note: I'm pretty sure this is what was happening at #566 but it wasn't so well described at that time.

### Reproduction

[Here](https://jsbin.com/yudawobocu/1/edit?js,console,output) is a small and simple sandbox to reproduce the issue.

# Feature Requests

### Checklist

* [X] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

The `key` must be generated by the component's `key` prop, only when this is not present it should use name or id.

After reviewing the changes at #1062 and digging through the source code, yet I'm not sure where this generation of prop is really happening. Reason why I'm not creating a PR but this issue instead, someone else will probably know much quicker where to make the proper changes.

**Comment by boygirl** [comment]
@luciomartinez thanks for the thorough issue description and reproduction.

**Comment by Sawtaytoes** [comment]
I encountered this tonight. I set `eventKey` to my data point's `id` and that fixed it.

I don't see this specifically documented, but it happened to me when using labels.
