### ISSUE TITLE
Victory-Chart/src/helper-methods.js getCalculatedProps Performance Impact for undocumented(?) feature

### ISSUE THREAD

**Issue by MxFr** [FormidableLabs/victory#1207]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm in the progress of optimizing the performance of the charts we created with victory and came over this lines:
 
https://github.com/FormidableLabs/victory/blob/4cab96636e7b95710dc2caa6cbae5e49afa7f1b6/packages/victory-chart/src/helper-methods.js#L65-L68

The calculation of `stringMap` makes up around a third of our frame time, since it iterates and clones all data for each invocation (`"x"` and `"y"`), to extract the `"xName"` and `"yName"` properties from the data.

How ever I did not found any documentation on these properties and a coursory search for these strings in the code and github issues did not not help either. Since this feature does not look widely used, the easiest fix seems to me to gate it behind a flag in the charts properties.

**Comment by boygirl** [comment]
@MxFr the stringMap calculation is highly necessary as it is used to reconcile categorical data for `VictoryChart` / `VictoryGroup` / `VictoryStack`. Turning it off would break any chart using string data.

**Comment by MxFr** [comment]
@boygirl Ok, I might have missed that since im just using numerical data.

If you dont mind I'll look into creating a pull request that improves the performance of the stringMap creation, as the current looks quite inefficent. It iterates twice over all data using Data.getData(which in turn clones each element using addEventKeys), just to extract two different properties. My current worst case scenario are around 5k datapoints.

From my point of view a number of helper/wrapper methods could be changed in a way that instead of receiving an `axis` parameter, they return an object with both `x` and `y` properties as they are called in most of the times in sequence with both parameters:

https://github.com/FormidableLabs/victory/blob/4cab96636e7b95710dc2caa6cbae5e49afa7f1b6/packages/victory-group/src/helper-methods.js#L23-L26

https://github.com/FormidableLabs/victory/blob/4cab96636e7b95710dc2caa6cbae5e49afa7f1b6/packages/victory-stack/src/helper-methods.js#L107-L110

I assume these helper methods are not considered part of public API, otherwise I'd have to look for a different approach.
