### ISSUE TITLE
Decorator syntax in Babel 6

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#121]
When we upgrade to Babel 6 we will need to figure out what to do with decorator syntax currently in use for Radium. i.e. `@Radium`

options: 
- Avoid decorator syntax: `Radium(MyComponent)`
- Add a babel plugin for legacy decorator support

**Comment by knowbody** [comment]
here is the example on how it can be done with the legacy decorator support https://github.com/FormidableLabs/spectacle/pull/131

**Comment by boygirl** [comment]
We are no longer using Radium, so this is no longer an issue
