### ISSUE TITLE
Typo in Readme FAQ - https://formidable.com/open-source/victory/docs/faq/#how-can-i-annotate-my-charts-with-lines-and-markers

### ISSUE THREAD

**Issue by vedadeepta** [FormidableLabs/victory#1217]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ ] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
Typo in code example in the following FAQ link: https://formidable.com/open-source/victory/docs/faq/#how-can-i-annotate-my-charts-with-lines-and-markers
Buggy Code:
```
<VictoryScatter
    data={[{ x: 5, y: 5, fill: "red", symbol: "star", size: 8 }]}
  />

```
`fill: "red"` won't work as a part of `data` prop it should be a part of `style` prop.
`style={{ data: { fill: 'red' }}}`

### Reproduction
- Go to link https://formidable.com/open-source/victory/docs/faq/#how-can-i-annotate-my-charts-with-lines-and-markers
- The star color is "black"

**Comment by boygirl** [comment]
@vedadeepta Thank you. I will move this issue to `victory-docs` 

I need to update the docs to reflect a change. Victory no longer accepts arbitrary style attrs on the data prop. As a work around, you can still define things like `fill` on your data prop, but you will also need to explicitly reference them from your style object like:

```
<VictoryScatter
    data={[{ x: 5, y: 5, fill: "red", symbol: "star", size: 8 }]}
    style={{ data: { fill: (d) => d.fill } }}
  />
```

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#588
