### ISSUE TITLE
VictoryGruop failed to render updated data

### ISSUE THREAD

**Issue by njiang** [FormidableLabs/victory#1229]
We are developing a data visualization web app based on React, typescript and Victory.  We are using VictoryGroup to display a set of barcharts. The initial rendering works fine.  When we try to filter data with different dimensions, it fails to update the charts.  Below is the code:

public render() {
        var resData = this.props.componentData;
        var dchart = [];

        if (resData.data != null) {
            for (var i = 0; i < resData.categories.length; i++) {
                dchart.push(<VictoryBar data={resData.data[i]} labels={(d) => (d.label)}  style={{ labels: { fontSize: "8px" } }} />);
            }
        }
        if (dchart != null && dchart.length > 0) {
            return (<VictoryChart
                ref="vchart"
                domainPadding={40}
                theme={VictoryTheme.grayscale}
                animate={{ duration: 100 }}>

                <VictoryLegend x={450} y={50}
                    title=""
                    centerTitle
                    orientation="vertical"
                    gutter={10}
                    style={{ border: { stroke: "black" }, title: { fontSize: 8 }, labels: { fontSize: 8 } }}
                    data={resData.legends}
                />

                <VictoryGroup offset={10}
                    colorScale={resData.colors}
                    categories={{
                        x: resData.categories
                    }}
                    padding={15}
                    style={{

                        data: { width: 8 },
                        labels: { padding: 15 },
                    }}
                    labelComponent={<VictoryLabel angle={270} />}
                >

                    {dchart}

                </VictoryGroup>
            </VictoryChart>);
        }
        else {
            return (<div className="text-div">
               You have no data to display. Beep beep!
            </div>);
        }

We set breakpoints and the data was correctly generated, and rendering code was triggered.  We replaced the group with a div to show some dynamic data and it worked fine.  Please suggest what we should do.  

Thanks!

**Comment by Chee7ah** [comment]
Hi @njiang, did you ever find a solution to this issue?

**Comment by maxaggedon** [comment]
Same here, disabling animation fixed it on my side

**Comment by becca-bailey** [comment]
Closing this issue since I do not believe we plan to address this right now. If you need this feature, PRs are still welcome!
