### ISSUE TITLE
VictoryChart with VictoryLine/Time Series not displaying properly in Firefox

### ISSUE THREAD

**Issue by mdramos** [FormidableLabs/victory#123]
Charts with lines and a time series don't seem to be displaying properly in firefox. I'm using 44.0a2 (2015-12-14).

Best example of this issue is on the Victory site: http://victory.formidable.com/docs/victory-chart ("Time series data is also supported" chart)

**Comment by mdramos** [comment]
It seems the Line is fine, but the Time Series axis is what is causing the issue

**Comment by mdramos** [comment]
The transform values after the initial date aren't being calculated right in Firefox

**Comment by boygirl** [comment]
wow, thanks for bringing this to our attention.

**Comment by mdramos** [comment]
@boygirl I have a fix but am unable to push to the victory-chart repo.

**Comment by mdramos** [comment]
@boygirl submitted a pull request on Victory-Chart. I think this should resolve the issue

**Comment by mdramos** [comment]
moved to: https://github.com/FormidableLabs/victory-chart/issues/78

**Comment by boygirl** [comment]
Merged and resolved. Thanks so much @mdramos
