### ISSUE TITLE
Can we add fixed Y-axis with scroll-able X-axis in Victory chart using VictoryAxis and VictoryBar? 

### ISSUE THREAD

**Issue by peddiraju26** [FormidableLabs/victory#1232]
`<ScrollView horizontal={true} showsHorizontalScrollIndicator={false} style={{ marginLeft: 0 }}>

                    <View pointerEvents="none" style={{ flexDirection: 'row', flex: 1, marginTop: 0, paddingBottom: 0 }} >

                      <View style={{ justifyContent: 'center', marginRight: 25, }}>
                        <Text numberOfLines={1} style={{
                          position: 'absolute', color: '#575b60', fontSize: 10,
                          transform: [{ rotate: '-90deg' }], marginLeft: -10, fontWeight: 'normal'
                        }}>No. Of Units</Text>
                      </View>

                      <VictoryChart
                        domainPadding={30}
                        width={Dimensions.get('window').width + this.state.systemDetailsData.system_hourly_data.length * 30}
                        style={{ flex: 0.9, color: '#FBC530', }}>

                        <VictoryAxis dependentAxis style={{ axis: { stroke: '#000000' }, tickLabels: { fill: "#575b60", fontSize: 10 } }} />

                        <VictoryAxis style={{ axis: { stroke: '#000000' }, tickLabels: { fill: "#575b60", fontSize: 10 } }} />

                        <VictoryBar
                          barWidth={10}
                          padding={{ left: 0, right: 0 }}
                          style={{
                            data: { fill: '#FF7A0B' },
                            labels: { fontSize: 4 },
                          }}
                          data={this.state.systemDetailsData.system_hourly_data} x="time" y="this_hr_output" />

                        <VictoryLine
                          style={{ data: { stroke: "#1683EF", strokeWidth: 1 }, }}
                          y={() => this.state.systemDetailsData.system_hourly_data_output_average} />

                      </VictoryChart>

                    </View>

                  </ScrollView>`

I have tried above code and in that senario the Y-axis also scrolling with chart. Can you help me with suggestions?

**Comment by boygirl** [comment]
You can do something like this with `VictoryZoomContainer` with `zoomDimension="x"`. More information here: http://localhost:3000/docs/victory-zoom-container

**Comment by fusandy** [comment]
@boygirl
Hello! I have a stackedBarChart which might contain hourly data for several days, so need a scroll to view the whole chart. But I've tried what you've mentioned above and followed the document, the stacked bar chart can't be scrolled smoothly.
I had added ScrollView element outside the VictoryChart to test whether it would scroll smoothly or not, but it failed.
Do you have any idea how to fix the code ? appreciate a lot if you answer my question!! ^^ 
```
<ScrollView horizontal>
  <VictoryChart
    domainPadding={{ x: 10 }}
    containerComponent={
      <VictoryZoomContainer
        allowZoom={false}
        // zoomDimension='x'
        zoomDomain={{ x: [0, 10] }}
      />
    }
  >
    {/* y */}
    <VictoryAxis
      dependentAxis
      style={{
        axis: { stroke: 'transparent' },
        grid: { stroke: '#5a5a5a66' }
      }}
      tickLabelComponent={<VictoryLabel style={[{ fill: '#5a5a5a', fontSize: normalizeFontSize(14), fontFamily: 'PingFangTC-Regular' }]} />}
    />
    {/* x */}
    <VictoryAxis
      style={{
        axis: { stroke: '#5a5a5a' },
        axisLabel: { fontSize: normalizeFontSize(14), fill: '#5a5a5a' }
      }}
      tickLabelComponent={<TickLabelComponent />}
    />
    {/* bar */}
    <VictoryBar
      cornerRadius={{ top: 5, bottom: 5 }}
      barWidth={normalizeFontSize(10)}
      alignment='middle'
      labels={({ datum }) => datum.category === 'etaPerHour' ? `${datum.total}%` : undefined}
      style={{ data: { fill: ({ datum }) => `${datum.fill}${selectedBarIndex === undefined || selectedBarIndex === datum.index ? 'FF' : '1A'}`, opacity: ({ datum }) => datum.opacity } }}
      data={dataSource}
      dataComponent={<DataComponent />}
      labelComponent={<LabelComponent />}
    />
  </VictoryChart>
</ScrollView>
```
