### ISSUE TITLE
VictoryBar: bars drawn even when outside domain

### ISSUE THREAD

**Issue by pkyeck** [FormidableLabs/victory#1233]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Bars of a VictoryBar chart are drawn even when they are outside the supplied domain.
I was expecting for them to be omitted.

![screenshot 2019-01-18 at 14 39 13](https://user-images.githubusercontent.com/870980/51390257-1ae2e100-1b2f-11e9-871d-9e06690051c2.png)

### Reproduction

https://formidable.com/open-source/victory/docs/common-props/#domain
and change the domain to `domain={{ x: [1.5, 5.5], y: [0, 10] }}`

custom chart w/ the same issue:
https://jsfiddle.net/x4fLk2z1/20/

**Comment by boygirl** [comment]
@pkyeck this is the expected behavior, as it is necessary to allow things like zooming to work. If you would like your chart to cut off cleanly at the axes you can use `VictoryClipContainer` as the `groupComponent` by adding this prop to `VictoryBar`

`groupComponent={<VictoryClipContainer/>}`
