### ISSUE TITLE
VictoryBoxPlot: Can't set independent tick values when horizontal

### ISSUE THREAD

**Issue by martingordon** [FormidableLabs/victory#1235]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When displaying a box plot horizontally, setting `tickValues` on the dependent axis causes them to also be set (and override any existing) ticks on the independent axis. `categories` is not good for my use case as I'd like to label only certain box plots to simulate grouping functionality (e.g., group "A" consists of two box plots and I only want to draw a label under one of them).

### Reproduction

See: https://codesandbox.io/s/rr2370yj94

In horizontal mode, I would expect to be able to have Victory auto-generate tick values for the x-axis even when I specify y-axis values.

In building up this test case, I found a workaround where I can specify `tickCount` and `tickFormat` to generate the correct results, but being able to just pass in `tickValues` would be great.

**Comment by boygirl** [comment]
@martingordon 

The recent major version of victory did a lot of work to make horizontal charts more consistent, and I believe it addresses this issue. I've updated your sandbox to take the breaking changes in `victory@32.0.0` into account: https://codesandbox.io/s/l9n3pnvoq7

I recommend reading the changelog as well, it covers all the breaking changes and explains how to migrate: https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#3200-2019-02-27
