### ISSUE TITLE
[Docs] Write up an in-depth quickstart guide

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/victory#124]
We have great per-component docs right now, but it'd be nice to have an equally great high-level overview that walks through the dev process from `npm install` through rendering a composed chart.
* We could start with a look at our (arbitrary) data and a screenshot of the desired outcome.
* Next, we'd walk through the installation process: `npm install`, etc.
* Step by step, we'd build out the chart components (with a screenshot at every major step) until we have what we want!

If we wanted to get real fancy, we could even put the sample chart in a standalone repo and, after every major step, link to a diff of the relevant commit(s).

(Note that this could also replace the current contents of `/docs` [a.k.a. "Getting started"] in the docs site.)

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#22
