### ISSUE TITLE
Change line color based on y value

### ISSUE THREAD

**Issue by mattoni** [FormidableLabs/victory#1242]
Is it possible using a VictoryLine to change the color of a section of the line if it rises above a certain Y value? Say y < 5, we can make the color of that portion of the line blue, but if y > 5 the section of the line above 5 is red?

**Comment by boygirl** [comment]
It is possible, but you will need to use a gradient stroke. Here are some examples that use a gradient fill on VictoryArea: 

https://formidable.com/open-source/victory/gallery/stream-graph/
https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory

**Comment by Eric0201** [comment]
> Is it possible using a VictoryLine to change the color of a section of the line if it rises above a certain Y value? Say y < 5, we can make the color of that portion of the line blue, but if y > 5 the section of the line above 5 is red?

have you solved this?

**Comment by karlvd** [comment]
Add a custom Clip component, which gets the 0 line coords from props.scale.y(0)

```
function CustomClip({ ...props }) {
        return (
            <defs key={'clips'}>
                <clipPath id="clip-path-1">
                    <rect x={'0'} y={0} width={'100%'} height={props.scale.y(0)} />
                </clipPath>
                <clipPath id={'clip-path-2'}>
                    <rect x={'0'} y={props.scale.y(0)} width={'100%'} height={'100%'} />
                </clipPath>
            </defs>
        )
    }
```
Add the custom clip component inside your VictoryChart
Add your LinceChart 2 times with different colors and reference the id of the clippath

```
<VictoryChart>
    <VictoryLine
        id={'line-1'}
        style={{
            data: {
                stroke: 'green',
                strokeWidth: 2,                
                clipPath: 'url(#clip-path-1)',
            }
        }}
        data={newData}
    />
    <VictoryLine
        id={'line-2'}
        style={{
            data: {
                stroke: 'red',
                strokeWidth: 2,                
                clipPath: 'url(#clip-path-2)',
            }
        }}
        data={newData}
    />
    <CustomClip />
</VictoryChart>
```

**Comment by vanpacheco** [comment]
The scale prop received by CustomClip is an empty object. Any ideas why?

**Comment by ZuzooVn** [comment]
@vanpacheco Did you find the solution?

**Comment by vanpacheco** [comment]
@ZuzooVn No, I didn’t. To display a line with different colors we processes the data in a way we could draw a line for each range of values with a different color.

**Comment by oliviercperrier** [comment]
@karlvd No props are given to CustomClip, so your solution doesnt work
