### ISSUE TITLE
Stacked area chart with scatter points broken by v0.27.1 changes

### ISSUE THREAD

**Issue by desbrowne** [FormidableLabs/victory#1246]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The changes introduced in v0.27.1 has broken the rendering of stacked groups that contain scatter points. There are two example charts contained in each sandbox, the first chart has scatter points, the second doesn't. While the second chart continues to render correctly in v0.27.1 the first doesn't. Every second group is a repeat of the previous group, i.e. the "y" values are the same. The latest version (v31.2.0) continues to exhibit the same issue.

The first chart in the following debug demo is also exhibiting this problem:
https://github.com/FormidableLabs/victory/blob/master/demo/components/debug-demo.js

### Reproduction

Expected: v0.27.0: https://codesandbox.io/s/98129yynk4
![victory-0 27 0](https://user-images.githubusercontent.com/3364592/52185699-dadd6700-286d-11e9-8af1-a42cb7c7c80c.png)

Issue: v0.27.1: https://codesandbox.io/s/kk4onz09z5
![victory-0 27 1](https://user-images.githubusercontent.com/3364592/52185703-e6309280-286d-11e9-9844-964a513517e5.png)

v31.2.0: https://codesandbox.io/s/km4xmq8zmr

**Comment by boygirl** [comment]
@desbrowne this issue is fixed in `victory@32.0.0`

**Comment by desbrowne** [comment]
Great, so appreciate this @boygirl
