### ISSUE TITLE
Console log errors rendering victory chart and using react-router-dom

### ISSUE THREAD

**Issue by eled30** [FormidableLabs/victory#1255]
# Bugs and Questions

### Checklist

- [v ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [v ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [v ] I am using the latest version of Victory

- [ v] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

In the console I see a lot of errors by react-dom development and they only shows in the console when I am using the victory Chart.
All the errors say "react-dom.development.js:3135 Error: <path> attribute d: Expected number ..."
I don't know if I made some mistake configuring the chart.
I am using create-react-app and have inserted the chart in a component, following the guidelines.
The chart and the app work well, but I see 52 errors of that type in the console. What can be the problem?

Thank you for your help

**Comment by boygirl** [comment]
@eled30 I can't reproduce the problem from this information. If your problem persists please open an issue with a codesandbox example.
