### ISSUE TITLE
VictoryZoomContainer only renders chart after manual zoom

### ISSUE THREAD

**Issue by satyasinha94** [FormidableLabs/victory#1259]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

my VictoryScatter chart inside a VictoryZoomContainer only renders if I manually zoom in (using mac's pinch zoom). After I manually zoom in it seems to work fine. 

### Reproduction

Basic create-react-app demo of bug linked below: 
https://github.com/satyasinha94/victory-zoom-bug

**Comment by boygirl** [comment]
@satyasinha94 the issue here is that `VictoryScatter` is using a default domain of [0, 1], and your `zoomDomain` is set to [0, 75]. When you zoom, the domain is reset on all of the child components. This can be a super strange scenario when you don't have any data. Try adding a domain to your child component so you can see what's going on:
```
  <VictoryGroup
    containerComponent={<VictoryZoomContainer zoomDomain={{ x: [0, 75], y: [0, 75] }} />}
  >
    <VictoryScatter domain={{ x: [0, 75], y: [0, 75] }}/>
  </VictoryGroup>
```

Or try with a component with data:
```
  <VictoryGroup
    containerComponent={<VictoryZoomContainer zoomDomain={{ x: [0, 10], y: [0, 15] }} />}
  >
    <VictoryScatter 
      data = {[
        { x: 1, y: 1 },
        { x: 2, y: 3 },
        { x: 3, y: 5 },
        { x: 4, y: 2 },
        { x: 5, y: 10 }
      ]}
    />
  </VictoryGroup>
```
