### ISSUE TITLE
Catch big error after installed the latest victory version 

### ISSUE THREAD

**Issue by TeresaZhang7517** [FormidableLabs/victory#1260]
# Bugs and Questions

### The Problem
Catch a big error after installed the latest victory version. Details as below. Could help to solve this issue? Thanks very much.

### Description
![image](https://user-images.githubusercontent.com/36947669/53555698-66040100-3b7d-11e9-9f20-c1afab6a96e0.png)
![image](https://user-images.githubusercontent.com/36947669/53555764-8a5fdd80-3b7d-11e9-8285-5701adbe31ad.png)

**Comment by boygirl** [comment]
@TeresaZhang7517 Hi there! I'm guessing this is caused by a different version of `prop-types`, but I will release a patch that changes the prop declaration back to the more common `shape` instead of `exact`
