### ISSUE TITLE
external event mutations aren't applied in some cases

### ISSUE THREAD

**Issue by gnijuohz** [FormidableLabs/victory#1263]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

In some cases external event mutations aren't being applied.
The expected outcome is that external event mutations should be applied.

### Reproduction

It can be reproduced here: https://codesandbox.io/s/l515mzqwm The idea is when hovering over the the labels at the bottom, corresponding pie pieces are highlighted (turned into black in this case). And when the mouse moves away from a label, the style of the pie piece gets restored.

The problem is when you move the mouse **quickly** from left to right (and in the reverse direction) over the labels, sometimes some of the pie pieces get stuck at the highlighted state. It may take several tries to see that happen but it can be reproduced consistently.

It does work properly if you move the mouse slowly over the labels.

**Comment by boygirl** [comment]
@gnijuohz thanks for the reproduction. I was able to see the issue in your reproduction if I moved my mouse very quickly. I changed your `onMouseEnter` to `onMouseOver` and I can no longer see the issue. I think it may not be related to external events in Victory. I'm going to close this issue for now, but let me know if it persists for you with `onMouseOver`

**Comment by gnijuohz** [comment]
Hi @boygirl thanks for looking into it! I also tried  `onMouseOver` and it indeed worked. However, judging by the console in the sandbox, the handlers(`onMouseOver/Leave` or `onMouseEnter/Leave`) are always called in pairs, so it's puzzling why one pair works while the other doesn't. `onMouseEnter` and `onMouseEnter` are also used together more.

But I agree this may not be a Victory bug, thanks again for looking into this.
