### ISSUE TITLE
VictoryTooltip near mousehover point

### ISSUE THREAD

**Issue by jayasivabaskar** [FormidableLabs/victory#1267]
Is there any way to show victory tooltip near the mouse hover point, i.e(changing the position of tooltip when the mouse hover point changes) for bar, pie, groupbar?

**Comment by boygirl** [comment]
@jayasivabaskar thanks for your patience! This is currently supported when using `VictoryVoronoiContainer` with multiple labels like in this example: https://formidable.com/open-source/victory/gallery/multipoint-tooltip-labels

You can also create your own mouse follow tooltips by following this example: https://codesandbox.io/s/epic-wu-wqrm1oq2lk
