### ISSUE TITLE
Alignment of VictoryTooltip on scatter plot

### ISSUE THREAD

**Issue by nbuonin** [FormidableLabs/victory#1268]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The alignment of the tooltip on seems to skew left on the left side of the graph, and skew right on the right side of the graph.
Skew left:
<img width="690" alt="skew left" src="https://user-images.githubusercontent.com/6710696/53973870-909b1000-40cf-11e9-93e6-7b5e5b6a21e7.png">

Skew right:
<img width="716" alt="skew right" src="https://user-images.githubusercontent.com/6710696/53973874-942e9700-40cf-11e9-9764-02731813317b.png">

But it tends to the center when the dot is in the center of the chart:
<img width="688" alt="center" src="https://user-images.githubusercontent.com/6710696/53973899-9db7ff00-40cf-11e9-974d-35be8f32a2f9.png">

I'm using the base VictoryChart, and VictoryScatter components to render my chart, and VictoryTooltip for my label component. I see the same mis-alignment both with and without using VictoryVoronoiContainer.

My expectation is that the tooltip would position the point precisely on the dot.
### Reproduction

You can see the same mis-alignment in the docs, though its less pronounced: https://formidable.com/open-source/victory/guides/tooltips/#tooltips-with-victoryvoronoicontainer
Note that the tooltips on the left side of the chart tend to the left, and tend to the right on the right side.

Though its a different graph type, it can be seen on the basic bar graph example: https://formidable.com/open-source/victory/guides/tooltips/#simple-tooltips
Here, I'd expect the tooltip to position in the center of the bar.

**Comment by boygirl** [comment]
@nbuonin thanks for this issue! A general audit of tooltip alignment is actually next up in my work queue. I'll keep you posted
