### ISSUE TITLE
peerDependency not satisfied

### ISSUE THREAD

**Issue by knowbody** [FormidableLabs/victory#127]
### Problem

Error when installing packages from npm, in `package.json` we have: `"react-router": "^1.0.0"` which installs the newest react-router 1.0.3. That version of the router needs `"history": ^1.17.0`.

### Solution:

Either lock the react-router version, or update the history version to 1.17.0

**Comment by david-davidson** [comment]
Good catch! We had a very similar problem just a few weeks ago (#101); looks like `react-router` is moving pretty fast. I'd vote for locking `react-router`, under the assumption that otherwise this sort of thing will come up again soon.

**Comment by knowbody** [comment]
React Router 2.0 will be release soon, so then we can update both of them, for now locking seems like a good solution.
