### ISSUE TITLE
Grouping items for colorScale

### ISSUE THREAD

**Issue by solace** [FormidableLabs/victory#1270]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a series of VictoryLine in a VictoryGroup which is coloured using colorScale. I would like each of the datapoints to be marked with a dot the way it has been demonstrated in https://formidable.com/open-source/victory/gallery/interpolation/

The example uses a combination of Line and Scatter to achieve this effect. However, by wrapping them in a VictoryGroup, the lines obviously get assigned different colours to the scatters.

I was wondering if it is possible to group the line and scatter to use the same colour for that iteration, or if the only way to handle this is to not use VictoryGroup and to manually assign the colours.

Thanks!

### Reproduction

https://codesandbox.io/s/o4x8mqnoqy

**Comment by boygirl** [comment]
@solace unfortunately there isn't a way to have colorScale operate across all elements of a group. It would be better to assign them manually.

**Comment by taylorbf** [comment]
For anyone looking here for answers, I did accomplish this by wrapping the line and scatter in an additional VictoryGroup:

```jsx
<VictoryGroup colorScale={"qualitative"}>
    <VictoryGroup>
      <VictoryLine data={data} />
      <VictoryScatter data={data}/>
    </VictoryGroup>
</VictoryGroup>
```

The outer group assigns a unique color to each inner group.

 I don't know if this is a recommended pattern, but it's how I've been doing this.
