### ISSUE TITLE
Scroll doesn't work on android

### ISSUE THREAD

**Issue by CorayThan** [FormidableLabs/victory#1274]
# Bugs and Questions

### Checklist

- [yes ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ yes] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [yes ] I am using the latest version of Victory

- [yes ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

No matter where I add `pointerEvents: "none"` victory charts consume the scroll event when using touch devices, including chrome dev tool's touch emulator.

### Reproduction

Use the "new window" button in the following, and try to scroll the chart in chrome dev tools touch mode.

https://codesandbox.io/s/w2kp8q3vq8

### Checklist

- [yes ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [yes ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I want to be able to make it possible to scroll on touch of charts.

**Comment by boygirl** [comment]
@CorayThan I'm not able to reproduce this using your sandbox and the steps you suggest. I think it may be an issue with your emulator? They can be flaky sometimes.
