### ISSUE TITLE
voronoiBlacklist prop should take regex

### ISSUE THREAD

**Issue by kaitmore** [FormidableLabs/victory#1275]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a chart using `VictoryVoronoiContainer` to render a tooltip, and I need to blacklist certain components using the `voronoiBlacklist` prop.  I can't know ahead of time how many components I will need to blacklist because it is based on the data being passed in, so it would be unfeasible to list every `name` that could be rendered.

A solution is to give these components a static name. However, because Victory uses [`name` as the key](https://github.com/FormidableLabs/victory/issues/1205) I get errors in the console, even if the `key` I provide is actually unique.

# Feature Requests

### Checklist

- [x ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

It would be great if the `vonoroiBlacklist` prop could accept regex expressions.

**Comment by narinluangrath** [comment]
I'll take a crack at this!

**Comment by kaitmore** [comment]
thanks @narinluangrath!
