### ISSUE TITLE
Cursor component sticks when moving between charts

### ISSUE THREAD

**Issue by kaitmore** [FormidableLabs/victory#1276]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have multiple victory charts on a page that use `createContainer` to combine voronoi + cursor containers in order to render a tooltip and a cursor line. When moving between them, the `cursorComponent` doesn't always disappear on mouse out:
![P4z3lYWKpmhgY](https://media.giphy.com/media/DN8vBonyQMrmpYjKgV/giphy.gif)

### Reproduction

https://codesandbox.io/s/31vw7w25xp

**Comment by boygirl** [comment]
@kaitmore thanks for this issue. I think what's going on is that the throttled `onMouseLeave` is too slow and misses some events. I'll double check, and remove the throttling on this handler if it looks like it isn't always being called.
