### ISSUE TITLE
Incorrect error: React does not recognize the `verticalAnchor` prop on a DOM element

### ISSUE THREAD

**Issue by dallashuggins** [FormidableLabs/victory#1277]
Anytime you scroll over one of the elements within any of the Victory charts we're rendering, we get the error "React does not recognize the `verticalAnchor` prop on a DOM element". For instance, one of the charts we are rendering is a bar chart and when you hover over an individual bar, this error appears in the console logs. This is the same with all of the other charts, whenever you hover over any of the individual elements. 

The issue appears to be related to the custom tooltips we are using (the `TooltipContent` component in the `flyoutComponent` within `VictoryTooltip`), but I haven't been able to determine why the issue is happening. 

Code Sandbox (scroll over bars in the table to duplicate error and then check the console log area): https://codesandbox.io/s/mm72y07xv9

Full error in console logs:
```
Warning: React does not recognize the `verticalAnchor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `verticalanchor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by StackedHistogram)
    in g
    in svg (created by Portal)
    in Portal (created by VictoryContainer)
    in div (created by VictoryContainer)
    in div (created by VictoryContainer)
    in VictoryContainer
    in VictoryChart (created by StackedHistogram)
    in div (created by StackedHistogram)
    in StackedHistogram (created by inject-StackedHistogram-with-themeStore)
    in inject-StackedHistogram-with-themeStore (created by Ancestry)
    in div (created by Panel)
    in Panel (created by Ancestry)
    in div (created by Ancestry)
    in Ancestry (created by RouterContext)
    in div (created by Explore)
    in div (created by Explore)
    in div (created by Explore)
    in Explore (created by RouterContext)
    in div (created by Home)
    in AuthGate (created by Home)
    in div (created by Flex)
    in Flex (created by Home)
    in Home (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Unknown (created by App)
    in div (created by App)
    in App (created by inject-App-with-versionStore)
    in inject-App-with-versionStore (created by inject-inject-App-with-versionStore-with-themeStore)
    in inject-inject-App-with-versionStore-with-themeStore
    in Provider
```

**Comment by boygirl** [comment]
@dallashuggins after looking at your sandbox, I believe this issue is happening because you have added `labelComponent={<div />}`. `VictoryTooltip` provides a bunch of props to its `labelComponent` that don't belong on a div. I'm going to close this issue, but please open another if you're having trouble getting your custom tooltips working.

**Comment by dallashuggins** [comment]
Awesome, thanks! I added a component and am now passing it into VictoryTooltip's `labelComponent`, which fixed the error. 

```
const TooltipWrapper = () =>
  <svg width="100%" height="100%"></svg>
```
