### ISSUE TITLE
Mixing horizontal & vertical components in a single chart

### ISSUE THREAD

**Issue by flipchart** [FormidableLabs/victory#1281]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Prior to v32 mixing horizontal & vertical components in a single chart worked fine - I had a horizontal bar with "vertical" line in the same chart by specifying the `horizontal` prop on the bar components, but not on the line components.

Now, since v32, it seems if you specify `horizontal` on any component, the entire chart is rendered horizontal making a mixture impossible. Is there a way to mix horizontal & vertical components in v32?

### Reproduction

Victory v30 - old (and desirable) behaviour
https://codesandbox.io/s/jqr7nmmqy

Victory v32 - new (and undesirable) behaviour
https://codesandbox.io/s/w22o16xxlw

**Comment by boygirl** [comment]
@flipchart it is no longer possible to have elements that render in horizontal and standard orientations _automatically_ within the same chart. This is generally an improvement as horizontal orientations were not really supported for things like `VictoryLine` prior to this change, and props like `domain` needed to be flipped to switch between horizontal and vertical orientations. In v32 you will need to manually flip your standard components. I've forked and altered your v32 sandbox to demonstrate: https://codesandbox.io/s/zqmpr869ml

https://codesandbox.io/s/zqmpr869ml

**Comment by flipchart** [comment]
@boygirl Thanks so much! Works a charm. Very glad I could continue using Victory :)

For those looking for a quick reference, flipping the orientation is achieved with the following props:
```
y="x"
x="y"
sortKey="y"
```
