### ISSUE TITLE
VictoryLine animations don't always complete under high cpu pressure when animate is chart-level

### ISSUE THREAD

**Issue by DingoEatingFuzz** [FormidableLabs/victory#1282]
### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When the `animate` property is assigned to the `VictoryChart` component (or assumed from a theme), `VictoryLine`s don't always complete their animation if high CPU usage creates choppiness.

If the animation is applied to the `VictoryLine` directly, the line is guaranteed to make it to a steady-state regardless of animation fps.

This is a regression from earlier versions.

### Reproduction

https://codesandbox.io/s/lpzqn5mmnq

Since this is a CPU pressure dependent issue, you will probably have to throttle CPU in Chrome in order to reproduce the issue.

In a real-world example, this is most likely to happen during initial page load/render.

**Comment by boygirl** [comment]
@DingoEatingFuzz I see what you mean. Thanks for the reproduction. I think this one might take a bit of time to dig into.

**Comment by boygirl** [comment]
Resolved in `victory@35.6.0`
