### ISSUE TITLE
[VictoryCandleStick] render same stroke color with the positive/negative color

### ISSUE THREAD

**Issue by gasolin** [FormidableLabs/victory#1285]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Read the doc https://formidable.com/open-source/victory/docs/victory-candlestick and the source https://github.com/FormidableLabs/victory/blob/master/packages/victory-candlestick/src/victory-candlestick.js

We are able to set `candleColors={{ positive: "green", negative: "red" }}` and stroke color separately

```
style={{
  data: { stoke: 'grey' strokeWidth: 1},
}}
```

But it's not possible to set a stroke color to follow the positive/negative color (To make a OHLC green bar with the green line color, the red bar with the red line color)

I suggest adding new props `positiveStroke`/`negativeStroke` for `candleColors` to render stroke with the specific positive/negative stroke color. 

Therefore a user can have varient OHLC bar with a specific color (hollow green, concrete red, etc)

**Comment by boygirl** [comment]
@gasolin you're right, this is not currently supported.  I will add this as part of a larger feature to improve `VictoryCandlestick`

**Comment by boygirl** [comment]
oh! actually I misunderstood. When I first read this I thought you wanted to have the high wick and the low wick to be _different colors from each other_. That is not currently possible. If you want to have the high wick and low wick change colors depending on whether the candle is positive or negative, that _is_ possible with the following styles:

```
style={{
  data: {
    fill: "none",
    strokeWidth: 2,
    stroke: d => (d.close > d.open ? "red" : "green")
  }
}}
```

Here's an example sandbox: https://codesandbox.io/s/ykjrv52mnv
