### ISSUE TITLE
VictoryLegend breaks when using VictoryLabel with `text `prop

### ISSUE THREAD

**Issue by wootencl** [FormidableLabs/victory#1291]
### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Title pretty much says it but at current `VictoryLegend` will throw an Invarient Violation when `VictoryLabel` with a `text` prop is specified as the `labelComponent`.
### Reproduction
https://codesandbox.io/s/5vmm8ov56x

**Comment by boygirl** [comment]
Yikes! Thanks for the reproduction. I'll look into this today

**Comment by wootencl** [comment]
No problem! Thanks again for the super quick turnaround
