### ISSUE TITLE
VictoryGroup children data accessors ignored (if data supplied to group)

### ISSUE THREAD

**Issue by wootencl** [FormidableLabs/victory#1294]
### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Uncertain if this might be related to #451, but it seems something such as the following should work:

```
<VictoryChart>
  <VictoryGroup
    data={data}>
    <VictoryBar
      x='sharedX'
      y='uniqueY1' />
    <VictoryBar 
      x='sharedX'
      y='uniqueY2'/>
  </VictoryGroup>
</VictoryChart>
```

At current, it seems to ignore the data accessor props entirely from what I can tell.

### Reproduction

https://codesandbox.io/s/m3w13jp8kp

**Comment by becca-bailey** [comment]
I'm uncertain whether this is reproducible in the latest version. Feel free to re-open if this still needs to be addressed!

**Comment by scotthhso** [comment]
Hey this still has not been fixed yet. Definitely still reproducible
