### ISSUE TITLE
[VictoryCandlestick] render line color based on previous entry's price

### ISSUE THREAD

**Issue by gasolin** [FormidableLabs/victory#1296]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

It's possible to render different line color based on @boygirl 's suggestion
https://github.com/FormidableLabs/victory/issues/1285#issuecomment-480132855

But the edge case is when the `close price equals open price` (generally happens in low volume), it always shows the negative color.

To show the line color properly, we need to compare the previous entry's close price to the current entry's close price.

https://formidable.com/open-source/victory/guides/data-accessors/ shows we can only process current data set like

```
data: {
    stroke: (d) => {}
}
```

Is it possible to pass the current data's index to data function, so we can refer from the whold dataset when necessary?

```
style={{
  data: {
    stroke: (d, idx) => {
      if (d.close == d.open) {
         return candleData[idx-1] > d.close ? "red" : "green"
      } else {
          return d.close > d.open ? "red" : "green")
      }
    }
  }
}}
```

**Comment by boygirl** [comment]
@gasolin interesting! you won't be able to do that with functional styles, because they wont have access to all the arguments you would require. You can do it with a custom data component, though. Here's an example: https://codesandbox.io/s/1q8pv2r1l4

You can also read about all the props the `Candle` components gets here: https://formidable.com/open-source/victory/docs/victory-primitives#candle

**Comment by gasolin** [comment]
thanks for point out the custom data component, `Candle` component serves well for this case

Though the `candleColors={{ positive: 'green', negative: 'red' }}` seems not work with the custom candle element, neither by passing in `<VictoryCandlestick candleColors={...}>` nor `<Candle candleColors={...}>`
