### ISSUE TITLE
Component based development Issue

### ISSUE THREAD

**Issue by arpitjain-in** [FormidableLabs/victory#1309]
Why component's are not getting rendered when breaking into small-small components.
For example:-
VictoryAxis as one component. 
VictoryBar as one component.

Codesandbox example:-
```https://codesandbox.io/embed/basic-victory-example-gyiqs```

In above example, Chart1 and Chart2 are not getting called.

**Comment by boygirl** [comment]
@arpitjain-in thank you for your patience. Your custom component will need to proxy the props it receives from `VictoryBar` like this:

```
class Chart2 extends React.Component {
  render() {
    return <Bar {...this.props}/>;
  }
}
```

You can read more about custom components here: https://formidable.com/open-source/victory/guides/custom-components

**Comment by arpitjain-in** [comment]
Thank you so much @boygirl.
