### ISSUE TITLE
Exclude dist from the repository, but keep it in the npm

### ISSUE THREAD

**Issue by knowbody** [FormidableLabs/victory#131]
As per https://github.com/FormidableLabs/radium/issues/471#issuecomment-167003690 I think we should do that in all our projects. There is no point of keeping track of `dist` on GH.

### Solution
As described in the comment above:
- add `dist` to `.gitignore`
- create empty `.npmignore` which overrides `.gitignore` so the `dist` will be included in the npm package and can be used via https://npmcdn.com

More in the [npm docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package).

**Comment by ryan-roemer** [comment]
Do _not_ create an empty `.npmignore`!!! You'll wind up with `.DS_Store`, and tons of other junk.

Instead, meticulously copy and edit the `.gitignore` to also exclude `.dist`

**Comment by knowbody** [comment]
That's what I had in mind. I'll send the PR soon. Sorry for not explaining properly 


    _____________________________

**Comment by ryan-roemer** [comment]
@knowbody -- Haha. Thanks!

**Comment by ryan-roemer** [comment]
Oh, and we'll want to add `dist` building to the `postinstall` commands in the archetype like `lib`
