### ISSUE TITLE
How to get width of independent axis tick?

### ISSUE THREAD

**Issue by gajus** [FormidableLabs/victory#1312]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))
- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question
- [x] I am using the latest version of Victory
- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Seemingly simple question, but I cannot find an answer: How to get width of independent axis tick?

Use case: I want to create bars of exactly the same width as the tick width (and offset the label).

The desired result is ~:

<img width="1232" alt="Screenshot 2019-05-28 at 12 57 35" src="https://user-images.githubusercontent.com/973543/58476277-38146580-8148-11e9-8269-ed043fa0c398.png">

I currently achieve this by dividing chart width by the number of ticks, i.e.

```js
// @todo Where is the 20 coming from?
const chartBodyWidth = width - 20;
const barWidth = chartBodyWidth / dateRange.length;

return <VictoryChart
  scale={{
    x: 'time'
  }}
  width={containerWidth}
  height={400}
  domainPadding={0}
  padding={{
    top: 0,
    bottom: 50,
    right: 0,
    left: 100
  }}
>
  [..]

```

This seems to give approx. the right width (it is not clear for me where the 20 is coming though and why it is not 100 – which is the left padding).

**Comment by boygirl** [comment]
Oh, interesting! The ticks are positioned by based on their value relative to the scale, (scale being d3's concept of a scale https://github.com/d3/d3-scale). `VictoryChart` passes this scale to all of its children with `domain` and `range` already applied. If you create a custom axis component you will be able to make use of it to position your ticks exactly where you want them. Here's an example: https://codesandbox.io/s/custom-axis-dk0rl
