### ISSUE TITLE
VictoryLabel TSpan expects 'number'

### ISSUE THREAD

**Issue by Charimon** [FormidableLabs/victory#1313]
I'm trying to do (similar to #641 )
`<VictoryLabel x="99%" y="1%" />`

The code actually works, I just get an a warning about TSpan not being able to have % in x or y.

```
Warning: Failed prop type: Invalid prop `x` of type `string` supplied to `TSpan`, expected `number`.
    in TSpan
    in VictoryLabel 
```

newest victory for the web ("victory": "32.2.0")

**Comment by boygirl** [comment]
Oh, interesting. I can change that prop to accept a string or a number. Thanks for your patience.
