### ISSUE TITLE
VictoryGroup offset not working as expected with VictoryStack and VictoryBar

### ISSUE THREAD

**Issue by ratchet12340** [FormidableLabs/victory#1315]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Potential Duplicate Issues
I tried looking for duplicate issues, and it seems like #1116 discusses grouped stacks of bars not being centered, which may be the root issue that I am having.

If this is in fact a duplicate, please feel free to close it.

### The Problem
When using `VictoryGroup`, `VictoryStack`, and `VictoryBar`, if one provides an `offset` prop to `VictoryGroup`, the stacks of bars will render off the chart, and off-center from the axis ticks.

### Reproduction
https://codesandbox.io/s/basic-victory-example-r9365

### Additional Info
I used an old fiddle using an older version of Victory (`0.21.4` to be exact) and the issue is not there. For reference: https://jsfiddle.net/arukqfsh/

I just checked each version manually. Seems like the last version of the `offset` prop working properly was in `0.26.1`. Things broke in `0.27.0`

**Comment by boygirl** [comment]
@ratchet12340 thanks for the reproduction! I'll take a look next week

**Comment by BornaSepic** [comment]
@boygirl Just wanted to check what the progress is on this ticket as we are having the same issue as @ratchet12340

**Comment by PrimeHydra** [comment]
Same issue here--when grouping Bars, the graphs are centered nicely, but when grouping Stacks, they are offset. Amazing library, BTW!

**Comment by iranana** [comment]
Just wondering if there's any update on this issue, and anything I can do to help? :)

**Comment by richardtks** [comment]
@boygirl, first of all, this is an awesome library and thank you for your hard work. May I know what is the status of this issue? If you are not available for this issue, maybe you can give us some guideline or hints how can we help? 😄

**Comment by richardtks** [comment]
@boygirl, when I investigated this issue, I found that the issue was causing by this [line](https://github.com/FormidableLabs/victory/blob/eedf69fa061f0a6e0429d3369811bc55eb26b63a/packages/victory-group/src/helper-methods.js#L70). 

```
function getX0(props, calculatedProps, index) {
  const center = (calculatedProps.datasets.length - 1) / 2;
  const totalWidth = pixelsToValue(props, "x", calculatedProps);
  return (index - center) * totalWidth;
}
```


Let's said I have 1 group, 2 stacks and 11 bars:
```
<VictoryChart width={500} height={250} domainPadding={{ x: [200, 0] }}>
   <VictoryGroup offset={10} style={{ data: { width: 20 } }}>
        <VictoryStack>{this.renderBars()}</VictoryStack>
        <VictoryStack>{this.renderBars()}</VictoryStack>
    </VictoryGroup>
</VictoryChart>
```

Then the structure I see for the `calculatedProps.datasets` is as following:
![image](https://user-images.githubusercontent.com/43637878/75842190-a6d6cb80-5e0a-11ea-82b1-2043af8f1137.png)

The calculation of the `X0` is based on the number of the bar instead number of stacks? Based on the picture above, stacks is nested inside the bars? Is that expected?

For the quick fix, I can do something like this, where it takes the number of stacks instead of numbers of bars 
```
const center = (calculatedProps.datasets[0].length - 1) / 2;
```

**Comment by cneltyn** [comment]
@richardtks , have you tried to fork and build the project with the fix you have proposed? Was it success? If yes, maybe you can share the link to the forked solution (not able to build so far)?
