### ISSUE TITLE
VictoryLegend should work as a labelComponent

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#1319]
The api for `VictoryLegend` should be altered so that it can take `datum` and `data` props that are typically provided to `labelComponent` by their parents. It should also have accessor props that convert `datum` / `data` to legend rows. The existing `data` prop will need to be renamed so that it doesn't conflict with the `data` being passed to labels

**Comment by becca-bailey** [comment]
I'm going to close this for now since I'm not sure we still have all the context here. If there is a re-write involving these components I will make a note to make sure this functionality gets incorporated.
