### ISSUE TITLE
VictoryZoomContainer and Tooltip on Custom Chart?

### ISSUE THREAD

**Issue by switchtrue** [FormidableLabs/victory#1320]
Is it possible to add a `VictoryZoomContainer` and/or Multi-point `VictoryTooltips` to the `Custom Chart` example found [here](https://formidable.com/open-source/victory/guides/custom-charts). Specifically I am referring to adding zoom and tooltip functionality to a chart with multiple dependent axis.

All the examples for `VictoryZoomContainer` and Multi-point `VictoryTooltip`s require using the `containerComponent` prop. There is no logical place for this when manually rendering `svg` and `g` elements as in the Custom Chart example. Additionally, `VictoryGroup` explicitly states it cannot be used with `VictoryAxis` so this is not a suitable wrapper component.

Issue #492 states a potential idea but I can't figure out how to add even one `VictoryZoomContainer`.

**Comment by boygirl** [comment]
@switchtrue you should be able to add multiple dependent axes to `VictoryChart` as in this example: https://formidable.com/open-source/victory/gallery/multiple-dependent-axes.

**Comment by switchtrue** [comment]
Does this work because they all have the same domain? I actually need to use different domains.
