### ISSUE TITLE
click event not working

### ISSUE THREAD

**Issue by billouboq** [FormidableLabs/victory#1321]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm using multiple VictoryPolarAxis and each one of them has a custom tooltip component for the axisLabel.

```jsx
<VictoryPolarAxis
  key={data.get('_id')}
  dependentAxis
  startAngle={START_ANGLE}
  endAngle={END_ANGLE}
  style={polarAxisStyle}
  labelPlacement="vertical"
  axisAngle={angle}
  label={data.get('name')}
  tickFormat={this.formatTickValue(data.get('_id'))}
  tickValues={[0.2, 0.4, 0.6, 0.8, 1]}
  axisLabelComponent={
    <DiagnosticGraphTooltip
      selectedTheme={selectedTheme}
      theme={data}
      angle={angle - END_ANGLE}
      width={TOOLTIP_WIDTH}
      height={TOOLTIP_HEIGHT}
      totalWidth={width}
      totalHeight={height}
      design={design}
      onPress={onTooltipPress}
    />
  }
/>
```

Each tooltip has onPress and onClick events attached to it.
The onPress is used in React-native app and the onClick for web-app. 
My probleme is that React-native onPress events is triggered but onClick on web version does not and I really don't know what to do anymore, I searched but didn't find any solutions.

Here is the tooltip component :

```jsx
class DiagnosticTooltip extends React.PureComponent {
	onTooltipPress = () => {
		debugger;
		const { onPress, theme } = this.props;

		if (onPress) {
			onPress(theme);
		}
	};

	isSelected = () => {
		const { theme, selectedTheme } = this.props;
		return selectedTheme && theme.get('_id') === selectedTheme.get('_id');
	};

	render() {
		const {
			text,
			x,
			y,
			angle,
			totalWidth,
			totalHeight,
			width,
			height,
			design
		} = this.props;

		const isSelected = this.isSelected();
		const mainColor = design.get('mainColor');
		const position = getTooltipPosition(angle);
		const dx = getTooltipDx(position, x);
		const dy = getTooltipDy(position, y);
		const bgColor = isSelected ? mainColor : 'white';
		const textColor = isSelected ? 'white' : mainColor;

		return (
			<VictoryTooltip
				active
				y={totalHeight / 2}
				x={totalWidth / 2}
				dx={dx}
				dy={dy}
				cornerRadius={5}
				width={width}
				height={height}
				events={{
					onPressIn: this.onTooltipPress,
					onClick: this.onTooltipPress
				}}
				flyoutComponent={
					<Flyout style={{ fill: bgColor, stroke: mainColor }} />
				}
				labelComponent={
					<VictoryLabel style={{ fontSize: 10, fill: textColor }} />
				}
				pointerLength={4}
				pointerWidth={6}
				lineHeight={17}
				text={formatText(text)}
				orientation={position}
				angle={0}
			/>
		);
	}
}
```

**Comment by boygirl** [comment]
@billouboq I'm having a tough time diagnosing what might be going wrong. Can you make a codesandbox example of what isn't working?

**Comment by billouboq** [comment]
@boygirl I had issues with onClick not triggering on web (but worked on native). I fixed it by adding this css style on my app :

```css
  .VictoryContainer {
    pointer-events: auto !important;
    touch-action: auto !important;
  }
```
