### ISSUE TITLE
Histogram chart

### ISSUE THREAD

**Issue by kuzzmi** [FormidableLabs/victory#1324]
### The Problem

How to create a chart, where a bar can start at some point and end at some point, like a histogram? 

![image](https://user-images.githubusercontent.com/1727140/59582426-e58fee80-90e0-11e9-8df0-2bb8cae81dbe.png)

I need to make each bar interactive, the amount of bars is dynamic. Bar chart as it is doesn't work well at all due to weird dynamic spacing between bars and each bar can be of a non-fixed width.

Any ideas how to implement this?

**Comment by boygirl** [comment]
@kuzzmi I've added the feature label to this issue. I think you're right that `VictoryBar` is awkward for this kind of chart, and that a new `VictoryHistogram` component would be the best solution

**Comment by ZarifS** [comment]
While I was looking through the documentation I noticed that data supports {x: val, y: val, y0: val} where if you wanted to you could manipulate y and y0 to create where the bar starts and ends, thought it would be useful for histograms being displayed in the horizontal.

This might be a solution for your problem for now.

**Comment by NgoKnows** [comment]
Check out https://formidable.com/open-source/victory/docs/victory-histogram which was recently released!
