### ISSUE TITLE
victory tooltip is rendering behind victory bars in victory chart and victory tooltip not working with VictoryLine in same chart

### ISSUE THREAD

**Issue by kiranSourav** [FormidableLabs/victory#1330]
# Bugs and Questions

### Checklist

- [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ ] I am using the latest version of Victory

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I have a Victory chart in which I'm displaying a stack of Victory bars and a VictoryLine for some Y-axis value(like y= const graph).
Now i want to display a tooltip on click/mouce hover on each item of  stack of victory bars. I'm able to display the tooltip but below tooltips are rendeing behind the graph.
And also victory tooltip is not working at all on Victory Line in same graph.(tried using VictoryVoronoieContainer as well )

![issue_tooltip](https://user-images.githubusercontent.com/51992862/59757090-9d232d00-92a8-11e9-892b-a29a7e532e26.PNG)

**Comment by boygirl** [comment]
@kiranSourav can you make a codesandbox reproduction of the issue you're seeing?

**Comment by HristoEftimov** [comment]
Hello @boygirl , I have the same issue that I can reproduce on the official documentation:

```
<VictoryChart>
  <VictoryGroup offset={18}
    colorScale={"qualitative"}
  >
    <VictoryBar
      data={[{ x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 3 }]}
    />
    <VictoryBar
      data={[{ x: 1, y: 1.5 }, { x: 2, y: 1.5 }, { x: 3, y: 1.5 }]}
      labels={({ datum }) => `y: ${datum.y}`}
      labelComponent={<VictoryLabel dy={20}/>}
    />
    <VictoryBar
      data={[{ x: 1, y: 3 }, { x: 2, y: 4 }, { x: 3, y: 9 }]}
    />
  </VictoryGroup>
</VictoryChart>
```

The `VictoryLabel` is overlapped from the third column:
<img width="542" alt="Screenshot 2020-05-13 at 13 00 46" src="https://user-images.githubusercontent.com/5830987/81799320-d9dbc080-9519-11ea-9c45-268c1f3e2eb0.png">

Is there any solution or workaround?

**Comment by miquelnez** [comment]
Any progress here? It still happening
