### ISSUE TITLE
Using custom components with Typescript

### ISSUE THREAD

**Issue by vjsingh** [FormidableLabs/victory#1332]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

What is the correct way to use a custom component with Typescript?

I'm trying to create a custom component like so:
```
<VictoryChart ...>
   <MyBar>
</VictoryChart>

const Bar: React.FC<InputProps> = props => {
  return (
    <VictoryBar
      style={props.style}
      data={data}
    />
  );
}
```

It appears that Victory uses prop injection on all children of a VictoryChart component. I'm not sure if this prop injection pattern is possible to type in Typescript? Additionally, because I am using react-native-web, which uses Babel, I'm unable to simple ignore the type errors. Type errors result in the app not loading.

Thanks

**Comment by juandelacruz23** [comment]
Old discussion, but did you try removing the React.FC type?

**Comment by wbobeirne** [comment]
The problem with that is that `props` would then be untyped. If you then manually type `props`, you'll still get the warning for this.

My workaround has been to use `React.createElement(Bar)` instead of JSX, seems that the types for React.createElement don't check if you pass all the props.
