### ISSUE TITLE
voronoiDimension tooltip behaves differently with single and multiple points

### ISSUE THREAD

**Issue by dlabrecq** [FormidableLabs/victory#1336]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Tooltips with `voronoiDimension="x"` behave differently for single and multiple data points. When there are multiple points, the tooltip remains within the boundary of the chart, which is what I want. However, when there is only a single point available, the tooltip overflows the chart, which is undesirable. As a result, the tooltip either gets cut off on the left-side or appears behind the chart on the right.

![overflow (1)](https://user-images.githubusercontent.com/17481322/59971056-56506400-9542-11e9-8ee0-01d5bef4b37a.gif)

Ideally, the tooltip would remain within the boundary of the chart when `voronoiDimension="x"` is set. 

Would it be possible to omit the `points.length < 2` check in the `getLabelPosition` function below?

<img width="418" alt="Screen Shot 2019-06-22 at 11 45 22 PM" src="https://user-images.githubusercontent.com/17481322/59971327-efce4480-9547-11e9-8b42-e7dff65874e2.png">

**Comment by boygirl** [comment]
@dlabrecq thank you for this issue. Our next major version bump will include improvements for tooltips. We will include adding more explicit customizability for the tooltip behavior in `VictoryVoronoiContainer`
