### ISSUE TITLE
voronoiDimension tooltip positioning using orientation function

### ISSUE THREAD

**Issue by dlabrecq** [FormidableLabs/victory#1337]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

 Having trouble using a function with the `orientation` prop of `VictoryTooltip`, along with `voronoiDimension="x"`.

In the example below, the `getOrientation` function simply returns either 'left' or 'right' when `d.x < 2` or `d.x > 30`.

```
<VictoryChart 
  containerComponent={
    <VictoryVoronoiContainer
      labelComponent={<VictoryTooltip orientation={(d) => getOrientation(d)}/>}
      labels={this.getTooltipLabel}
      voronoiDimension="x"
  /> }
>
...
```

A function works fine with single points, but the use of a function produces some very odd positioning behavior while hovering over multiple points. Not only does the tooltip overflow on the left-side, but the label position is incorrect while hovering on the far right.

![orientation-function](https://user-images.githubusercontent.com/17481322/59971132-4fc2ec00-9544-11e9-962d-028ece7d5c99.gif)

When a function is replaced with a string (e.g., 'top'), the tooltip behaves as expected. It didn't matter what value the function returns, the problem is simply due to the fact that a function was used.

Looking at the `getFlyoutExtent` function of `victory-voronoi-container.js`, the code does not appear to consider the `orientation` prop as a function, only a string.

**Comment by boygirl** [comment]
@dlabrecq thank you for this issue. I will add this to our next milestone
