### ISSUE TITLE
When Chart width & parent width is the same, Y axis is cut off

### ISSUE THREAD

**Issue by bgold0** [FormidableLabs/victory#1339]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

<img width="1025" alt="Screen Shot 2019-06-24 at 1 48 39 PM" src="https://user-images.githubusercontent.com/4645400/60040367-d5e74b80-9686-11e9-90e3-6ca4930fcb75.png">

When I add a line chart in a container who's width is equal to my chart's width, it cuts off the Y axis.

The only way I can see to fix this is to add `padding={{ left:25 }}` but this quickly becomes an insufficient solution if I wanted to make the graph 300 x 300 which then starts cutting off pieces of the graph.

Any help to figure out if I want the entire chart to fix in a 1000px container, how to make it fit in there would be greatly appreciated.

### Reproduction

https://codesandbox.io/s/basic-victory-example-b6lc7

**Comment by boygirl** [comment]
Unfortunately, you will need to use `padding` to prevent your axis from being cut off.

**Comment by bgold0** [comment]
Thanks @boygirl will do
