### ISSUE TITLE
Upgrade lodash to fix Prototype Pollution and Regular Expression Denial of Service vulnerabilities

### ISSUE THREAD

**Issue by roy-bakker-new10** [FormidableLabs/victory#1340]
Hey there, just a quick mention of the fact that  lodash@4.17.10 has some vulnerabilities, you can find a report here: https://snyk.io/test/npm/lodash/4.17.10.

Upgrading to 4.17.11 fixes both issues.

Thanks for creating this library and continuing support for it!

**Comment by boygirl** [comment]
@roy-bakker-new10 thanks! I'll update that
