### ISSUE TITLE
Stacked bar chart and corner radius #2

### ISSUE THREAD

**Issue by vjsingh** [FormidableLabs/victory#1348]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I would like to use cornerRadius with a stacked bar chart. Currently, this doesn't really work, since all the bars are rounded. See https://codesandbox.io/embed/y2m2o2qzqv

What is the correct interpretation here, I believe, is that only the top of the top bar is rounded. I'm not sure if there is any way to do this with the current API.

See also the request here, in the last comment of this issue: https://github.com/FormidableLabs/victory/issues/705

There was another issue open about this, but the solution doesn't work for me. I don't want to overlap the bars if possible. I would imagine that anybody using a stacked bar chart would not want the current cornerRadius behavior.
https://github.com/FormidableLabs/victory/issues/1289

Thanks. Also - a shoutout to @boygirl for an extremely well-developed and well-maintained library with even more impressive documentation! Thank you so much for your hard work on this excellent library.

**Comment by kalemo** [comment]
Even I am stuck with cornerRadius. 

My requirement is to have to a radius on all the side like `cornerRadius={{topRight: 5, topLeft: 5, bottomLeft: 5, bottomRight: 5}}` which seems to be work perfectly fine [here](https://codesandbox.io/s/y2m2o2qzqv?from-embed) but not in my app. 

If you have figured out a hack, do post it here @vjsingh

**Comment by vjsingh** [comment]
@boygirl Is there any possibility of an update on this feature request? Or if you could point me in the right direction, I could take a stab at a pull request?

**Comment by narinluangrath** [comment]
Hi @kalemo 

You can specify the cornerRadius for the top and bottom of each bar like so https://codesandbox.io/s/issue-1348-solution-7msqp?file=/index.js:192-534

```
<VictoryChart>
  <VictoryStack>
    <VictoryBar
      cornerRadius={0}
      style={{ data: { fill: "firebrick" } }}
    />
    <VictoryBar
      cornerRadius={{ top: 5, bottom: 0 }}
      style={{ data: { fill: "goldenrod" } }}
    />
  </VictoryStack>
</VictoryChart>
```

Let me know if this hasn't answered your question!

**Comment by vjsingh** [comment]
@narinluangrath Thank you so much for commenting, and that helpful solution! =)

Is there any solution for the following use case, where not every bar has every stacked value? In this case, if the "top" segment is not in a bar, then the entire bar segment will not be rounded.

https://codesandbox.io/s/issue-1348-solution-uxhqp?file=/index.js

I'm happy to help with a PR if needed, and if you can point me in the right direction. Thank you,

**Comment by ottovirtanen** [comment]
After several experiments I decided to make my own wrapper of the VictoryStack component that uses the clipPath for rounded corners. This allowed me to make rounded corners for the stack instead of individual bars. Hopefully this will help others as well.

```
import { VictoryStackProps, VictoryStack } from "victory";
/**
 * Wrap your VictoryBar components with this component to get rounded corners.
 */
export const VictoryStackWithRoundedCorners = ({
  children,
  clipPathRadius = "4px",
  ...props
}: VictoryStackProps & {
  children: React.ReactNode;
  clipPathRadius?: string;
}) => {
  return (
    <VictoryStack
      groupComponent={
        <g
          style={{
            clipPath: `inset(0% 0% 0% 0% round ${clipPathRadius})`,
          }}
        />
      }
      {...props}
    >
      {children}
    </VictoryStack>
  );
};

```
