### ISSUE TITLE
Stacked bar charts don't correctly clear style props in event mutations

### ISSUE THREAD

**Issue by vjsingh** [FormidableLabs/victory#1349]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I expect only one bar region to be highlighted red in the example below.
Instead, multiple bar regions are highlighted red at a time.
Clicking a bar region clears all other bar regions in that group, but not in other groups.

### Reproduction

https://codesandbox.io/embed/currying-sunset-brfm1

EDIT: Another solution could be to store the eventKey of the last selection and only use that, as shown in the commented-out code, but I couldn't get that to work either.

**Comment by becca-bailey** [comment]
Closing for now, since this may have been addressed in related issues.
