### ISSUE TITLE
How to make VictoryScatter points cover other points?

### ISSUE THREAD

**Issue by Trancever** [FormidableLabs/victory#1350]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When I render `VictoryScatter` and few points are overlapping each other, labels for all those points stays on top. 
Is there any way to make "next" point cover "previous" point and it's label?

Currently:
![Screenshot 2019-07-10 at 12 05 31](https://user-images.githubusercontent.com/18584155/60964411-899d3c00-a313-11e9-962c-dd47a4baa5cb.png)

What I want to achieve:
<img width="56" alt="Screenshot 2019-07-10 at 13 07 22" src="https://user-images.githubusercontent.com/18584155/60964477-b05b7280-a313-11e9-93b8-9c3c9d71e390.png">

### Reproduction

https://codesandbox.io/embed/cool-bouman-xfx1i

**Comment by boygirl** [comment]
@Trancever Victory is svg based, and so there isn't really good z-index support, it's all based on render order. We made the choice to render all of the labels after all of the data, as most users want labels to end up on top. What you want is still possible, but will involve a little bit more work.  You will need to create a custom data component that renders both your data and label. Here's an example: 
https://codesandbox.io/s/custom-data-with-labels-rf33h

**Comment by Trancever** [comment]
@boygirl Thanks! That's exactly what I needed :)
