### ISSUE TITLE
ScatterPlot: changing tickValues and tickFormat leads to none of my data displaying

### ISSUE THREAD

**Issue by abrown945** [FormidableLabs/victory#1351]
### The Problem

Summary: ScatterPlot does not seem to be able to have its axis tick format changed to strings without removing the data from display.

I want to mimic the format of this chart as I am making a clone of this site. 

![Screenshot (65)](https://user-images.githubusercontent.com/23192489/61055746-26b5ae80-a3c0-11e9-9969-992f47626f41.png)

Without making modifications to my tickValues or tickFormat, my chart looks like so.
![Screenshot (66)](https://user-images.githubusercontent.com/23192489/61055880-67152c80-a3c0-11e9-9693-78144d95f475.png)

I thought that if I wanted my tickValues to be changed to words and keep the data displayed that I would use the currently presented tickValues as the range, then format my tickFomat prop with empty strings in addition to my desired strings like so.

`                            <VictoryAxis dependentAxis`
                                `orientation="left"`
                               ` tickValues={[10,20,30,40,50]}`
                                `tickFormat={['Low Crime', '', '', '', 'High Crime']}   `                                  
                                `/>`
                           ` <VictoryAxis `
                              `  tickValues={[100, 200, 300, 400]}`
                               ` tickFormat={['Few Guns', '', '', 'Many Guns']}    `
                               ` />`

When I use this code however, none of my data is displayed and some of the tick is cut off.

![Screenshot (67)](https://user-images.githubusercontent.com/23192489/61056254-fa4e6200-a3c0-11e9-9244-57f9acc4a1b6.png)

This link will lead you to related code for this issue for reproduction/debugging purposes

https://codesandbox.io/s/flamboyant-shamir-6ms33

I have commented out the code that I have used which is causing the issue.

According to the documentation, 

The tickFormat prop specifies how tick values should be **labeled**. 
The tickValues prop explicitly specifies a set of tick values to **draw on the axis**.

Why is this affecting the display of my data?

**Comment by boygirl** [comment]
@abrown945 I took a look at your sandbox. It looks like you're trying to nest your axis components inside `VictoryGroup`. If you move them outside of `VictoryGroup` but keep them inside `VictoryChart`, I think your chart will render as expected.

**Comment by abrown945** [comment]
Thank you for your help!
