### ISSUE TITLE
No idea how width and height work

### ISSUE THREAD

**Issue by selrond** [FormidableLabs/victory#1352]
I need to create this:

![image](https://user-images.githubusercontent.com/6603389/61136714-5e0d8380-a4c4-11e9-9acb-bf2051fd0027.png)

It's a simple area-like Line chart with dimensions `105 x 20`px.

This is where I am so far: https://codesandbox.io/s/graph-solutions-wc3qc?fontsize=14

The biggest issue I have is that `width` and `height` seem to work totally unpredictably. 

For instance - If the height is less than `100`, the graph is vertically inverted. When the `height === 100` - the graph renders as a flat line. It only starts to work when it's way above 100. 

I get that it computes an aspect ratio, not the exact pixel width, but how it this a proper behavior?

I've searched the whole documentation and looked at many examples for a couple of hours, and I'm beginning to slowly lose my mind...

Am I missing something critical?

**Comment by boygirl** [comment]
@selrond Victory components have default padding (provided by the default theme). It's set to 50, which is much to much for a 100 px graph! You'll want to alter the `padding` prop. It takes either a single number, or an object with values for "top", "bottom", "left" and "right.

**Comment by selrond** [comment]
@boygirl thank you!
These default should be documented on one place somewhere - it's not obvious at all

**Comment by boygirl** [comment]
@selrond sorry for the confusion. The padding prop and its default value is documented for each component: https://formidable.com/open-source/victory/docs/victory-area#padding. If you can think of a more useful or obvious place in the docs to point this out, please consider making a PR to our docs site: https://github.com/FormidableLabs/victory-docs/tree/master/src/content

**Comment by selrond** [comment]
@boygirl the problem is that the default values are scattered throughout the documentation. 
Maybe my expectations were wrong, but I've expected to achieve the result I was after with minimum configuration. This assumes some sensible defaults of course, but currently the only way to learn them is to - paradoxically - go through the whole documentation (of the component one uses) and find them

**Comment by boygirl** [comment]
I understand what you're saying... I think maybe the padding I have in place is a sensible default for _charts_ since there will be axes by default, and without padding they look very broken. I had carried that default across to every component, but It might be appropriate to remove it.

**Comment by selrond** [comment]
@boygirl the simplest solution would be to display default properties together in the docs for every component, alongside the current way - under each individual prop

**Comment by pixelass** [comment]
After reading all of this I still have no idea how it works 🤨 
I think some better examples would really help here.
