### ISSUE TITLE
Function label styles not being evaluated for VictoryBar

### ISSUE THREAD

**Issue by jamstooks** [FormidableLabs/victory#1356]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

`VictoryBar` doesn't seem to evaluate style methods the way `VictoryPie` does.

When:

```javascript
style = {
    data: {
      fill: d => d.color
    },
    labels: {
      backgroundColor: d => d.color
    }
}
``` 

the `backgroundColor` property is evaluated for `VictoryPie`, but not for `VictoryBar`. 

Maybe there's a different way I should be implementing this?

### Reproduction

Here's an example where I use the same `style` property and custom `labelComponent` for both components:

https://codesandbox.io/s/victorycharts-custom-labels-7fgso

![Screenshot from 2019-07-22 11-53-08](https://user-images.githubusercontent.com/585436/61657298-78d7b900-ac77-11e9-8b52-a36c6f07d715.png)

**Comment by jamstooks** [comment]
After diving a little deeper here, it looks like `VictoryPie` evaluates the props before sending them to the custom label, whereas `VictoryBar` doesn't.

To work around this for now, I've added a method to my custom label:

```javascript
const evalProp = prop => (typeof prop === "function" ? prop(datum) : prop);
```

This allows me to get the correct `fill` value with: `fill={evalProp(backgroundColor)}`. I even have to use this for the `text` property:

```javascript
<tspan>{evalProp(text)}</tspan>
```

Unfortunately, what I really need to do is evaluate all styles... as in [`victory-core/src/victory_util/helpers.js`](https://github.com/FormidableLabs/victory/blob/master/packages/victory-core/src/victory-util/helpers.js#L112)

All this leads me to believe that I'm missing some step... maybe my custom label should be wrapped in a `VictoryLabel` wrapper or something? But why would this work with `VictoryPie`, but not with `VictoryBar`?

My quick workaround example is available here: https://codesandbox.io/s/victorycharts-custom-labels-tweaks-uepes

**Comment by boygirl** [comment]
I believe this is fixed in the latest version
