### ISSUE TITLE
VictoryTooltip not visible when mouse pointer is moved very fast between multiple victory charts.

### ISSUE THREAD

**Issue by sumitverma3012** [FormidableLabs/victory#1358]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The VictoryTooltip is not visible when mouse pointer is moved very fast between multiple charts which are aligned next to each other.

### Reproduction

Sandbox:
https://codesandbox.io/s/victorytooltip-visibility-issue-pvd4y

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.
The VictoryTooltip should be visible even if the user is moving his mouse cursor very fast.

**Comment by andrewyoo** [comment]
I can confirm that i'm having the same problem. It is apparent on Safari Version 13.1.2 (15609.3.5.1.3) and Chrome **with dev tools open** 84.0.4147.105 on mac osx. 

Sometimes, the tooltip does not appear if shifting from one chart to another very fast.  It comes back if you mouse off and mouse over again.
