### ISSUE TITLE
VictoryCandlestick chart issue

### ISSUE THREAD

**Issue by jayasivabaskar** [FormidableLabs/victory#1359]
The candles are going beyond the axis(going past x-axis). There seems to be an issue. Tried few approaches and none worked.

Ultimately the candle height is very large and it is going out of the window

Is there a way to resolve these issues ?

**Comment by Dadseeks** [comment]
How about a more direct n less vague approach be employed in resolving the
issue? To put simply, the respecting the basic rules of engagement might
help ease the way.....

Dad

**Comment by boygirl** [comment]
@jayasivabaskar it sounds the the domain is incorrect for your data. Without more detailed information, it's hard to say more. You can try altering the `domain` prop on `VictoryChart` or adding `domainPadding`. If you're still struggling, please make a small reproduction in codesandbox, and I'll try to help you out.
