### ISSUE TITLE
Break long words on victory website - playground

### ISSUE THREAD

**Issue by knowbody** [FormidableLabs/victory#137]
*Not sure if this should be here or in the ecology issues.*

<img width="975" alt="screen shot 2015-12-29 at 23 57 12" src="https://cloud.githubusercontent.com/assets/3802023/12044426/dc0bc9c6-ae88-11e5-8c2c-8278b2287e59.png">

Probably we want to use something like:

```css
overflow-wrap: break-word;
```

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#21
