### ISSUE TITLE
Poor Performance with VictoryGroup and VictoryStack (and VictoryChart)

### ISSUE THREAD

**Issue by jackson-ml** [FormidableLabs/victory#1376]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Victory has very poor performance when a VictoryStacks (with plenty of children) are nested within VictoryGroup, nested within VictoryChart. This is due to the fact that each of these "wrapper" classes call a method named getCalculatedProps on render or during getChildren. getCalculatedProps figures out props like domain, scale, stringMap, and categories from the nested children, but to do that it traverses through each of its children up to 4 times! To make matters worse, when one of these traversals encounters a child with nested children, it calls getChildren and therefore that class's getCalculatedProps, traversing **its** children 4 more times. In this manner, the (up to) 4 traversals multiply over the depth of nesting; When you have VictoryStacks within a VictoryGroup within a VictoryChart, each of the VictoryStacks' children are being traversed **64** times just to calculate the props for the VictoryChart!

### Reproduction

There's another bug with stacked bars within victory group, where the offset doesn't apply correctly (in fact, it shifts all of the bars in a single direction by a constant factor of the offset , possibly off the chart), but that is already an open issue. Here is a demonstration of the incredibly slow render times of VictoryStack within VictoryGroup:

https://codesandbox.io/s/github/jackson-ml/group-stack-performance

When you click the button to show the chart, you'll notice it takes a good 5 seconds or so to render.

**Comment by boygirl** [comment]
@jackson-ml Thanks for the reproduction! I'll see what I can do to minimize the impact of `getChildren` / `getCalculatedProps` methods. If you have any thoughts on how to go about this, I'd be happy for the help.

**Comment by jackson-ml** [comment]
I've been thinking about this all day, and I really want to start contributing to open source more, so I'd love to help if I can. I have a bunch of ideas, but not definite solutions yet. 

I've thought about the problem from a few angles; first, just plain reduce fewer times. In theory getCalculatedProps should only have to call Helpers.reduceChildren once, and get all of the calculated props from children it needs from that (domain, scale, categories, and stringMap, typically). Right now, however, because that is segmented out into different function calls (Wrapper.getCategories, Wrapper.getDomain, Wrapper.getScale, and createStringMap), getCalculatedProps ends up calling Helpers.reduceChildren up to 4 times. I have some code along this idea, a function that takes in an object with a bunch of iteratees and calls Helpers.reduceChildren in a way that combines all of them at once.

This approach has problems, though, because when the code currently calls Helpers.reduceChildren is very conditional. For example, createStringMap and Wrapper.getCategories both care about the output of Wrapper.getStringsFromChildren, but that cares about the output of two different reductions: Wrapper.getStringsFromCategories and Wrapper.getStringsFromData. Thus, our combined reducer would need to effectively perform both reductions.

There are some other ways to approach the problem; one workaround I had for this problem is to pass a categories prop (an empty array, in my case) to VictoryChart. Even though this isn't a documented prop, it short circuits getCategories, which is otherwise a relatively expensive call. Categories is kinda a data idea, so it doesn't totally fit in VictoryChart, but it's also kinda a domain idea, so it does. It might be worth thinking about supporting this.

Finally, when I was staring at Helpers.reduceChildren, I realized that because reduceChildren reduces through *all* nested children, it shouldn't have to calculateProps for those children with subchildren; after all, those children are just calculating based on their subchildren, which reduceChildren will already eventually traverse.

I hope this helps! If one of the directions seems promising, I'll definitely start trying to write more code there!

**Comment by boygirl** [comment]
Thanks for taking the time to write this up! A couple of other thoughts:

What if we store a flattened list of all the children and pass it as an optional argument to the higher level functions that are normally traversing children. This won't help in every case (i.e. getDomain needs to retain information about the shape of the tree for groups and stacks to actually work), but in some of them it could at least be used to cut out extra work. (i.e. check if any of the children even have a `categories` prop and return early if they don't)

**Comment by akx** [comment]
I'm also seeing this issue whenever my Victory-containing chart component updates.
My tree is pretty much

* VictoryChart (regular container)
  * VictoryGroup (dataset 1 set here as `data`)
     * VictoryLine (to render line)
     * VictoryScatter (to render each point)
  * VictoryGroup (dataset 2 set here as `data`)
     * VictoryLine (to render line)
     * VictoryScatter (to render each point)
  * _... rinse and repeat ..._
  * VictoryLegend

and I'm currently computing each `data` within `render()`.  For 10 datasets, it takes 600 msecs (of which only 1.5 msec is my data-mangling code, I checked 😇)  to render the chart and the profiling flamechart looks like
![Screenshot 2019-08-29 at 14 50 38](https://user-images.githubusercontent.com/58669/63937991-746ba080-ca6c-11e9-98d1-45b44536ae8b.png)

I think the aforementioned approach of memoizing the list of children to traverse within `getCalculatedProps` would help a lot to start with.

**Comment by boygirl** [comment]
@akx thanks for more detail. I'm on vacation until the 15th, but this is where I'll start when I get back.

**Comment by RishC** [comment]
@boygirl Is there any progress that we can track or help with? I'm running into the same problem

**Comment by dmmulroy** [comment]
Hi y'all, I've been working on this a bit and currently have some promising improvements!  With @jackson-ml's codesandbox example above, I have been able to improve the time to render from 4.47s on my macbook pro to 690ms.  I have a few more ideas I'm exploring and I'd like to thoroughly make sure I have introduced no regressions, but I plan to open a PR this week 🎉🚀
