### ISSUE TITLE
Charts rendering everything in black, no colours extracted from data

### ISSUE THREAD

**Issue by DaveClissold** [FormidableLabs/victory#1377]
### Checklist

- [ X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X ] I am using the latest version of Victory

- [ X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When rendering a chart, no colours are passed into the charts style using the function to extract from the data as follows
``` 
style={{
              data: {
                fill: d => d.fill
              }
            }}
```
Everything renders in black

### Reproduction

here is a repo of the project

https://github.com/DaveClissold/victory-problem

**Comment by boygirl** [comment]
Hi there! Version 33.0.0 of victory was released earlier this week, and involves breaking changes. I'm still in the process of updating the docs 😅

To fix your issue, try

fill: ({ datum }) => datum.fill

You may also want to check out CHANGELOG.md for a full list of changes. Expect new docs by early next week!

**Comment by DaveClissold** [comment]
Awesome thanks.
