### ISSUE TITLE
Victory chart flatlines on data update

### ISSUE THREAD

**Issue by Boucher-David** [FormidableLabs/victory#1382]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

In VictoryChart, updating the data passed into VictoryLine causes the chart to 'flatline':

https://ookla.d.pr/lw6KwL

At a temporary measure on our end I unmount the VictoryChart component, rendering a loading animation, and then re-mount it. This seems to fix the issue. The flatline can also be fixed  by hovering my mouse over the chart and loading the chart label component. I suspect it triggers a re-render within victory and that makes it display as it should.

Obviously I'd prefer not to have to do these options. Is this something you can look into?

We were previously on version 30.4.1 and did not see this issue.

Edit: We tested changing the animation time and it seemed to have a positive affect on the flatline issue. An animation time over 300ms, or removing the animation altogether, stopped us getting the flatline issue.

Thanks!

**Comment by becca-bailey** [comment]
Closing this issue because it is unverified.
