### ISSUE TITLE
Animation not working on Victory Pie

### ISSUE THREAD

**Issue by irohitb** [FormidableLabs/victory#1383]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

Hey 
- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Animate Prop doesn't seem to be working for Victory Pie

### Reproduction

Code Sandbox Link: https://codesandbox.io/embed/basic-victory-example-stu7l

Please describe the feature you're requesting in detail.

**Comment by mattgle** [comment]
This is an article that i wrote, hope it helps you https://medium.com/wolox-driving-innovation/how-to-animate-a-pie-chart-with-victory-in-react-native-db5997b991a5

**Comment by becca-bailey** [comment]
This is a duplicate issue of #531
