### ISSUE TITLE
Axis renders 1970 date as cross axis point due to Unix epoch

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/victory#139]
Taking the "Decades" example from the [VictoryChart docs](http://victory.formidable.com/docs/victory-chart) and simply adding 1960 (or any pre-1970) reveals an issue with our date handling.

Since in Unix epoch land 1970-01-01 is 0, it's treated as the cross axis point. https://jsfiddle.net/g4f58Lwf/1/

<img width="434" alt="screen shot 2015-12-30 at 10 00 05 am" src="https://cloud.githubusercontent.com/assets/53522/12054878/216ba0f6-aedc-11e5-8b3f-d5684ba8b3d9.png">

This is an implementation detail that should not be revealed or require manually adjusting the axis.

**Comment by mdramos** [comment]
Try the fix is here: FormidableLabs/victory-chart#80, it hasn't been implemented yet into the npm modules

**Comment by exogen** [comment]
@mdramos: Tried it and it still happens with the fix – unfortunately correctly adding the numbers doesn't change the fact that 1970-01-01 value is 0. I think we'll need to special-case our `crossAxis` handling when dealing with dates.

**Comment by ebrillhart** [comment]
fixed with https://github.com/FormidableLabs/victory-core/pull/90 and https://github.com/FormidableLabs/victory-chart/pull/318
