### ISSUE TITLE
Replace tick mark with icons

### ISSUE THREAD

**Issue by vishnup95** [FormidableLabs/victory#1390]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I want to replace the tick marks in my charts with icons. In simple terms suppose I have a social media analysis chart that shows various social media stats, I would like to replace the social media name tick marks with the icons. Preferably font awesome icons. Is it possible to do so with victory. How would I go about it? I have tried tickFormat and component for ticks. 

# Feature Requests (?)

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

I think it's possible, can you please point me in the right direction with an example or sorts.

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by boygirl** [comment]
You'll need to replace the `tickLabel` component with a custom component. Just make sure it's something that can render within an svg tag, or you'll need to use `foreignObject`. 

Here's an example with cat emoji 😹
https://codesandbox.io/s/cat-tick-labels-9ls7t
