### ISSUE TITLE
Unable to show image as data label on each data point in area chart

### ISSUE THREAD

**Issue by rohitsg** [FormidableLabs/victory#1391]
# Bugs and Questions
Here i want to show product images on each data point as data labels. But unable to achieve that. I am stuck here. Please anybody worked on this before. Any help will be appropriated.

### Checklist

-  This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

-  I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

-  I am using the latest version of Victory

-  I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

-  I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

-  I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@rohitsg you will need to use `foreignObject` to render non-svg elements within the svg that Victory renders.

**Comment by aldimirprincipal** [comment]
@boygirl Could you please provide an example? I'm trying to put some png icons for a weather app and I need this. Thanks for this library!
