### ISSUE TITLE
Making the components more accessible - specifically re: aria-labelledby, tabindex, and desc

### ISSUE THREAD

**Issue by alexdunham** [FormidableLabs/victory#1392]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am trying to make my VictoryPie and VictoryLegend as accessible as possible - I noticed that the <svg> elements have an `aria-labelledby` property. However they seem to be referencing non-existent elements - for example my VictoryPie component's <svg> has `aria-labelledby="victory-container-1-title victory-container-1-desc"` and when I search the HTML produced, there appear to be no such elements.

In addition, I am trying to set tabIndex on some of the components and this appears to not be supported - can this be added or can elements have tabindex="0" by default so that the user is able to tab through legend items, for example?
I also tried to set the description on the legend label component, e.g. `labelComponent={<VictoryLabel desc="DESCRIPTION" />}` and would really like to be able to access the datum it is referring to, however a function such as `({datum}) => datum.x ` or something to that effect appears to be unsupported.

Ideally it would be great if a user could tab through things to activate events such as onClick that the mouse user can access. If it is 'opt-in' that's fine, so long as things like the above can be set by the developer.

If I have misunderstood, please let me know.

Thanks,

Alex

**Comment by boygirl** [comment]
@alexdunham Thank you for this issue! Hearing specifically what you need for this is super helpful. It sounds like my action items are:
- Change the `desc` prop to take a function everywhere it exists, and make sure it's a standard prop on all primitive components.
- Add a `tabIndex` prop (number or func) to all primitive components with a default of zero. 
- Fix the `labeledby` issue you mention. That sounds like a bug. 
Is there anything else that would help?

**Comment by alexdunham** [comment]
Those updates would be wonderful! Thank you for doing this, I really
appreciate it! If I notice any more a11y improvements I will let you know :)

**Comment by boygirl** [comment]
@alexdunham here's the a11y PR I promised: https://github.com/FormidableLabs/victory/pull/1404. I decided not to make the default `tabIndex={0}` because I didn't want to create a breaking change. I'm going to merge this change and release a patch today. It would be great if you could test it out and let me know if anything is not working as you would expect it to.

**Comment by boygirl** [comment]
@alexdunham the patched version is `victory@33.1.0`

**Comment by alexdunham** [comment]
Hi @boygirl , just letting you know I tried out the patch, and it's wonderful! Thank you so much!
