### ISSUE TITLE
Display multiple elements with different styles within a Tooltip

### ISSUE THREAD

**Issue by aurerua** [FormidableLabs/victory#1396]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Would it be possible that the VictoryBar's `labels` prop receive a function that returns an element instead of just a string?

#### Problem:

How can multiple elements with different styles be displayed within a Tooltip while having the flyout sized correctly?

What I would like to achieve is to display two values within a tooltip with one of them having a different font size, like this:
![label](https://user-images.githubusercontent.com/10965364/64876491-7aa67300-d64f-11e9-846e-62a1a1f16bbb.png)

Displaying both the x and y axis labels in a VictoryTooltip for a VictoryBar hasn't been difficult.

I also managed to display the x-axis datum below the y-axis datum within the label with a different font size by using a custom Tooltip and rendering within it two <Text> elements with a different font-size.

But, the size of the Flyout doesn't always fit (depending on the length of the labels' strings) because it seems to be calculated from the value passed via the `labels` prop of `VictoryBar` where the given function **has to return a string** and from the `fontSize` that can be passed via the style prop (`labels: { fontSize: 21 }`) but since I need to apply too different font sizes this is problematic. 

If the VictoryBar's `labels` prop received a function that returns an element instead of just a string and then calculated from it the size of the Flyout, it would then be possible to render more than just a string within labels. Or is there already a solution?

**Comment by boygirl** [comment]
@aurerua The function can actually also return an _array_ of strings, and can then be styled with an array of style objects. Check it out: https://codesandbox.io/s/array-labels-and-styles-zqzui.
