### ISSUE TITLE
React error about "stringTicks" in console after upgrading to version 33

### ISSUE THREAD

**Issue by kaiyoma** [FormidableLabs/victory#1397]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

After upgrading from 32.3.3 to 33.0.5, we are now seeing a React error in the console when rendering a LineGraph with a Line inside:

```
Warning: React does not recognize the `stringTicks` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `stringticks` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

We don't use `stringTicks` anywhere in our code, and in fact our `Line` component is incredibly simple, so I believe this is an error in Victory somewhere.

**Comment by tohjustin** [comment]
Just wanted to give an update on this issue, the React warning above surfaces when the following conditions are met:
- `<victory.VictoryAxis />` is using a theme
- `<victory.VictoryAxis />`'s `props.tickComponent` is using `<victory.Line />`

Example: 
```
<VictoryAxis
    width={200}
    height={200}
    offsetY={200}
    domain={[-10, 10]}
    theme={VictoryTheme.material}
    tickComponent={<Line {...lineProps} />}
    standalone={false}
/>
```

Live demo: https://codesandbox.io/embed/mystifying-roentgen-64kkv

We can simply fix this issue by swapping `<victory.Line />` with `<victory.LineSegment />`

**Comment by boygirl** [comment]
@kaiyoma and @tohjustin we changed how the `Line` primitive component renders. It now renders all the props given to it rather than a whitelisted subset. `LineSegment` is the default `tickComponent` for `VictoryAxis, and `LineSegment` ends up eventually rendering `Line`. I know this is super confusing in the case of `Line` / `LineSegment`. It's a lot more senible for components like `VictoryBar` for example, which renders a `Bar` component which in turn renders a `Path`

**Comment by brandontle** [comment]
Hi @boygirl What is the solution to getting rid of this error? This still occurs in v35.3.2 with the exact same setup originally described.

**Comment by boygirl** [comment]
@brandontle The solution would be to use `LineSegment` rather than `Line` as your `tickComponent`.
