### ISSUE TITLE
VictoryBrushContainer not updating as expected

### ISSUE THREAD

**Issue by xseignard** [FormidableLabs/victory#1399]
### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hello,
In the following example, the VictoryBrushContainer is not updating against a domain change.

### Reproduction

On the following codesanbox: https://codesandbox.io/s/tender-pike-dptn7

Do the following:

- Click on the ALL button
- Reduce the brush zone
- Click on the 1Y button

Clicking on the 1Y button should expand the brush zone to the whole area, but it's not. Is it something I do wrong or a bug ?
Regards

**Comment by xseignard** [comment]
Any comment ?

**Comment by xseignard** [comment]
What can I do to see this issue addressed ?

**Comment by xseignard** [comment]
Well, the most efficient way to solve this issue was to drop Victory lib...

**Comment by becca-bailey** [comment]
Closing in favor of #2111
