### ISSUE TITLE
OnBrushDomainChangeEnd provides wrong domain

### ISSUE THREAD

**Issue by sup-bs** [FormidableLabs/victory#1400]
# Bugs and Questions

### Checklist

- [x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

`onBrushDomainChangeEnd` of `VictoryBrushContainer` provides the wrong domain: According to the Documentation, the current domain should be given. Instead, the domain of the whole Chart is provided. 
In contrast, `onBrushDomainChange` works as expected. 

### Reproduction
See the following sandbox:
https://codesandbox.io/s/basic-victory-example-zrijg?fontsize=14

Drag the domain; the domains for `onBrushDomainChangeEnd` and `onBrushDomainChange` are printed in the console.

**Comment by jorko95** [comment]
I have the same problem, onBrushDomainChangeEnd provied the hole chart domain, and not the selected domain.

**Comment by dippindots** [comment]
Same here, any solution?

**Comment by jorko95** [comment]
I found a partial solution, I made this on my code:
I create two separate functions, the first to stock the value of the domain in a global variable, and the second to set the new domain to the state, using setState.

handleBrush called on onDomainChange
`handleBrush(domain) {`
  `this.nDomain = { x: [domain.x[0], domain.x[1]] };`
` }`

onMouseUp called on onDomainChangeEnd
`onMouseUp() {`
    `this.setState({`
      `selectedDomain: this.nDomain,`
   ` });`
  `}`


`onBrushDomainChange={domain => this.props.handleBrush(domain)}`
 `onBrushDomainChangeEnd={domain => this.props.onMouseUp()}`

 It works for me.

**Comment by dippindots** [comment]
@jorko95 Thanks for sharing your solution! I also have a workaround for my case, which is using debounce function from lodash: 
`onBrushDomainChange={_.debounce(this.onSelection, 500)}`.
