### ISSUE TITLE
Tooltip sometimes does not change in VictoryVoronoiContainer

### ISSUE THREAD

**Issue by nburt** [FormidableLabs/victory#1403]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

We have an application that displays time series data and has a date picker to query over time. It also overlays multiple `VictoryLine`s with data from different sensors. I can't pin down exactly what causes it but occasionally the tooltip will be stuck on the first data point of the graph. It only occurs for certain time ranges, other times hovering over the graph triggers the tooltip to change as expected.

Pinning Victory to version 32.2.3 fixes the issues so I'm assuming that this bug was introduced with changes to the `VictoryVoronoiContainer` in 33.0.0.

### Reproduction

Reproduction: https://codesandbox.io/s/victoryvoronoicontainer-bug-1o4tq

I've created a select dropdown to toggle between data that works + data that causes the bug. Please let me know if there are any additional details that would be helpful

**Comment by nburt** [comment]
Just wanted to add on that I've also tested with 33.1.0 and this is still an issue.

I added onActivated/onDeactivated callbacks to the `VictoryVoronoiContainer` and it looks like for the buggy charts it calls them both immediately when the mouse moves over the chart.

**Comment by boygirl** [comment]
@nburt I just published `victory@33.1.1` with changes to the underlying method we're using for finding the nearest point. I just checked the new version against your sandbox, and it seems to work as expected. Thanks for providing a reproduction! 

I'm going to close this issue, but please do open another if you notice any persisting edge cases.

**Comment by nburt** [comment]
Thanks! Confirmed that this update fixes it
