### ISSUE TITLE
linearGradient inside VictoryChart throws 2 console errors

### ISSUE THREAD

**Issue by sbsrnt** [FormidableLabs/victory#1405]
### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Basically, whenever we provide `linearGradient` inside `VictoryChart` we get 2 console errors.:

![image](https://user-images.githubusercontent.com/19862545/65846866-2eab3c00-e37a-11e9-91a8-e179d29ff35d.png)

Aforementioned errors are intended by the design of `VictoryChart` component according to [standalone docs](https://formidable.com/open-source/victory/docs/common-props/#standalone): `[..., however, wrapper components like VictoryChart, VictoryStack, and VictoryGroup force children to use standalone={false}]`.

`linearGradient` does not have `standalone` attribute hence the errors.

Ideally, the expected behaviour is to not show those errors for `linearGradient` elements.

We could move `linearGradient` element outside of `VictoryChart` but then the style is not rendered unless there is an alternative way to provide `gradient` styles for `VictoryArea` 🤔.

### Reproduction

[CodeSandbox](https://codesandbox.io/embed/basic-victory-example-wn9ly)

**Comment by boygirl** [comment]
@sbsrnt would it be possible to create a custom component that renders your linear gradient but ignores the props that come in from VictoryChart?

**Comment by sbsrnt** [comment]
@boygirl yeah, seems like that is a good alternative to the issue - [https://codesandbox.io/embed/basic-victory-example-wn9ly](https://codesandbox.io/embed/basic-victory-example-wn9ly)

We can close this then.
