### ISSUE TITLE
when i use invertAxis prop , the axisValue sometimes have bug

### ISSUE THREAD

**Issue by Elliot2636** [FormidableLabs/victory#1410]
my environment：
"react": "16.8.3",
"react-native": "0.59.8",
"victory-native": "^33.0.0"

this is no inverAxis prop, my code
`<VictoryChart polar
          startAngle={0}
          endAngle={180}
        >
          <VictoryPolarAxis
            tickValues={[0, 100]}
            labelPlacement="vertical"
          />
          <VictoryPolarAxis
            dependentAxis
            axisValue={100} //or axisValue={0}
            label={TemperatureValue}
            style={{ tickLabels: { fill: "none" } }}
            labelPlacement="perpendicular"
          />
        </VictoryChart>`
when I set axisValue = 0 or 100 ,I will get right result, picture is result
<img width="304" alt="截屏2019-10-09上午11 22 29" src="https://user-images.githubusercontent.com/45113206/66449454-adddf580-ea87-11e9-9395-ff8bcfacf74c.png">
<img width="304" alt="截屏2019-10-09上午11 22 40" src="https://user-images.githubusercontent.com/45113206/66449466-b1717c80-ea87-11e9-8878-087eb585a39d.png">
there is have inverAxis prop, my code
`<VictoryChart polar
          startAngle={0}
          endAngle={180}
        >
          <VictoryPolarAxis
            invertAxis={true}
            tickValues={[0, 100]}
            labelPlacement="vertical"
          />
          <VictoryPolarAxis
            dependentAxis
            invertAxis={true}
            axisValue={0} //or axisValue={0} 
            label={TemperatureValue}
            style={{ tickLabels: { fill: "none" } }}
            labelPlacement="perpendicular"
          />
        </VictoryChart>`
when I set axisValue = 0 or 100 , the result is no difference
<img width="304" alt="截屏2019-10-09上午11 23 20" src="https://user-images.githubusercontent.com/45113206/66449539-06ad8e00-ea88-11e9-9d55-314f76f65e43.png">

**Comment by boygirl** [comment]
@Elliot2636 I think this is happening because when you set the `axisValue` prop it explicitly sets the position of the axis, so `invertAxis` is not applied. That prop is used for setting the default position of the axis. I think the documentation could be clearer on this point. I will open an issue on the docs to explain.
