### ISSUE TITLE
Stacked group bar with large data set, the groups are crossing the chart domain

### ISSUE THREAD

**Issue by jayasivabaskar** [FormidableLabs/victory#1411]
In case of large data set, the stack groups are
 Moving out of the provided chart space or domain.
The x-axis ticks are not alligned to the center of the group.
We tried giving domain padding as well but the implementation was not fruitful.
Please see the attachment for more clarity.
![IMG_20191011_160416](https://user-images.githubusercontent.com/32515618/66659537-4f6c6f00-ec61-11e9-80fc-5a6d86354e13.jpg)

**Comment by boygirl** [comment]
@jayasivabaskar thank you for reporting this. It does look like a bug that I need to look into more. One thing you might try in the meantime, though would be to add the `singleQuadrantDomainPadding={false}` prop along with `domainPadding`.  You can read more about what that prop does here: https://formidable.com/open-source/victory/docs/common-props/#singlequadrantdomainpadding

**Comment by boygirl** [comment]
related to https://github.com/FormidableLabs/victory/issues/1407
