### ISSUE TITLE
Victory Axis orientation prop and dependentAxis and independentAxis namespaces

### ISSUE THREAD

**Issue by kilemensi** [FormidableLabs/victory#1413]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

From victory axis [theme](https://formidable.com/open-source/victory/docs/victory-axis#theme) support description, it says:
> _Note_: Use the dependentAxis and independentAxis namespaces to theme axes by type. These namespaces will be merged with any props and styles supplied in the axis namespace.

But looking at `getOrientation`, only `props` are checked for orientation:
https://github.com/FormidableLabs/victory/blob/b2229e33c34cc30557871c6bc41f783cbb0ed4d4/packages/victory-axis/src/helper-methods.js#L301-L310

It **never** checks theme or `theme.dependentAxis` or `theme.independentAxis` namespaces for default orientation setting. As a result, setting orientation in say, `theme.dependentAxis.orientation`doesn't work.

### Reproduction

https://codesandbox.io/s/basic-victory-example-dmktv

**Comment by boygirl** [comment]
@kilemensi Thank you for reporting this! VictoryAxis and VictoryPolarAxis should merge themes with props prior to this check.
