### ISSUE TITLE
VictoryLegend data prop: label vs labels

### ISSUE THREAD

**Issue by kilemensi** [FormidableLabs/victory#1414]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

From the document (https://formidable.com/open-source/victory/docs/victory-legend#data), the `data` prop accepts an array of `{ name, symbol, **labels** }` objects. But from the code, the propTypes check for `{ name, symbol, **label** }`: https://github.com/FormidableLabs/victory/blob/b2229e33c34cc30557871c6bc41f783cbb0ed4d4/packages/victory-legend/src/victory-legend.js#L57-L63

This produces a runtime warning if your `data` contains a `label` attribute of type other than `object`. For example, in our case, we need the `label` attribute to be a string we can show as a tooltip when a user hovers over the legend. 

### Reproduction

N/A : Problem clearly on the source code.

**Comment by boygirl** [comment]
@kilemensi Thanks for this. It appears to be correct in the source code, and incorrect in the docs, I will open an issue that references this one from the docs repo.

**Comment by oskari** [comment]
Still an issue, the code defines with PropTypes data to be array of objects with fields: name, **label** and symbol
https://github.com/FormidableLabs/victory/blob/7f634e17d33bfcac3ee836a9b1c970e0e4e158cb/packages/victory-legend/src/victory-legend.js#L57-L63

while the TypeScript definition says it should be: name, **labels** and symbol
https://github.com/FormidableLabs/victory/blob/7f634e17d33bfcac3ee836a9b1c970e0e4e158cb/packages/victory-legend/src/index.d.ts#L27-L36
