### ISSUE TITLE
Stacked bar chart panning performance issue

### ISSUE THREAD

**Issue by sezginriggs** [FormidableLabs/victory#1418]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm using VictoryZoomContainer as containerComponent of VictoryChart but panning is too slow on iOS and Android.

I only have one Victory Stack and 3 VictoryBar (with only 12 items as data) in it but it's still hard to drag and too slow.

### Reproduction

Here you can find and run the code: [https://snack.expo.io/SJhMSjQqH](https://snack.expo.io/SJhMSjQqH)

**Comment by hntddt123** [comment]
I gave up on VictoryZoomContainer and render a Victorychart with off-screen width and wrapped with Scrollview which works perfectly!

**Comment by sezginriggs** [comment]
@hntddt123 how did you set the off-screen width? May you please share a code example if possible?

**Comment by taromorimoto** [comment]
Are there any plans to improve Victory chart panning performance on React Native?

**Comment by Critically** [comment]
> Are there any plans to improve Victory chart panning performance on React Native?

+ Same question

**Comment by becca-bailey** [comment]
Apologies for the late response, but we are currently starting to plan out a re-write of some of Victory's pan and zoom behavior that should address some of these performance issues. I'm going to close this ticket and move the discussion to #2111.
