### ISSUE TITLE
VictoryTooltip displays a value of 0 with no padding

### ISSUE THREAD

**Issue by aurerua** [FormidableLabs/victory#1419]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

VictoryTooltip displays a value of 0 with no padding which does not happen for other values.

### Reproduction
Here a modified version of the [Simple Tooltips](https://formidable.com/open-source/victory/guides/tooltips#simple-tooltips) example from the docs:
https://codesandbox.io/s/basic-victory-example-ltx57

![otherValue](https://user-images.githubusercontent.com/10965364/67829505-c1eda380-fad7-11e9-945f-1254730de1a7.png)

![zero](https://user-images.githubusercontent.com/10965364/67829515-c7e38480-fad7-11e9-9b52-fbc1744d88d7.png)

**Comment by boygirl** [comment]
@aurerua Thanks for reporting this bug
