### ISSUE TITLE
theme provider

### ISSUE THREAD

**Issue by sibelius** [FormidableLabs/victory#1421]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'd like to make all my chats to follow the same Theme

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I'd like to make all my chats to follow the same Theme

I'd like to have something like <VictoryThemeProvider /> that will make all my Victory charts to the default theme of my application

Simple example of how to implement this
```jsx
const contextTheme = useVictoryTheme();
const theme = props.theme || contextTheme || VictoryTheme.default;
```

**Comment by becca-bailey** [comment]
We are currently working on this as a part of #2076. One of the goals of using context of Redux for managing state under the hood would be to expose these kinds of provider hooks to make it easier for custom components to access  state. Thanks for the suggestion! I'm going to close this issue for now and we can move discussion to 2076.
