### ISSUE TITLE
VictoryAxis gradient

### ISSUE THREAD

**Issue by mustkem** [FormidableLabs/victory#1427]
Hey there - Thank you for the project

 I have a design requirement for a area stacked graph where the the x-axis color is filled with a gradient. 

There is an example of gradient fill for stacked area but I could not find a way to fill the same or another gradient to x-axis. 

https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory

For code please follow below link
https://stackoverflow.com/questions/58645052/how-to-fill-gradient-to-x-axis-in-victory-chart

Thanks!

**Comment by narinluangrath** [comment]
Hi @mustkem,

Yep the solution is pretty similar to the area chart

```
<div>
  <svg style={{ height: 0 }}>
    <defs>
      <linearGradient
        id="myGradient"
        x1="0%"
        x2="100%"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0%" stopColor="red" />
        <stop offset="25%" stopColor="orange" />
        <stop offset="50%" stopColor="gold" />
        <stop offset="75%" stopColor="yellow" />
        <stop offset="100%" stopColor="green" />
      </linearGradient>
    </defs>
  </svg>
  <VictoryAxis
    style={{
      axis: {
        stroke: "url(#myGradient)",
        strokeWidth: 10
      }
    }}
  />
</div>
```

Sandbox: https://codesandbox.io/s/issue-1427-solution-571gu?file=/index.js:165-908
