### ISSUE TITLE
Victory Axis-Label Overlap with Ticks

### ISSUE THREAD

**Issue by dchicchon** [FormidableLabs/victory#1431]
# Bugs and Questions

Currently I am using Victory Line to chart a graph with Victory Axis. My current issue is that my y-axis tick marks are overlapping with my y-axis label that I have set. I have tried to resolve the issue by adding the props fixLabelOverlap={true} to no avail. 

Here is my code:

```javascript
import React from "react";
import { render } from "react-dom";
import {
  VictoryChart,
  VictoryContainer,
  VictoryLabel,
  VictoryAxis,
  VictoryLine,
  VictoryTooltip
} from "victory";

class App extends React.Component {
  render() {
    return (
      <VictoryChart
        domainPadding={30}
        height={600}
        width={1050}
        containerComponent={<VictoryContainer responsive={false} />}
        style={{ parent: { maxWidth: "100%" } }}
      >
        <VictoryAxis
          axisLabelComponent={<VictoryLabel />}
          scale={{ x: "time" }}
          style={{
            axisLabel: {
              fontFamily: "inherit",
              fontWeight: 100,
              letterSpacing: "1px",
              stroke: "white",
              fontSize: 20
            },
            grid: { stroke: "lightgrey" },
            tickLabels: {
              fontFamily: "inherit",
              fontWeight: 100,
              letterSpacing: "1px",
              stroke: "#61dafb ",
              fontSize: 20
            }
          }}
        />
        <VictoryAxis
          dependentAxis={true}
          axisLabelComponent={<VictoryLabel />}
          label={"Number of Commits"}
          fixLabelOverlap={true}
          style={{
            axisLabel: {
              fontFamily: "inherit",
              fontWeight: 100,
              letterSpacing: "1px",
              stroke: "white",
              fontSize: 20,
              margin: "30px"
            },
            grid: { stroke: "lightgrey" },
            tickLabels: {
              fontFamily: "inherit",
              fontWeight: 100,
              letterSpacing: "1px",
              stroke: "#61dafb ",
              fontSize: 20,
              marginBlock: "20px"
            }
          }}
        />

        {/* {this.state.studentData
          ? this.state.studentData.map((student, i) => (
              <VictoryLine
                interpolation="natural"
                name={student.author.firstName}
                key={i}
                labelComponent={<VictoryTooltip />}
                labels={() => `${student.author.firstName}`}
                data={student[`${this.state.dataFormat}`]}
                style={{
                  data: { stroke: student.color, strokeWidth: 1.5s }
                }}
                x="date"
                y="count"
              />
            ))
          : ""} */}
      </VictoryChart>
    );
  }
}

render(<App />, document.getElementById("root"));

```
[Sandbox](https://codesandbox.io/s/basic-victory-example-jhp13?fontsize=14)

**Comment by StraightOuttaCrompton** [comment]
You can use the ```dy``` prop on the ```VictoryLabel``` to alter the positioning of the label.

```js
<VictoryAxis
    dependentAxis
    axisLabelComponent={<VictoryLabel dy={-12} />}
    label={"Dependent axis"}
/>
```

[Possible solution sandbox](https://codesandbox.io/s/basic-victory-example-4jp88)

**Comment by narinluangrath** [comment]
Hi @dchicchon! You just need to increase the `axisLabel` padding (and chart padding). Here's a fork of your sandbox: https://codesandbox.io/s/issue-1431-solution-4q3rw

**Comment by jumble** [comment]
The above solution (set a fixed axisLabel padding) works for @dchicchon's specific case as their tick labels are a fixed length. I am running into a similar problem, but my tick labels are a variable length. Does Victory include a way to dynamically position the axis labels with respect to the tick labels, or is this left to the user to configure? Unclear what best practice here would be.

**Comment by osamaqarem** [comment]
> The above solution (set a fixed axisLabel padding) works for @dchicchon's specific case as their tick labels are a fixed length. I am running into a similar problem, but my tick labels are a variable length. Does Victory include a way to dynamically position the axis labels with respect to the tick labels, or is this left to the user to configure? Unclear what best practice here would be.

for future readers, [`TextSize.approximateTextSize`](https://github.com/FormidableLabs/victory/blob/b44f58d0ad768270485419c24e73468f5ea268a1/packages/victory-core/src/victory-util/textsize.ts#L376) worked well for me.
