### ISSUE TITLE
Functional Styling of VictoryPolarAxis

### ISSUE THREAD

**Issue by ByronBecker** [FormidableLabs/victory#1436]
First off, I would like to thank you for this wonderful library, which has made my life so much 
easier!

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

For polar charts, when a particular scatter data point is at the maximum chart value, it will overlap with the tickLabelComponent's axisLabel. See image below.

<img width="439" alt="Screen Shot 2019-11-06 at 17 30 32" src="https://user-images.githubusercontent.com/17368530/68352490-77fa5400-00bb-11ea-86f5-c2d72df8b5af.png">

If the padding is increased to always account for this case, it's a bit too far away from the other polar axes, and looks slightly awkward.

<img width="415" alt="Screen Shot 2019-11-06 at 18 00 03" src="https://user-images.githubusercontent.com/17368530/68353825-8b0f2300-00bf-11ea-8e34-77d21fdc8654.png">

Ideally, one would be able to individually change the padding in the styling prop for `tickLabels` functionally, having in scope/reference at least the particular axis in question so that the labels can dynamically have more padding assigned if needed. The `dy` and `dx` solution doesn't take into account that one may not know in what order the labels will appear, what position/side of the polar chart the label is on, etc. - padding is a much easier property to update.

### Attempted Solution

For some of the Victory components functional styling is possible, for others it is not. In the documentation for the VictoryPolarAxis component, the tickLabels style props is mentioned as having the following capability:

> The `style` prop defines the style of the component. The style prop should be given as an object with styles defined for `parent`, `axis`, `axisLabel`, `grid`, `ticks`, and `tickLabels`. Any valid svg styles are supported, but `width`, `height`, and `padding` should be specified via props as they determine relative layout for components in VictoryChart. Functional styles may be defined for `grid`, `tick`, and `tickLabel( missing s?)` style properties, and they will be evaluated with the props corresponding to each axis element, such as `tick` and `index`.

So I attempted to mess around with this feature and test it out.

```
<VictoryPolarAxis 
key='dimension axes'
style={{
  tickLabels: ({datum}) => {
    console.log('tickLabel datum', datum)
    return {
      fill: '#2B2C3A',
      fontSize: 12,
      fontFamily: 'Roboto, sans-serif',
      overflow: 'visible',
      padding: 20
    }
  }
  ...
}
```

Upon attempting to use a functional style for the tickLabels, I run into this error

```
VM16768 bundle.js:11287 Warning: Failed prop type: Invalid prop `style.tickLabels` of type `function` supplied to `VictoryAxis`, expected `object`.
    in VictoryAxis (created by VictoryRadar)
    in VictoryRadar (created by ChartTesting)
    in div (created by ChartTesting)
    in div (created by ChartTesting)
    in div (created by ChartTesting)
    in ChartTesting (created by AppContainer)
    in MathJaxProvider (created by AppContainer)
    in AppContainer (created by ConnectFunction)
    in ConnectFunction (created by Application)
    in Provider (created by Application)
    in Application
```

### Help?

My question is then, are there any plans of adding functional styles to the VictoryPolarAxis component or are there any suggestions on how one might accomplish solving this?

**Comment by boygirl** [comment]
@ByronBecker apologies for the delay. What you want to do instead is to use a function for each style attribute like:
```
style={{
  tickLabels: {
      fill: ({ datum }) => datum.y > 0 ? "blue" : "red"
    }
  }}
```
