### ISSUE TITLE
"datum" is undefined when used in VictoryScatter

### ISSUE THREAD

**Issue by borisrev** [FormidableLabs/victory#1438]
# Bugs and Questions

When running the demonstrated code for VictoryScatter and trying to use any properties of datum in the style of the VictoryScatter, I get an error that the datum is undefined. Reproduced in the sandbox.

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@borisrev this is very likely caused by the breaking change in version 33.0.0. You can read about the change and the upgrade path here: https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#3300-2018-08-21
