### ISSUE TITLE
React.StrictMode support? (migrate to new context API)

### ISSUE THREAD

**Issue by djmadeira** [FormidableLabs/victory#1442]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Are there any plans to release a breaking change to Victory which removes support for the legacy context API and other APIs deprecated in Strict Mode? This will be necessary to support the new concurrency features coming to react.

**Comment by boygirl** [comment]
We've already removed all the unsafe lifecycle methods and string refs. This should be the last thing on the list. It may, unfortunately, require a significant overhaul of our animation system, which is why it has been put off.
