### ISSUE TITLE
Brush gets stuck in `isSelecting: true` state

### ISSUE THREAD

**Issue by Hypnosphi** [FormidableLabs/victory#1444]
To reproduce, you should start resizing the brush, then move the mouse out of the chart area really fast and release the mouse. After that, any mouseMove over the chart is handled as brush resize.

It works OK if I revert https://github.com/FormidableLabs/victory/commit/f64e01404229a5b098d30c395953de6104b39464. @chrisbolin @boygirl do you think it's still needed?

The problem is that for some reason fast movement leads to `target` being something other than svg

**Comment by boygirl** [comment]
@Hypnosphi I'm not able to reproduce the behavior you're seeing, or the undesirable resize behavior reported in https://github.com/FormidableLabs/victory/issues/607 after reverting the change you mention. Based on the explanation of the issue reporter and the person who fixed it, I expect the check for `evt.target.nodeName === "svg"` to no longer be needed, as `VictoryContainer` no longer renders nested svgs. I will remove the check.
