### ISSUE TITLE
Can labels be positioned and anchored within a VictoryPie half circle?

### ISSUE THREAD

**Issue by AndresTIY** [FormidableLabs/victory#1445]
# Bugs and Questions

### Checklist

- [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Trying to find a way to position the labels at the end of a half circle when there's only 2 data points. I've been able to move the labels using `VictoryLabel` and setting the dy prop to 150, but if the data changes, the labels will still move. 

**Close to what I was able to do**
<img width="257" alt="Screen Shot 2019-11-23 at 6 32 45 PM" src="https://user-images.githubusercontent.com/25064365/69487927-13135d80-0e20-11ea-97a5-cb6801af7720.png">

**When the data changes, the labels move :( **
<img width="252" alt="Screen Shot 2019-11-23 at 6 36 16 PM" src="https://user-images.githubusercontent.com/25064365/69487939-36d6a380-0e20-11ea-8325-a0a8b11fb785.png">

Here's my data and render method:

```js

// for the first screenshot
  const data = [
    {
      x: 200,
      y: 0.5,
    },
    {
      x: 220,
      y: 0.5,
    },
  ];

//for the second screenshot
  const data = [
    {
      x: 200,
      y: 0.25,
    },
    {
      x: 220,
      y: 0.75,
    },
  ];

//render
<VictoryPie
      labelComponent={<VictoryLabel dy={150} />}
      data={data}
      startAngle={90}
      innerRadius={140}
      colorScale={['grey', 'white']}
      endAngle={-90}
      style={{
        labels: { fontSize: 24, fill: 'white' },
      }}
    />


```

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@AndresTIY VictoryPie has a `labelPosition` prop that takes options `startAngle`, `endAngle` and `centroid`. It sounds like adding the option for this prop to take a function and be evaluated for each label would solve your problem, because then you could set the label for the first slice at the `startAngle` and the second slice at the `endAngle`. This should be a quick change. I can get a patch out for you tomorrow :)

**Comment by AndresTIY** [comment]
Interesting! Yes, I was able to use the those `labelPosition` props but didn't think it'd be possible to only give the first data point `startAngle` and the second one `endAngle`. Thanks for your help!

**Comment by boygirl** [comment]
published as `victory@33.1.4`

**Comment by AndresTIY** [comment]
@boygirl has this also been updated in `victory-native`?

**Comment by boygirl** [comment]
This issue definitely belongs here, because it's not _specific_ to `victory-native`, so thank you for opening it here. `victory-native` uses `^` version ranges for all its `victory-*` dependencies, so you should be able to pick up this patch to `victory-pie` with a fresh npm install. (Might need to clear out your node_modules)

**Comment by norre-daroy** [comment]
@boygirl I used `labelPosition="startAngle"` like you said and it works but it has this problem. 

<img width="512" alt="Screen Shot 2020-02-04 at 11 09 23 PM" src="https://user-images.githubusercontent.com/49046908/73810154-8ed84180-47a3-11ea-9c94-48f667a91b74.png">
