### ISSUE TITLE
Error when trying to load data from array

### ISSUE THREAD

**Issue by Vick206** [FormidableLabs/victory#1449]
My program takes data from a CSV and turns it into an array which is then condensed using papaparse.  my code is provided below. 
####################################################
import React from 'react';
import ReactDOM from 'react-dom';
import { VictoryBar, VictoryChart, VictoryLine, VictoryTheme, VictoryAxis } from 'victory';
import Papa from 'papaparse';
import moment from "moment";
var masterData = []
    function groupAverage(arr, n) {
      var result = [];
      for (var i = 0; i < arr.length;) {
        var sum = 0;
        for(var j = 0; j< n; j++){
          // Check if value is numeric. If not use default value as 0
          sum += +arr[i++] || 0
        }
        result.push(sum/n);
      }
      return result
    }

  
    function reform(data) {
      var i = 0;
      var timeset = [];
      var HR = [];
      var RR = [];
      for(i = 1; i < data.length -1; i++ ){
          timeset.push(data[i][1])
          HR.push(data[i][2])
          RR.push(data[i][4])

      }
      timeset  = (groupAverage(timeset,30));
      HR  = (groupAverage(HR,30));
      RR  = (groupAverage(RR,30));
      
      for(i = 0; i < timeset.length; i++ ){
        timeset[i] = Math.round(timeset[i])
        HR[i] = Math.round(HR[i])
        RR[i] = Math.round(RR[i])
        var hour = Number(moment(timeset[i]).format('h'));
        var minute = Number(moment(timeset[i]).format('m'));

        timeset[i]={ DATE: moment(timeset[i]).format() , HOUR: hour, MINUTE: minute, HeRT: HR[i], ReRT: RR[i]}
    }
    masterData = timeset;
    console.log(masterData)
    return timeset;

        

// Will display time in 10:30:23 format
      
  }
  function parseData(url, callBack) {
      Papa.parse(url, {
          download: true,
          dynamicTyping: true,
          header: false,
          complete: function(results) {
              callBack(results.data);
          }
      });
  }
  
 parseData("https://gist.githubusercontent.com/Vick206/031f7f0fb72ab1dfde6364ddea29de3f/raw/14e2e9f11175705fc306efabe9c687b34ea946ca/data.csv", reform);
class app extends React.Component {
    render() {
     console.log(masterData.toString())

        return (

          <div>
<VictoryChart
  theme={VictoryTheme.material}
>
  <VictoryLine
    style={{
      data: { stroke: "#c43a31" },
      parent: { border: "1px solid #ccc"}
    }}
    data={[masterData]
    }
      x ="HOUR"
      y ="ReRT"
  />
 <VictoryLine
    style={{
      data: { stroke: "#c43a31" },
      parent: { border: "1px solid #ccc"}
    }}
    data={[
      { x: 2, y: 1 },
      { x: 3, y: 4 },
      { x: 4, y: 6 },
      { x: 5, y: 5 },
      { x: 6, y: 8 }
    ]
  }
  />
</VictoryChart>
          </div>
        );
      }
    }
  
  ReactDOM.render(
    <VictoryBar />,
    document.getElementById('root')
);

  export default app;  
####################################################

I get the error "Received NaN for the `y1` attribute. If this is expected, cast the value to a string." when I know for a fact HeRT and HOUR are both numbers from console.log(masterData)

**Comment by boygirl** [comment]
@Vick206 this is a bit tough to diagnose the problem from this information. What is the shape of `masterData`? 
Victory expects an array of objects, so `data={[masterData]}` makes me think that `masterData` might be an object. Is this correct? If so, the problem might be that you're using `VictoryLine` with a single point. 
The best way for me to help you would be for you to create a codesandbox with a small subset of your actual data.

**Comment by Vick206** [comment]
https://codesandbox.io/s/flamboyant-moon-3n4e9?fontsize=14&hidenavigation=1&theme=dark
something like this? it looks like I'm getting the same issue

**Comment by boygirl** [comment]
It looks like you have one extra layer of array. If you change `data={[masterData]}` to `data={masterData}` in your codesandbox I think it will work as expected. I'm going to close this issue, but let me know if you're still having trouble.
