### ISSUE TITLE
Docs on webpack builds with Victory

### ISSUE THREAD

**Issue by knowbody** [FormidableLabs/victory#145]
Write a comprehensive guide of how to build Victory components in your project with webpack the "right" way considering:

* Source Maps
* Overall build composition
* Pointing to `lib/` vs. `src/`
* Dependency management and flattening for things like lodash, React, et.c

This should go in the main victory README.

**Comment by coopy** [comment]
Closing - `npm3` requirement is in docs

**Comment by ryan-roemer** [comment]
@coopy -- This is supposed to be a comprehensive guide of how to build Victory components in your project with webpack the "right" way considering:

* Source Maps
* Overall build composition
* Pointing to `lib/` vs. `src/`
* Dependency management and flattening for things like lodash, React, et.c

Do we have all that already?

**Comment by coopy** [comment]
Ah, I interpreted the issue as just a followup to https://github.com/FormidableLabs/victory/issues/144, which was a `npm2` based issue. Reopening. Thanks for the details!

**Comment by coopy** [comment]
Roll up #146 into this (build from `src/` not `lib/`)

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#24
