### ISSUE TITLE
Cursor container misalignment with createContainer("zoom", "cursor")

### ISSUE THREAD

**Issue by StraightOuttaCrompton** [FormidableLabs/victory#1451]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Cursor "crosshair" is not aligned with cursor when using createContainer("zoom", "cursor")

### Reproduction

Clone [repository](https://github.com/StraightOuttaCrompton/victory-zoom-cursor-container-example/tree/c748ba6b85d987698030c9ac6d1d1f52feb47375) and run the command
```
npm install && npm start
```
Notice that after zooming, the crosshair is not aligned with the cursor.

**Comment by becca-bailey** [comment]
Closing in favor of #2111
