### ISSUE TITLE
Documentation bug in changelog example

### ISSUE THREAD

**Issue by thisconnect** [FormidableLabs/victory#1455]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

in https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#3300-2018-08-21
the example is:
```
labels={({ datum }) => `x: ${d.x}`}
```

but that seems incorrect, the following may be correct:
```
labels={({ datum }) => `x: ${datum.x}`}
```

### Reproduction

the link  posted, but here again https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#3300-2018-08-21

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Let me know if that is correct, if you want I an open a PR.

**Comment by boygirl** [comment]
Thanks for pointing this out! I will correct it.
