### ISSUE TITLE
Define D3 as peer dependency

### ISSUE THREAD

**Issue by cphoover** [FormidableLabs/victory#1456]
I want to use this library but still have access to the underlying d3 library. I think in this sense it makes more sense to have d3-shapes, d3-scale defined as peerDependencies instead of dependency. Also right now it is defined as a `devDependency` for some reason.

While you can download these libraries in your main package and if they are of compatible versions npm should deduplicate them, I still think it makes more sense to have d3 defined as a peerDependency.

**Comment by boygirl** [comment]
@cphoover 

The `d3` devDependencies you see at the root of the  `victory` monorepo are used in testing utilities for the project.  The _actual_ d3 dependencies are defined as real dependencies for each package that requires them. See `packages/victory-core/package.json` for an example. 

We are relying on specific d3 modules, and our use of these is tightly coupled with the library, so we will not be moving them to peerDependencies.
