### ISSUE TITLE
Not able reduce font size of content created from mouse hover of victoryline

### ISSUE THREAD

**Issue by mrafivyr** [FormidableLabs/victory#1457]
Tried generating mouse hover content for victoryline plot using VictoryVoronoiContainer.

**code:**
containerComponent={<VictoryVoronoiContainer labels={({ datum }) => `(x=${datum['prod_date']};y=${datum['row_count']})` }/>} 

Sample image with content from mouse hover on plots.
![image](https://user-images.githubusercontent.com/43163662/70703781-c7edbb80-1cf6-11ea-8b32-e97af953429b.png).

Expected behavior: Reduce the size of font.
![image](https://user-images.githubusercontent.com/43163662/70704564-3bdc9380-1cf8-11ea-9c7b-16009d2a1b14.png)

**Comment by boygirl** [comment]
You can style the labelComponent that `VictoryVoronoiContainer` renders like so:

```
<VictoryVoronoiContainer
   labelComponent={<VictoryTooltip style={{ fontSize: 8 }} flyoutStyle={{ stroke: "red" }} />
/>
```
You might want to take a look at the tooltip docs for more ways to customize: https://formidable.com/open-source/victory/docs/victory-tooltip
