### ISSUE TITLE
Performance issue: Axis eating up lots of CPU time even when domain / range don't change

### ISSUE THREAD

**Issue by toddmedema** [FormidableLabs/victory#1459]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm creating a demanding live updating chart with multiple layers that (hopefully) will be able to run smoothly on mobile. View a demo here (click play - no login required): http://beta.electrifygame.com/

The problem is that the axis are eating up a lot of CPU whenever the data changes, even though the data's domain + range aren't changing every frame. You can see from this performance screenshot that the two axis are taking far more CPU time than the actual graphs, which seems.... undesirable:

![Capture](https://user-images.githubusercontent.com/775657/70877007-c38d0100-1f89-11ea-8279-ef08b61f5f14.PNG)

Running Victory 33.1.4, the source code for my chart is available here: https://github.com/toddmedema/electrify/blob/master/services/app/src/components/base/Chart.tsx

# Feature Requests

My request is to be able to pass the domain and range into the axis (in the same way you pass data to area and line charts) - I'm already computing these values for other pre-rendering calculations, and if the axis just received their domain / range, they'd know that it's not changing even though the rest of the data is.

^^ That being said, ideally I shouldn't even have to do this for the axis to not re-render, the charts should be able to figure it out on their own :)

NOTE: I noticed that there's `minDomain` and `maxDomain` in the docs for axis, but when I tried to use it like so:
```
<VictoryAxis minDomain={rangeMin} maxDomain={rangeMax} />
```

I received the following TypeScript error: 

```
Property 'minDomain' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<VictoryAxis> & Readonly<VictoryAxisProps> & Readonly<...>'.
```

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by toddmedema** [comment]
Could we potentially use something like this on the axis? (And legend, too, because that looks like it's eating up about as much CPU as the graphs too!) https://www.saltycrane.com/blog/2019/03/how-to-usememo-improve-performance-react-table/

**Comment by Timopheym** [comment]
I having the same issue, trying to achieve the same functionality. @toddmedema Did you solve the issue?
How is it expected to optimize performance on rerendering PARTS of the chart? It's one of the reasons I moved from Plotly to Victory, and I definitely want to control it.

**Comment by Timopheym** [comment]
From what I see there is no major update on this https://github.com/toddmedema/electrify/blob/master/services/app/src/components/base/ChartSupplyDemand.tsx#L184 @toddmedema

**Comment by toddmedema** [comment]
Correct, I never solved it (although I haven't worked on that project in a while)
