### ISSUE TITLE
Unexpected VictoryBrushContainer behaviour when aspect ratio is changed

### ISSUE THREAD

**Issue by StraightOuttaCrompton** [FormidableLabs/victory#1460]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have created a chart that changes aspect ratio on browser resize, so that the width changes but the height remains the same. However, there is a problem when using a VictoryBrushContainer where the container seems to not be updated with the new width after resize.

### Reproduction

To reproduce the bug, please refer to the [repository](https://github.com/StraightOuttaCrompton/victory-zoom-resize-example). It contains instructions in the README as well as a video outlining the problem.

**Comment by becca-bailey** [comment]
Closing in favor of #2111
