### ISSUE TITLE
VictoryLegend is messing up time label on X Axis

### ISSUE THREAD

**Issue by BrunoQuaresma** [FormidableLabs/victory#1472]
When I use VictoryLegend component inside of VictoryChart it is messing up the time label on X Axis.

<img width="650" alt="Screen Shot 2020-01-20 at 20 33 48" src="https://user-images.githubusercontent.com/3165839/72763967-d1efbd80-3bc4-11ea-9988-be0ab7c39881.png">

```js
const data = [
  { x: new Date("02/01/2020"), y: 1 },
  { x: new Date("02/02/2020"), y: 2 }
];

<VictoryChart>
      <VictoryBar colorScale="qualitative" data={data} />

      <VictoryLegend
          colorScale="qualitative"
          x={125}
          y={50}
          orientation="horizontal"
          symbolSpacer={5}
          gutter={20}
          data={[{ name: 'first' }, { name: 'second' }]}
      />
</VictoryChart>
```

Codesandbox: https://codesandbox.io/s/basic-victory-example-942kc

**Comment by pramodgupta** [comment]
Add the  scale={ {x: "time"} } prop at the victoryChart and that should fix it.

**Comment by narinluangrath** [comment]
Hi @BrunoQuaresma,

@pramodgupta's suggestion will fix the problem 😄. Thanks!
