### ISSUE TITLE
VictoryLabel does not allow the the customization of ID attr

### ISSUE THREAD

**Issue by gitjeff05** [FormidableLabs/victory#1477]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I recently ran an accessibility audit on a page with _multiple_ Victory charts and found that Victory is generating duplicate id attributes on `<text />` elements created  with `<VictoryAxis />` and `<VictoryLabel />`. It seems that this is in violation of [WCAG 2.1 Guideline 4.1](https://www.w3.org/WAI/WCAG21/quickref/#parsing). 

See Also: [[id] attributes on active, focusable elements are not unique](https://web.dev/duplicate-id-active/).

It seems there is no easy mechanism to customize the id attribute on `VictoryLabel`. I could not find anywhere in the documentation that gave examples on how to do this. Please correct me if I am wrong.

### Reproduction

I was able to reproduce here:

https://codesandbox.io/s/basic-victory-example-77rw3

# Feature Requests

VictoryLabel should -- like it does for the `text` prop -- accept a function as an argument to the `id` property. This way, the users can own the responsibility of ensuring unique id attributes. Alternatively, it could use a more robust generator that would be unlikely to produce duplicates. Another solution might be to allow the user to pass in a string that was prefixed to the id.

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

In the above sandbox, you can try to pass in an `id` prop to `<VictoryLabel />` and it does work, however it will use the same one for each `tickLabelComponent` so they will not be unique.

**Comment by boygirl** [comment]
I agree, allowing the `id` prop on `VictoryLabel` to accept a function would solve this issue.
