### ISSUE TITLE
How to limit the scale for the time?

### ISSUE THREAD

**Issue by andreymyssak** [FormidableLabs/victory#1480]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I need to limit the scaling of time to days, but my zoom scales to hours. 

<img width="559" alt="Screenshot 2020-01-31 at 20 02 56" src="https://user-images.githubusercontent.com/40265277/73646661-176fb880-46a4-11ea-991b-b47a5011c67e.png">

The basis for my example was an example from the gallery on the site (https://formidable.com/open-source/victory/gallery/brush-and-zoom). 

The example on the site (brush-and-zoom) scales up to days because the data shows a long time. If the time span is less, then the zoom will scale up to hours.

### Reproduction

https://codesandbox.io/s/react-victory-zoom-problem-8j63w

**Comment by narinluangrath** [comment]
Hi @andreymyssak, 

One solution is to set a minimum zoom level for the chart so the tick labels never show hours. I forked your reproduction and implemented that solution here: https://codesandbox.io/s/issue-1480-solution-u71ov?file=/src/App.js

If you still want to be able to zoom arbitrarily, you'll need a custom `tickFormat` function that returns `null` for timestamps that contain an hour value, e.g. `tickFormat={time => (new Date(time)).getHours() !== 0 ? null : <something else>}`
