### ISSUE TITLE
Sort order does not work in VictoryCandlestick

### ISSUE THREAD

**Issue by edemen** [FormidableLabs/victory#1482]
### The Problem

I am trying to create a tornado graph using VictoryCandlestick.
The data are passed pre-sorted with longest bars on top.
However, the graph seems to render in ascending or reversed order and sortKey or sortOrder seem to have no effect.

### Reproduction
Very simple way is to put two default candle stick charts, one with `sortOrder="descending"` and one with `sortOrder="ascending"` https://codesandbox.io/s/flamboyant-cerf-sqvyd
They are the same.

```
import React from "react";
import { render } from "react-dom";
import { VictoryChart, VictoryCandlestick } from "victory";

class App extends React.Component {
  render() {
    return (
      <React.Fragment>
        <VictoryChart>
          <VictoryCandlestick sortOrder="ascending" />
        </VictoryChart>
        <VictoryChart>
          <VictoryCandlestick sortOrder="descending" />
        </VictoryChart>
      </React.Fragment>
    );
  }
}

render(<App />, document.getElementById("root"));
```

**Comment by jhumbug** [comment]
Candlestick's sortOrder like the other chart types only works for categorical data such as strings.  The default data that you'd see using the above code uses Date objects which won't be sorted as you expect.  They'll still plot along the axis regardless of sortOrder. For your purposes, just make sure your 'x' axis has strings as its data and they'll go ascending or descending like you want.  You'll need to also include `sortKey="x"` in your props and make sure it stays wrapped in VictoryChart.
