### ISSUE TITLE
Positive bottom Y and positive left X domain padding does not work

### ISSUE THREAD

**Issue by edemen** [FormidableLabs/victory#1484]
### The Problem

Specifying positive bottom domain padding for Y or positive left X does not work
What's interesting is that negative value works! Only positive does not.
Top domain padding for Y and right domain padding for X work fine too (either negative or positive)

### Reproduction
See example
https://codesandbox.io/s/nervous-dust-fpm8b

```
import React from "react";
import { render } from "react-dom";
import { VictoryChart, VictoryCandlestick, VictoryAxis } from "victory";

class App extends React.Component {
  render() {
    return (
      <React.Fragment>
        <VictoryChart
          // Bottom Y POSITIVE padding does NOT work
          // LEFT  X POSITIVE padding does NOT work
          domainPadding={{ x: [50, 0], y: [50, 0] }}

          // Bottom Y NEGATIVE padding however works fine
          // Left X NEGATIVE padding works too
          //  domainPadding={{ x: [-50, 0], y: [-50, 0] }}

          // Top Y padding works fine
          // Right X padding works fine
          // domainPadding={{ x: [0, 50], y: [0, 50] }}
        >
          <VictoryAxis />
          <VictoryAxis dependentAxis />
          <VictoryCandlestick
            data={[
              {
                open: 5.228,
                low: 5.228,
                close: 0.516,
                high: 0.516
              },
              {
                open: 0,
                low: 0,
                close: 0.499,
                high: 0.499
              },
              {
                open: 0.0,
                low: 0.0,
                close: 0.446,
                high: 0.446
              }
            ]}
          />
        </VictoryChart>
      </React.Fragment>
    );
  }
}

render(<App />, document.getElementById("root"));

```

**Comment by edemen** [comment]
I think there is something going on with VictoryChart height.
If I set VictoryChart height to something very big, then the domain padding works starts having a limited effect.
Like, for a height of 360, the positive domain padding would work for up to 15. I don't thing any relation of the domain padding to chart height is documented, so really hoping it is a bug and any domain padding can be used.

**Comment by edemen** [comment]
In this example positive left X padding works, but positive Y bottom padding still does not work
```
<VictoryChart
   domainPadding={{x:[50,50],y:[50,50]}}
>
<VictoryAxis orientation = "left"/>
<VictoryAxis orientation = "right"/>
<VictoryAxis dependentAxis orientation = "top"/>
<VictoryAxis dependentAxis orientation = "bottom"/>
  <VictoryBar />
</VictoryChart>
```
Either there is a bug or a matter of some limitations of domainPadding not being specified in documentation.

**Comment by narinluangrath** [comment]
Hi @edemen, 

Thanks for the question and reproduction! This behavior you are describing is documented [here](https://formidable.com/open-source/victory/docs/common-props/#domainpadding).

> Values supplied for domainPadding will be coerced so that padding a domain will never result in charts including an additional quadrant. For example, if an original domain included only positive values, domainPadding will be coerced so that the resulted padded domain will not include negative values.

You can disable this by setting `singleQuadrantDomainPadding={false}` as described [here](https://formidable.com/open-source/victory/docs/common-props/#singlequadrantdomainpadding)
