### ISSUE TITLE
[Typescript] domainPadding does not exist on VictoryAxis interface

### ISSUE THREAD

**Issue by South-Paw** [FormidableLabs/victory#1487]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

`domainPadding` is [documented](https://formidable.com/open-source/victory/docs/victory-axis/#domainpadding) as being a property of `VictoryAxis` but is [not in the Typescript interface for the component](https://github.com/FormidableLabs/victory/blob/master/packages/victory-axis/src/index.d.ts#L26).

### Reproduction

In a Typescript environment, simply try:

```ts
<VictoryAxis domainPadding={10} />
```

And you'll see the following type error:

![Code_O5E6GwytlZ](https://user-images.githubusercontent.com/2154764/74400839-2d3f6380-4e84-11ea-98bc-61e9e5a45921.png)

**Comment by boygirl** [comment]
fixed in recent versions
