### ISSUE TITLE
VictoryZoomContainer: no pinch to zoom on iOS?

### ISSUE THREAD

**Issue by mcintyre94** [FormidableLabs/victory#1488]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue - may be a dupe of comments on this made after it was closed and not responded to, in 2017: https://github.com/FormidableLabs/victory/issues/434

### The Problem

I'm unable to use pinch to zoom on iOS Safari on any VictoryZoomContainer charts.

### Reproduction

Any of these charts in documentation:

- https://formidable.com/open-source/victory/docs/victory-zoom-container
- https://formidable.com/open-source/victory/guides/brush-and-zoom/
- https://formidable.com/open-source/victory/guides/zoom-on-large-datasets

On all of these, on MacOS (at least in Firefox) a two-finger scroll zooms as expected, but on iOS pinch to zoom does not.

TBH I'm not 100% sure if this should be a feature request or a bug, is pinch-to-zoom supported on iOS?

**Comment by inspmoore** [comment]
Same thing on Android Chrome 84.x.

**Comment by Adam-isdd** [comment]
Same thing on Android Chrome 86.x.

**Comment by mcintyre94** [comment]
Can I ask why this is closed? All 3 examples linked in my issue are still broken on iOS Safari.

**Comment by nes123** [comment]
+1

**Comment by jwh-hutchison** [comment]
+1

**Comment by Aryan-mor** [comment]
+1
