### ISSUE TITLE
Use of d3 scale functions rather than strings like "linear"

### ISSUE THREAD

**Issue by zenithlight** [FormidableLabs/victory#1489]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I want to define a scale function using `d3-scale` and use that as the scale for the y-axis of the graph, instead of using one of the predefined strings (`"linear"`, `"log"`, etc.)

### Reproduction

https://codesandbox.io/s/basic-victory-example-nejef

Expectation: The line is steeper when 40 < y < 60.

Result: Both the graphs look the same.

How can I make use of a scale function?

**Comment by soren-mou-jakobsen** [comment]
See https://formidable.com/open-source/victory/gallery/discontinuous-scale/

**Comment by becca-bailey** [comment]
This is already supported! The documentation that @soren-mou-jakobsen should provide more details.

**Comment by devunt** [comment]
I think this is not supported yet. Victory ignores custom scale's `domain` and `range` properties as seen in original post's codesandbox... @becca-bailey
