### ISSUE TITLE
VictoryArea datum undefined for fill style

### ISSUE THREAD

**Issue by JAgostoni** [FormidableLabs/victory#1491]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I was trying to dynamically set the fill in an area chart to be red when y is negative and green when y is positive. 

Problem: datum is undefined (Cannot read property 'y' of undefined)
Expected behavior: A VictoryArea chart with a red fill for negative y, green fill for positive

[Documentation](https://formidable.com/open-source/victory/docs/victory-area#style) for VictoryArea states it uses the standard style prop.
[Documentation](https://formidable.com/open-source/victory/docs/common-props/#style) for style prop shows the exact example.

### Reproduction
Steps:
- Create a VictoryArea chart with y values which are positive and negative
- Set the fill value based on datum:
- Error: Cannot read property 'y' of undefined

Code:
```
  <VictoryArea
          data={[{ x: -10, y: -4 }, { x: -8, y: 4 }]}
          style={{
            data: {
              fill: ({ datum }) => (datum.y < 0 ? "red" : "green")
            }
          }}
  />
```
Sandbox: https://codesandbox.io/s/victorychart-datum-issue-xk0lc

**Comment by dmitry-cyberdog** [comment]
try to use:
`fill: ({ d }) => (d.datum.y < 0 ? "red" : "green")`

I had the same problem, they apparently reworked the functionality

**Comment by boygirl** [comment]
For VictoryArea, there isn't any `datum` since it renders the entire dataset as a single path element. You do something like `fill: ({ data }) => (data[0].y < 5 ? "red" : "green")` for example.

**Comment by JAgostoni** [comment]
Ok.  That certainly doesn't fix the issue I am having but at least explains why it doesn't work.  

For a workaround, I created a LinearGradient adding Stops when my data cross the axis.  I then set the fill to that gradient as in:

```fill: "url(#myGradient)"```

This gets pretty close.

**Comment by jsleeuw** [comment]
@JAgostoni Thanks for the posting this workaround. I've been finding the occasional issue where my gradient stop point (red -> green) doesn't line up precisely to where the data crosses the axis on the area graph. Did you see this too? Were you able to resolve?

**Comment by JAgostoni** [comment]
Pretty sure mine isn't 100% either. I think I made one color a little biased vs the other to make it aesthetic.
