### ISSUE TITLE
Victory Pie, data renders in reverse of VictoryToolTip order

### ISSUE THREAD

**Issue by abrown945** [FormidableLabs/victory#1492]
My pie renders in the right order data wise, but for some reason the tooltip values are the inverse of what it is supposed to be.

IE:

- biggest chunk of data is created with the largest value, but on hover it displays information for the smallest chunk of data

...

- smallest chunk of data created properly with smallest value, but on hover displays information for the largest chunk of data

Below is my code

```
<DonutContainer>
        <VictoryPie
          containerComponent={
            <VictoryContainer height={200} responsive={false} width={300} />
          }
          height={200}
          width={310}
          innerRadius={25}
          data={data}
          padAngle={3}
          labels={({ datum }) => `${datum.y}: ${datum.x}`}
          labelComponent={
            <VictoryTooltip
              flyoutStyle={{
                fill: "white",
                stroke: "black"
              }}
              style={{
                fontSize: 11,
                fontFamily: "Poppins",
                stroke: "black"
              }}
            />
          }
          style={{
            labels: {
              fontFamily: "Poppins",
              fontSize: 8.5
            }
          }}
        />
      </DonutContainer>
```

**Comment by abrown945** [comment]
This is throughout the entire pie chart to clarify, it is not just the first and last data points that experience this reversal of label issue!

**Comment by narinluangrath** [comment]
Hi @abrown945! 🎉 

I put together [a CodeSandbox][0] with your code (and a guess at what `data`) and couldn't reproduce the issue you described. Please feel free to reopen the issue if you can reproduce it in CodeSandbox.

[0]: https://codesandbox.io/s/issue-1492-edzgu
