### ISSUE TITLE
Infinite looops in TimerContext

### ISSUE THREAD

**Issue by doomsower** [FormidableLabs/victory#1499]
# Bugs and Questions

### Checklist

- [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

This is in fact victory-native issue, but the root of the problem is here in this repo.

While running e2e tests of my react-native application using [detox](https://github.com/wix/Detox) I've noticed that it hangs forever on chart screen.

Turns out that detox doesn't like infinite loops ([link](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#settimeout-and-setinterval)), and `TimerContext` probably creates one via `d3-timer`. ([link](https://github.com/FormidableLabs/victory/blob/master/packages/victory-core/src/victory-util/timer-context.js))

Funny thing that I didn't even mount any chart component in that test, just placeholder. `TimerContext`  was instantiated via module require chain.

I think possible solution is to initialize `transitionTimer` and the other one lazily. This way the infinite loop should not start on require. 

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

**Comment by Grohden** [comment]
Maybe this [PR](https://github.com/FormidableLabs/victory/pull/1738) solved the issue?
