### ISSUE TITLE
Add Greenkeeper.io to all victory components

### ISSUE THREAD

**Issue by knowbody** [FormidableLabs/victory#150]
I've seen someone mentioning similar thing on some other Formidable repo. I think it will be great to add it across all Victory components as we have a few of them and we are likely to have more soon, and this wouldn't need to be manually managed.

Thoughts? cc @boygirl @coopy @exogen @ryan-roemer

**Comment by coopy** [comment]
I feel like we need better test coverage before we add dependency upgrade automation.

**Comment by coopy** [comment]
When ART conversion is done, if it’s not a big effort, I’m fine with trying it out. We do need to test the changes manually though before merging

**Comment by knowbody** [comment]
ok let's do that after tests are in place, I'll keep it open for now. Thanks @coopy for your insight
