### ISSUE TITLE
Not set custom style

### ISSUE THREAD

**Issue by VaishaliUbhada** [FormidableLabs/victory#1500]
I have seted #ccc color but not effect in output.

<VictoryChart
                        width={Constant.screenWidth * 0.8}
                        height={250}
                        style={{
                            parent: {
                                border: "2px solid #ccc",
                                color: 'red',
                            }
                        }}
                        theme={ VictoryTheme.material}
                    >

**Comment by narinluangrath** [comment]
Hi @VaishaliUbhada! Could you reproduce this issue in CodeSandbox? [Here's a template][https://codesandbox.io/s/victorychart-boilerplate-xkcjp] to get you started. Thanks!
