### ISSUE TITLE
Brush and zoom domain issue

### ISSUE THREAD

**Issue by alisd23** [FormidableLabs/victory#1502]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When creating a chart like the [Brush and Zoom](https://formidable.com/open-source/victory/guides/brush-and-zoom/) example, there is a strange bug (also present and reproducible in the example) where the domain of the **brush chart** brush line somehow becomes out of sync and does not match the domain of the **zoom chart** above when zooming/panning.

The strange thing is it only seems to happen when the **zoom chart** is panned to the *edge* of its domain, either all the way to the left or to the right.

### Reproduction

I have also managed to create the most minimal example I could to show the issue here:
https://codesandbox.io/s/victory-js-playground-s0c6k

Reproduction steps (it's a weird one, but this is the easiest way I can reproduce):
1. Adjust the brush line on the **brush chart** so that it is smaller than the width of the brush chart
2. Move the brush line so it is slightly separated from the left axis of the brush chart
3. Pan the **zoom chart** all the way to the left so the brush line is now up against the left axis of the brush chart
4. Once again move the brush line on the **brush chart** so it is separated from the left axis
5. Now again pan the **zoom chart** all the way to the left (as in step 3).
6. You should now see that when as soon as the zoom chart is panned all the way to the edge of the axis, to its minimum domain, the brush line on the brush chart decides to revert to the last position it was moved to in step 4 - making it out of sync with the zoom chart visible domain

Here is a screen capture of the issue reproducing as above:
https://filebin.net/e9k952o7reto389y/victory-bug.mp4?t=3mioiiuv

**Comment by jyshin97** [comment]
Is there any update on this? I'm running into a similar situation where if you decrease the size using the brush and then zoom out the brush and zoom are now out of sync. Can also be replicated in the example brush and zoom.

**Comment by becca-bailey** [comment]
Closing in favor of #2111
