### ISSUE TITLE
Center VictoryBars in the middle of the chart

### ISSUE THREAD

**Issue by hdgone** [FormidableLabs/victory#1506]
# Bugs and Questions

### Checklist

✅ This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

✅ I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

✅ I am using the latest version of Victory

✅ I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

By default, when you add Bars they are centered the way to fill the chart. Is there a way to center them from the middle?
As in my example, I add 2 bars and one is on the left and the other is on the right. How to put both of them in the middle of the chart?
### Reproduction

[Sandbox](https://codesandbox.io/s/basic-victory-example-2cce6)

**Comment by NgoKnows** [comment]
@hdgone you could try using `domainPadding` to somewhat center them. For example `domainPadding={{ x: 250 }}`
