### ISSUE TITLE
Render images as a label for VictoryLine

### ISSUE THREAD

**Issue by aldimirprincipal** [FormidableLabs/victory#1507]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm trying to render an Image as a label for VictoryLine within the labelComponent prop

### Reproduction

```
<VictoryChart width={wpF("83%")} height={hpF("39%")} >
                                <VictoryLine
                                    data={[
                                        { x: "09:00", y: 19.86 },
                                        { x: "12:00", y: 22.15 },
                                        { x: "15:00", y: 20.29 },
                                        { x: "18:00", y: 16.19 },
                                        { x: "21:00", y: 12.45 },
                                      ]}
                                    labels={({ datum }) => datum.y}
                                    labelComponent={ <Image source= 
                                                 {require("../../assets/images/meteo/humedad.png")} /> } 
                                    />
</VictoryChart>
```

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

There's nothing regarding this problem

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Being able to render images on top of a chart, for example this one: 
![image](https://user-images.githubusercontent.com/44405296/78891568-1c683400-7a68-11ea-947d-5b2780254da1.png)

My idea was to put the image just on the top of the max value of the line for every temperature

**Comment by narinluangrath** [comment]
Hi @aldimirprincipal, 

Your code is pretty close, just needs some tweaks to your `labelComponent` prop 😸. Here's an example to get you going: https://codesandbox.io/s/issue-1507-solution-2zmd1

Here's the documentation for more details: https://formidable.com/open-source/victory/docs/common-props/#labelcomponent
