### ISSUE TITLE
sortOrder does not exist on Victorybar

### ISSUE THREAD

**Issue by BrianD91** [FormidableLabs/victory#1509]
### The Problem

I receive an error when I try to use the `sortOrder='descending'` prop on a `<VictoryBar />` component

![image](https://user-images.githubusercontent.com/37163937/79074607-5f6e1580-7cbb-11ea-9e78-0a9e6fbebeff.png)

**Comment by boygirl** [comment]
@BrianD91 Apologies! We're in the middle of auditing and updating our type definitions. This issue should be fixed in the next minor version, which I anticipate releasing this week.
