### ISSUE TITLE
[Docs] Add `npm link` instructions to contribution guide

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#151]
There are some gotchas when you're setting up the dev environment to contribute to the Victory ecosystem. Consider adding a script to help `npm link` clones of victory components.

**Comment by coopy** [comment]
This goes along with https://github.com/FormidableLabs/victory/issues/145

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#20
