### ISSUE TITLE
VictoryHistogram

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#1518]
Histograms in general:

Histograms involve data and a concept of bins / thresholds. The data may come in either one dimension or two dimensions. This data is them processed into more standard x, y format where x refers to the bin, and y refers to either the number of data points in that bin (1D Data) or the cumulative sum of all y data in that bin (2D data). When plotted, histograms greatly resemble bar charts, but histogram bars should be laid out so that there are either 1) no gaps between bars or 2) small, consistent gaps between bars that are stylistic but have no quantative meaning

For Victory:
- `VictoryHistogram` should support both 1D and 2D data, as well as proprocessed x, y data (provided by the user as `_x`, `_y` where _x is the center of the given bin, and _y is the frequency. Similar to how `VictoryBoxplot` checks for preprocessed data: https://github.com/FormidableLabs/victory/blob/master/packages/victory-box-plot/src/helper-methods.js#L7)
- `VictoryHistogram` should support custom bins (as either an array on 2 element arrays or an array of objects like `[{ x0: 0, x1: 2 }, { x0: 2, x1: 4 } ...]`. We will need to perform a check to ensure consecutive and non-overlapping bins.
- If custom bins are not given, VictoryHistogram should take a `binCount` prop, and evenly divide the x domain into that number of bins.
- We probably want to reuse `Bar` for the data component, but getting the layout to have bars touch each other exactly might require some changes.

**Comment by NgoKnows** [comment]
Closed via #1531
