### ISSUE TITLE
Change render order in stacked bar chart

### ISSUE THREAD

**Issue by maks-io** [FormidableLabs/victory#1523]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hi, i want to highlight certain bars in my stacked bar chart, by changing their border color.
This only works for the lowest part of a stacked bar though, because for every other part stacked upon it, i would never see the bottom part of its border:

Lowest part highlighted -> result ok:

![Screenshot from 2020-04-22 17-06-22](https://user-images.githubusercontent.com/48987577/80025875-8c9f9c80-84e1-11ea-9c2a-5caabf88a933.png)

Second-lowest part highlighted -> bottom border not visible:

![Screenshot from 2020-04-22 17-06-39](https://user-images.githubusercontent.com/48987577/80025878-8dd0c980-84e1-11ea-8c2e-9a7839172aef.png)

I guess, to solve this, I could maybe change the render order - if that is possible? Due to this assumption I also chose the corresponding github issue title. But if there's any other way to solve this, please let me know too.

I would really appreciate your help!

Thanks in advance!

**Comment by narinluangrath** [comment]
Hi @maks-io,

Good question! One possible solution is to use a `<VictoryPortal />` to render the middle bar above the rest. Here's an example: https://codesandbox.io/s/issue-1523-solution-khpop?file=/index.js

**Comment by maks-io** [comment]
Hi @narinluangrath ,
thanks for your quick reply - the example is very helpful, however, i cannot get it to work on my side - and i am on the react native side atm.

I tried to more or less copy your example, but i will always end up getting `renderInPortal is not supported outside of VictoryContainer. Component will be rendered in place` warnings.

I tried to manually add `VictoryContainer` components, but that led to other errors. My ultimate goal is to let the end user click on any given bar which would then be highlighted with another border style, just as your example does. I am not really sure how I should deal wich onClick/onPress events for those "currently selected bars", that would use the `dataComponent` prop, as you suggested.

Would it be possible to extend your example a little further - regarding the onClick functionality?
I am currently really not sure if I am dealing with one or two problems here, at the moment.

As already said - without manually adding a `VictoryContainer` I get warnings and not the desired rendering, but **with** adding it, I get other errors, that are maybe (!) connected to onClick events. And in the latter case, I don't know if the rendering problem is solved, because as soon as I click, my app crashes.

Your help would really be appreciated!

**Comment by narinluangrath** [comment]
Hi @maks-io! Hm that is odd. Can you generate a reproduction in a React Native sandbox or create a repo with the reproduction?

**Comment by maks-io** [comment]
Hi @narinluangrath ,
sorry I somehow didn't get a notification that you replied again.
For me it is not relevant anymore, because I ended up doing a workaround (which I also needed due to other reasons) - and to quickly summarize it: I am now stacking multiple charts upon each other. Sounds like a hack, but works like a charm ;)
