### ISSUE TITLE
[Question] Is it possible to have a custom Tooltip without SVG?

### ISSUE THREAD

**Issue by visualcookie** [FormidableLabs/victory#1539]
I'm currently on a project, where I have highly customized Tooltips. I found out custom tooltips are possible in Victory but only with the `VictoryTooltip` element.

Is there any kind of possibility to have a custom element which uses `<div />` elements which are styled using `styled-components`? I found out that `VictoryTooltip` renders an SVG.

What I want to accomplish:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/1857554/80541125-2495fe00-899a-11ea-8958-d548bb7ed29b.png">

**Comment by narinluangrath** [comment]
Hi @visualcookie,

Yep this is possible. I'd recommend using `<VictoryTooltip />` with a custom `flyoutComponent` that renders a `<foreignObject />` with your `<div />`. Here's a [good example](https://github.com/FormidableLabs/victory/issues/445#issuecomment-327953835)
