### ISSUE TITLE
Theme: Typescript error for tooltip's pointerWidth prop 

### ISSUE THREAD

**Issue by zzeni** [FormidableLabs/victory#1540]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

`VictoryThemeDefinition` interface doesn't accept `pointerWidth` property for the tooltip.

The following code:

```ts

export const theme: VictoryThemeDefinition =  {
    ...VictoryTheme.material,
    // for some reason next styles are not auto-applied and
    // therefore need to be manually fed to the component
    tooltip: {
        cornerRadius: 3,
        pointerLength: 7,
        pointerWidth: 15
    }
};
```

errors with:

```
Type '{ cornerRadius: number; pointerLength: number; pointerWidth: number; style: { textAnchor: "start"; fill: string; padding: number; fontFamily: string; fontSize: number; stroke: string; strokeWidth: number; }; }' is not assignable to type '{ style?: CSSProperties | undefined; flyoutStyle?: CSSProperties | undefined; cornerRadius?: number | undefined; pointerLength?: number | undefined; }'.
  Object literal may only specify known properties, and 'pointerWidth' does not exist in type '{ style?: CSSProperties | undefined; flyoutStyle?: CSSProperties | undefined; cornerRadius?: number | undefined; pointerLength?: number | undefined; }'.ts(2322)
index.d.ts(848, 9): The expected type comes from property 'tooltip' which is declared here on type 'VictoryThemeDefinition'
```

However if I cast the object to `VictoryThemeDefinition` (E.g.:

```ts
const theme = { /* ... */ } as VictoryThemeDefinition;
```

), the prop is actually taking effect.

### Reproduction

I have tried to configure typescript on the sample sandbox, but I couldn't make it work: https://codesandbox.io/s/problem-with-prop-yjggw?file=/index.tsx

Please let me know if it's absolutely necessary to provide an example for this problem and I will try to create a git repo for it.

Thanks in advance!

**Comment by boygirl** [comment]
@zzeni Thanks for this issue! We're actually working auditing types across the project right now.

**Comment by zzeni** [comment]
Hi @boygirl , yes I saw those, but I didn't feel right to hijack the already opened MR for the Tooltop.

Thanks!
