### ISSUE TITLE
BrushContainer does not update on brushDomain change

### ISSUE THREAD

**Issue by tomdohnal** [FormidableLabs/victory#1541]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'd like to be able to clear the brushDomain on a button click. To do so, I programmatically set the `brushDomain` to `{x: [0, 0]}`. However, it does not work. If I set it to a different value every time (like `{x: [1, 1]}` or `{x: [2, 2]}`) it does work. 

I've read about `externalEventMutations` and think it's a more appropriate approach in my use-case. 

However, the docs say: (https://formidable.com/open-source/victory/docs/victory-brush-container#brushdomain)

>  When this prop changes, the chart will render with a new highlighted domain.

So according to the docs, it should work like in the attached CodeSandbox. If it's not supposed to work like in the docs, then they should be updated :) (happy to send a PR)

### Reproduction

https://codesandbox.io/s/victory-brush-domain-bug-dkldi?file=/src/App.js

**Comment by NgoKnows** [comment]
So in your case, you are providing an initial prop for `brushDomain`, but as you change the brush domain by interacting with the brush, the prop value provided to `brushDomain` remains the same. So when you are clicking the clear button, you are passing the same prop value to `brushDomain`, and so it doesn't update. If this usage of `brushDomain` did work, and there was a re-render to this component unrelated to any interaction, then it would reset the brush domain every time.

 One option other than external event mutations, could be to treat the VictoryBrushContainer as a controlled component and update the value you pass to `brushDomain` by using the `onBrushDomainChange` prop. See this example (https://formidable.com/open-source/victory/gallery/brush-and-zoom).

**Comment by novascreen** [comment]
This happens even if we try to completely control the `brushDomain` state:

https://codesandbox.io/s/victory-brush-domain-bug-0y227?file=/src/App.js

In this case the domain applied is definitely not the same again.

My current workaround is to use `Math.random` on the `y` as shown in the example

**Comment by becca-bailey** [comment]
Closing in favor of #2111
