### ISSUE TITLE
domain property causing TypeError

### ISSUE THREAD

**Issue by jshaughn** [FormidableLabs/victory#1548]
### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
You can currently see this on the web site examples at:

https://formidable.com/open-source/victory/docs/common-props/#polar

It shows the "TypeError: Array.prototype.map called on null or undefined".  If I use the active editor and remove the domain properties from the example, the error goes away.  I see similar behavior in my project, using victory v34.1.3.

### Reproduction
See above.

**Comment by narinluangrath** [comment]
Hi @jshaughn! Thanks for noticing this. It's an error with the documentation which will be fixed soon.
