### ISSUE TITLE
Second TRY - Cannot zoom in <div><svg>...</svg></div>

### ISSUE THREAD

**Issue by 6axter82** [FormidableLabs/victory#1555]
This is a duplicate issue cause the previous one was closed. And in case of not solving this problem I was asked to open the new issue.

Here is the link to the old one [https://github.com/FormidableLabs/victory/issues/1513#issuecomment-618065673](https://github.com/FormidableLabs/victory/issues/1513#issuecomment-618065673)

# Bugs and Questions

### Checklist

- [ x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x ] I am using the latest version of Victory

- [ x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I can't zoom or do anything on charts when inside an svg tag. I need to use div and svg as I want to calculate the width of the div on changing the window width and give it back to charts. It looks like resizing works if I put the charts into the svg. But than the zoom and brush are not working within the svg. And the placement of charts is misaligned.
Commenting the svg out, brings the placement and allows zoom with brush. But the resizing is gone.

### Reproduction

[https://codesandbox.io/s/floral-field-7ozn0?file=/src/App.js](https://codesandbox.io/s/floral-field-7ozn0?file=/src/App.js)

**Comment by boygirl** [comment]
@6axter82 

As explained in the previous issue, using `standalone={false}` means that `VictoryChart` will only render a g tag, and not an outer svg, which means it will not render its `containerComponent`, so none of the event containers (`VictoryZoomContainer`, `VictoryBrushContainer`) are actually being rendered in your example. 

Here's a working brush and zoom: https://codesandbox.io/s/elegant-firefly-wcvm6

**Comment by 6axter82** [comment]
@boygirl 
I have modified a bit my first example to bring it more to my case:
1. I have an outer div 
2.a sidebar , which changes its width on hover
3. charts area.

you can see that I have problems with resizing the width of the charts while hovering over sidebar area and also when I resize the viewport. The inner part of charts is overshooting the right side.

[https://codesandbox.io/s/xenodochial-driscoll-nx0xi](https://codesandbox.io/s/xenodochial-driscoll-nx0xi)

**Comment by 6axter82** [comment]
@boygirl have you had a chance to look into my modified example?

**Comment by boygirl** [comment]
oh, I see! The issue here is that the `width` that you're getting with `useDimensions` doesn't actually change when the sidebar expand, because nothing is triggering a rerender. With `responsive={false}` on both of your charts, they are using the width you give them as expected.

Since you're using `styled-components`,  what about setting your flex values based on some `sidebarHovered` prop on both `Sidebar` and `ChartDiv` rather than using the hover pseudo selector?
