### ISSUE TITLE
dependency to history.js needed?

### ISSUE THREAD

**Issue by janusch** [FormidableLabs/victory#156]
there is a dependency to `"history": "~1.13.1",` in your package.json
Is this really necessary to have for the victory components?

I have some trouble getting it to work with a different history.js version

**Comment by knowbody** [comment]
@janusch yes, we use it for our docs: https://github.com/FormidableLabs/victory/blob/master/docs/router.jsx#L3

**Comment by dandelany** [comment]
Sounds like it should be a devDependency, then? Library consumers shouldn't need to care about dependencies that are only used for docs - the docs use `react-router` too but that is a devDependency.

**Comment by knowbody** [comment]
thanks @dandelany, fixed in #157

**Comment by dandelany** [comment]
:+1:

**Comment by janusch** [comment]
Thanks for fixing this so fast! Now I am really close to run victory in production. I really appreciate your work!

I worked around it by importing the separated victory components instead, maybe that is the recommended way anyhow? 
I would prefer to keep my node_modules dir as lean as possible, it is already littered with all those dependencies of dependencies that depend on something for I don't know...

Doesn't the router have its own dependency on history anyways?

**Comment by knowbody** [comment]
React Router 2.0 has history as a peer dependency. Once we upgrade we won't need to have history in our devDependencies.

I would recommend: `npm install victory` and then:

```js
import { VictoryAxis, VictoryBar } from 'victory';
```

**Comment by janusch** [comment]
@knowbody yea, I would also go with your recommendation, if it would work. Somehow npm tells me that history@1.3.1 is invalid, maybe that is due to a conflict with another version of history.js

For now I have to import the single components to get around that. I am going to try to import from victory.js again when I have time to upgrade the package. Somehow my graphs always fell apart when I upgraded. For instance from 0.1.0 to 0.1.3 a bunch of things must have changed. I am very happy that I have a working graph at the moment that is build with victory. And the breaking changes are understandable since it is still alpha software.

Thank you for your time and recommendations!

**Comment by knowbody** [comment]
It should be 1.13.1


    _____________________________
