### ISSUE TITLE
BrushContainer doesn't work properly with scale='time'

### ISSUE THREAD

**Issue by Zegoverno** [FormidableLabs/victory#1560]
# Bugs and Questions

### Checklist

- [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by Zegoverno** [comment]
I have a timeserie dataset and I tried to merge the Brush and Zoom example with the Zoom on Large Dataset.

The ZoomContainer works properly. But the BrushContainer returns a domain.x different from the ZoomContainer, the zoomcontainer returns the actual date but the brushcontainer returns the index of the data array, which broke the application.

My solution was to convert the date back to number, takeoff the scale='time' from the brushcontainer and apply the format this number back to date with tickformat.

For now it is working but I lose the nice feature that display from years to weekday when zooming.

**Comment by jimMartin4321** [comment]
I am seeing a similar issue where the domain for my chart no longer auto scales for the x domain (which is timestamps) as it did in 34.1.3 . The domain now scales from 0 to my largest timestamp, which skews all of my data to the far right of the graph. I think it has to do with the update released yesterday. I saw some commits that looked like they were impacting the domain but can't put my finger on which one it was.

**Comment by becca-bailey** [comment]
Closing in favor of #2111
