### ISSUE TITLE
VictoryBar only shows partial label

### ISSUE THREAD

**Issue by flamingofugang** [FormidableLabs/victory#1565]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x] I am using the latest version of Victory

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The labels of VictoryBar can only show partial, given the long text. I have played different height and width of VictoryChart, and textAnchor as "start" or "end"

### Reproduction

<img width="558" alt="Screen Shot 2020-05-10 at 4 01 42 PM" src="https://user-images.githubusercontent.com/4203132/81513368-e6270a00-92dc-11ea-8718-c58b2dfc9e92.png">
<img width="533" alt="Screen Shot 2020-05-10 at 4 40 46 PM" src="https://user-images.githubusercontent.com/4203132/81513393-0ce54080-92dd-11ea-96dc-9fab7e8451d8.png">

**Comment by Genarito** [comment]
I have the same problem! If you found a workaround I'd appreciate it

**Comment by boygirl** [comment]
Apologies for the delay! `VictoryBar` renders with a clipped groupComponent by default to support curtain style animations. You might try replacing the groupComponent like `groupComponent={<g/>}`. You might also try rendering your labels into Victory's portal component like `labelComponent={<VictoryLabel renderInPortal />}`.  Also, be sure whatever container you're rendering your chart into has `overflow: "visible"`. Hope that helps!

**Comment by Genarito** [comment]
Thank you so much! I'll give a try!
