### ISSUE TITLE
VictoryTooltip when using VictoryVoronoiContainer and animation changes the y value rapidly on hover

### ISSUE THREAD

**Issue by pramodgupta** [FormidableLabs/victory#1574]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When i use a VictoryLine with animation set to true and use a VictoryVoronoiContainer to show standard tooltip which shows the y value, the y value keeps on changing by a value of .000000001 and the tooltip keep on flickering with different values. This does not happen when i turn off animation on the Victory Line.

![image](https://user-images.githubusercontent.com/2654798/81981837-7a071780-95f6-11ea-9dee-b6a0874d149e.png)

One other issue is if you hover on the chart when the line is animating, the animation slows down. Not sure if this is a know issue or not.

### Reproduction

You can see the issue in the below [codesandbox](https://codesandbox.io/s/tooltip-with-flickering-issue-g4g3m?file=/src/Components/VictoryLineDemo.tsx)

**Comment by rickyliu93** [comment]
I found the sample problem too, waiting for fixes

**Comment by mohity777** [comment]
Any solutions?

**Comment by pramodgupta** [comment]
I found a temporary workaround for this issue. Instead of adding the label and labelComponent at the VictoryLine, if you add them to the containerComponent at victoryChart, this doesn't seem to happen.

Here is a codesandbox example:
[https://codesandbox.io/s/tooltip-with-flickering-issue-g4g3m?file=/src/Components/VictoryLineDemo.tsx](https://codesandbox.io/s/tooltip-with-flickering-issue-g4g3m?file=/src/Components/VictoryLineDemo.tsx)

**Comment by mohity777** [comment]
Actually i am using labels as well as tooltip  in victory native area chart. So removing label and label component from area chart would remove labels for me. Any other way ? And do you also know how can i control the cutting of labels from end without disturbing the current width of chart.? Image and code is attached for a reference if u know.

<VictoryGroup
        containerComponent={
          <VictoryVoronoiContainer
            labels={({ datum }) => {
              console.log(datum);
              return `x:${datum.x}\ny:${datum.y}`;
            }}
            labelComponent={<VictoryTooltip constrainToVisibleArea />}
          />
        }
        domainPadding={{ y: Fonts.thirty, x: 0 }}
        height={Fonts.twenty5*5.5}
        padding={{ top: Fonts.fifteen, bottom: 0, right: Fonts.twenty*2.1 }}
        style={{ parent: { borderWidth: 1,borderColor:'rgb(180,180,180)',marginTop:Fonts.eight,marginBottom:Fonts.five } }}
      >
        <VictoryArea
          animate={true}
          interpolation="natural"
          data={props.item.data}
          labels={({ datum }) => datum.y}
          style={{ labels: { fill: "blue", fontSize: Fonts.ten,fontFamily: FontType.regular } }}
          labelComponent={
            <VictoryLabel textAnchor="middle" verticalAnchor="middle" />
          }
        ></VictoryArea>
      </VictoryGroup>

https://lh3.googleusercontent.com/-ex0rM8ZuPic/X8UvJUCbrcI/AAAAAAAAA8Q/ZMupW5D-8RI9uNTV1CpC1n20mumLJL_6QCK8BGAsYHg/s0/2020-11-30.jpg

**Comment by pramodgupta** [comment]
It would be easy if you could create a codesandbox or jsfiddle example so that i can play with the code and see if there is any way to fix it.

**Comment by crankeith** [comment]
I'm running into this as well with a combination of VictoryChart/VictoryStack/VictoryBar. If I remove the animation, the flickering stops so it seems to be specific to the animate prop.

**Comment by mikecx** [comment]
Just ran into this issue today myself. Would love a fix here as the animations really make a difference.

**Comment by waltermvp** [comment]
Ran into the same issue we can use the `labels` props and `toFixed(1)` for a  superficial fix:

`labels={({ datum }) => `${(datum.y * 0.01).toFixed(1)}lbs`}`

**Comment by becca-bailey** [comment]
Closing this issue in favor of #2104
