### ISSUE TITLE
Unexpected behavior with Tooltip and VictoryBrushContainer

### ISSUE THREAD

**Issue by elderferreiras** [FormidableLabs/victory#1577]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ ] I am using the latest version of Victory - 
-- I'm using 32.1.0, but noticed it happens with the latest version too.

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I want to highlight a specific area of my chart using the brush container, so I keep track of the selected brush domain and change it depending on the area that was selected in the chart. When I make this selection, though, my tooltips behave weirdly and don't show up for the selected area. If I leave the container with my mouse and come back, then the tooltip shows up normally.

### Reproduction

I was able to reproduce it here: 
https://codesandbox.io/s/happy-wing-nb325

(1) Click in the second scatter.
(2) The area is highlighted.
(3) Move your mouse up and down in the area.
(4) The tooltip for that scatter won't show up.
(5) Leave the container with your mouse.
(6) Enter the chart container again.
(7) Now the tooltip shows up.

This actually seems to be shifting the whole Y axis in my project, which is fixed when the mouse leaves and enters the container, so I was wondering if anyone knows what's going on.

**Comment by becca-bailey** [comment]
Closing in favor of #2111
