### ISSUE TITLE
VictoryLine with animate=true blocks animations on mouse hovers

### ISSUE THREAD

**Issue by no-itsbackpack** [FormidableLabs/victory#1579]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I found a similar report on [spectrum chat](https://spectrum.chat/victory/general/victoryline-with-animate-true-blocks-animations-on-mouse-hovers~5b6e261e-08d0-4086-994d-c9b09fd33eb7) but its 3 months old with no response, the problem has to do with mouse hovers blocking animations for `VictoryLine`. 

### Reproduction

https://codesandbox.io/s/nostalgic-hypatia-c4zwc

Hit refresh and move mouse over graph immediately, animation will block. Hopefully there is a simple workaround for this bug 🙏🏾

**Comment by pramodgupta** [comment]
I'm also facing the same issue. Any workaround would be highly appreciated...

**Comment by pramodgupta** [comment]
Tagging @boygirl to see if there is any workaround (other than turning of animation) for this issue?

**Comment by becca-bailey** [comment]
Hello! Sorry we have been slow responding to some of these animation issues. Historically they have been a challenge to fix, so I'm going to roll some of these issue reports into a ticket for a larger refactor here: #2104
