### ISSUE TITLE
Theme Documentation Isn't Clear, points back to itself.

### ISSUE THREAD

**Issue by vallamost** [FormidableLabs/victory#1593]
# Bugs and Questions

### Checklist

- [X ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X ] I am using the latest version of Victory

- [X ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

Apologies for removing some of the boilerplate issue data targeted for code bugs. But this is an issue for your documentation.

The theme documentation here: [1] https://formidable.com/open-source/victory/docs/victory-theme/

has a link in the text 'Read more about themes here.' which points to: 
[2] https://formidable.com/open-source/victory/guides/themes

which points back to [1] via link on the text 'Check out the VictoryTheme documentation more details on themes..'.

I'm just wanting to find a list of Themes that are provided out of the box :)

PS, hello fellow Seattleites :)

**Comment by NgoKnows** [comment]
Hi @awarmfastbear, https://formidable.com/open-source/victory/guides/themes/ does show the two themes that Victory ships with out the box, do you think explicitly stating that would make things clearer? Or are you looking for something else?

**Comment by awarmfastbear** [comment]
>do you think explicitly stating that would make things clearer?

Yes, I think there should be a definitive list specified of what themes are available to use. In the docs I've seen references to a Warm theme, dark theme, etc.

**Comment by boygirl** [comment]
What about having the docs explicitly point to the source for the themes: https://github.com/FormidableLabs/victory/tree/master/packages/victory-core/src/victory-theme

**Comment by awarmfastbear** [comment]
I think that's still confusing as they're stored in a folder named 'victory-theme; does that mean there's just one theme, the victory-theme? 

Ideally the documentation should auto generate from the themes that are available.
