### ISSUE TITLE
Hiding a pie slice from VictoryPie when empty

### ISSUE THREAD

**Issue by GantMan** [FormidableLabs/victory#1594]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'd like to be able to hide the label for pie slices of weight zero.  In my reproduction for the VictoryPie, you can see "Fearful" is set to zero.   But the label component still is visible.  This is confusing because it looks like it's part of something it's not.

### Reproduction

https://codesandbox.io/s/basic-victory-example-y9iig?file=/index.js

**Comment by GantMan** [comment]
I solved it with a custom label component.  Is this the best way?

https://codesandbox.io/s/basic-victory-example-2-dsw43?file=/index.js

**Comment by NgoKnows** [comment]
You can use the `labels` prop like so, `labels={({ datum }) => (datum.y === 0 ? "" : datum.x)}`

https://codesandbox.io/s/basic-victory-example-6w65b?file=/index.js

**Comment by acharyakavita** [comment]
closing the issue.
