### ISSUE TITLE
upgrading d3-scale to v2.4 is causing error in IE

### ISSUE THREAD

**Issue by vinojv** [FormidableLabs/victory#1595]
https://github.com/FormidableLabs/victory/blob/7df06ba06f94fd9b332cf79b4f2b5cf6f9a9e354/packages/victory-histogram/package.json#L22

upgrading d3-scale to v2.4 is causing an error in IE in the following code
`SCRIPT1004: Expected ';'`

```
/***/ "./node_modules/d3-array/src/count.js":

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return count; });
function count(values, valueof) {
  let count = 0;
  if (valueof === undefined) {
->    for (let value of values) {
      if (value != null && (value = +value) >= value) {
        ++count;
      }
    }
```

**Comment by Fil** [comment]
you mean d3-array@2

please see https://github.com/d3/d3-array/releases/tag/v2.0.0

**Comment by pancr9** [comment]
Seeing same issue.

**Comment by becca-bailey** [comment]
We have had some issues with upgrading our d3 packages. In the current version of Victory, `d3-scale` is pinned at `^1.00` to avoid this issue. This should be resolved for now, but I opened up another issue (#2124) to look into this dependency issue a little further before upgrading this package again.
