### ISSUE TITLE
Custom Components don't scale to size when using VictoryZoomContainer

### ISSUE THREAD

**Issue by saussayjesica** [FormidableLabs/victory#1597]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I want my custom component to scale when i use VictoryZoomContainer. When i zoom in on the chart, the customComponent doesn't change in size. I want it to grow bigger as you zoom in more.
I came up with a fix using onZoomDomainChange to calculate pixels per tick value every time you zoom but this creates a lot of rerenders because i need to save this value to state. 
Is there a better way to do this?

### Reproduction
Example of chart with custom component not scaling to size
https://codesandbox.io/s/nameless-field-l8q22

This is the hack I made so that the custom component scales as the user zooms in
https://codesandbox.io/s/dreamy-lewin-48cm3?file=/src/App.js:962-980

**Comment by boygirl** [comment]
@saussayjesica the `scale` with correct `domain` is passed with props to each `dataComponent` that renders. You could do something like adjust the size of each point based on the domain. For example:

```
class CatPoint extends React.Component {
  render() {
    const { x, y, datum, scale } = this.props;
    const xDomain = scale.x.domain();
    const xExtent = Math.abs(xDomain[1] - xDomain[0]);
    const fontSize = 20 / xExtent;
    const cat = datum._y >= 0 ? "😻" : "😹";
    return (
      <text x={x} y={y} style={{ fontSize }}>
        {cat}
      </text>
    );
  }
}
```
