### ISSUE TITLE
style.tickLabels propTypes in VictoryAxis should accept an array

### ISSUE THREAD

**Issue by madmed88** [FormidableLabs/victory#1598]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

I have a chart axis with multiple lines for each tick and different styles for each line.
I am getting this prop validation error although everything is working fine:
```
Warning: Failed prop type: Invalid prop `style.tickLabels` of type `array` supplied to `VictoryAxis`, expected `object`
```

**Comment by boygirl** [comment]
That error is correct. `style.tickLabels` should be given as an object. To style individual ticks, you can use functions to alter what each tick style ends up as like `style={{ tickLabels: { fill: ({ tick }) => tick === 3 ? "red" : "blue" } }}` for example.

**Comment by madmed88** [comment]
@boygirl I am not trying to style individual ticks. I am styling individual TSpans of the same tick. As I said it is working for me it's just the error is annoying.
VictoryLabel style can be an array, so tickLabels can be an array too.

**Comment by boygirl** [comment]
Ah, I see. I'll change the prop type
