### ISSUE TITLE
I landed on this nifty little repo with nothing in it but a few thoughts jotted down in an MD file and I like it

### ISSUE THREAD

**Issue by mcanthony** [FormidableLabs/victory#16]
So I think perhaps maybe I would like to be involved in this project. But I think maybe also that I don't know SH about D3's nuts and bolts.

Perhaps someone can hold my hand as I ask some silly questions and pose some silly prollems.

One thing I think I know about what makes D3 special is that it is meticulously designed to deal with a ton of interlinking data and any associations that come along with it, and what I have heard on the street is they utilize the DOM to accomplish this with amazing efficiency. This is said to be achieved because the DOM is structurally perfectly suited for this task.

That said, I intuit that the nature of deeply nested data structures that the DOM is so suited for, can be replaced with a plain old JS built data structure that models the desired DOM behaviors without all the cruft that comes along with it.

As I understand it, the above mentioned model has already been implemented in what is called the "Virtual DOM" which react employs in order to accomplish the very same goal. Do we (you) already know for fact that the VDOM encompasses everything necessary to implement D3's DOM dependent functionality? I assume so...

1.) If this is so, how difficult would it be to adapt D3's infrastructure to utilize the VDOM in the same way it would the DOM? I assume (probably incorrectly) that this wouldn't be such a big deal per se.

2.) I assume from the bits I read in DESIGN.MD that this project intends to keep SVG as the core rendering technology. If so, does SVG not also utilize the DOM, which would make cutting the DOM out an impossibility?

Perhaps I misunderstood and SVG is not the intended rendering tech for this proj. Please clarify this point so I don't continue down a train of thought which is misguided (and useless to all).

I would be very intrigued by a project that cuts out the DOM and is render agnostic. Leaving the option open for those who need/want to use SVG.

3.) Do most browsers utilize hardware acceleration in the SVG render chain?

Of the ~25,000 or so projects I have reviewed over the past couple years, I have not run into many as capable or performant as D3. I actually only recall one project that seemed to encompass the core of what D3 accomplishes, and if I recall correctly it was render agnostic and modular. I can't seem to remember the name of it at the moment, but I will hunt it down and get back to you on that. It seemed very robust, and the rendering was definitely much higher in performance than what I have experienced with similar D3 charts. The author of this charting library was a very young (early 20's) MIT student (I think) - he had a definite focus on performance and provided a detailed benchmark comparison of all the top charting libs providing similar functionality.

**Comment by boygirl** [comment]
Hi there!  This project is in it's very early formative stages.  We are actually having a steering meeting this very week, and better docs on this repo will be forthcoming. We hope to break the functionality of d3 into a lot of modular components, and add our own twists (nicer api, sensible defaults, yada yada).  Once we figure out guidelines for all that we would love help churning out components.  Keep an eye out!  Also, answers to your questions about SVG etc will come in the form of a much more polished README.  Probably by Monday.  Thanks!
