### ISSUE TITLE
Striped Background

### ISSUE THREAD

**Issue by akexinad** [FormidableLabs/victory#1601]
## Feature Request

Is there any way to have a striped background like the one below:

![image](https://user-images.githubusercontent.com/44803303/83476908-386edb80-a4d5-11ea-8539-27593862c100.png)

The closest thing I found in the docs was this:
https://formidable.com/open-source/victory/docs/victory-chart#backgroundcomponent

My sincere apologies in advance if I missed anything in the docs..

**Comment by boygirl** [comment]
@akexinad indeed, this could be accomplished with backgrounds for `VictoryChart`. You can read about those in a bit more detail here: https://formidable.com/open-source/victory/docs/new#backgrounds-for-victorychart

You could also do something like this with a custom `gridComponent` on `VictoryAxis`, but you would need to do a bit of work to get the grids to line up with each other. 

I'm going to close this issue, and I don't think this will become a built in option for Victory, but let me know if you're not able to implement it with one of the strategies mentioned above.

**Comment by hibearpanda** [comment]
Hey @boygirl I am currently trying to implement this.

As you suggested, I have tried adding vertical stripes to a VictoryBar chart using the background component. However, the biggest difficulty I have with using the background component is making the stripes align perfectly with each tick / grid spacing.

Do you have any advice regarding how to align the background rect's / patterns with the x-axis spacing?

**Comment by manentai** [comment]
I have this same issue here, is there an example to study and have a better picture on how to solve this problem? Thanks!

**Comment by BhargaviAnnadevara-MSFT** [comment]
Any workaround to this issue? Will be good to have a straightforward way to add a striped background to a VcitoryChart. :(
