### ISSUE TITLE
Accessibility: Screenreader to announce contents of charts and usability bug with aria-title

### ISSUE THREAD

**Issue by christiemolloy** [FormidableLabs/victory#1606]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

We are currently using Victory Charts in our project (PatternFly)[www.patternfly.org]. We have come across some Accessibility issues. As our library wraps the Victory Chart library, we are not able to directly edit the current accessibility that is set on the svg chart.

**1) Victory's accessible title prop is causing usability issues:**
a) When passing through `ariaTitle` and `ariaDesc` props to the Chart, a <title> and <description> prop are rendered in the DOM which is causing usability issues because when hovering over the chart the title tag will display in front of the chart.

<img width="507" alt="Screen Shot 2020-06-09 at 2 09 44 PM" src="https://user-images.githubusercontent.com/20118816/84184212-f60c4800-aa5a-11ea-9986-87c019dcf591.png">

**2) It is not possible for a screen-reader to announce the content inside of the chart**
Because `role="img"` is set on the chart `<svg>`, we have no way to override this. That means that we aren’t able to announce any of the content inside of the chart. To fix this issue in the mean time we added an html table which is visually hidden from the user but is read by the screenreader. 

**Solution:** We would like to submit a pull request so that developers using Victory can pass through a role to the svg to override `role="img"`, e.g.`role="table"` or `role="list"`, which will allow us to read the data from the chart, by further adding roles to the children inside (we have tested this method and it works).

**Comment by boygirl** [comment]
These features are released in `victory@35.2.0`. Let me know if anything is missing!
