### ISSUE TITLE
Zoom on Large Datasets with Voronoi tooltips

### ISSUE THREAD

**Issue by soapnrope** [FormidableLabs/victory#1614]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I made up and example based on https://formidable.com/open-source/victory/guides/zoom-on-large-datasets together with VictoryZoomVoronoiContainer. 

When I hover over the scatter line the tooltips will show up. Now when I zoom the chart, tooltip that was visible before will disappear or appear in wrong place on the chart.

Tooltips goes back to normal only when you re-enter the container with mouse. 

### Reproduction

Can be seen in https://codesandbox.io/s/quizzical-hodgkin-0ot7k?file=/src/index.js

Steps:
1. Mouse over the chart line until Tooltip will show up
2. Zoom in/out - Tooltips should stop showing up unless you leave/re-enter chart container.

**Comment by laban211** [comment]
I'm experiencing a similar issue using VictoryZoomVoronoiContainer, but more severe. My tooltip always has an offset to the right-up. Have you been able to solve your issue?

**Comment by rahdi** [comment]
Hmm, I don't experience this issue with your codesandbox. However, I've got exactly the same problem as you describe. Here is a link for my chart: https://codesandbox.io/s/blissful-thompson-srm6s

**Comment by soapnrope** [comment]
> I'm experiencing a similar issue using VictoryZoomVoronoiContainer, but more severe. My tooltip always has an offset to the right-up. Have you been able to solve your issue?

I have since moved to  different lib called uPlot. Better overall performance by miles.

**Comment by becca-bailey** [comment]
This is related to #655
