### ISSUE TITLE
Victory Chart with Victory single single point keeps on flickering and changes position

### ISSUE THREAD

**Issue by pramodgupta** [FormidableLabs/victory#1615]
# Bugs and Questions

### Checklist

- [x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When a victory chart has only single data point for victory line or victory scatter, the point keeps on flickering and moves around the chart. This doesn't happen when you add the second point.

Can anyone provide a workaround or a fix for this?

### Reproduction

Here is an example
https://codesandbox.io/s/single-point-flickering-076ox?file=/src/Components/VictoryLineDemo.tsx

**Comment by laurenmbeatty** [comment]
I'm looking into something similar. Seems like removing the animate property gets around the issue.
