### ISSUE TITLE
flickering tick values

### ISSUE THREAD

**Issue by iwan-uschka** [FormidableLabs/victory#1629]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through all the relevant [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Have you ever experienced "flickering" tick values?

Please have a look at http://creativytool.com/public/bar-chart.mp4. A very short video containing a bar chart with an animation. You will see changing values inside the tick value labels during animation.

### Reproduction

I am using `<VictoryAxis>` without any custom `tickFormat`:

```
<VictoryAxis
  dependentAxis
  domain={yAxisDomain}
  ...
/>
```

I was able to fix the issue by setting `tickFormat={Math.round(d)}` or `tickFormat={d3_format.formatPrefix('.1', yAxisDomain[1])}`.

While debugging using `console.log(d)` inside the `tickFormat` function i recognised different values returned by `d` for the same date:

```
140
280
420
560
140.00000000000003
280.00000000000006
420
560.0000000000001
140
280
420
560
140
```

If needed, i will provide a codepen.

**Comment by boygirl** [comment]
@iwan-uschka this is expected behavior when animating if your labels are based on the values of your data. the data itself will be interpolated throughout the animation. Your workaround of rounding your label values is the correct solution as well.

**Comment by iwan-uschka** [comment]
Ok. Thanks!
