### ISSUE TITLE
Contributing wiki instructions not working

### ISSUE THREAD

**Issue by munnygupta7** [FormidableLabs/victory#1642]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hi.. I really like this library and i'm interested in contributing to the library. I followed the instructions mentioned in the contributing [wiki](https://github.com/FormidableLabs/victory/blob/main/CONTRIBUTING.md) but it is failing when i run yarn start. I also tried yarn start-ts and it is also failing. 

Here is the error that i'm getting 

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.
![image](https://user-images.githubusercontent.com/56319691/87446551-0ade7d00-c5bf-11ea-9a04-4d68d69d539b.png)

Similar error shows up for the demo/ts as well. I tried making some changes to the webpack.config loaders to see if that fixes the issue but had no success.

Am i missing something? It might be something small that i might be missing. Can you help me fix this issue?

Thanks
munny

**Comment by boygirl** [comment]
Hi there! It may be that your dependencies are incorrect or that the project level babel config is somehow being overridden. You might try cloning down the repo fresh, and doing a fresh `yarn install`. If you're still seeing the issue then, maybe you could let me know what versions of node and yarn you're using and I will try to reproduce it with those particular versions.

**Comment by munnygupta7** [comment]
I just cloned a fresh repo with the node - 12.18.2 and yarn 1.22.4 and still getting the same error. This is happening only for the demo files. Babel is able to compile all the files under the package folder. I tried this in a fresh VM just to make sure there aren't any global install's that might be creating this issue.

**Comment by boygirl** [comment]
Very odd. I've tried a fresh clone and yarn install with your exact node and yarn versions and all is still working as expected. I'll keep digging, but I'm not sure what's going wrong.

**Comment by munnygupta7** [comment]
That is weird. FYI.. the bash console doesn't stop at the above error.. Right after the error it starts to compile the files from each package and it shows the success message. So the error message goes out of the screen. The demo page at localhost:3000 simply shows the "loading..." message and doesn't do anything else.

**Comment by munnygupta7** [comment]
@boygirl I created a fresh VM on Azure and installed yarn, node and checked out the code and tried running the project. Still getting the same error. 

I have sent the login credentials for the VM on spectrum chat. When you are free please take a look at it.
