### ISSUE TITLE
VictoryLabel's backgroundStyle functional styles are not provided current props for evaluation

### ISSUE THREAD

**Issue by chacestew** [FormidableLabs/victory#1646]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When providing a `backgroundStyle` prop to `VictoryLabel`, the functional styles are not being passed props for evaluation.

### Reproduction

This sandbox shows the problem: https://codesandbox.io/s/basic-victory-example-eck0o?file=/index.js

Open console to see that `undefined` is returned when logging the argument provided to the `fill` functional style.

### Cause

I believe this is due to the following code:

https://github.com/FormidableLabs/victory/blob/cc9b9b217d1ed78e76e1bf6d0a8a444c6e45f52b/packages/victory-core/src/victory-label/victory-label.js#L77-L80

On line 79, `props` are missing as the second argument to `Helpers.evaluateStyle`.

### Fix

If you agree with my findings, I would be happy to create a PR altering this one line.

**Comment by boygirl** [comment]
@chacestew Good catch! Your solution is correct, and a PR would be very welcome. Thank you!
