### ISSUE TITLE
Turn on hot reloading for all components

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#165]
## Overview

This is needed:

* Split out a `<Demo/>` component and just have `demo/app.jsx` render it. For hot reloading to work, the rendered component must be exported from a separate module. Thanks @dandelany for pointing out this better way! See https://github.com/FormidableLabs/victory-chart/pull/84 for an example.
* Remove `<script src="http://localhost:3000/webpack-dev-server.js"></script>` from all components `demo/index.html`
* Do all the above for `victory-component-boilerplate` as well

## Subtask list

- [x] victory-component-boilerplate
- [x] victory
- [x] victory-animation
- [x] victory-axis
- [x] victory-bar
- [x] victory-chart: https://github.com/FormidableLabs/victory-chart/pull/84
- [x] victory-label
- [x] victory-line
- [x] victory-pie
- [x] victory-scatter

**Comment by knowbody** [comment]
@coopy wasn't sure what you wanted to be done in `victory-util` and `builder-victory-component` but all of the others are updated.

**Comment by coopy** [comment]
@knowbody Thank you for all the PRs!

**Comment by coopy** [comment]
Nothing to be done in `victory-util` - that was a mistake. And I meant `victory-component-boilerplate`. PR here: https://github.com/FormidableLabs/victory-component-boilerplate/pull/22
