### ISSUE TITLE
[TypeScript] VictoryCursorContainer cursorLabel has not datum interface

### ISSUE THREAD

**Issue by terrierscript** [FormidableLabs/victory#1653]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I found typescript maybe error like those code.

```
<VictoryCursorContainer
      cursorLabel={(data) => {
        const val = data.datum.x    
      // Error: Property 'datum' does not exist on type 'CoordinatesPropType 
       ....
```

[CoordinatesPropType ](https://github.com/FormidableLabs/victory/blob/a2067b3cdb27a64314a1951d21e79bcde028c0dd/packages/victory-core/src/index.d.ts#L112-L115) has only x and y. 
In [this implementation](https://github.com/FormidableLabs/victory/blob/7bddb8a92db69f2aac44f01e7d522b1f3625cbe8/packages/victory-cursor-container/src/victory-cursor-container.js#L133-L139), it's need 
It's may need `datum` props,

**Comment by shakti97** [comment]
@boygirl I would like to work on this issue

**Comment by Wesleyzxc** [comment]
I've had a play with editable source on the docs and realise that there's actually more to it than just `datum`. I'm not exactly familiar with it yet but is it safe to add all of those props under `CoordinatesPropType`?
![image](https://user-images.githubusercontent.com/36616095/127819073-ebdc1965-f047-4e43-a978-21d6800eb389.png)

This is the snippet of code I ran:
```
<VictoryScatter
  containerComponent={
    <VictoryCursorContainer
      cursorDimension="x"
      cursorLabel={data => 
      {
      console.log(data);
      return `${round(data.datum.x, 2)}, ${round(data.datum.y, 2)}`}}
    />
  }
/>
```

**Comment by Wesleyzxc** [comment]
Checking back, this seems to be solved by https://github.com/FormidableLabs/victory/pull/1739.

**Comment by limpep** [comment]
issue still seems to exist on
  "victory": "^36.2.0",
"typescript": "^4.5.3",
![image](https://user-images.githubusercontent.com/2228477/145885302-fd46062e-c7c2-40e9-a212-c8c2a8bcdbca.png)

![image](https://user-images.githubusercontent.com/2228477/145885362-caf9f522-b469-41b3-a061-c4d56a6bef61.png)

**Comment by joeleonard212** [comment]
Hi, any update on this ? I'm facing the same issue
