### ISSUE TITLE
Invalid prop type ouiaSafe

### ISSUE THREAD

**Issue by patricknick** [FormidableLabs/victory#1656]
### The Problem

The prop type of ouiaSafe is invalid. According to the doc, it should be `PropTypes.bool`:
https://github.com/FormidableLabs/victory/blob/453f2bb537c6fbcc85c45cd4b98c50ad1f37f8a1/packages/victory-core/src/victory-container/victory-container.js#L24 

This results in a warning in Dev mode:
![image](https://user-images.githubusercontent.com/25477019/88930123-55c4e980-d27b-11ea-95c2-3f125c0ceb92.png)

Related to this PR: #1654 

### Reproduction
You should see this when you start your project with a victory chart inside.

### Versions
victory: 35.0.7

**Comment by corasan** [comment]
I'm getting the same thing
