### ISSUE TITLE
Use archetype DEVELOPMENT.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#166]
* Remove `DEVELOPMENT.md` from all victory components, and link to the archetype file where appropriate.
* Remove `CONTRIBUTING.md` from all victory components, and link to the archetype file where appropriate.

### Subtask list
- [x] Add `CONTRIBUTING.md` to archetype
- [x] victory
- [x] victory-animation
- [x] victory-axis
- [x] victory-bar
- [x] victory-chart
- [x] victory-component-boilerplate
- [x] victory-label
- [x] victory-line
- [x] victory-pie
- [x] victory-scatter
- [x] victory-util

**Comment by ryan-roemer** [comment]
For reference, https://github.com/FormidableLabs/builder-react-component/blob/master/DEVELOPMENT.md

**Comment by knowbody** [comment]
@coopy all done, please check it out one more time and close the issue if all is good :)

**Comment by coopy** [comment]
Many thanks, @knowbody! If you have any ideas how to make many-repo-changes like this less painful, please let me know.
