### ISSUE TITLE
Victory Chart not drawing strokes in the negative axis for a valid data set in React

### ISSUE THREAD

**Issue by rahulrsingh09** [FormidableLabs/victory#1665]
I am creating a horizontal bar chart using Victory that may get negative value and for that scenario i need the chart to draw on the -ve x axis .

some thing like below ---

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/I6GFY.png

But currently i am using version 33.0.5 and when I try with that version i see none of the bar charts draw in horizontal -ve x axis . Only when i degrade the version lower than 32.0.0 i get the charts draw on the -ve axis. Is there no way to achieve this in version 33.0.5 ? or any higher version . If yes what am i missing.. 

I tried doing in this [sandbox](https://codesandbox.io/s/victory-bar-chart-demo-forked-4ilv4?fontsize=14&hidenavigation=1&theme=dark), currently the dependency for victory is set at 32.0.0 in which we will see the -ve x axis is not draw try lowering it below that and you will see the math has -ve x axis value too .

**Comment by boygirl** [comment]
@rahulrsingh09 apologies for the delay. I've forked your sandbox and made some simplifications. Can you explain what isn't working as you would expect in this version?

https://codesandbox.io/s/issue-1665-f4g68

**Comment by Th0rgal** [comment]
Hey, I have a similar issue.
