### ISSUE TITLE
VictoryHistogram - Negative bin thresholds produce an error

### ISSUE THREAD

**Issue by svmah** [FormidableLabs/victory#1666]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When rendering a VictoryHistogram with either:

- no `bins` prop and a domain that includes negative values (ie. -10 to +10)
- a `bins` prop with negative numbers in the threshold array (ie [-10, 0, 10])

the graph will render properly, but a console error is produced:  `Warning: Failed prop type: Invalid prop 'bins' supplied to 'VictoryHistogram'.`

We suspect the issue starts [here](https://github.com/FormidableLabs/victory/blob/ec6ebc9642a9ba4adc1e82c683d078ffaf98b66f/packages/victory-histogram/src/victory-histogram.js#L55) 

### Reproduction

[Code Sandbox](https://codesandbox.io/s/basic-victory-example-forked-go079)

**Comment by boygirl** [comment]
@svmah Thank you! I am in the process of making some improvements to `VictoryHistogram`, I will include this fix as well. Look for it in the next major version.
