### ISSUE TITLE
VictoryLine does not rerender on data update

### ISSUE THREAD

**Issue by olaven** [FormidableLabs/victory#1667]
Hi! Thanks for maintaining this library! 
Please let me know if I should add more details to this issue. 

Have a nice day 🌻 

# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I am rendering `VictoryLines` based on coordinates fetched from a server. 
My React component rerenders, but the lines do not appear on the chart. 

### Reproduction
[Reproduction here](https://codesandbox.io/s/basic-victory-example-forked-q8552?file=/index.js:0-52)

**Comment by olaven** [comment]
# Update 
This seems to be related to having child components, not to the async fetching. 
[updated reproduction](https://codesandbox.io/s/basic-victory-example-forked-3ljzy?file=/index.js)

Should it be possible to have Victory-elements as children, as I am doing?

Again, let me know if more details/explanation is needed! 😄

**Comment by sglza** [comment]
In case you haven't been able to fix it, I made it work by wrapping VictoryLine with VictoryChart right from the return statement on line 17, like this:

```
const Lines = () => {
  const coordinates = [
    {
      x: 0,
      y: 3
    },
    {
      x: 0,
      y: 1
    }
  ];
  console.log("Rendering with coordinates: ", coordinates);
  return coordinates.length === 0 ? null : <VictoryChart><VictoryLine data={coordinates} /></VictoryChart>
  ;
};

class App extends React.Component {
  render() {
    return (
        <Lines />
    );
  }
}
```

Best of luck!

**Comment by olaven** [comment]
@sglza Thanks for the response! I made it work by simply not having it in a child component. 
But having it in a child component is preferable, so I'll have a look at your suggestion! 

Assuming I can close, as you found a solution 😄 

Thanks 👍
