### ISSUE TITLE
Upgrade to Radium 0.16

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#167]
This upgrade is a breaking change, and before we release a new version of the `builder-victory-component` archetype, we need to update all victory components that use either media queries or keyframes to use `<StyleRoot>`. 

Note that we _have to release_ `builder-victory-archetype` `v 0.1.0` before merging any of the below listed PRs.

See https://github.com/FormidableLabs/radium/blob/master/docs/guides/upgrade-v0.16.x.md#v016x-upgrade-guide

@boygirl: Can you compile a list of such components below? I'll start by adding all victory repos, and you can remove unaffected ones. Maybe this is just relevant to `victory` and `victory-animation`?

### Affected Components

- [x] victory: https://github.com/FormidableLabs/victory/pull/169

**Comment by boygirl** [comment]
@coopy I think this is an issue on in all repos in `docs/docs.jsx`. Does that sound right?

**Comment by coopy** [comment]
Closed via https://github.com/FormidableLabs/victory/pull/169/files
