### ISSUE TITLE
Custom labels (components) on VictoryPie

### ISSUE THREAD

**Issue by ugrdursun** [FormidableLabs/victory#1670]
Hello, I really like this library, fast, clean and useful.

What i need is;

On VictoryPie , I have Emoji component and want to use it as label according to my data's .emoji object (so datum needed). But Victory only excepting string as labels.

I need something like this:

```
                                            labelComponent={({datum}) =>
                                                <Emoji
                                                  name={datum.emoji}
                                                />
                                              }
```

Of course its not working.. Couldnt find a way to do this even with VictoryLabel.

 Do you have an idea or shortcut to do this ?

My Whole VictoryPie:

```
<VictoryPie
    height={300}
    data={data}
    colorScale={["#DC7633","#5DADE2", "#48C9B0", "#F4D03F", "#DC7633", "#A569BD" ]}
                                            x='name'
                                            y='amount_chart'
                                            innerRadius={50}
                                            radius={({ datum }) => 90 + datum.amount_chart * 0.01 }
                                            labels={({datum}) => datum.name}
/>
```

**Comment by sglza** [comment]
This displays an emoji as the label of their respective section. Is that what you are looking for?
```
<VictoryPie
  data={[
    { x: "😻", y: 35 },
    { x: "🐶", y: 40 },
    { x: "🐦", y: 55 }
  ]}
/>
```

**Comment by boygirl** [comment]
@ugrdursun this example might help you:
https://formidable.com/open-source/victory/guides/custom-components#creating-new-components

it's for dataCompoments, but you should be able to adapt it for your labels
