### ISSUE TITLE
Feature Request: VictoryPie color transitions

### ISSUE THREAD

**Issue by sglza** [FormidableLabs/victory#1672]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

It would be nice if transitions could be applied to the colors of the VictoryPie component. This is something that is already implemented for VictoryScatter as shown in the [animations guide](https://formidable.com/open-source/victory/guides/animations). It's a very minor thing, but would make a great addition.

**Comment by boygirl** [comment]
@sglza this is already possible in VictoryPie. You should be able to adapt the example you give, and see the colors transition in VictoryPie the same way.
