### ISSUE TITLE
Question about the possibility of implementation

### ISSUE THREAD

**Issue by apequa-alan** [FormidableLabs/victory#1674]
Friends
Do you think it is possible to implement the following interface for victory?
Now the problem with the selection of the area for example

<img width="481" alt="Снимок экрана 2020-08-27 в 10 00 45" src="https://user-images.githubusercontent.com/70209802/91408671-e11aa600-e84c-11ea-917f-2eb4c802eb19.png">

**Comment by boygirl** [comment]
Yes, this should be possible, but it will require custom components for the bar backgrounds. I'm not sure exactly what is intended, but an interactive selection is possible with `VictorySelectionContainer`. Annotated regions can be added as custom children for `VictoryChart`, or as `VictoryArea` children.

**Comment by apequa-alan** [comment]
How about the **VictoryBrushContainer** component?
It seems that there is the necessary functionality
