### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by stefan-werner-ais** [FormidableLabs/victory#1676]
Hello

Short question why is your main Release 33.x but you have also release tags with version 35.x? Why is that how it is? 

Kind regards

Stefan

**Comment by boygirl** [comment]
Apologies. The step to create a tag and publish a version is an automated one. The step to create a release based on a tag and copy over my release notes from my changelog is a manual one. The reliable source of truth for this project is the changelog. I'll take a moment to update the releases.
