### ISSUE TITLE
Animation not working for VictoryScatter

### ISSUE THREAD

**Issue by sarah-vanderlaan** [FormidableLabs/victory#1678]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Animation is not working on VictoryScatter.  The points load instantly and pay no attention to the provided animate property.

### Reproduction

https://codesandbox.io/s/cold-cdn-jtz1j?file=/src/App.js

```
      <VictoryChart
        theme={VictoryTheme.material}
        domain={{ x: [0, 5], y: [0, 7] }}
      >
        <VictoryScatter
          animate={{
            duration: 5000,
            onLoad: { duration: 3000 }
          }}
          style={{ data: { fill: "#c43a31" } }}
          size={7}
          data={[
            { x: 1, y: 2 },
            { x: 2, y: 3 },
            { x: 3, y: 5 },
            { x: 4, y: 4 },
            { x: 5, y: 7 }
          ]}
        />
      </VictoryChart>
```

**Comment by ItayElgazar** [comment]
BUMP

**Comment by boygirl** [comment]
Apologies for the delay. To improve performance, we're no longer picking up styles from `datum` automatically. Try adding explicit opacity styling based on datum, and setting explicit `before` and `after` functions for your `onLoad` animation. Here's an example:

https://codesandbox.io/s/blissful-wind-gzxk4?file=/src/App.js
