### ISSUE TITLE
VictoryCursorContainer stops registering cursor when moved between charts

### ISSUE THREAD

**Issue by Alexander-AJ-Berman** [FormidableLabs/victory#1680]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Mousing quickly between charts that have a `VictoryCursorContainer` causes some of the containers to stop tracking the cursor (not firing `onCursorChange` event). 

This looks relatively similar to #1276 but wasn't fixed as part of the MR associated with that issue.

### Reproduction

To reproduce this issue, render multiple charts with cursor containers and move between them. 

https://codesandbox.io/s/cursorcontainer-not-registering-1nlf5?file=/index.js has a setup to demo this, and here's a short gif of the behavior in which the cursor line stops appearing after mousing between charts:
![cursorcontainer](https://user-images.githubusercontent.com/29256184/92494939-4ca53180-f1c4-11ea-9f1e-3af648f12d32.gif)

**Comment by Codesleuth** [comment]
I am also having this issue. The behaviour changes when using both zoom and cursor containers.

![chart-cursor-issue](https://user-images.githubusercontent.com/5011956/95874280-a28f6b00-0d68-11eb-9cac-6a1b216b7dcb.gif)

https://codesandbox.io/s/victory-zoom-cursor-issue-s3veg?file=/src/Chart.tsx

Moving the user's cursor over the charts independently (giving the chart state enough time to finish and render) avoids the issue. But, move your cursor left to right and you can immediately see that the cursor seems to disappear. It's not actually gone - it's just at the wrong position. If you're lucky enough, you can still see it (as in my gif above).

**Comment by Alexander-AJ-Berman** [comment]
Fixed in the merge above

**Comment by ifranke** [comment]
I still had this problem in 36.4.0 with React 17/18. I solved this by tweaking a full reload like this

```
const [enterId, setEnterId] = useState(uuidv4());
  const onEnterHandler = useEventCallback(() => {
    setEnterId(uuidv4())
  });
```

and

```
...
<div onClick={onClickHandler} onMouseEnter={onEnterHandler} className="h-100 w-100">
      <VictoryChart
        id={enterId}
...
```
