### ISSUE TITLE
Victory Native: chart not showing Y axis's first label

### ISSUE THREAD

**Issue by rajscet** [FormidableLabs/victory#1683]
[<VictoryChart
                padding={{left: 75, top: 50, right: 50, bottom: 50}}
                width={Dimensions.get('window').width}
                theme={VictoryTheme.material}>
                <VictoryBar
                  style={{
                    data: {fill: colors.barColor, border: 0},
                    axis: {stroke: 'transparent'},
                    ticks: {stroke: 'transparent'},
                    tickLabels: {fill: 'transparent'},
                  }}
                  data={profitFlowResponse.data.values}
                  x="displayName"
                  y="income"
                />
                <VictoryAxis
                  dependentAxis
                  tickValues={Math.max(
                    profitFlowResponse.data.values.map((item) => item.income),
                  )}
                  domain={{
                    y: [
                      0,
                      Math.ceil(
                        Math.max(
                          ...profitFlowResponse.data.values.map(
                            (item) => item.income,
                          ),
                        ),
                      ),
                    ],
                  }}
                  tickFormat={(t) => `${currency.symbol}${nFormatter(t, 2)}`}
                  style={{
                    grid: {stroke: colors.invoiceDivider, strokeWidth: 0.5},
                    axis: {stroke: 'none'},
                  }}
                />
                <VictoryAxis
                  fixLabelOverlap={true}
                  style={{
                    tickLabels: {
                      angle: -45,
                      padding: moderateScale(16),
                    },
                    grid: {strokeWidth: 0},
                    axis: {stroke: 'none'},
                  }}
                  tickValues={profitFlowResponse.data.values.map(
                    (item) => item.displayName,
                  )}
                />
              </VictoryChart>

](url)
![Capture](https://user-images.githubusercontent.com/6961313/93894644-96d1fb00-fd0c-11ea-86bf-7026f2b87417.PNG)

**Comment by boygirl** [comment]
Hi there! By default, `VictoryChart` will filter origin ticks from the axes it plots to avoid awkward looking charts like this:
<img width="342" alt="Screen Shot 2020-09-23 at 11 08 43 AM" src="https://user-images.githubusercontent.com/3719995/94052000-346d0f00-fd8d-11ea-8326-8356a754956f.png">

You can change this behavior using the `crossAxis` prop on `VictoryAxis`. Add `crossAxis={false}` to the axis component that you want to render the origin tick. Here's more information on that prop: https://formidable.com/open-source/victory/docs/victory-axis#crossaxis
