### ISSUE TITLE
VictoryZoomVoronoiContainer tooltip offset bug

### ISSUE THREAD

**Issue by laban211** [FormidableLabs/victory#1686]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When I use `createContainer` to combine Zoom and Voroni I get a wierd offset on my tooltip, it's always offset to the upper-right. The issue only appears when I use a callback in my custom container > `onActivated`. If I use a normal `VictoryVoronoiContainer` the bug doesen't appear. The expected behavior should be the same as in a normal `VictoryVoronoiContainer`

### Reproduction

[Code Sandbox](https://codesandbox.io/s/victoryzoomvoronicontainer-voroni-offset-bug-gweg4?file=/src/GraphComp.jsx). The line that causes it can be found in the file `GraphComp.jsx` at line 23.

**Comment by laban211** [comment]
Hi! 
Is there any progress on this issue, or does anyone know any workarounds?

**Comment by Codesleuth** [comment]
I think this may be related to #1660. There's some issue with the scale function, which causes different issues in both but seems to have the same cause.

**Comment by laban211** [comment]
@Codesleuth The issues looks similar indeed. I've noticed that using a normal variable instead of a React.state solves the main bug. Have you managed to find any other workarounds?

**Comment by Codesleuth** [comment]
It seems to me that it's a problem with setting state that causes a re-render. The scale function appears to be re-created at every re-render (which makes sense, as it would be needed every time zooming happens) but this appears to cause some internal state issues when zooming is then used to feed back into the charts.

I've tried a lot of things without any success. I have to use state updates to get what I need. Even deferring the state updates by setting an object value and then queuing a timeout to go set the state ends up causing the same issue again. The root of the issue looks like state updates + zooming. It all goes away without zoom.

**Comment by laban211** [comment]
I've come to the conclusion that I'll also need to use a state to solve my problems. I guess this counts as a bug then?

**Comment by becca-bailey** [comment]
Closing in favor of #2111
