### ISSUE TITLE
Need to fill the gap between two line charts in certain condition

### ISSUE THREAD

**Issue by t4dek** [FormidableLabs/victory#1695]
Hey guys! 

First of all, thanks for the library, it is really awesome and super extensible, I am loving how the docs and guides are created!

I have a certain feature, and I more than sure that it can be achieved using your library, but I struggle to make it on my own after going through all the issues in repo, docs and guides. 
So I may need a bit of guidance here.

Here is the code:

https://codesandbox.io/s/sharp-johnson-o92o7?file=/index.js

What we have:

1. Blue line chart representing 'benchmark' data. So it is essentially the ideal state to which user need to compare his data.
2. Red line is actual users data.

Whenever Red Line is above the blue I need to fill the gap between red and blue line with red color. And only in the case when Red line is above the Blue one, if red is underneath the blue I do not need the filling.

Like so (it is only a screenshot with my drawing on it :) ):

<img width="658" alt="Screenshot 2020-09-29 at 15 52 45" src="https://user-images.githubusercontent.com/9040160/94560971-0e9fa880-026c-11eb-849f-6df0e376332a.png">

I though about having 2-3  Area charts overlapping each other to mimic this behaviour but it seems like a workaround.
Hope there is a working solution within your library API.

Thanks in advance!

**Comment by boygirl** [comment]
Hi @t4dek I'm glad you're enjoying Victory! I thought about the chart you're trying to create, and I think the easiest way to do it is using two overlapping area charts as you recommend. You can take advantage of rendering order to hide some parts of the red area. I made a quick example:

https://codesandbox.io/s/area-fill-64fxi

I'm going to close this issue, but let me know if that solution doesn't work for you.

**Comment by t4dek** [comment]
Wow, thanks a lot for the flawless response! I will give it a try within my application, and thanks for the code example :) 

Wish you the best, but keep in mind that I may bother you with some more in near future :)

**Comment by t4dek** [comment]
@boygirl I tried your solution and it kinda worked :)

But the thing is that I have negative values on my chart, and it produces strange behavior.
I updated code:

https://codesandbox.io/s/sharp-johnson-o92o7?file=/index.js

Would really appreciate if you can suggest something to make it work, if there is a solution :) 

Thanks in advance!

**Comment by t4dek** [comment]
And btw. On my example with negative values there is no '0' point in tick values. 
I saw you comment to some other issue, that I need to set crossAxis but it did not help :(

**Comment by boygirl** [comment]
Hi @t4dek 

`VictoryArea` charts default to a zero baseline. You can change the baseline (`y0` value) for the area with the white background so that it wipes out the pink area on the negative side of your chart too. Also, the `crossAxis` value should be `false` if you want to show the zero tick. It's a confusingly named prop, for sure. It's a prop that is usually set by `VictoryChart` on its axis children. The idea is that if the axis crosses, the tick shouldn't show up. Anyway, apologies for the confusion. Here's an updated sandbox with those changes for your reference:

https://codesandbox.io/s/fast-lake-tvog9?file=/index.js

**Comment by t4dek** [comment]
@boygirl Thank's, you just made my day 💯
