### ISSUE TITLE
react version, createContext

### ISSUE THREAD

**Issue by acthp** [FormidableLabs/victory#1699]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

README.md says this works with react 15 and up, but it has createContext calls which fail in react 15. Needs updated docs to show usage in react 15, or update to say it only works with 16, or createContext calls should be removed. Or, I suppose, revise your decision to not support accurate peer dependencies.

**Comment by boygirl** [comment]
Readme updated! Thank you for this issue.
