### ISSUE TITLE
Add npm scripts for builder commands

### ISSUE THREAD

**Issue by mxstbr** [FormidableLabs/victory#170]
In the `CONTRIBUTING.md` you mention running `builder run dev` to run the dev env, and `builder run check` to run tests.

I have never worked with builder before, and don't have it globally installed. Trying those commands gave me a `builder: command not found` error.

It'd be nice to have npm scripts that run those builder commands, since npm scripts [link the `.node_modules/.bin` folder to the PATH](http://blog.mxstbr.com/2016/01/npm-scripts/) one can use the `builder` command in there without having to install builder globally. (And you install it as a dependency via npm anyway, so it's in there)

EDIT: This wasn't a big problem for me, as I knew what to do, but this is high-priority in my opinion. A beginner that might have never worked with the command line before will be massively confused by this.

**Comment by ryan-roemer** [comment]
@mxstbr -- We're trying hard to avoid global installs, particularly while there's a huge amount of churn on `builder`. Also, one of the main points of `builder` is that we have 10+ repos that we don't want to keep copy and pasting the same commands and maintaining multiple copies of the same `scripts` fields.

Can you read over https://github.com/FormidableLabs/builder#local-install and see if that gives you enough to "get going" and then perhaps @coopy @boygirl we can add that straight to the README / CONTRIBUTING so there's more help initially?

**Comment by mxstbr** [comment]
After a quick flyover, I'm sure I could follow that guide and I'd be fine, but that's not very beginner friendly. *(Wtf is `PATH`, how can I do that on Windows, how do I even open the terminal, ugh)*

In the React world especially there is a huge amount of assumed knowledge and tooling, and I think making bigger-scale OSS projects like victory easier to help with for beginners would be very beneficial for the entire ecosystem. (Who knows, we might scare of the next Dan Abramov, Michael Jackson, Ryan Florence,...)

I understand that maintaining the `scripts` across that many repos would be a pain, I understand if you don't want to care about absolute newcomers, and nobody can force you to, but I think it'd help quite a bit.

**Comment by knowbody** [comment]
@mxstbr great feedback! might sending PR with suggested changes that you think would be *beginner friendly*?

**Comment by mxstbr** [comment]
I'm not entirely sure how to solve this problem to be honest.

What about having a npm module that is runnable with a single `script` in the `package.json` (something like `npm run victory -- --test`) which points to a `#!/usr/bin/env node` script file in the node_modules folder which will then take care of running the correct commands? (in this example the testing suite)

When a new script is added, a new, minor version of the module is released and the scripts stay in sync across the repos.

**Comment by knowbody** [comment]
this is the problem that is being solved by builder, it's a really good tool. Once you learn more about it, you will understand why we built (rely on) it. 

I do agree with the globals and we will do definitely something about it :)

**Comment by boygirl** [comment]
@mxstbr I'm sorry you ran into issues. The goal of builder is to make working on and consuming victory very easy and beginner friendly indeed by hiding a lot of the complexity in the archetype. (and also to make our lives a lot easier when it comes to maintaining dozens of similar repos). `builder run dev` and other commands are meant to just work after you clone down and `npm install` a repo. All the path manipulating and other annoyance should be a problem for archetype authors not victory developers / consumers. That's the goal anyway, but the project is very young, so there are some snags. The problem you've encountered is unexpected though. Can you give a repro? We definitely want that fixed.

**Comment by mxstbr** [comment]
@knowbody I see, I'll take a deeper look then!

@boygirl I didn't do anything special, I `git cloned` the victory repo, ran `npm install` and tried to run a `builder` command...

**Comment by knowbody** [comment]
Now that we have #73 merged (thanks @ryan-roemer), we should update our docs on victory. so let's leave this open until the docs are changed accordingly.

@boygirl if the builder is not installed globally that's the error you would get

**Comment by exogen** [comment]
@mxstbr If you don't wanna update your `PATH` (totally understandable), can you try just replacing `builder` with `node_modules/.bin/builder` in any of those commands?

e.g. `node_modules/.bin/builder run dev`

This is how you'd run any `bin` script from npm without updating your `PATH`.

**Comment by mxstbr** [comment]
@exogen I'm almost certain that'd work, the question isn't  that I have a problem, it's more that others might run into this problem and maybe there's a way to mitigate it.

What about this having an npm command that does nothing but running builder, i.e. in your package.json:

```JSON
"scripts": {
    "builder": "node_modules/.bin/builder"
}
```

And then you could replace `builder run dev` with `npm run builder -- run dev` (the `--` passes the arguments to the script being called) without having to do any PATH trickery or weird folder prefixes. That's one script field you maintain across all repos, and beginners don't have to worry about anything more complicated.

<sub>In this example I'd think about renaming (or even removing) the `builder run` command to something else, but that's nitpickery</sub>

**Comment by ryan-roemer** [comment]
@mxstbr -- The hard part is that builder _also_ support ` -- ` so there are going to be parsing ambiguities / likely conflicts between npm and builder.

@mxstbr @boygirl @knowbody @exogen -- I have a "paste-ready" snippet for documentation for anywhere we reference `builder` in a doc to help educate developers in the wonders of local install bliss (for `builder` at least) https://gist.github.com/ryan-roemer/cb7e8696cad1144275d4

**Comment by knowbody** [comment]
added the note with the code snippet to the [CONTRIBUTING](https://github.com/FormidableLabs/victory/blob/master/CONTRIBUTING.md#developers-guide) so closing for now.

**Comment by coopy** [comment]
Reopening – I want to at least add an `npm start` script that runs `builder run hot`.

`npm test` is more problematic because of internal overloading of scripts.
