### ISSUE TITLE
Proper use of the domain

### ISSUE THREAD

**Issue by apequa-alan** [FormidableLabs/victory#1713]
# Bugs and Questions

### Checklist

- [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ ] I am using the latest version of Victory

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

I need to scale candles on a chart in the way shown in the image
![ui-maket](https://user-images.githubusercontent.com/70209802/95560589-28867b80-0a22-11eb-84b3-54e1040954ba.png)

At the moment, the chart looks like this

![real](https://user-images.githubusercontent.com/70209802/95560902-9468e400-0a22-11eb-8d6b-53c50956ff22.png)

**Comment by apequa-alan** [comment]
I would be grateful for any suggestions :)

**Comment by boygirl** [comment]
@apequa-alan I think you're looking for the `minDomain` prop:  `https://formidable.com/open-source/victory/docs/common-props/#mindomain`.  I'm going to close this issue, but let me know if that doesn't help.
