### ISSUE TITLE
Axis not updating after panning VictoryZoomContainer

### ISSUE THREAD

**Issue by the-kwisatz-haderach** [FormidableLabs/victory#1717]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ ] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using the VictoryZoomContainer to allow horisontal panning, my y-axis is not updating when I switch data sets **after panning the chart**. If I don't try to pan the chart sideways, there's no problem.

### Reproduction

Sandbox: https://codesandbox.io/s/admiring-davinci-2o1nd

If you swap the data after page load you'll see everything works fine. Then try panning the chart and then swapping data. The axis doesn't change.

I'm not using the latest version of Victory Charts but you can see that the problem is still there in v. 35.3.0. The latest version also seems to introduce some strange visuals when panning the chart, and also doesn't update the chart on the initial "data swap" clicks in the sandbox, but those are different matters since I'm not running the latest code in production anyway.

The production app allows users to view multiple groups of data, even if I didn't add this to the sandbox. Hence the data structue and use of VictoryGroup components.

Thanks for an awesome library!

**Comment by the-kwisatz-haderach** [comment]
The problem seems to be related to the zoomDomain which stops updating after panning. Current workaround is to force a remount by generating a random key every time data changes and assigning as key prop for the VictoryChart component. Probably not very performant.

**Comment by boygirl** [comment]
I'm guessing the issue is related to setting the child domain in `VictoryZoomContainer`. It may have to do with the `cachedDomain`, or with incorrect logic about what to do when `allowZoom` is false as in the example given.

https://github.com/FormidableLabs/victory/blob/main/packages/victory-zoom-container/src/victory-zoom-container.js#L171

**Comment by the-kwisatz-haderach** [comment]
I did some crude testing on a fork and concluded the same. I think the logic for `!allowZoom && allowPan`, resulting in the child domain being used, is missing.

**Comment by michaelg9** [comment]
I believe this is the same issue as this:
https://github.com/FormidableLabs/victory/issues/775
I'm also stuck on this
