### ISSUE TITLE
How to Position Chart Below Title and Legend

### ISSUE THREAD

**Issue by s2t2** [FormidableLabs/victory#1718]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm successfully positioning a VictoryLabel (as a chart title) and VictoryLegend via x and y attributes.
I need to position a VictoryBar (or any chart) to appear below the legend, but right now the chart isn't positionable and overlaps the title and legend so they aren't viewable. 

One confusing aspect of the framework is the chart's x and y attributes refer to the chart data instead of the chart position. 

Is there a styling technique I am missing? How can I achieve chart positioning? Thanks.

### Reproduction

```js

// render ...

<VictoryChart 
    padding={ left: 175, top: 15, right: 50, bottom: 130 } 
    domainPadding={ x: [10,0] } 
>

    <VictoryLabel text="Chart Title"
        x={225} y={10}
        textAnchor="middle"
    />

    <VictoryLegend
        height={15}
        orientation="horizontal"
        data={[
            { name: "Pro-This (0%)", symbol: { fill: colorScale(0.15), type: "circle" } },
            { name: "Pro-That (100%)",     symbol: { fill: colorScale(0.85), type: "circle"} },
        ]}
        x={200}
        y={20}
        style={{
            title: {fontSize: 10},
            data: {fontSize: 10},
            labels: {fontSize: 10},
        }}
    />

    <VictoryBar horizontal
        data={data} x="column1" y="column2"
        animate={true}
        barRatio={0.87}
        labels={({ datum }) => datum["scorePct"]}
        style={{
            data: {
                fill: ({ datum }) => colorScale(datum["column3"]),
            },
            labels: {
                fontSize: 10,
                padding:2
            }
        }}
    />
    <VictoryAxis/>
    <VictoryAxis dependentAxis
        //tickFormat={formatBigNumber}
        label="My Axis Count"
        style={{
            axisLabel: {fontSize: 10, padding:25},
            ticks: {stroke: "grey", size: 4},
            tickLabels: {fontSize: 10, padding:5}
        }}
    />
</VictoryChart>
```

**Comment by mcchong** [comment]
Having the reverse issue with trying to position a rectangle box using domain coordinates rather than pixel coords e.g to highlight the range from y0-y1 with a border.  As a workaround using a VictoryArea with VictoryLines as borders.  In order to position the lines, I need to position by pixel coords (x val), and data coords (y val).

**Comment by mcchong** [comment]
So hacked something together using a custom component and the scale property.

**Comment by boygirl** [comment]
Apologies for the delay. @mcchong has the right approach using the `scale` prop that `VictoryChart` supplied to all of its children. You might also look into the `padding` prop to create the space you need to render the legend above the chart
