### ISSUE TITLE
Charts are getting squished to the left starting with v35.3.0

### ISSUE THREAD

**Issue by jleider** [FormidableLabs/victory#1719]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

With the latest version of victory v35.3.0, some charts get squished to the left while others do not. Unfortunately, I am not able to reproduce this at the moment in a minimal way using codesandbox.io.

We are using the following modules though:
-   VictoryArea,
-   VictoryAxis,
-   VictoryBar,
-   VictoryChart,
-   VictoryLabel,
-   VictoryPortal,
-   VictoryTooltip

v35.2.0
![image](https://user-images.githubusercontent.com/38108/96289857-baa6fa80-0fb3-11eb-8ada-8c4149ae9c70.png)

v35.3.0
![image](https://user-images.githubusercontent.com/38108/96289768-977c4b00-0fb3-11eb-9508-59fd39be68b7.png)

**Comment by cafesanu** [comment]
Same here after trying to upgrade to 35.3.0. After clicking the graph it re-renders correctly

**With V35.2.0**
<img width="734" alt="Screen Shot 2020-10-19 at 10 00 08 AM" src="https://user-images.githubusercontent.com/4213098/96461045-e8798280-11f1-11eb-9ed6-0d353d78c4ac.png">
**With V35.3.0**
<img width="728" alt="Screen Shot 2020-10-19 at 10 00 01 AM" src="https://user-images.githubusercontent.com/4213098/96461048-e9121900-11f1-11eb-9805-bba970a0a7a1.png">

**On V35.3.0. Rendering correctly after clicking the graph**
![](http://g.recordit.co/BOzoXTO7d4.gif)

**Comment by boygirl** [comment]
@jleider and @cafesanu thank you for this issue, and apologies for the regression! I'm not seeing this locally. Any information you can provide to help me reproduce it would be greatly appreciated. 

1) Are your charts animating, and does the issue persist if animation is disabled?
2) Do your charts use events or any of the evented containers like `VictoryVoronoiContainer`?
3) Both of your examples use time scale charts. Does this issue persist with non time series data?

**Comment by boygirl** [comment]
@jleider @cafesanu I've made a codesandbox example that looks similar to your examples above, but is working as expected. Can you tell me how it differs from yours?

https://codesandbox.io/s/vigorous-elion-fckf6?file=/index.js

**Comment by jleider** [comment]
I tried making a scaled down version of our graph in the sandbox that had the issue but I was unable to reproduce the behavior: https://codesandbox.io/s/red-rgb-q8x6q?file=/index.js

One thing I can think of is that the graph is displayed within a `react-responsive-carousel`. This issue is affecting 2 of 3 of our graphs, all three are time based so I would guess its something other than the time scale.

**Comment by cafesanu** [comment]
@boygirl I was able to simplify my example and reproduce it! Basically, in my case, the width of the chart is dynamic. So for this simple example, I just built a simple useEffect that changes the width via `setState`. I you take a look at the console.log in line 42, you can see that the last width is correctly `600`, but the chart does not resize.

https://codesandbox.io/s/zen-mountain-kdmmm?file=/index.js

**Comment by cafesanu** [comment]
Forgot to mention... if you hover over the chart, then it successfully rerenders.

Hope this helps!
