### ISSUE TITLE
VictoryArea overflow labels be covered

### ISSUE THREAD

**Issue by AlexJeeee** [FormidableLabs/victory#1725]
# Bugs and Questions

### Checklist

- [√ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [√ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [√ ] I am using the latest version of Victory

- [√ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

the labels of VictoryArea is being covered, but I use the same code in [https://formidable.com/open-source/victory/docs/victory-area](url), it shows well
```
<VictoryChart
                        height={220}
                      >
                        <VictoryArea
                          data={lastScoresValue}
                          labels={({ datum }) => datum.y}
                          style={{data: {fill: "#f6471c", fillOpacity: 0.1, stroke: "#e2231a", strokeWidth: 2}}}
                        />
                        <VictoryAxis
                          style={{
                            axis: {stroke: "none"},
                            tickLabels: {stroke: "#666",fontSize: 11}
                          }}
                        />
                      </VictoryChart>
```
what it should be:
![image](https://user-images.githubusercontent.com/37064647/97415851-aadacf00-1940-11eb-8c64-8ec3dbbe557f.png)

what my app looks like
![area](https://user-images.githubusercontent.com/37064647/97415550-5afc0800-1940-11eb-9f6d-f2a6d1fb3ca2.jpeg)

any ideas?

**Comment by boygirl** [comment]
@AlexJeeee `VictoryArea` uses a clipped group to render so that it can animate in with a curtaining effect. This is causing the labels to be cut off. If you don't need the entrance animation you can change the `groupComponent` on `VictoryArea` to a plain `<G />` tag. Labels are normally rendered in `VictoryPortal`, but it looks like that isn't happening for you. It may be that there is an issue in `victory-native` with the portal.

**Comment by AlexJeeee** [comment]
> @AlexJeeee `VictoryArea` uses a clipped group to render so that it can animate in with a curtaining effect. This is causing the labels to be cut off. If you don't need the entrance animation you can change the `groupComponent` on `VictoryArea` to a plain `<G />` tag. Labels are normally rendered in `VictoryPortal`, but it looks like that isn't happening for you. It may be that there is an issue in `victory-native` with the portal.

thx for the comment, I change the value of clipPadding in `VictoryClipContainer`, and the label shows up. Thanks a lot ~
