### ISSUE TITLE
Mouse events are captured by VictorySelectionContainer

### ISSUE THREAD

**Issue by Quanyails** [FormidableLabs/victory#1727]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

If a `VictoryChart` uses `VictorySelectionContainer`, we can trigger `mouseover` and `mousedown` events on data elements, but not `mouseup` and `click` events. This behavior does not occur if we use the default container component (all event handlers are triggered).

### Reproduction

[JSFiddle](https://codesandbox.io/s/laughing-thompson-x9c6c?file=/index.js)

**Comment by boygirl** [comment]
Apologies for the delay. This can be solved by adding an `evt.stopPropagation()` to your `onMouseDown` event. Here's a fork of your sandbox that demostrates the fix: 

https://codesandbox.io/s/clever-golick-fbeot?file=/index.js
