### ISSUE TITLE
VictoryTooltip with custom text positioned incorrectly if data label is undefined

### ISSUE THREAD

**Issue by Quanyails** [FormidableLabs/victory#1729]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using `VictoryTooltip` with a custom `text` property as a `labelComponent`, the tooltip will only render correctly if the input data has a `label` property defined, even if the value of the label isn't used.

### Reproduction

[JSFiddle](https://codesandbox.io/s/eager-lamarr-6e5zy?file=/index.js)

**Comment by boygirl** [comment]
@Quanyails for perf savings, Victory only calulates label positions for labels that exist. To fix the issue you're seeing you can set a `labels` prop on `VictoryBar` so that it calculates positions for your tooltip. Something like `labels={() => ""}` should do the trick.
