### ISSUE TITLE
keep consistent CONTRIBUTING guide across victory components

### ISSUE THREAD

**Issue by knowbody** [FormidableLabs/victory#173]
we need the CONTRIBUTING guide across all victory components.

@boygirl @coopy I was just thinking about it, and maybe we can just link each victory component to the CONTRIBUTING in victory repo? then we just maintain one doc and we are not worried about pushing changes to each of those components.

**Comment by coopy** [comment]
We should link to a CONTRIBUTING file from the individual repos; the question is if that file should live in `victory` or in the `builder-victory-component` archetype. See https://github.com/FormidableLabs/victory/issues/166.

We should pick one, and be consistent.

**Comment by knowbody** [comment]
oh, thanks for clarifying this @coopy!

let's add it to archetype as well then. Could you add one more tick box with this task and then we could close this issue in favour of #166

**Comment by coopy** [comment]
Closing in favor of #166
