### ISSUE TITLE
[IE11] TypeError: Object.keys: argument is not an object

### ISSUE THREAD

**Issue by Averethel** [FormidableLabs/victory#1736]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

On IE11 rendering any graphs result with:

```
TypeError Object.keys: argument is not an object
```

I did some digging and it is caused by the difference in implementation of `Object.keys` in ES6 and ES5.

```
Object.keys(true)
```
will return `[]` in the former and throw in the latter.
This leads me to believe that error is somewhere in reading some configuration values (it happens even on most basic charts with fallback values), using a polyfill (e.g. from core-js) fixes the problem

### Reproduction

The code provided in the [demon sandbox](https://codesandbox.io/s/m3xo745x2x) should be enough to reproduce the issue. Unfortunately, codesandbox itself does not work in IE11 so it would need to be downloaded and run locally.

**Comment by boygirl** [comment]
@Averethel Thank you for this issue. I believe this could be fixed by auditing the repo and replacing all instances of `Object.keys` with lodash `keys`
