### ISSUE TITLE
Victory Chart break multiples independent axis

### ISSUE THREAD

**Issue by vjauneau-effidic** [FormidableLabs/victory#1747]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hello, I'm currently trying to do a chart with 2 y axis and one x axis with VictoryChart.
I did the example that is here : https://formidable.com/open-source/victory/guides/custom-charts and it work but 
where i embbed the code in a <VictoryChart> component with a theme both of the axis take the same values. while my domain are different.

Questions is already asked here : https://github.com/FormidableLabs/victory/issues/555 but not answered.

Regards

**Comment by boygirl** [comment]
@vjauneau-effidic 

`VictoryChart` is intended to work with only a single domain for all of its children, including axes. To give the appearance of mutiple domains on the same chart, you can normalize all your data and then scale the label values for your axes. Here's an example: https://formidable.com/open-source/victory/gallery/multiple-dependent-axes
