### ISSUE TITLE
Background className doesn't work

### ISSUE THREAD

**Issue by mcchong** [FormidableLabs/victory#1749]
# Bugs and Questions

### Checklist

- [x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

className prop doesn't put a class on the background element for a Background element.  Has the prop in the docs though.

### Reproduction

https://codesandbox.io/s/hopeful-dew-w6wds

**Comment by beccanelson** [comment]
Thanks @mcchong! It looks like we are missing this prop in the Background component. This should be a quick fix.
