### ISSUE TITLE
How is possible to wrap group (and other) components? (for Data Driven VictoryCharts)

### ISSUE THREAD

**Issue by brumik** [FormidableLabs/victory#1758]
# Question

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description
I am trying to render charts from a huge JSON file. For this, to work I am wrapping the Victory components into other components (which handles some customizations renders the component's children via custom logic). 

The easiest I think is to show on a basic example (the `Component` element in the next examples are assigned dynamically)

It works for:
```typescript
const Component = (props) => (<VictoryBar data={ ... } {...props} />)

<VictoryChart>
    /* set the axis domain according to the data  */
    <Component />
</VictoryChart>
```
It is still imperfect since I could not figure out how the `VictoryChart` components see the `data` passed to the `VictoryBar` when not wrapped into `Component`. I would like to achieve the same functionality if possible. 

However, when I try groupped chart it displays only one data set: (offset for data sets are not applied)
```typescript
const Component = (props) => (<VictoryBar data={ ... } {...props} />);
const GroupComponent = (props) => (<><Component /><Component /></>);

<VictoryChart>
    /* set the axis domain according to the data  */
    <GroupComponent />
</VictoryChart>
```

I am struggling to understand how the implementation works, or how is the data passed around in the `Chart` or `Group` component and how could I achieve the same functionality when I am wrapping these components.

**Comment by jordantomax** [comment]
Is there any update on this issue? I am having a similar issue, attempting to wrap a set of Victory components in a custom component. I am seeing unexpected behavior, even when following the [guide on wrapping components](https://formidable.com/open-source/victory/guides/custom-components#wrapping-components). My components are structured like this:

```javascript
function Outside () {
  return (
    <VictoryChart>
      <VictoryAxis scale='time' />
      {arr.map(item => <Inside item={item} />)}
    </VictoryChart>
  )
}

function Inside ({ item }) {
  const data = item.points.map(point => ({
    date: new Date(point.date),
    value: point.value
  }))

  return (
    <VictoryGroup data={data}>
      <VictoryAxis dependentAxis />
      <VictoryLine />
      <VictoryScatter />
    </VictoryGroup>
  )
}
```

The problem is that the independent time axis doesn't accurately reflect the underlying data. It appears that the `VictoryChart` is unaware of its children unless they are direct descendants of the parent. Note that the problem persists whether I use a `VictoryGroup` or not. I have also tried spreading parent props onto the `VictoryGroup` as recommended like the below, taking into account the recommended way of splitting out `style`. When I do this, all of the data on the charts disappears. I've narrowed it down to the `domain` property. I'm not exactly sure what's happening there.

```javascript
// Trying to spread parent props onto VictoryGroup
function Inside ({ item, ...props }) {
  // construct the data
  return (
    <VictoryGroup data={data} {...props}>
      // Children
    </VictoryGroup>
  )
}
```

Nothing seems to work smoothly. Being able to use a wrapper component is necessary for me because I am using react-relay for data fetching and the child component is declaring its data requirements. But I believe this should be workable regardless of that. Do you have any recommendations for how to structure these react components or pass the data around. Any suggestions would be highly appreciated. 

I am seeing this issue with victory-native, but given that others are having the issue in the standard library, I am leaving this comment here.

**Comment by brumik** [comment]
I ended up not wrapping them into components but rather functions, you can check out in my WIP project:
https://github.com/brumik/react-data-explorer/tree/main/src/components/Chart 

Since then I switched to Patternfly 4 Charts but they are still VictoryCharts with added styling.

**Comment by jordantomax** [comment]
@brumik Thanks for sharing.

Aren't you using functional components just like my example? I think the issue in my case is that I don't fully understand what needs to be passed to the child component in order for the outer `VictoryChart` to know about it. I see that you're manually grabbing the parent chart and pulling its `props`. Are there specific props that are required on the inner components in order for the `VictoryChart` to be able to render the `VictoryAxis` correctly? That is the main problem that I'm facing now. Thanks for your help.

**Comment by brumik** [comment]
Yes, I could not figure out either what props are passed from `VictoryChart` to its children. This is why I decided not to `wrap` them in extra components, just compose them with a function. This way they are passing down props as normally, and I can add my extra props. Just make sure you are not passing prop names `children` (and a few another one) since they are definitely passed down from parent to children components.

**Comment by jordantomax** [comment]
@brumik Thanks for sharing. I'm still having this problem when I wrap child components in functional components, but I think I see what you're talking about re: composition. Though I'm actually a little unclear about how your composition works. In [this example](https://github.com/brumik/react-data-explorer/blob/main/src/components/Chart/Renderers/createChart.tsx), I see that you have a compose function called `createChart` that returns an already instantiated function. I was under the impression that React elements needed to be callable functions and that you would need to wrap `SelectedChart` inside of another function, thereby making it equivalent to a functional component. That code works as expected for you? Thanks for your help.

**Comment by brumik** [comment]
Yes it works as expected. Actually, every Functional component is a function, so you can call them and return their return value, which is a created React Element. Therefore I do not make `Functional components` but just plain functions, which return a React Element. There is a subtle difference since the function is not handled by `react` and you cannot have state or effect, or any react lifecycle-related logic. 

In the example the `createChart` is a function which returns exactly one React Element, and the type of the React Element can be one of the 4 options. These options are defined in the `components` mapper. You can see the mapper returns the `function` for a react component. Then it is called in our `createChart` function (aka Rendered with react) and the Element from this render is returned. This leads to a non wrapped component on the higher levels, but we can still separate the logic for all elements in different functions (not functional components).

**Comment by jordantomax** [comment]
Thanks @brumik I see what you mean. Unfortunately for me, I really, really want to be able to use an actual functional component. I am using `react-relay` which requires you to collocate your data requirements with components. Being unable to specify my data requirement inside of the component makes my code a lot dirtier. 

I've played around with this a lot, and it does seem as though what I'm trying to do is not possible though. It seems that the parent `VictoryChart` maintains a reference to the children. If I try to follow the example given by Victory to wrap components, if I don't pass all of the props that a component normally expects, it throws errors. Even when I'm dynamically adding those props with my wrapper component.

It would be really nice if someone from the Victory team would respond here to confirm or dispel this, or to provide some alternate ideas.

**Comment by olcayertas** [comment]
I have the same problem, I have tried to use some functional components to customize container and axis but it doesn't work. It only works if i call my functional component as a function:

```
const CombinedContainer = createContainer('selection', 'voronoi');

const selectionStyle = {
  fill: 'transparent',
  fillOpacity: 0.5,
  stroke: 'red',
  strokeWidth: 1,
};

type Props = {};

const ChartContainer = (props: Props) => (
  <CombinedContainer
    // @ts-ignore
    cursorDimension="x"
    selectionDimension="x"
    selectionStyle={selectionStyle}
    labels={({datum}) => `Date: ${datum.date}\nPrice: $${datum.close.toFixed(2)}\nVolume: ${datum.volume}`}
    {...props}
  />
);

export default ChartContainer;
```

this is working:
```
<VictoryChart
  width={width}
  padding={padding}
  minDomain={{ y: 70 }}
  maxDomain={{ y: dataSet.maxDomain }}
  containerComponent={ChartContainer({})}
>
```
but this doesn't:

```
<VictoryChart
  width={width}
  padding={padding}
  minDomain={{ y: 70 }}
  maxDomain={{ y: dataSet.maxDomain }}
  containerComponent={<ChartContainer/>}
>
```

**Comment by becca-bailey** [comment]
Apologies for the late response, but this is one of the issues we are trying to address in some upcoming work. Right now we have some confusing logic around passing data to child components based on the static `role` prop that the child has. So the workaround for now would be to add a role to a static component that matches the role of the component you are replacing. For example, if you are creating a `CustomContainer` component that wraps `VictoryContainer`, you will need to specify `CustomContainer.role = 'container'` in order to receive the correct props. Obviously this is _not_ ideal, so we're working on it!

**Comment by esdrasjnr** [comment]
@becca-bailey I'm getting the same issue. I'm trying to replace a `VictoryStack` component, but it doesn't work. What role should I use for it?

To give a better context, I'm creating a wrapper in the Victory components to use in my dashboard. I want to keep this wrapper composable, so I can create new charts more easily based on my business logic.

**Comment by matt-breeden** [comment]
@esdrasjnr did you find a solution? 

@becca-bailey any updates? Thanks for the great library.

**Comment by utg1-tdawg** [comment]
Facing the same issue. @becca-bailey May I know if there are any updates on this?

**Comment by IordanisSap** [comment]
This is really bad for large datasets

**Comment by andreas-groos** [comment]
This solution worked for me. Rendering of line charts failed when they were not a direct child of the `<VictoryChart>`. So I created a wrapper that flattens all the non-victory components, allowing me to write custom components for specific line charts that then get flattened.

```tsx
const ChartWrapper = ({ children, height, width }: WrapperProps) => {
  const flattenChildren = (children: React.ReactNode): React.ReactNode[] => {
    const result: React.ReactNode[] = [];
    React.Children.forEach(children, (child) => {
      if (React.isValidElement(child)) {
        const childType = child.type;
        // Check if it's a custom component (function component, not a Victory component)
        if (typeof childType === 'function') {
          const displayName =
            (childType as any).displayName || childType.name || '';
          // If it's not a Victory component, render it and flatten its children
          if (
            !displayName.startsWith('Victory') &&
            childType.name !== 'VictoryChart'
          ) {
            try {
              // For function components, call them directly
              const renderedChild = (childType as any)(child.props);
              if (renderedChild) {
                result.push(...flattenChildren(renderedChild));
              }
            } catch (error) {
              // If rendering fails, keep the original component
              result.push(child);
            }
          } else {
            // It's a Victory component, keep it as-is
            result.push(child);
          }
        }
      }
    });
    return result;
  };
  return (
    <VictoryChart
      padding={{ top: 4, bottom: 30, left: 40, right: 20 }}
      height={height}
      width={width}
    >
      {flattenChildren(children)}
    </VictoryChart>
  );
};
```
