### ISSUE TITLE
How to achieve the following chart?

### ISSUE THREAD

**Issue by mingbackmountain** [FormidableLabs/victory#1762]
[
<img width="261" alt="Screen Shot 2563-12-29 at 13 56 51" src="https://user-images.githubusercontent.com/25886138/103264614-cd8b7180-49dd-11eb-847e-238eeb5bc1e8.png">
](url)

How can I achieve this following chart. I have tried to use the victory area component with the help of victory stack component. However, How can I change the colour of the area base on y-axis value and not just by the colour scale of the victory stack.

**Comment by boygirl** [comment]
@mingbackmountain You can make a chart like this one using gradients with custom stops. Here are a couple examples to get you started: 
https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory
https://formidable.com/open-source/victory/gallery/stream-graph/
