### ISSUE TITLE
Shade the background of the VictoryArea

### ISSUE THREAD

**Issue by kirill-6000feet** [FormidableLabs/victory#1763]
### The Problem

Hello! I need to shade the background of the VictoryArea component. Tell me how can I do this?

Here is the code:
https://codesandbox.io/s/nameless-water-lv1ei

<img width="305" alt="Снимок экрана 2020-12-29 в 4 50 40 PM" src="https://user-images.githubusercontent.com/74168738/103288755-af7e3b00-49f6-11eb-8af9-e421a26dfdf0.png">

**Comment by boygirl** [comment]
Hi there! I altered your example. I hope that helps! https://codesandbox.io/s/great-dhawan-51xo6?file=/src/App.js

You might also take a look at these new features: 
https://formidable.com/open-source/victory/docs/new/#backgrounds-for-victorychart
https://formidable.com/open-source/victory/docs/new/#backgrounds-for-victory-label
