### ISSUE TITLE
Cross symbol

### ISSUE THREAD

**Issue by eatyourpeas** [FormidableLabs/victory#1764]
This is a small feature request - would it be possible to add a cross to the list of supported symbols?

**Comment by boygirl** [comment]
@eatyourpeas how's this looking?
<img width="486" alt="Screen Shot 2021-01-04 at 3 19 59 PM" src="https://user-images.githubusercontent.com/3719995/103589500-5d2e9580-4ea0-11eb-8291-7c7a2633271f.png">

**Comment by eatyourpeas** [comment]
That is great - I am sorry I should have made it clearer - I meant a cross as in x .

**Comment by boygirl** [comment]
I see! I could add that, but it's so similar to the "plus" symbol. What about rotating the existing plus symbol like so:

https://codesandbox.io/s/x-symbol-points-5edp4

**Comment by eatyourpeas** [comment]
Thank you for your time on this - your link only renders a line graph through the origin unless I have missed something. I did think about rotating the plus but couldn't work out how. Do I have to use the transform prop within <g> ? My code is below - I figured a custom symbol would just be simpler,
```
     <VictoryScatter
                      data={measurementPair}
                      symbol={({datum})=> datum.age_type==="chronological_age" ? measurementShape : "plus"}
                      
                      style={{ data: 
                        { fill: measurementFill } 
                      }}
                      name= 'split_age'
          />
```
where measurementShape is chosen by the use from the victory symbol selection.

**Comment by boygirl** [comment]
Apologies! It would help if I changed my codesandbox changes 😅 
https://codesandbox.io/s/x-symbol-points-5edp4?file=/index.js

My custom dataComponent looks like this: 
```
const XPoint = (props) => {
  const transform = `rotate(45, ${props.x}, ${props.y})`;
  return <Point {...props} symbol="plus" transform={transform} />;
};
```
Since the dataComponent will get access to props like `datum` you could also centralize the logic you use for selecting the symbol there.

**Comment by eatyourpeas** [comment]
That is amazing thank you!

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1058647/103706074-1cb84000-4fa4-11eb-877e-d16000f2d3f0.png">
