### ISSUE TITLE
Text/Point stretch on resize

### ISSUE THREAD

**Issue by han-yan-ds** [FormidableLabs/victory#1769]
# Bugs and Questions

### Checklist

- [X ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ X] I am using the latest version of Victory

- [X ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hello,

I have some tick labels and a point on my chart that stretches upon resizing the window.  They stretch because I want the chart to be responsive only horizontally (so preserveAspectRatio is off and the containing-div's height is fixed).

This has been brought up before with the suggestion to use a resize handler for fontSize.  How do I do that though?  There has to be a scale variable/prop being passed around somewhere on resize that can tell me how much to un-stretch the font.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/5281743/103701070-a0513d00-4f62-11eb-843d-fb99b22b0970.png)

### Checklist

- [X ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ X] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by boygirl** [comment]
Victory has no awareness of resize events that effect its container, so you'll need to add a handler yourself. Then, the easiest thing to do might be to use the handler to update the `width` and `height` props of your parent Victory component (i.e. `VictoryChart`). Updating the `width` and `height` props will update the `range` and therefore the `scale` (as in d3 scale) of your chart, which determines how everything is laid out. The `scale` prop is also passed to every primitive component Victory renders including `VictoryLabel` and custom `labelComponent` elements that you might create. Depending on what you need, you might experiment with using scale information to determine the font size your label uses. 

I hope that helps!
