### ISSUE TITLE
portal container and svg container have different size in responsive rendering mode

### ISSUE THREAD

**Issue by helt** [FormidableLabs/victory#1770]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

the root `svg` container size differs from the `div` portal size, when using responsive mode. Desired behavior is pixel-exact size, as it is the case when `responsive={false}`. 

![image](https://user-images.githubusercontent.com/1732112/103822299-260ede80-5070-11eb-8742-e35f0c24499d.png)

### Reproduction

The default sandbox is already a repro for the issue, but https://codesandbox.io/s/cold-microservice-h9qsm?file=/src/App.js is more convenient for this purpose.

**Comment by boygirl** [comment]
@helt Thanks for this issue. We actually recently changed the behavior of the container component from using `height: "auto"` to `height: "100%" to accomodate people who wanted to use different `preserveAspectRatio` behavior. https://github.com/FormidableLabs/victory/pull/1685

If I change just the portal div back to `height: "auto"` the size will be identical for default `preserveAspectRatio` values, but wildly different for other values.

**Comment by helt** [comment]
thank you for the workaround. I moved away from responsive containers anyways, but as I stumbled over this issue and were able to reproduce, I had to report it before it gets buried unnoticed.
