### ISSUE TITLE
Does flyoutPadding work?

### ISSUE THREAD

**Issue by AndrejGajdos** [FormidableLabs/victory#1772]
How can I adjust tooltip paddings? I am [trying](https://codesandbox.io/s/happy-flower-dffym) to use flyoutPadding option, but it seems like it's not working.

**Comment by boygirl** [comment]
@AndrejGajdos I took a look at your sandbox, and it looks like it's using quite an old version of Victory (v0.22.0). `flyoutPadding` was added in version 35.0.0.

**Comment by AndrejGajdos** [comment]
@boygirl that was it. Thank you!
