### ISSUE TITLE
ZoomContainer doesn't invert axis

### ISSUE THREAD

**Issue by Bopzor** [FormidableLabs/victory#1776]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using `ZoomContainer`, the inverted axis doesn't appear inverted anymore.
I expect that using `ZoomContainer` keep the axis domain as inverted.

### Reproduction

https://codesandbox.io/s/admiring-faraday-3tbkt

Hope there is enough information.
Thanks for your help!

**Comment by DanLops** [comment]
**Hello, is there any feedback on this? I'm having the same problem.**
