### ISSUE TITLE
How to extract candlestick data onClick?

### ISSUE THREAD

**Issue by tombohub** [FormidableLabs/victory#1781]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I don't know how to do it

### Reproduction

Not much to reproduce

# Feature Requests

### Checklist

- [ x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I am having a hard time understanding documentation.

I want to get open, close, high and low on click. I don't know how to work with `datum` . 

This is the Candlestick chart part i am trying to do:

```javascript
<VictoryCandlestick
          data={props.data}
          x="time"
          candleRatio={0.8}
          labels={({ datum }) =>
            `open:${datum.open}\n high:${datum.high}\n low:${datum.low}\n close:${datum.close}`
          }
          labelComponent={<VictoryTooltip />}
          dataComponent={
            <Candle
              events={{
                onClick: (e, props) => console.log(props.datum.open),
              }}
            />
          }
        />
```

how to get `datum.open` and display in console.log

**Comment by boygirl** [comment]
@tombohub I understand where you might get confused. In your example above, you are using standard events directly on the `Candle` primitive, and they will only have access to the standard event arguments. If you want the props that Victory usually adds to events that run through its event system, you should set up the events prop on a `VictoryCandlestick` and specify the `target` and `eventHandlers` you want to use. This guide has more detail and some examples: https://formidable.com/open-source/victory/guides/events
