### ISSUE TITLE
Does type Portal require width and height intentionally?

### ISSUE THREAD

**Issue by helt** [FormidableLabs/victory#1783]
I am developing in typescript

I want to use a custom container like so:
```
        <VictoryPie
            containerComponent={
                <VictoryContainer portalComponent={<VictoryDomPortal />} />
            }
```

But my IDE yells at me that I have to supply `width` and `height`, so I have to use the following instead:

```
        <VictoryPie
            containerComponent={
                <VictoryContainer portalComponent={<VictoryDomPortal width={width} height={height}/>} />
            }
```

Is this intended behaviour? I.e. Is it neccessary to supply width and height? Or is this merely due to the type definitions?

For the curious: My `VictoryDomPortal extends Portal` like this:

```
import React from "react";
import { Portal } from "victory-core";

import { VictoryPopoverPortalBridge } from "./VictoryPopoverPortalBridge";

export class VictoryDomPortal extends Portal {
    render() {
        return (
            <VictoryPopoverPortalBridge>
                {((this as unknown) as any).getChildren()}
            </VictoryPopoverPortalBridge>
        );
    }
}
```

**Comment by boygirl** [comment]
@helt Victory's `Portal` component typically renders an `svg` which does use the `width` and `height` props to set its dimensions such that it matches the main chart svg.
