### ISSUE TITLE
How can I achieve Donut Chart with Victory Pie

### ISSUE THREAD

**Issue by mingbackmountain** [FormidableLabs/victory#1802]
<img width="377" alt="Screen Shot 2564-03-09 at 17 54 20" src="https://user-images.githubusercontent.com/25886138/110460475-d0eb5980-8100-11eb-8d8e-319b682ed1f8.png">

Does anyone have any idea for implement this design?

My challenges are showing the center part, I have no idea how can I center label within the pie chart

**Comment by boygirl** [comment]
This should help you get started! https://formidable.com/open-source/victory/gallery/victory-pie-with-center-label

**Comment by brianwachira** [comment]
@mingbackmountain did you find a solution? 
I followed this solution 
https://jsfiddle.net/boygirl/z7x34s2y/3/
but I would like to achieve almost the same thing as yours

**Comment by brianwachira** [comment]
> <img alt="Screen Shot 2564-03-09 at 17 54 20" width="377" src="https://user-images.githubusercontent.com/25886138/110460475-d0eb5980-8100-11eb-8d8e-319b682ed1f8.png">
> 
> Does anyone have any idea for implement this design?
> 
> My challenges are showing the center part, I have no idea how can I center label within the pie chart

@mingbackmountain did you find a solution? 
I followed this solution 
https://jsfiddle.net/boygirl/z7x34s2y/3/
but I would like to achieve almost the same thing as yours
