### ISSUE TITLE
`labels` prop is still required when using custom tooltip component

### ISSUE THREAD

**Issue by YouMinTW** [FormidableLabs/victory#1805]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'd like to implement custom tooltip in stack bar chart. Follow the [gallery](https://formidable.com/open-source/victory/gallery/stacked-histogram) in document, I add `<VictoryVoronoiContainer >` and labels.

For customizing the Tooltip, I tried to add Flyout component on ` labelComponent={<VictoryTooltip flyoutComponent={<MyCustomFlyOut />} /> }` and I will take `datum` to my HTML flyout so I don't need labels anymore (which will generate `<svg> <text>`)  

If I don't use labels in VictoryVoronoiContainer, The tooltip can't show up.
If I use  labels in VictoryVoronoiContainer, The tooltip will show label (`<svg> <text>`) and `<MyCustomFlyOut>` and I can't find where to switch off label

### Reproduction

1. add `<VictoryVoronoiContainer>` in `<VictoryChart containerComponent={}>`
2. add `labels` in `<VictoryVoronoiContainer>`
3. add  `labelComponent={<VictoryTooltip />}` in `<VictoryVoronoiContainer>`
4. add  `flyoutComponent={<MyCustomFlyOut />}` in `<VictoryTooltip />`

[codesandbox](https://codesandbox.io/s/brave-hawking-inoe6?file=/src/App.js)
```
   <VictoryChart
        containerComponent={
          <VictoryVoronoiContainer
            labels={({ datum }) => (datum.y > 0 ? `${datum.y} songs` : null)}
            labelComponent={<VictoryTooltip />}
          />
        }
   >
```

```
    <VictoryChart
        containerComponent={
          <VictoryVoronoiContainer
            // labels={({ datum }) => (datum.y > 0 ? `${datum.y} person` : null)}
            labels={() => ''} // which make tooltips doesn't show up 
            labelComponent={<VictoryTooltip flyoutComponent={<MyCustomFlyOut />} />}
          />
        }
      >
```

### My Reference
[Doc - labelComponent](https://formidable.com/open-source/victory/docs/victory-voronoi-container#labelcomponent)
[Doc - stacked-histogram](https://formidable.com/open-source/victory/gallery/stacked-histogram)
[github - Is there a way to add HTML tooltips?](https://github.com/FormidableLabs/victory/issues/445)
[github - Problem with VictoryVoronoiContainer Example](https://github.com/FormidableLabs/victory/issues/1105)
[github - Victory ToolTip Does not Appear](https://github.com/FormidableLabs/victory/issues/1393)
[medium Creating chart tooltips with VictoryJs](https://medium.com/the-andela-way/creating-chart-tooltips-with-victoryjs-c68273a4b1f7)
[spectrum - Persistent tooltip labels and points](https://spectrum.chat/victory/general/persistent-tooltip-labels-and-points~9827fcc6-89a2-4b17-a66e-14ecca1727ad)
[spectrum - How to use a custom tooltip component with labelComponent?](https://spectrum.chat/victory/general/how-to-use-a-custom-tooltip-component-with-labelcomponent~cbbed5b9-68c8-47fb-b4ba-bd4a7fea1f45)

**Comment by boygirl** [comment]
@YouMinTW thanks for the detailed reproduction. I think there is an underlying bug, and I will look into it. As a temporary workaround, you can use `labels={() => ' '}` (a single space rather an an empty string)

**Comment by YouMinTW** [comment]
Thanks for your kindly reply.
The workaround work, and I will use it first.

**Comment by chriszrc** [comment]
@boygirl did instructions for html tooltips ever make it to the docs? https://github.com/FormidableLabs/victory/issues/445#issuecomment-328205863

**Comment by DevGeorge** [comment]
Another problem I've seen is that if you pass in a customFlyout component the default Flyout component still renders. Filling the labels with `''` works for now
`return {
              x: new Date(item.x),
              y: y,
              label: '',
              otherLabel: 'Real label'
}`
