### ISSUE TITLE
Brush area is initially stuck when styling handles with <svg>

### ISSUE THREAD

**Issue by aknaut** [FormidableLabs/victory#1806]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I would like to style the handles of a VictoryBrushContainer. There should be centered rectangles on the handles and therefore I am using a <svg> container to get a new coordinate system. When I am introducing the svg the brush area is intially stuck. After clicking into the brush area or draggin it I can start manipulating it and it behaves as expected.

### Reproduction

A minimal version can be found here https://codesandbox.io/s/vibrant-wiles-iir66?file=/index.js

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

It would be great if I could use a relative coordinate system to style the handles like in the example.

**Comment by boygirl** [comment]
@aknaut I think this is happening because your handle svg is capturing the events that would normally be captured by the container svg and used to handle resizing the brush area. You can fix this by adding `pointerEvents="none"` to your handle svg

**Comment by aknaut** [comment]
@boygirl thanks for the hint! I changed it to that but now my cursor style is not updated when I hover over the handles. Do you have any idea how to fix that as well?
