### ISSUE TITLE
hover one dataComponent and let other dataComponents be transparent in VictoryPie

### ISSUE THREAD

**Issue by lch9487** [FormidableLabs/victory#1808]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'd like to have the behavior when I hover one of dataComponents in VictoryPie and let other dataComponents be transparent.\
I've searched for `childName`, but it can't use in VictoryPie, because there aren't any children to specify.\
Because the `mutation` event only for the hovered one, how can I get others update?\

My expected behavior.\
![Screen Shot 2021-03-22 at 4 19 59 PM](https://user-images.githubusercontent.com/26849535/111960472-c2eaff00-8b2a-11eb-8002-7cba2b02f412.png)

### Reproduction

[code sandbox](https://codesandbox.io/s/tender-kalam-ytdy1?file=/src/App.js)

```
events={[
          {
            target: "data",
            eventHandlers: {
              onMouseOver: (e, props) => {
                return [
                  {
                    mutation: (props) => {
                      const fill = props.style.fill;

                      return { style: { fill, opacity: 1 } };
                    }
                  },
                ];
              },
              onMouseOut: () => [
                {
                  mutation: (props) => {
                    const fill = props.style.fill;

                    return { style: { fill, opacity: 0.3 } };
                  }
                },
              ]
            }
          }
        ]}
```

**Comment by boygirl** [comment]
Apologies for the delay! You can take advantage of the special `eventKey: "all"` to target every slice of your pie. Victory will apply your mutations in order, so first set all of your pie slices to be semi-transparent, and _then_ alter the opacity on just the slice you're hovering. like so:

```
onMouseOver: (e, props) => {
  return [
    {
      eventKey: "all",
      mutation: (props) => {
        const fill = props.style.fill;

        return { style: { fill, opacity: 0.3 } };
      }
    },
    {
      mutation: (props) => {
        const fill = props.style.fill;

        return { style: { fill, opacity: 1 } };
      }
    }
  ]
}
```
https://codesandbox.io/s/dreamy-dan-tg1fz?file=/src/App.js
