### ISSUE TITLE
How to make it so that a VictoryLine with tickCount value sticks to the values on the right?

### ISSUE THREAD

**Issue by RamonEMV** [FormidableLabs/victory#1809]
I have a doubt, my chart looks like this:

![imagen](https://user-images.githubusercontent.com/49501000/112245036-c9a27080-8c15-11eb-9898-65f165d89e46.png)

And I want the victory chart to prioritize showing the right-most value, wich would be the newest one in the data (in this case it would be 20:24 but It shows 20:22)

**Comment by RamonEMV** [comment]
My axis looks like this right now
`<VictoryAxis
                  crossAxis
                  theme={VictoryTheme.material}
                  standalone={false}
                  tickValues={data.map(d => moment(d.date).format('HH:mm'))}
                  fixLabelOverlap={true}
                  tickCount={5}
                  style={{
                    grid: { stroke: 'transparent' },
                    tickLabels: {
                      fill: themeColors.label
                    }
                  }}
                />`

**Comment by boygirl** [comment]
Apologies for the delay. When you provide a `tickCount`, Victory will downsasmple your `tickValues` array with this function:

https://github.com/FormidableLabs/victory/blob/main/packages/victory-core/src/victory-util/axis.js#L221

If you need to preserve a particular tick value, I would recommend _not_ using `tickCount`, an doing some custom filtering / downsampling on your values before providing them to `tickValues`
