### ISSUE TITLE
VictoryTooltip static y-position with pointer

### ISSUE THREAD

**Issue by Adam-isdd** [FormidableLabs/victory#1810]
After reading docs I didn't find any possibility to have VictoryTooltip with fixed Y position and still retain pointer fixed to data point.
If I make `<VictoryTooltip  y={75} />`  pointer is too short. I am looking for something like `<VictoryTooltip  center={{y: 75}} />` without x property.

Minimal example works how I want it but when I use Typescript value `x` is mandatory.
https://codesandbox.io/s/angry-mclaren-7zcuo?file=/src/App.js

**Comment by boygirl** [comment]
Apologies for the delay! I will update the typescript types to make the x value optional
