### ISSUE TITLE
y-position with 100k show like this 00,000 but i'd want to show it originally. How to i fix it?

### ISSUE THREAD

**Issue by woogyeongsik** [FormidableLabs/victory#1811]
When y-values exceed 100k on bar-chart, it show 00,000. But i want to show it like 100,000 not 00,000.
please give me some key to solve about the problem.

thank you

**Comment by boygirl** [comment]
@woogyeongsik it sounds like your labels are being cut off by the edge of your svg. You have a few options for how to fix it, but I recommend altering the overall `padding` on your chart. Here's more information: https://formidable.com/open-source/victory/docs/faq/#my-axis-labels-are-cut-off-how-can-i-fix-them

**Comment by woogyeongsik** [comment]
@boygirl Thank you for your comment.
