### ISSUE TITLE
The brush container is no longer clickable after upgrade from version 34.1.3

### ISSUE THREAD

**Issue by 6axter82** [FormidableLabs/victory#1813]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory !!! tried multiples

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I had used a victory version 34.1.3 and upgraded to the latest, cause I wanted to use the latest lodash dependacies.

After the upgrade the BrushContainer is not responding on clicks in the chart. Dragging works though.

### Reproduction

I have made a sandbox here: https://codesandbox.io/s/spring-rain-2swm5

This reproduction is set with the version 34.1.3, now try to change to any victory version starting from 35.4.0 and click somewhere else in the chart

PS: In my own project on my local machine the break happens already starting from 35.0.0.

**Comment by boygirl** [comment]
@6axter82 thanks for the reproduction! I took a look, and it seems like the problem is with `allowResize={false}`. When that prop is true everything works as expected. This is defintely a bug on our end. I'll do some more digging and try to get a fix out for you as soon as I can.

**Comment by 6axter82** [comment]
@boygirl Thank you very much!
