### ISSUE TITLE
How do you get the width of a component after it's rendered.

### ISSUE THREAD

**Issue by surgetom** [FormidableLabs/victory#1814]
Hi All,

I can't seem to find anything online which shows me how to get the width of a component after it has been rendered.

I need to know the width of my ```<VictoryStack />``` after rendering.

Note: I'm using Victory with React Native. 

_I've removed my options below to make my scenario easier to read._

```
 <VictoryChart>
    <VictoryAxis dependentAxis /> // y axis
    <VictoryAxis />                  // x axis
    <VictoryStack />
<VictoryChart>
```

Thanks in advance

**Comment by beccanelson** [comment]
Hi @surgetom, this solution is not specific to Victory, but if you need the width in pixels you can wrap your victory chart with a wrapper component, pass in a ref, and call `ref.current.clientHeight`. 

Here's an example:
```
function App() {
  const ref = React.useRef();
  const [width, setWidth] = React.useState();

  React.useEffect(() => {
    if (width !== ref.current?.offsetWidth) {
      setWidth(ref.current?.offsetWidth);
    }
  }, [ref, width, setWidth]);

  return (
    <div className="container" ref={ref}>
      <VictoryChart>
        <VictoryBar></VictoryBar>
      </VictoryChart>
      Width: {width} pixels
    </div>
  );
}
```
Code sandbox: https://codesandbox.io/s/victory-width-demo-6ht1e?file=/src/App.js

**Comment by beccanelson** [comment]
I'll close this for now since this isn't a Victory-specific issue, but let me know if that solution works for you!
