### ISSUE TITLE
export 'bin' (imported as 'd3Array') was not found in 'd3-array'

### ISSUE THREAD

**Issue by 6axter82** [FormidableLabs/victory#1822]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
After updating to the latest version of victory 35.5.1 
getting the following printout in terminal after 'yarn start':

WARNING in ./node_modules/victory-histogram/es/helper-methods.js 63:12-23
"export 'bin' (imported as 'd3Array') was not found in 'd3-array'
 @ ./node_modules/victory-histogram/es/victory-histogram.js
 @ ./node_modules/victory-histogram/es/index.js
 @ ./node_modules/victory/es/index.js

**Comment by boygirl** [comment]
@6axter82 thanks for opening this issue. Unfortunately, I'm not able to reproduce it. We did make some changes to how we build Victory's `dist` in the latest version, but the warning you're seeing looks like it's referencing the `es` source, so I wouldn't expect the resent set of changes to cause it. You can see the diff here: https://github.com/FormidableLabs/victory/pull/1819/files

**Comment by JWess** [comment]
I am seeing this exact same error, and I can't figure out why. My co-workers are not seeing the same issue. I have tried changing versions of Node/Npm, re-cloning my repo, etc. I use NVM in case that somehow helps, and we are using Craco to build our React app that was originally created with Create React App.

![image](https://user-images.githubusercontent.com/8697891/126365198-1308a5ee-4d02-4e48-b842-99536dd92749.png)

**Comment by mcserep** [comment]
I have the very same issue, only on Windows. Did anyone managed to solve it?  
npm v6.14.11
node v14.16.0

**Comment by mcserep** [comment]
After some debugging it turned out if I execute in `npm start` or `npm run build`, there is no issue, only when using the good old Command Prompt of Windows. Since there are separate `.cmd` and `.ps1` scripts in the `.bin` folder of `node_modules`, there could be an issue with the Batch scripts.
