### ISSUE TITLE
TS warnings with onTouchStart and onTouchEnd props

### ISSUE THREAD

**Issue by TomCorvus** [FormidableLabs/victory#1823]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hello, 👋 
I have a TS warning when I use `onTouchStart` and `onTouchEnd` props on `VictoryVoronoiContainer` component.
this is the TS2769 error (No overload matches this call) and I didn't see any definitions for these props in Victory Core.

https://formidable.com/open-source/victory/docs/common-container-props#ontouchstart

Thanks for your help.

Regards,

**Comment by boygirl** [comment]
Hi there! This should be a `victory-native` issue since these are native only props, and it's actually something I've just fixed in the latest release of `victory-native`. Here's the issues that was closed there: https://github.com/FormidableLabs/victory-native/issues/632
