### ISSUE TITLE
VictoryStack issues with setting domain/minDomain

### ISSUE THREAD

**Issue by madandrija** [FormidableLabs/victory#1824]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using the [gallery demo for 100% column chart](https://formidable.com/open-source/victory/gallery/100-column-chart), after adding the domain value (e.g.  `domain={{y:[40,100]}}`), I would expect the rendering to start at 40%. Instead, the chart starts rendering below the x-axis.

### Reproduction

Open the [gallery example](https://formidable.com/open-source/victory/gallery/100-column-chart) and add the `domain` value to either the `Chart` or the `Stack` component, e.g

```
<VictoryStack
              colorScale={["black", "blue", "tomato"]}
                domain={{y:[40,100]}}
            >
```

or for `minDomain`, 

```
<VictoryStack
              colorScale={["black", "blue", "tomato"]}
                   minDomain={{y:40}}
            >
```

**Comment by boygirl** [comment]
@madandrija Thank you for this issue and the steps to reprduce it. It does look like a bug!

**Comment by boygirl** [comment]
@madandrija we're investigating this issue now in https://github.com/FormidableLabs/victory/pull/1825

As a temporary solution you can try supplying `VictoryClipContainer` as the `groupComponent` for `VictoryStack` like so:
`groupComponent={<VictoryClipContainer />}`

**Comment by madandrija** [comment]
@boygirl - awesome, thanks!
