### ISSUE TITLE
VictoryTheme.material modifying

### ISSUE THREAD

**Issue by dhanushm360** [FormidableLabs/victory#1828]
I'd like to modify the components within the material theme in VictoryTheme. How can I do this? I tried modifying the material.js, but it doesn't look like it's doing anything.

**Comment by boygirl** [comment]
In Victory, themes are just objects with expected properties. The easiest way to get started would be to copy the object from `material.js`, and then start altering values. Next you will supply your new theme as a prop to you top level Victory component (usually VictoryChart)

Here's an example: 
https://codesandbox.io/s/altering-a-theme-kwr3m?file=/index.js
