### ISSUE TITLE
Domain Padding for Y Axis not working correctly 

### ISSUE THREAD

**Issue by daniey1108** [FormidableLabs/victory#1829]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When trying to use the DomainPadding Prop and using it for both the x and y axis assigning different variables to each of them like this `{ x: [left, right], y: [bottom, top] }` The one for y bottom does not change the graph at all. This can be replicated on the example code for the domain padding prop in the [documentation](https://formidable.com/open-source/victory/docs/common-props#domainpadding) as well as in the project I am working on. 

Is there a workaround for this problem? I would like the y axis to have more padding from the bottom. I am making a double line graph, and one set of data has y values like 1000, 2000, 3000 and the other set of data has values like 20, 30, 40 I would like additional padding on the y axis so that the second line does not appear to overlap with the base line for the x axis. 

### Reproduction

If you replace the domain padding example code with: `domainPadding={{ x: [20,20], y: [200, 0]}}` regardless of what you change the first item in the y array to, it has no affect on the graph whats so ever. 

Here is a sandbox example with the same graph, but with the domain padding changed for both the graphs and there is no difference between the two based on what should have happened. [sandbox](https://codesandbox.io/s/quizzical-sea-q26vz?file=/index.js)

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

**Comment by boygirl** [comment]
@daniey1108 by default, Victory will constrain `domainPadding` so that it does not increase the number of quadrants in your chart (as in, it will not let your domain expand into negative values if it isn't already). You can alter that behavior with the `singleQuadrantDomainPadding` prop. Here's some more information: https://formidable.com/open-source/victory/docs/common-props/#singlequadrantdomainpadding
