### ISSUE TITLE
Segmented Picker for changing axis scale

### ISSUE THREAD

**Issue by dhanushm360** [FormidableLabs/victory#1830]
I'd like to use this segmented control library with the options Day, Week, Month, and Year. Whenever I pick one of these the chart should update and the axis scale should change corresponding to what I picked. For example, if I was on Week, the axis scale would be Sun, Mon, Tue, Wed... Then, if I changed it to Month, the axis scale should change to Jan, Feb, Mar... Is there a way I can do this with victory-native?

**Comment by boygirl** [comment]
You could do this by altering the `tickFormat` prop (and potentially also the `domain` depending on what you're trying to do) on your chart when your option changes. Here's more information on the `tickFormat` prop: https://formidable.com/open-source/victory/docs/victory-axis#tickformat
