### ISSUE TITLE
Scale missing in typescript interface for VictoryCursorContainer

### ISSUE THREAD

**Issue by topched** [FormidableLabs/victory#1831]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using a ref on VictoryCusorContainer `scale` is missing from the interface

### Reproduction

https://codesandbox.io/s/hardcore-night-63q1x?file=/index.tsx

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Add the typing for the x and y scale functions that are provided from the cursor container

**Comment by boygirl** [comment]
@topched thanks for the issue and the reproduction! I'll take a look!
