### ISSUE TITLE
`VictoryScatter` with `dependentAxis` set to `invertAxis` doesn't render

### ISSUE THREAD

**Issue by andrew-anguiano** [FormidableLabs/victory#1836]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When attempting to use `VictoryScatter` in a `VictoryChart` with `<VictoryAxiy dependentAxis invertAxis />`, the scatter chart is not rendered. This issue appears to have been added in 35.6.0; in 35.5.1 it works as expected.

I think it arises from https://github.com/FormidableLabs/victory/blob/e65abc9b17bf33067cacfe912c43158cbe1b2790/packages/victory-core/src/victory-util/data.js#L124. When the axis is inverted, it improperly sets `_y` to `null`.

### Reproduction
https://codesandbox.io/s/blissful-elion-hvx5l?file=/index.js

I'm happy to create a PR to solve this if I can get a little context as to what needs to be done. For now, I will just downgrade. It's feeling like a higher-level issue than just fixing that if-statement since that function doesn't have context as to whether the axis is inverted (and the domain is provided reversed so it's getting `maxDomainY = 0; minDomainY = 5` for example). 

https://github.com/FormidableLabs/victory/blob/e65abc9b17bf33067cacfe912c43158cbe1b2790/packages/victory-core/src/victory-util/data.js#L101

Thanks for the project!

**Comment by jhumbug** [comment]
Thanks for opening this issue!  The fix should be part of the next release.
