### ISSUE TITLE
VictoryAccessibleGroup

### ISSUE THREAD

**Issue by daniey1108** [FormidableLabs/victory#1841]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

VictoryAccessibleGroup seems to not be exported by the main Victory npm package. 

### Reproduction

Using the Newest Version of Victory I am unable to use the VictoryAccessibleGroup. I am attempting to use it on a line graph and/or a victory axis 

`<VictoryLine data={myData} x="day" y="num" groupComponent={ <VictoryAccessibleGroup />} />`

`<VictoryAxis data={myData} dependentAxis  groupComponent={ <VictoryAccessibleGroup />} />`

was i incorrect in understanding the use of VictoryAccessibleGroup? I would just like to be able to supply an aria-label to the axis saying like "X Axis of Days of the week" and on the actual line, id love to add a description. 

I am unable to find any example on how to actually use VictoryAccessibleGroup, outside of your documentation.

**Comment by boygirl** [comment]
You're right! `VictoryAccessibleGroup` is exported from `victory-core`, but I forgot to re-export if from the main `victory` package. I'll correct that oversight right now!
