### ISSUE TITLE
nps start error on Windows

### ISSUE THREAD

**Issue by VadimSvirdoff** [FormidableLabs/victory#1843]
Hi, could you help me, I have cloned and installed repo by instruction, but this error appaired.
![image](https://user-images.githubusercontent.com/44972265/117644885-a36b6c80-b192-11eb-950e-0af7d3525d38.png)

**Comment by boygirl** [comment]
@VadimSvirdoff Can you give me a bit more information about what node version you're using? You might also try manually killing all your node processes and trying again

**Comment by VadimSvirdoff** [comment]
@boygirl First time I used 10.16.3, and I got an error with package installation, and than 14.16.1 when I got error with running.

**Comment by boygirl** [comment]
I'm also on node ~14. Are you using windows?

**Comment by VadimSvirdoff** [comment]
yep
