### ISSUE TITLE
Typescript - is an event handler always required to return an EventCallbackInterface?

### ISSUE THREAD

**Issue by tvsmk** [FormidableLabs/victory#1851]
# Bugs and Questions

### The Problem

When using Typescript and assigning event handler that does not return anything, the "No overload matches this call" error is thrown.

### Reproduction

Sandbox created here: https://codesandbox.io/s/long-snow-m6vnz?file=/index.tsx

### Description

When using Typescript and assigning an `onClick` event handler that does not return anything, the "No overload matches this call" error is thrown. The only required prop on the `EventCallbackInterface` is the `mutation` prop, however I do not want to mutate anything, just do something arbitrary such as navigate to a different page. When it runs, the event handler is called correctly so I believe this is maybe a type definition issue. Is there a workaround for this? Thanks

**Comment by boygirl** [comment]
You're right. I think this is a type definition issue. The solution will be altering the type def in the library.
