### ISSUE TITLE
How to share events between legend and chart

### ISSUE THREAD

**Issue by franjorub** [FormidableLabs/victory#1854]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x] I am using the latest version of Victory

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

# Feature Requests

### Checklist

- [ x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Hi, 

I would like to do a feature using shared events but I'm not very clear about how to achieve it. 

the idea is to click on one legend item and hide the chart related to it (a line chart more specifically) and if I click again the chart must be shown again.

thanks for your orientation.

**Comment by boygirl** [comment]
Hi @franjorub 

Here's an example of a chart with a legend that highlights related lines. This one is using the `events` prop on `VictoryChart`, but you could get a similar effect by wrapping related elements in `VictorySharedEvents`.  The example has a lot of code comments to explain what's going on, but please let me know if you have further questions. 

https://codesandbox.io/s/bottom-legend-with-events-zvce7?file=/index.js:2529-2676
