### ISSUE TITLE
Tooltips show only first data point, if chart scale is set to 'log' and 'voronoiDimension' is set (with Codesandbox link)

### ISSUE THREAD

**Issue by man-on-box** [FormidableLabs/victory#1857]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When setting any scale (`x` or `y`) to `log` **and** setting a `voronoiDimension`, the `VictoryVoronoiContainer` only renders the tooltip on the very first datapoint.

This bug only occurs when both conditions are true.

### Reproduction

https://codesandbox.io/s/victory-scale-tooltip-log-scale-rybuk?file=/src/App.js

**Comment by boygirl** [comment]
@man-on-box 

Thank you so much for the reproduction. That helps a ton. I'll take a look and try to get a fix out this week.

**Comment by man-on-box** [comment]
Thanks for verifying. I assumed the bug was in the `VictoryVoronoiContainer` but I tracked that the datapoints passed in as props to the container included the bug (always the first datapoint was passed).

I stopped there as it was getting difficult to track the props, without downloading this repo running the library locally.

**Comment by boygirl** [comment]
@man-on-box apologies for the delay.`VictoryVoronoiContainer` sets  `_voronoiX` and `_voronoiY` points for each datum that are used to calculate the set of nearest points, When a `voronoiDimension` is given, the opposite dimension voronoi point is always set to zero, which works fine for normal scales, but breaks log scales.
