### ISSUE TITLE
Victory Line deal with no data  example not working

### ISSUE THREAD

**Issue by YoungGary** [FormidableLabs/victory#1860]
# Bugs and Questions

### Checklist

- [√ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ √] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [√ ] I am using the latest version of Victory

- [ √] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

the doc  ： https://formidable.com/open-source/victory/gallery/victory-line-with-null-data   shows we can deal with null data  through insert null data  sothat the line is  continuous  but it is not working for me  and  the doc is not working either

**Comment by boygirl** [comment]
@YoungGary The example you reference is working as expected. When null data is used with `VictoryLine`, breaks in the line is the expected result. If you would like to avoid breaks in the data, the best thing to do would be to filter your `data` prop to remove any null values.
