### ISSUE TITLE
Question - Is it possible to add `gap` between stacked bars?

### ISSUE THREAD

**Issue by qjnz** [FormidableLabs/victory#1862]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x] I am using the latest version of Victory

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

How can we add some gap between the stacked bars here? I have tried to add margin / padding to one of the bars but none seem to be working.

![image](https://user-images.githubusercontent.com/75322/119288331-70e66700-bc9c-11eb-850a-0b82fe78a086.png)

Example code to play around:  https://codesandbox.io/s/23x6jmlnpn?from-embed=&file=/src/index.js

**Comment by boygirl** [comment]
@qjnz yes! You could do this by adding a `stroke` and `strokeWidth` to your bar styles, or if you only want the gap on one side of your bar (say the top edge) you could do this with a custom `dataComponent` for `VictoryBar` that trimmed off a pixel or two on the top edge. Your custom data component could look something like this:

```
const CustomBar = props => {
  // adding rather than subtracting 2 pixels because svg y coordinates start from the top
  return <Bar {...props} y={props.y + 2} />;
};
```
