### ISSUE TITLE
Possible to fill in color vertically in a Victory Pie Component?

### ISSUE THREAD

**Issue by AndresTIY** [FormidableLabs/victory#1869]
# Bugs and Questions

### Checklist

- [x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

So I'm trying to use Victory Pie to display a Circle on top of a Chart with Horizontal Lines. The challenge I'm facing is that we want the circle's to have a fill in color that comes in vertically, like a water glass being filled. I couldn't find anything in the docs that allow me to do something like this. Is this possible? 

Here's the screenshot of a mock up I'm trying to work with. 

<img width="194" alt="Screen Shot 2021-05-28 at 9 44 08 AM" src="https://user-images.githubusercontent.com/25064365/120020261-16584e00-bfaf-11eb-9f28-e44a9666a9ee.png">

### Reproduction

Here's an example of what I've been able to do so far:

```
const Example = () => {

  const sampleData = [
    { x: '', y: 20 },
    { x: '', y: 30 },
    { x: '', y: 30 },
    { x: '', y: 20 },
  ];

  const colorScale = [Colors.GREY, Colors.PURPLE, Colors.PURPLE, Colors.GREY];

  return (
    <VictoryPie colorScale={colorScale} innerRadius={130} data={sampleData} />
  );
}
```

<img width="580" alt="Screen Shot 2021-05-28 at 12 09 19 PM" src="https://user-images.githubusercontent.com/25064365/120020328-2a03b480-bfaf-11eb-8187-1bca55ea9c97.png">

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
Hi @AndresTIY! This is possible, but you'll want to use an svg pattern or gradient fill. Here are a couple examples of using gradient fills with Victory that should help you get started:

https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory

https://formidable.com/open-source/victory/gallery/stream-graph
