### ISSUE TITLE
How do I control the amount of zooming on the VictoryZoomContainer?

### ISSUE THREAD

**Issue by cintiapinto** [FormidableLabs/victory#1872]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I want to be able to control the amount of zooming being done in the `VictoryZoomContainer`.

Also. when I use `downsample` in the  `VictoryZoomContainer`, one of my  bar graph disappears. The one defined here: 

```
            {contextItems.map((contextItem) => (
              <VictoryBar
                standalone={false}
                data={[{x: getContextXCoordinate(contextItem.startYear), y:600}]}
                dataComponent={
                  <ContextGraphComponent  />
                }
              />
            ))}
```

### Reproduction

My current code consists of a wrapping `VictoryChart` component with two `VictoryBar` components inside it.

```
        <VictoryChart
            domain={entireDataDomain}
            padding={{ 
              top: 0, 
              bottom: 0, 
              left: -24.9, 
              right: -41.6 
            }}
            containerComponent={
              <VictoryZoomContainer 
                allowPan={true}
                zoomDimension="x"
                downsample={zoomLevelInYears}
                zoomDomain={graphZoomDomain}
                onZoomDomainChange={(graphDomain, props) => {
                   setGraphZoomDomain(graphDomain)
                }}
              />
            }
          >
            <VictoryAxis 
              dependentAxis 
              offsetX={8.4}
              tickFormat={(t) => `${(t)}\nppm`}
              style={{
                axis: {
                  stroke: `${colours.black}`, 
                  strokeWidth: 60, 
                  strokeLinecap: "square",
                },
                ticks: {
                  stroke: `${colours.white}`, 
                  transform: "translate(8.2px, 0)",
                  size: 4,
                },
                tickLabels: {
                  fill: `${colours.white}`, 
                  fontSize: 4.5,
                  padding: 3,
                  textAnchor: 'start',
                  fontFamily: `${fonts.family.maisonNeue}`
                },
              }}
            />

            {contextItems.map((contextItem) => (
              <VictoryBar
                standalone={false}
                data={[{x: getContextXCoordinate(contextItem.startYear), y:600}]}
                dataComponent={
                  <ContextGraphComponent  />
                }
              />
            ))}

            <VictoryBar
              standalone={false}
              data={graphDataPoints}
            />
          
          </VictoryChart>
```

This is not working at the moment because the zoom does not snap and I'm not sure how to define that feature.

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I want to be able to control the amount of zooming being done in the `VictoryZoomContainer`.

What I ultimately want to achieve is a snap zoom feature, where the zoom will have pre-defined breakpoints.

For example:
1. zoom is at a level showing 1000 bars in a bar graph. this is the maximum zoom out level and the graph cannot be zoomed out further.
2. zooming in would go to the next snap breakpoint - e.g. 500 bars in the bar graph

I want panning to be allowed so that the user can navigate left and right.

- It would also be good to know - is there a way to access the events in the Zoom Container directly? 

Thanks!

**Comment by cintiapinto** [comment]
I ended up making my own custom Zoom container for this.

**Comment by vtarelkin** [comment]
@cintiapinto good day, could you provide your solution please? stuck at the zoom too
