### ISSUE TITLE
Define width for custom dataComponent bar chart from x1 to x2

### ISSUE THREAD

**Issue by cintiapinto** [FormidableLabs/victory#1873]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am trying to create barchart that has "thick" bars that I can defined from one point to another on the x axis. (from x1 to x2)

### Reproduction

I am currently trying to define the width with:

```
const width = x2Value - datum._x

where `x2Value` is the end value that I want for my bar
```

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I am trying to create barchart that has "thick" bars that I can defined from one point to another on the x axis. (from x1 to x2)

I am using a custom component here that has access to the `dataum` and therefore the `x` value.
However, I can't seem to be able to define the width of the bar from one x to the other. 

Maybe there's some other exposed functionality of Victory that I've missed in the docs that would make this possible?

Thank you for the help!

**Comment by beccanelson** [comment]
Hi @cintiapinto , as far as I know there isn't a way to do this currently. The width of a bar can be specified using the `barWidth` prop, setting the `width` on the style object, or setting the `barRatio`. From there, the SVG path is calculated based on the container width and the bar width. 

https://github.com/FormidableLabs/victory/blob/d929836c5d718ddb3a2a9aab8d30f251a74e3a61/packages/victory-bar/src/path-helper-methods.js#L5

If you wanted to do something really customized, you could use the `getPath` prop on the `Bar` component to calculate your own custom path based on the `x` and `y` values. (This isn't currently documented for `Bar`, but is listed here in the `Point` props. https://formidable.com/open-source/victory/docs/victory-primitives#point 

In most cases, I think you will find that `barWidth` and `barRatio` will do a lot of this for you, but I'm not sure if there's something really specific you're trying to do. 

I'm closing this issue for now, but let me know if you need more specific guidance!
