### ISSUE TITLE
Keep the y axis always to the left independent of the positive/negative quadrant

### ISSUE THREAD

**Issue by JoleMile** [FormidableLabs/victory#1875]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Is there a way to always keep the "y axis" all the way to the left even while panning to the negative side?
You can check the codesandbox below.

### Reproduction

https://codesandbox.io/s/distracted-firefly-39n4e?file=/index.js:222-370

How it is now:
![Screen Shot 2021-06-10 at 1 44 34 PM](https://user-images.githubusercontent.com/9325716/121452972-75c54d80-c9f4-11eb-88a5-9e5bfc49a781.jpg)

How I would like it to be:
![Screen Shot 2021-06-10 at 1 44 34 PM (2)](https://user-images.githubusercontent.com/9325716/121452997-807fe280-c9f4-11eb-86c3-b380418f909f.jpg)

**Comment by boygirl** [comment]
@JoleMile You can set the `xOffset` prop on your dependent axis so that it is always in the same, fixed position. Here's more information about that prop: https://formidable.com/open-source/victory/docs/victory-axis#offsetx

**Comment by JoleMile** [comment]
@boygirl The proposed solution doesn't really work when using the `zoomDomain` as it's `fixed` position. I guess it's just not possible to do what I'm asking for. Thank you for replying nevertheless :)
