### ISSUE TITLE
Bar chart domainPadding spacing for variable number of items

### ISSUE THREAD

**Issue by danly** [FormidableLabs/victory#1876]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a bar chart that could render a variable date range that could be anywhere from 1 - 365+ items.

I want to align my bars to the center of each tick and also ensure that the bar doesn't overlap with my y-axis. I have made my chart responsive according to the containers width. For small datasets, the first bar starts y-axis for small datasets as the width increases (widths >1000px). I tried using the suggestions found in [FAQ: Why are the bars in my bar chart overlapping with the axis?](https://formidable.com/open-source/victory/docs/faq/#why-are-the-bars-in-my-bar-chart-overlapping-with-the-axis), but tuning `domainPadding` for a variable number of items doesn't seem feasible.

![image](https://user-images.githubusercontent.com/11883444/121491988-6d2f4000-ca11-11eb-8ec3-86144c0908f4.png) 

I have also tried setting the `barRatio` to `0.1` however, I would like the bars to grow in relation to the chart's width.
![image](https://user-images.githubusercontent.com/11883444/121494065-5d186000-ca13-11eb-9935-e637347c1c76.png)
![Screen Shot 2021-06-10 at 5 40 10 PM](https://user-images.githubusercontent.com/11883444/121494075-60135080-ca13-11eb-8cae-d6e0cf66a9bc.png)

Is there a better way to dynamically set `domainPadding` depending on the width and the number of items?

### Reproduction
[Sandbox](https://codesandbox.io/s/gifted-sinoussi-se74m?file=/index.js)

**Comment by boygirl** [comment]
@danly I've got an example that should help you!

https://codesandbox.io/s/grouped-or-stacked-charts-0jh3h

This chart is designed to work with a variable number of bars and determine 1) how wide to make the bars 2) how much domainPadding to use and 3) whether they should be grouped or stacked depending on how much data there is (grouped when there's not too much data, stacked else). 

Not all of it will be relevant to you, but I imagine the bar width and domainPadding logic is just what you need.

**Comment by danly** [comment]
Thanks for the helpful response @boygirl! 

Have you and your team thought about baking these kinds of feature as part of the charting component? 
Or maybe even a hooks library that can include features like responsive charts and bar width calculation?

**Comment by alfredvaa** [comment]
@boygirl If you set total number of bars in your example to lower than 5 you get a little bit of overflow to the left, over the y-axis. Why is that? Above 5 it seems to work as expected.
