### ISSUE TITLE
Victory-Histogram upgrade of d3-array

### ISSUE THREAD

**Issue by Radix-Technos** [FormidableLabs/victory#1877]
# Bugs and Questions

### Checklist

- [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

After d3-array upgrade to 3.x.x version, when it build on Android it crash.
We opened a issue on Victory-Native here:
https://github.com/FormidableLabs/victory-native/issues/653

But I think the solution come from here, because Victory-Histogram need be upgrade to new form usage of d3-array thats was relesed 3 days ago.

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Upgrade Victory-Histogram to version 3 of d3-array.

**Comment by ryan-roemer** [comment]
https://unpkg.com/browse/d3-array@3.0.1/dist/d3-array.js still has the code that is going break current babel.

```
function cumsum(values, valueof) {
  var sum = 0, index = 0;
  return Float64Array.from(values, valueof === undefined
    ? v => (sum += +v || 0)
    : v => (sum += +valueof(v, index++, values) || 0));
}
```

I think the options are:

1. Downgrade `d3-array` to something before this particular function was introduced and make sure Victory correctly integrates with the old version.
2. Users look for options to skip parsing `d3-array` in babel/webpack/whatever configs until upstream babel fixes the parser bugs

Parser bug refs:
- https://github.com/babel/babel/issues/11038
- https://github.com/babel/babel/issues/7235

**Comment by boygirl** [comment]
@Radix-Technos I don't believe _upgrading_ `d3-array` is the solution. After looking at the recent d3-array issues, if anything I need to _downgrade_ `d3-array`. Let me investigate further.
