### ISSUE TITLE
Feature Req: Hiding ranges of dates on an AreaChart

### ISSUE THREAD

**Issue by svenlombaert** [FormidableLabs/victory#1879]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Hi there!
We've been using victory for quite a while now at Delta, with success. We have one crucial feature missing and we wonder how hard this would be to implement: 

We'd like to hide certain date ranges on an area chart and haven't found a way to successfully do this. Reason being is that we render area charts for stock prices, and the stock market is closed in weekends. We'd like to hide weekends (and other closing dates) from the chart. Currently, when passing null values for those weekends, victory just draws a flat line for those timestamps, but this is not really expected when drawing a price chart for a stock ticker. This screenshot of trading view should illustrate what we're trying to achieve:

![Screenshot 2021-06-14 at 11 38 29](https://user-images.githubusercontent.com/2846986/121871985-0ce81900-cd05-11eb-9f41-f5cbdcd300cf.png)

You can see that 5 and 6 June are hidden and the chart and this is what we would like to achieve with victory(-native) as well.

So, is this something rather simple achievable? If so, if someone could point us in the right direction where to start, we're willing to invest some of our engineering capacity into this.

**Comment by boygirl** [comment]
Hi @svenlombaert! I'm glad Victory is working well for you! It sounds like what you would need would be a discontinuous domain. This isn't a concept that Victory handles currently, and it isn't something the underlying `d3-scale` logic that Victory uses really handles out of the box either. We could experiment with adding ore replicating funcationality from a library like [this one](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-discontinuous-scale/README.md) to alter the domains / scales we're using from d3. I would want to experiment a bit to see how invasive that might be with the rest of the api. 

Alternately, if your data points are approximately evenly spaced on weekdays, you could try filtering out all your weekends, and then converting your data to strings rather than date objects, and plotting the whole chart on a linear scale instead of a time scale. You would need to do some custom `tickValue` and `tickFormat` handling on your x axis if you went this route, but your weekend discontinuities would be removed as you expect.

**Comment by svenlombaert** [comment]
> Alternately, if your data points are approximately evenly spaced on weekdays, you could try filtering out all your weekends, and then converting your data to strings rather than date objects, and plotting the whole chart on a linear scale instead of a time scale. You would need to do some custom `tickValue` and `tickFormat` handling on your x axis if you went this route, but your weekend discontinuities would be removed as you expect.

We've been using this approach successfully up til now, cause indeed our datapoints are evenly spaced and converting the timestamps to strings worked beautifully. But, for a new feature we want to build we need to show points on more random timestamps (so not evenly spaced anymore) which of course skews the chart.

The discontinious domain seems indeed like the solution we'd need. Let me know if we can be of any help.

**Comment by beccanelson** [comment]
Right now we are providing a way to choose between a few different d3 scales (linear, time, log, or sqrt). However, it sounds like we might also want to provide a way to pass a custom scale function in as a prop, such as the discontinuity scale plugin that @boygirl mentioned above. Here's a quick demo of how you would build a discontinuous time scale in case you're curious. https://codesandbox.io/s/discontinuous-scale-demo-f1f19

If this sounds like a good solution, we can get to work on providing you this prop, and I will post any updates here. Thanks for the suggestion!

**Comment by svenlombaert** [comment]
> Right now we are providing a way to choose between a few different d3 scales (linear, time, log, or sqrt) or pass in a custom scale function. I'm not sure whether this is documented currently, but you might be able to use this discontinuous scale plugin that @boygirl mentioned above to create your own scale and pass it in.
> 
> Here's a quick demo of how you might do this. https://codesandbox.io/s/victory-discontinuous-scale-demo-9014g
> 
> ```js
> export default function App() {
>   const data = [
>    ...
>   ];
> 
>   const discontinuousScale = scaleDiscontinuous(
>     d3Scale.scaleTime()
>   ).discontinuityProvider(discontinuitySkipWeekends());
> 
>   return (
>     <VictoryChart scale={{ x: discontinuousScale }}>
>       <VictoryLine data={data}></VictoryLine>
>     </VictoryChart>
>   );
> }
> ```
> 
> This demo is assuming that all weekends have already been filtered from the data, but it allows you to still use `d3.scaleTime` rather than using strings.
> 
> @svenlombaert Do you think a solution like this would work for you, or is there more functionality that we can help you implement?

This really looks like what we're aiming for, I can get back to you once I've fiddled around with it. There's more dates than just weekends to be filtered out (other closing dates, like national holidays), but I guess we could write our own discontinuity provider for that. Thanks a lot for the example!

**Comment by svenlombaert** [comment]
@beccanelson Finally got to trying this out! Everything seems to work well, but I have a question. How come there's a difference between using the `discontinuitySkipWeekends` and manually filtering the weekends using `discontinuityRange()`?

You can see it when switching between the first and second scale:
https://codesandbox.io/s/victory-discontinuous-scale-demo-forked-zuzhx?file=/src/App.js
