### ISSUE TITLE
how to create a custom delimiter line in VictoryLine

### ISSUE THREAD

**Issue by franjorub** [FormidableLabs/victory#1884]
# Bugs and Questions

### Checklist

- [x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x] I am using the latest version of Victory

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

Hi we are migrating some charts to Victory and there is a feature that we need to keep and  it is to create custom ranges in the chart, for example: 

![image](https://user-images.githubusercontent.com/24401350/122664327-bd737400-d16e-11eb-9dea-217b5a2367b1.png)

are there some examples of how to do this?

I was thinking of something like a second Victory line with only that point? if there is a more easy way to do it directly on the chart could be awesome.

also could be helpful if the area between the delimiter and some point could be filled with a color.

thanks for your time

**Comment by boygirl** [comment]
@franjorub Thanks for trying Victory!

You can do something like that by using `VictoryLine` or `VictoryArea` and plotting a function rather than providing data. To match the example above, you would do something like
```
<VictoryLine y={() => 5.5} />
```

Here's a codesandbox example that should help:
https://codesandbox.io/s/chart-annotations-v3lbz?file=/index.js

and a bit more information about annotations in general:
https://formidable.com/open-source/victory/docs/faq/#annotations

**Comment by franjorub** [comment]
hi @boygirl thank you for your quick response! I was able to make what I need 

![image](https://user-images.githubusercontent.com/24401350/122804332-cb6fe480-d295-11eb-8a39-1d1928b45f72.png)

just a couple questions: 

- how can I change the line style to dashed for example
- how can I target only the axis label from the horizontal line, like for example apply custom styles 

thank you !

**Comment by boygirl** [comment]
@franjorub I made a couple additions to my example that should help: https://codesandbox.io/s/overlapping-annotations-ticklabel-styles-tz1r9

**Comment by franjorub** [comment]
hi @boygirl yes ! that exactly what I made, overlapping the filling with a white background 

just to end, it's supported to style using something like a custom render function to only customize the axis label at the line?


eg 
![image](https://user-images.githubusercontent.com/24401350/122858705-b40e1700-d2e8-11eb-9d09-b45e5e718ad2.png)

thanks a lot for your patience and time
