### ISSUE TITLE
victoryPie stroke not work

### ISSUE THREAD

**Issue by 271915902** [FormidableLabs/victory#1885]
_here is my ### code_

 <VictoryPie
          standalone={false}
          innerRadius={75}
          data={props.initDataSource}
          x="son"
          y="value"
          startAngle={175}
          endAngle={580}
          style={{
            data: {
              stroke: "#40A9FF",
              fill: "white",
            },
          }}
          labelPosition={"centroid"}
          labelRadius={95}
          events={[
            {
              target: "data",
              eventHandlers: {
                onPressIn: () => {
                  console.log(props.tabindex)
                  return [
                    {
                      eventKey: "all",
                      mutation: ({style}) => ({style: { fill: "white",stroke:"#40A9FF",} })
                    },
                    {
                      mutation: ({style}) => ({style: {fill:"#40A9FF",stroke:"#40A9FF", } })
                    }
                  ];
                }
              }
            }
          ]}
        />

>

**Comment by boygirl** [comment]
@271915902 I wasn't able to reproduce your issue. I made a modified version of the code you show in codesandbox:
https://codesandbox.io/s/issue-1885-st11j?file=/index.js  Can you modify it so that it demonstrates your issue?

**Comment by 271915902** [comment]
> @271915902 I wasn't able to reproduce your issue. I made a modified version of the code you show in codesandbox:
> https://codesandbox.io/s/issue-1885-st11j?file=/index.js Can you modify it so that it demonstrates your issue?

Sorry I fotgot to tell that I use React-native,in web this example looks like no problem,Will there be any difference between the web and Android

And I should show all my code
import React, { useState, useEffect } from "react";
import { StyleSheet, View, Text } from "react-native";
import {
  VictoryPie,
} from "victory-native";
import Svg from "react-native-svg";
const data = [
  { label: "L", value: 1, color: "#d9d9d9" },
  { label: 1, value: 1, son: [], color: "white" },
  { label: 2, value: 1, son: [], color: "white" },
  { label: 3, value: 1, son: [], color: "white" },
  { label: 4, value: 1, son: [], color: "white" },
  { label: 5, value: 1, son: [], color: "white" },
  { label: 6, value: 1, son: [], color: "white" },
  { label: 7, value: 1, son: [], color: "white" },
  { label: 8, value: 1, son: [], color: "white" },
  { label: 9, value: 1, son: [], color: "white" },
  { label: 10, value: 1, son: [], color: "white" },
  { label: 11, value: 1, son: [], color: "white" },
  { label: 12, value: 1, son: [], color: "white" },
  { label: 13, value: 1, son: [], color: "white" },
  { label: 14, value: 1, son: [], color: "white" },
  { label: 15, value: 1, son: [], color: "white" },
  { label: 16, value: 1, son: [], color: "white" },
  { label: 17, value: 1, son: [], color: "white" },
  { label: 18, value: 1, son: [], color: "white" },
  { label: 19, value: 1, son: [], color: "white" },
  { label: 20, value: 1, son: [], color: "white" },
  { label: 21, value: 1, son: [], color: "white" },
  { label: 22, value: 1, son: [], color: "white" },
  { label: 23, value: 1, son: [], color: "white" },
  { label: 24, value: 1, son: [], color: "white" },
  { label: 25, value: 1, son: [], color: "white" },
  { label: 26, value: 1, son: [], color: "white" },
  { label: 27, value: 1, son: [], color: "white" },
  { label: 28, value: 1, son: [], color: "white" },
];

function Panel(props) {
  const [slot, setSlot] = useState();
  const { addCell1,tabindex} = props;
  useEffect(() => {
    props.initDataSource1(data);
  }, []);
  return (
    <View>
      <Svg width={400} height={350}>
        <VictoryPie
          standalone={false}
          innerRadius={75}
          data={props.initDataSource}
          x="son"
          y="value"
          startAngle={175}
          endAngle={580}
          style={{
            data: {
              stroke: "#40A9FF",
              fill: "white",
            },
          }}
          labelPosition={"centroid"}
          labelRadius={95}
          events={[
            {
              target: "data",
              eventHandlers: {
                onPressIn: (props) => {
                  return [
                    {
                      eventKey: "all",
                      mutation: (props) => {
                        return { style: { stroke: "#40A9FF", fill: "white" } };
                      },
                    },
                    {
                      mutation: ({ datum }) => 
                        return {
                          style: { stroke: "#40A9FF", fill: "#40A9FF" },
                        };
                      },
                    },
                  ];
                },
              },
            },
          ]}
        />
      </Svg>

    </View>
  );
}

**Comment by boygirl** [comment]
@271915902 are your event handlers definitely firing? There should be no difference in how the event system applies mutations between Victory and Victory Native. What version are you using?

**Comment by 271915902** [comment]
> @271915902 are your event handlers definitely firing? There should be no difference in how the event system applies mutations between Victory and Victory Native. What version are you using?
hi,I try to console.log(style) in mutation({style}) and the stroke has been changed but in my phone it not works
    "expo": "~41.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "victory-native": "^35.3.3"
