### ISSUE TITLE
How two align in different positions two labels in a VictoryLine

### ISSUE THREAD

**Issue by franjorub** [FormidableLabs/victory#1895]
Hi I would like to do something like this 

![image](https://user-images.githubusercontent.com/24401350/124522288-bd0ae800-ddc0-11eb-877a-f336067758a7.png)

following the docs you can pass an array in the labels prop to a VictoryLine but I don't see how I could set independent positions

```jsx
<VictoryLine
    style={{ data: { stroke: "blue", strokeWidth: 3 } }}
    y={() => 0.7} // dummy number
    labels={["text1", "text2"]} // how to set text1 on the left and text2 on the right
  />
```

also, it's possible to apply different styles to each one? one solution that I can think of is to render twice the same VictoryLine but with different anchors but if there is a better solution I would like to know thanks.

**Comment by boygirl** [comment]
@franjorub what about using `VictoryLabel` independently of `VictoryLine` for your annotations?

Something like this example:
https://codesandbox.io/s/victorylabel-annotations-pxcxf?file=/index.js
