### ISSUE TITLE
How to overlap/show Victory Pie labels beyond the Container class

### ISSUE THREAD

**Issue by jontycool** [FormidableLabs/victory#1898]
# Question

### The Problem

![image](https://user-images.githubusercontent.com/8183283/125330704-b6521700-e364-11eb-8ac9-d40d49d2a89b.png)

### Description

As seen in the image above, my Victory Pie labels are not fitting in the container class. Is there any method by which we can display the labels beyond the container class ?

### Code I am using

```javascript
<VictoryPie
  data={pieData}
  style={{
    labels: {
      fontWeight: 700,
      fill: ({ data, index }: any) =>
        index === 0 ? '#3FB87C' : index === 1 ? '#E50000' : '#265886',
    },
  }}
  innerRadius={95}
  padAngle={2}
  colorScale={['#3FB87C', '#E50000', '#265886']}
/>

**Comment by tgalfin** [comment]
@jontycool, While not technically extending labels beyond the container, there is a pretty straightforward workaround that will achieve the same result visually. Pad the chart so the labels fit, then put the chart inside another container and use absolute positioning to get the total time taken box closer to your pie than the edge of the actual chart container:

![image](https://user-images.githubusercontent.com/79439202/134992554-cf5d3678-637d-472f-9f96-7e3f49993dda.png)
![image](https://user-images.githubusercontent.com/79439202/134992491-6ed9bc09-a34a-42fe-b343-64555c755380.png)
