### ISSUE TITLE
Can gradients be added to grid lines?

### ISSUE THREAD

**Issue by colin-young** [FormidableLabs/victory#1899]
See https://codepen.io/colin_young/pen/bGqXeqP. If lines 22 and 23 of the JS are modified, you will see the grid lines are not rendered, at least on Safari and Chrome on MacOS. The gradient appears on the graph line, just not for the grid. If I attempt to use a gradient on the horizontal grid lines, I do not see them rendered at all.

Should I be able to create grid lines with a gradient? If so, is there an example available?

**Comment by beccanelson** [comment]
You might not be able to add a gradient via the style props, but you can customize the grid lines by using the `gridComponent` prop on victory axis. For example, you could create a line with a linear gradient:

```jsx
function GradientLine(props) {
  return (
    <g>
      <defs>
          <linearGradient id="Gradient1">
            <stop stopColor="black" offset="0%"/>
            <stop stopColor="white" offset="100%"/>
          </linearGradient>
      </defs>

      <line {...props} fill={url(#Gradient1)} />
    <g>
  );
}


```
And then plug it in like this:
```jsx
<VictoryAxis gridComponent={<LineSegment lineComponent={<GradientLine />} />} />
```

I'll close this issue for now, but let me know if this solution will work for you! Perhaps we can add an example to the gallery as well.
