### ISSUE TITLE
Is it possible to wrap each VictoryBar with the container?

### ISSUE THREAD

**Issue by alexfrize** [FormidableLabs/victory#1904]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Is it possible to wrap each VictoryBar with the container?

Code: https://codesandbox.io/s/funny-cloud-gyt8i

Now I have:
![image](https://user-images.githubusercontent.com/22485563/126348316-59ad8efe-5db2-4f5d-b5af-4b32706b201c.png)

But how can I do something like this:
![image](https://user-images.githubusercontent.com/22485563/126348424-22625924-1c18-402c-9de0-2f9c85cbe6b6.png)

I also asked this question on a StackOverflow:
https://stackoverflow.com/questions/68448226/how-to-wrap-victorybar-with-the-container
and it looks like many people also have this question as well.

### Reproduction

Code: https://codesandbox.io/s/funny-cloud-gyt8i

# Feature Requests
Maybe it is a feature request. Who knows :)

Waiting for your response. And thank you for the amazing library!

**Comment by boygirl** [comment]
You could create custom bars and plot them with your others like so: 

https://codesandbox.io/s/polished-water-5p5zq?file=/index.js
