### ISSUE TITLE
Y-axis labels should go higher than the data's y-values

### ISSUE THREAD

**Issue by christinegaribian** [FormidableLabs/victory#1905]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The y-axis labels don't go up high enough for a VictoryGroup with a few VictoryBars. The maximum labeled y-axis value is always lower than the maximum y-value of the data, even in the documentation's similar example. I want y-axis values to go above the data, and this seems like it should be the default behavior of the chart as well. I tried adding a constant domainPadding to the y-axis, but this doesn't consistently solve the problem, I think because domainPadding is specified in pixels and the range on different graphs can really vary. 

<img width="583" alt="Screen Shot 2021-07-12 at 12 47 18 PM" src="https://user-images.githubusercontent.com/8163206/126374851-dbbce429-dc1c-4492-b4c2-8c56a9da0b46.png">

### Reproduction

This example in the documentation: https://formidable.com/open-source/victory/docs/victory-group/#victorygroup

# Feature Requests

Maybe this is more feature request than bug. Also, thanks for this awesome library!

**Comment by boygirl** [comment]
Hi @christinegaribian! Thanks for this issue. The expected behavior is the the y domain to _exactly_ match the highest y data value unless an explicit `domain`, `maxDomain` or `domainPadding` is specified. I believe the expected beharior is correct as a default for most folks. If it's possible to know your highest data value, you might have better luck with the `maxDomain` prop if the pixel-based domain padding is not serving your needs.

**Comment by christinegaribian** [comment]
Hi @boygirl thanks for the response! The domain indeed matches, but the labels do not. Let me try to rephrase - I expect the highest labeled numbered on the y-axis to be greater than or equal to the highest y data value, which is not the case. For example, in [this example in the documentation](https://formidable.com/open-source/victory/docs/victory-group/#victorygroup), the highest y-value is 9, while the highest y-axis label is 8 (not 9). Ideally, the y-axis labels should go up to at least 9

**Comment by boygirl** [comment]
Ah! I see what you mean. Victory relies on `d3-scale` to provide default `tickValues` for axes when `tickValues` are not user provided. It optimizes for nice, evenly spaced values. You can read more about how ticks are calculated by d3 here: https://github.com/d3/d3-scale#continuous_ticks

If you'd like more control over how your ticks are displayed in Victory, check out the `tickValues` and `tickFormat` documentation here:

https://formidable.com/open-source/victory/docs/victory-axis#tickvalues
https://formidable.com/open-source/victory/docs/victory-axis#tickformat

**Comment by christinegaribian** [comment]
Great, this answers my question. Thanks for the resources!

**Comment by SaeedZhiany** [comment]
@boygirl and @christinegaribian 

I realized that if we pass some tick values higher that the highest data value, victory will skip them and not show them. no matter if they are generated by d3-scale or by a manual const array of values.

for example I'm passing `tickValues={[0, 10, 20, 30, 40]}` to my chart and here is the result:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/13766432/161050058-51ef7fdf-b102-4325-bfae-952d4f5041f9.png">

and if I pass `tickValues={[0, 10, 20, 30, 36]}`
<img width="269" alt="image" src="https://user-images.githubusercontent.com/13766432/161051994-baaf0767-f392-4ef9-88ee-46fe5500a645.png">

please note that my data is dynamic and I'm not using const tick values in my chart. I just want to report Victory's problem and ask you to reopen this issue. maybe another solution/logic is needed to get better tick values automatically.

I'm using victory-native for my react-native project and [highcharts](https://www.highcharts.com/) for my web application. as you can see in the picture below, highcharts could generate the tick values as the way @christinegaribian said and it's not needed for my help to generate the values. as Highcharts is a open-source project, maybe worths to checkout its logic to get an idea to improve victory tick value logic.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/13766432/161050995-ce3e3f71-1258-4a6d-b0a9-1e0a79576de2.png">

**Comment by SaeedZhiany** [comment]
Hi @boygirl and @christinegaribian 

I realized that if we pass some tick values higher that the highest data value, victory will skip them and not show them. no matter if they are generated by d3-scale or by a manual const array of values.

for example I'm passing `tickValues={[0, 10, 20, 30, 40]}` to my chart and here is the result:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/13766432/161050058-51ef7fdf-b102-4325-bfae-952d4f5041f9.png">

and if I pass `tickValues={[0, 10, 20, 30, 36]}`
<img width="269" alt="image" src="https://user-images.githubusercontent.com/13766432/161051994-baaf0767-f392-4ef9-88ee-46fe5500a645.png">

please note that my data is dynamic and I'm not using const tick values in my chart. I just want to report Victory's problem and ask you to reopen this issue. maybe another solution/logic is needed to get better tick values automatically.

I'm using victory-native for my react-native project and [highcharts](https://www.highcharts.com/) for my web application. as you can see in the picture below, highcharts could generate the tick values as the way @christinegaribian said and it's not needed for my help to generate the values. as Highcharts is a open-source project, maybe worths to checkout its logic to get an idea to improve victory tick value logic.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/13766432/161050995-ce3e3f71-1258-4a6d-b0a9-1e0a79576de2.png">

**Comment by SaeedZhiany** [comment]
@boygirl please reopen this issue.

**Comment by SaeedZhiany** [comment]
@becca-bailey or @boygirl please reopen this issue.
