### ISSUE TITLE
Using VictoryPortal with tooltips: tooltips events are not working or tooltips are overlapped by the axis

### ISSUE THREAD

**Issue by alexfrize** [FormidableLabs/victory#1906]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Example: https://codesandbox.io/s/eloquent-hofstadter-zsns4

If I use VictoryPortal, it shows the tooltip properly but I don't have an access to any tooltip events.
If I don't wrap tooltip with VictoryPortal, events are firing, but the tooltip is overlapped with VictoryAxis.

Also opened on StackOverflow: https://stackoverflow.com/questions/68460100/using-victoryportal-with-tooltips-tooltips-events-are-not-working-or-tooltips-a

### Reproduction
https://codesandbox.io/s/eloquent-hofstadter-zsns4

**Comment by boygirl** [comment]
@alexfrize Thanks for the reproduction. That's really helpful. I'd bet that there is an event bubbling issue, with your mouse event being captured somewhere and never making it to your link when you're rendering in the portal. I'll take a closer look.

**Comment by boygirl** [comment]
Sure enough! `VictoryContainer` uses `div` elements alongside `svg` to give users some rudimentary z-index contol at the chart level. These `div`s all have `pointerEvents: "none"` to keep them from swallowing events indended for the svgs. In your case, the `div` in your tooltip that contains your link is inheriting that style. I think your problem will be solved if you add `pointerEvents: "auto"` to the styles on that `div`.
