### ISSUE TITLE
Cannot read property 'barWidth' of undefined

### ISSUE THREAD

**Issue by WaysToGo** [FormidableLabs/victory#1911]
The same component was working fine before 

steps to repo
 here in the example we have two buttons when we are changing the second button then the component works fine but when first button is clicked then we are getting barWidth issue 
 sandbox link : https://codesandbox.io/s/gifted-panini-htwv7?file=/src/App.js

**Comment by boygirl** [comment]
Funny timing! I just opened a PR around this: https://github.com/FormidableLabs/victory/pull/1908. I'll get it merged and released as a patch version today

**Comment by WaysToGo** [comment]
Raised issue after seeing your the PR 😄

**Comment by boygirl** [comment]
The fix is released in `v35.9.2`. Please let me know if you're still having problems after upgrading.

**Comment by WaysToGo** [comment]
<img width="493" alt="Screenshot 2021-07-23 at 10 11 47 AM" src="https://user-images.githubusercontent.com/17769286/126738188-caa14268-cf19-42a9-b922-b1f9cf499aa1.png">
Still facing similar  issue
