### ISSUE TITLE
Add react version as a dependency for usage with ModuleFederation

### ISSUE THREAD

**Issue by llcro** [FormidableLabs/victory#1914]
Evaluating the library for use in a federated platform and found that the package will throw a warning when used in conjunction with ModuleFederation due to no react version being specified for each of the dependent packages.

It would be beneficial for users to enable this as a dependency or peerDep at minimum.

**Comment by ryan-roemer** [comment]
@boygirl @beccanelson --  After reviewing our past history of keeping `react` out of `peerDependencies`, I think it's fine to finally move it in with our current infrastructure and build scenarios, if y'all want. 

If we do go down that road, we should review our UMD build external declaration https://github.com/FormidableLabs/victory/blob/42fe713c9fb09214a2a105bc786d568b05fc68ec/config/webpack/webpack.config.js#L31-L40 and see if we also want to keep that as an external (and I think the answer is probably "yes" in that bundling it might lead app users to have multiple versions of react...)

**Comment by boygirl** [comment]
@ryan-roemer agreed. I don't want react as an actual dependency, but I don't have objections to making it a peer dep.
