### ISSUE TITLE
VictoryVoronaiContainer does not allow opting out of bounds checking on mouse / touch move

### ISSUE THREAD

**Issue by samwilkins333** [FormidableLabs/victory#1916]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I think it would be helpful to be able to optionally disable bounds checking (via a prop) for the onMouseMove and onTouchMove events for VictoryVoronaiContainer.

The proposed change is short, and my description may be too long :)

As a preface: I've encountered this issue in a victory-native project and will follow up with an associated issue there if this seems reasonable (i.e. there's no easy workaround I'm missing), but because that functionality is just a slight alteration of this repository and directly imports voronai-helpers.js where one of the small changes in question would be implemented, I figured I would start here. If not, I'd be happy to move the issue to victory-native, though I do think there would need to be a small edit here as well.

For my particular application of the library, when touchMove'ing across the VictoryVoronaiContainer, I would like for the closest-data-point activation behavior to continue even when the user's finger leaves the container's bounds (implementing a Robinhood-style stock graph scrubber, if that helps to visualize the interaction). Currently, no data points or labels are activated if the touchMove event leaves the container's bounds, due to the checking of `this.withinBounds` in `onMouseMove` in voronai-helpers.js, which leads to an abrupt end behavior / unnecessary precision required when the user is scrubbing.

I would propose an optional boolean prop of VictoryVoronaiContainer passed into the onMouseMove helper that allows the disabling of bounds checking to support this use case. The default value would be false, to ensure bounds checking is enabled by default. I have proposals of the few changes implemented in forks of victory and victory-native, so I can make parallel pull requests at any point if this all seems reasonable.

### Reproduction

Because this is from a react-native context, and not really a bug but more of a behavior choice in only a few known files, I believe / hope the description is sufficient. But, if that is not the case, I'd be happy to try and build something out.

**Comment by TheTalonHughes** [comment]
@samwilkins333 If I understand your description correctly, I also could use this. I am trying to select a bar on my bar graph after removing the finger from the graph. Is that what you are talking about? I'd love to see you build something out as a concept 🙏🏼
