### ISSUE TITLE
Warning: Failed prop type: Invalid prop `events[0].eventKey` supplied to `VictoryPie`

### ISSUE THREAD

**Issue by AScholan** [FormidableLabs/victory#1923]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am seeing the following warning when I am setting the eventKey value for events relating to VictoryPie:
> Warning: Failed prop type: Invalid prop `events[0].eventKey` supplied to `VictoryPie`.
>     at addEvents (https://x6s4l.csb.app/node_modules/victory-core/es/victory-util/add-events.js:109:7)
>     at CircularSegmentInput (https://x6s4l.csb.app/src/circular-segment-input.js:63:3)
>     at StatisticsPage (https://x6s4l.csb.app/src/statistics-page.js:27:41)
>     at div
>     at App
> 

### What I am doing

I have created a circular input control with a number of segments. 
- Each segment can either be selectable or not.
- Selectable segments can either be normal, or show an issue.
- One selectable segment can be active.

I have attached the following events:
- onMouseOver, onMouseOut: These change the hover color for the segment when the mouse is over the segment. They also change the style of the cursor in the _parent_ object so that selectable entries have the pointer cursor.
- onClick: Used to change the active element.

Because I couldn't find appropriate props information to handle the cursor change in the parent, I used the _eventKey_ property of the events object to attach the event only to selectable segments. **This works** but gives the above warning. I have specified the eventKey property correctly, I believe, as a list of indexes for the event to be applied. 

### Reproduction

Please see the following sandbox: https://codesandbox.io/s/victory-pie-eventkey-warning-reproduction-x6s4l

The code sandbox runs correctly with correct behaviour for the controls but shows the warning in the console.

**Comment by beccanelson** [comment]
Sounds like a prop types warning - this should prevent the code from running, but should be a quick fix to update the prop types here.

**Comment by AScholan** [comment]
BTW this is the first time I'm using Victory and chose it over other React charting libraries (ReCharts was other final contender) because of the much better standard of documentation for Victory and the more flexible event system. 
**Well done to the team for this professional library.**
