### ISSUE TITLE
Custom labelComponent in VictoryGroup

### ISSUE THREAD

**Issue by WoSchmo** [FormidableLabs/victory#1924]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a VictoryChart with VictoryBars inside of a VictoryGroup with a custom labelComponent which contains a VictoryTooltip (see Reproduction).

The problem is, that despite using a VictoryVoronoiContainer, the Tooltip is not visible/not set to active, when the mouse is over the Bar. With VictoryTooltip as labelComponent, it works as expected, also when the bars are not within a VictoryGroup.

Am I doing something wrong?

### Reproduction

See the [Sandbox](https://codesandbox.io/s/icy-darkness-vx09j).

**Comment by beccanelson** [comment]
Hi @WoSchmo, you should be able to fix this by moving the `containerComponent` prop up to the `VictoryChart`. Let me know if this helps! https://codesandbox.io/s/frosty-dubinsky-nk69e?file=/index.js

**Comment by WoSchmo** [comment]
Thank you for the suggestion, but it doesn't work as expected.

If the VoronoiContainer doesn't have any props set, the Tooltips seem to be shown by the y-position. Try moving the mouse on the second bar up and down and you'll see what I mean.

If I set voronoiDimension="x" all tooltips for every bar of the group are shown.
