### ISSUE TITLE
Update VictoryGroup so it is not re-calculating props each time its children change

### ISSUE THREAD

**Issue by beccanelson** [FormidableLabs/victory#1927]
Right now, `VictoryGroup` is rerendering and recalculating its props each time it's children change, which adds around 200ms to each render cycle when there is some interaction. If I change the return value of `shouldComponentUpdate` to false after the initial render, this cuts out this render cycle (while still updating the child components). We can either update `shouldComponentUpdate` with a different conditional, or refactor this component to use memoization. 

<img width="1437" alt="Screen Shot 2021-08-05 at 6 24 07 PM" src="https://user-images.githubusercontent.com/13334214/128429431-a2da118a-63fc-463f-bd82-151d6a4daf84.png">

**Comment by olcayertas** [comment]
Does this also happen with `VictoryChart`? I have 250 data points and the performance is terrible when I interact with the chart.

```
<VictoryChart
  width={width}
  padding={padding}
  minDomain={{ y: 70 }}
  maxDomain={{ y: dataSet.maxDomain }}
  containerComponent={ChartContainer({})}
>
  <GradientFill color={fillColor} id={'chart1'} />
  {ChartAxis({})}
  <VictoryArea animate={areaAnimation} style={areaStyle} data={data} x={'date'} y={'close'} />
  <VictoryBar animate={barAnimation} data={data} x={'date'} y={(d) => (Math.log2(d.volume) - dataSet.minDomain) * 3 + 55} />
</VictoryChart>
```

**Comment by beccanelson** [comment]
@olcayertas It's definitely possible! In most use cases I haven't seen a lot of re-rendering in VictoryChart (it's mostly in VictorySharedEvents and VictoryGroup), but I still have a bit of work to do investigating cases where there are animation props.  I will look into this a little more as well.
