### ISSUE TITLE
Using functional componenet wrappers for customization

### ISSUE THREAD

**Issue by olcayertas** [FormidableLabs/victory#1929]
### The Problem

Wrapping components with functional components and use them as inline JSX doesn't work.

### Reproduction

Please check this sandbox:

https://codesandbox.io/embed/wizardly-austin-lzftu?fontsize=14&hidenavigation=1&theme=dark

The chart is rendering but selection and labels doesn't work.

If you change the chart.tsx line 37

`
const container = <ChartContainer />;`

to

`const container = ChartContainer({});`

it will work.

**Comment by beccanelson** [comment]
Hi @olcayertas, do you mind also including a sandbox link with the expected behavior? I tried swapping out the line you included in the issue, but I'm still not seeing the expected behavior you described. As far as I know, there shouldn't be any difference between functional and class-based custom components, but there might be something weird going on here that I'm not aware of.

**Comment by olcayertas** [comment]
Expected behavior is showing labels for data and showing axis. Here is the sandbox link:

https://codesandbox.io/s/dank-tdd-8qhk3?file=/src/chart/chart.tsx

**Comment by olcayertas** [comment]
@beccanelson I have also getting these errors for my chart:

- Warning: Received `false` for a non-boolean attribute `standalone`.

- Warning: React does not recognize the `stringMap` prop on a DOM element.

You can check them in sandbox console.

**Comment by boygirl** [comment]
@olcayertas `VictoryChart` clones all its child elements and provides additional props. This is typically useful, as it gives chart children access to things like a shared `scale` and `domain`. Unfortunately, it can result in some unwanted props getting added to your child elements. You can get around this by having your functional wrappers render specific children that  are specific about how they use the props that will be provided to them. So, to re-work the example you provide:

```
const GradientFill = props => (
  <defs>
    <linearGradient id={props.id} x1="100%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stopColor={props.color}/>
      <stop offset="100%" stopColor="#FFFFFFFF"/>
    </linearGradient>
  </defs>
);

const createGradientFill = (color: string, id: string) => (
  <GradientFill color={color} id={id} />
);
```

**Comment by becca-bailey** [comment]
I think this is related to #1758. This will also be addressed once we re-work the way child components receive props and state in #2076. I know this isn't ideal right now, so stay tuned for updates! I'm going to close this issue for now and move discussion about component props to 2076.
