### ISSUE TITLE
How to add roles? It is the best way? (see example)

### ISSUE THREAD

**Issue by alexfrize** [FormidableLabs/victory#1935]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Need a piece of advice.
I tried to add roles to my components. Just wanted to ask if there is any "best" way to do it?
https://codesandbox.io/s/winter-moon-2wwqz

My code does not seem to be working properly, because as I know in this case uses should be able to navigate the menu items in the example above by using arrow keys.

### Reproduction
https://codesandbox.io/s/winter-moon-2wwqz

**Comment by beccanelson** [comment]
Hi @alexfrize ! In your example, the `Bar` component renders a path component under the hood, but it only passes the expected props through to the path component, which doesn't currently include `role`. You can add other props to the path by using a `pathComponent` prop like this:
```
<Bar 
  pathComponent={<path role="menuitem"/>}
/>
```

**Comment by becca-bailey** [comment]
Hi @alexfrize, sorry it has taken a while for us to respond to this issue! We are currently working on some work around accessibility props, and we may be able to include the `role` prop in this work. CC: @dlcartright

**Comment by becca-bailey** [comment]
As a temporary workaround, you can use custom components to inject your own data component with a `role` prop rather than passing that prop into Victory.

**Comment by Nagendra88688** [comment]
hey @becca-bailey @dlcartright , can I pick this task?
Please let me know.
