### ISSUE TITLE
Custom Area Chart with selection

### ISSUE THREAD

**Issue by olcayertas** [FormidableLabs/victory#1936]
### Custom Area Chart

We need a custom are chart to apple different styles at different points. Since area chart draws the data as a hole we can not do it now like in selection container example:

```
<VictoryChart containerComponent={<VictorySelectionContainer/>}>
  <VictoryScatter
    style={{ data: { fill: ({ active }) => active ? "tomato" : "gray" } }}
  />
</VictoryChart>

```

What we are trying to do is having same result like above using area chart.
Can anyone give me some hints to where to start?
I am checking custom components documents now.

**Comment by becca-bailey** [comment]
Hi @olcayertas, this should be documented in the Victory docs. If you have further questions, please check to see if there are duplicate discussions, and then open a Q&A discussion thread. Thanks!
