### ISSUE TITLE
Recharts.js

### ISSUE THREAD

**Issue by knowbody** [FormidableLabs/victory#194]
Seems like guys at Recharts are doing great work on the charting in React, maybe it will be worth to join forces, borrow the ideas from each other?

See: https://github.com/recharts/recharts
(@xile611, @arcthur, @evilucifero see what Formidable built so far, it will be great to get your insight here)

**Comment by arcthur** [comment]
Great, victory is similar to idea of recharts. The core of recharts is custom simply for React, so we create more smaller components to combine them, and welcome to borrow each other for better. Thanks.

**Comment by xile611** [comment]
Thanks! I really appreciate your viewpoint, @knowbody .

**Comment by boygirl** [comment]
@arcthur @xile611 this recharts is really beautifully done! I definitely want to borrow and collaborate.

**Comment by typeofgraphic** [comment]
Do either Victory or reCharts apply the Grammar of Graphics in their approaches? This would seem to be the logical way forward and has served ggPlot2 and Tableau very well. I was going to start hacking up a library using React and D3.js to do just this, then saw Victory.js was underway. Thanks @knowbody - I wasn't aware of reCharts before this thread.

For those who may not know, GoG was created by Leland Wilkinson (now VP Stats at Tableau) and used by H. Wickham as the basis of ggPlot2 :http://vita.had.co.nz/papers/layered-grammar.pdf

I am in my 3rd year of a PhD in Visual Analytics and Behaviour, happy to provide info / feedback / resources on this to either reCharts or Victory folk :)
