### ISSUE TITLE
How to use borderRadius inside Victory Legend

### ISSUE THREAD

**Issue by asf89** [FormidableLabs/victory#1942]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

There isn't any specifications of what props I can use to round the border corners of the `VictoryLegend` component. Any help to how to round the corners is appreciated.

**Comment by Wesleyzxc** [comment]
```ts
<VictoryLegend x={125} y={50}
    title="Legend"
    centerTitle
    orientation="horizontal"
    style={ { border: { stroke: "red", rx: "10", ry: "10" } }}
```
You can specify it by passing in `rx` and `ry` on border styles.
