### ISSUE TITLE
Incorrect tickFormats are selected for the selected tickValues

### ISSUE THREAD

**Issue by el-aasi** [FormidableLabs/victory#1944]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When having a secondary axis with `tickValues`, `tickFormat` and `tickCount` it picks several points from the `tickValues` (as expected) but doesn't pick the same/representative `tickFormat` those misrepresenting data. 

In the picture below the top axis ranges from 1 - 13 but instead it shows first formats from the array. 

![image](https://user-images.githubusercontent.com/27493937/130620300-9debe0ca-5d2c-477e-a7ab-3a62f457fe5a.png)

Tick Values and Tick Formats: 

```
tickValues={[
              new Date(Date.parse("2016-06-03T01:15:33")),
              new Date(Date.parse("2016-06-03T01:35:33")),
              new Date(Date.parse("2016-06-03T03:15:33")),
              new Date(Date.parse("2016-06-03T03:35:33")),
              new Date(Date.parse("2016-06-03T04:15:33")),
              new Date(Date.parse("2016-06-03T04:35:33")),
              new Date(Date.parse("2016-06-03T05:15:33")),
              new Date(Date.parse("2016-06-03T05:35:33")),
              new Date(Date.parse("2016-06-03T07:15:33")),
              new Date(Date.parse("2016-06-03T07:35:33")),
              new Date(Date.parse("2016-06-03T07:45:33")),
              new Date(Date.parse("2016-06-03T08:15:33")),
              new Date(Date.parse("2016-06-03T08:35:33"))
            ]}
 tickFormat={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]}
 tickCount={5}
 orientation="top"
```

It looks like it picks the correct values but instead of getting formats with the same index as values it just returns from the beginning of the array. 

### Reproduction

Minimal reproduction [here](https://codesandbox.io/s/add-points-to-a-chart-forked-yj78m?file=/index.js:1736-2656).

**Comment by cjhines** [comment]
Also getting this issue.

With a data array of 7 items the following code is giving totally incorrect indexes.

```
tickFormat={(value, index) => {
  console.log(index);
  return index;
}}
```

Outputs the following:

```
0
1
2
0
1
2
3
4
5
```
