### ISSUE TITLE
custom tooltip in area chart

### ISSUE THREAD

**Issue by saurabh-nayak** [FormidableLabs/victory#1951]
I want to add a custom flyoutComponent using labelComponent attribute that is working perfectly fine in bar chart but for area chart its not working. i have added area chart as below. is there any other way i can do this or i'm doing anything wrong?
<VictoryArea labelComponent={<VictoryTooltip flyoutComponent={<CustomizedDot/>}/>} data={this.state.data}/>

**Comment by becca-bailey** [comment]
Hi @saurabh-nayak, this should be documented in the Victory docs. If you have further questions, please check to see if there are duplicate discussions, and then open a Q&A discussion thread. Thanks!
