### ISSUE TITLE
Render horizontal bars from the top to bottom (change the rendering order)

### ISSUE THREAD

**Issue by alexfrize** [FormidableLabs/victory#1959]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Is it possible to render bars in a different order? I need it to be rendered from the top to bottom.
tabIndex order is incorrect. When the user press the Tab key the lowest bar is highlighted.
I tried sortOrder, but it does not seem to be working properly in my situation and still renders from the bottom to top.

### Reproduction

An example is here: https://codesandbox.io/s/pensive-goodall-g7sty
Press the Tab key to highlight.

**Comment by alexfrize** [comment]
The only solution I found is to sort borders in the opposite direction to data.

Implemented here: https://codesandbox.io/s/focused-cohen-yhhh4

But in this case, borders will have different indexes than data. It is possible to solve it as well and I already did it for my real code, but maybe there is a better and simpler way.

Any advice?

**Comment by carlcodes** [comment]
I am also experiencing this issue - it seems like when the chart is horizontal, it sorts oppositely.

Reproduction - https://codesandbox.io/s/sorting-doesnt-work-horizontally-5fpukm?file=/index.js

I'm thinking I can working around by just doing "ascending" instead of "descending", but this feels broken to me
