### ISSUE TITLE
Include composed example without VictoryChart wrapping in landing page docs

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#196]
The existing example in [`victory-examples`](https://github.com/FormidableLabs/victory-examples/blob/master/demo/app.jsx#L20-L77) is an important piece of documentation, as it shows users how to compose standalone `VictoryLine` and `VictoryAxis` components in an `svg` tag, while maintaining control over domain and scale.

Let's clean up the `victory-examples` repo and add it as a part of `victory.formidable.com` under e.g. "composing charts from standalone components".

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#17
