### ISSUE TITLE
Question - How to show a trailing line in the beginning and end of a line chart.

### ISSUE THREAD

**Issue by vishalsharmaeic** [FormidableLabs/victory#1960]
I tried to dig into documentation to find out if we have any feature but couldn't find that.

Scenario: 

I want to show data points with the x-axis being the date points, lets say our chart is from 1st Aug to 30 Aug, now if we have data before 1st Aug we want to show a trail line indicating that there are previous records to it.  and similarly, if there are records after 30 Aug then we want to show a trailing line after that.. 

Please help if there is a way

**Comment by tgalfin** [comment]
@vishalsharmaeic, if you are still interested in this, can you drop some code for a demo of the base chart you want use, and take a screenshot of the chart and draw over it what you want it to look like?

**Comment by vishalsharmaeic** [comment]
![image](https://user-images.githubusercontent.com/90024694/135031432-0157e3a3-3615-4ccd-abb7-449544fae695.png)

something like this, where users can get informed by a different color-line that there is a date before this.

**Comment by tgalfin** [comment]
There's a pretty straightforward workaround that visually achieves this same result:

![image](https://user-images.githubusercontent.com/79439202/135139887-7fdd8984-8f6c-4f55-beab-943c4f4d015f.png)

You can add VictoryLine components within the chart for the leading and trailing line. It would be nice if you could conditionally style the line based on the individual data points like you can for scatter points, labels, etc, but as far as I can tell this isn't possible. There are other ways to call attention to the end of the line as well: overlay a scatter with a custom point at the ends, 
 label the end points, etc. 

```
<VictoryChart
  theme={VictoryTheme.material}
>
<VictoryAxis 
  dependentAxis 
/>
<VictoryAxis 
    tickValues={[2, 3, 4, 5]} 
/>
  <VictoryLine
  	domain={{x: [1, 6]}}
    style={{
      data: { stroke: "blue" },
      parent: { border: "1px solid #00FF00"}
    }}
    data={[
      { x: 2, y: 3 },
      { x: 3, y: 5 },
      { x: 4, y: 4 },
      { x: 5, y: 7 }
    ]}
  />
    <VictoryLine
    style={{
      data: { stroke: "yellow" },
    }}
    data={[
      { x: 1, y: 2 },
      { x: 2, y: 3 },
    ]}
  />
      <VictoryLine
    style={{
      data: { stroke: "yellow" },
    }}
    data={[
      { x: 5, y: 7 },
      { x: 6, y: 4 },
    ]}
  />
</VictoryChart>
```

**Comment by beccanelson** [comment]
Hi @vishalsharmaeic, did this work for you? If so, I'll close this issue for now!
