### ISSUE TITLE
Question - Is it possible to add multiple y-axes on the same side but do not overlap the chart data area?

### ISSUE THREAD

**Issue by ngmikeng** [FormidableLabs/victory#1968]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm working to build a line chart that supports multiple y axes, I've found the showcase from the documentation of Victory but the y-axis in the middle is overlapping with the chart data.

https://formidable.com/open-source/victory/gallery/multiple-dependent-axes/

Is there a way to style or make it on the leftmost or outside the chart data area like this?

![](https://i.stack.imgur.com/aALF8.jpg)

### Reproduction
The currently sample from Victory: https://jsfiddle.net/ngmikeng/5m73ktja/

**Comment by tgalfin** [comment]
In the fiddle, you will get the desired result if you:
change xOffsets = [100, 50, 300];
set padding={100} on VictoryChart 

![image](https://user-images.githubusercontent.com/79439202/134575900-2e408597-3efb-4376-94ad-83700e0edbbe.png)

You can also adjust padding for individual sides. For example, padding={{left: 100, right: 50, top: 50, bottom: 50 }}. In the padding={100} example, it pads all sides of the chart so it will shrink the whole chart within the container. You may want to pad the left more than the other sides and adjust the offsets accordingly if you want the chart to fill as much of the container as possible.

**Comment by ngmikeng** [comment]
> In the fiddle, you will get the desired result if you:
> change xOffsets = [100, 50, 300];
> set padding={100} on VictoryChart
> 
> ![image](https://user-images.githubusercontent.com/79439202/134575900-2e408597-3efb-4376-94ad-83700e0edbbe.png)
> 
> You can also adjust padding for individual sides. For example, padding={{left: 100, right: 50, top: 50, bottom: 50 }}. In the padding={100} example, it pads all sides of the chart so it will shrink the whole chart within the container. You may want to pad the left more than the other sides and adjust the offsets accordingly if you want the chart to fill as much of the container as possible.

Thank you a lot for pointing out @tgalfin , 
The key property here is the padding of  the VictoryChart component, now I can have the result as expected.
https://jsfiddle.net/ngmikeng/t9sbnye2/
