### ISSUE TITLE
Tooltip appears behind the other VictoryBar in a VictoryGroup

### ISSUE THREAD

**Issue by smithamohannikesh** [FormidableLabs/victory#1969]
# Bugs and Questions
victory tooltip of barchart2 hide behind the bar chart1 how can i solve .my code is below

![simulator_screenshot_9CBF9D7E-9579-4845-A375-A4A10887F15E](https://user-images.githubusercontent.com/17214093/134505223-d120444b-cd5b-45dd-ac37-018c69365727.png)
 <VictoryChart
          width={Dimensions.get("screen").width+10}
          domainPadding={{ x: 30 }}
      
          >
    
  <VictoryAxis
    dependentAxis
    crossAxis={true}
   //domain={[0,1000] }
   // minDomain={{ y: 0 }}
    tickFormat={(t) => (t>=1000)?((t>=100000)?((t>=1000000)?((t>1000000000)?("$"+Math.round(t)/1000000000+"B"):("$"+Math.round(t)/1000000+"M")):("$"+Math.round(t)/100000+"L")):("$"+Math.round(t)/1000+"k")):("$"+Math.round(t))}
   //crossAxis={true}
    style={{
      axis: {stroke: 'transparent'},
      ticks: {stroke: 'transparent'},
      tickLabels: {fontSize:RFPercentage(1.4)},
    }}
  />
  <VictoryAxis
    crossAxis
    style={{
      axis: {stroke: 'transparent'},
      ticks: {stroke: 'transparent'},
      tickLabels: {fontSize:RFPercentage(1.5)},
    }}
  />
            <VictoryGroup
            offset={10}
              
            
            >
           
              <VictoryBar  name="Bar-1"
               externalEventMutations={this.state.externalMutation}
              labels={({ datum }) =>(datum.y>=1000)?((datum.y>=100000)?((datum.y>=1000000)?((datum.y>=1000000000)?("$"+(Math.round(datum.y)/1000000000).toFixed(2)+"B"):("$"+Math.round(datum.y)/1000000+"M")):("$"+Math.round(datum.y)/100000+"L")):("$"+Math.round(datum.y)/1000+"k")):("$"+Math.round(datum.y))}
              labelComponent={<VictoryTooltip
             
                flyoutWidth={60}
                orientation={"left"}
                horizontal={true}
                active={false}
                flyoutStyle={{ fill: "white" }}
              />}
             events={[
               {
                   target: 'data',
                   eventHandlers: {
                    
                     onPressIn: (evt, pressedProps) => {
                       
                       const selectedDataIndex = pressedProps.index
                       return [
                           {
                               eventKey: 'all',
                               target: 'labels',
                               mutation: props => {
                                   let activeState = true
                              
                                   if (props.active === true) {
                                       activeState = false
                                   }
                                   return props.index ===
                                       selectedDataIndex
                                       ? { active: activeState }
                                       : { active: false } 
                               },
                           },
                       ]
                   },
                       onPressOut: (evt, pressedProps) => {
                           const selectedDataIndex = pressedProps.index
                           return [
                               {
                                   eventKey: 'all',
                                   target: 'labels',
                                   mutation: props =>
                                       props.index === selectedDataIndex
                                           ? { active: props.active }
                                           : true
                               },
                           ]
                       },
                   },
               },
           ]}
              cornerRadius={{ top: 5}}
              data={this.state.data.earning}
              style={{
                data:{
                  fill:'rgb(81,57,45)',
                  width:normalize(5),
                }
              }}
              
              />
              
              <VictoryBar
                externalEventMutations={this.state.externalMutation}
              labels={({ datum }) =>(datum.y>=1000)?((datum.y>=100000)?((datum.y>=1000000)?((datum.y>=1000000000)?("$"+(Math.round(datum.y)/1000000000).toFixed(2)+"B"):("$"+Math.round(datum.y)/1000000+"M")):("$"+Math.round(datum.y)/100000+"L")):("$"+Math.round(datum.y)/1000+"k")):("$"+Math.round(datum.y))}
              labelComponent={<VictoryTooltip
               flyoutWidth={60}
               orientation={"left"}
               horizontal={true}
               active={false}
               flyoutStyle={{ fill: "white" }}
             />}
             events={[
               {
                   target: 'data',
                   eventHandlers: {
                     onPressIn: (evt, pressedProps) => {
                       const selectedDataIndex = pressedProps.index
                       return [
                           {
                               eventKey: 'all',
                               target: 'labels',
                               mutation: props => {
                                   let activeState = true
                                   if (props.active === true) {
                                       activeState = false
                                   }
                                   return props.index ===
                                       selectedDataIndex
                                       ? { active: activeState }
                                       : { active: false } // changed this line from null
                               },
                           },
                       ]
                   },
                       onPressOut: (evt, pressedProps) => {
                           const selectedDataIndex = pressedProps.index
                           return [
                               {
                                   eventKey: 'all',
                                   target: 'labels',
                                   mutation: props =>
                                       props.index === selectedDataIndex
                                           ? { active: props.active }
                                           : true
                               },
                           ]
                       },
                   },
               },
           ]}
              cornerRadius={{ top: 5}}
               data={this.state.data?.expense}
               style={{
                data:{
                  fill:'rgb(252,205,18)',
                  width:normalize(5),
                }
              }}
              
              />
            </VictoryGroup>
            <VictoryLegend
            orientation="horizontal"
            gutter={20}
             x={Dimensions.get("screen").width/2-100} 
             y={275}
             
              data={[
                {
                name:"Earnings",
                symbol:{
                  fill:'rgb(81,57,45)',
                }
                
              },
              {
                name:"Expense",
                symbol:{
                  fill:'rgb(252,205,18)',
                }
              }
              ]}
           />
          </VictoryChart>

**Comment by tgalfin** [comment]
Not sure if this is relevant to this issue, but another issue (#981) of flyouts being covered by chart elements have been solved by rendering in a portal, but this was with a custom flyout. Portal rendering should be default in VictoryTooltip, so I it seems like it should work as expected. I noticed in the docs that portal doesn't work in a custom container, and you have an empty containerComponent prop in your pasted code--are you using a custom container, and if so, could this have something to do with it?

It might help if you posted a demo that reproduces with this behavior since it's not possible to do so easily from the pasted code.
