### ISSUE TITLE
invalid format error with chart from documentation

### ISSUE THREAD

**Issue by xcoderzach** [FormidableLabs/victory#197]
I'm using victory@0.4.0, and this code, copied directly from the demo fails:

```javascript
      <VictoryChart>
        <VictoryLine
          y={(x) => Math.sin(1.5 * Math.PI * x)} />
        <VictoryLine
          style={{data: {stroke: "#c33b33"}}}
          y={(x) => Math.cos(2 * Math.PI * x)} />
      </VictoryChart>
```

with: 

```
Uncaught Error: invalid format: ,.NaNf
```

**Comment by exogen** [comment]
The demo is unfortunately out of date. See this same issue from yesterday: https://github.com/FormidableLabs/victory-line/issues/76

**Comment by exogen** [comment]
@dandelany Do you know if we have an issue tracking this?

**Comment by boygirl** [comment]
@xcoderzach demo republished just now! sorry about that.
