### ISSUE TITLE
Victory chart disappears when the width prop is over 2730 pixels

### ISSUE THREAD

**Issue by chedielathmnilatech** [FormidableLabs/victory#1978]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ ] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a horizontal scrollview, with a chart in it, and when I put the VictoryChart component width to something over 2730, the chart disappears.
I think it's related to this somehow: https://github.com/facebook/react-native/issues/24934
I'm suspecting it's more related to react-native-svg and OpenGL renderer. but if anyone has encountered the same problem, it would be very helpful

### Reproduction

https://snack.expo.dev/@chedielathmni/victory-demo
I have the same issue on managed or bare workflow

### Environment
React Native version: 0.63.4
Android version: 8.0.0
Device: Samsung Galaxy S7 Edge
victory-native: 33.0.0

I tried also with victory-native 35.0.0, same problem

**Comment by nattapat-p** [comment]
i face this problem too(disappearing very wide chart in a horizontal scrollview) too but only on some android device HUAWEI P9 PLUS (Android 7)
vivo1806 (Android 10)
