### ISSUE TITLE
Victory Native Absorption: Testing Setup

### ISSUE THREAD

**Issue by gksander** [FormidableLabs/victory#1979]
## Description

Add a suite of tests for Victory Native. Borrow as much as possible from the standalone VN repo, but also add a suite of tests to test that each component can mount (using something like `@testing-lib/react-native`). To start, we probably don't need to be too exhaustive -- but I think just ensuring components mount will be a great safeguard to refactors around Victory Core/Native.

**Comment by zibs** [comment]
Hey @gksander, 

I can see there's a collection of tests for native [here](https://github.com/FormidableLabs/victory/blob/main/test/jest/components.test.js) - does this accomplish what we wanted here? Or is anything else we should add here for now, or can we close this out?
