### ISSUE TITLE
CSS modules support

### ISSUE THREAD

**Issue by F21** [FormidableLabs/victory#198]
I am standardizing on using CSS modules throughout my project.

Essentially, I write my CSS as a traditional css file:

```css
.test{
  color: red;
}
```
In my javascript, I import it to use with my component:
```js
import styles from './component.css'

export default () => (
   <div className={styles.test}>
       <p>blah</p>
   </div>
)
```

Webpack then compiles `.test` into a unique id and inserts it into the right places.

Currently, Victory components set the styles on the `style` attribute using an object like so:
```javascript
{
    axis: {
        stroke: "#756f6a"
    },
    grid: {
        stroke: "grey"
    },
    ticks: {
        stroke: "grey"
    }
}
```

It would be really neat if the style object can be provided like so (where `styles.axis` etc are class names):

```javascript
{
    axis: styles.axis,
    grid: styles.grid,
    ticks: styles.ticks,
}
```

Then, in the components generated by victory would have a class name set rather than the styles set. This would be a pretty easy way to have victory work with css modules.

**Comment by boygirl** [comment]
@F21 I'm not very familiar with CSS modules. Are you still able to access the individual attrs? Victory is doing stuff like determining label positioning from stuff like `style.ticks.padding`, and falling back on default styles if it's not provided. If this would still be feasible with css modules I'm happy to add the functionality.  Apart from accessing individual style attrs for calculations, I'm imagining just preferentially adding a `style` or `className` prop depending on whether the value for a key like `axis` is a string or an object.

**Comment by F21** [comment]
I don't think it's possible to access the properties of a class. All css module does is rewrite a classname like `.test` to `.some_component_test_hash` so that they are globally unique.

So, usually with something like react-cssmodules, you would do:

```js
<mycomponent styleName="test" />
```

After compilation, it will rewrite the classname as:
```js
<mycomponent class="some_component_test_hash" />
```

If css modules are not possible, is it possible to use an external css file for styling?

**Comment by boygirl** [comment]
@F21 This issue is going to need a bit more planning on our part. We'll come back to this and #185 next sprint
