### ISSUE TITLE
Victory Bar Chart - Unable to fix width of tick-label on X-axis 

### ISSUE THREAD

**Issue by bhaveshbarskar** [FormidableLabs/victory#1986]
Facing issue while fixing the width of tick-label on x-axis, so the ask is to have width of tick label same as bar, in case the label text is long it should move to next line. Currently its overlapping with the next tick label.

    <VictoryChart domainPadding={{x:50 , y:20}} >
          <VictoryAxis style={{tickLabels:{width:10, fontSize:7, fill: '#575757', fontFamily:'Roboto Regular'}}}/>
          <VictoryBar 
          sortKey={criteria}
          style= {{ data : {fill:'#0a2c9b', fillOpacity:({index})=> ++index*0.1 , width:20}}}
          cornerRadius={3}
          barWidth={20}
          data ={projects} 
          x="title" 
          y ={criteria}> 
          </VictoryBar>
          <VictoryAxis dependentAxis
          label="ProjectName" 
          tickFormat={() => ''}
          style={{
            axisLabel: { padding: 10, fontSize:7, fill: '#575757', fontFamily:'Roboto Regular' }
          }}
        />
          </VictoryChart>

<img width="658" alt="Capture" src="https://user-images.githubusercontent.com/16028984/136016388-f90f13db-aa60-427d-8242-6ae7bdcbadeb.PNG">

**Comment by tgalfin** [comment]
Do you want the tick label to wrap so it takes up multiple lines, or do you want it to remain as a single line and offset the entire line down?

**Comment by tgalfin** [comment]
The VictoryAxis tickFormat prop can take a callback that allows you to modify labels individually:

If you wanted to wrap at a specific character count, you can just split the string up into an array of strings for every n characters and return that array. Each element will display on a new line:
```
      tickFormat={(label) => {
      	return label.match(/.{1,4}/g)
      }}
```

If you wanted to every individual label on a single line and have the entire line shift, you add a newline to labels in the callback. You could alternate labels, or only shift labels down they are longer than a certain length

ex: shift every other label:
```
        tickFormat={(label, i) => {
      	  return i % 2 === 0 ? label : '\n' + label 
        }}
```

![image](https://user-images.githubusercontent.com/79439202/136095166-64439f17-badc-4088-bd23-ec5e85f73f35.png)


The callback gives you access to the current label, current index, and array of all tick labels, so you could write logic to only shift specific labels based on whatever criteria you want

```
      tickFormat={(label, i, labels) => {
      	// whatever logic you want to figure out how you want to display labels
      }}
```

Does this cover what you need?

**Comment by bhaveshbarskar** [comment]
Thanks, this covers my need
