### ISSUE TITLE
Tooltips in VoronoiContainer are flickering

### ISSUE THREAD

**Issue by chrysb** [FormidableLabs/victory#1993]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x] I am using the latest version of Victory

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Tooltips in my VoronoiContainer are flickering. I can also see one of the data points being rendered way outside of the container (look to the right in this video):

https://user-images.githubusercontent.com/120388/136677120-a7db9f35-626f-48b8-af3b-7ff85c965bee.mov

```
      <VictoryChart
        minDomain={{ y: 0 }}
        height={200}
        padding={{ left: 30, right: 18, top: 18, bottom: 18 }}
        theme={victoryTheme}
        scale={{ x: 'time' }}
        containerComponent={
          <VictoryVoronoiContainer
            voronoiDimension='x'
            labels={({ datum }) => `${datum.labelX}: ${round(datum.y, 2)}`}
          />
        }
      >
        <VictoryAxis theme={victoryTheme} dependentAxis />
        <VictoryAxis
          theme={victoryTheme}
          crossAxis
          tickFormat={(t) => getChartDate(t)}
        />
        <VictoryScatter
          animate={{
            duration: 150,
            onLoad: { duration: 150 },
          }}
          style={{
            data: {
              fill: ({ datum }) => colors[datum.type],
            },
          }}
          data={data}
        />
      </VictoryChart>
```

**Comment by becca-bailey** [comment]
Closing for now, but we will address this as a part of #2104.
