### ISSUE TITLE
event is not woking on android in react-native.

### ISSUE THREAD

**Issue by Nsingh0007** [FormidableLabs/victory#2005]
events={[
              {
                target: "data",
                eventHandlers: {
                  onClick: () => {
                    console.log('Pressed on Data -> ')
                  },
                },
              },
            ]}
            
            and 
  events={[
              {
                target: "data",
                eventHandlers: {
                  onPress: () => {
                    console.log('Pressed on Data -> ')
                  },
                },
              },
            ]}

Both are not working on the android platform in react-native

**Comment by Siva-Leo** [comment]
![image](https://user-images.githubusercontent.com/68079920/143876359-82b4bdb6-c648-48a8-a56c-b082ec39acd4.png)

I can't find the issues section in https://github.com/FormidableLabs/victory-native

and their mentioned 
![image](https://user-images.githubusercontent.com/68079920/143876554-27eaf798-dae1-4fc5-807d-25f409f736fc.png)

like this...???
My Code is 
```
<VictoryChart
        width={size.responsiveWidth(100)}
        domain={{ y: [200, 1000] }}
        domainPadding={{ x: 2, y: 10 }}
        theme={VictoryTheme.material}
      >
<VictoryBar
          name="data"
          data={data[2021]}
          x="month"
          y="customer"
          dataComponent={
            <Bar
              events={{
                onClick: evt => alert(`(${evt.clientX}, ${evt.clientY})`),
              }}
            />
          }
          barWidth={() => 7}
          style={{ data: { fill: colors.primary } }}
        />
      </VictoryChart>
```
