### ISSUE TITLE
Cannot hide the VictoryChart default axes, or appropriately use VictoryGroup instead

### ISSUE THREAD

**Issue by esdrasjnr** [FormidableLabs/victory#2009]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

By now I want to hide the default axes when using the `VictoryChart` component. My custom component `BarChart` must show axes optionally, and by default hide them.

As [wrote in the FAQ](https://formidable.com/open-source/victory/docs/faq/#how-do-i-turn-off-the-axes-on-victorychart), I have already tried to replace the `VictoryChart` with the `VictoryGroup`, but there are two problems with it:
- The  `VictoryGroup` [own documentation](https://formidable.com/open-source/victory/docs/victory-group/#victorygroup) advises to not use `VictoryAxis` as children, which as I told above is a requirement for my component. Quote:
> `VictoryGroup` _should not_ be used with [VictoryAxis](https://formidable.com/open-source/victory/docs/victory-axis) children. Use [VictoryChart](https://formidable.com/open-source/victory/docs/victory-chart) instead;
- Even ignoring this quote, when I try to use `VictoryGroup` it doesn't render the x-axis tick labels correctly. It renders numbers instead of the data categories (which is explicitly set by the `x` property of my `VictoryBar`).

If it is only an error in the documentation I don't know, but this second behaviour associated with the `VictoryGroup` lead me to open this issue.

Currently, I'm using the workaround [suggested here](https://stackoverflow.com/a/62035719), which consists in add an "invisible" axis to overwrite the default `VictoryChart` behaviour. I don't like it, but is the way I found to make my code works. Any other suggestion is welcome 😄 

### Reproduction

Use `VictoryChart` without any `VictoryAxis` inside it: [sample](https://codesandbox.io/s/distracted-nobel-eqn62)
Use `VictoryGroup` instead and add an independent `VictoryAxis`: [sample](https://codesandbox.io/s/admiring-pare-bxscr)

**Comment by beccanelson** [comment]
Hi @esdrasjnr ! Thanks so much for that helpful explanation and those reproductions. It does look like there is an issue with the axis scaling when you use an axis inside `VictoryGroup`. I will investigate a bit more, and let you know what I find out.
