### ISSUE TITLE
Tooltip obscured in a Grouped Bar chart

### ISSUE THREAD

**Issue by PttB422** [FormidableLabs/victory#2016]
# Bugs and Questions

### Checklist
- [x] This is a `victory-native` specific issue

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm trying to display a tooltip in a grouped bar chart when the user tapped on a bar but the tooltip is obscure by other bar.

### Reproduction

```
<VictoryChart>
      <VictoryGroup offset={20} colorScale={"qualitative"}>
        <VictoryBar
          labels={({datum}) => `x: ${datum.x}, y: ${datum.y}`}
          labelComponent={<VictoryTooltip />}
          data={[{ x: 1, y: 1 }, { x: 2, y: 2 }, { x: 3, y: 5 }]}
        />
        <VictoryBar
          labels={({datum}) => `x: ${datum.x}, y: ${datum.y}`}
          labelComponent={<VictoryTooltip active={true} />}
          data={[{ x: 1, y: 2 }, { x: 2, y: 1 }, { x: 3, y: 7 }]}
        />
        <VictoryBar
          labels={({datum}) => `x: ${datum.x}, y: ${datum.y}`}
          labelComponent={<VictoryTooltip />}
          data={[{ x: 1, y: 3 }, { x: 2, y: 4 }, { x: 3, y: 9 }]}
        />
      </VictoryGroup>
</VictoryChart>
```
<img width="340" alt="Screen Shot 2021-11-04 at 11 52 58" src="https://user-images.githubusercontent.com/66003753/140259967-b24c11f5-26e2-40ca-a190-67772f1cd825.png">

**Comment by beccanelson** [comment]
@PttB422 Thanks for flagging this issue! I think this could be related to a `VictoryPortal` issue I flagged in #1984.

**Comment by PttB422** [comment]
I think the renderInPortal prop doesn't work on React Native at all. I got this warning in my console whenever I tried to use VictoryTooltip. @beccanelson 
```
`renderInPortal` is not supported outside of `VictoryContainer`. Component will be rendered in place
``` 
I have to disable the renderInPortal of VictoryTooltip and provide a custom flyoutComponent
<img width="353" alt="Screen Shot 2021-11-05 at 10 15 54" src="https://user-images.githubusercontent.com/66003753/140452537-71c5e65c-3024-435e-ad29-513b2f58f511.png">
