### ISSUE TITLE
undefined is not an object (evaluating 'y.BrushHelpers.onMouseMove.cancel')

### ISSUE THREAD

**Issue by SaeedZhiany** [FormidableLabs/victory#2021]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
This is a Victory-Native related bug. I use the sample code of [this documentation](https://formidable.com/open-source/victory/guides/brush-and-zoom#brush-and-zoom)

BrushContainer is not working when the user starts to touch and move it and the error message below has shown.

```bash
undefined is not an object (evaluating 'y.BrushHelpers.onMouseMove.cancel')
```

![image](https://user-images.githubusercontent.com/13766432/140868837-cce3eedd-4116-4a52-af07-3815ccb68237.png)

### Reproduction
Open the link below and run the project in Android and iOS emulators. then try to move the brush to the left or right. you'll see the error.

https://snack.expo.dev/@saeedzhiany/victory_native_brushcontainer_bug

**Comment by jason-zeiler** [comment]
Seeing the same issue, has anyone else ran into this and found a solution?

**Comment by uginy** [comment]
I faced with the same issue recently. No way for now to fix that, just downgrade to 33.X version, but it leads to new compatibility issues so far

**Comment by uginy** [comment]
As a quick-hack solution you could make these changes in the file ./node_modules/victory-native/src/components/victory-brush-container.js. But sure, it's quite enough just for demo/testing purposes.

change onMouseMove -> onGlobaMouseMove
change onMouseUp -> onGlobalMouseUp

I tried to contribute that fix, but have no privileges for that, so i wrote to Becca, mb she will put these changes to a new package version.

**Comment by SaeedZhiany** [comment]
Thanks, @uginy, I'll try it.

> I tried to contribute that fix, but have no privileges for that, so i wrote to Becca, mb she will put these changes to a new package version.

Have you tried to send a PR for it? there is no need to have permission for it and anyone can create a PR on repositories.

**Comment by YoucefAcheuk** [comment]
> As a quick-hack solution you could make these changes in the file ./node_modules/victory-native/src/components/victory-brush-container.js. But sure, it's quite enough just for demo/testing purposes.
> 
> change onMouseMove -> onGlobaMouseMove change onMouseUp -> onGlobalMouseUp
> 
> I tried to contribute that fix, but have no privileges for that, so i wrote to Becca, mb she will put these changes to a new package version.

It works, please send a PR for this 🙏🏽

**Comment by uginy** [comment]
> 

Hi, I am glad for you )
As you might see, the PR was made almost month ago, let's believe that finally it will be approved in the new 2022 year.
