### ISSUE TITLE
Vertical scroll in victory legend

### ISSUE THREAD

**Issue by AG-dms** [FormidableLabs/victory#2027]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When i use victory chart with many data, victory legend cannot display all data within one chart. If i need use it within the established design. I need vertical scroll in victory legend to display all data.

### Reproduction
![victoryLegend](https://user-images.githubusercontent.com/75346722/143531474-efc982df-6aa6-45f8-b7db-3dc7c5eb7a62.png)

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

scroll list data in victory legend

**Comment by becca-bailey** [comment]
This functionality might require a custom component to implement. For questions about how to do this, please [open a discussion thread](https://github.com/FormidableLabs/victory/discussions). If you believe this is a bug with Victory, please re-open this issue with a reproduction. Thank you!
