### ISSUE TITLE
Chart animations not working on first page load

### ISSUE THREAD

**Issue by elderferreiras** [FormidableLabs/victory#2030]
# Bugs and Questions

### Checklist

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a project with a page that displays six VictoryLine charts and I recently noticed that they do not load properly on the first load, sometimes not even the second. Is this an issue anyone else here might have had before? If yes, how did you solve it?

### Reproduction

I reproduced my issue in this CodeSandbox:

https://codesandbox.io/s/happy-dawn-znmee?file=/src/App.js

If you go to this link, you can access the CodeSandbox result in a separate window: https://znmee.csb.app/

I also did a small recording of refreshing the page and the GIF is below. As you can see, every time CodeSandbox decides to do a hard reload (loading modules...), the charts don't show any animation, but when there's a simple refresh, the animations show up.

![ezgif-6-e1808a55c3ec](https://user-images.githubusercontent.com/5190461/143971326-a97f1737-7d84-4c94-8e8a-07fe5af2e86c.gif)

**Comment by becca-bailey** [comment]
Hi @elderferreiras, I think this is intended behavior! When code sandbox does a hot refresh (when you make a change and save it), it changes any props or functions, but it doesn't reset the state. We keep track of the state of the animations using React state, and the loading state is only triggered when the page is reloaded.
