### ISSUE TITLE
React Native: Victory charts are not supported for rtl.

### ISSUE THREAD

**Issue by blazk0** [FormidableLabs/victory#2033]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The VictoryBar Charts are working great in ltr direction and behaving as expected. However, When switching to rtl, the chart remain in the same direction as ltr.

### Reproduction

```javascript
   const data = {
    {
      "cashBackDate": "فبراير",
      "amount": 25
    },
    {
      "cashBackDate": "يناير",
      "amount": 25
    },
    {
      "cashBackDate": "ديسمبر",
      "amount": 10500
    },
    {
      "cashBackDate": "أكتوبر",
      "amount": 1860
    },
    {
      "cashBackDate": "سبتمبر",
      "amount": 10352
    }
  ]

   <VictoryChart domainPadding={20} theme={VictoryTheme.material}>
          <VictoryBar
            cornerRadius={{ topLeft: 10, topRight: 10 }}
            style={{ data: { fill: BAR_GREEN_COLOR_HIGHLIGHT } }}
            data={data}
            x="cashBackDate"
            y="amount"
          />
  </VictoryChart>
   ```

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

The Chart should be inverted. The Horizontal and vertical Axis.
I have tried to transform the style but this also inverts the text which is not ideal.

![Simulator Screen Shot - iPhone 12 - 2021-12-08 at 13 43 45](https://user-images.githubusercontent.com/36491230/145194894-17bb6cd7-9505-489f-b6e3-ceb532102373.png)

![Simulator Screen Shot - iPhone 12 - 2021-12-08 at 13 31 29](https://user-images.githubusercontent.com/36491230/145194560-784d1df1-9e05-4431-8930-2a718a0448c2.png)

**Comment by blazk0** [comment]
any one ?

**Comment by blazk0** [comment]
Any body facing this issue ?

**Comment by becca-bailey** [comment]
Hi @blazk0, we have had a few issues come up recently around internationalization, and I do think it should be a priority for us to address. I'll flag this, and we'll work on getting it prioritized.

**Comment by becca-bailey** [comment]
Closing this issue and moving discussion to #2018.
