### ISSUE TITLE
A full zoom-out on combned Brush and Zoom chart results in incorrect brush selection being drawn

### ISSUE THREAD

**Issue by Chris7** [FormidableLabs/victory#2042]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Using the brush-and-zoom chart, when performing a full zoom-out following a selection via the brush, the brush component will "overflow" and then get reset to the initial cached selection

### Reproduction

You can actually use your example to reproduce this: https://formidable.com/open-source/victory/guides/brush-and-zoom/

1) Select an area using the brush
2) Do a full zoomout using the mouse wheel
3) The zoom chart will correctly render, but the brush selection will be incorrect

![image](https://user-images.githubusercontent.com/963909/147287304-e70cb92e-a693-4774-aee0-c3b31a80ed99.png)

**Comment by becca-bailey** [comment]
Interesting! I'm not actually able to reproduce this in Chrome or Safari. What browser are you using?

**Comment by Chris7** [comment]
Hi Becca,

Thanks for the quick response! I'm using Firefox on Linux. I can try and
see if it reproduces in chrome as well and maybe see how to make a gif of
what I see.

**Comment by Chris7** [comment]
Here's a gif reproducing the bug on the demo page:

![victory bug](https://user-images.githubusercontent.com/963909/147686078-6030d327-a3a8-4e5d-a70a-fa1b51ae5eed.gif)

**Comment by becca-bailey** [comment]
Closing in favor of #2111
