### ISSUE TITLE
Show background color on victory bar (react native)

### ISSUE THREAD

**Issue by TheEvisu** [FormidableLabs/victory#2045]
# Bugs and Questions

### Checklist

- [ √] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [√ ] I am using the latest version of Victory

- [ √] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](
https://codesandbox.io/s/practical-elgamal-4xq2x?file=/index.js
) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests
![2](https://user-images.githubusercontent.com/47283629/147558940-f839d802-e725-43a6-9421-2c930591cf59.png)

### Checklist

- [√ ] I've read through the [Docs](https://formidable.com/open-source/vict
![1](https://user-images.githubusercontent.com/47283629/147558721-0569ef6e-c63e-48a6-84f2-e1b05c50c3f9.png)
ory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ √] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.
Hello . I can't figure out how to fill in the background Bar ..

**Comment by becca-bailey** [comment]
Hi @TheEvisu - here is a codesandbox with three different ways of styling your bars. You can use a `theme` prop in the top-level chart, include an inline `style` object with a `data` key, or use a CSS class. See the docs here: https://formidable.com/open-source/victory/docs/victory-bar

https://codesandbox.io/s/filled-bar-examples-5ucoq
