### ISSUE TITLE
No ability to change font family

### ISSUE THREAD

**Issue by Melber17** [FormidableLabs/victory#2047]
# Bugs and Questions

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
No ability to #change font family for component **`VictoryAxis`**, **tickLabels**
`						tickLabels: {
							color: "#03061D",
							fontFamily: "Proxima Nova",
							fontSize: 18,
						},`

### Reproduction

<img width="374" alt="Screen Shot 2021-12-29 at 10 14 50 AM" src="https://user-images.githubusercontent.com/63192915/147638554-95c9ff00-12cc-4972-a465-cced9fa31c94.png">

**Comment by mjcarnaje** [comment]
+1

**Comment by zibs** [comment]
Hey @Melber17, I've made a codesandbox trying to repro this issue: https://zzt4y.csb.app/ and I seem to be able to set the font family of the tick labels (and axis labels) to a custom google font. You can see how it's set up here https://codesandbox.io/s/dank-snowflake-zzt4y. It's a bit messy but I've tried to throw a few different bar charts/axes in there.

Let me know if I've missed something here. If I have, do you mind throwing up a codesandbox with a simple [mvce](https://stackoverflow.com/help/minimal-reproducible-example) and posting it here?

**Comment by Melber17** [comment]
> Hey @Melber17, I've made a codesandbox trying to repro this issue: https://zzt4y.csb.app/ and I seem to be able to set the font family of the tick labels (and axis labels) to a custom google font. You can see how it's set up here https://codesandbox.io/s/dank-snowflake-zzt4y. It's a bit messy but I've tried to throw a few different bar charts/axes in there.
> 
> Let me know if I've missed something here. If I have, do you mind throwing up a codesandbox with a simple [mvce](https://stackoverflow.com/help/minimal-reproducible-example) and posting it here?

Yeah, thank you, it's working fine. My problem was actually in the version of react native. After update to 0.66 all is fine

**Comment by zibs** [comment]
Feel free to close this out if you think we're good here then @Melber17 - thanks!

**Comment by lea-foliume** [comment]
Hey, I've been experiencing the same issue. And although I've followed the format used in the sandbox. I don't seem able to get it working. How does Victory know which font to use? Do i have to install some package for it? Using  
style={{
                tickLabels: { fontFamily: "Permanent Marker" },
                axisLabel: { fontFamily: "Permanent Marker" }
              }}
 Doesn't seem to be enough for it to be working properly. 
 Thanks in advanced
