### ISSUE TITLE
850kb for a simple line chart

### ISSUE THREAD

**Issue by roger-ng-helloworld** [FormidableLabs/victory#205]
I would like to use this but the glaring issue is the bundle size for a simple line chart, it's about 850kb

**Comment by bkniffler** [comment]
Yes, I've been submitting an equivalent issue here https://github.com/FormidableLabs/victory/issues/202

**Comment by ryan-roemer** [comment]
Hi Folks -- Yes, this is on our radar, and we're actively working on slimming down the Victory builds (as well as the package.json dependencies on installs to make things faster).

**Comment by boygirl** [comment]
Closing in favor of specific issues #211 and #212
