### ISSUE TITLE
Enable Victory Selection Container by Default?

### ISSUE THREAD

**Issue by jesper-stighem-pini** [FormidableLabs/victory#2050]
# Question

### The Problem

We're using Victory and VictorySelectionContainer in a project and have to uncomment the import of VictorySelectionContainer, SelectionHelpers and selectionContainerMixinit every time we pull it down, which adds to our build process and breaks automated builds. Not sure if that was the main cause for the obmittance, but it seems to now have the needed types to work well enough. See [merged pull requiest #1530](https://github.com/FormidableLabs/victory/pull/1530). Our experience is that VictorySelectionContainer is mature enough to be imported by default. Is this the case?

### The Solution

In `/victory/src/index.d.tss` uncomment the lines 112-116: 

    // import {
    //   VictorySelectionContainer,
    //   SelectionHelpers,
    //   selectionContainerMixin
    // } from "victory-selection-container";

In the same file uncomment the exports at lines 244-246:

    // VictorySelectionContainer,
    // SelectionHelpers,
    // selectionContainerMixin,

**Comment by becca-bailey** [comment]
Hi @jesper-stighem-pini, thanks for flagging this! I just put up a PR that should make your life a little easier for now, and I'll also open an issue so we can audit the other commented type definitions in `victory/src/index.d.ts` and address any outstanding work that is needed there.

**Comment by jesper-stighem-pini** [comment]
@becca-bailey Awesome! Thanks!
