### ISSUE TITLE
Warning: Failed prop type: Cannot read properties of undefined (reading 'hasOwnProperty') with NextJS

### ISSUE THREAD

**Issue by monsieurnebo** [FormidableLabs/victory#2052]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Victory components (VictoryChart, VictoryBar, ...) usage triggers the following error when used with **NextJS**:
`Warning: Failed prop type: Cannot read properties of undefined (reading 'hasOwnProperty')`

### Reproduction

You can take a look to [this basic example on CodeSandbox](https://codesandbox.io/s/nervous-hugle-b0zrn?file=/pages/index.js).

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

The error started with `victory v36.2.0`.

This error should be fixed to avoid log pollution.

It seems to be triggered by[ the following code (`shouldComponentUpdate`)](https://github.com/FormidableLabs/victory/blob/00c362fcd3e8f3880e14d3ba42873c34dd69c577/packages/victory-core/src/victory-util/add-events.js#L49-L69).

Seems specific to SSR because of [the error absence in pure React](https://codesandbox.io/s/lucid-rubin-932cx?file=/src/App.js).

Thanks for the hard work 🙏 

### Related issues
https://github.com/vercel/next.js/issues/1412
https://github.com/FormidableLabs/victory/issues/516

**Comment by alfianwahid** [comment]
after upgrade victory-native 35.5.5 to 36.2.0, I got this error

ERROR  Warning: Failed prop type: Cannot read property 'hasOwnProperty' of undefined
    at VictoryAxis
    in VictoryChart (created by VictoryChart)
    
   
React-Native 0.66.4

**Comment by tsachit** [comment]
> after upgrade victory-native 35.5.5 to 36.2.0, I got this error
> 
> ```
> ERROR  Warning: Failed prop type: Cannot read property 'hasOwnProperty' of undefined
>     at VictoryAxis
>     in VictoryChart (created by VictoryChart)
> ```
> 
> React-Native 0.66.4

I've been seeing this on 35.5.5 since few days

**Comment by becca-bailey** [comment]
Hmm, this is a tricky one! I can see the error on the code sandbox linked above, but so far I haven't been able to reproduce the same issue in my own next.js code sandbox or local project. The issue seems to resolve itself once I switch to any other version of victory, but _also_ doesn't re-appear once I re-install 35.6.2. I'm going to continue to look into this, but I'm also adding a "help wanted" label here in case anyone else has ideas! 

Historically, it does seem like the higher-order components have been a bit problematic with `next.js`, but I'm not aware of any changes in 35.6.2 that would have affected this on our end.

**Comment by becca-bailey** [comment]
In the reproduction it is appearing as a prop type warning, but it is not preventing the build from succeeding. Is anyone experiencing this as a build error? I'll look into it either way, but I'm just trying to determine the priority for addressing it.

**Comment by monsieurnebo** [comment]
@becca-bailey Thanks for digging in. We only encountered as a prop type error.

I understand that's less of a priority than a build error, but I hope it will be fixed anyway because this is causing false positive when we want to debug stuff in runtime 🤯

**Comment by wnvuong** [comment]
i'm also having this issue with react native

**Comment by monsieurnebo** [comment]
@becca-bailey Did you have the time to dig into this issue by any chance? :)

**Comment by cpandya231** [comment]
@becca-bailey it is really flooding the console and make debugging difficult, I will be happy to help if you can give me directions.  🙂

**Comment by becca-bailey** [comment]
I can see the error in the code sandbox link above (thanks for the reproduction!), however I can't reproduce it locally with `create-next-app` or see the same error if I upgrade Victory to the latest version (36.3.1). Here's my current sandbox. https://codesandbox.io/s/charming-cannon-tqnjez

If you are seeing this error - can try to upgrade to the latest version of Victory?

**Comment by jessegong37110** [comment]
Same here, is there any fix available ?
```
 ERROR  Warning: Failed prop type: undefined is not an object (evaluating 'checkerResult.data.hasOwnProperty')
VictoryArea
```

**Comment by becca-bailey** [comment]
This has been reported as a bug, but no fix is available yet. If anyone here would like to tackle this issue, PRs are welcome.

**Comment by rassemdev** [comment]
> This has been reported as a bug, but no fix is available yet. If anyone here would like to tackle this issue, PRs are welcome.

Also having this same error.

**Comment by acharyakavita** [comment]
@rassemdev I was unsuccessful in recreating this issue with the latest version of victory and NextJs.
Also the code sandbox examples shared above is not working anymore. Can you please check if this is occuring again ?
