### ISSUE TITLE
Aligning the grid view with x-axis tick labels

### ISSUE THREAD

**Issue by dhanushm360** [FormidableLabs/victory#2053]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I want the grid to align with the x-axis on the graph below. I have the bar alignment set to "end", but the grid view does not align and as a result, there is a bar that is "outside" the graph. How can I fix this?

![image](https://user-images.githubusercontent.com/49541102/148113143-ddfa9c82-ab49-499f-ba0f-2273d0c14056.png)

### Reproduction

I just used your example and modified it a bit. https://codesandbox.io/s/wizardly-darwin-ntrr2

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by becca-bailey** [comment]
Hi @dhanushm360 - Are you using a custom axis component? The code sandbox link you included doesn't include the bar chart. I'm not seeing the same alignment issue in my reproduction here.

https://codesandbox.io/s/ecstatic-cache-30wd0?file=/src/App.js

**Comment by dhanushm360** [comment]
Hi @becca-bailey No, I am not using a custom axis component. By alignment issue, I meant that the 1st bar is not part of the grid view as you can see in the image above. I want the vertical dashes to align with the beginning of the bars , instead of the at the end shown in the image.

**Comment by becca-bailey** [comment]
@dhanushm360 Do you mean like this, with the grid line in the center of the bar? 
<img width="465" alt="Screen Shot 2022-01-14 at 1 34 02 PM" src="https://user-images.githubusercontent.com/13334214/149588294-99eaa2da-9961-4952-b8a3-1bb2cc0dcb3a.png">

**Comment by dhanushm360** [comment]
@becca-bailey I want the grid line to the left of the bar.
![148113143-ddfa9c82-ab49-499f-ba0f-2273d0c14056](https://user-images.githubusercontent.com/49541102/149599100-222832e0-8a27-41a6-bf59-6c05a6b2bf2c.png)

I would like it to be like this:
![Screen Shot 2022-01-14 at 5 48 59 PM](https://user-images.githubusercontent.com/49541102/149599135-46b5d75e-9f60-4213-ace4-eb5d0338f914.png)
