### ISSUE TITLE
Is there a way to avoid collisions in scatter chart bubbles?

### ISSUE THREAD

**Issue by vlopezitrs** [FormidableLabs/victory#2054]
I was wondering if it's possible to avoid bubbles collisions, something similar as in d3:
`.force(
            'collide',
            forceCollide((d) => {
              return d.size;
            })
          )`

**Comment by becca-bailey** [comment]
As far as I know, this behavior isn't built into Victory. We can keep this issue open as a feature request, though! We also might be able to explore some ways to replicate this behavior in a custom scatter point component.
