### ISSUE TITLE
bar group selection issue

### ISSUE THREAD

**Issue by jsh0116** [FormidableLabs/victory#2056]
# Bugs and Questions

### Checklist

- [V] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [V ] I am using the latest version of Victory

- [V ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am developing a chart for my company.
I want to be able to select Group Bar.

Here's the Bar Group Selection possible case:
```
<div>
    <VictoryBar
      events={[{
      	target: "parent",
        eventHandlers: {
          onClick: () => {
            return [
              {
                target: "data",
                mutation: (props) => {
                  const fill = props.style && props.style.fill;
                  return fill === "black" ? null : { style: { fill: "black" } };
                }
              }
            ];
          }
        }
      }]}
      data={sampleData}
    />
</div>
```

but in this case, Bar GroupSelection is impossible
```
<div>
    <VictoryGroup>
        <VictoryBar
          events={[{
      	    target: "parent",
            eventHandlers: {
              onClick: () => {
                return [
                  {
                    target: "data",
                    mutation: (props) => {
                      const fill = props.style && props.style.fill;
                      return fill === "black" ? null : { style: { fill: "black" } };
                    }
                  }
                ];
              }
            }
          }]}
        data={sampleData}
      />
  </VictoryGroup>
</div>
```

Also, I want to change only bar-1's style through 'bar-1' group selection but when I selected 'bar-2' component, 'bar-1' component's style has been changed
```
<VictoryGroup
  offset={20}
  events={[{
    childName: "bar-1",
    target: "parent",
    eventHandlers: {
      onClick: () => {
        return [
          {
            childName: "bar-1",
            target: "data",
            mutation: (props) => ({ style: Object.assign({}, props.style, { fill: "gold" }) })
          }
        ];
      }
    }
  }]}
>
  <VictoryBar name="bar-1"
    data={[{x: "a", y: 2}, {x: "b", y: 3}, {x: "c", y: 5}]}
  />
  <VictoryBar name="bar-2"
    data={[{x: "a", y: 1}, {x: "b", y: 4}, {x: "c", y: 5}]}
  />
  <VictoryBar name="bar-3"
    data={[{x: "a", y: 3}, {x: "b", y: 2}, {x: "c", y: 6}]}
  />
  <VictoryBar name="bar-4"
    data={[{x: "a", y: 2}, {x: "b", y: 3}, {x: "c", y: 3}]}
  />
</VictoryGroup>
```
 please answer the question, thank you

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [ V] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ V] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by scotthhso** [comment]
What was the resolution for this?
