### ISSUE TITLE
Audit commented type definitions in victory/src/index.d.ts

### ISSUE THREAD

**Issue by becca-bailey** [FormidableLabs/victory#2059]
Related issue: #2050 

There are a lot of commented types in `victory/src/index.d.ts` and a TODO comment to add missing type definitions. I'm adding an issue for this so we can prioritize this work.

**Comment by jesper-stighem-pini** [comment]
Another related issue: #1516

**Comment by becca-bailey** [comment]
I'm going to close this since we are working on a TS conversion.
