### ISSUE TITLE
VictoryScatter: externalEventMutations prop type invalid warning

### ISSUE THREAD

**Issue by ninni426** [FormidableLabs/victory#2063]
### The Problem
While using VictoryScatter we are observing a warning in the console for prop-type being invalid when we pass a function in the callback.

'Warning: Failed prop type: VictoryScatter: prop type `externalEventMutations[0].callback` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.'

This issue is observed once we have upgraded 'react-scripts' and 'eslint' packages. 

![image](https://user-images.githubusercontent.com/20175744/150524222-e12b5732-4288-486c-9902-e6a1ff5c6d90.png)

The code is developed taking https://formidable.com/open-source/victory/docs/common-props#externalEventsMutations document as the reference.

![image](https://user-images.githubusercontent.com/20175744/150535482-b1b24e7b-caee-43a0-9607-28c6c2c3fbe2.png)

Ref: https://stackoverflow.com/questions/36127842/it-must-be-a-function-usually-from-react-proptypes 

Due to audits, we do need to upgrade our packages, could you please assist in resolving this warning?

Current dependencies:

  "dependencies": {
    "@azure/msal-browser": "^2.21.0",
    "@azure/msal-react": "^1.2.0",
    "@microsoft/applicationinsights-react-js": "^3.2.2",
    "@microsoft/applicationinsights-web": "^2.7.2",
    "axios": "^0.21.4",
    "bootstrap": "^4.6.0",
    "env-cmd": "^10.1.0",
    "react": "^17.0.1",
    "react-bootstrap": "^1.6.0",
    "react-datepicker": "^3.6.0",
    "react-dom": "^17.0.1",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^5.0.0",
    "react-select": "^4.3.1",
    "react-tooltip": "^4.2.15",
    "redux": "^4.0.5",
    "victory": "^36.2.0",
    "web-vitals": "^1.1.0"
  },
 "devDependencies": {
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@wojtekmaj/enzyme-adapter-react-17": "^0.4.1",
    "enzyme": "^3.11.0",
    "eslint": "^8.7.0",
    "eslint-plugin-react": "^7.28.0"
  }

CC: @boygirl

**Comment by becca-bailey** [comment]
This should be fixed in 36.4.1. Thanks @gustaff-weldon!
