### ISSUE TITLE
[Question] Why don't the labels respect the data being passed?

### ISSUE THREAD

**Issue by sadikyalcin** [FormidableLabs/victory#2065]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The Y axis labels doesn't reflect the data being passed with few items. Is there a way to turn this off? Seems to be happening with the X axis as well. I do not want decimals... I'm new to this lib and I couldn't find anything regarding this on the docs.

### Reproduction

```
  const data = [
    {"x": 0, "y": 1},
    {"x": 1, "y": 2},
  ];

  const data1 = [
    {"x": 0, "y": 1},
    {"x": 1, "y": 2},
    {"x": 3, "y": 3},
    {"x": 4, "y": 4}
  ];

  /**
   * data = Y axis isn't right for me
   * data1 = X axis isn't right for me
   */

  return (
    <VictoryChart>
      <VictoryLine data={data} />
    </VictoryChart>
  );
```

Link to sandbox: https://codesandbox.io/s/youthful-currying-ks79v?file=/index.js:141-495

**Comment by zibs** [comment]
Hey @sadikyalcin, you can totally customize that - here's a forked [sandbox of yours](https://codesandbox.io/s/quirky-rubin-tgeqx) that shows a few options. You'll want to familiarize yourself with [VictoryAxis](https://formidable.com/open-source/victory/docs/victory-axis) and the (`tickValue`, `tickFormat`) props to do more!
