### ISSUE TITLE
Victory Bars - Unable to remove left spacing in React Native on Android

### ISSUE THREAD

**Issue by Garlicvideos** [FormidableLabs/victory#2066]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using Victory Bars, I am unable to remove the left spacing that is created by default in order to make space for the y axis labels.
Removing both x and y axis altogether by wrapping Victory Bars in Victory Chart and adding Victory Axis does not remove the spacing on the left either.

### Reproduction

![image](https://user-images.githubusercontent.com/33229805/150653900-e79dc68a-835d-48c7-bac5-b7a963fb5ee8.png)

Here is the code to reproduce the issue in React-native on Android

    const barData = [{x: 1, y: 1357.40}, {x: 2, y: 901.10}, {x: 3, y: 1174.62}, {x: 4, y: 1854.80}, {x: 5, y: 793.12}, {x: 6, y: 998.42}, {x: 7, y: 
    1208.30}, {x: 8, y: 416.70}];

    //Return the component
    return(
         <VictoryBar style={{ data: { fill: "#609FC7" } }} height={200} width={Dimensions.get("window").width - 30} domainPadding={{ x : [20, 20] }} barWidth={15} labels={() => `$value`} data={barData}></VictoryBar>
    )

As can be seen, there is a massive space on the left, which is present for seemingly no reason.

However, wrapping VictoryBar in VictoryChart reveals that the space on the left is reserved for the y-axis labels.

![image](https://user-images.githubusercontent.com/33229805/150653939-4996beb3-70e8-48d4-b84d-12d4eca5bf40.png)

The issue is that I want my VictoryBar to take up the width of its parent container, and not have a massive space on the left.
I do not want to have any of the axis displayed.

Is there any way for me to do this?

**Comment by zibs** [comment]
Hey @Garlicvideos  are you able to do this on iOS? As far as I can't tell it's probably the same result on both platforms?

I've made a small snack that might help you out in either case: https://snack.expo.dev/@zibsform/laughing-sandwich - you can see two alternate implementations here, and the second one is probably the one you want to go with. Essentially it makes use of the [padding prop](https://formidable.com/open-source/victory/docs/common-props/#padding). (The first one is a hack that uses window width + left positioning to center the chart even as it extends beyond the window, but leaving it just as option if you need it).

Let me know if this works and we can close it out if so

**Comment by Garlicvideos** [comment]
That's great! Thank you.
