### ISSUE TITLE
Unique react-icon for every point on a scatter

### ISSUE THREAD

**Issue by owensco** [FormidableLabs/victory#2067]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I would like to create a scatter similar to this where each point is a unique [react-icon](https://react-icons.github.io/react-icons/).

![image](https://user-images.githubusercontent.com/3844029/150688501-e5c59f4b-46aa-4264-a767-6eed65dfaa9e.png)

The problem I'm having is that my icons are all stacking up in the top left of the chart:
![image](https://user-images.githubusercontent.com/3844029/150689711-2107d88b-8251-4015-881d-2fb29e50e492.png)

### Reproduction

[Code sandbox](https://codesandbox.io/s/summer-tree-4p3bu?file=/index.js). I'm guessing this snippet is the culprit:
```
const ScatterPoint = (props) => {
    const { x, y, datum } = props;
    return <DynamicIcon name={myIcons[props.index]} x={x} y={y}></DynamicIcon>;
};
```
Although looking at the props supplied to each instance of `<ScatterPoint/>`, they do appear to be receiving the correct `data`/`datum`:
![image](https://user-images.githubusercontent.com/3844029/150689901-0bfe13c4-e398-4e16-8313-eb9ecf08a36b.png)

Docs and guides I've read:
* [VictoryScatter](https://formidable.com/open-source/victory/docs/victory-scatter)
* [dataComponent](https://formidable.com/open-source/victory/docs/victory-scatter#datacomponent)
* [Custom Components](https://formidable.com/open-source/victory/guides/custom-components)
* [Similiar codesandbox #1](https://codesandbox.io/s/cat-tick-labels-9ls7t?file=/index.js)
* [Similiar codesandbox #2](https://codesandbox.io/s/x-symbol-points-5edp4?file=/index.js:127-282)

I think I'm close! Any and all support is greatly appreciated!

**Comment by sadikyalcin** [comment]
You also need to use `x` and `y` params on your icon components. They are svg so the below should work, unless you're talking about something else which I didn't understand.

```
const DynamicIcon = ({ name, x, y }) => {
  const Icon = reactIcons[name];
  return <Icon x={x} y={y} />;
};

// custom component to be used
// with Victory's dataComponent
const ScatterPoint = (props) => {
  const { x, y, datum } = props;
  return <DynamicIcon name={myIcons[props.index]} x={x} y={y}></DynamicIcon>;
};
```

**Comment by owensco** [comment]
@sadikyalcin that did it!
`return <Icon x={x} y={y} />;`

🤦‍♂️🤦‍♂️🤦‍♂️ 

Thank you sooooo much! Updated the [sandbox](https://codesandbox.io/s/summer-tree-4p3bu?file=/index.js) in case someone runs across this in the future!
