### ISSUE TITLE
EventHandler clear previous set style before selecting a new bar - referencing #489

### ISSUE THREAD

**Issue by OverYonderCat** [FormidableLabs/victory#2069]
Hi,

I'm a new user of victory charts and love it. Great work!
We're using victory-native 36.2. Picking up on already closed Issue  #489 we wanna have only one selected bar.

@boygirl mentioned "you can clear all the props set by previous events by returning null." - I'm interested how that should look like. 

imho we just can manipulate currently selected bar in EventHandler onClick / onPressIn, but not previously selected ones or "other bars" in general... at least not directly -> so we looked for a way to have "selections" in state and found [External Event Mutation example](https://formidable.com/open-source/victory/guides/events/#external-event-mutations). Following that we're able to clear "selections" manually by clicking a button.

well, thats not bad but we wanna have our onClick function something like:  first clear previously applied styles, then apply style for selection on current bar. Idea was to have 2 events, use first to clear state, second to apply style but this won't work.

here's an example on [codesandbox](https://codesandbox.io/s/victorycharrt-singlebarselect-2gn2m?file=/src/App.tsx)

Maybe you can take a look at this and maybe provide an example. This would help us and others.
We're also curious if this scenario could be handled without External Event Mutation.

thanks in advance
brgds
Flo

**Comment by OverYonderCat** [comment]
update: found a solution/workaround with differentiating between onPressIn and onPressOut

- use ExternalEventMutation as described in prev. post
- define two EventHandlers:

1. onPressIn -> which clears selection (what was triggered by onPress from Button in example)
2. onPressOut -> set style for selection

it looks sth. like this:

`events={[{
      target: 'data',
      eventHandlers: {
          onPressIn: (_event, _data) => {
              return [{ mutation: clearSelection }];
          },
          onPressOut: (_event, _data) => {
              return [{ mutation: (props) => ({style: Object.assign({}, props.style, {fill: 'red'})}) }];
          }
      }
  }]}`

greetings

**Comment by OverYonderCat** [comment]
update: after working more with Victory Charts I found the proper way of doing it - without ExternalEventMutation :-)

key learning is proper usage of target and eventKey, so it works with sth. like this:

```javascript
events={[{
    target: 'data',
    eventHandlers: {
        onPressIn: (_event, _data) => {
            return [
                {
                    eventKey: "all", // reset style for all bars, default target goes to data
                    mutation: () => null
                },
                {
                    mutation: (props) => { // set selected bar red - target "data" is default and eventKey is current element
                        return ({style: Object.assign({}, props.style, {fill: 'red'})})
                    }
                }
        }
    }
}]}
```

**Comment by c-goettert** [comment]
Thans for your solution @OverYonderCat I was struggeling with a very similar issue. However, when I used your Code above it would only work for the first press event. Using onPressIn / onPressOut as you suggested before solved this issue for me:
```javascript
events={[
  {
    target: 'data',
    eventHandlers: {
      onPressIn: (_event, _data) => {
        return [
          {
            eventKey: 'all', // reset style for all bars, default target goes to data
            mutation: () => undefined
          }
        ]
      },
      onPressOut: (_event, _data) => {
        return [
          {
            // eventKey: 'all', // reset style for all bars, default target goes to data
            mutation: (props) => {
              // set selected bar red - target "data" is default and eventKey is current element
              return {
                style: Object.assign({}, props.style, {
                  fill: 'red'
                })
              }
            }
          }
        ]
      }
    }
  }
]}
```

**Comment by thongle12** [comment]
Hi @OverYonderCat , can you check it again ?. Your provided code above doesn't work.
