### ISSUE TITLE
Invalid prop `dataComponent` of type `string` supplied to `VictoryPie`, expected a single ReactElement.

### ISSUE THREAD

**Issue by my-name-is-nheo** [FormidableLabs/victory#2086]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory (victory-native)

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Getting invalid prop error, not setting the optional prop. Therefore, using default. 

### Reproduction
![image](https://user-images.githubusercontent.com/58013260/152847961-418d0560-b721-4291-a00d-9faa4d2b799e.png)

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Using FullStory in my app, commenting out the component will load the app, but otherwise, will crash both release and debug version

**Comment by acharyakavita** [comment]
@my-name-is-nheo I was not able to reproduce this issue. I tested it with the below code and it worked fine. Can you share a code sandbox for the same ? Thanks.

```
  <VictoryPie 
      x="stageName"
      y="count"
      data={[{stageName:"abc",count:12,color:"red"},{stageName:"xyz",count:13,color:"blue"}]}
      innerRadius={60}
      radius={75}
      labels={[]}
      height={150}
      width={150}
      style={{data:{fill:({datum})=>datum.color,},}} 
      containerComponent={<VictoryContainer responsive={false}/>}
      />  
```
