### ISSUE TITLE
Spike: Webpack 2 tree shaking

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#209]
I'd like to support the current use of selective imports with descructuring `import { foo } from 'lib'` without taking a bundle weight hit. Let's see how much work it'd be to upgrade to webpack 2 and enable tree shaking (and how much size savings this would give us).

**Comment by okonet** [comment]
Is it implemented or won't be?

**Comment by ryan-roemer** [comment]
@boygirl and @coopy know more about this than I do, but we have audited and will continue to audit our bundles to make sure we have either (1) a plugin that tree shakes (like lodash) or (2) manually ensure that we do one-off imports and never have an import with unused exports. We check things with tools like https://github.com/FormidableLabs/inspectpack#parse which can detect multiple es5 / cjs and es-next-style multiple re-exports (the anti-pattern tree-shaking addresses).

My hunch is we'll wait on issues like:

* https://github.com/webpack/webpack/issues/1750
* https://github.com/lodash/babel-plugin-lodash/issues/75
* https://github.com/rollup/rollup/issues/45

before looking to convert our one-off imports to first class imports that would even implicate tree shaking...
