### ISSUE TITLE
'VictoryTooltip.defaultEvents' reports errors in the Expo environment and the event does not work

### ISSUE THREAD

**Issue by rachelcao277** [FormidableLabs/victory#2120]
# Bug Reports
in Expo `victory-native` occurs this problem.

In the [Custom Tooltip Labels](https://formidable.com/open-source/victory/gallery/custom-tooltip-labels) example, if you add
`Label.defaultEvents = VictoryTooltip.defaultEvents;` the web environment will output the following warning on the console:

Warning: Unknown event handler property `onStartShouldSetResponder`. It will be ignored.
Warning: Unknown event handler property `onResponderTerminationRequest`. It will be ignored.
Warning: Unknown event handler property `onResponderGrant`. It will be ignored.
Warning: Unknown event handler property `onResponderMove`. It will be ignored.
Warning: Unknown event handler property `onResponderRelease`. It will be ignored.
Warning: Unknown event handler property `onResponderTerminate`. It will be ignored.

![image](https://user-images.githubusercontent.com/33114417/154191490-f39fbe53-24bb-4970-9951-e5193aef6251.png)

And it is normal in IOS environment, and the event processing in Web environment does not work

**Comment by becca-bailey** [comment]
Hi @rachelcao277, we have had a few issues come up recently around react native web (#2017, #2120). Right now we're uncertain about whether we will support react native web in the future, but we are working on putting out some guidance around how to work around this issue if you require react native web support. CC: @jpdriver

**Comment by rachelcao277** [comment]
> Hi @rachelcao277, we have had a few issues come up recently around react native web (#2017, #2120). Right now we're uncertain about whether we will support react native web in the future, but we are working on putting out some guidance around how to work around this issue if you require react native web support. CC: @jpdriver

OK, thank you for your reply. The alternative I can think of now is to `import { ** } from 'victory'` under `Expo web` according to "Platform.OS". Is there any better suggestion or scheme?

**Comment by becca-bailey** [comment]
@rachelcao277 We just merged in a documentation update in #2121 that should provide some guidance around React native web support. I hope that helps!

**Comment by rachelcao277** [comment]
> @rachelcao277 We just merged in a documentation update in #2121 that should provide some guidance around React native web support. I hope that helps!

@becca-bailey Thank you for your efforts, this document solved my problem very well. Hope you are getting better
