### ISSUE TITLE
Custom View instead of label component

### ISSUE THREAD

**Issue by codeapp17** [FormidableLabs/victory#2129]
Hello, I am using this library for creating a doughnut chart, but I need to use an icon instead of a label at the text position, Is this possible with this library? Any help would be appreciated

**Comment by becca-bailey** [comment]
@codeapp17 Yes, it is possible to use custom label components. Every Victory component accepts a `labelComponent` prop that defaults to `VictoryLabel`. Here is the documentation for using this prop with `VictoryPie`. https://becca.is/building-a-developer-friendly-interface-with-custom-hooks/

Hope this helps!

**Comment by codeapp17** [comment]
@becca-bailey Yes, I checked the label component but it accepts only the VictoryLabel component which accepts a few props but not the icon. Can it be possible to use the icon instead of VictoryLabel?

**Comment by becca-bailey** [comment]
Here's a quick example of how you might be able to do this using either a custom text component or VictoryLabel. https://codesandbox.io/s/emoji-label-example-6u4hvl?file=/index.js

**Comment by codeapp17** [comment]
Actually, I am using react-native expo and unfortunately, the example didn't work for Image Component as I want to show an icon instead of Text. Here's my code

import { Text, Image, ImageBackground } from "react-native";
function CustomLabel(props) {
    // return <VictoryLabel {...props} text={Images.app_logo} />;
    return (
      <Image {...props} source={Images.app_logo}>
        🔥
      </Image>
    );
  }

**Comment by stevewillard** [comment]
@codeapp17 did you find a workaround? Also having a hard time setting a custom label in react-native/expo

**Comment by codeapp17** [comment]
@stevewillard Yes, I have used the react-native-svg library and  wrap my custom Label component around ForiegnObject imported from SVG. Here's the code



return (
      <G>
        <ForeignObject x={xCordinateIcon} y={yCordinateIcon}>
          <Image source={datum.icon} />
        </ForeignObject>
        <ForeignObject x={xCordinatePercent} y={yCordinatepercent}>
          <TextComponent font={fontNames.SemiBold} size={Fonts.size.medium} color={Colors.black}>
            {datum._y + "%"}
          </TextComponent>
        </ForeignObject>

        <ForeignObject x={xCordinateText} y={yCordinateText}>
          <TextComponent font={fontNames.Medium} size={Fonts.size.xSmall} color={datum.color}>
            {datum.xName}
          </TextComponent>
        </ForeignObject>
      </G>
