### ISSUE TITLE
`sortKey` type not available for `VictoryPie`

### ISSUE THREAD

**Issue by stevemeisner** [FormidableLabs/victory#2139]
# Bug Report

### Checklist

- [ :white_check_mark:] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [ :white_check_mark:] I am using the latest version of Victory

- [ :white_check_mark:] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The `sortKey` prop is not available in types.

### Reproduction

[https://codesandbox.io/s/summer-firefly-dflzch?file=/index.tsx](https://codesandbox.io/s/summer-firefly-dflzch?file=/index.tsx)

**Comment by acharyakavita** [comment]
@stevemeisner Please use 
```sortKey={"x"} ```

**Comment by acharyakavita** [comment]
@ stevemeisner . sorting is working for me. I tried the below code and everything looks fine and works as expected. Please re-open the issue if this does not resolve your issue.

 ```
const Chart = () => {
  const graphData = [
    { x: "1", y: 63 },
    { x: "2", y: 37 },
    { x: "3", y: 45 },
    { x: "4", y: 15 },
  ];
  return (
    <div style={containerStyle}>
     <VictoryPie style={parentStyle} data={graphData} sortKey="x" />
     <VictoryPie style={parentStyle} data={graphData} sortKey="y" />
     <VictoryPie style={parentStyle} data={graphData} sortKey="y" sortOrder="descending"/>
    </div>
  );
```
