### ISSUE TITLE
update to lodash 4

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#216]

**Comment by okonet** [comment]
Also, please consider using of [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) and use ES2015 imports instead of single npm components. This should dramatically decrease build size in projects which already have lodash as dependecy by using Dedupe webpack plugin.

**Comment by ryan-roemer** [comment]
@okonet -- It's unlikely that there will be any effect. We're doing one-off (not `_ = require("lodash")`) already, and as one-offs all the lodash modules we use have single exports. This means webpack is already only including the minimum of what we need and unfortunately even in the future tree-shaking won't have a large effect either.

All that said, we have manually reviewed _all_ our lodash usage and honed it down to the bare minimum that we need. Just know that many lodash single imports -- say `memoize` have a _ton_ of other base dependencies. I've got a brief example here: https://gist.github.com/ryan-roemer/12dcf16efe85f3a28588

**Comment by okonet** [comment]
In my experience, using ES2015 imports `import { map } from 'lodash'` with the babel plugin results in a smaller build size as using single npm modules since each of these modules will have some common dependencies in it.

**Comment by ryan-roemer** [comment]
We're not doing multiple npm modules, we're using root lodash but requiring into it's tree for one off methods like: `const map = require("lodash/collections/map")`.

That should be exactly the same in terms of common dependency resolution / collapsing via webpack at bundle time (and I've got a fair guess it is _exactly the same_ as what the es/babel-ified version ultimately translates to, although I don't have time write now to do a bundle experiment).
