### ISSUE TITLE
VictoryScrollViewContainer to improve UX when chart is larger than the screen

### ISSUE THREAD

**Issue by TomCorvus** [FormidableLabs/victory#2167]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

👋 Hi,

Is it possible to have a container that would allow the user to display chart tooltips while scrolling when the chart is larger than the screen?
The user keeps pressing to display tooltips and when he is on the right of the charts, it is automatically scrolling to display the rest.

If I include the chart in a ScrollView, there is a conflict between the scroll event and the tooltips display, and scroll direction is not adequate.
If I include the chart in a View, the user can't see all of the chart.

https://user-images.githubusercontent.com/3451011/158582474-4e7bc7d6-bf9d-47f1-a526-03553ae8af33.mp4 
https://user-images.githubusercontent.com/3451011/158582628-34a4a628-7ca5-40d4-9af9-8f1f12e09042.mp4

Thanks 🙏

**Comment by TomCorvus** [comment]
@becca-bailey is it something that can be implanted in Victory?

**Comment by becca-bailey** [comment]
I'm not sure if this is something that we have the bandwidth to implement right now, but we can leave this issue open, and PRs are welcome! For now, you can try using the `containerComponent` prop to implement something custom in the consumer application.
