### ISSUE TITLE
View config getter callback for component `g` must be a function (received `undefined`).

### ISSUE THREAD

**Issue by gabrielporcher** [FormidableLabs/victory#2173]
# Bug Reports

### Checklist

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm trying to use SharedEvents to disable the bars tooltip when click on another bar in **React Native**, but seems that theres some problem in the import.
I tried to do this in sandbox and works fine (just removing the merges).

### Reproduction

**The code I'm trying to run is this demo that I found here 

** In my case, I'm importing VictorySharedEvents from victory-native**

https://gist.github.com/boygirl/367b76ab7d6144f43ce3e6a5228fde40

**Comment by rachna-khatnawlia** [comment]
any update on it??

**Comment by SashaPltnchnk** [comment]
@gabrielporcher no luck with that?

**Comment by gabrielporcher** [comment]
> any update on it??



> @gabrielporcher no luck with that?

Due to documentation difficulties I decided to switch to highcharts lib
