### ISSUE TITLE
Change Victory Chart to rtl

### ISSUE THREAD

**Issue by Alreadywinner** [FormidableLabs/victory#2174]
# Questions

**For discussions about features or questions about how to use Victory, please [start a new discussion](https://github.com/FormidableLabs/victory/discussions/new) rather than opening an issue.**

# Bug Reports

### Checklist

- [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [ ] I am using the latest version of Victory

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

I need victory chart to be rtl because the requirement of my client is to make zoom container work from right to left as well as the Y-axis should be fixed to right side. The data will float from right to left

Please describe the feature you're requesting in detail.

**Comment by becca-bailey** [comment]
We are currently tracking this issue in #2108
