### ISSUE TITLE
Unable to show VictoryTooltip on onClick ( touch ) event inside VictoryVoronoiContainer

### ISSUE THREAD

**Issue by Engazan** [FormidableLabs/victory#2176]
### The Problem

Unable to show VictoryTooltip when clicked on chart, but default (hover works) but hover is not ideal for my case ( react-native ), even when i try pass "event"prop from docs it does not trigger 

### Reproduction

https://codesandbox.io/s/affectionate-joana-rput2t?file=/index.js

### Description

I would like to show VictoryTooltip when click on chart, but cant figure it out how to do it when we are in VictoryVoronoiContainer

**Comment by bleszerd** [comment]
You might want to avoid the default behavior of an event by overriding it. Just define the function, but if you want to go further you will have to explore the object better since the documentation doesn't cover this subject very well

```jsx
<VictoryChart
   events={[
     {
       target: 'parent',
       eventHandlers: {
         onTouchEnd: (props, { vIndex }) => {
           // vIndex represents the index of the closest selected element
           console.log(vIndex);
         },
       },
     },
   ]}
/>
```
