### ISSUE TITLE
Zooming on VictoryZoomContainer is slow - victory-native

### ISSUE THREAD

**Issue by St0wy** [FormidableLabs/victory#2180]
### The Problem

Zooming on the `VictoryZoomContrainer` reduces the framerate as low as 10 FPS. I don't have a lot of data, I'm just testing with a `VictoryLine`, but it also happens without anything on the chart.

### Reproduction

Here is my code : 

```js
import { View } from "react-native";
import {
  VictoryLine,
  VictoryChart,
  VictoryTheme,
  VictoryZoomContainer,
} from "victory-native";

export default function App() {
  return (
    <View>
      <VictoryChart
        theme={VictoryTheme.material}
        containerComponent={<VictoryZoomContainer />}
      >
        <VictoryLine
          data={[
            { x: -1, y: -1 },
            { x: 1, y: 1 },
          ]}
        />
      </VictoryChart>
    </View>
  );
}
```

**Comment by vtarelkin** [comment]
@St0wy same. any workarounds?

**Comment by St0wy** [comment]
@vtarelkin In the end I disabled the zoom and used an other library (react-native-border-zoom-view).

**Comment by acharyakavita** [comment]
Hi everyone, we are transitioning all Native development to our new [Victory Native XL](https://github.com/FormidableLabs/victory-native-xl) library which is purpose built for supporting Native. Many of the design decisions we made in this version of Victory is not ideal for Native development.
