### ISSUE TITLE
Exports is not defined

### ISSUE THREAD

**Issue by amansani15** [FormidableLabs/victory#2181]
Export is not defined error

# Bug Reports

### Checklist

- [Yes] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [Yes] I am using the latest version of Victory

- [Yes] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am trying to add victory to one of my projects. I added the victory in the script tag or in the import statement like below:

`<script src="https://npmcdn.com/victory/lib/index.js" type="text/javascript" charset="utf-8" crossorigin></script>`

`import { VictoryPie } from 'https://npmcdn.com/victory/lib/index.js'`

The error I am getting is 
![image](https://user-images.githubusercontent.com/62998123/161823627-eb79fcbf-334d-468c-9786-63a72d6c056b.png)

This is something continuation to the below issue
[https://github.com/reactjs/reactjs.org/issues/4529](url)

I have tried skypack, jsdeliver links as well. Nothing is helping out. 

Any inputs are highly appreciated. TIA

**Comment by ryan-roemer** [comment]
So using `import` means that you need to have use `<script type="module" ` which React doesn't natively support. The example the react site has adds `React` to window globals. Unfortunately, other upstream libraries (like Victory) that import React likely can't us that global in an HTML page context.

Skypack might provide an avenue. And for your current attempted ES module import, you'd want to use the `es` (ESM) not `lib` (CommonJS) version. E.g., something like https://unpkg.com/victory@36.3.1/es/index.js?module=true or I think something like https://cdn.skypack.dev/victory/

Perhaps the best avenue for help is you creating a minimal repository (or single HTML file if that's what you're attempting) that (1) works with React alone, and (2) has what you _want_ to do with Victory that doesn't work, so we can dig into something more tangible to make our diagnosis easier.

Thanks!

**Comment by amansani15** [comment]
Hello Ryan, thank you for the quick reply.

Meanwhile I create a sample repo, I just gave a quick try in using the skypack link which you shared. Below is the error I see now:

![image](https://user-images.githubusercontent.com/62998123/161841359-7bffb7ef-5fec-481d-91f2-149c6b29ba41.png)

I am not sure if it's quick fix at you end in the package.

**Comment by amansani15** [comment]
Hello Ryan, here is the sample repository to the issue what we are facing.

[https://github.com/amansani15/web-apps-node-iot-hub-data-visualization-VictoryCharts](url)

The steps to run the project are mentioned in the readme document. It's pretty straight forward steps, but please let me know if you face any issues.

If I comment out the import victory and victorypie in likebutton.js, then the like button works perfectly. I am unable to use the victory charts within this project. Any kind of help is highly appreciated.

**Comment by ryan-roemer** [comment]
Thanks for the repo. I've now run:

```sh
$ npm install
$ npm run start
```

When navigating to: http://127.0.0.1:3000/ the error in the console I get is:

```
Uncaught ReferenceError: require is not defined
    at <anonymous>:5:16
    at i (babel.min.js:24:29679)
    at r (babel.min.js:24:30188)
    at e.src.n.<computed>.l.content (babel.min.js:24:30503)
    at XMLHttpRequest.n.onreadystatechange (babel.min.js:24:29946)
```

Which makes sense because you have code like `import` (which gets translated to `require`). What you have to do use the UMD versions of _all_ the libraries and place imports on `window` globals. Fortunately, victory does this, so you can use `window.React` from existing UMD import and `window.Victory` from the Victory UMD import.

_Note_: Not all modern React libraries use this approach. The better, big approach is to use an actual build with like webpack and produce a single frontend bundle to include without trying to do this all in Vanilla JS with runtime babel translation (which your babel lib even console logs it shouldn't be used in production). That said, I do like Vanilla JS and you could get rid of Babel + JSX by using something fully runtime like https://github.com/developit/htm

Anyways, here's a diff to make your code work and give you a path forward with your current approach:

```diff
diff --git a/public/index.html b/public/index.html
index 0239ca0..4142b6d 100644
--- a/public/index.html
+++ b/public/index.html
@@ -14,20 +14,26 @@
     <title>Testing Victory charts</title>
 </head>
 
-<body>    
+<body>
     <div>
         <canvas id="iotChart"></canvas><br>
     </div>
 
     <!-- We will put our React component inside this div. -->
-    <div id="like_button_container"></div> 
+    <div id="like_button_container"></div>
 
     <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
     <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
     <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
+    <script src="https://unpkg.com/victory@36.3.1/dist/victory.js"></script>
 
+    <script>
+      // Check Victory and React available.
+      console.log("Checking imports", { React, Victory });
+    </script>
     <!-- Load our React component. -->
     <script src="js/src/likebutton.js" type="text/babel"></script>
+
 </body>
 
 </html>
\ No newline at end of file
diff --git a/public/js/src/likebutton.js b/public/js/src/likebutton.js
index 9423607..0a0e338 100644
--- a/public/js/src/likebutton.js
+++ b/public/js/src/likebutton.js
@@ -1,6 +1,11 @@
 'use strict';
 
-import {VictoryPie} from 'victory'
+// Can't use real `require` or `import`. Have to use globals on `window`
+// loaded in a separatae script tag.
+// WON'T WORK -- import { VictoryPie } from 'victory'
+
+const { VictoryPie } = Victory;
+// Note: `React` globally available
 
 const e = React.createElement;
 
@@ -33,4 +38,4 @@ class LikeButton extends React.Component {
 }
 
 const domContainer = document.querySelector('#like_button_container');
-ReactDOM.render(e(LikeButton), domContainer);
\ No newline at end of file
+ReactDOM.render(e(LikeButton), domContainer);
```

Hope that gets you going and good luck!

**Comment by amansani15** [comment]
Thank you, I will look into it. For a quick test, it's running at my end as well now. But there are few things left for me to test, so I will work on testing different parts. 

Thanks again for quick fix
