### ISSUE TITLE
React 18 support?

### ISSUE THREAD

**Issue by wadehammes** [FormidableLabs/victory#2187]
When can we expect React 18 support (mainly around updating peer dependencies and adopting new hydration methods?)

**Comment by becca-bailey** [comment]
I'll try to get a PR up for this today.

**Comment by becca-bailey** [comment]
We can start to work on this - right now the biggest blocker is the fact that there is no Enzyme support in React 18, and it doesn't sound like that's going to change anytime soon. So if we upgraded all of Victory's dependencies, we would have to re-write a lot of our tests as well.

**Comment by wadehammes** [comment]
I don't blame you on holding off then! Thanks for the update.

**Comment by wadehammes** [comment]
Oh my, just looked at the Enzyme Github and they still don't officially support React 17 yet lol. Maybe time to switch testing libraries?

**Comment by becca-bailey** [comment]
@wadehammes Yep, I just opened an issue for that. It's probably about time for us to overhaul our testing anyway!

**Comment by stur86** [comment]
Has there been any progress on this? The latest release mentions adding react testing library, is this switch not complete yet or is the dependency in `package.json` lagging behind? Since it's just a testing issue, can I try simply forcing the install and have it work anyway?

**Comment by becca-bailey** [comment]
@ryan-roemer Do you see any issue with us upgrading the `peerDependencies` on our packages so consumers can use React 18?

**Comment by ryan-roemer** [comment]
@becca-bailey -- I tried this over the weekend. For our tests (and our `devDependencies`, there are failures in Karma and IIRC Jest too for `.render()` or something.  For our `peerDependencies`, I think it's fine to do the `|| ^ 18.0.0` if we have other reports and indications that the current library is fine with 18.

**Comment by stur86** [comment]
Thanks! I've ended up using `--force` and the basic examples seem to work fine with React 18. I'll let you know if I find any bugs!
