### ISSUE TITLE
Replace Enzyme with React Testing Library

### ISSUE THREAD

**Issue by becca-bailey** [FormidableLabs/victory#2195]
In addition to some of the general issues with our tests being a little slow and out of date, we will need to replace Enzyme as our method of rendering components in tests if we want to upgrade to React 18+. 

We should re-write our existing tests using Jest + React Testing Library.

Related issue: #2187 

See also: https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl

## Completed packages

- [x] victory
- [x] victory-area
- [x] victory-bar
- [x] victory-box-plot
- [x] victory-brush-container
- [x] victory-candlestick
- [x] victory-chart
- [x] victory-core
- [x] victory-errorbars
- [x] victory-group
- [x] victory-histogram
- [x] victory-legend
- [x] victory-line
- [x] victory-pie
- [x] victory-scatter
- [x] victory-selection-container
- [ ] victory-shared-events (this might be going away soon, so it's a lower priority test suite to convert)
- [x] victory-stack
- [x] victory-tooltip
- [x] victory-voronoi

## General tips and pointers

- We can use `querySelector` in a test to test attributes on SVG elements. 
- We can also use `getByRole` or `getByTestId` to isolate specific nodes. #2191 should allow us to add `data-testid` to our test components, but there may be some primitive components that need to be set up to work with these user-provided props.
- We can replace some of the test assertions with `.toMatchInlineSnapshot`, provided that the snapshot is focused (< 10 lines) and easy to read. 
- If we want to test the data that is being passed to the SVG component, there are some workarounds we can use, such as giving our test component a property that outputs the rendered data as JSON. Here is an example:

```jsx
it("renders data ordered by value of sortKey, if given", () => {
      const data = [{ t: 0 /*x: 10, y: 1*/ }, { t: 1 /*x:  9, y: 1*/ }];
      const { container } = render(
        <VictoryLine
          data={data}
          sortKey="t"
          x={({ t }) => 10 - t}
          y={() => 1}
          dataComponent={
            <Curve data-json={(props) => JSON.stringify(props.data)} />
          }
        />
      );

      const line = container.querySelector("path");
      const renderedData = JSON.parse(line.getAttribute("data-json")).map(
        ({ t }) => t
      );

      expect(renderedData).toEqual([0, 1]);
    });
```
Long-term, we might want to figure out how to test data transformations in a different place.

**Comment by heythisispaul** [comment]
@becca-bailey I can start work on victory-bar.

**Comment by heythisispaul** [comment]
#2216 for victory-bar tests should be good to go, I'm moving on to victory-box-plot.

**Comment by becca-bailey** [comment]
I'm going to start work on `victory-core`.

**Comment by becca-bailey** [comment]
I am working on victory-errorbar next.

**Comment by heythisispaul** [comment]
I'm picking up victory-histogram now

**Comment by heythisispaul** [comment]
#2255 is up for the histogram tests, moving on to `victory-legend`

**Comment by heythisispaul** [comment]
Moving on to `victory-pie`

**Comment by becca-bailey** [comment]
The modules that were excluded from this conversion are `add-events` and `victory-shared-events`, due to their heavy reliance on mocking and class inheritance. We are going to re-write those tests once we refactor Victory events and state management.
