### ISSUE TITLE
Not able to place image instead of default line in - cursorComponent of VictoryCursorContainer in VictoryLine chart

### ISSUE THREAD

**Issue by naikvaishnav3** [FormidableLabs/victory#2200]
# Questions

How to place image instead of default Line in - cursorComponent of VictoryCursorContainer in VictoryLine chart

# Bug Reports
Not able to place image instead of default line, for cursorComponent of VictoryCursorContainer in VictoryLine chart.

### The Problem
Not able to place image instead of default line, for cursorComponent of VictoryCursorContainer in VictoryLine chart

### Description

Not able to place image instead of default line, for cursorComponent of VictoryCursorContainer in VictoryLine chart

Current Code: 
```

<VictoryChart
    standalone={true}
    height={setHeight(161)}
    width={setWidth(320)}
    domainPadding={{ y: 10 }}
    containerComponent={
      <VictoryCursorContainer
        cursorDimension="x"
        
        cursorComponent={
          <Line
            style={{
              stroke: "gray",
              strokeWidth: 2,
            }}
          />
        }
        onCursorChange={this.handleCursorChange.bind(this)}
      />
    }
  >

  <VictoryAxis
    standalone={false}
    style={{
      axis: {
        stroke: '#00000014'  //CHANGE COLOR OF X-AXIS
      },
      tickLabels: {
        fill: '#00000066', fontSize: 12 //CHANGE COLOR OF X-AXIS LABELS
      },
    }}
  />
  <VictoryAxis
    tickFormat={t => `${t}k`}
    dependentAxis
    domain={[0, 50]}
    orientation="left"
    standalone={false}
    style={styles.axisOne}
    
  />
   <VictoryLine
      style={{
        data: {
          stroke: "#0A68CC",
          strokeWidth: 2
        }
      }}
      interpolation="natural"
      data={lineA}
      
    />
     <VictoryLine
      style={{
        data: {
          stroke: "#F2BD49",
          strokeWidth: 2
        }
      }}
      interpolation="natural"
      data={lineB}
    />
  </VictoryChart>
```

Current Design with line as below:
<img width="281" alt="current" src="https://user-images.githubusercontent.com/102343699/165927765-d58b8744-c71f-4298-9af0-7b21fc1e2a88.png">

Expecting image on cursor movement, as shown in screenshot, instead of line:
<img width="328" alt="Expected" src="https://user-images.githubusercontent.com/102343699/165925995-42334543-65c1-486e-9371-35792d216467.png">

**Comment by naikvaishnav3** [comment]
@becca-bailey, I have updated question with current and expected behaviour and also added code snippet. Please let me know if we can achieve this graph with image instead of default line.

**Comment by naikvaishnav3** [comment]
@becca-bailey - Any update?

**Comment by becca-bailey** [comment]
I'm still not sure I understand this issue. Is it a styling issue where the line isn't styled the way you are expecting, or is the cursor actually not functioning as expected?

**Comment by naikvaishnav3** [comment]
Not trying to re-style the cursor line. Actually, trying to use an image (like a png or a jpeg file).

**Comment by radekzz** [comment]
@becca-bailey In my case i just need to modify styles of the cursor line. Could you please give me a hint how to do that?
