### ISSUE TITLE
VictoryLegend not properly rendering with VictoryGroup

### ISSUE THREAD

**Issue by ricohumme** [FormidableLabs/victory#2202]
### The Problem
Hi,

I trying to implement a horizontal stacked barchart and wanting to add a legend to this to explain the bars.
However, due to the nature of these bars, I need them to render without any Axis so I read I should use VictoryGroup instead of VictoryChart.
This does in fact render the chart without any axis, but instead renders the legend partially / malformed or not at all.

### Reproduction

For this I created a snack with 2 components showcasing this issue.
https://snack.expo.dev/@ricohumme/stackedbarchart-example

**Comment by Saf3ty1nnumb3rs** [comment]
@ricohumme  I was unable to fully render the VictoryLegend component with the VictoryGroup component and I was able to easily reproduce your results.
I did figure out an alternative solution to your issue without VictoryGroup though: [https://snack.expo.dev/@f13ldd4y/stackedbarchart-example](https://snack.expo.dev/@f13ldd4y/stackedbarchart-example) 

You may have already solved your problem, but if not, I hope that helps. 😁
