### ISSUE TITLE
Infra: New monorepo management tools

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/victory#2205]
The following two tools are now deprecated (and somewhat related in task execution). We should find replacements:

- `lerna`
- `nps`

Dependency management:

- `yarn1`: Has issues with upgrading package deps (See #2203 )
- `yarn2+`: Not a lot of community uptake and it runs a monkey-patched version of Node to work.
- `npm`: Is it better now with workspaces
- `pnpm`: Looks like nice [workspaces](https://pnpm.io/workspaces) support.
    - Has `hoisted` option for `victory-vendor` hopefully?

Monorepo options:

- Yarn workspaces
- [nx](https://nx.dev/)
- [Turborepo](https://turborepo.org/)

Task execution options:

- Ye olde npm `scripts`
- [Wireit](https://github.com/google/wireit)

Release options:

- [changesets](https://github.com/changesets/changesets)

Notes:

- https://monorepo.tools/

**Comment by becca-bailey** [comment]
Urql uses npm workspaces + changesets for change management and deployment. They don't have the same number of packages to manage, but we may want to consider adopting the same tooling for consistency across our repos.
