### ISSUE TITLE
Label value is displaying adjacent to the bar

### ISSUE THREAD

**Issue by akumath14** [FormidableLabs/victory#2211]
# Questions

**For discussions about features or questions about how to use Victory, please [start a new discussion](https://github.com/FormidableLabs/victory/discussions/new) rather than opening an issue.**

# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I would like to have all chart labels right-aligned so that they appear in a single column rather than being stacked at the end of the corresponding bar in each row.
![Screen Shot 2022-05-03 at 2 12 39 PM](https://user-images.githubusercontent.com/82956848/166525853-a42e7841-6ca5-4445-93c1-5b4a2ba2a150.png)

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by akumath14** [comment]
Can someone provide me with some information on this?

**Comment by lauradecc** [comment]
I had a similar issue and solved it by passing the property `y` to the component instance that `labelComponent` takes (it would be `x` in your case, as you are using horizontal bars). 

You can try to use this example code on the editable source window under the [labelComponent section](https://formidable.com/open-source/victory/docs/common-props/#labelcomponent) to check if it solves your need:
```
<VictoryBar
  data={sampleData}
  horizontal
  labels={({ datum }) => datum.y}
  style={{ labels: { fill: "red" } }}
  labelComponent={<VictoryLabel  x={410} />}
/>
```

**Comment by rachnarai** [comment]
> I had a similar issue and solved it by passing the property `y` to the component instance that `labelComponent` takes (it would be `x` in your case, as you are using horizontal bars).
> 
> You can try to use this example code on the editable source window under the [labelComponent section](https://formidable.com/open-source/victory/docs/common-props/#labelcomponent) to check if it solves your need:
> 
> ```
> <VictoryBar
>   data={sampleData}
>   horizontal
>   labels={({ datum }) => datum.y}
>   style={{ labels: { fill: "red" } }}
>   labelComponent={<VictoryLabel  x={410} />}
> />
> ```

I wish to have a different labels in a Bar graph. 
I want to have SVGs on it. 
How could I do that?
