### ISSUE TITLE
Tooltip multiplied by number of groups, duplicate values

### ISSUE THREAD

**Issue by JeffBaumgardt** [FormidableLabs/victory#2224]
# Questions

**For discussions about features or questions about how to use Victory, please [start a new discussion](https://github.com/FormidableLabs/victory/discussions/new) rather than opening an issue.**

# Bug Reports

### Checklist

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

I did find references to similar issues and tried the various examples included in the issues
#545

### The Problem

I have a chart with two groups, a line + scatter. I originally put labels on each group component but a tooltip for one label is under the second line, see example screenshot.

I changed to putting the tooltip in the Voronoi container, but now the labels are duplicated, see example screenshot. I tried using the blacklist but that made one group unresponsive to mouse action, and didn't clear the duplicated label.

### Reproduction

 * With Voronoi Container tooltip - https://codesandbox.io/s/priceless-paper-4xirhj
 * **Note** I could not reproduce the line through the tooltip in code sandbox, I copied the code back and forth verbatim. Only differences would be global css (I have no specific targets from my css) and data, mine is in an api, the data in codesandbox is a straight copy.
 
Screenshots from application

* Duplicated labels
![Screen Shot 2022-05-09 at 11 58 28 AM](https://user-images.githubusercontent.com/777527/167478471-d26cb222-2e1f-47da-ab49-ca67082e05ae.png)

* Line through tooltip
![Screen Shot 2022-05-09 at 11 57 59 AM](https://user-images.githubusercontent.com/777527/167478603-fb2e570c-fbbd-471b-8f2e-275124b1ced8.png)

I have tried to put the labelComponent on the group, the line of each group and I get the first tooltip under the second line.

I would like to keep the mouse and tooltip to appear when close to the individual scatter point rather than on just 'x'.

Also side note, if I put the labels in the VoronoiContainer with the x dimension I get the label duplicated 4 times.

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

**Comment by Saf3ty1nnumb3rs** [comment]
Hello, using the blacklist and canceling the tooltip on **two** fo the scatter plots does indeed cause one line to be unresponsive, however, just blacklisting **one** scatter enabled the tooltip on all plot points without duplication: [forked sandbox with working tooltips](https://gojbwl.csb.app/) . Hope that helps.

**Comment by JeffBaumgardt** [comment]
@Saf3ty1nnumb3rs Thank you very much for your repo. It does work as expected. As a side note I still had the double render of the labels on the second group. Not sure why it matters, but on my `<VictoryLine>` I also had a name, different name, but a name none the less. As soon as I removed the name prop the double tooltip reverted back to the expected single pass render.

If I have time someday I might have a gander at the label logic and see why the name prop would seem to duplicate the labels.

But alas for today you have helped me solve my issue.
