### ISSUE TITLE
Radium constraints

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#224]
- [x] initial constraints builder
- [x] small subset of autolayout / fork it
- [x] packaging workers (ideas @baer @ryan-roemer)
- [x] whitelist of supported elements

**Comment by baer** [comment]
I'm excited to learn but I don't have immediate experience with web workers. Let me know if you want me to help in the effort.

**Comment by tptee** [comment]
`radium-constraints@0.3.0` is a good start!
