### ISSUE TITLE
`active` prop not triggering properly for `VictoryScatter` inside `VictoryStack` and `VictoryGroup`

### ISSUE THREAD

**Issue by Kerumen** [FormidableLabs/victory#2242]
# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)
- [x] I am using the latest version of Victory
- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The `active` prop of the second `VictoryScatter` is not triggered when I hover the chart. There should be 2 active dots but I'm only seeing the one from the first `VictoryScatter`.
NB: I have the issue on `react-native` but I managed to reproduce it on the web.

### Reproduction

https://codesandbox.io/s/gallant-lederberg-sksj0s

**Comment by embooglement** [comment]
I'm encountering this issue as well. Is there any workaround?

**Comment by acharyakavita** [comment]
I got it working by passing  a "name" parameter into VictoryScatter.
https://codesandbox.io/p/sandbox/fervent-shirley-j2vqwh?file=%2Findex.js
