### ISSUE TITLE
Orientation 'right' not working with dates

### ISSUE THREAD

**Issue by matejfalat** [FormidableLabs/victory#2251]
### The Problem
Setting `orientation = "right"` doesn't seem to work properly when values are date objects. Tick labels are moved to the right, but the axis remains on the left. 

### Reproduction

https://codesandbox.io/s/interesting-nova-q14s3v?file=/index.js

**Comment by zfrankdesign** [comment]
I think I am having a similar issue 😬 If I add enough padding on the right side things work, but that's not ideal.

**Comment by zfrankdesign** [comment]
> ### The Problem
> Setting `orientation = "right"` doesn't seem to work properly when values are date objects. Tick labels are moved to the right, but the axis remains on the left.
> 
> ### Reproduction
> https://codesandbox.io/s/interesting-nova-q14s3v?file=/index.js

@matejfalat I seemed to get my padding and y axis orientation (on the right) problems working by converting the date values in my data to numbers i.e. `new Date(date).setHours(0, 0, 0, 0)` no clue why this works, but it seems to stop my y axis from rendering on the left

**Comment by scottarver** [comment]
Here is a fork of the codesandbox that shows it working and not working if you comment line 20

https://codesandbox.io/s/sleepy-orla-qjq68f?file=/index.js

**Comment by scottarver** [comment]
I've got it narrowed down to a Date equality bug. 

![image](https://github.com/FormidableLabs/victory/assets/6730885/4b777732-37d6-4bba-9edb-deaf444d14a6)
![image](https://github.com/FormidableLabs/victory/assets/6730885/65b21e2b-82b6-4d69-830e-dd0106176765)
