### ISSUE TITLE
'VictoryPie' cannot be used as a JSX component

### ISSUE THREAD

**Issue by dht** [FormidableLabs/victory#2258]
# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)
- [x] I am using the latest version of Victory
- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I've followed the getting started section and getting:
```
(alias) class VictoryPie
import VictoryPie
'VictoryPie' cannot be used as a JSX component.
  Its instance type 'VictoryPie' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/Users/dht/projects/gli/node_modules/@types/styled-components/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.ts(2786)
```

**Comment by becca-bailey** [comment]
Hi @dht, are you able to reproduce this error in code sandbox? Without more information about your environment it will be hard to reproduce it on our end.

**Comment by dht** [comment]
@becca-bailey 
Yes , I believe this issue can be closed, as @giacomoalonzi mentioned this is related to an issue with the new React 18 which is not victory-related and can be solved by installing the latest react types.
