### ISSUE TITLE
NPM install ERROR!!!

### ISSUE THREAD

**Issue by NiuGuohui** [FormidableLabs/victory#2263]
# Questions
Package `victory-bar@36.4.1` has some error when I run `npm i  victory-native`!
<img width="617" alt="image" src="https://user-images.githubusercontent.com/37471959/170407903-d13b7191-3731-4408-bbbf-9aaa01aa1c71.png">

**For discussions about features or questions about how to use Victory, please [start a new discussion](https://github.com/FormidableLabs/victory/discussions/new) rather than opening an issue.**

# Bug Reports

### Checklist

- [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [ ] I am using the latest version of Victory

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by NiuGuohui** [comment]
@becca-bailey

**Comment by becca-bailey** [comment]
Have you been getting this consistently? We pushed out a release yesterday for victory 36.4.1, and according to npm `victory-bar@36.4.1` definitely exists. https://www.npmjs.com/package/victory-bar

I tried to reproduce this locally, but didn't see the same error.

**Comment by NiuGuohui** [comment]
Oh sorry, that's a problem with my private repository.
