### ISSUE TITLE
getting "fontFamily "'Gill Sans', 'Seravek', 'Trebuchet MS', sans-serif" is not a system font and has not been loaded through Font.loadAsync" on React Native

### ISSUE THREAD

**Issue by giacomoalonzi** [FormidableLabs/victory#2267]
# Questions

**For discussions about features or questions about how to use Victory, please [start a new discussion](https://github.com/FormidableLabs/victory/discussions/new) rather than opening an issue.**

# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

In react native I've started to get this error when VictoryChart is loaded

```
fontFamily "'Gill Sans', 'Seravek', 'Trebuchet MS', sans-serif" is not a system font and has not been loaded through Font.loadAsync.
```

**Comment by poplingue** [comment]
This error occured in my project. Any idea where it comes from?
