### ISSUE TITLE
`renderInPortal` is not supported outside of `VictoryContainer`. Component will be rendered in place

### ISSUE THREAD

**Issue by makhataibar** [FormidableLabs/victory#2270]
# Questions

**For discussions about features or questions about how to use Victory, please [start a new discussion](https://github.com/FormidableLabs/victory/discussions/new) rather than opening an issue.**

# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [ ] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

`renderInPortal` is not supported outside of `VictoryContainer`. Component will be rendered in place

That warning showed in Expo app when I'm launch in iOS
### Reproduction

```
<VictoryChart
            theme={VictoryTheme.material}
            padding={{ top: 0, left: 0, right: 0, bottom: 25 }}
            containerComponent={<VictoryVoronoiContainer />}
            width={victoryChartWidth}
            height={victoryChartHeight}
          >
            <VictoryArea
              style={{
                data: { stroke: '#6A30FF', fill: '#F4EFFF' },
              }}
              data={chartData}
              labelComponent={<VictoryTooltip constrainToVisibleArea />}
            />
            <VictoryAxis
              orientation={'bottom'}
              tickFormat={(tick, index) => (index === 0 ? tick : '')}
              tickLabelComponent={<VictoryLabel textAnchor={'start'} />}
            />
            <VictoryAxis
              orientation={'bottom'}
              tickFormat={(tick, index, ticks) => (index === ticks.length - 1 ? tick : '')}
              tickLabelComponent={<VictoryLabel textAnchor={'end'} />}
            />
          </VictoryChart>
```

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description
"victory-native": "^36.3.2"

Expo 44, iOS

**Comment by dlehddnjs** [comment]
Is there any progress on this issue?
I have same problem.

**Comment by Norcy** [comment]
+1
