### ISSUE TITLE
App crashes on victory-native iOS on specific versions. TypeError: undefined is not a function (near '...Object.fromEntries...')

### ISSUE THREAD

**Issue by AliZaib-Emumba** [FormidableLabs/victory#2272]
I am getting this error at victory-chart for iOS version 11.4. On other versions it is working fine.
The app crashes as soon as the screen is loaded with the chart and displays the following error.

```
TypeError: undefined is not a function (near '...Object.fromEntries...')

This error is located at:
    in VictoryChart (created by VictoryChart)
.
.
.
```

I have updated to the latest version and tried re-installing the module but still no change observed.

**Comment by jpdriver** [comment]
hey @AliZaib-Emumba 👋🏻 please can you provide a reproduction / chart code sample for this?

it looks like this might be a bug in `victory-core` as that's [the only place](https://github.com/FormidableLabs/victory/blob/main/packages/victory-core/src/victory-util/user-props.js#L76-L82) we use `Object.fromEntries()`

i'm not sure whether that's supported or not in `react-native` -- it may be that we just need an extra polyfill or to use `core-js` or something

**Comment by babyg-neel** [comment]
For me it is happening in Android. I just installed the library and then after running seeing this issue.

**Comment by antonandreyev** [comment]
Happening for us in this setup:
- react-native 0.66.4
- victory 36.6.8
- iOS 12.1, iPhone 8

Using VictoryAxis, VictoryLabel, VictoryTooltip, VictoryBar, VictoryChart, VictoryContainer

Not happening on iOS 12.3, iPhone XS

**Comment by kiranojhanp** [comment]
also happening in android

**Comment by kiranojhanp** [comment]
Update: Use this package for the fix

https://www.npmjs.com/package/polyfill-object.fromentries
