### ISSUE TITLE
VictoryLabel on Android renders duplicate emoji characters on top of each other.

### ISSUE THREAD

**Issue by Tuuben** [FormidableLabs/victory#2297]
# Questions

**For discussions about features or questions about how to use Victory, please [start a new discussion](https://github.com/FormidableLabs/victory/discussions/new) rather than opening an issue.**

# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Rendering Emoji strings with `<VictoryLabel />` on Android causes some weird issues where the Emoji renders twice on top of each other.

Pie chart example: 
<img width="567" alt="Screenshot 2022-06-10 at 17 00 39" src="https://user-images.githubusercontent.com/22411478/173082239-4a311c58-b0e5-424e-aa81-1070be09baae.png">

Bar chart example:
<img width="607" alt="Screenshot 2022-06-10 at 11 18 21" src="https://user-images.githubusercontent.com/22411478/173082273-46f5d1b9-05fc-48df-a8ea-4fcd80efe415.png">

Example where normal text + emoji's are rendered as a label on pie chart:
<img width="337" alt="Screenshot 2022-06-10 at 11 10 18" src="https://user-images.githubusercontent.com/22411478/173082482-e155e9b8-1c59-4a93-ae68-b7647ab11622.png">

### Reproduction

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

https://github.com/Tuuben/VictoryChartRNAndroidEmojiLabelBug/tree/main

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by oromis300** [comment]
We had the same problem. Do you manage to work around it ?

**Comment by j1mie** [comment]
Fixed this by adding a custom tick label component

```jsx

import { Text } from 'react-native'
import { ForeignObject } from 'react-native-svg'
...

<VictoryAxis
  dependentAxis
  tickLabelComponent={<TickLabel />}
/>

...

const TickLabel = (props: { text?: string; y?: number }) => {
  const { y, text, ...rest } = props

  return (
    <ForeignObject {...rest} y={y - 10}>
      <Text>{text}</Text>
    </ForeignObject>
  )
}

```
