### ISSUE TITLE
Typescript readonly data array is incompatible with data property interface definition

### ISSUE THREAD

**Issue by mward-sudo** [FormidableLabs/victory#2309]
### The Problem

I'm attempting to use a functional programming style to the extent it is possible to do so using the JavaScript frameworks I am using.

As part of this effort, I am defining my arguments and data constructs as readonly using TypeScript so that my data is not mutable.

However, I am experiencing an issue with Victory in that the TypeScript interface for the `data` property (on the `VictoryLine` component for example) cannot accept a readonly value because its typescript definition is using the mutable `any` type.

I get the following error:

`The type 'ChartData' is 'readonly' and cannot be assigned to the mutable type 'any[]'.`

### Reproduction

https://codesandbox.io/s/winter-tree-00wu4z?file=/index.tsx

### Potential Solution

In limited testing I tried changing the definition for the `data` property from `any[]` to `any[] | readonly any[]` and this solved the TypeScript error, but I haven't tested this properly.

If this issue is accepted, and the above is deemed an acceptable solution, then I will create a PR that modifies the TypeScript interfaces in the correct places.

**Comment by becca-bailey** [comment]
Thanks for reporting this issue! We have been working on a Typescript conversion on our end, and there might be some kinks to work out with some of the typings.  FYI @scottrippey.

**Comment by scottrippey** [comment]
I see no issue with marking `data` as `readonly`, since we never mutate it.  I'll include it in my existing PR #2306
