### ISSUE TITLE
Module not found: Error: Can't resolve 'use-context-selector'

### ISSUE THREAD

**Issue by starpit** [FormidableLabs/victory#2322]
# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

victory-core/es/victory-state seems recently to have added a dependence on `use-context-selector` without expressing this dependence in its package.json. As a result, webpack builds now fail.

Further complicating matters... the latest several versions of `use-context-selector` depend on `react >= 18`... so I'm not even sure how you all would express a dependence on this node module in a way that allowed for that kind of flexibility. oof. 

of note, patternfly, which uses you, is not yet react 18, and yet they express a `^` floating dependence on you that brings in this breaking change!

Full error message:
> Module not found: Error: Can't resolve 'use-context-selector' in '.../node_modules/victory-core/es/victory-state'

The fix, for react 17 users, is `npm install use-context-selector@1.1`; >1.1 have a react >= 18 dependence

### Reproduction

todo

**Comment by becca-bailey** [comment]
Thanks for reporting this bug - we introduced a dependency on use-context-selector in some of the preliminary work we are doing on the re-write, but we will either remove this dependency or make sure we are using a version that is compatible with previous React versions, and get a fix out ASAP. For now, you can also pin your Victory version on `3.5.0` until we release a fix.

**Comment by becca-bailey** [comment]
This is resolved in 36.5.2
