### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'animate')

### ISSUE THREAD

**Issue by jailsonpaca** [FormidableLabs/victory#2327]
**Describe the bug**
When I build my project made with vitejs in production mode, and open some page with charts, this page broken

**Victory version**
"victory": "36.5.1",

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14353246/175634258-33763eb1-04e8-413c-826f-513458a332bd.png)

**Desktop (please complete the following information):**
 - OS: pop-os
 - Browser chrome

**Additional context**
This problem only happens with the prop animate in victory components

**Comment by jailsonpaca** [comment]
fixed in #2329

**Comment by Burnett2k** [comment]
As @jailsonpaca mentions, this is fixed in https://github.com/FormidableLabs/victory/issues/2329. Closing this issue.
