### ISSUE TITLE
[victory-native] VictoryPie border width is inconsistent with Samsung Galaxy devices.

### ISSUE THREAD

**Issue by guangyu-moves** [FormidableLabs/victory#2328]
**Describe the bug**
Samsung Galaxy border widths are barely visible relative to Google Pixel and other Android devices.

**Victory version**
victory-native: `36.4.1`

**Code Sandbox link**

You will need to run this on a Google Pixel or any other Android phone vs Samsung Galaxy to tell the difference. They all look the same in the sandbox.

https://snack.expo.dev/@gsong-moves/victory-pie-looks-small-on-samsung-galaxy-devices

**To Reproduce**
1. Run on a Samsung Galaxy device. The border width of the ring will be barely visible, sometimes invisible depending on the device.
2. Run on a non-Samsung device.

**Expected behavior**
Samsung galaxy devices does not render the Victory Pie inner radius the same way as other Android devices.

**Screenshots**

Google Pixel 5
<img width="268" alt="Screen Shot 2022-06-24 at 2 32 53 PM" src="https://user-images.githubusercontent.com/86622911/175644566-cd168d63-9a2a-45a8-87ae-4346e3529dc2.png">

Samsung Galaxy S9-22
<img width="310" alt="Screen Shot 2022-06-24 at 2 33 17 PM" src="https://user-images.githubusercontent.com/86622911/175644614-7a896d8b-7cbd-493e-91a6-a99aa589425e.png">

Extreme example (The border is so thin that no colors show up):
<img width="314" alt="Screen Shot 2022-06-24 at 2 34 33 PM" src="https://user-images.githubusercontent.com/86622911/175644766-7418623d-3d30-4fbf-b852-c4bda73b66b1.png">

**Desktop (please complete the following information):**
**N/A**

**Smartphone (please complete the following information):**
 - Device: **Samsung Galaxy S9 to S22**
 - OS: **Android**
 - Version: **9, 10 (haven't tested other ones)**

**Additional context**
The inner radius differs even across different Samsung Galaxy devices. 

We have tested on a dozen devices. Including:

<img width="676" alt="Screen Shot 2022-06-24 at 2 38 39 PM" src="https://user-images.githubusercontent.com/86622911/175645516-7de520ef-adf1-45c5-9b7b-772a0c0e30de.png">

**Comment by acharyakavita** [comment]
Hi everyone, we are transitioning all Native development to our new [Victory Native XL](https://github.com/FormidableLabs/victory-native-xl) library which is purpose built for supporting Native. Many of the design decisions we made in this version of Victory is not ideal for Native development.
