### ISSUE TITLE
No longer export types in v36.5.2

### ISSUE THREAD

**Issue by tanigaki39** [FormidableLabs/victory#2330]
**Is your feature request related to a problem? Please describe.**
I have used exported types such as VicoryTooltipProps or FlyoutProps to extend my own components.
However, they are no longer exported in v36.5.2.
Is there a plan to export them again in future version?

**Describe the solution you'd like**
Export `xxxProps`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by scottrippey** [comment]
Thanks for reporting this! It looks like a bug with our latest release. We will get this fixed asap.
As a temporary workaround, you can use an older version. Will update here once this is fixed.

**Comment by scottrippey** [comment]
Fixed in `36.5.3`
