### ISSUE TITLE
error after running yarn lint

### ISSUE THREAD

**Issue by 3KINGZ** [FormidableLabs/victory#2337]
**Describe the bug**
am getting an error when running yarn lint
export { Border as Box, type BorderProps as BoxProps, } from "./victory-primitives";

**Victory version**
^36.5.3

**Code Sandbox link**
Please include a code sandbox link or a similar reproduction if possible.

**To Reproduce**
1.yarn lint

**Expected behavior**
export { Border as Box, type BorderProps as BoxProps, } from "./victory-primitives";

**Desktop (please complete the following information):**
 - android/ios

**Comment by scottrippey** [comment]
This has been fixed in the latest version. Thanks for reporting!
