### ISSUE TITLE
Component Request: Radar Chart

### ISSUE THREAD

**Issue by ElliotChong** [FormidableLabs/victory#234]
I was curious if there are any plans for the inclusion of a [Radar Chart](https://en.wikipedia.org/wiki/Radar_chart) into Victory, and if not, start a discussion on requirements.

I'll need a Radar Chart in an upcoming project and may take a swing at implementing one if there hasn't been any work already and time permitting.

**Comment by boygirl** [comment]
Hi @ElliotChong 

Radar chart is not currently in progress, and help is definitely welcome. More contribution resources (and new project templating in particular) should be ready by the end of this week. If you were thinking of starting sooner, let me know and I'll try to answer any questions you might have about how to get started or make sure your component is consistent with the others.

**Comment by boygirl** [comment]
polar charts were released in `victory@0.21.0`. :)
