### ISSUE TITLE
SVG outgrows VictoryContainer's Flexbox

### ISSUE THREAD

**Issue by HackBrettHB** [FormidableLabs/victory#2351]
**Describe the bug**
Below are several images to help you understand the situation!
We have a VictoryPie Chart that should be rendered next to a small legend. To achieve this, both elements are contained within a `<View>` (React) with flexDirection: "row". The VictoryPie has a VictoryContainer as containerComponent. The container has "flex:1" as style, just like the `<View>` of the Legend has. The expected behaviour is that the Container and the Legend's View both get an equal amount of space and layout their children within that space. This is what happens in the web version, but it does not happen in the mobile version. There the SVG outgrows the flexbox instead of being reduced in size to make it fit. Please refer to the screenshots below! The only "fix" that works it fixing the width/height of the VictoryPie to a fixed constant. But obviously, this is not responsive.

I am not excluding the possibility that I am misunderstanding flexboxes or any Victory concepts. However, it works on the web version and I have read every documentation/recommendation/StackOverflow answer that I could find about the topic for days now without any outcome.
Therefore, I am slowly suspecting that this is some kind of bug. In any case, I am grateful for any suggestions.

**Victory version**
We are using "victory-native" for the mobile and "victory" for the web build. Both versions are the same: 36.5.3.
We are using "react" 17.0.1 and "react-native" 0.64.3.
We use expo version 44.0.0.

**Code Sandbox link**
We have no sandbox, but the important code snippet is here:
```
<View
  style={[
    {
      flexDirection: "row",
    }
  ]}
>
  <VictoryPie
    data={pieData}
    labels={[]}
    containerComponent={
      <VictoryContainer
        style={{
          flex: 1,
          maxHeight: 400,
        }}
      />
    }
  />
  <View
    style={[
      {
        flex: 1,
        flexDirection: "column",
        justifyContent: "center",
      },
      styles.alignItemsCenter,
    ]}
  >
  ...
  </View>
</View>
```

**To Reproduce**
See screenshots / Code snippet

**Expected behavior**

**Screenshots**
How to SVG behaves:
![Screenshot_20220706-162726_Expo Go](https://user-images.githubusercontent.com/45429426/177575031-9593ba5f-1463-4c35-9567-c7f297a9dce3.jpg)

How the VictoryContainer behaves:
![Screenshot_20220706-162717_Expo Go](https://user-images.githubusercontent.com/45429426/177575037-b58a3315-fc99-4b5f-a9e6-2257b928624b.jpg)

What it should look like on the mobile: (Bottom chart! This is a performance-heavy, custom implementation we want to get rid of)
![Screenshot_20220706-162738_Expo Go](https://user-images.githubusercontent.com/45429426/177575036-e25e69da-57d3-412e-a399-bc3f21e79535.jpg)

What it looks like in the browser: (I can make the window _arbitrarily_ small, the layout stays the same)
![image](https://user-images.githubusercontent.com/45429426/177579895-030ef974-ea14-47ec-8457-f065cdaeaff8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome & Edge
 - Version 36

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - OS: Android 12
 - Browser Chrome
 - Version 36

**Comment by luisfuertes** [comment]
Same problem here

I have this code
```
const PieChart: FC<PieChartProps> = ({ label, percent = 70, style = {} }) => {
  const data = useMemo(
    () => [
      { x: '', y: percent },
      { x: '', y: 100 - percent },
    ],
    [percent]
  )

  const colorScale = useMemo(
    () => [percent < 61 ? chartColor60 : percent < 81 ? chartColor80 : chartColor100, chartColorEmpty],
    [percent]
  )

  return (
    <View style={{ backgroundColor: 'red', width: 88, height: 88 }}>
      <VictoryPie
        colorScale={colorScale}
        labels={[]}
        data={data}
        innerRadius={80}
        width={88}
        height={88}
        animate={{
          duration: 1000,
        }}
      />
    </View>
  )
}

export default PieChart
```

with this result:
![Captura de pantalla 2023-07-24 a las 12 09 34](https://github.com/FormidableLabs/victory/assets/18212615/733edb7c-0fb3-4026-9698-f10bc1c15c87)

I need 88x88 circle with 8px bar width.

**Comment by luisfuertes** [comment]
Continue open
