### ISSUE TITLE
TypeScript error with victory-core's index.d.ts

### ISSUE THREAD

**Issue by dlabrecq** [FormidableLabs/victory#2355]
**Describe the bug**
Encountered a TypeScript error while attempting to build with the latest victory-core package.

**Victory version**
victory-core: 36.5.3
typescript: 4.7.4

**To Reproduce**
1. yarn add victory-core
2. import from victory-core
3. build

**Expected behavior**
Removing the `type` keyword, from the index.d.ts snippet (below) appears to resolve the issue.

`export { Border as Box, type BorderProps as BoxProps, } from "./victory-primitives";`

**Screenshots**

![Screen Shot 2022-07-08 at 10 39 52 AM](https://user-images.githubusercontent.com/17481322/178014915-c8bb51f2-1682-4f9a-8916-1b78fbb68e46.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.4

**Comment by scottrippey** [comment]
Fixed in #2363
