### ISSUE TITLE
update `axisLabels` -> `axisLabel` in docs

### ISSUE THREAD

**Issue by ApolloTang** [FormidableLabs/victory#236]
![cannot-set-styling-for-axislabels](https://cloud.githubusercontent.com/assets/1150961/14235274/5ce4e8aa-f9c7-11e5-8bfb-45d0749e19ac.jpg)

https://github.com/ApolloTang/n-victory/blob/master/02-lab/app/02-axis-n-bar/index.js

**Comment by boygirl** [comment]
Hi Apollo, 

Sorry for the confusion. The namespace for applying styling to the axis label is `axisLabel` not `axisLabels` I figured that made since as there is only one axis label, but several tick labels... I'll double check to be sure that's clear in the docs.

**Comment by ApolloTang** [comment]
Thanks ! need to update document too at: http://victory.formidable.com/docs/victory-axis/ 
:) 

![screen shot 2016-04-04 at 12 13 29 am](https://cloud.githubusercontent.com/assets/1150961/14238056/2a4ac92c-f9fa-11e5-890c-b56f23509f55.png)
