### ISSUE TITLE
Victorie pie with animation gets stucked sometimes after refreshing page

### ISSUE THREAD

**Issue by billysk87** [FormidableLabs/victory#2367]
I have a VictoryPie, that gets different data when some buttons get clicked. When i first land on the page everything works perfect. But when i refresh the page, i can see that sometimes when i push the buttons the pie remains the same or is shown as if an other button was pushed. The labels are shown correctly though. When I disable the animation it works correctly.

I am writing a nextJS project with versions:
"react": "18.2.0",
"victory": "^36.5.3"

**Comment by clemwo** [comment]
I'm also on NextJS with react 18 and get similar issues. 
I think it has to do with `ReactDOM.createRoot`. Please refer to my other [comment](https://github.com/FormidableLabs/victory/issues/2104#issuecomment-1880609203).

Unfortunately I don't know how to fix these issues with NextJS as there is no way to access the index.js AFAIK
