### ISSUE TITLE
VictoryVoronoiContainer tooltip breaks when mouse moves between different chats

### ISSUE THREAD

**Issue by sergeykimaia** [FormidableLabs/victory#2369]
**Describe the bug**
if you quicky hover between two VictoryVoronoiContainer's, the tooltip wont appear in the latter

**Victory version**
36.5.3

**Code Sandbox link**
[Please include a code sandbox link or a similar reproduction if possible.](https://codesandbox.io/s/festive-einstein-pnv3jl?file=/src/App.js)

**To Reproduce**
1. hover over the first chart
2. hover over the second chart
3. see that tooltip sometimes doesn't appear

**Expected behavior**
tooltip to consistently appear when hovering over different charts

**Screenshots**

https://user-images.githubusercontent.com/58387319/179466489-c25d3256-4d9c-408e-b059-493366b86fc7.mov

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Browser chrome
 - Version Version 103.0.5060.114 (Official Build) (x86_64)

**Comment by doctordru** [comment]
👋 I've just found this bug as well, and would love for it to be fixed 🙏 

I'm currently POCing libraries to use for the analytics part of our product and this will stop me from using Victory 😢 

We have a lot of charts next to each other in our dashboards.
