### ISSUE TITLE
<VictoryBar />:  padding.left = 0 result in missing bar rendering for x_domain=0

### ISSUE THREAD

**Issue by ApolloTang** [FormidableLabs/victory#237]
![padding-left-0--no-render-at-x 0](https://cloud.githubusercontent.com/assets/1150961/14235290/08aa6764-f9c8-11e5-8573-7516ab928de5.jpg)

https://github.com/ApolloTang/n-victory/blob/master/02-lab/app/02-axis-n-bar/index.js

**Comment by boygirl** [comment]
@ApolloTang 

Thanks for bringing this to my attention. I'll take a look right now.
