### ISSUE TITLE
Add vector-effect attribute 

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory#238]
Ideally the grid stroke widths will stay fixed for responsive SVGs. There is support for retaining the stroke width using `vector-effect="non-scaling-stroke"`, see: https://www.w3.org/TR/SVGTiny12/painting.html#NonScalingStroke

The `vector-effect` SVG attribute isn’t supported [until React v15](https://github.com/facebook/react/pull/6267), whomp whomp. 

Here’s a [demo of a responsive chart with a non-scaling-stroke](http://codepen.io/paulathevalley/pen/Ragobo) (text scaling looks OK as it grows, but as it shrinks there's a point when it's unreadable).

**Comment by boygirl** [comment]
@stefvhuynh if you have time you can drop this in along with your React 15 update
