### ISSUE TITLE
Victory Zoom Container cuts victory tooltips which are set on Victory bar chart

### ISSUE THREAD

**Issue by amannarola** [FormidableLabs/victory#2381]
**Describe the bug**
Whenever I use VictoryZoomContainer,tooltip cuts outside of the bar chart

**Victory version**
36.5.3

**Code Sandbox link**
<VictoryChart
            containerComponent={
                <VictoryZoomContainer
                  allowZoom={zoom}
                  allowPan={zoom}
                />
            }
            domainPadding={{
              x: 8,
            }}
            domain={{
              x: [0.8, chart?.length],
            }}
            style={{
              background: { fill: 'transparent' },
            }}
            width={wp(88)}
            height={hp(32)}
            theme={VictoryTheme.material} >
            <VictoryAxis dependentAxis
              // crossAxis={false}
              style={{
                grid: {
                  strokeDasharray: 4,
                  stroke: '#CECFD6'
                },
                tickLabels: {
                  fontSize: 10,
                  fill: colors.ChallengeAnimationText,
                  fontFamily: Font.Manrope_500
                },
                ticks: {
                  stroke: 'transparent'
                },
                axis: {
                  stroke: 'transparent'
                }
              }}
              tickFormat={(t) =>
              (Number(t) >= 0 && hours ?
                `${t}h` : t)
              }
            />
            <VictoryAxis
              style={{
                grid: {
                  stroke: 'transparent'
                },
                axis: {
                  strokeWidth: 0.5,
                  strokeDasharray: 4,
                  stroke: '#CECFD6'
                },
                ticks: {
                  stroke: 'transparent'
                },
                tickLabels: {
                  fontSize: 10,
                  fill: colors.ChallengeAnimationText,
                  fontFamily: Font.Manrope_500,
                },
              }}
            />
                <VictoryBar
                  labelComponent={
                    <VictoryTooltip
                      renderInPortal={false}
                      pointerLength={hp(2)}
                      flyoutPadding={styles.flyOutPadding}
                      flyoutStyle={{
                        fill: 'black',
                      }}
                      style={{
                        fill: 'white',
                      }}
                    />
                  }
                  events={[
                    {
                      childName: "chart-bar-2",
                      target: 'data',
                      eventHandlers: {
                        onPressIn: ({ nativeEvent }) => {
                          return [
                            {
                              // Add an event to reset all the points to the original color
                              target: 'labels',
                              eventKey: 'all',
                              mutation: () =>
                                ({ active: false }),
                            },
                          ];
                        },
                        onPressOut: ({ nativeEvent }) => {
                          return [
                            {
                              target: 'labels',
                              mutation: () => ({ active: true }),
                            }
                          ];
                        },
                      },
                    }
                  ]}
                  cornerRadius={{
                    top: hp(0.5),
                    bottom: hp(0.5)
                  }}
                  domain={domain}
                  barWidth={15}
                  style={{
                    data: {
                      fill: colors.statsDataBackground,
                    },
                  }}
                  data={chart}
                />
          </VictoryChart >

**Screenshots**
![Simulator Screen Shot - iPhone 13 - 2022-07-25 at 12 25 07](https://user-images.githubusercontent.com/60807630/180718015-087d1a0e-a2fc-4ee7-9180-bf84142e3281.png)

If applicable, add screenshots to help explain your problem. (You can exclude this if you included a reproduction)

**Comment by AnuBhallaSCE** [comment]
I am also using zoom and voronoi container in bar chart. I  am also facing same issue on tapping bars

**Comment by fusandy** [comment]
same here! Although I'm not using the tooltip, but I have customized dataComponent which would like to show detail area above the VictoryChart if user click the Victorybar. Elements will be cut outside the VictoryZoomContainer.

Any update for this issue? thanks.
```
<VictoryChart
   standalone
   domainPadding={{ x: 10 }}
   containerComponent={
      <VictoryZoomContainer 
          allowZoom={false}
          zoomDimension='x'
          zoomDomain={{ x: [0, 8] }}
      />
  <VictoryAxis
    ...props
  />
  <VictoryAxis
   dependentAxis
   ...props
  />
  <VictoryBar
   ...props
  dataComponent={<DataComponent />}
  />
</VictoryChart>

**Comment by pranjal-jately-unmind** [comment]
+1 on this. Would be great to get this fixed as we're facing the same issue.
