### ISSUE TITLE
as data accumulates, axes not re-rendering properly

### ISSUE THREAD

**Issue by artitw** [FormidableLabs/victory#240]
as `props.data` accumulates more data, more ticks are added. It is not 5 ticks as specified in the code below.

```
          <Victory.VictoryChart>
            <Victory.VictoryAxis
              tickCount={5}
              padding={75}
              standalone={false}/>
            <Victory.VictoryAxis dependentAxis
              tickCount={5}
              padding={75}
              standalone={false}/>
            <Victory.VictoryLine
              data={props.data}/>
          </Victory.VictoryChart>
```

**Comment by boygirl** [comment]
@artitw Victory is using `d3-scale` to calculate ticks, and the `tickCount` prop is passed to `scale.ticks()` https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_ticks. Unfortunately this function as described returns _approximately_ the number of ticks you ask for; instead prioritizing even tick spacing. I will document this oddity in the prop description. Are you seeing a systematic increase in the number of ticks? If you need exact ticks you can accomplish this with by passing an array to `tickValues`.

**Comment by artitw** [comment]
@boygirl yes, it is a systematic increase. I have passed in an array to tickValues and it works now, though I have to keep calculating those values on the run. Thanks!
