### ISSUE TITLE
Y Axis/plotting issue?

### ISSUE THREAD

**Issue by justin-mcclain** [FormidableLabs/victory#2404]
**Describe the bug**
My data is not plotting correctly in React Native

**Victory version**
Which npm version are you using?
36.5.3

**Code Sandbox link**
`<VictoryChart maxDomain={{ y: 8 }}>
								<VictoryArea
									interpolation="natural"
									style={{
										data: {
											fill: "#f1642b2e",
											fillOpacity: 0.7,
											stroke: "#f1612b",
											strokeWidth: 3,
										},
									}}
									labels={({ datum }) => `${datum.temp}`}
									data={areaData}
									x="time"
									y="temp"
								/>
								<VictoryAxis
									style={{
										axis: { stroke: "transparent" },
										ticks: { stroke: "transparent" },
									}}
								/>
							</VictoryChart>`

![temp](https://user-images.githubusercontent.com/95764373/182679811-30822eb0-5fef-43d6-bc6a-95eefefbd5d8.png)

data looks like this:
Array [
  Object {
    "temp": "91",
    "time": "1 PM",
  },
  Object {
    "temp": "92",
    "time": "2 PM",
  },
  Object {
    "temp": "93",
    "time": "3 PM",
  },
  Object {
    "temp": "86",
    "time": "4 PM",
  },
  Object {
    "temp": "74",
    "time": "5 PM",
  },
  Object {
    "temp": "70",
    "time": "6 PM",
  },
  Object {
    "temp": "70",
    "time": "7 PM",
  },
  Object {
    "temp": "71",
    "time": "8 PM",
  },
]

**Comment by gksander** [comment]
Hi @justin-mcclain – It looks like your `temp` values are strings here. Will you try casting those to numbers, something like `areaData.map(el => ({ ...el, temp: +el.temp }))`? That seems to resolve the issue for me.

You might also want to remove the `maxDomain={{ y: 8 }}` bit since the max "y" value is quite a bit more than 8 in your example data.

**Comment by justin-mcclain** [comment]
hey @gksander , that definitely helped.  However, now my graph just....need some styling help?

I've used Chart.js in React a few times and there's an option there called "grace" which is the value is added to the maximum data value and subtracted from the minimum data.  Is there any way to do something like that with Victory?  Lastly, my first and last label are cut off on the sides.  I've tried messing with the padding and I can't seem to figure out that one either.  Is there a way to bring the area graph in some so the numbers aren't cut off?

![temp2](https://user-images.githubusercontent.com/95764373/182953558-3b8b8d99-f62f-4333-8624-8a8d2177cb65.png)

thanks for your help!

**Comment by gksander** [comment]
Have you tried the [domain padding](https://formidable.com/open-source/victory/docs/victory-area#domainpadding) prop on `VictoryChart` yet? I _think_ that might help with what you're trying to achieve!

**Comment by justin-mcclain** [comment]
@gksander that definitely could be a solution, however, I'm looking more to start my Y axis 3 below my lowest number in the array.  This is a graph of temperature over time.  If the lowest temperature over this time period is 75 and the high is 78,  I'd like the graph to start at 72, and go up to 81.  Is there any way to do that? 

One more additional thing, how can I style the X-axis labels, and the labels I have in the graph area itself?  

I appreciate your time and assistance!

**Comment by gksander** [comment]
@justin-mcclain Oh, gotcha. Here are a few things (illustrated in the code sample below):

- For adding/subtracting 3 from range: here might be multiple ways to achieve that, but one option is to just extract the min/max value from your dataset and use the `maxDomain` and `minDomain` props of `VictoryChart` accordingly.
- For styling x-axis label, use the `style['tickLabels']` field on `VictoryAxis`.
- For styling labels in the graph, use the `style['labels']` field on `VictoryArea`.

```tsx
import { VictoryChart, VictoryArea, VictoryAxis } from "victory";

const data = [
  { temp: "91", time: "1 PM" },
  { temp: "92", time: "2 PM" },
  { temp: "71", time: "8 PM" },
];

const cleanedData = data.map((el) => ({ ...el, temp: +el.temp }));
const maxTemp = Math.max(...cleanedData.map((el) => el.temp));
const minTemp = Math.min(...cleanedData.map((el) => el.temp));

export default function App() {
  return (
    <div>
      <VictoryChart
        maxDomain={{ y: maxTemp + 3 }}
        minDomain={{ y: minTemp - 3 }}
      >
        <VictoryArea
          data={cleanedData}
          x="time"
          y="temp"
          interpolation="natural"
          style={{
            data: {
              fill: "#f1642b2e",
              fillOpacity: 0.7,
              stroke: "#f1612b",
              strokeWidth: 3,
            },
            labels: {
              fontWeight: "bold",
            },
          }}
          labels={({ datum }) => `${datum.temp}°`}
        />
        <VictoryAxis
          style={{
            axis: { stroke: "transparent" },
            ticks: { stroke: "transparent" },
            tickLabels: { fontWeight: "bold" },
          }}
        />
        <VictoryAxis
          style={{
            axis: { stroke: "transparent" },
            ticks: { stroke: "transparent" },
          }}
          dependentAxis
        />
      </VictoryChart>
    </div>
  );
}
```

Hope this helps!

**Comment by justin-mcclain** [comment]
@gksander you are a wonderful man.  Thank you for all your help!

**Comment by gksander** [comment]
Happy to help! I'll close this issue accordingly.
