### ISSUE TITLE
How to present zero values in VictoryPie chart?

### ISSUE THREAD

**Issue by saniemehmet** [FormidableLabs/victory#2407]
### Discussed in https://github.com/FormidableLabs/victory/discussions/2405

<div type='discussions-op-text'>

<sup>Originally posted by **saniemehmet** August  3, 2022</sup>
I would like to present data which contains 0 values using pie chart. When all the values are null, pie does not appear. I am trying to show the pie, but it is visible only for values greater than zero. How can I make it visible even if the percentage is null for all the values?</div>

**Comment by acharyakavita** [comment]
Answered in https://github.com/FormidableLabs/victory/discussions/2405 .
