### ISSUE TITLE
`VictoryAxis` missing types on @36.6.0

### ISSUE THREAD

**Issue by Noitham** [FormidableLabs/victory#2411]
**Describe the bug**

The `<VictoryAxis>` component is missing it's types on the latest@36.6.0 release.

<img width="226" alt="Screenshot 2022-08-05 at 16 44 54" src="https://user-images.githubusercontent.com/32934478/183101402-64b15992-62e2-4ac7-aa14-f79b70645512.png">

**- EDIT -**
Checked a bit more, and types seem to also be missing on `VictoryScatter`.
Could this be related to something wrong with the latest TS migration?
(From release changelog, matches the two components I've noticed missing types):

<img width="702" alt="Screenshot 2022-08-05 at 16 49 00" src="https://user-images.githubusercontent.com/32934478/183102410-064602a1-1ec4-4f9d-981c-21d7b60a10f1.png">

**Victory version**
*36.6.0*

**Code Sandbox link**

**To Reproduce**
Install the latest 36.6.0 version and notice the missing types on the `<VictoryAxis>` component.

**Expected behavior**
`<VictoryAxis>` types should be defined.

**Comment by scottrippey** [comment]
I'm looking into this.
What I've found so far, is that the [`victory-axis.d.ts` file is correctly being published](https://unpkg.com/victory-axis@36.6.0/lib/victory-axis.d.ts), but the type is exported as `any`:
```
export declare const VictoryAxis: any;
```
And the same for `victory-scatter`, as you noted.


However, this does NOT happen for most other packages like `victory-line` or `victory-area`, which have nearly identical code, so this is an interesting issue!

**Comment by scottrippey** [comment]
Fixed in `36.6.1` 👍
