### ISSUE TITLE
clean up spurious postinstall errors

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#242]
Victory successfully installs, but throws 

```
victory@0.6.0 postinstall /Users/boygirl/formidable/victory-examples/node_modules/victory
> cd lib || builder run npm:postinstall || (echo 'POSTINSTALL FAILED: If using npm v2, please upgrade to npm v3. See bug https://github.com/FormidableLabs/builder/issues/35' && exit 1)
```

**Comment by ryan-roemer** [comment]
@boygirl -- Which part failed?

**Comment by boygirl** [comment]
Actually this was just a case of the echoed command being read as a failure by one of the users in the gitter channel. Nothing actually fails, so I think I will close this ticket unless you have any thoughts on improving clarity.
