### ISSUE TITLE
Changesets improvements

### ISSUE THREAD

**Issue by scottrippey** [FormidableLabs/victory#2429]
Improvements that can be made to changesets:
- [ ] Remove the excessive "Updated Dependencies" ([see Slack for more info](https://formidablelabs.slack.com/archives/CUBJUUSBF/p1660684599511609))
- [x] Apply a default message when running `pnpm run changeset` that includes the text `(fixes #xxxx)` so that publishing will automatically close tickets
- [x] Ensure PRs include a changeset file  (eg see https://danger.systems/js/)

**Comment by gwynethrose** [comment]
The second bullet point here, about applying a default message on changesets, does not appear to be supported by the `changesets` package. It also doesn't have a way to add this to the generated changeset files immediately.

**Comment by gwynethrose** [comment]
Installed https://github.com/apps/changeset-bot on the Victory repo, which will handle posting on PR's to remind contributors to add changesets.
