### ISSUE TITLE
clash setOpacity(T,float)  com.facebook.react.uimanager.BaseViewManager and com.facebook.react.viewmanagers.RNSVGCircleManagerInterface

### ISSUE THREAD

**Issue by lelsteph** [FormidableLabs/victory#2438]
Hello

I need help, please bare with me if I do not correctly describe the problem, help me to complete what is missing :-(

Thanks for your help!

I have I guess some setup issues which I cannot resolve. After installation, trying to display a simple chart I get a set of errors:

Task :react-native-svg:compileDebugJavaWithJavac FAILED

_...node_modules\react-native-svg\android\src\main\java\com\horcrux\svg\RenderableViewManager.java:1038: error: name clash: setOpacity(T,float) in com.facebook.react.uimanager.BaseViewManager and setOpacity(T,float) in com.facebook.react.viewmanagers.RNSVGCircleManagerInterface have the same erasure, yet neither overrides the other
  static class CircleViewManager extends RenderableViewManager<CircleView>_

The code I use:
`            <VictoryChart>
              <VictoryLine
                data={reArmerMeasures.map((measure: IReArmerMeasure) => {
                  return {
                    x: measure.rawTimeS / 60,
                    y: measure.batteryTemperature,
                  };
                })}
              />
            </VictoryChart>`

Package.json
{
  "name": "alarmapp",
  "version": "0.0.2",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@freakycoder/react-native-material-textfield": "^1.0.0",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "@reduxjs/toolkit": "^1.7.1",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "^2.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-network-logger": "^1.12.0",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-reanimated": "2.3.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.1",
    "react-native-sensitive-info": "^6.0.0-alpha.9",
    "react-native-sha256": "^1.4.7",
    "react-native-svg": "^13.0.0",
    "react-native-vector-icons": "^9.0.0",
    "react-redux": "^7.2.6",
    "victory-native": "^36.6.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/chart.js": "^2.9.37",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.66.4",
    "@types/react-native-popup-dialog": "^0.16.4",
    "@types/react-test-renderer": "^17.0.1",
    "@typescript-eslint/eslint-plugin": "^5.8.1",
    "@typescript-eslint/parser": "^5.8.1",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "eslint-plugin-react": "^7.28.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "reactotron-react-native": "^5.0.2",
    "typescript": "^4.4.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

**Comment by lelsteph** [comment]
No clue?

**Comment by hit-cod** [comment]
i got the same issue and it is prob related to "react-native-svg": "^13.0.0", the error even says 
Task :react-native-svg:compileDebugJavaWithJavac FAILED
[the link](https://github.com/react-native-svg/react-native-svg/issues/1723) to the same issue for that lib. have no clue how to solve it, but at least i share what i found

**Comment by lelsteph** [comment]
I upgraded my project (huge effort) to react native 0.70 and now everything is working.

**Comment by aleciogomes-sl** [comment]
We were having build issues on AppCenter, but when runned `assembleRelease` locally was working pretty fine.

We solved by setting AppCenter build Java version to 11.

**Comment by sajibsaha4647** [comment]
just downgrade your package react-native-svg ..... now i am using "react-native-svg": "12.3.0" and my problem solve.. 

"react": "17.0.2",
"react-native": "0.67.3",
"react-native-svg": "12.3.0"

I think the problem was in letest version hope this helpful .

**Comment by chinalwb** [comment]
ran into the same issue, for the issue in my project, it turned out to be the JDK version, for working with react-native-svg: 13.9.0, it requires higher version than JDK 8. I changed JDK 8 to JDK 11, it fixed the problem. Hope this helps.
