### ISSUE TITLE
VictoryAccessibleGroup is not available for victory-native

### ISSUE THREAD

**Issue by talon-himself** [FormidableLabs/victory#2444]
**Describe the bug**
Trying to import `VictoryAccessibleGroup` from `victory-native` and I get the `Module '"victory-native"' has no exported member 'VictoryAccessibleGroup'.`

**Victory version**
36.5.3

**To Reproduce**
1. Attempt to import `VictoryAccessibleGroup` from `victory-native`

**Expected behavior**
To have the ability to make RN graphs accessible.

**Comment by acharyakavita** [comment]
Hi everyone, we are transitioning all Native development to our new [Victory Native XL](https://github.com/FormidableLabs/victory-native-xl) library which is purpose built for supporting Native. Many of the design decisions we made in this version of Victory is not ideal for Native development.
