### ISSUE TITLE
Module not found: Error: Can't Resolve (...)

### ISSUE THREAD

**Issue by JVictor-0** [FormidableLabs/victory#2448]
When I first installed it I keep getting the error that some files are missing, or that "can't resolve" error. I've tried the auto fix that is supose to instal whats missing but it just got me into a loop.

Eg: ERROR

Module not found: Error: Can't resolve 'C:\Users\joaoc\OneDrive\Área de Trabalho\dogs\node_modules\source-map-loader\dist\cjs.js' in 'C:\Users\joaoc\OneDrive\Área de Trabalho\dogs'

I'm using the 8.5.5 version of npm.

**Comment by scottrippey** [comment]
Please provide more information /steps to reproduce.  Thanks!

**Comment by MatteuSan** [comment]
Hi! I'm also getting the same error in Next.js v13.0.1. Here's the error that pops up:

![image](https://user-images.githubusercontent.com/39852553/201745787-e040265d-bcec-4594-8e3f-f0eed3924fba.png)

And here are my imports for the page file:
```tsx
import React from 'react';
// ...
import { VictoryLine } from 'victory-line';
```

Steps to reproduce:
1. Create a fresh NextJS project (^13.0.0)
> **NOTE:** Be sure that the project will be running typescript.
2. Install Victory
3. Try to instantiate a chart in any page.

Environment:
- NodeJS v16.15.0
- Typescript v4.8.4

**Comment by ryan-roemer** [comment]
@MatteuSan can you place a full minimal project up on GitHub with install + build / error reproduction steps?

Offhand this just looks like `react` has not been added as a dependency... (There is some weird internal build stuff for React and many other libs especially in next 13 so I am curious if there is a real issue).

**Comment by MatteuSan** [comment]
@ryan-roemer sure sure, give me a sec...
