### ISSUE TITLE
Victory-native VictoryPortal is not rendered properly in native.

### ISSUE THREAD

**Issue by dlehddnjs** [FormidableLabs/victory#2450]
**Describe the bug**
An example on `VictoryPortal` - `children` is not working on iOS/Android.
Please check attached screenshot.

**Victory version**
npm :  7.20.3
victory-native : 36.6.5

**Code Sandbox link**
https://formidable.com/open-source/victory/docs/victory-portal#children
Same code in this section. (Not working on native)

**To Reproduce**
Check the example above.

**Expected behavior**
It works same as `Victory` (like the example source code)

**Screenshots**
iOS
![Screen Shot 2022-08-31 at 10 40 24 AM](https://user-images.githubusercontent.com/7699765/187575387-88837bce-c6d0-471b-b6c2-22bc3d278098.png)
Android
![Screen Shot 2022-08-31 at 10 44 07 AM](https://user-images.githubusercontent.com/7699765/187575396-923aa6a4-b88f-4b68-aead-5f1e89c4498f.png)

**Smartphone (please complete the following information):**
 - Device: iPhone13 Simulator
 - OS: iOs 15.5
- Device: Android Emulator
 - OS: Android 12.0

**Additional context**
Why `Victory` and `Victory-native` works different?

**Comment by letvigna** [comment]
This is an almost critical issue, how is it not possible to render tooltips above the rest of the chart for mobile applications?
