### ISSUE TITLE
enter / exit transitions for changing numbers of child components

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#246]
transition code is expecting a child component at a particular index and not finding it since some filtering is happening. For this situation in data nodes for individual components we've added support for a key attr on data that will be used instead of index, but we don't currently have a similar concept for entire child components, so they are just referenced by index. It looks like there's a little bit more work to be done with changing numbers of child components.

**Comment by beccanelson** [comment]
@boygirl Do you know anything about the status of this one? It looks like #684 might have addressed this issue.

**Comment by boygirl** [comment]
I think this issue is distinct from #684. This would refer to perhaps an entire new _series_ of bars tansitioning in rather than an changing number of bars in a given series. Does the distinction make sense?

**Comment by beccanelson** [comment]
Oh okay, I see! I will leave it for now then.

**Comment by becca-bailey** [comment]
I'm going to close some of these specific transition issues for now in favor of opening a larger issue for a general overhaul of transition logic.

**Comment by becca-bailey** [comment]
Larger issue thread: https://github.com/FormidableLabs/victory/issues/2104
