### ISSUE TITLE
TypeScript error with VictoryLineProps interface

### ISSUE THREAD

**Issue by dlabrecq** [FormidableLabs/victory#2463]
**Describe the bug**
Encountering a TypeScript error with the `animate` prop of `VictoryLineProps` .  The `VictoryLineProps` interface appears to have been changed to only accept a boolean only?

![Screen Shot 2022-09-12 at 1 27 04 PM](https://user-images.githubusercontent.com/17481322/189718168-8d6eb6bc-f255-4d32-bdaf-f6792600dc49.png)

**Victory version**
36.6.6

**Expected behavior**
Per the docs below, the prop should accept a boolean or an object.

https://formidable.com/open-source/victory/docs/victory-line#animate

**Screenshots**

![Screen Shot 2022-09-12 at 1 16 31 PM](https://user-images.githubusercontent.com/17481322/189716234-2d2a0a4f-674f-4ce0-8c6a-498ddda0861d.png)

 - OS: macOS Monterey
 - Version 12.4

**Comment by dlabrecq** [comment]
Fixed via https://github.com/FormidableLabs/victory/pull/2464

**Comment by scottrippey** [comment]
Fixed in `36.6.7`!
