### ISSUE TITLE
Horizontal bar chart sort is opposite

### ISSUE THREAD

**Issue by carlcodes** [FormidableLabs/victory#2473]
**Describe the bug**
When a bar chart is horizontal, the sorting is flipped. Non-horizontal charts the sorting works as expected

**Victory version**
36.6.7

**Code Sandbox link**
https://codesandbox.io/s/sorting-doesnt-work-horizontally-5fpukm?file=/index.js

**Expected behavior**
I would have expected bars to be sorted with the largest first when it is descending order

**Desktop (please complete the following information):**
- PC Chrome

**Additional Comments**
- This also happens when the array is already sorted in descending order, and the sort props are ommited - it reverse sorts the array.
- when tabIndex is used, it is also reversed

**Comment by scottrippey** [comment]
This behavior is intentional.  The origin of both a vertical and a horizontal graph is the 0,0 coordinate, so when items are sorted in descending order, the largest will be at 0,0.  
If you'd like to have the largest item at the top of the chart, simply use "ascending" order instead.

**Comment by carlcodes** [comment]
I admit the workaround is easy and covers most cases.

However, when tabidex is used on each bar for a11y, that's where it feels like a bug, since tabbing is not in sequential order @scottrippey

**Comment by scottrippey** [comment]
Any chance could you give me a codesandbox with tabbing?  
Does tabbing start from 0,0 and go "up" the list?  And the expected behavior is that it would go from top-to-bottom?

**Comment by carlcodes** [comment]
forked and updated with tab index here https://codesandbox.io/s/sorting-doesnt-work-horizontally-forked-uqg4lb?file=/index.js

what you said is correct. pages with good a11y generally have tab functionality that navigates down the page as it's presented on the ui. in my new example, clicking on the middle bar gives the bar an outline indicating that it's clickable / tabbable, but htiting tab goes up the page unexpectedly.
