### ISSUE TITLE
VictoryTooltip width on Windows

### ISSUE THREAD

**Issue by cagha** [FormidableLabs/victory#2475]
**Describe the bug**
Having a weird issue with tooltip padding.
This issue is happening on all browsers on Windows machines but not at all on Macs.
Top/Bottom padding works normal but Left/Right seems to be ignored on Windows.
While checking open bugs I noticed that the issue already appears in previously created sandboxes.. like this one for example: https://codesandbox.io/s/victory-brush-zoom-chart-forked-64tdfw

Windows:
<img width="699" alt="CleanShot 2022-09-23 at 15 51 49@2x" src="https://user-images.githubusercontent.com/114258949/192066820-5c24c3c1-7066-4841-989b-bb516e8cec82.png">

Mac:
<img width="654" alt="CleanShot 2022-09-23 at 15 52 04@2x" src="https://user-images.githubusercontent.com/114258949/192066858-a0016285-1c13-4581-a3a2-2b579f6f82c1.png">

**Victory version**
36.6.7

**Comment by scottrippey** [comment]
With #2505 merged, can you check if this problem has been solved with the latest version?
