### ISSUE TITLE
Missing react dependency for victory-native v36

### ISSUE THREAD

**Issue by ruairidhgallagher** [FormidableLabs/victory#2478]
# Questions
N/A

# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Using Intel Macbook, 
within a React app, 
using react v17.0.2,
using yarn v3.2.3 
running **yarn install for victory-native v36.6.7** 
within the console I see the warnings below.

➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p35168), requested by victory-core
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p0e13c), requested by victory-axis
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p31079), requested by victory-polar-axis
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pdb675), requested by victory-shared-events
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p9ca13), requested by victory-brush-container
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p56173), requested by victory-cursor-container
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pf3f25), requested by victory-selection-container
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pc61c5), requested by victory-voronoi-container
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pa4fd1), requested by victory-zoom-container
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p6d809), requested by victory-bar
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pd0f66), requested by victory-tooltip
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pc8eb9), requested by victory-area
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pbf46f), requested by victory-box-plot
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p1dee1), requested by victory-brush-line
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p7f754), requested by victory-candlestick
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p32b4e), requested by victory-chart
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p32f08), requested by victory-create-container
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pd51d5), requested by victory-errorbar
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p7df13), requested by victory-group
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p13c7c), requested by victory-histogram
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p3cec9), requested by victory-legend
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p2656e), requested by victory-line
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p2911c), requested by victory-pie
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p8fa8c), requested by victory-scatter
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pfa08a), requested by victory-stack
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (p866ce), requested by victory-voronoi
➤ YN0002: │ victory-native@npm:36.6.7 doesn't provide react (pd2fab), requested by victory

If you run **yarn explain peer-requirements p35168** you get the below output.

YN0000: victory-native@npm:36.6.7 doesn't provide react, breaking the following requirements:
➤ YN0000: victory-core@npm:36.6.7 [e9c70] → >=16.6.0 ✘

### Reproduction

Reproduce by using same version of Yarn with same version of victory in package.json

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Should the dependency for each of the packages above include React?
Yarn V3 cant seem to find react within the peer dependencies of victory-native.
Apologies if i'm missing something obvious but on first glance the error implies the dependency for the library is lacking?

**Comment by scottrippey** [comment]
React should be a `peerDependency` for this package, you're correct, and it's currently missing.
For now, the workaround is simply to install it as your own dependency, since that's the ultimate desired result.
I'll create a PR adding the `peerDependency`
