### ISSUE TITLE
export chart to image support on React Native

### ISSUE THREAD

**Issue by KartikLakhani009** [FormidableLabs/victory#2483]
### Discussed in https://github.com/FormidableLabs/victory/discussions/2482

<div type='discussions-op-text'>

<sup>Originally posted by **KartikLakhani009** September 28, 2022</sup>
Hi, I'm Kartik. I want to export chart from React Native side. Anyone have any idea ? or is there any way to do that ?
</div>

**Comment by daaanigm** [comment]
I think the best solution should be take a screenshot of this component with other library
