### ISSUE TITLE
Victory Line chart(Graph doesn't plot the new values fetched from API)

### ISSUE THREAD

**Issue by MeenuSai** [FormidableLabs/victory#2494]
I am new to Live data Plot in react native. 
I am using the Victory Line chart.
I am fetching data from API every 2 seconds. The graph has to add the new data points fetched from API to the graph and show it as live data streaming.  I have useEffect() to repeatedly call API.
In my case, It works fine for the first two fetches, but after that, there is no update in the plot, it remains the same. 
The input data gets appended with the new data points as expected but it doesn't reflect in the graph.
Please help me.
 
![Screenshot 2022-10-12 at 3 49 19 PM](https://user-images.githubusercontent.com/40272408/195317581-f5207f91-6a4f-4e19-a88a-66bb74edf0a1.png)

https://user-images.githubusercontent.com/40272408/195309346-fa887a7a-4a5c-43e3-8559-c4f2435b2520.mov

![Screenshot 2022-10-12 at 3 14 57 PM](https://user-images.githubusercontent.com/40272408/195309733-1765d732-9c1b-4920-8227-3e93a0b6dd6a.png)

**Comment by scottrippey** [comment]
Looking at your code, I see a common React problem.  In this code:
```
const d = [ ...chartData ]; // <--- problem
d.push(response.data);
setData(d);
```
Since this is inside a `useEffect`, you've got a "stale closure", which is a common problem.  Here's the simplest fix:
```
setData((chartData) => {
  const d = [ ...chartData ];
  d.push(response.data);
});
```
