### ISSUE TITLE
Polygon radar chart

### ISSUE THREAD

**Issue by margretheluth** [FormidableLabs/victory#2509]
### Discussed in https://github.com/FormidableLabs/victory/discussions/2508

<div type='discussions-op-text'>

<sup>Originally posted by **margretheluth** November  3, 2022</sup>
Hi,
i have a chart with polar axis and wondering how I can get the shape of a polygon and not a circle. Like this one.
<img width="184" alt="2018-07-29_09-42-46" src="https://user-images.githubusercontent.com/54893964/199682227-4a6c74e2-0e3e-4f9f-ab48-3b0e257b6c7c.png">
</div>

**Comment by wesleyguirra** [comment]
Hi, @margretheluth were you able to do it? I'm trying to do same thing but struggling to find it in docs.
