### ISSUE TITLE
label doesn't display on mouse over event

### ISSUE THREAD

**Issue by artitw** [FormidableLabs/victory#251]
Hi, has anyone gotten the events and labels to work together? I'm modifying the example found from http://victory.formidable.com/docs/victory-scatter

It looks like the `props.label` is getting updated based on `console.log(props.label)`. However, the chart display itself does not get updated.

```
  <VictoryScatter
    data={[
      {x: 1, y: 3, label: "hey"},
      {x: 2, y: 5},      
      {x: 3, y: 4},
      {x: 4, y: 2},
      {x: 5, y: 5}
    ]}
    size={8}
    symbol={"star"}
    style={{
      data: {
        fill: "gold",
        stroke: "orange",
        strokeWidth: 3
      }
    }}
    events={{
      data: {
        onMouseOver: (evt, props) => {
          console.log(props.label)
          return {label: "yo"};
        }
      }
    }}
  />
```

**Comment by boygirl** [comment]
@artitw I know why this is happening! Under the covers those events alter state objects on VictoryScatter for example. The data events alter `dataState` and the labels events alter `labelsState` and then these state objects are passed with other props to the rendered element. Label rendering is currently checking props and `labelsState`, but doesn't take `dataState` into account. I will change this behavior (this is step towards building tooltip anyway) and get back to you with a working example

**Comment by artitw** [comment]
The tooltip feature is exactly what I am looking for in this issue. Thanks so much for your response and for making Victory.

**Comment by boygirl** [comment]
- [X] label / data interaction in victory-chart
- [ ] label / data interaction in victory-pie
