### ISSUE TITLE
lodash: use "^4.6.1" rather than "~4.6.1"

### ISSUE THREAD

**Issue by danielberndt** [FormidableLabs/victory#253]
I found that some victory dependencies (victory-core, victory-chart, victory-pie) use a fairly strict lodash version definition. Looking through the lodash changelogs I couldn't find anything obviously dangerous. Am I maybe missing something?
Otherwise, using a more relaxed version definition like `^4.6.1` will likely lead to much fewer duplicate lodash versions in applications.

**Comment by boygirl** [comment]
@danielberndt this was put in place to avoid `lodash@4.7.0` which broke CI. The dep should be updated to `"lodash": "^4.11.0"`. I'll PR those repos in the next day or so unless you have the time / inclination.

**Comment by danielberndt** [comment]
Created the corresponding PRs :)

`victory-pie` already had a `^`-prefixed version so I left it as is.

**Comment by boygirl** [comment]
@danielberndt thanks for finding and fixing this issue!
