### ISSUE TITLE
VictoryPie Gradient - React Native

### ISSUE THREAD

**Issue by MobileMon** [FormidableLabs/victory#2544]
How to use gradients in VictoryPie React Native?

**Comment by ksetrin** [comment]
https://jsfiddle.net/boygirl/3mL9rjb5/

**Comment by adrian-burkhart** [comment]
You can use [react-native-linear-gradient](https://github.com/react-native-linear-gradient/react-native-linear-gradient) for Linear Gradients, or [react-native-radial-gradient](https://github.com/surajitsarkar19/react-native-radial-gradient) for Radial Gradients.

**Comment by acharyakavita** [comment]
Hi everyone, we are transitioning all Native development to our new [Victory Native XL](https://github.com/FormidableLabs/victory-native-xl) library which is purpose built for supporting Native. Many of the design decisions we made in this version of Victory is not ideal for Native development
