### ISSUE TITLE
VictoryAxis orientation left and right are different from domain value but max and min yAxis are same

### ISSUE THREAD

**Issue by truongnat** [FormidableLabs/victory#2572]
**Describe the bug**

My feature is create a chart combining two lines and one bar.

- Two lines chart depends on the axis orientation left.
- The bar chart depends on the axis orientation right.

When I pass data to the three charts above and set the domain for each axis:
 
Ex: 
 - Two lines:         <VictoryAxis dependentAxis={true} domain={{ y: [-10, 30] }} />
 -  Bar:                   <VictoryAxis dependentAxis={true} orientation='right' domain={{ y: [0, 20] }} />

Result:
max and min of both yAxis are -10 and 30.

**Victory version**
npm: 8.15.0
yarn: 1.22.19
victory-native: 36.6.8
react-native: 0.69.5

**To Reproduce**

```javascript
import { appColors } from '@themes';
import React from 'react';
import { View } from 'react-native';
import {
  VictoryChart,
  VictoryLine,
  VictoryBar,
  VictoryAxis,
} from 'victory-native';

const MyCombinedChart = () => {
  return (
    <View>
      <VictoryChart>
        <VictoryAxis dependentAxis={true} domain={{ y: [-10, 30] }} />
        <VictoryAxis
          dependentAxis={true}
          orientation='right'
          domain={{ y: [0, 20] }}
        />

        <VictoryLine
          data={[
            { x: 1, y: 30 },
            { x: 2, y: 7 },
            { x: 3, y: 6 },
            { x: 4, y: 9 },
            { x: 5, y: 7 },
          ]}
          style={{ data: { stroke: 'blue' } }}
          y='y'
        />

        <VictoryLine
          data={[
            { x: 1, y: -10 },
            { x: 2, y: 4 },
            { x: 3, y: 8 },
            { x: 4, y: 5 },
            { x: 5, y: 2 },
          ]}
          style={{ data: { stroke: 'green' } }}
          y='y'
        />

        <VictoryBar
          data={[
            { x: 1, y: 0 },
            { x: 2, y: 2 },
            { x: 3, y: 5 },
            { x: 4, y: 3 },
            { x: 5, y: 20 },
          ]}
          style={{
            data: {
              width: 10,
              strokeLinejoin: 'round',
              strokeWidth: 4,
            },
            labels: {
              fontSize: 10,
              fill: appColors.black,
              fontWeight: '500',
              fontFamily: 'Sarabun',
            },
          }}
          y='y'
          dependentAxis={true}
          domain={{ y: [0, 20] }}
        />
      </VictoryChart>
    </View>
  );
};

export default MyCombinedChart;


```

**Expected behavior**

- Each axis must have a different value as declared, not the same.
- Like the above description, the axis left max y is 30 and min -10 and the axis right max y is 20, min 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/87919564/222506172-b69af4f3-70f5-484a-8d3d-9bcdfaa920e9.png)

**Smartphone (please complete the following information):**
 - OS: iOS, Android

**Additional context**

I searched a lot and hope to get help from the contributor, thanks for all <3.

**Comment by truongnat** [comment]
@boygirl i have been following you for a long time, i need your help, plz

**Comment by t4t5u0** [comment]
This is workaround. You can solve it replace `<VictoryChart>` to `<Svg><G>`. 
But in this way, you cannot use Voronoi Container etc.
