### ISSUE TITLE
Is this package actively maintained?

### ISSUE THREAD

**Issue by laurentperroteau** [FormidableLabs/victory#2579]
I am a user of Victory and have noticed that the project has not been updated in some time. I would like to know if it is still being actively maintained or if development has been abandoned.

I appreciate the work that has been done on this project so far, and I understand that maintaining an open source project can be challenging.

Thank you

**Comment by Markkop** [comment]
If it is not, can someone recommend another data visualization library? I tried `react-vis`, but its react version is outdated.
https://github.com/uber/react-vis/issues/1435

**Comment by carloskelly13** [comment]
Yes it is, please see this comment for more:
https://github.com/FormidableLabs/victory/discussions/2576#discussioncomment-5369901

**Comment by Markkop** [comment]
Awesome, thanks for replying!
