### ISSUE TITLE
Consider using .js instead of .jsx extension

### ISSUE THREAD

**Issue by stefvhuynh** [FormidableLabs/victory#259]
It seems `.js` files are being transpiled by babel anyway for es6 support. Do we need to keep the `.jsx` extension? From what I've seen, it seems like the `.jsx` extension is starting to be used less and less. What do you guys think?

**Comment by dandelany** [comment]
FWIW Facebook uses `.js` for everything internally; [relevant discussion by React team here](https://github.com/facebook/react/issues/3582#issuecomment-89411479)

**Comment by boygirl** [comment]
We are moving forward with this change.
Repos to update
- [ ] victory
- [ ] victory-core
- [ ] victory-chart
- [ ] victory-pie
- [ ] victory-docs ?
- [ ] victory-examples

**Comment by boygirl** [comment]
All non-docs repos converted
