### ISSUE TITLE
VictoryAxis - tickLabelComponent

### ISSUE THREAD

**Issue by samynaj** [FormidableLabs/victory#2596]
### Discussed in https://github.com/FormidableLabs/victory/discussions/2595

<div type='discussions-op-text'>

<sup>Originally posted by **samynaj** May 16, 2023</sup>
Please anyone tried to give a custom component to tickLabelComponent in react native, it only takes the VictoryLabel any custom react native element doesn't display anything. Plus I want to be able to handle click events on the component. Urgent suggestions needed here pls.</div>

**Comment by helagoddr** [comment]
@samynaj found any solution?
