### ISSUE TITLE
Adding image/icons with text in VictoryAxis

### ISSUE THREAD

**Issue by Gayathri1996** [FormidableLabs/victory#2602]
I need to customise the tick labels used in Victory Axis as "Image with text"

Tried using 

```
class CustomTick extends React.Component {
  render() {
    const { x, y } = this.props;
    return (
      <View>
        <Image source="src/img/download.png" />
        <Text>{x}</Text>
      </View>
    );
  }
}

 <VictoryChart>
          <VictoryAxis
            tickValues={[1, 2, 3, 4]}
            tickLabelComponent={<CustomTick />}
       />

```
Not working. Please help me with the issue

**Comment by ardentcricket** [comment]
@Gayathri1996 Please try using `image` tag from `react-native-svg` instead of `Image` tag from `react-native`.
[Here's an example](https://github.com/FormidableLabs/victory/discussions/2636) of another instance where using `Image` from react-native can cause issues.
