### ISSUE TITLE
Updated text size calculation breaks VictoryLegend

### ISSUE THREAD

**Issue by dlabrecq** [FormidableLabs/victory#2613]
**Describe the bug**
The victory-core package changed how text sizes are calculated -- see https://github.com/FormidableLabs/victory/pull/2505. However, this appears to have inadvertently affected VictoryLegend. As a result, we can no longer use `gutterRow={0}` and the `lineHeight` label style for vertical legends. Unlike `gutter={0}`, there is always a minimum amount of space between legend rows, which appears based on font size. 

Note that the gap between rows increases with larger font sizes. For example, `gutterRow={0}`and and `lineHeight` no longer produces the same gap for font size 14 Vs 20.

**Victory version**
36.6.10

**Code Sandbox link**
Example with v36.6.8  (expected)
https://codesandbox.io/s/legend-row-gutter-example-1-19qsyb

Example with v36.6.10
https://codesandbox.io/s/legend-row-gutter-example-2-5yn1p4

Example with v36.6.10 and font size 20
https://codesandbox.io/s/legend-row-gutter-example-3-4inypx

**To Reproduce**
1. Go to https://formidable.com/open-source/victory/docs/victory-legend/#rowgutter
2. Update `gutterRow={0}`
3. See error

**Expected behavior**
With `gutterRow={0}` and `lineHeight: 0.275`, a minimal gap is expected between rows.

**Screenshots**

Example with v36.6.8 (expected)
![Screenshot 2023-06-07 at 8 21 00 PM](https://github.com/FormidableLabs/victory/assets/17481322/4f303198-77fd-4338-9d93-c2cca2ad8dfc)

Example with v36.6.8 and font size 20 (expected)
![Screenshot 2023-06-07 at 9 00 14 PM](https://github.com/FormidableLabs/victory/assets/17481322/b9b183b4-1383-4b2a-b363-d2a1be5621ab)

Example with v36.6.10
![Screenshot 2023-06-07 at 8 22 09 PM](https://github.com/FormidableLabs/victory/assets/17481322/c184b013-0ab3-41a1-aba4-662fb68f3776)

Example with v36.6.10 and font size 20
![Screenshot 2023-06-07 at 8 24 56 PM](https://github.com/FormidableLabs/victory/assets/17481322/8b42bd25-9244-4216-b099-1d9de43aaaed)

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]
 - Version [113.0.5672.126]

**Additional context**

**Comment by dlabrecq** [comment]
FYI @EthanRutherford

**Comment by EthanRutherford** [comment]
This issue has been addressed in the latest release, please let us know if you encounter further problems!
