### ISSUE TITLE
VictoryPie does not have access to common data props

### ISSUE THREAD

**Issue by harrisonlo** [FormidableLabs/victory#2620]
**Describe the bug**
Common data props like `sortKey`  and `sortOrder` are not accessible in VictoryPie, contrary to what the [documentation](https://formidable.com/open-source/victory/docs/victory-pie#sortkey) says.

**Victory version**
36.6.10

**Code Sandbox link**
https://codesandbox.io/s/victory-pie-common-props-issue-kgx95t

**To Reproduce**
1. Open sandbox
2. Uncomment the line `// sortKey="x"`
3. See error

**Expected behavior**
Common data props like `sortKey` and `sortOrder` can be used in VictoryPie

**Comment by acharyakavita** [comment]
The below code works.

`export default function App() {
  return (
    <div className="App">
      <VictoryPie
        data={[
          { employee: "Jane ", salary: 65000 },
          { employee: "Mary ", salary: 62000 },
          { employee: "James ", salary: 50000 },
          { employee: "Jessica ", salary: 70000 },
        ]}
        x="employee"
        y="salary"
        sortKey="x"
        sortOrder="descending"
      />
    </div>
  );
}
`
Appropriate data and keys needs to be defined initially for the sortkey and SortOrder to work.
Documentation for the same : https://formidable.com/open-source/victory/docs/victory-pie/#sortkey
                                                   https://formidable.com/open-source/victory/guides/data-accessors/

Please reopen the issue if the above code doesn't meet your requirement.

**Comment by acharyakavita** [comment]
Duplicate Issue .Related to #2139 .

**Comment by acharyakavita** [comment]
Use the below code 

```
const Chart = () => {
  return (
    <VictoryPie
      data={[
        { x: "1", y: 37 },
        { x: "2", y: 63 },
        { x: "3", y: 12 },
      ]}
      sortKey={"y"}
    />
  );
};
```
