### ISSUE TITLE
Victory Chart - How to add Axis extra tick

### ISSUE THREAD

**Issue by melly35** [FormidableLabs/victory#2622]
How are the ticks made in the area indicated by the red arrow in the picture?

Data = [0,10,20,30, ..n]

Short description: Adding extra ticks between 0-10 or 10-20 or 20-30

![javafx-linechart-1](https://github.com/FormidableLabs/victory/assets/44056608/d19be989-5500-4c2a-8721-9a07ca101378)

**Comment by BeyondThat** [comment]
https://codesandbox.io/s/broken-resonance-qtcw2y?file=/src/App.js

`<VictoryAxis
          crossAxis={false}
          style={{
            ticks: { stroke: "grey", size: ({ tick }) => (tick % 10 ? 5 : 10) }
          }}
          tickCount={50}
          tickFormat={(tick) => (tick % 10 ? null : tick)}
        />`

**Comment by melly35** [comment]
> https://codesandbox.io/s/broken-resonance-qtcw2y?file=/src/App.js
> 
> `<VictoryAxis crossAxis={false} style={{ ticks: { stroke: "grey", size: ({ tick }) => (tick % 10 ? 5 : 10) } }} tickCount={50} tickFormat={(tick) => (tick % 10 ? null : tick)} />`

Thank you, but how can this be done in a data like 2021/06/12 10:00:00?

**Comment by sem4phor** [comment]
Just update the functions in the proposed solution to match your logic.

For having full control over the ticks you can use [tickValues prop](https://formidable.com/open-source/victory/docs/victory-axis#tickvalues)

**Comment by sem4phor** [comment]
@helagoddr For our financial chart we passed the current price to a custom tick label component:


```
const YAxisTickLabel = props => {
  const { datum, currentPrice } = props

  const isCurrentPriceTick = datum === currentPrice

  if (!isCurrentPriceTick) return <VictoryLabel {...props} />

  return (
    <VictoryLabel
      animate={false}
      {...props}
      style={{ color: 'black', fontSize: 12 }}
      backgroundStyle={{
        fill: 'green'
      }}
    />
  )
}
```
