### ISSUE TITLE
No option to enable clickevent for each data in Victory Bar

### ISSUE THREAD

**Issue by premcoke** [FormidableLabs/victory#2630]
**Describe the bug**
In the below sample u can see a bar chart with 2 different colors (based on data). I need to have a click event for each data (i.e) while clicking on each color I need to perform different operation and need to have a different click handler which I can't achieve.

**Code Sandbox link**
https://codesandbox.io/s/victory-bar-chart-forked-zc5rqw?file=/index.js

**Comment by BeyondThat** [comment]
You can add  events to VictoryStack and access its children.

https://codesandbox.io/s/amazing-snow-dqr6yc?file=/src/App.js

**Comment by acharyakavita** [comment]
@BeyondThat Thank you. Closing this issue.
