### ISSUE TITLE
how to add background and border radius for ticklabels in victory native charts

### ISSUE THREAD

**Issue by helagoddr** [FormidableLabs/victory#2631]

**Comment by ardentcricket** [comment]
@helagoddr You can use the `tickLabelComponent` property and then assign`VictoryLabel` component to it. The `VictoryLabel` component allows you to use the [backgroundStyle property ](https://formidable.com/open-source/victory/docs/victory-label#backgroundstyle). Additionally, you can add custom styles using `backgroundComponent`.

Here is a small code blurb that solves for your question:
```js
      <VictoryChart
        domain={{x: [0, 5], y: [0, 7]}}
        containerComponent={<VictoryZoomContainer zoomDimension="x" />}>
        <VictoryAxis
          domain={[1, 7]}
          tickLabelComponent={
            <VictoryLabel
              dy={10}
              style={{
                fill: 'red',
              }}
              backgroundStyle={{fill: 'yellow', stroke: 'black'}}
              backgroundPadding={5}
            />
          }
        />
        <VictoryScatter
          style={{data: {fill: '#c43a31'}}}
          size={7}
          data={[
            {x: 1, y: 2},
            {x: 2, y: 3},
            {x: 3, y: 5},
            {x: 4, y: 4},
            {x: 5, y: 7},
          ]}
          labels={() => 'test label'}
        />
      </VictoryChart>
```
<img width="313" alt="Screenshot 2023-08-15 at 10 51 07 PM" src="https://github.com/FormidableLabs/victory/assets/18222457/ad1754ae-4771-44cc-afd7-c9f089c1989c">

**Comment by acharyakavita** [comment]
Thank you @ardentcricket . Closing this issue.
Note :  we are transitioning all Native development to our new [Victory Native XL](https://github.com/FormidableLabs/victory-native-xl) library which is purpose built for supporting Native. Many of the design decisions we made in this version of Victory is not ideal for Native development. Please refer to the new docs moving forward.
