### ISSUE TITLE
y value is 65 but showing near by 80

### ISSUE THREAD

**Issue by anuradhaprom** [FormidableLabs/victory#2637]
y value is 65 but showing near by 80
![Simulator Screen Shot - iPhone11 - 2023-08-16 at 18 14 21](https://github.com/FormidableLabs/victory/assets/129257843/e3c2317e-5258-427d-8433-bc7d1e528a8d)

**Comment by acharyakavita** [comment]
@anuradhaprom Can you please provide a code sandbox link with your code ?
