### ISSUE TITLE
Domain padding not applying in the start of the domain

### ISSUE THREAD

**Issue by syrusakbary** [FormidableLabs/victory#264]
The domainPadding prop when applied in `VictoryChart`, it's only applying in the end, but not the start of the domain.

## How to reproduce
Enter in http://formidable.com/open-source/victory/docs/victory-chart/ (last one: *Animating*), and add the following value in the `VictoryChart`: `domainPadding={{x:300}}`.

```js
class App extends React.Component {
   constructor(props) {
    super(props);
    this.state = {
      data: this.getData(),
    };
  }

  getData() {
    const n = _.random(4, 10)
    return _.map(_.range(n), (i) => {
      return {
        x: i,
        y: _.random(2, 10)
      };
    });
  }

  componentDidMount() {
    setInterval(() => {
      this.setState({
        data: this.getData()
      });
    }, 2000);
  }

  render() {
    return (
      <VictoryChart height={500}
        domainPadding={{x:300}}
        animate={{duration: 1000}}>
        <VictoryBar
          data={this.state.data}
          style={{
            data: {
              fill: "tomato", width: 12
            }
          }}
          animate={{
            onExit: {
              duration: 500,
              before: () => ({
                y: 0,
                fill: "orange",
                label: "BYE"
              })
            }
          }}
        />
      </VictoryChart>
    );
  }
}
ReactDOM.render(<App/>, mountNode);
```

**Comment by boygirl** [comment]
Thanks for the reproduction. I'm linking this to the issue open in victory-chart

**Comment by cbranch101** [comment]
I'm still having this issue, where can I find the solution to this?

**Comment by SethTompkins** [comment]
I am also having this issue, looks like the related issue on victory-chart no longer exists as issues are disabled on that repo now.

@boygirl any info on this?

**Comment by jarrx** [comment]
Any solution to this yet. I have the same problem.

**Comment by boygirl** [comment]
@jarrx 

This issue has been solved by adding the prop `singleQuadrantDomainPadding`. Please read about it here: https://formidable.com/open-source/victory/docs/common-props/#singlequadrantdomainpadding

**Comment by kevinfelisilda** [comment]
thanks, `singleQuadrantDomainPadding` solves the issue i'm facing.
