### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by zgagnon** [FormidableLabs/victory#2651]
**Describe the bug**
Fresh install using code from tutorial results in this error
**Victory version**

Which npm version are you using?

victory 36.6.11

**To Reproduce**
1. Go to ['...'](https://formidable.com/open-source/victory/docs)
2. Follow instructions
3. visit app

**Expected behavior**

super expression is either null or a function

**Screenshots**
stack trace below

**Desktop (please complete the following information):**
 - OS: macos
 - Browser arc (like chrome)
 - Version 1.7.0 

**Additional context**

Uncaught TypeError: Super expression must either be null or a function
    at _inherits (webpack-internal:///(:3000/rsc)/../../node_modules/.pnpm/victory-core@36.6.11_react@18.2.0/node_modules/victory-core/lib/victory-accessible-group/victory-accessible-group.js:37:15)
    at eval (webpack-internal:///(:3000/rsc)/../../node_modules/.pnpm/victory-core@36.6.11_react@18.2.0/node_modules/victory-core/lib/victory-accessible-group/victory-accessible-group.js:103:5)
    at eval (webpack-internal:///(:3000/rsc)/../../node_modules/.pnpm/victory-core@36.6.11_react@18.2.0/node_modules/victory-core/lib/victory-accessible-group/victory-accessible-group.js:132:2)
    at (rsc)/../../node_modules/.pnpm/victory-core@36.6.11_react@18.2.0/node_modules/victory-core/lib/victory-accessible-group/victory-accessible-group.js (/Users/zell/spike/my-turborepo/apps/web/.next/server/app/page.js:5337:1)
    at __webpack_require__ (/Users/zell/spike/my-turborepo/apps/web/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(:3000/rsc)/../../node_modules/.pnpm/victory-core@36.6.11_react@18.2.0/node_modules/victory-core/lib/index.js:38:31)
    at (rsc)/../../node_modules/.pnpm/victory-core@36.6.11_react@18.2.0/node_modules/victory-core/lib/index.js (/Users/zell/spike/my-turborepo/apps/web/.next/server/app/page.js:5304:1)
    at __webpack_require__ (/Users/zell/spike/my-turborepo/apps/web/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(:3000/rsc)/../../node_modules/.pnpm/victory-area@36.6.11_react@18.2.0/node_modules/victory-area/lib/helper-methods.js:8:20)
    at (rsc)/../../node_modules/.pnpm/victory-area@36.6.11_react@18.2.0/node_modules/victory-area/lib/helper-methods.js (/Users/zell/spike/my-turborepo/apps/web/.next/server/app/page.js:4930:1)

**Comment by t4t5u0** [comment]
In my case, I  solved this by adding  `'use clinet';` at the begging of the file.

**Comment by acharyakavita** [comment]
@zgagnon
can you please share a code sandbox for the same ? I am not able to recreate this scenario.

**Comment by prsauer** [comment]
> @zgagnon can you please share a code sandbox for the same ? I am not able to recreate this scenario.

https://codesandbox.io/p/devbox/next-14-0-3-forked-485w7h?workspaceId=5b262ed1-a1f3-41dc-b528-a559e2d7393f&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls23bm8d0007356g5qe0c1ny%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls23bm8d0002356ggl1bfmmm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls23bm8d0004356gp66cudi1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls23bm8d0006356gbz5986sn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls23bm8d0002356ggl1bfmmm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls23bm8d0001356gyzhpgji5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls23cblv004t356g4pod43i7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A30%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A30%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls23bm8d0002356ggl1bfmmm%2522%252C%2522activeTabId%2522%253A%2522cls23cblv004t356g4pod43i7%2522%257D%252C%2522cls23bm8d0006356gbz5986sn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls23bm8d0005356guwhly2d9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls23bm8d0006356gbz5986sn%2522%252C%2522activeTabId%2522%253A%2522cls23bm8d0005356guwhly2d9%2522%257D%252C%2522cls23bm8d0004356gp66cudi1%2522%253A%257B%2522id%2522%253A%2522cls23bm8d0004356gp66cudi1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls23bm8d0003356gpr69p50a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cls23bm8d0003356gpr69p50a%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by acharyakavita** [comment]
Clicking on the link gives `devbox not found` . Could you please share it again ?

**Comment by prsauer** [comment]
> Clicking on the link gives `devbox not found` . Could you please share it again ?
> 
> ![image](https://private-user-images.githubusercontent.com/42627321/301272618-8c542cbb-ff3b-4038-b9a5-22ee38bb5529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjcyMDksIm5iZiI6MTcwNjcyNjkwOSwicGF0aCI6Ii80MjYyNzMyMS8zMDEyNzI2MTgtOGM1NDJjYmItZmYzYi00MDM4LWI5YTUtMjJlZTM4YmI1NTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE4NDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNWZkNjFhMzZhYzQ0N2YwNjM0Mjc1Nzg1ODU4ZjIxYTI1NDdiYjgzYzY2YTNiNzVjNGI1NzhiYjY3Yjg2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3r8GaWYgak3IO-ArSxkXDAFnabN6XGcV52czroVLrsw)

Oops, fixed the perms.. link should work now

**Comment by zgagnon** [comment]
sorry, the company I was working at on this shut down, and I've lost context on what the bug is. I don't think I'll be able to give a reproduction at all

**Comment by acharyakavita** [comment]
> sorry, the company I was working at on this shut down, and I've lost context on what the bug is. I don't think I'll be able to give a reproduction at all

No worries. I am able to see the issue reproduced in your sandbox. I will look into it this week.

**Comment by acharyakavita** [comment]
@prsauer @zgagnon  victory is not a server side package, so it requires the use client directive `use client` when used on server side. 
The error will be resolved when we use ```"use client";``` on top of the file.
