### ISSUE TITLE
Gallery page error

### ISSUE THREAD

**Issue by toropov023** [FormidableLabs/victory#2684]
**Describe the bug**
The gallery page is not working.

**Victory version**
N/A

**Code Sandbox link**
N/A

**To Reproduce**
1. Go to https://formidable.com/open-source/victory/gallery/
2. See error

**Expected behavior**
No error.

**Screenshots**
<img width="505" alt="image" src="https://github.com/FormidableLabs/victory/assets/9454321/5294594e-9fb1-4ade-ad24-fede594e7e4a">
<img width="609" alt="image" src="https://github.com/FormidableLabs/victory/assets/9454321/f3f6e9a1-d07f-454e-b77f-a7899e81c162">
<img width="591" alt="image" src="https://github.com/FormidableLabs/victory/assets/9454321/eb6aa67d-7c9f-4c05-9a89-ffb0965a8cd5">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by toropov023** [comment]
I think the issue is here: https://github.com/FormidableLabs/victory/blob/ce87132faca49d44c1b9fc3074ec2b6473e153a0/docs/src/partials/gallery/preview.js#L14C3-L14C41

**Comment by smilemittal** [comment]
docs are also not working properly 
https://formidable.com/open-source/victory/docs/
sidebar missing and search is also not working

**Comment by hafizgohar** [comment]
yes docs are working fine too
https://formidable.com/open-source/victory/docs/

**Comment by KenanYusuf** [comment]
Fixed in https://github.com/FormidableLabs/victory/pull/2685

[Separate PR](https://github.com/FormidableLabs/victory/pull/2688) coming for the sidebar issues.
