### ISSUE TITLE
Victory documentation - sidebar items are not showing 

### ISSUE THREAD

**Issue by hafizgohar** [FormidableLabs/victory#2686]
Documentation not working fine - sidebar items are not showing 

**To Reproduce**
1. Go to 'https://github.com/FormidableLabs/victory/issues'
2. See error

**Expected behavior**
docs side bar should give options.

**Screenshots**
![image](https://github.com/FormidableLabs/victory/assets/139463122/c821bbba-5cc2-4574-b719-cdeaf9a0e709)

 - OS: Ubuntu
 - Browser: Chrome

**Comment by brsantos197** [comment]
@hafizgohar It also happens on Windows

**Comment by GKyomen** [comment]
+1

**Comment by amanShukla-amber** [comment]
+1
