### ISSUE TITLE
Victory GUI component builder produces working code

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#27]
as requested by @eastridge

**Comment by knowbody** [comment]
@boygirl can you provide more details for this, please

**Comment by boygirl** [comment]
Ak

**Comment by boygirl** [comment]
@knowbody this will be similar to a project @rgerstenberger is building for more general UI components. It will be a drag and drop type chart builder with sliders and drop downs for all the props, and some sort of data import. Once configured it should be able to export a zipped project, or a built/minified source. Not shovel ready atm.
