### ISSUE TITLE
gauge component

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#270]
build a gauge component with the following features

![screen shot 2016-05-23 at 2 09 24 pm](https://cloud.githubusercontent.com/assets/3719995/15484864/037ddf5a-20f1-11e6-982f-dc3495b5817e.png)

- Gauges will be circular, but can be formed from any portion of a circle. Define `startAngle` and `endAngle` as in victory-pie
- Gauges will be composed of segments, ticks, and tickLabels Re-use as much language from victory axis as possible in defining this api
- Gauges can be rings or full circles (ie inner radius) re-use api from victory-pie
- Support for a custom components (v2)
- Sensible default needle component
- needs to animate 
- follow the patterns established in the other victory components

props:
`animate`, `data`, `style`, `startAngle`, `endAngle`, `colorScale`, `innerRadius`, `outerRadius`, `padAngle`, `width`, `height`, `padding`, `tickValues`, `tickFormat`, `domain`

v2 props:
`dataAccessor`, `events`, `tickComponent`, `needleComponent`, `tickLabelComponent`, `segmentComponent`

This should end up looking quite similar to victory-pie. Here's a straight d3 example of a gauge component: http://bl.ocks.org/msqr/3202712

This feature should be created in a new repo [victory-gauge](https://github.com/FormidableLabs/victory-gauge). It would probably be easiest to start by cloning `victory-pie`

**Comment by mdaxtman** [comment]
should there be an upper bound to the angular spread of the chart? For example, should it span no more than 180 degrees, or should it allow for up to a 360 degree donut-type chart with a gauge?

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-gauge#1

**Comment by mdaxtman** [comment]
What format should `data` props be? A simple integer should work just fine, but are there any formats we should consider?

**Comment by boygirl** [comment]
@mdaxtman I'm moving this question to the corresponding issue in the newly created repo. Let's discuss there.
