### ISSUE TITLE
npm conflicts due to `builder-victory-component` dependency

### ISSUE THREAD

**Issue by EvNaverniouk** [FormidableLabs/victory#272]
The `victory` npm package has `builder-victory-component` set as a `dependencies` (not as a `devDepenencies`).

The `builder-victory-component` package has `style-loader` set as a `dependencies` (not as a `devDepenencies`).

My question is why aren't these `devDependencies` in both cases? It's causing undesirable npm install conflicts in our application because we want to use a different version of `style-loader`. It's also causing the victory packages to be larger than they have to be since it's installing loaders and babel, etc... as a direct dependency.

Any reason these have to be in `dependencies` and not in `devDepenencies`?

**Comment by ryan-roemer** [comment]
@EvNaverniouk -- We provide a `postinstall` hook to build / transpile if it doesn't already exist, which allows `git` dependencies which don't have the built files. So these are "prod" dependencies. There is a potential future ticket to on npm publishing _only_ swap the archetype and `builder` itself to `devDependencies`. (This latter ticket would take care of the "larger install" issue)

But that should be orthogonal to any issues you're having. Can you actually get us a public reproduction of the issue and perhaps we can dig in more?  And specifically, all these dependencies should be localized to victory alone and _not_ to your application. `npm` won't flatten dependencies past a compatible point in the `node_modules` tree.

However, if you are building victory raw sources (as opposed to going off the `dist/` or `lib/`) then you will need to be compatible with our underlying build.

Thanks!

**Comment by EvNaverniouk** [comment]
Ok. I understand. No action required.
