### ISSUE TITLE
Component/Feature Request: Brush/View Finder/Zoom & Range Tool

### ISSUE THREAD

**Issue by joshburgess** [FormidableLabs/victory#273]
I think this is another important one. The ability to change the range and zoom in/out & pan around would be really useful, especially with the new Shared Events feature, as you could use a single brush to control multiple charts on the page simultaneously.

See below links for different examples:

[NVD3 Line Chart with View Finder](http://nvd3.org/examples/lineWithFocus.html)
[D3 Demo Focus+Context via Brushing](https://bl.ocks.org/mbostock/1667367)
[Recharts Brush BarChart](http://recharts.org/examples#BrushBarChart)
[D3 Demo with a Different Method of Zooming](http://wrobstory.github.io/2013/11/D3-brush-and-tooltip.html)

**Comment by joshburgess** [comment]
@boygirl I might try to work on adding this component soon if you're cool with it. Have been working more with React + raw D3 recently. I'll try to see what I can come up with if I get some time.

**Comment by boygirl** [comment]
@joshburgess that would be awesome. Let's me know what can be done in terms of parent events to support that effort.

**Comment by brezal** [comment]
Any updates here? I came across this issue when searching for ways to make interactions with the chart more accessible to mobile users.

**Comment by joshburgess** [comment]
Nothing from me... I've been too busy to even start. :[ 

I definitely need something like this though... and a legend also. :/

**Comment by wuct** [comment]
How is this issue going? I really like Victory and would like to help this feature come true.
 
I have implemented the brush component in my [chart lib](https://github.com/wuct/a4). You can play with it in [the demo page](https://wuct.github.io/a4/). If it looks good to you, I can reimplement  the brush component in Victory.

**Comment by boygirl** [comment]
@wuct This issue isn't under active development, so I'm happy for you to take a stab at it. I need to write a better contributors guide! that's on my TODOs for tomorrow. I'll be sure to mention you in the PR when I finish that so you resource to get started.

**Comment by wuct** [comment]
Great! I am looking forward to it.

**Comment by boygirl** [comment]
@wuct Sorry I forgot to mention you in the PR. Here's the updated [Victory Component Style Guide](https://github.com/FormidableLabs/builder-victory-component/blob/master/dev/CONTRIBUTING.md#victory-component-style-guide). Please contact me in the [gitter channel](https://gitter.im/FormidableLabs/victory) if you have specific questions. Thanks so much for helping out!

**Comment by wuct** [comment]
@boygirl Thanks!

**Comment by boygirl** [comment]
Released in `victory@0.13.7`
