### ISSUE TITLE
How to center Pie chart?

### ISSUE THREAD

**Issue by matthjes** [FormidableLabs/victory#274]
Victory looks good so far, however, I'm unable to center the g element within the svg element. The Pie chart is always left aligned.

The svg element uses the entire width of the enclosing div, but the default transform for the g element does not center it inside the svg element. 

JSBin example: http://jsbin.com/najujeyaqa/1/edit?html,css,js,output

**Comment by rssfrncs** [comment]
Could you try losing the height/width props on the VictoryPie component and replace the height/width css properties on **#container** with **max-width**. This should hopefully allow the VictoryPie component to be responsive whilst never growing more than 300px in width (and height).

![fixed?](http://i.gyazo.com/b95d586dbdd9e3c55c8e48e7491fb9de.png)
![fixedsomemore?](http://i.gyazo.com/bfcc44cbaea422626ba531a54715c94b.png)
