### ISSUE TITLE
Use of `reduce-css-calc` requires unsafe-eval CSP

### ISSUE THREAD

**Issue by jaredly** [FormidableLabs/victory#276]
I'd like to use victory in a chrome extension, where the default Content Security Policy disallows the use of `eval` (which is at the core of reduce-css-calc's functionality). Now, I can relax this manually, but eval is a notorious XSS concern, and it's much safer to disallow it.
Unfortunately, `calc()` literals are not allowed as svg properties (e.g. dx, dy); they are only allowed in CSS. And so without eval, lots of html syntax errors are raised, and e.g. the tick labels don't get placed correctly

Is there a way that you could remove the need for reduce-css-calc?

**Comment by tomduncalf** [comment]
+1, we've had to relax our CSP due to this :( Wonder if it could at least be made optional (and I guess accept a performance hit? or is the use more fundamental than that?)
