### ISSUE TITLE
VictoryPie svg height does not reflect start/end angle props

### ISSUE THREAD

**Issue by rssfrncs** [FormidableLabs/victory#278]
System is OSX El Capitan. Browsers tested Chrome and Safari

I have specified a start and end angle to create a half pie using the below props:

```
<VictoryPie endAngle={90} startAngle={-90} />
```

However the viewBox attribute on the component svg node remains '0 0 400 400'. This results in excess height, so is it possible for the svg viewBox attribute to reflect the height caused by setting a start and end angle?

![Issue screenshot](https://i.gyazo.com/aacdad5cfe5e03e55f01f6671f988f44.png)

By changing the viewBox attribute to 0 0 400 200 (through dev tools) we get the desired result.

![Desired screenshot](https://i.gyazo.com/c6a4cb0921fcab064d0c856793234759.png)

**Comment by boygirl** [comment]
@rssfrncs those width and height values come from default props in VictoryPie, but I think you're right that setting them to 400 x 200 would result in a smaller pie chart even though only a half circle is rendered. Since the start and end angles can be arbitrary it might be difficult to have the final svg size contain only and exactly a half pie, but I'll see what can be done. Another solution you might look into is setting `standalone={false}` and rendering the resulting `<g>` in an `<svg>` that you have full control over.

**Comment by rssfrncs** [comment]
@boygirl I wasn't aware of the standalone prop, sounds like it will work for me :)

**Comment by davidramos-om** [comment]
This one was my workaround solution, it solves the issue for now, update the DOM once elements are rendered

```typescript
  updateSVGAttributes = (svg: Element, width: number, height: number) => {
    svg.setAttribute('height', height.toString());
    svg.setAttribute('viewBox', `0 0 ${width} ${height}`);
  };

  updateRechartsWrapperStyle = (wrapper: Element, height: number) => {
    wrapper.setAttribute('style', `height: ${height}px;`);
  };

updateElements = () => {
    const width = Number(this.props.options?.width);
    const gaugeHeight = Number(this.props.options?.height) / 2;
    const svgs = document.querySelectorAll('.recharts-surface');
    svgs.forEach((svg) => {
      const parent = svg.parentElement;
      if (parent) {
        const grandparent = parent.parentElement;
        if (grandparent && grandparent.id.includes('gc-pie')) {
          this.updateSVGAttributes(svg, width, gaugeHeight);
        }
      }
    });

    const wrappers = document.querySelectorAll('.recharts-wrapper');
    wrappers.forEach((wrapper) => {
      if (
        wrapper.parentElement &&
        wrapper.parentElement.id.includes('gc-pie')
      ) {
        this.updateRechartsWrapperStyle(wrapper, gaugeHeight);
      }
    });
  };

  componentDidMount() {
    this.updateElements();
  }
``` 

and in my card component:
```typescript
    <Box style={props.boxProps?.style}>
      <Center>
        <StyledTitle>{props.title}</StyledTitle>
      </Center>
      {props.stack.map((element) => (
        <StyledCentered key={element.key} id={`gc-pie-${element.key}`}>
          <StackIem legend={element.legend} chartProps={element.chartProps} />
        </StyledCentered>
      ))}
      <Center>
        <Typography fontSize="sm">{props.legend}</Typography>
      </Center>
    </Box>
``` 

**Result**
<img width="177" alt="image" src="https://github.com/user-attachments/assets/4c20be30-3573-412f-afd6-3be2d0969b01">
