### ISSUE TITLE
support canvas via SVG -> canvas parser

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#28]
Maybe modify this:
https://github.com/kangax/fabric.js/blob/master/src/parser.js

svg performance is a problem with a large number of nodes. Giving a canvas option would help.  Canvas option might also facilitate server-side rendering.

**Comment by Thorbenandresen** [comment]
this might really help me. I have a scatterplot with almost 5000 nodes which take a lot of time to render.
