### ISSUE TITLE
[ Question ] Could this be used in a react-native WebView today?

### ISSUE THREAD

**Issue by esutton** [FormidableLabs/victory#280]
I understand it is Alpha, however,  I am desperately seeking a cross-platform Android / iOS line chart for react native.

1) Does anyone know if a React Native WebView could host this ?

2) Is a react-native version expected anytime soon? 

( I am willing to take Alpha risks and help provide feedback )

**Comment by esutton** [comment]
I guess react native is not usable at this time. 

I get **error: Unsupported architecture** when I install.

http://formidable.com/open-source/victory/docs

```
{
  "name": "HelloVictoryPie",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.0.2",
    "react-native": "0.26.2",
    "victory": "^0.8.0"
  }
}
```

Then:
`npm install victory
`



```
npm install victory

> bufferutil@1.2.1 install /Users/edward3/Documents/projects/react-native/HelloVictoryPie/node_modules/bufferutil
> node-gyp rebuild

2016-06-14 10:54:21.837 xcodebuild[16196:500734] Build settings from command line:
2016-06-14 10:54:21.838 xcodebuild[16196:500734]     ENABLE_BITCODE = NO
2016-06-14 10:54:21.838 xcodebuild[16196:500734]     SWIFT_DISABLE_REQUIRED_ARCLITE = YES
2016-06-14 10:54:21.838 xcodebuild[16196:500734]     SWIFT_LINK_OBJC_RUNTIME = YES
2016-06-14 10:54:21.838 xcodebuild[16196:500734]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-06-14 10:54:21.838 xcodebuild[16196:500734]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:7:
In file included from /Users/edward3/.node-gyp/5.9.1/include/node/v8.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include/stdint.h:63:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/include/sys/_types.h:32:
/Applications/Xcode.app/Contents/Developer

```

**Comment by boygirl** [comment]
@esutton look for Victory-Native at the end of the week!

**Comment by rgoldiez** [comment]
Any update on Victory-Native?

**Comment by txizzle** [comment]
Any updates?

**Comment by boygirl** [comment]
@rgoldiez @txizzle check out `victory-native-chart` and `victory-native-pie`. I haven't tried it out in a webview, but these should be working in react native apps on ios at least. There are still a few bugs to work out (_i.e._ events are not yet working on native), but you should be able to get started :)

**Comment by rgoldiez** [comment]
@boygirl - I'd love to try to incorporate this into one of my projects (I'm using RN 0.29.2).  I went to the `victory-chart-native` project to look at which dependencies to add (`react-native-svg`, `victory-core-native`, and `victory-chart` looked to be the ones) and I ran into conflicts when starting the react native packager.
