### ISSUE TITLE
VictoryAxis label not working as intended

### ISSUE THREAD

**Issue by flexzuu** [FormidableLabs/victory#281]
Hey I just played arround with victory to decide if i what to use it in an side project and i might have found a bug. I could aswell be me useing it wrong.

Please get back to me if you need more information.

**The component i try to render:**
```javascript
function Graph() {
  const data = [
    { x: 0, y: 10 },
    { x: 1, y: 30 },
    { x: 2, y: 20 },
    { x: 3, y: 40 },
    { x: 4, y: 30 },
    { x: 5, y: 50 },
  ];
  const interpolation = 'natural';
  return (
    <VictoryChart>
      <VictoryAxis dependentAxis label="y-axis" />
      <VictoryAxis label="x-axis" />
      <VictoryLine
        interpolation={interpolation}
        data={data}
        label={interpolation}
      />
      <VictoryLine
        data={data}
        style={{
          data: {
            stroke: '#822722',
          },
        }}
      />
    </VictoryChart>
  );
}
```

## The Problem:
- The axis labes are not displayed correctly.
- x-axis is displayed on the top instead of bottom
- y-axis is not on displayed

On the left is as i should be and is on your website.
On the right is with my build system (I removed all my css files).
![victory-axis-bug](https://cloud.githubusercontent.com/assets/3532919/16126466/9541149c-33f8-11e6-87bc-844880499909.png)

**Comment by boygirl** [comment]
@flexzuu yep this is a bug in a version of `victory-chart` that is not yet included in the main `victory` package. (Which is why you don't see it on our site). I will fix it for our scheduled release tomorrow. Thanks for pointing it out!

**Comment by flexzuu** [comment]
Hey thanks for the quick reply. Will check back tomorrow if everything is working.

**Comment by flexzuu** [comment]
It seems like it is not fixed completely.
The x-axis is working now. the y axis is missing the label still.

![victory-still-bugged](https://cloud.githubusercontent.com/assets/3532919/16168492/9174e17a-3508-11e6-903f-bb915410e921.png)

You can check out a repo with the bug [here](https://github.com/flexzuu/react-redux-axios-boilerplate/tree/victory).
