### ISSUE TITLE
tickFormat

### ISSUE THREAD

**Issue by camerow** [FormidableLabs/victory#282]
I'm using Victory for a project, and I am having difficulty using the `tickFormat` prop in a `<VictoryAxis/>` component. 

Here is my chart currently:

```
const xAxisTicks = [ "2016-06-16 00:00", "2016-06-16 01:00", "2016-06-16 02:00" ]

<VictoryChart scale={{ x: "time" }} >
              <VictoryAxis 
                  label={this.state.interval} 
                  tickValues={xAxisTicks}
                  tickFormat={(a, i) => {
                  /* The problem is here, where a is coming in as an integer, 
                      but I'm feeding the component an array of dates, 
                      and I'd like to intelligently return either a date or time 
                      based on some other context. */
                   console.log(a, i) // will print 1 0, 2 1, 3 2 etc...
                   return a.split(" ")[1];
                }}/>
              <VictoryAxis dependentAxis
                label="Count" />
              <VictoryLine
                data={data} />
            </VictoryChart>
```

As in the comment, `tickFormat`'s argument seems to be an integer relating to the length of the item being passed to `tickValues`, and the second argument seems to be the index of each element. As per your docs it looks like `tickFormat` should be getting each item in the `tickValues` array. 

Any help with this is appreciated. 

And on a more positive note, I'm really loving working with this library. It's beautifully done. 

Thanks!

**Comment by boygirl** [comment]
@camerow can you try formatting your `tickValues` like `new Date("2016-06-16 00:00")`. I'll look into why you're seeing integers coming through. I would expect strings given the code above. One of my colleagues is running into a similar issue. I'll see if I can nail it down for our release tomorrow.

**Comment by ca057** [comment]
Hey, sorry for digging out a super old issue, weirdly I’m running into the same bug right now.

I have setup a range of `tickValues` from ISO-date strings:

```ts
const tickValues = [
  "2021-02-09T06:00:00.000+01:00",
  "2021-02-09T07:00:00.000+01:00",
  "2021-02-09T08:00:00.000+01:00"
];
```

which I feed to my `VictoryAxis`:

```tsx
return <VictoryAxis standalone tickValues={tickValues} tickLabelComponent={<DateLabel />} />
```

My problem is now that in my `DateLabel`-component I receive the strings as `number`s:

```tsx
const DateLabel = ({ ticks }) => {
  console.log(ticks) // logs [1, 2, 3]

  return <Text />
}
```

When I map my `tickValues` to `Date`s first (following https://formidable.com/open-source/victory/docs/victory-axis#tickvalues to be able to supply Dates), I receive them in a stringified fashion:

```ts
// 
const tickValues =  [
  "2021-02-09T06:00:00.000+01:00",
  "2021-02-09T07:00:00.000+01:00",
  "2021-02-09T08:00:00.000+01:00"
].map(tick => new Date(tick));

// in DateLabel
console.log(ticks) // logs ["Tue Feb 09 2021 06:00:00 GMT+0100 (Central European Standard Time)", /* ... */]
```

I can fix this issue by passing the `tickValues` explicitly as `ticks`-prop to the `DateLabel`:

```tsx
return <VictoryAxis standalone tickValues={tickValues} tickLabelComponent={<DateLabel ticks={tickValues} />} />
```

Now I receive the correct types in my `DateLabel`-component.

---

I’m using `victory-native` - shall I open a separate issue in the respective repository?

* `react-native@0.63.4`
* `victory-native@35.3.1` with `victory@35.4.7` as dependency

**Comment by boygirl** [comment]
@ca057 I would recommend passing your `tickLabels` as explicit date objects, and making sure your chart / axis is using `scale={{ x: "time" }}`. if you're using VictoryAxis with a chart that has other data, you might make sure your data is also coming in as date objects. Victory handles string data by calculating a string mapping of unique strings to integer values. This works out great if your data is something truly qualitative like "Team A", "Team B", "Team C", but gets really confusing if your data is date strings, and is meant to be time scale.
