### ISSUE TITLE
Aria roles on individual path elements

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#284]
Maybe just the `role` + index for each rendered path / label etc.

**Comment by stephenotalora** [comment]
This is particularly important for 2 reasons:
1. react-a11y
2. running react in `dev` mode renders `Victory` components unusable courtesy of `react-a11y` as react warnings spam the console log to the point of causing the browser to crash. disabling `react-a11y` is not an option as we use it for accessibility validation against react elements.

**Comment by stephenotalora** [comment]
pr available here: https://github.com/FormidableLabs/victory-chart/pull/271
