### ISSUE TITLE
Unable to use all null data in timeseries with VictoryStack

### ISSUE THREAD

**Issue by PeterYurkovich** [FormidableLabs/victory#2844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Victory version

37

### Code Sandbox link

https://codesandbox.io/p/sandbox/victory-starter-forked-3gxgkt?file=%2Fsrc%2FApp.tsx

### Bug report

VictoryStack supports null values in the VictoryArea data, except in the instance where all values are null, x values are dates, and there are multiple VictoryAreas. In this case VictoryStack crashes.

This is due to filtering out all null values before determining if the array of data uses dates as the x data. 

```ts
function stackData(props, childComponents) {
  const dataFromChildren = Wrapper.getDataFromChildren(props, childComponents);
  const filterNullChildData = dataFromChildren.map((dataset) =>
    dataset.filter((datum) => datum._x !== null && datum._y !== null),
  );
  const datasets = fillData(props, filterNullChildData);
  return datasets.map((d, i) => addLayoutData(props, datasets, i));
}
```

The dataset being passed into fillData is empty, and so when inside fill data it is checked if the x value is a date, it returns a falsey value (undefined). 

```ts
const isDate = dataset[0] && dataset[0]._x instanceof Date;
```

This causes the return from fillData to place unix timestamps instead of JS date objects in the x value. Once this new dataset is passed into addLayoutData it sees the other VictoryArea uses JS Dates, and so tries to call a date function (getTime) on a unix timestamp.

This can be solved by waiting to filter the null values out until the isDate is determined so that a Date object will be returned rather than a unix timestamp.

### Steps to reproduce

Steps to reproduce behavior:
1. Added Code Sandbox link [Code Sandbox](https://codesandbox.io/p/sandbox/victory-starter-forked-3gxgkt?file=%2Fsrc%2FApp.tsx)

### Expected behavior

```markdown
VictoryStack should render even if one VictoryArea is only null values.
```

### Actual behavior

```markdown
JS error occurs and the chart does not render.
```

### Environment

```markdown
- Device: Desktop
- OS: MacOS 14.4.1
- Browser: Firefox, Chrome, Arc
```

**Comment by robwalkerco** [comment]
Reopening.
This issue will be resolved once the [related PR](https://github.com/FormidableLabs/victory/pull/2888) is merged
