### ISSUE TITLE
Label on dependentAxis (y-axis) doesn't render correctly

### ISSUE THREAD

**Issue by GertjanReynaert** [FormidableLabs/victory#285]
Since I updated my charts from v0.7.0 to v 0.9.0 I noticed that the labels on the y-axises were gone. Not sure how I can help, but I made screenshots from the official docs where the same behaviour occurs.

It seems like the label is correctly put in the DOM, but is positioned outside of the chart view.

![screen shot 2016-06-22 at 10 50 42](https://cloud.githubusercontent.com/assets/4712292/16260491/f5ad1b3c-3867-11e6-8010-c05bb4688253.png)
![screen shot 2016-06-22 at 10 52 46](https://cloud.githubusercontent.com/assets/4712292/16260492/f5ade2ce-3867-11e6-9e7b-ebc9ec3a02e9.png)

**Comment by flexzuu** [comment]
Related Issue: #281
