### ISSUE TITLE
Very poor performance

### ISSUE THREAD

**Issue by EvNaverniouk** [FormidableLabs/victory#287]
At the request of @boygirl I have created a simple test case illustrating the very poor performance of Victory. For my team, this is by far the biggest problem right now. It makes our app unusable. I have tried to keep the example as concise as possible while still illustrating our use case and data set.

Please clone https://github.com/EvNaverniouk/victory-performance to see the issue. The test case renders 5 rows of BarChart components with a very large data set. Below that charts are two controls.

- Control A: Changes the pan of the domain (ie. The min and max values of the X domain range)
- Control B: Changes the size of the domain (ie. The max value of the X domain range)

Changing Control A will still only render 10 bars per chart, so the rendering should be very fast. Changing Control B will tell the charts to render more and more nodes -- for testing rendering performance.

The main problem this illustrates, is that even without any events, without any custom styling and with a tiny range, the rendering performance of the charts is so poor that changing the value of Control A is un-useably slow (5s to re-render). This is before we even get to rendering thousands of items. The example is using the production build of React. I can confirm that React's internal methods are not the ones causing the slow down. All the slow functions appear to be coming from the Victory codebase.

Our hope is to get performance to near-parity of this app: https://www.tradingview.com/chart/dRvq5XyR/ (granted they use Canvas, but their use case, interactions and data size are similar to ours).

Doing some simple profiling on the code, the biggest offenders seem to be:
- `renderData()` in the `VictoryBar` component (because it loops over the entire dataset, instead of only the visible domain)
- `getBaseProps()` in `helper-methods` for `VictoryBar` (because it also loops over the entire dataset and generates new objects for each)

Here is what the Timeline chart looks like for a single re-render:

![screen shot 2016-06-27 at 12 05 10 pm](https://cloud.githubusercontent.com/assets/226640/16392186/746abe5c-3c5f-11e6-9c9f-bef06d20fae6.png)

Can you help advise? Is there anything that can be done to improve this, or should we start looking into Canvas for our needs? I understand SVG can only go so far, but I think the example isn't that unreasonable. This large dataset SVG example (http://syntagmatic.github.io/parallel-coordinates/examples/slickgrid.html) is slow, but it's no where near as slow as the Victory one I attached above.

**Comment by iamdoron** [comment]
you might be able to solve it by changing the data you provide to Victory

for example, you might add these lines to `_renderCharts`
```javascript
            let chartData = machine.solution_vars.volume.values.filter((point) => (
				point.time > xMin && point.time < xMax
			));
			if (chartData.length > 1000) {
				chartData = chartData.filter((point, index) => (index % Math.ceil(chartData.length / 200) === 0))
			}
```

for the pan problem - you could just filter on the domain dates

for showing a lot of results - you could maybe average or bin the results using different segmentation - like minutes/hours/days (in my example I just filtered arbitrary values) - Of course, you might need the original high resolution, but I think you can lower it as the span of the domain grows - the question is by how much, of course, and if there are still performance issues

**Comment by dandelany** [comment]
I have considered this problem quite a bit while building my own charts in React, & I think it mostly boils down to two things:

* You are providing Victory with far more data than is actually being rendered
* and Victory does not assume that the data you provide is sorted

Since no sort order is assumed, Victory *must* loop through all data to find which data points are in the domain. So I would recommend that, if you have sorted data, you should filter it to the desired domain *before* passing it to a Victory chart - because if you know it's sorted ahead of time, you can filter it in O(n log n) time instead of O(n).

Long term, I think it might be helpful for Victory to have a boolean `isSorted` prop that can be passed to `VictoryChart` (which would be false by default). Passing `true` would be a way to signal Victory that you *know* your data is already sorted, and would cause Victory to use the faster domain filtering method.

**Comment by dandelany** [comment]
To clarify, the faster O(log n) domain filtering method I'm talking about is to [bisect](https://github.com/d3/d3-array/blob/master/README.md#bisect) the start and end dates (or numbers) of your dataset to find the start/end indices, instead of `Array.filter` which would be O(n)

**Comment by EvNaverniouk** [comment]
I have updated my example: https://github.com/EvNaverniouk/victory-performance
- I am now filtering the `data` by the domain. So instead of passing the whole data array to Victory I filter it to exclude any data points which aren't in the active domain range
- I added a pure d3 rendering example so you can see the comparison between d3 speed and Victory speed

**Panning Speed**

Using the filtered data set has dramatically improved the performance of brushing the domain. However, Victory is still about 5x slower than pure d3. Panning the domain range of 100 items about 10-15ms per render, whereas in Victory the same is about 50-60ms per render.

![pand3](https://cloud.githubusercontent.com/assets/226640/16494850/c9d861ea-3e9f-11e6-92ac-673b4f46d6f2.png)

![panvictory](https://cloud.githubusercontent.com/assets/226640/16494853/cc5e1f68-3e9f-11e6-9de4-498192c5493c.png)

**Domain Increase Speed**

Both d3 and Victory are quite sluggish when the domain range increased to display more data points. But again, Victory is about 5x the render time.

**Conclusion**

Given that d3 is also having a very hard time with a dataset of 10,000+ items, I don't think fair to expect Victory to do any better. So I'm happy to ignore it. But I still think the 5x slowdown between d3 and Victory using a data set of 100 items still warrants some investigation.

**Comment by boygirl** [comment]
@EvNaverniouk 5x performance hit is still definitely something we need to work on.  My colleagues have put together a list of first pass perf improvements that I will have time to implement over the next couple days. I'll reach out when those are ready to test, and we can iterate from there.

**Comment by EvNaverniouk** [comment]
FYI: I've revisited this issue with victory `0.12.1` after some improvements have been made in Victory. However, the is virtually no noticeable performance difference between `0.9.0` and `0.12.1` using my tests here: https://github.com/EvNaverniouk/victory-performance.

Panning through a 100 item bar chart is still about 60ms for re-rendering (at its fastest). Still about 5x behind pure d3.
