### ISSUE TITLE
tickValue unwanted grouping

### ISSUE THREAD

**Issue by filipemerker** [FormidableLabs/victory#288]
Hey, i'm with this weird problem:
![Grouped tickValues](https://d1ro8r1rbfn3jf.cloudfront.net/ms_110966/edzf7VPsHmFZy5I2cxJmdZAG31GTQJ/localhost_9090_webpack-dev-server_%2B-%2BGoogle%2BChrome%2B2016-06-28%2B16.40.06.png?Expires=1467229394&Signature=lFFNS1neJAURTjTU0dsCq1ZQZ1TP~7pSxyoB8RvnA10UHgrOvW11b~YcX2~PCy9tEBftub0Yz4r37CDsSGKPRWuKaffs5PcqvhYz2uoHQbIOwL6VQWo7R0yDSrrpi2N1Fym83LAlpPZqwHeR-r2E-VnFTq5ROJQYOSiL314T-tzatkqJrKv0Yn6d4ZEf2Dxax9ObdyCWaaAe9RvhGR~CBgsyge96lC6xsNfS3Nu4IqsIrRx-35SXV1uRPXCmE8TJULfVZ9oaKy6dq2oJWvC4vjnaJWrwvzhXCVx5k9RzxRdv7IFqIX1ntFD5UYBJTUg8kHsWoPupLqrkZU7ldpp8NA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

My code is
```js
    <VictoryChart
      height={270}
      width={props.chartWidth}
    >
      <VictoryBar
        style={{
          data: {
            width: props.barWidth
          }
        }}
        animate={{
          duration: 500,
          onExit: {
            duration: 1000,
            before: () => ({ y: -1 })
          }
        }}
        data={props.data}
        colorScale="qualitative"
      />
      <VictoryAxis
        style={{
          axis: { stroke: 'transparent' },
          grid: { strokeWidth: 0 },
          ticks: { stroke: 'transparent' },
          tickLabels: { fontSize: props.fontSize }
        }}
        tickValues={props.tickValues} // this renders as ['D', 'S', 'T', 'Q', 'Q', 'S', 'S']
      />
    </VictoryChart>
```

And if i change the `tickLabels` to `['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab']`, it works perfectly
![Grouped tickValues](https://d1ro8r1rbfn3jf.cloudfront.net/ms_110966/9zSo7P1StpagU4DHZdjtiCHK6aAfB4/localhost_9090_webpack-dev-server_%2B-%2BGoogle%2BChrome%2B2016-06-28%2B16.47.08.png?Expires=1467229656&Signature=XQsSkZzrI94bcCHWfmiigKT7KMUdvLJqqY0hKOOdC4nuwTVG3H1kS-l1BTSFed2ubkT7WOYrnKQYFZgJhnTzfKBaiOxw697qETisBNlG18VLg9JIUVV7Na4uDwErWgQG94q00Lnb-jf2NX2oZnvK5A0B22f8WQn9qtZU9-jibi0ohVFD501BcnPhZvS7iYJspMCDqutccXfgzAZlb~f3w-J0DV3fzqcijR3lkSuczbRiFayvbuDESvgbbIisbZmq-jQtg5UtZbENrQk0cHHnnOWnziVSzrfwu288qWVY4GK9BqH2qJQcddKxd6hh8lTrAcwXQ-A7j7BrqvdrG48Z3w__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by boygirl** [comment]
That's bizarre, we'll take a look

**Comment by ebrillhart** [comment]
@boygirl this is weird. i think it has to do with the categorical data grouping. it works okay until there's a chart with data used along with the axis, and then it gets messed up, so it doesn't have to do with the axis itself. doesn't happen with just letters, but any time a label gets used more than once.

**Comment by boygirl** [comment]
@ebrillhart oh! Thanks for figuring out the exact conditions that makes this happen. Categorical data gets converted into a string map. When categorical data appears in a data set, a unique set is created. That's appropriate for data. For tickValues that's kind of questionable, but since they're meant to be _values_ I think this expected behavior. Non unique tick labels should be applied with tickFormat

**Comment by ebrillhart** [comment]
@boygirl okay! should I just do a props documentation update then to reflect that?

**Comment by boygirl** [comment]
@ebrillhart yes please!
