### ISSUE TITLE
Any updates on using this library on react native?

### ISSUE THREAD

**Issue by dfguo** [FormidableLabs/victory#290]
I saw it on roadmap that it's targeting to release at the end June. Do we have an update on that? If not, what's the status now and how can I help?

**Comment by cablegunmaster** [comment]
https://github.com/FormidableLabs/victory-chart/issues/278  
I kinda have this as a update with RN 28.0 and  victory 0.9.2

**Comment by boygirl** [comment]
Check out `victory-chart-native` it's still missing events, but it's otherwise working

**Comment by rgoldiez** [comment]
@boygirl - This is great... but are there any instructions for using in an existing app?  Which npm packages need to be pulled down, etc.

**Comment by boygirl** [comment]
@rgoldiez I'm sorry that our docs are lagging our development. You can pull down the `victory-chart-native` and `victory-pie-native` npm packages and use the victory components from those packages as you normally would. i.e. `import { VictoryPie } from "victory-pie-native"`. The api for the native components is identical to the normal components

**Comment by rgoldiez** [comment]
@boygirl - If I want to start playing with Victory in my react native projects... which package(s) do I need to be installing?  Is `victory-native` enough?

**Comment by boygirl** [comment]
@rgoldiez infrastructure is still a little rough. Give `victory-native` a shot. If that's giving you trouble, try `victory-chart-native` / `victory-pie-native` directly
