### ISSUE TITLE
The [キロ] character is not displayed correctly in VictoryLabel.

### ISSUE THREAD

**Issue by Developer1103** [FormidableLabs/victory#2912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Victory version

36.4.0

### Bug report

```markdown
Hi.
In VictoryLabel on iOS, it is displayed as [キロ]->[㌔], [メートル]->[㍍].
If you could teach me how to display it as [キロ], [メートル], I would be grateful. 
Please help me.
```

### Environment

```markdown
- Device:iPhone
- OS:iOS
- Node:
- npm:
```

**Comment by coston** [comment]
Hey @Developer1103, thanks for creating this issue. I've confirmed that this issue exists. It looks like something is forcing ligatures to be rendered in iOS, but only when using the label component. 

<img width="424" alt="image" src="https://github.com/user-attachments/assets/7173ff7d-6852-4952-8771-6ec7335481b7">

**Comment by coston** [comment]
The source of the issue is [react-native-svg](https://github.com/software-mansion/react-native-svg/blob/0c30339c5559a0fe01c20e13a7d6f74f7632c564/apple/Text/RNSVGTSpan.mm#L403 
), with Victory uses to render the `VictoryLabel` text. 

The quick fix is to simply set `fontVariantLigatures: "none"` in your styles.

```jsx
<VictoryLabel
          text="メートル Coston"
          x={150}
          y={200}
          textAnchor="middle"
          style={{
            fontSize: 20,
            fill: "black",
            fontVariantLigatures: "none",
          }}  
        />
```

**Comment by Developer1103** [comment]
Thank you so much for your help.
I will check it out. 
Please continue to take care of me.

**Comment by Developer1103** [comment]
I was able to solve it.
Thank you very much for your help.
