### ISSUE TITLE
I don't understand how to correctly size a pie chart

### ISSUE THREAD

**Issue by lropero** [FormidableLabs/victory#298]
I'm having a hard time trying to understand how the height prop for `<VictoryPie />` works.

The pie size seems to depend on the browser window size and is not keeping a fixed height when I resize the browser window. Still, passing out different numbers to the height property does affect the initial size that gets rendered.

Am I missing something here?

**Comment by boygirl** [comment]
@lropero by default VictoryPie will render in a responsive SVG with `viewBox={`0 0 props.width props.height}` and parent styles `{width: "100%", height: "auto"}`. You can override this behavior by adding the prop `standlone={false}` and rendering the resulting `<g>` tag in your own `<svg>`
