### ISSUE TITLE
Lists of charts

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/victory#30]
http://www.highcharts.com/demo
http://www.datavizcatalogue.com/
https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf

**Comment by knowbody** [comment]
@colinmegill should we move this somewhere? maybe something like resources docs or wiki page?

**Comment by colinmegill** [comment]
Yeah a wiki on chart would be a good place
