### ISSUE TITLE
Ecology docs for Events

### ISSUE THREAD

**Issue by hexatonics** [FormidableLabs/victory#300]
It would be wonderful to provide an example in the demos of charts and components interacting together.   For example, changing some element of the underlying data using a slider or a dropdown box. Even more useful would be something similar to dc.js, where clicking on the graphs themselves provides interaction.

**Comment by paulathevalley** [comment]
We added a dropdown to change the data sets in the VictoryChart docs that will be visible in the next release! This particular example will demonstrate how the axes behave with different data sets. 

We were struggling to figure out other use cases in the docs for them, actually. Do you have a specific example or use case that you'd like to see?
