### ISSUE TITLE
"Manually calling PropTypes"-warnings in 15.3.0

### ISSUE THREAD

**Issue by ekmartin** [FormidableLabs/victory#307]
Using React 15.3.0 I get a lot of warnings on the form of:

```
Warning: You are manually calling a React.PropTypes validation function for the `cornerRadius` prop on `VictoryPie`. 
This is deprecated and will not work in the next major version. 
You may be seeing this warning due to a third-party PropTypes library. 
See https://fb.me/react-warning-dont-call-proptypes for details.
```

Happens for lots of different components and props. Feel free to move this if it rather belongs in `victory-chart` or similar.

**Comment by boygirl** [comment]
I think we're running into the false positive situation described here in our custom prop types. 
https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by topheman** [comment]
I can see that this issue is closed, I still have the same problem, emmited via VictoryBar and VictoryLabel :

```
Warning: You are manually calling a React.PropTypes validation function for the `domain` prop on `VictoryBar`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

I'm using:

* react / react-dom 15.3.2
* victory-bar@4.0.1
* victory-pie@6.0.0

Happens on: https://github.com/topheman/d3-react-experiments

**Comment by boygirl** [comment]
@topheman I'm really sorry for the confusion, but the `victory-bar` package you're using a deprecated and very, very out of date. The `VictoryBar` component is now included as part of the `victory-chart` package. Please try that instead. 

p.s. thank you for including versions with your issue!

**Comment by boygirl** [comment]
@topheman yep, that's the right way to import what you need from Victory. I'll create an issue to have those deprecations notices show up on npm install.
