### ISSUE TITLE
`victory` very slow to `npm install`

### ISSUE THREAD

**Issue by EvNaverniouk** [FormidableLabs/victory#313]
Related to #186, I've run `slow-deps` (https://www.npmjs.com/package/slow-deps) on my project, and noticed that `victory` and `victory-chart` are the biggest offenders for causing `npm install` to be slow. The output looks like this:

```
Analyzing 79 dependencies...
[====================] 100% 0.0s
------------------------------------------------------------------------
| Dependency                               | Time    | Size   | # Deps |
------------------------------------------------------------------------
| victory                                  | 1m 0.1s | 57 MB  | 383    |
| victory-chart                            | 42.8s   | 31 MB  | 381    |
| webpack                                  | 18s     | 14 MB  | 192    |
....
------------------------------------------------------------------------
Total time (non-deduped): 6m 11s
Total size (non-deduped): 350 MB
```

Victory solidly holds the top 2 spots and accounts for 27% of the total install time for my project (which has ~70 other dependencies). Victory currently takes `1m 42s` to install. The next nearest one (3rd spot) is `webpack` which only accounts for 0.04% of time with `18s`.

I'm wondering if there's anything that can be done to mitigate this.

**Comment by boygirl** [comment]
Fixed in `victory0.13.3`

**Comment by EvNaverniouk** [comment]
Fix confirmed. New results are:

```
| victory                                  | 5.3s  | 8.6 MB | 17     |
```

From 88MB to 8.6MB.  Thank you!
