### ISSUE TITLE
VictoryGauge

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#318]

**Comment by imranolas** [comment]
Do we have any examples or a specification for this feature?

**Comment by imranolas** [comment]
https://github.com/FormidableLabs/victory-gauge/issues/1

**Comment by CASandmann** [comment]
What's the status on this feature?  Is it planned on being worked on anytime soon?  My team is using the victory-gauge on npm, but it looks like it isn't being supported at the moment.

**Comment by ophite** [comment]
what about for React-Native ?

**Comment by beccanelson** [comment]
@boygirl Is this still planned work, or can we close this one?

**Comment by boygirl** [comment]
I think this one can be closed. We don't have specific plans to build it
