### ISSUE TITLE
support `animate={true}`

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#320]
For users who just want all the default animation behavior. Let all components have `animate={true}` as a default so that they will have cool onLoad animations. `animate={false / null}` will still create static charts.

**Comment by nfcampos** [comment]
Could this maybe be defined on a theme, or is that kind of outside of what themes are for?

**Comment by zachhale** [comment]
This sounds like a great use for themes. Thoughts @boygirl?

**Comment by boygirl** [comment]
@zachhale yes! If you could fold animation themes into this ticket, that would be great. I think the `defaultTransitions` need to remain as static methods on each Victory component though, so that they can be picked up correctly by `VictoryTransition`
