### ISSUE TITLE
[Homepage] Code examples very small

### ISSUE THREAD

**Issue by jbreckel** [FormidableLabs/victory#325]
Hey there,

love this library.
While trying to figure some stuff out, I realized, that the code examples for bigger code snippets like the [Theme Park](https://formidable.com/open-source/victory/recipes/theme-park/) are very small to get an overview.

Is there a way to make those samples bigger?

Maybe hide the code at first and make it expandable to see the whole sample at once.

Thanks

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#127
