### ISSUE TITLE
mixBlendMode not making it through to the HTML

### ISSUE THREAD

**Issue by netikular** [FormidableLabs/victory#328]
While using VictoryLine I'm trying to use the mix-blend-mode style attribute.

```
    <VictoryLine
        data={data}
        domain={{ y: [0, 10] }}
        width={100}
        standalone={false}
        style={
          {
            data: {
              stroke: color,
              fill: 'none',
              strokeWidth: 2,
              mixBlendMode: 'multiply',
            }
          }
        }
    />
```

The HTML that is generated looks like: (zoomed into just this path)

```
<g role="presentation" style="height: auto; width: 100%;">
<path d="...CUT..." vector-effect="non-scaling-stroke" style="stroke: #795548; fill: none; stroke-width: 2px; opacity: 1;">
</path></g>
```

You can see that the color, strokeWidth, fill all come through but the maxBlendMode does not.

I've investigated how the Helpers.getStyles method works and I could not find any reason for the styles to be filtered out.

I also looked into Radium but I could not find any reference to filtering out style attrs.

**Comment by boygirl** [comment]
Can't reproduce.
