### ISSUE TITLE
Investigate portal pattern for tooltips

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#329]

**Comment by nfcampos** [comment]
I've actually done something like this recently, but got it to work for only one tooltip at a time, more than one requires some sort of unique keys that distinguish one tooltip from another, I think. I can open a PR with what I've got, interested @boygirl ?

**Comment by boygirl** [comment]
@nfcampos yes, please!

**Comment by nfcampos** [comment]
here it is https://github.com/FormidableLabs/victory-chart/pull/389

**Comment by boygirl** [comment]
Specs: 

- [ ] `VictoryContainer` gets a `portalComponent` prop that it will always render within the main `svg`
- [ ] new `VictoryPortal` component (naming?)
- [ ] `VictoryTooltip` gets a `usePortal` (`renderToPortal` naming?) boolean prop that causes it to render either in the portal container or like usual.

**Comment by nfcampos** [comment]
VictoryPortal PR at https://github.com/FormidableLabs/victory-core/pull/141

**Comment by nfcampos** [comment]
@boygirl you don't think it's worth it for the `usePortal` functionality to be done inside a HOC like @cpb mentioned? Does it make sense for any other component?

**Comment by boygirl** [comment]
Interesting... Yes, it would be useful for `VictoryVoronoi` which should usually end up rendered above other components. And potentially for labels generally.

**Comment by nfcampos** [comment]
ah, so i was thinking that VictoryTooltip, VictoryVoronoi,etc. could just be exported already wrapped in the HOC, and the boolean prop would control whether it was rendered in the portal or the usual way. what do you think?

**Comment by boygirl** [comment]
Perfect! And we can export the HOC from victory core too, in case someone wants to use it for something unusual

**Comment by nfcampos** [comment]
exactly

**Comment by nfcampos** [comment]
and what's that HOC called then? `VictoryInPortal`? or is that too similar to `VictoryPortal`? or since t's a HOC maybe a non-capitalised name, maybe just whatever name we decide to use for that boolean prop can be used for the HOC itself as well?

**Comment by boygirl** [comment]
Yeah, I think it should match the boolean prop name. `usePortal` `renderInPortal` ? Wrapping a component in it should make it render in the portal with no other modification, so we will have to do something a little special with VictoryTooltip to turn that behavior on and off with the prop

**Comment by nfcampos** [comment]
I was thinking that a component wrapped in this HOC would either render in portal or in its usual place, depending on the value of the prop, which would default to true so that just wrapping would render it in the portal with no other modification like you said.

**Comment by boygirl** [comment]
I was thinking we could do something like we do with `VictoryTransition`
```
if (animate) {
      return (
        <VictoryTransition animate={animate}>
          {React.createElement(this.constructor, props)}
        </VictoryTransition>
      );
    }
```
So a component wrapped in the HOC will _always_ render in the portal. And we can decide whether to return it wrapped or not depending on the prop in `VictoryTooltip`

**Comment by boygirl** [comment]
But I think it comes out about the same either way.

**Comment by nfcampos** [comment]
ah I see, that may actually be better

**Comment by nfcampos** [comment]
might want to reopen this seeing as the third item in your list is yet to be done
