### ISSUE TITLE
Add support for pointerOffset and pointerAngle to VictoryTooltip / Flyout

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#332]
_From @boygirl on September 14, 2016 21:53_

_Copied from original issue: FormidableLabs/victory-core#136_

**Comment by boygirl** [comment]
Also requested by https://github.com/FormidableLabs/victory/issues/941

**Comment by gokulramesh71** [comment]
Hey, any heads up on when this will be fixed?

**Comment by radShah** [comment]
Was this resolved?
