### ISSUE TITLE
Warn user if setState is called before an animation frame finshes

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#337]
_From @boygirl on August 11, 2016 7:1_

if `setState` is being called faster than the chart is animating (duration + enter/exit transition durations) it animates unpredictably.

_Copied from original issue: FormidableLabs/victory-core#106_

**Comment by sto3psl** [comment]
This also happens if I use the `labels` prop on `VictoryVoronoiContainer`. When I hover over the chart the animation gets blocked and does weird things. 

Is there any reliable workaround to block all user input when an animation is happening?

**Comment by boygirl** [comment]
All of the evented containers have a `disable` prop. You can set that when you trigger an animation and clean it up during the animation's `onEnd` callback. 

I'm going to close this issue as there's no plan to implement animation blocking
