### ISSUE TITLE
Firefox displays Material Theme incorrectly 

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#338]
_From @paulathevalley on August 8, 2016 22:24_

The material theme on Firefox is resulting in overflow.

Material theme:
![screen shot 2016-08-08 at 3 18 31 pm](https://cloud.githubusercontent.com/assets/768965/17498346/aaa3e2cc-5d7b-11e6-8f77-4fdc5412123d.png)

Default theme:
![screen shot 2016-08-08 at 3 18 39 pm](https://cloud.githubusercontent.com/assets/768965/17498354/b4e6e0b8-5d7b-11e6-8601-5fc6610293e5.png)

On changing the default padding prop on VictoryChart, it's alleviated, but I am not sure if this is the cause: 
![screen shot 2016-08-08 at 3 22 57 pm](https://cloud.githubusercontent.com/assets/768965/17498420/1e869220-5d7c-11e6-9f7d-4b6aea747e7e.png)

_Copied from original issue: FormidableLabs/victory-core#100_

**Comment by paulathevalley** [comment]
Made a lot of changes, so this is resolved now! 

![screen shot 2016-09-16 at 9 08 19 am](https://cloud.githubusercontent.com/assets/768965/18592730/227d2d78-7bed-11e6-9aa8-e0aad6c1363d.png)
