### ISSUE TITLE
improve animation perf across all components

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#34]
especially composed components like chart with animating children

**Comment by exogen** [comment]
Adding a note on what I've investigated so far:

1. Setting NODE_ENV to production skips a *lot* of checks, and demos that were running at ~20-30 fps in dev mode jumped to 55-59 fps in prod mode. In dev mode, the function taking the most time is Radium's `checkProps` (in the component demo I checked). If you're profiling, focus on the things that are slow in prod mode first.
2. `shouldComponentUpdate` has been very difficult to implement every time I've tried. One reason is that d3's interpolator reuses the same object on each step (when interpolating objects), so the previous and current value will always compare strictly equal.
