### ISSUE TITLE
1px of space between stacked bars

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#345]
_From @angelanicholas on August 17, 2016 19:25_

very subtle but you can see 1px of the dark blue bars in the background peaking through between the overlaid stacked bar:

<img width="171" alt="screen shot 2016-08-17 at 12 25 52 pm" src="https://cloud.githubusercontent.com/assets/2624467/17750179/d01c6280-6475-11e6-891a-52ecb351791e.png">

_Copied from original issue: FormidableLabs/victory-chart#350_

**Comment by klaemo** [comment]
could this be due to subpixel rendering? I've noticed that victory doesn't seem to round values to full pixels.

**Comment by sto3psl** [comment]
I think there is a similar problem in this chart, where the bottom of the red bar blurs a little but the black one is fine.
If I manually round the numbers in the `d` attribute of the `path` element everything looks nice and crisp. I also think it's the subpixel rendering which kind of isn't a problem on 2x displays (Retina Macbook, iPhone) but quite visible on lower res screens.

![bildschirmfoto 2017-03-07 um 18 56 01](https://cloud.githubusercontent.com/assets/5798652/23670456/068c5b0e-0368-11e7-8cab-ccdbb1e1f505.png)

**Comment by boygirl** [comment]
@sto3psl that seems like a good solution. I'll round those values. Thanks

**Comment by beccanelson** [comment]
It looks like this has been fixed, and there hasn't been any activity here in a few years. Closing for now!
