### ISSUE TITLE
low hanging fruit for perf improvement

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#346]
_From @boygirl on August 16, 2016 1:44_

Map / reduce can be replaced with length cached for loops
https://github.com/FormidableLabs/victory-chart/blob/master/src/helpers/domain.js#L108
https://github.com/FormidableLabs/victory-chart/blob/master/src/helpers/domain.js#L161
https://github.com/FormidableLabs/victory-chart/blob/master/src/helpers/wrapper.js#L223
https://github.com/FormidableLabs/victory-chart/blob/master/src/helpers/data.js#L56
https://github.com/FormidableLabs/victory-chart/blob/master/src/helpers/data.js#L71

more perf improvements in this issue
https://github.com/FormidableLabs/victory-chart/issues/359

_Copied from original issue: FormidableLabs/victory-chart#345_

**Comment by karanjthakkar** [comment]
@boygirl Can you update the description to provide more info? Would love to help out here. Right now all the links 404. I guess there has been some major rehaul of the `victory-chart` repo.

**Comment by boygirl** [comment]
@karanjthakkar sorry about that! This code did indeed move to `victory-core`

Here are the remaining relevant code sections:

https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/domain.js#L108
https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/domain.js#L189
https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/domain.js#L220
https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/data.js#L79
https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/data.js#L134
https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/data.js#L167

**Comment by karanjthakkar** [comment]
@boygirl no problem. I did end up finding it going through the changelog. Could you elaborate a bit on what you mean by `length cached for loops`? An example perhaps?

**Comment by boygirl** [comment]
Sure thing. You can see an example of the pattern we moved to here:
https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-bar/helper-methods.js#L106

**Comment by DerekMaffett** [comment]
Benchmarks showed this change to have little effect. After discussion, I've gone through and replaced `map/reduce` manual algorithms with the native versions.
