### ISSUE TITLE
Force layout chart

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#349]
_From @nfcampos on June 27, 2016 20:46_

Hi,

I'm using `victory` in one project for most charts and I had the need for a force layout chart, which I've implemented. If you guys are interested in having a force layout chart as part of `victory` I can open a pull request. if yes, I have some questions before proceeding, regarding the API for the component, since working with the simulation + the several available forces in `d3-force` makes it a but different from all the other chart types with a `data` array.

Thanks,
Nuno

_Copied from original issue: FormidableLabs/victory-chart#276_

**Comment by boygirl** [comment]
@nfcampos That sounds great. We haven't had any full components authored by folks outside our org yet so there are a couple things to get ironed out. Are you in the gitter channel https://gitter.im/FormidableLabs/victory? Let's chat directly about getting this set up.

**Comment by chrisjcook** [comment]
Hey @boygirl has there been any movement on this? Would love to use a wrapper for d3-force :)

**Comment by boygirl** [comment]
@chrisjcook this part of the project still needs some work to make it consistent with other victory conventions, but @nfcampos already built a useable prototype that you can test out. 

https://github.com/FormidableLabs/victory-force

**Comment by beccanelson** [comment]
I'm going to close this for now since this feature hasn't been pulled into the monorepo, and there hasn't been any activity for a few years.
