### ISSUE TITLE
victory-legend

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#35]

**Comment by knowbody** [comment]
@boygirl can you give more details on this, please

**Comment by boygirl** [comment]
This should be a box with colored symbols / lines and corresponding data series names. It should take an array of colors, symbols, and names, as well as an absolute position x, y. Chart should be able to generate one for its child data, and should also be able to use a user provided legend component, and auto fill it with missing props. i.e. names / colors from data.

**Comment by joanllenas** [comment]
+1

**Comment by mdramos** [comment]
http://bl.ocks.org/bobmonteverde/2070123

legend with colored circles would be cool ...

**Comment by boygirl** [comment]
@knowbody are you interested in giving this feature a shot?

**Comment by knowbody** [comment]
@boygirl yup, I'll ping you with some code, once I have something

**Comment by knowbody** [comment]
I have no time to do it this week, but will try next week.

**Comment by StevenLangbroek** [comment]
@boygirl can you assign the ticket to me? thanks :)

**Comment by adammenges** [comment]
Is this on track for release at the end of the month? :tada:

**Comment by ekmartin** [comment]
Any update on this? Would be really cool 👍

**Comment by ahmedghoneim92** [comment]
Hi, I'd like to take a shot at this issue. Can you let me know what the requirements are?

**Comment by boygirl** [comment]
@ahmedghoneim92 the reason this feature hasn't been started has a lot to do with nailing down the requirements actually! But it you'd like to get stated on something generic, it should live in the `victory-core` repo. You can chat with me in the gitter channel about collaborating https://gitter.im/FormidableLabs/victory

**Comment by dandelany** [comment]
FWIW I've used this library before, it may be a good starting point for determining requirements:

http://d3-legend.susielu.com/

**Comment by angelanicholas** [comment]
Fixed in https://github.com/FormidableLabs/victory-core/pull/189
