### ISSUE TITLE
BUG: incorrect axis date formatting. Sundays appear as months

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#352]
_From @boygirl on May 19, 2016 16:27_

@alikhani provided the following fiddle in which Sundays are being misrepresented as "Jun". Is this something in Victory, or is this a bug in d3-scale default tick formatting for time scales?
https://jsfiddle.net/alikhani/t9s1ycx1/5/

_Copied from original issue: FormidableLabs/victory-chart#219_

**Comment by boygirl** [comment]
_From @awesomebob on May 19, 2016 22:36_

Here's another fun example: https://jsfiddle.net/AwesomeBob/6fyfs28p/1/ with the sequence

    [Thu 31, 2016, Sat 02, Jan 03, Mon 04]

I found that this is in fact the default setting for d3.time.scale.

"The tick format provided by d3.time.scale is a multi-scale tick format, meaning that it formats times differently depending on the time." found on [this example](http://bl.ocks.org/mbostock/4149176)

The d3 docs explains how to [define your own multi-scale tick format](https://github.com/d3/d3/wiki/Time-Formatting#format_multi)

**Comment by Aweary** [comment]
I looked into this today and verified that it is indeed the default behavior for `d3-scale`. Sundays will always be parsed using `formatWeek` as it "rounds down" the date to the beginning of the week and [checks if floored date value is less than the initial date](https://github.com/d3/d3-scale/blob/master/src/time.js#L65). In the case of Sundays it's not less than (they are equal) so it parses it using the week scale.

**Comment by boygirl** [comment]
This is a know issue with d3 time formats
