### ISSUE TITLE
Feature Request: Annotations on Line Chart

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#353]
_From @andrewhathaway on March 16, 2016 21:19_

On a previous project, I "hacked" the ability to have annotations in to NVD3. My next project would also like to have this feature and I'd love to use Victory!

Annotations would consist of the following red line on a specific X value:

![image](https://cloud.githubusercontent.com/assets/1188830/13829010/9460d85c-ebbc-11e5-9fac-d6ef96c7d050.png)

An when hovering over said red line, it would show an extra tooltip on the right with a specific message.

![image](https://cloud.githubusercontent.com/assets/1188830/13828993/795f7086-ebbc-11e5-844a-ff2c9a376688.png)

It would be great to see this functionality in Victory-Chart!

Thanks.

_Copied from original issue: FormidableLabs/victory-chart#155_

**Comment by boygirl** [comment]
@andrewhathaway sorry for the late reply. Work on events has progressed to the point that this is seeming like a viable feature. The last remaining difficulty is in coordinating events between several components, so that you could do stuff like call out points on several line components as you do in the second image. I will add static annotation / simple evented annotations to the roadmap for this next release, but coordinated events might be a bit further out.

**Comment by boygirl** [comment]
_From @andrewhathaway on May 7, 2016 9:47_

@boygirl No worries, better late than never! Great to see this being put on the roadmap, looking forward to the release. Thanks.

**Comment by evollu** [comment]
can I expect this feature in next few weeks?

**Comment by boygirl** [comment]
@evollu this feature wont be ready in time for your needs, but you should be able to add your own custom annotations, either with `VictoryLine` or by supplying your own custom children to `VictoryChart`. I'm around in the [gitter channel](https://gitter.im/FormidableLabs/victory) if you need help getting started.

**Comment by boygirl** [comment]
This feature should be accomplished with VictoryLine and VictoryLabel children
