### ISSUE TITLE
Time series bar chart not working in Safari 9.0.3 (11601.4.4)

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#354]
_From @boygirl on March 14, 2016 17:25_

_From @okonet on March 14, 2016 16:35_

Go to http://victory.formidable.com/docs/victory-bar/ and use following examples in Safari:

``` jsx
<VictoryBar
  data={[
    {x: new Date('2015-01-01'), y: 1},
    {x: new Date('2015-01-02'), y: 2},
    {x: new Date('2015-01-03'), y: 3},
    {x: new Date('2015-01-04'), y: 2},
    {x: new Date('2015-01-05'), y: 1}
  ]}
/>
```

``` jsx
<VictoryBar
  data={[
    {amount: 1, time: 1457537410000},
    {amount: 2, time: 1457547410000},
    {amount: 3, time: 1457557410000},
  ]}
  y={"amount"}
  x={(data) => new Date(data.time)}
/>
```

Both will be empty. They look perfectly fine in Chrome tho. See screenshot:

![2016-03-14 at 17 28](https://cloud.githubusercontent.com/assets/11071/13751561/06f71ab0-ea0b-11e5-9148-4df6d21bcd8c.png)

As a workaround I'm using moment.js to wrap the Date object for now.

_Copied from original issue: FormidableLabs/victory-bar#107_

_Copied from original issue: FormidableLabs/victory-chart#151_

**Comment by nfcampos** [comment]
(this appears to no longer be an on latest versions of Safari and Safari Technology Preview)

**Comment by okonet** [comment]
It looks like a Safari issue after all. See http://stackoverflow.com/questions/4622732/new-date-using-javascript-in-safari#4623148 and http://dygraphs.com/date-formats.html

**Comment by Aweary** [comment]
Might be worth mentioning somewhere that you should use momentjs or something if you are using dates and need to support older Safari versions

**Comment by olivia-leach** [comment]
I'm having this issue with both Safari and IE 11. Unfortunately when I wrap the date attribute in moment(), i.e.: `x={(d) => moment(d.date)}`, although the svgs path then do render in both Safari and IE11, my VictoryLine then looks like this (drawn totally out of sequential order):
<img width="905" alt="screenshot 2016-11-08 14 02 22" src="https://cloud.githubusercontent.com/assets/17397519/20113027/a6fc22ae-a5bc-11e6-9373-2ea0fb2ce458.png">

I've tried sorting the data by date to try to force it to draw in sequential order, but no luck.

**Comment by boygirl** [comment]
@olivia-leach to confirm, you're seeing correct behavior in Chrome / Firefox ?

**Comment by boygirl** [comment]
@olivia-leach I think I figured out part of what is going on. If your dates are coming in as strings and then being formatted with the x accessor, sorting by "date" will actually give you an alphabetic sort. It should be sorting by "x" automatically though. I can't reproduce the issues just using `x={(d) => new Date(d.date)}` with string data or `x={(d) => moment(d.date)}`

Please double check that you aren't accidentally sorting by a string key. You should also be including `scale={{x: "time"}}` in the `VictoryChart` wrapper.

**Comment by dnataraj** [comment]
@olivia-leach I got my time series correct. My dates are coming in as strings, so my transform was :         return { x: moment(o.Date), y: value } where o.Date is string, and on my VictoryLine I have scale={{x: "time", y: "linear"}} (as @boygirl pointed out). The chart finally appeared in IE/Edge.

**Comment by boygirl** [comment]
I'm going to go ahead and close this one
