### ISSUE TITLE
layout problems for stacked area charts with mixed negative and positive values

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#355]
_From @boygirl on March 2, 2016 1:20_

When stacked area charts have a mix of negative and positive data, the resulting charts look broken. 

<img width="426" alt="screen shot 2016-03-01 at 4 49 35 pm" src="https://cloud.githubusercontent.com/assets/3719995/13447606/ca0f3882-dfd1-11e5-80a2-852b72769997.png">

_Copied from original issue: FormidableLabs/victory-chart#132_

**Comment by stepek** [comment]
:+1:

**Comment by swittk** [comment]
Seems this hasn't been solved yet, yes?

**Comment by boygirl** [comment]
True. In fact I'm not sure what the solution _should_ be. Do you have thoughts on how charts like this should look, @swittk?

**Comment by salmituukka** [comment]
I think it would be great if one could set `y0` property similar as area to stacked areas as well. This would solve at least my use case regarding this issue:
![image](https://user-images.githubusercontent.com/42428595/57673411-7f690500-7624-11e9-89c8-2442d9dd1dc8.png)

**Comment by boygirl** [comment]
@salmituukka oh cool, I see what you're saying. Yeah!

**Comment by boygirl** [comment]
Oh, actually. That wouldn't address the scenario where say, the middle stack has a negative value in it

**Comment by boygirl** [comment]
@salmituukka I created a new issue for your suggestion
