### ISSUE TITLE
animating stacked bars has gaps when animating between negative and positive values

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#356]
_From @boygirl on March 1, 2016 18:31_

_From @boygirl on December 14, 2015 5:16_

when a group of stacked bars contains both negative and positive values, there can be gaps between the bars during the animation

_Copied from original issue: FormidableLabs/victory-bar#64_

_Copied from original issue: FormidableLabs/victory-chart#123_

**Comment by boygirl** [comment]
_From @coopy on January 20, 2016 21:30_

@boygirl see if this is still reproducible.

**Comment by beccanelson** [comment]
Closing for now, since this may not be reproducible.
