### ISSUE TITLE
Decide whether `datum` is required in `SliceLabel` & fix

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#364]
_From @ianwsperber on April 26, 2016 23:13_

The `SliceLabel` component will not render if an object is not passed into the `datum` prop, thanks to an [unguarded reference to that prop](https://github.com/FormidableLabs/victory-pie/blob/master/src/components/slice-label.jsx#L58). We should either add a guard or mark `datum` as required in the prop types. Note that `datum` is _not_ marked as required in the `VictoryLabel` component

_Copied from original issue: FormidableLabs/victory-pie#83_

**Comment by Aweary** [comment]
@boygirl I think this can be closed now? `SliceLabel` was replaced by `VictoryLabel` in [3.0.0](https://github.com/FormidableLabs/victory-pie/blob/ce0d32a5931f88cd04827723c2f1ff7bbc893fa3/CHANGELOG.md#300-2016-05-13).

**Comment by boygirl** [comment]
@Aweary thanks!
