### ISSUE TITLE
Circularly load Pie Chart

### ISSUE THREAD

**Issue by gauravbhusare** [FormidableLabs/victory#368]
I am passing data & getting Pie very well. But I wanted to load my Pie chart Circularly, that it should visibly start drawing from start angle to end angle. I am not understanding how to give animation for this. I tried with giving empty array as data on starting and updating data on componentDidMount using setTimeout function. But I am not getting expected output. Will you please help me solving this problem? Thanks in advance...

**Comment by gauravbhusare** [comment]
Now I am using VictoryAnimation as follows,
       <VictoryAnimation easing="quadOut"> 
        {(props)=>(<VictoryPie data={this.props.data} y={this.props.drawBy} 
        style={{display: 'inline-block',alignItems:'right',position:'relative',outerRadius:20+'px',data:    {stroke:"white",float:'right',strokeWidth:2},labels:{display:'none'}}}
        colorScale={this.colorData(this.props.data)} 
        labelComponent={<Flyout sumOn={this.props.drawBy} sum={this.getSum()} style={{backgroundColor: 'rgba(255,255,255,.5)'}} />}
        data-toggle="modal" data-target="#myModal"
        events={[
            {
              target: "data",
              eventHandlers: {
                onMouseOver: () => {
                  return [
                    {
                      target: "labels",
                      mutation: () => {
                        return {active: true};
                      }
                    }
                     
                  ];
                },
                onMouseOut: () => {
                  return [
                    {
                      target: "labels",
                      mutation: () => {
                        return {active: false};
                      }
                    }
                  ];
                },
                onClick: () => {
                  this.open()
                }
              }
            }
          ]}/>)}
          </VictoryAnimation>

though it is not showing any effect

**Comment by Aweary** [comment]
You should be able to get this effect using `<VictoryAnimation/>`. Just specify the `endAngle` in in the `data` prop.

```js
<VictoryAnimation data={[{ endAngle: 0 }, { endAngle: 360 }]}>
     {(({ endAngle }) => (
       <VictoryPie startAngle={0} endAngle={endAngle}/>
     ))}
</VictoryAnimation>

**Comment by gauravbhusare** [comment]
@Aweary  Thank you Animation is started, but it is continuously animating. It is going from start angle to end angle. I want it should stop animating once loaded.

**Comment by gauravbhusare** [comment]
My issue is solved. Thanks a lot for help.
