### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#37]
Begin testing components now that the api is more settled

**Comment by boygirl** [comment]
Add issues to all the repos 
"pass 10% test coverage"

**Comment by coopy** [comment]
We should determine what [coverage criteria](https://en.wikipedia.org/wiki/Code_coverage) to use for our baseline requirement:

- Statements (Has each statement in the program been executed?)
- Branches ( Has each branch of each control structure been executed?)
- Functions (Has each function in the program been called?)
- Lines 

_Branches_ is fairly comprehensive and is what I'd recommend going with.
