### ISSUE TITLE
VictoryVoronoiTooltip and styling the flyout

### ISSUE THREAD

**Issue by chriskurzeja** [FormidableLabs/victory#370]
As of 12.0.1 it does not appear to be possible to style the flyout component for a VictoryVoronoiTooltip - as far as I can tell there is no mechanism that setting flyoutStyle on the underlying Tooltip unless I define a label component and explicitly set it myself. 

Working example:
```javascript
<VictoryVoronoiTooltip labelComponent={<VictoryTooltip style={theme.toolTip.labels} flyoutStyle={theme.toolTip.flyout}/>}/>
```

Non-working example:
```javascript
<VictoryVoronoiTooltip style={theme.toolTip}/>
```

where 
```javascript
theme = {
  ...
 toolTip: {
        labels: { fontSize: 10, padding: 2, fontFamily: 'Open Sans'}, flyout: { stroke: 'red', fill: '#666666'    }
  }
  
}
```
In the non-working example the style for the contents of the tooltip is passed through. It is just that the flyout properties are not. This does seem to be at odds with both the described behaviour in the documentation and the code comments.

**Comment by boygirl** [comment]
@chriskurzeja yep, this is a bug. The `flyout` style is not getting properly passed through. I'll get this fixed today. Sorry about that!
