### ISSUE TITLE
Refactor components to extend from a base

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#372]

**Comment by nfcampos** [comment]
is this really a good idea? the conversation we had on https://github.com/FormidableLabs/victory-force/pull/1 about an hypothetical VictoryXY component suggests there are enough differences for this not to be feasible

**Comment by boygirl** [comment]
It's a good idea for repeated props. Events end up with a ton of boilerplate too. It should make it easier for people to write their own own components and have them work with the more complicated moving parts like the event system and animation transitions. A lot of the x-y specific stuff is still going to live on the individual components because of their different implementations

**Comment by nfcampos** [comment]
If it's for repeated props why not do something like 
```
class VictoryBase extends React.Component {
  propTypes = {
    events,
    animate,
    ...
  }

  ...
}

class VictoryBar extends React.Component {
  ...

  render() {
    return <VictoryBase {...pick(this.props, ['events', 'animate', ...])}>
     ...
    </VictoryBase>
  }
}
```

One advantage is if eg. VictoryBar needs to something special for eg. events all it needs to do is make changes to them before passing them to VictoryBase.

**Comment by pbeshai** [comment]
Might be better off using a higher order component? React devs seem to frown upon extending from anything besides React.Component (or PureComponent): https://twitter.com/dan_abramov/status/777077899191062528

**Comment by boygirl** [comment]
Hmm.  A lot of the child/parent interaction in `VictoryChart` `VictoryStack` etc depends on static methods on children _i.e._ `VictoryBar` has a static `getDomain`  method specific to that data type (bar charts should start at zero by default).  After this discussion and some more head scratching I'm thinking of using inverted inheritance HOCs how Radium does.
