### ISSUE TITLE
Remove lodash dep

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#38]
replace as many lodash methods as we can with es5 / es6 methods
rely on methods we cant replace (like `_.merge`) individually with https://www.npmjs.com/browse/keyword/lodash-modularized?offset=0

**Comment by knowbody** [comment]
these might be good resources for the replacement:
- https://www.reindex.io/blog/you-might-not-need-underscore/
- http://blog.xebia.com/you-might-not-need-lodash-in-your-es2015-project/

**Comment by boygirl** [comment]
@ryan-roemer is philosophically opposed to shipping polyfills last time I checked.

**Comment by ryan-roemer** [comment]
Libraries should never mutate your application merely from inclusion. So don't implement polyfills.

But requiring them is perfectly fine as long as it's well-documented. And maybe it makes sense throw an exception if they're not present in development mode.

**Comment by ryan-roemer** [comment]
And in your application server you absolutely should be doing polyfills. Just a single lib or component should respect and not change the environment in which it is used.

**Comment by ryan-roemer** [comment]
Last thought - non mutating ponyfills (not polyfills) are ok too, but be careful with interaction with real polyfills in apps

**Comment by knowbody** [comment]
I've just seen this: https://github.com/cht8687/You-Dont-Need-Lodash-Underscore
might be useful, so leaving this here.
