### ISSUE TITLE
VictoryTooltip should have constrain to visible area option / functionality

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#380]

**Comment by boygirl** [comment]
@mjanandparihar92 check out this guide on wrapping and customizing VictoryTooltip. You can use this to alter the x and y prop that are used to position your tooltip. https://formidable.com/open-source/victory/guides/tooltips/#wrapping-victorytooltip

The reason this has not been implemented in the main library is because there are many edge cases involved in correctly positioning the tooltip pointer when tooltips are constrained to the chart area. The pre-work for the feature involves supporting `pointerOffset` and `pointerAngle` so that when tooltips are moved so that they remain in the chart area they are still pointing to the correct point. 
You can get around this by giving your tooltip `pointerLength={0}`, but it's not an acceptable general solution IMO.

**Comment by mjanandparihar92** [comment]
@boygirl wow, that exactly I implemented yesterday, happy to see that this is correct way. thanks for replying. Victory should document this as there are other things which was needed and this is very common handling in any chart.  

what works for me :

```
// importing TextSixe here to  calculate the width 
import { VictoryTooltip, TextSize } from "victory";

class CustomTooltip extends React.Component {
  static defaultEvents = VictoryTooltip.defaultEvents;
  static propTypes = {
    chartWidth: PropTypes.number,
    chartHeight: PropTypes.number,
    x: PropTypes.number,
    y: PropTypes.number,
    style: PropTypes.any,
    text: PropTypes.any,
  }
  constructor() {
    super();
    this.orientation = this.orientation.bind(this);
  }

  render() {
    return (
      <VictoryTooltip
        {...this.props}
        orientation={this.orientation}
      />);
  }
  orientation() {
   // chartWidth and chartHeight we need to explicitly provide char `height` and `width`  
    const { chartWidth, chartHeight, x, y, text, style } = this.props;
    let maxTooltipText = "";
    (text || []).forEach((labelText) => {
      if (maxTooltipText.length < labelText.length) {
        maxTooltipText = labelText;
      }
    });
    // we need to calculate the size of label text to be able to check the cutoff  
    const size = TextSize.approximateTextSize(maxTooltipText, style);
    if ((x - size.width) < 0) {
      return "right";
    } else if ((x + size.width) > chartWidth) {
      return "left";
    } else if ((y + size.height > chartHeight)) {
      return "buttom";
    }
    return "top";
  }
}
```

I think tooltip `orientation` should provide these values or may be some flag prop to enable accessibility  of these value in `orientation` function. @boygirl  can you please have a look if this make sense. or i am missing something. 

also if we have a uses example of these props would be very helpful for any victory beginner like me.
and of course thanks for this awesome library :+1:
