### ISSUE TITLE
How to set outerRadius on victory-pie

### ISSUE THREAD

**Issue by yunda** [FormidableLabs/victory#381]
Is there a way to set up outer radius when creating a donut chart? Sorry if the answer is obvious but I did find it in docs.

**Comment by rob10e** [comment]
Why was this closed? Did you come up with a solution? I am trying to accomplish the same thing to embed smaller pie charts inside of a larger one.

**Comment by coolprobn** [comment]
@yunda , @rob10e what is the solution to this?
