### ISSUE TITLE
Aria problem: VictoryContainer creates elements with same id

### ISSUE THREAD

**Issue by cowboy** [FormidableLabs/victory#382]
Looking at [the VictoryContainer source](https://github.com/FormidableLabs/victory-core/blob/fb6a4e8764c9daacae340907702e72d9dce1723b/src/victory-container/victory-container.js#L108-L109) I noticed that each `VictoryContainer` creates elements with the fixed ids of `title` and `desc`.

What happens when there are multiple `VictoryContainer` in the same page? Don't `id` attributes need to be unique?

**Comment by chrisbolin** [comment]
definitely an issue. we have multiple tickets open for this, so I am closing this in favor of https://github.com/FormidableLabs/victory/issues/515
