### ISSUE TITLE
shapeRendering="optimizeSpeed" results in blocky visualizations

### ISSUE THREAD

**Issue by dylang** [FormidableLabs/victory#383]
It seems that `shapeRendering="optimizeSpeed"` [is hardcoded in the points primitive](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-primitives/point.js#L42) and [elsewhere](https://github.com/FormidableLabs/victory-core/search?utf8=%E2%9C%93&q=optimizeSpeed).

I didn't see anything about this in the documentation, or ways to override it in the code.

This is resulting in blocky visualizations. I was wondering if we can explain why this is set, and/or provide a way to change to a more attractive `shapeRendering` mode.

### `shape-rendering="OptimizeSpeed"`
![screen shot 2016-10-04 at 3 15 37 pm](https://cloud.githubusercontent.com/assets/51505/19088736/87dc7bae-8a45-11e6-8d5c-d715e583c816.png)

### `shape-rendering="auto"`
![screen shot 2016-10-04 at 3 16 14 pm](https://cloud.githubusercontent.com/assets/51505/19088744/94f11156-8a45-11e6-92f1-ad8d3b2f1fdb.png)

Thanks!

**Comment by Aweary** [comment]
It seems reasonable to allow primitive components and components that render these primitives to accept a prop to control this

**Comment by boygirl** [comment]
Yeah, agreed. Reasonable to abuse the `style` prop for this purpose?

**Comment by Aweary** [comment]
Are there any other cases where the `style` prop is used to define other attributes? If not, I would be hesitant about introducing new API abuse just for this.

**Comment by Aweary** [comment]
(also, I'd like to take a crack at implementing this)

**Comment by boygirl** [comment]
@Aweary yeah, we're already abusing it to pass `angle` and `verticalAnchor` to `VictoryLabel`. I kind of prefer that to growing the api surface. I would also be for just exposing the prop on the primitive  so it would be used like `dataComponent={<Point shapeRendering={"optimizeSpeed"}/>}`

**Comment by Aweary** [comment]
@boygirl from what I can tell `VictoryLabel` takes [`angle`](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-label/victory-label.js#L19-L22) and [`verticalAnchor`](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-label/victory-label.js#L102-L109) as props, and [falls back to `style.angle`](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-label/victory-label.js#L197)  only when `props.angle` is not defined. 

So it might make sense to just have a `shapeRendering` prop like you mentioned.

**Comment by boygirl** [comment]
@Aweary I think I'm in agreement. This prop is going to be used much less than the angle prop on VictoryLabel, so I'm pro just making it a prop on all the primitives that need it, and not exposing it anywhere higher up.
