### ISSUE TITLE
How does your interactive documentation work?

### ISSUE THREAD

**Issue by ccorcos** [FormidableLabs/victory#389]
First off -- great documentation. Bravo! 💯 

What are you using to make it, and particularly the interactive editor stuff:

https://formidable.com/open-source/victory/docs/victory-bar

**Comment by boygirl** [comment]
@ccorcos those pages are all built with [ecology](https://github.com/FormidableLabs/ecology), but you could also use [component playground](https://github.com/FormidableLabs/component-playground) by itself if you just want the interactive editor. Cheers!

**Comment by Noiwex** [comment]
Very hard to find a link to playground

**Comment by boygirl** [comment]
@Noiwex https://github.com/FormidableLabs/component-playground

**Comment by Noiwex** [comment]
I mean, it's hard to find in documentation.
