### ISSUE TITLE
Update contribution guide to include docs contrib.

### ISSUE THREAD

**Issue by valscion** [FormidableLabs/victory#393]
Victory is awesome :sparkles: and I'd like to help by e.g. fixing some errors I might come across in documentation by sending a PR. However, after scouring through your various repositories, I'm stumped. I don't know where the source for this page is: https://formidable.com/open-source/victory/docs/victory-errorbar

I see you're doing a docs restructuring over at https://github.com/FormidableLabs/victory-docs/pull/143 — it likely would help with future contributions.

I would've really liked to send a PR to fix https://formidable.com/open-source/victory/docs/victory-errorbar containing probably copy-paste references to VictoryCandlestick component:

> Use the events prop to attach events to specific elements in `VictoryCandlestick`

...but I have no clue where that line is coming from.

So:
- Where does the https://formidable.com/open-source/victory/docs/victory-errorbar code currently live in? Nowhere?
- How would you like to receive contributions to the docs?
- How do you build the docs locally to test out changes?
- I see the https://github.com/FormidableLabs/builder-victory-component/blob/master/dev/CONTRIBUTING.md doesn't really mention fixing documentation issues at all. Should it?'

Looking forward to using Victory in the future! 💖

**Comment by boygirl** [comment]
@valscion HI there! sorry for the delay! We in the middle of totally overhauling our docs, including infrastructure. The new docs should be live some time this week, but for now they're hanging out in this branch https://github.com/FormidableLabs/victory-docs/tree/feature-docs2markdown. In general, a PR directly to the `victory-docs` repo would be most welcome, but in this case I would ask you to hold out for a couple days. I think we might be out ahead of you in catching that error. 

To satisfy your curiosity, the docs previously lived in each repo, _i.e._ `victory-chart` and were pulled in by `victory-docs`. The docs have already been removed from the individual repos, but are not yet on master in `victory-docs`. Sorry for the confusion!

**Comment by valscion** [comment]
Ok, figured that much :) Thanks for the insight into how the current system works :+1:

Feel free to keep the issue open if you think so, I'm myself just looking forward to seeing the new docs. Keep up the good work!
