### ISSUE TITLE
Allow multiple axis within VictoryChart

### ISSUE THREAD

**Issue by jefffriesen** [FormidableLabs/victory#395]
It's great you have an example of a chart with multiple axis: https://formidable.com/open-source/victory/recipes/multiple-axes

It's also good to have an example of just using Victory components within an `svg` tag. But it would be nice to be able to use multiple axis within `<VictoryChart />`. Then we get other nice things like auto scaling and the resize handler. 

Are you considering adding this functionality to `<VictoryChart />`?

**Comment by boygirl** [comment]
@jefffriesen This is something we've thought about a lot, but it is very problematic. `VictoryChart` forcibly overwrites the `domain` and `scale` of all of it's children including `VictoryAxis`. The use case for most multi-axis charts is to actually have one of the axes represent a _different_ scale, and usually to have some data plotted on that scale, too, as in the example you reference above. 

I will think about whether there might be a way to enhance `VictoryGroup` to get you closer to what you want.

P.S. the resize handler you mention is actually just adding the `viewBox` attribute to the containing `svg` element and styling `width: "100%", height: "auto"`

**Comment by jefffriesen** [comment]
@boygirl Now that you say that I can imagine some of the complexities. The `viewBox` tip helps though. Thanks!
