### ISSUE TITLE
Fixed height, responsive width of VictoryChart

### ISSUE THREAD

**Issue by danielberndt** [FormidableLabs/victory#396]
Hey there!

I'm trying to create a chart which should have a fixed height of say 250px and fill 100% of the width of it's container. Kind of like a normal div would. Is that possible? I've looked through most of the documentation and couldn't find any pointers. (I imagine that ideally it should work via enabling `vectorEffect: "non-scaling-stroke"` as well.)

Cheers and thank you for this great library!
Daniel

**Comment by elisechant** [comment]
or setting preserveAspectRatio and/or viewbox on `<svg>`

**Comment by danielberndt** [comment]
What I'm aiming for is a time series that spans the whole width of the screen. Thus rewarding users with larger screens with very high fidelity and yet have everything being legible on smaller screens.

Basically like this example: http://dygraphs.com/gallery/#g/resize

**Comment by boygirl** [comment]
@danielberndt you can set `standalone={false}` on `VictoryChart` and it will render a `<g>` tag that you can render inside a custom `<svg>`

**Comment by samkelleher** [comment]
Coming here with the same issue. Once the SVG has been made it's scaled literally, so if you have a wide screen, a graph doesn't get wider but larger in both height and width, so a simple graph will be full screen. There seems to be some 4:3 aspect built in somewhere even if you override the width + height. I had some success by setting the width/height props to the pixel dimensions of the examined container *after* it had been rendered - then listening to resize, although the font sizes were all off. So if you set a 10px fontSize, it might end up being 3px or 23px depending on how much the image ends up being scaled.

**Comment by boygirl** [comment]
@samkelleher @danielberndt Victory renders responsive SVGs using the `viewBox` attribute which is aspect ratio based. You can read more about how responsive container interact with other props and some options you have for altering this default behavior here https://formidable.com/open-source/victory/guides/layout/

tl:dr the ~4:3 aspect ratio is coming from the width and height props defined in Victory's default theme https://github.com/FormidableLabs/victory-core/blob/master/src/victory-theme/grayscale.js

**Comment by jcbmb** [comment]
Hi all, so is there no way of doing this at all?
Trying to achieve the same thing as @danielberndt but no luck so far...

**Comment by boygirl** [comment]
@jcbmb you can change the aspect ratio by altering the `width` and `height` props on `VictoryChart`. Unfortunately responsive svgs don't scale things like text. 

The way to achieve what your after would be to add a resize handler to your container and update `width` and `height` on VictoryChart as you resize. You could also update your font sizes in your style prop at the same time.

**Comment by cbranch101** [comment]
If anyone is looking for an easy way to do this, I'd recommend using [`react-dimesions`](https://www.npmjs.com/package/react-dimensions)

All you have to do use the HOC they provide to get the height and width of the container, and then provide them to the chart, and everything works exactly how you'd expect.

**Comment by purplecones** [comment]
Thanks for posting that @cbranch101. Very handy.

**Comment by sooheon** [comment]
Curious how it's done in this showcase: https://projects.fivethirtyeight.com/sumo/

That's exactly the behavior I want (except how laggy the resize is--is this a Victory limitation?), especially the font sizes remaining constant. Victory by default gives you huge fonts for full-width charts.

**Comment by jasonhealy** [comment]
This is one way:

```
constructor(props) {
    super(props);

    this.state = {
      chartWidth: 500
    }
  }

  componentDidMount() {
    window.addEventListener('resize', this.updateDimensions.bind(this));
    // remove this on unmount 
  }

  updateDimensions(event) {
    this.setState({
      chartWidth: event.target.innerWidth
    }) 
  }
```

In your render function:
```
<svg viewBox={"0 0" + " "+ this.state.chartWidth +" " + "350"}  preserveAspectRatio="none" width="100%">
        <VictoryChart
          domainPadding={{x: 40}}
          standalone={false}
          width={this.state.chartWidth}
          height={350}
          >
         // Chart stuff 
          </VictoryChart>
</svg>
```

**Comment by normanaranez** [comment]
@jasonhealy thanks but one thing problem with the code, the font size are too small. how can i adjust the font-size base on the example you have?

**Comment by rweller59** [comment]
I see several comments that say 'create a resize handler' to prevent font sizes from becoming too small when using Victory with flex but an example sure would be helpful if anyone has one.

**Comment by rossdack** [comment]
@rweller59  I'm using Jason's method directly (i.e. it's not nested inside SVG tags) with VictoryChart and it works great. My VictoryCandlestick grows and shrinks horizontally, font sizes remain the same, and the x-axis is populated with more labels when space allows.

**Comment by srph** [comment]
I know this is an old thread, but in case anyone needs responsive charts that respect the container's (aka parent element)'s width:

## `ContainerWidthSizer.tsx`
```tsx
import * as React from 'react'

interface State {
  width: number
}

interface Props {
  children: (state: State) => React.ReactNode
}

class ContainerWidthSizer extends React.Component<Props, State> {
  state = {
    width: 0
  }

  container: HTMLDivElement

  componentDidMount() {
    this.setState({
      width: this.container.getBoundingClientRect().width
    })
  }

  render() {
    return (
      <div ref={c => this.container = c}>
        {this.props.children(this.state)}
      </div>
    )
  }
}

export default ContainerWidthSizer
```

## Usage
```tsx
<ContainerWidthSizer>
  {({ width }) => (
    <VictoryChart style={styles.chart} domain={{ y: [0, 31] }} height={box.height} width={width}>
  )}
</ContainerWidthSizer>
```

**Comment by alamothe** [comment]
I found this library: https://github.com/ctrlplusb/react-sizeme, seems maintained and well-supported.

**Comment by eijimine** [comment]
@jasonhealy  -Thank you, this worked beautifully!

**Comment by bronsonavila** [comment]
@jasonhealy Thank you so much!

**Comment by vjsingh** [comment]
Alternative hooks solution:

```
  const [size, onLayout] = useComponentSize();
  <View onLayout={onLayout}>
    <VictoryChart width={size?.width} height={300}>
    ...
```
**UseComponentSize.tsx**
```
import * as React from 'react';

const useComponentSize = () => {
  const [size, setSize] = React.useState(null);

  const onLayout = React.useCallback(event => {
    const { width, height } = event.nativeEvent.layout;
    setSize({ width, height });
  }, []);

  return [size, onLayout];
};

export default useComponentSize;

```

**Comment by lilyboyce** [comment]
Hi @vjsingh - thanks for this example! Where is the <View/> component coming from?

**Comment by vjsingh** [comment]
@lilyboyce I'm not sure what you mean? It's just a regular react-native View.

**Comment by Charlicus** [comment]
Example using [react-use-dimensions](https://www.npmjs.com/package/react-use-dimensions) hook if it can help anyone => [CodeSandbox](https://codesandbox.io/s/eager-visvesvaraya-0fyqu?fontsize=14&hidenavigation=1&theme=dark)

<svg> parameters are important to make it responsive, thanks @jasonhealy  !

**Comment by nicekiwi** [comment]
@lilyboyce @vjsingh the `View` component is specific to ReactNative, not React on the Web.

**Comment by rohandayal** [comment]
> Example using [react-use-dimensions](https://www.npmjs.com/package/react-use-dimensions) hook if it can help anyone => [CodeSandbox](https://codesandbox.io/s/eager-visvesvaraya-0fyqu?fontsize=14&hidenavigation=1&theme=dark)
> 
> parameters are important to make it responsive, thanks @jasonhealy !

Thanks @Charlicus - this helped! However, I'm not able to use axes with this approach. Any axes added render as default axes. Tried putting a &lt;g&gt; around the VictoryLine and VictoryAxis as suggested in the official docs, but that doesn't seem to work either. Have modified your CodeSandbox with an axis, and it renders as the default one. New [sandbox](https://codesandbox.io/s/victorycharttest-hqxhf)

**Comment by Charlicus** [comment]
@rohandayal, I don't have an example with axis sorry...

**Comment by rohandayal** [comment]
> @rohandayal, I don't have an example with axis sorry...

Sure. Let me try and figure out a solution (and update here for anyone else facing) :)

**Comment by denniske** [comment]
@rohandayal For me rendering chart with axis works using react-use-dimensions hook. But I do not use svg container but <VictoryChart> container.

**Comment by ymoon715** [comment]
I think this should be built in for complete responsiveness of the chart. I had to look around so much for a solution without using refs and detecting width of the container and setting state. setting padding to match the container makes the chart leak out of the parent container

**Comment by barco1997** [comment]
There is another solution with the use of dynamic refs, here is the example:
`
import React, { FC, useCallback, useState } from 'react';
import { VictoryArea, VictoryAxis, VictoryChart, VictoryGroup } from 'victory';
import { getRequiredDateFormat } from '../../utils/date/date-format';

export interface GraphProps {
  data: any;
  limits: any;
}

export const VictoryAreaGraph: FC<GraphProps> = ({ data, limits }) => {
  const [boundingRect, setBoundingRect] = useState({ width: 0, height: 0 });
  const graphRef = useCallback((node) => {
    if (node !== null) {
      setBoundingRect(node.getBoundingClientRect());
    }
  }, []);

  return (
    <div style={{ width: '100%', height: '100%' }} ref={graphRef}>
      <VictoryChart height={354} width={boundingRect.width}>
        <VictoryGroup
          style={{
            data: { strokeWidth: 3, fillOpacity: 0.4 },
          }}
        >
          <VictoryArea
            style={{
              data: { fill: data.color, stroke: data.color },
            }}
            data={data.data}
          />
        </VictoryGroup>
        <VictoryAxis
          dependentAxis
          domain={[limits.y.min, limits.y.max]}
          offsetX={50}
          orientation={'left'}
          standalone={false}
        />
        <VictoryAxis
          scale={'time'}
          standalone={false}
          offsetY={50}
          tickCount={4}
          tickFormat={(values) => getRequiredDateFormat(values, 'MMMM DD')}
        />
      </VictoryChart>
    </div>
  );
};
`

**Comment by christopherhill** [comment]
Since I'm using the zoom container, @barco1997's solution was the only one that worked. Thanks!

**Comment by chriszrc** [comment]
> There is another solution with the use of dynamic refs, here is the example:
> 
> ```
> import React, { FC, useCallback, useState } from 'react';
> import { VictoryArea, VictoryAxis, VictoryChart, VictoryGroup } from 'victory';
> import { getRequiredDateFormat } from '../../utils/date/date-format';
> 
> export interface GraphProps {
>   data: any;
>   limits: any;
> }
> 
> export const VictoryAreaGraph: FC<GraphProps> = ({ data, limits }) => {
>   const [boundingRect, setBoundingRect] = useState({ width: 0, height: 0 });
>   const graphRef = useCallback((node) => {
>     if (node !== null) {
>       setBoundingRect(node.getBoundingClientRect());
>     }
>   }, []);
> 
>   return (
>     <div style={{ width: '100%', height: '100%' }} ref={graphRef}>
>       <VictoryChart height={354} width={boundingRect.width}>
>         <VictoryGroup
>           style={{
>             data: { strokeWidth: 3, fillOpacity: 0.4 },
>           }}
>         >
>           <VictoryArea
>             style={{
>               data: { fill: data.color, stroke: data.color },
>             }}
>             data={data.data}
>           />
>         </VictoryGroup>
>         <VictoryAxis
>           dependentAxis
>           domain={[limits.y.min, limits.y.max]}
>           offsetX={50}
>           orientation={'left'}
>           standalone={false}
>         />
>         <VictoryAxis
>           scale={'time'}
>           standalone={false}
>           offsetY={50}
>           tickCount={4}
>           tickFormat={(values) => getRequiredDateFormat(values, 'MMMM DD')}
>         />
>       </VictoryChart>
>     </div>
>   );
> };
> ```

@boygirl This really should be built in, or documented in some way, a real footgun for first time users-

**Comment by seanng** [comment]
> This is one way:
> 
> ```
> constructor(props) {
>     super(props);
> 
>     this.state = {
>       chartWidth: 0
>     }
>   }
> 
>   componentDidMount() {
>     this.setState({
>       chartWidth: window.innerWidth
>     });
>     window.addEventListener('resize', this.updateDimensions.bind(this));
>     // remove this on unmount 
>   }
> 
>   updateDimensions(event) {
>     this.setState({
>       chartWidth: event.target.innerWidth
>     }) 
>   }
> ```
> 
> In your render function:
> 
> ```
> <svg viewBox={"0 0" + " "+ this.state.chartWidth +" " + "350"}  preserveAspectRatio="none" width="100%">
>         <VictoryChart
>           domainPadding={{x: 40}}
>           standalone={false}
>           width={this.state.chartWidth}
>           height={350}
>           >
>          // Chart stuff 
>           </VictoryChart>
> </svg>
> ```
> 
> **2020 update:**
> 
> _If you are using this solution in 2020_ (not sure if victory have a built in solution now) and you are using react functions/hooks vs classes (which you should be); something like this would be a more modern approach...
> 
> ```
> const [width, setWidth] = useState(window.innerWidth)
> const updateWidth = (ev) => {
>   setWidth(ev.target.innerWidth)
> }
> 
> // useEffect replaces `componentDidMount` and others
> useEffect(() => {
>  window.addEventListener('resize', updateWidth)
> 
>  // Removes listener on unmount
>  return () => {
>      window.removeEventListener('resize', updateWidth)
>  }
> 
> },[])
> ```
> 
> ```
> Replace {this.state.chartWidth} with {width} in you render return
> ```

Thanks for this! Any idea how to integrate this with VictoryVoronoiContainer (which requires `standalone={true}`) ?

**Comment by gitdallas** [comment]
@seanng - from what i can tell: on the `updateWidth` you are using the `window` size, so after any resizing, this would only work properly if the chart takes up the full window width.
