### ISSUE TITLE
vertical VictoryLine are not displayed when using a time scale

### ISSUE THREAD

**Issue by williaster** [FormidableLabs/victory#397]
In most cases when you pass `<VictoryLine />` an x or y accessor function that always returns the same value (e.g., `() => 123`), the result is a vertical or horizontal line that properly span the entire y or x domain, respectively.

However this does not seem to work with a constant x date value.

non-date x and y accessors: [works](https://jsfiddle.net/boygirl/vmL93m1u/1/)
both x and y accessors are dates: [works](https://jsfiddle.net/vmL93m1u/5/)
y accessor is date: [works](https://jsfiddle.net/vmL93m1u/6/)
x accessor is date: [doesn't work](https://jsfiddle.net/vmL93m1u/3/)

**Comment by jefffriesen** [comment]
I have this same problem

**Comment by boygirl** [comment]
released in `victory-core@9.2.4`
