### ISSUE TITLE
Improve VictoryTransition

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#398]
- Clean up `onLoad` transition. Previously `onLoad` callback was causing unnecessary re-rendering. This has been solved with aggressive `shouldComponentUpdate` but the underlying issue has not been solved
- Running transitions should be canceled when new animations are requested (i.e. changing props)
- Transitions durations vs. global animation durations should make more sense. 
- clipWidth transitions don't look right. The clipWidth should never be smaller than the range except during `onLoad`

**Comment by boygirl** [comment]
related issue https://github.com/FormidableLabs/victory/issues/404

**Comment by kujon** [comment]
related as well https://github.com/FormidableLabs/victory/issues/409. there seems to be a fair share of things that went wrong w/ transitions in 0.13.0. I'll create test cases if I catch some more.
