### ISSUE TITLE
victory-area

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#40]

**Comment by knowbody** [comment]
@boygirl can you give more details on this, please

**Comment by boygirl** [comment]
This component should render something similar to what line renders, but filled in down to the axis. That part should pretty much be copy and paste from the line component, and then a little more logic to complete the path. The complicated part is figuring out _stacked_ areas.

**Comment by austinpray** [comment]
If you need more details:

![image](https://cloud.githubusercontent.com/assets/2192970/12178787/f6435988-b538-11e5-8aef-2fd3eff26dda.png)

The red should fill down to the very bottom instead of intersecting

**Comment by jakepusateri** [comment]
An example of a stacked area chart.
![image](https://cloud.githubusercontent.com/assets/2494130/12188057/949e2810-b566-11e5-8470-fcf51d668bd9.png)

**Comment by vansters-dev** [comment]
+1

**Comment by F21** [comment]
Just noticed that adding a `fill` style to `victory-line` doesn't really work, so would love to see this happen too!
