### ISSUE TITLE
Long labels on VictoryPie get cropped

### ISSUE THREAD

**Issue by wmill** [FormidableLabs/victory#400]
Example here https://codepen.io/wmil/pen/PGxALp

The width of the chart + labels isn't being calculated correctly, and long labels are bing placed partly outside the svg viewbox.

**Comment by boygirl** [comment]
@wmill sorry for the delay. `VictoryPie` isn't actually calculating a width / height for the chart. Instead default width, height, and padding props are provided by themes. You can alter the padding to give your labels a little more room and / or add line breaks for longer labels (just include a newline character, and `VictoryLabel` will break it into tspan for you)
