### ISSUE TITLE
Tooltip for multiple lines

### ISSUE THREAD

**Issue by alikhani** [FormidableLabs/victory#403]
I wanted to add tooltip for chart with multiple lines but the tooltip only works for one of the lines.
See example: https://jsfiddle.net/alikhani/kk1kftoq/

Desired outcome would be more like: https://jsfiddle.net/alikhani/5gajehzt/
I would also like it if VictoryVoronoiTooltip had a prop to make the overlay more rectangular which results in better experience in Line and Area-charts. When mouse moves vertically the tooltip jumps between points which is weird experience.

**Comment by boygirl** [comment]
I'm going to close this one as related to #342. I will capture the request for rectangular areas there too.
