### ISSUE TITLE
Better strategy for computing layouts

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#41]

**Comment by tptee** [comment]
To deal with different issues of sizing, overlap, and measurement, we're experimenting with different engines to drive the layout of Victory components. This will dramatically reduce the manual math involved in our current approach and allow for elegant solutions to edge cases like in https://github.com/FormidableLabs/victory-chart/issues/122 and https://github.com/FormidableLabs/victory-label/issues/35.

I'm running feasibility experiments on the following engines:
- Flexbox (https://github.com/facebook/css-layout)
- Autolayout (a tiny subset of http://ijzerenhein.github.io/autolayout.js without the VFL nonsense)

Initial experiments with Flexbox are promising, but the need for tons of container elements really clutters the JSX and hurts the "glanceability" of components.

Autolayout (or any constraint-based engine) seems helpful here, especially for avoiding collisions/overlaps and dealing with edge cases (i.e. "distribute these bars evenly _unless_ they are flush to the axis). The downside is that the API doesn't map quite as cleanly to React, but I think this a small hurdle.

**Comment by boygirl** [comment]
closing in favor of #225
