### ISSUE TITLE
Vertical Scale

### ISSUE THREAD

**Issue by firedev** [FormidableLabs/victory#412]
Hi,

Is there a way to make my chart to use the whole height? Here is what I get:

![](https://files.gitter.im/FormidableLabs/victory/GFwA/blob)

And is it possible to get rid of empty spaces between bars. Seems like it adds additional placeholder after each bar.

Thanks.

**Comment by boygirl** [comment]
@firedev `VictoryChart` should be setting a correct domain based on the data of its children. Can I see your code to help determine what's going wrong? 

In general, you can change how data fits in a chart by altering the domain prop on `VictoryChart`.

**Comment by boygirl** [comment]
@firedev I'm closing this for now. I'm happy to reopen it if more information is added.

**Comment by firedev** [comment]
Sorry for delay here it is:
```jsx
<VictoryChart
      width={1600}
      height={500}
      domainPadding={100}
    >
      <VictoryLine
        style={{ data: { stroke: blue } }}
        data={data.map((_, i) => ({ x: i + 1, y: reference }))}
      />
      <VictoryAxis tickValues={map(data, 'title')} />
      <VictoryAxis dependentAxis />
        <VictoryStack
          style={{
            data: { width: 100 },
          }}
        >
          {data.map(({ mastered, remedial, title }, i) =>
            <VictoryBar
              style={{ data: { fill: olive } }}
              data={[
                {x: i + 1, y: mastered},
              ]}
            />
          )}
          {data.map(({ mastered, remedial, title }, i) =>
            <VictoryBar
              style={{ data: { fill: yellow } }}
              data={[
                {x: i + 1, y: remedial},
              ]}
            />
          )}
        </VictoryStack>
    </VictoryChart>
```

**Comment by boygirl** [comment]
@firedev it looks like you're returning a `VictoryBar` component with just one data point for each element in your data array. I think some odd behavior is probably being caused by trying to calculate domains based on single data points.  Rather than plotting one point per each VictoryBar, try it might help to plot the whole series at once. You can access the fields you require with data accessor props like so:

```
<VictoryLine y={() => reference} />
<VictoryStack>
  <VictoryBar
    data={data}
    y="mastered"
  />
  <VictoryBar
    data={data}
    y="remedial"
  />
</VictoryStack>
```
Here's a little more on data accessors https://formidable.com/open-source/victory/docs/victory-bar/#x-and-y

**Comment by firedev** [comment]
Thank you for your suggestion @boygirl, however the graph looks exactly the same. Also tried with `[{ y: value }, ...]` and `[ value, ... ]`. I need `x+1` because of an issue with X axis — labels are shifted to the right, i.e. start from 1, not zero: `<VictoryAxis tickValues={map(data, 'title')} />`.

```
        <VictoryStack
          style={{
            data: { width: 100 },
          }}
        >
          <VictoryBar
            style={{ data: { fill: olive } }}
            data={
              data.map(({ mastered, remedial, title }, i) => ({ x: i + 1, y: mastered }))
            }
          />
          <VictoryBar
            style={{ data: { fill: yellow } }}
            data={
              data.map(({ mastered, remedial, title }, i) => ({ x: i + 1, y: remedial }))
            }
          />
        </VictoryStack>
```

**Comment by firedev** [comment]
Sorry @boygirl can we reopen this?

**Comment by firedev** [comment]
Okay somehow it got better after an update so I am closing it. Thanks.
