### ISSUE TITLE
Styling of VictoryChart

### ISSUE THREAD

**Issue by jbreckel** [FormidableLabs/victory#420]
Hey,

the `style.height` property of the `style.parent` is always set to [`'auto'`](https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-chart/victory-chart.js#L113).

Is this intended behavior?

Thanks

**Comment by boygirl** [comment]
@jbreckel yes, this is the intended behavior. Victory renders responsive container by default. You can read about how to alter this behavior here https://formidable.com/open-source/victory/guides/layout
