### ISSUE TITLE
Implement animationWhitelist more comprehensively

### ISSUE THREAD

**Issue by michaelbridge** [FormidableLabs/victory#425]
We use lots of conditional formatting in our app, see example below:

```
<VictoryBar
data={data}
animate={{duration: 500}} 
style={{ data: {fill: (d) => d.y < 0 ? "red" : "green"} }}
/>
```

With the current implementation, Victory attempts to tween the style prop, but fails because style is a function.  Ideally, we could pass in an array of strings to the animate prop as follows: animate={{duration: 500, animationWhitelist:["y"]}}.  Only whitelisted props would then be tweened.

**Comment by boygirl** [comment]
closing in favor of https://github.com/FormidableLabs/victory/issues/1186
