### ISSUE TITLE
domainPadding breaking with time scales

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#430]
Specifying domainPadding on VictoryChart works fine with time scales, but specifying directly on VictoryAxis breaks

**Comment by boygirl** [comment]
Also  Having animate={{ duration: 500, delay: 0 }} in the VictoryBar component messes up the domainPadding

 @excentrik

**Comment by excentrik** [comment]
I've made a JSfiddle which show the issue with the animate: https://jsfiddle.net/vxev7q5v/

**Comment by boygirl** [comment]
Fixed and released in `victory@0.14.0`
