### ISSUE TITLE
How to set custom domains per y axis inside VictoryGroup?

### ISSUE THREAD

**Issue by hampusohlsson** [FormidableLabs/victory#431]
Trying to create a chart with multiple y axes. Since I want to use `VictoryZoom`, I have to use the `VictoryGroup` child component (I guess?). However, that seems to merge all the custom domains I've specified for the `VictoryAxis` children, so all y axes get the same domain. **Is there any way of overriding this behaviour, setting custom domain per VictoryAxis?**

Now, if I remove `VictoryGroup` and just use a `<svg>` element to wrap it, it works - but I can't set the size of the chart anymore, it just defaults to 450w/300h.

If anyone has any tips or tricks up their sleeve to solve this, please share!

**Comment by imranolas** [comment]
I think I follow the issue but could you provide an example case?

**Comment by hampusohlsson** [comment]
Sure!

Using `<VictoryGroup />` https://jsfiddle.net/bvy65hLx/
- Custom y-axis domains and axis styles **doesn't work**
- Could not get it to work with VictoryZoom either

Using `<svg />` https://jsfiddle.net/f8hwab9x/
- Custom y-axis domains and axis styles works
- Not sure how to properly set width/height
- VictoryZoom child requirements not fulfilled

**Comment by imranolas** [comment]
Ok got it.

VictoryGroup is designed such that it reconciles domains for all its children. In your case, even though you are specifying a custom domain for the child axes, VictoryGroup overloads this with its calculated domains. We actually rely on this feature to make zoom work but sadly it does make this case harder to deal with.

We could extend VictoryZoom to allow rendering within an svg. Only zoomable components would need to be rendered inside zoom. ie. data components and x axis, whereas y axes could be rendered directly within the svg. I think that would probably solve this case.

```jsx
<svg>
  <VictoryAxis dependentAxis />
  <VictoryZoom>
    <VictoryGroup>
      <VictoryLine /> 
      <VictoryAxis />      
    </VictoryGroup>
  </VictoryZoom>
</svg>
```

**Comment by hampusohlsson** [comment]
Hey @boygirl, what is the status since you closed the issue? wontfix / fixed?

**Comment by boygirl** [comment]
@hampusohlsson This is a wontfix. Reconciling domains is a major part of what `VictoryGroup` does. 

> Now, if I remove VictoryGroup and just use a <svg> element to wrap it, it works - but I can't set the size of the chart anymore, it just defaults to 450w/300h.

You can get around this problem by setting your own width and height rather than relying on the defaults. These guides might be helpful: 

http://formidable.com/open-source/victory/guides/layout
http://formidable.com/open-source/victory/guides/custom-charts

**Comment by gavrilenco** [comment]
@hampusohlsson @boygirl Could you take a look please? https://github.com/FormidableLabs/victory/issues/772

**Comment by gajendraprajapati** [comment]
@boygirl is there any way to use victoryGroup with custom domains for each y axis ?
