### ISSUE TITLE
Selecting data in charts

### ISSUE THREAD

**Issue by garysieling** [FormidableLabs/victory#432]
It would be nice if there was a way to select regions in charts (D3 calls this "brushes"). I have a simple application that uses D3, but at some point I would prefer to switch to a React based charting library.

**Comment by boygirl** [comment]
In progress: point selection via regions. next: zoom via regions

**Comment by boygirl** [comment]
Point selection via rectangular regions is released in 0.15.0. brush zoom expected by the end of the month. I'm closing this in favor of https://github.com/FormidableLabs/victory/issues/465

**Comment by garysieling** [comment]
Awesome, thanks!
