### ISSUE TITLE
ImmutableJS lists don't work as data

### ISSUE THREAD

**Issue by AugustinLF** [FormidableLabs/victory#433]
Passing an Immutable List to a VictoryScatter (and I guess to other type of charts) doesn't work. Do you think it would make sense to support them?

They natively work with React when used as children, so far, I rarely had to convert them to plain JS arrays to make them work with other libraries, since they are "just" iterables. But there'll be some issues, for instance, `.length` is `undefined` on a List, and `VictoryCore.data.getData` explicitely checks it.

If you're interested, I'd be willing to give it a try and submit a PR.

**Comment by Zerim** [comment]
I had the same thought. Seems like best design would be to support any data type that implements the iterable protocol: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

This would support Immutable.js as well as other use cases.

**Comment by corradio** [comment]
Any news here? This would be terrific!

**Comment by boygirl** [comment]
support for immutable data added in `victory@0.24.4`
