### ISSUE TITLE
mobile-web / touch support for Containers (Zoom, Cursor, Selection, Brush, Voronoi)

### ISSUE THREAD

**Issue by coreylight** [FormidableLabs/victory#434]
When I visit this page:
http://formidable.com/open-source/victory/guides/pan-and-zoom
I cannot seem to pan or zoom using touch controls.
Device info:
http://www.whatsmybrowser.org/b/VT4MJUZ

**Comment by imranolas** [comment]
I believe RN support is due to land very soon and touch for web will follow shortly after.

**Comment by sontek** [comment]
Whats the plan for touch?  Are you just going to use the synthetic events from:

https://facebook.github.io/react/docs/events.html#touch-events

Or something a little better like:

https://github.com/JedWatson/react-hammerjs

**Comment by laurencedorman** [comment]
Any updates on this?

**Comment by chrisbolin** [comment]
this is still an issue with the new containers. we may want to prioritize it.

**Comment by chrisbolin** [comment]
(I updated issue title to reflect that)

**Comment by boygirl** [comment]
released in `victory@0.21.4`

**Comment by Fischaela** [comment]
@boygirl Should this work out of the box? I updated to `victory@0.21.4` but pan and zoom, and also tooltips on touch don't work on iOS

**Comment by boygirl** [comment]
@Fischaela these should just work, though the implementation is a bit naive. Just aliases `onMouseOver` -> `onTouchStart` and `onMouseOut` -> `onTouchEnd` etc. There isn't specific pinch zoom logic in place, but scrolling gestures should work for zooming. I'll triple check on tooltips.

**Comment by toddmedema** [comment]
So, I'm trying the demo graphs on https://formidable.com/open-source/victory/guides/brush-and-zoom/ and it seems like panning works on mobile (Android 10, Chrome), but pinch to zoom does not. Am I missing something, or is that capability not available? Would it be possible to add it?
