### ISSUE TITLE
Cryptic repetitive warning ⚠️: "`renderInPortal` is not supported outside of `VictoryContainer`. Component will be rendered in place"

### ISSUE THREAD

**Issue by samkelleher** [FormidableLabs/victory#435]
Add the `standalone={false}` to a `<VictoryChart />` and the console comes to live logging the warning:

> \`renderInPortal\` is not supported outside of \`VictoryContainer\`. Component will be rendered in place

Unsure what it means or what to do to eliminate it. The graph still renders normally. The container is not being overwritten anywhere.  Error comes from the `componentDidMount` of `VictoryPortal`.

Tried to force a VictoryContainer as the first child of the VictoryChart without success. I have a scatter with label, and the warning comes up each time a 'point' is rendered, which would explain why so many of these logs warnings come up.

**Comment by jamieparkinson** [comment]
I had this same issue and was able to resolve it by setting `renderInPortal={false}` on the tooltip components, ie:
```
labelComponent={<VictoryTooltip ...stuff...
                                renderInPortal={false}/>}
```
This is actually documented - https://formidable.com/open-source/victory/docs/victory-tooltip/#renderinportal - but I would agree that it should probably be documented more clearly or the requirement to set `renderInPortal={false}` manually should be removed.
