### ISSUE TITLE
VictoryChart title

### ISSUE THREAD

**Issue by krzesio** [FormidableLabs/victory#436]
Hey, it would be really great to provide simple VictoryChartTitle component (or VictoryChart property) that would allow devs to set chart title centered relatively to chart area (excluding axises and their labels). Of course it would need some styling properties (fill, stroke, fontSize, textAlign).

**Comment by boygirl** [comment]
This is best accomplished by adding a `VictoryLabel` child to `VictoryChart` This solution provides the most flexibility without expanding the api surface.

**Comment by bhargav11-crest** [comment]
can you share an example with code? It will be very useful. thanks.

**Comment by aSlade** [comment]
I used VictoryLegend to get a title for my chart
