### ISSUE TITLE
Is there a way to add HTML tooltips?

### ISSUE THREAD

**Issue by kumarharsh** [FormidableLabs/victory#445]
Hello, I'm rather new to Victory, but have been using d3 for quite some time. The library seems very good and easy to use. In my usecase, I've found that using an SVG for rendering tooltip data is limiting, as I need to render my own react components in the tooltip. Is there a way to add HTML tooltips to Victory charts?

**Comment by kumarharsh** [comment]
Additionally, I'm not able to add a `labelComponent` on the `VictoryVoronoiTooltip`:

```js
<VictoryVoronoiTooltip
  labels={d => d.x}  /* <- works */
  // labelComponent={<VictoryTooltip />}  /* <- doesn't work */
  // labelComponent={<VictoryTooltip flyoutComponent={<MyFlyout />} />}  /* <- doesn't work */
/>
```

**Comment by AugustinLF** [comment]
You can always use foreignElements in your svg:
```jsx
<g transform={`translate(${x - 25}, ${y - 25})`}>
            <foreignObject
                width={50}
                height={50}
            >
                <div />
            </foreignObject>
</g>
```

But be careful, foreignElements have a lot of problems with stuff like transform, absolute positioning.

**Comment by kumarharsh** [comment]
@AugustinLF thanks. That's just what I was looking for! Now just if the `VictoryVoronoiTooltip` actually rendered the tooltip I'm giving it... 😢

**Comment by boygirl** [comment]
@kumarharsh I'm not able to reproduce the issue you're seeing with `VictoryVoronoiTooltip` Check out this fiddle https://jsfiddle.net/boygirl/8e7zucLd/

Can I see more of your code?

**Comment by kumarharsh** [comment]
@boygirl thanks for the reference issue. Here's my try:

https://jsfiddle.net/ftLb71t9/1/

Some of my needs are:
1. Each data-point has associated information about the player, which I'd like to display in the tooltip.
2. The tooltip will have images, custom react components, etc. so I need to be able to use HTML rather than svg.  This is taken care of by the foreignObject tag.
2. I have a scatter-graph, so I think the voronoi tooltip will be very useful.

What I don't get from the documentation:
1, The [VoronoiTooltip](https://formidable.com/open-source/victory/docs/victory-voronoi-tooltip) docs say that it *behaves* identically to `Voronoi`, expect for `labelComponent` being `ToolTip`. And since Tooltip accepts the `flyoutComponent` prop, shouldn't that work too?
2. I don't understand what the `labels` prop really does for VictoryVoronoiTooltip. If it only supplies the text for the tooltip, I don't think it's useful in my case, as I need the whole datum. Also, passing `labels={d => d}` throws a bunch of errors in the console. *I realise I must be doing this wrong, but can't find any reference of what should be done here instead*.

**Comment by boygirl** [comment]
@kumarharsh sorry the docs are light on this. There are a couple things going on...

1) if there isn't any label for a given element (either via the` labels` prop, or as a label property directly on the data object) no tooltip will be rendered for that element. This is to cut down on svg nodes.

2) `VictoryTooltip` expects the label text to be a string, which is why you're getting errors with the with `labels={d => d}` as it's returning the whole data object instead. You will have access to the data object via the `datum` prop that gets passed to `VictoryTooltip`

For the example you're showing, I think you actually want to be altering the label rather than the flyout, as that is what has access to the datum (though, after seeing how you'd like to customize tooltips, I can definitely be convinced to pass the datum to the flyout component as well)
Check out my modification of your example https://jsfiddle.net/boygirl/z24cs26g/

**Comment by boygirl** [comment]
@kumarharsh here's another modification of your example that might be a little more helpful

https://jsfiddle.net/boygirl/y0o17oqc/

**Comment by kumarharsh** [comment]
@boygirl super! Thanks for all the help 😃

**Comment by kumarharsh** [comment]
Also, for future reference, it seems that the `foreignObject` requires an explicit width/height to be set, without which is just renders a 0x0 box regardless of what the content inside the div is.

**Comment by kumarharsh** [comment]
And the `tooltip` element rendered should have a `pointerEvents: none`, otherwise it causes flickering when the mouse falls in the area of the tooltip

**Comment by EzraM** [comment]
The most recent jsfiddle 404's. Can that be resurrected? Sounds helpful for our case.
Much appreciated!

**Comment by erikreppen** [comment]
Conclusion: Totally not worth the effort. You have very little control of the HTML that doesn't just kill it when you finally do get this working. Just work with the SVG. I'm going to make a feature request for an HTML tooltip in an HTML container around the SVG element.

**Comment by bpb27** [comment]
This thread was very helpful in finally figuring this out. Took a while, but here it is:

**Custom tooltip component:**
```
import React from 'react';
import PropTypes from 'prop-types';

export class GraphTooltip extends React.Component {

  static propTypes = {
    x: PropTypes.number,
    y: PropTypes.number,
    orientation: PropTypes.string,
    datum: PropTypes.object
  };

  render () {
    const { datum, x, y } = this.props;
    return (
      <g style={{pointerEvents: 'none'}}>
        <foreignObject x={x} y={y} width="150" height="100">
          <div className="graph-tooltip">
            <span>{ datum.points_scored }</span>
          </div>
        </foreignObject>
      </g>
    );
  }
}

export default GraphTooltip;

```

**And it's invocation:**

```
<VictoryArea
  labels={() => ''}
  labelComponent={ <VictoryTooltip flyoutComponent={<GraphTooltip/>}/> }
/>
```

**NB:**
- You still need the labels attribute (just use a blank function)
- No pointer events to prevent flickering
- Foreign object to wrap HTML
- Foreign object can take x and y coordinates
- Foreign object needs height and width
- Access the actual data from the graph with the datum prop (automatically passed in)

Suerte and godspeed.

**Comment by boygirl** [comment]
@bpb27 Thanks for writing up a detailed solution. I'm making a note to capture this in the docs 
https://github.com/FormidableLabs/victory-docs/issues/380

**Comment by lgerndt** [comment]
@bpb27 thanks for supplying code on how to write an HTML tooltip, this should have been in the docs if you ask me.  Anyway, it works, but I'm still seeing a non-styled label along with my HTML label on hover.  I've added the labels={() => ''}, so that's not the cause.  Any idea?

**Comment by janbaykara** [comment]
I mean, you could also calculate the x/y positions of the data in relation to the svg parent, in relation to `window`, and render an absolutely positioned tooltip.

**Comment by chriszrc** [comment]
Here's what the typescript version looks like, and if all you want to do is customize the content of the flyout, you can actually keep using the default flyout and just overlay the content:

```typescript
import {Flyout, FlyoutProps} from 'victory';
import {ColoredLabels} from './colored-labels';
import {StackedBarChartData} from '../stacked-bar-chart';

export interface HtmlFlyoutProps extends FlyoutProps {
  chartData: StackedBarChartData;
  colorScale: string[];
}

export function HtmlFlyout(props: HtmlFlyoutProps) {
  const {chartData, colorScale = [], ...rest} = props;
  const {center = {x: 0, y: 0}, datum, height = 0, width = 0} = props;

  return (
    <g style={{pointerEvents: 'none'}}>
      <Flyout {...rest} height={(rest.height || 0) + 10} />
      <foreignObject
        x={center.x - width / 2}
        y={center.y - height / 2}
        width={width}
        height={height}
      >
        <div style={{padding: '0px 0 0 10px'}}>
          <ColoredLabels
            colorScale={colorScale}
            chartData={chartData}
            datum={datum}
            index={props.index || 0}
          />
        </div>
      </foreignObject>
    </g>
  );
}
```

and using it:

```
labelComponent={
    <VictoryTooltip
      //NOTE force show the tooltip for debugging
      // active={true}
      constrainToVisibleArea
      flyoutComponent={
        <HtmlFlyout colorScale={[...chartColors].reverse()} chartData={data} />
      }
      //NOTE the HtmlFlyout still uses the VictoryFlyout component, but flyout padding is calculated here,
      // so even with our custom flyout, we still need to pass the padding to the VictoryFlyout component :(
      flyoutPadding={{top: 10, bottom: 10, left: 30, right: 30}}
       style={{
         visibility: 'hidden'
       }}
    />
  }
```
