### ISSUE TITLE
Add pointerEvents: 'none' to Flyout labels for VictoryVoronoiTooltip by default

### ISSUE THREAD

**Issue by MrNice** [FormidableLabs/victory#446]
Currently, when you mouse over a VictoryVoronoiTooltip's flyout, it flickers rapidly as it consumes a mouse event, disappears, then reappears.

This can be fixed by setting:
```jsx
<VictoryVoronoiTooltip
  style={{
    labels: { pointerEvents: 'none' },
    flyout: { pointerEvents: 'none' },
  }}
/>
```

With the caveat that you can no longer click on or interact with the flyouts in advanced use cases.

## And So:
Does it make sense to make this part of the default styles, or
Should it be added to the tooltip guide, perhaps near this chart:
![screen shot 2016-12-09 at 11 09 30 am](https://cloud.githubusercontent.com/assets/2587335/21061155/006c3882-be00-11e6-8841-9ed855c3b64f.png)

It took me a bit to figure out how to eliminate the flickering, and I'd like others to not have to expend the effort.

**Comment by boygirl** [comment]
@MrNice thanks! I will add this style to the default theme for tooltip flyouts / labels.
