### ISSUE TITLE
VictoryZoom doesn't handle time or date scale

### ISSUE THREAD

**Issue by ejwright** [FormidableLabs/victory#447]
When using the VictoryZoom on a chart that has a time scale and is provided x-axis data points as Date objects, the zoom function fails to work and generates a NaN error

**Comment by contra** [comment]
It also doesn't render labels for dates (+ no time-based examples) so I'm guessing time-series graphs aren't a big priority for this project - I would love to see that change though.

**Comment by boygirl** [comment]
Sorry for this oversight. I'll get a fix out today.

**Comment by contra** [comment]
@boygirl Thanks for the quick response! 🌴
