### ISSUE TITLE
VictoryChart padding prop and expectations

### ISSUE THREAD

**Issue by REEMERGEMEDIA** [FormidableLabs/victory#448]
The documentation for the VictoryChart padding property states you can pass a single value or an object with top|bottom|left|right values. When I pass an object of just { top: 0 }, that value is used also for bottom|left|right. My expectation, based on the documentation, would be that the explicitly stated value of 0 would be used for 'top', and the default value of 50 would be used for bottom|left|right

**Comment by boygirl** [comment]
@REEMERGEMEDIA This is the expected behavior. I'll make the docs more explicit. Sorry for the confusion!
