### ISSUE TITLE
Animation for VictoryLine does not work as expected.

### ISSUE THREAD

**Issue by Zerim** [FormidableLabs/victory#452]
See this [fiddle](https://jsfiddle.net/3L93qwLm/).

When setting a value for the `animate` prop on a simple chart using VictoryLine, the line does not finish rendering all the way, and the console produces hundreds of `react.js:1768 Error: <rect> attribute x: Expected length, "NaN".` errors.

**Comment by boygirl** [comment]
@Zerim I'm seeing the issue in your fiddle, but I'm unable to reproduce it locally. Are you also seeing this problem via npm installed victory?

**Comment by boygirl** [comment]
@Zerim https://github.com/FormidableLabs/victory-core/pull/178 will at least guard against the errors you're seeing.
