### ISSUE TITLE
Inconsistent usage of 'Element', 'Component' and 'Component Instance'.

### ISSUE THREAD

**Issue by Zerim** [FormidableLabs/victory#453]
This may be a nitpicky semantics issue, but there are many props which are called `dataComponent`, `groupComponent`, etc. and in their documentation it is said that they accept a "component instance."

In reality all these props expect React Elements. See [here](https://facebook.github.io/react/blog/2015/12/18/react-components-elements-and-instances.html) for the disambiguation.

Probably not worth making a breaking change to the API just to resolve this, but might be worth updating documentation to be more clear... Or maybe not, like I said it's nitpicky, but was a bit confusing to me at first :)

**Comment by boygirl** [comment]
@Zerim I'll move this issue to the docs repo.
