### ISSUE TITLE
VictoryVoronoiTooltip should render itself inside of VictoryPortal component.

### ISSUE THREAD

**Issue by Zerim** [FormidableLabs/victory#454]
I came across this issue while implementing my own custom tooltip (some of my other learnings described in https://github.com/FormidableLabs/victory/issues/373).

When using a VictoryVoronoi to listen to mouse events I was getting superfluous mouseEnter and mouseLeave events which were causing glitchy looking flickering in my tooltip. Examples 4 and 5 in the 'Tooltips' guide in the docs suffer from this same problem. I've recreated example 5 [here](https://jsfiddle.net/1de7m0h8/) for convenience. If you move the mouse below the x=3 or x=6 data points, you should be able to see the flickering.

The issue is that the tooltip is being rendered at the top level inside of a VictoryPortal, and so when the mouse moves over the tooltip, the VictoryVoronoi sees a mouseLeave event, which causes the VictoryTooltip to dissapear, which causes a mouseEnter event on the VictoryVoronoi, etc. etc.

The solution is to make the VictoryVoronoi transparent and place it at the top-most level as shown [here](https://jsfiddle.net/1fkea5xh/). Note that the flickering is gone.

Happy to put together a quick PR if you agree with this approach. Cheers.

**Comment by boygirl** [comment]
@Zerim I think the way I'd prefer to do this would be with a `renderInPortal` prop on `VictoryVoronoi` and `VictoryVoronoiTooltip` as already exists in `VictoryTooltip`

**Comment by Zerim** [comment]
@boygirl Make sense to me. And then have that prop set to `true` by default for VictoryVoronoiTooltip?

**Comment by boygirl** [comment]
@Zerim yep, exactly!
