### ISSUE TITLE
Possible to "drive" charts externally by triggering events?

### ISSUE THREAD

**Issue by philipkobernik** [FormidableLabs/victory#455]
Hi @boygirl et al!

Myself and coworkers are loving Victory and finding it a joy to develop with. Thanks for all your efforts.

Curious about how you might approach a problem:

Assuming LineChart is a component that renders a group of line/scatter/voronoi visualizing a time-series such that hovering over the chart highlights the datapoint by mutating strokeWidth or something like that....

If we have 

<LineChart data={set1} >
<LineChart data={set2} >
<LineChart data={set3} >

We'd like to hover over one chart, and highlight that same year in the other charts.

Any thoughts? Perusing the docs, I don't see anything about triggering custom events on the charts...

Thanks,
Philip

**Comment by boygirl** [comment]
@philipkobernik I think you want to use the `VictorySharedEvents` wrapper. You can see an example in this guide: https://github.com/FormidableLabs/victory/issues/453

Hit me up in the gitter channel if you have any trouble getting it to do what you need.
