### ISSUE TITLE
The 'active' prop in the VictoryToolTips section is confusing.

### ISSUE THREAD

**Issue by brianzhou13** [FormidableLabs/victory#456]
Not 100% certain this is an issue, but in the 'active' props section in the VictoryToolTips documentation, there is some leftover text that I'm not certain should be there.

The section ([link](http://formidable.com/open-source/victory/docs/victory-tooltip/#active))  says:
--

active
The active prop specifies whether the tooltip component should be displayed.
examples: text={(datum) => "x: " + datum.x}, text="Apples\n(green)"

--

The 'examples...' part doesn't seem to use the prop 'active' anywhere.

Was this example accidentally carried over from the 'text' section, which is directly above it?

Thanks!

**Comment by brianzhou13** [comment]
by the way, awesome job! I look forward to continual usage of what you've guys built here. :)

**Comment by boygirl** [comment]
@brianzhou13 Thanks! You're right I need to take that out. I'll open an issue in the docs repo instead
