### ISSUE TITLE
Support missing data points

### ISSUE THREAD

**Issue by lapidus** [FormidableLabs/victory#457]
Would be great if VictoryLine supported missing data points "out of the box". Example dataset:
`[ { x: 1, y: 1 }, { x: 2, y: null }, { x: 3, y: 3 } ]`

In "Highcharts" this would typically render a default two lines with a gap:
http://jsfiddle.net/8qfrq0nw/

![image](https://cloud.githubusercontent.com/assets/66601/21311908/e532f384-c5e9-11e6-9155-adf4f5fadb18.png)

Using d3.line.defined this could perhaps be supported by adding a simple property 'defined'?
https://github.com/d3/d3-shape/blob/master/README.md#line_defined

Alternatively one could supply some styling for the 'gap filled/interpolated' values.

**Comment by boygirl** [comment]
@lapidus VictoryLine already supports null data as you describe. Check out this fiddle https://jsfiddle.net/boygirl/yo6xnc5s/

**Comment by Kobzol** [comment]
Could you please link to some documentation how to enable the data gaps? The fiddle link is dead.

**Comment by bewildergeist** [comment]
@Kobzol Late to the party, I know — but this requires no configuration, a data set that includes `null` values as in @lapidus' original example will create gaps in the line (i.e. a data point that has a valid `x` property but `y: null`).
