### ISSUE TITLE
Functional styles / props are not evaluated properly for entering elements

### ISSUE THREAD

**Issue by chriswhong** [FormidableLabs/victory#460]
![victorybar](https://cloud.githubusercontent.com/assets/1833820/21429402/8f3e317e-c82c-11e6-8b12-5fa2087841f4.gif)
I added `animate` to my `VictoryBar`, and am updating it with a new data based on a filtering UI.  The user can eliminate an entire category from their filtering.  When this happens, I am observing the following issues:

1) The dynamically assigned colors do not get applied.  (If I assigned yellow to the first category, and then eliminate that category from the data, the first bar remains yellow even though it now represents a different category...  basically the bar's size is updating, but not it's style.

2) If I then change the filters and add the category that was removed, a black bar appears in the last position (farthest right), and again the dynamic colors are not applied properly.  

Any assistance is much appreciated!  Thanks for a great package.

**Comment by chriswhong** [comment]
Also, the numbers show many decimals when animating... how can I fix that?  I tried adding converting to strings but it didn't help.

**Comment by chriswhong** [comment]
This is probably the same issue as https://github.com/FormidableLabs/victory/issues/374

**Comment by boygirl** [comment]
@chriswhong I'm going to update the title of this issue. Animating with different number of points works _except_ when functional styles are used to color the animating points. 

_i.e._ this works: 

```
<VictoryChart style={chartStyle} animate={{ duration: 1500 }}>
  <VictoryBar
    style={{data: {fill: "tomato"}}}
    data={this.state.barTransitionData}
  />
</VictoryChart>
```
but this doesn't
```
<VictoryChart style={chartStyle} animate={{ duration: 1500 }}>
  <VictoryBar
    style={{data: {fill: (d) => d.x % 2 === 0 ? "blue" : "tomato"}}}
    data={this.state.barTransitionData}
  />
</VictoryChart>
```

**Comment by boygirl** [comment]
as for the numbers, something like `labels={(d) => parseInt(d.y, 10)}` will prevent that issue
