### ISSUE TITLE
make only one axis line visible

### ISSUE THREAD

**Issue by omryr** [FormidableLabs/victory#461]
hi i am new to using victory library, and so far it has been awesome, im looking for a way to use a theme on a victorychart and make it so that only the X axis line is visible while the Y axis only shows the labels, is the library supporting such action through the use of theme?

this is my current theme : 
 theme: {
        chart: baseProps,
        axis: {
            style: {
                axis: {
                    fill: 'transparent',
                    stroke: 'transparent'
                },

                grid: {

                    fill: 'transparent',
                    stroke: 'transparent'
                },
                ticks: {
                    fill: 'transparent'
                },
                tickLabels: {
                    fill: vg.colors.white,
                    stroke: 'transparent',
                    fontSize: 8,
                    padding: 2
                },
                axisLabel: {
                    fontFamily: sansSerif
                }
            }
        },
        line: {
            style: {
                data: {
                    fill: vg.colors.white,
                    opacity: 1,
                    stroke: vg.colors.white,
                    strokeWidth: 2,
                    interpolation: 'radial'
                }
            }
        },
        tooltip: {
            style: {
                data: {
                    fill: 'transparent',
                    stroke: 'transparent',
                    strokeWidth: 0
                },
                labels: {
                    fill: vg.colors.white,
                    pointerEvents: 'none',
                    fontSize: 8
                },
                flyout: {
                    stroke: 'transparent',
                    strokeWidth: 0,
                    fill: vg.colors.greyishBrown,
                    pointerEvents: 'none'
                }
            },
            flyoutProps: {
                cornerRadius: 2,
                pointerLength: 10
            }
        }
    },

appericiate any help you may provide!

**Comment by boygirl** [comment]
@omryr you can differentiate between axes in themes using `dependentAxis` and `independentAxis` namespaces. Any styles / props defined in these namespaces will be merged with styles / props defined on the `axis` namespace.

**Comment by itelo** [comment]
any example?

**Comment by anuj-nickelfox** [comment]
Hi, I was stuck in the same issue.
Here is how I fixed it:

In the theme file, like grayscale.js inside node_modules, edit it and add the dependentAxis object like so

  axis: _assign({
    style: {
      axis: {
        fill: "transparent",
        stroke: charcoal,
        strokeWidth: 1,
        strokeLinecap: strokeLinecap,
        strokeLinejoin: strokeLinejoin
      },
      axisLabel: _assign({}, centeredLabelStyles, {
        padding: 25
      }),
      grid: {
        fill: "none",
        stroke: "none",
        pointerEvents: "painted"
      },
      ticks: {
        fill: "transparent",
        size: 1,
        stroke: "transparent"
      },
      tickLabels: baseLabelStyles
    }
  }, baseProps),
  dependentAxis: _assign({
    style: {
      grid: {
        fill: "none",
        stroke: "#E5E4E4",
        pointerEvents: "painted"
      },
    }
  }, baseProps),
  bar: _assign({
    style: {
      data: {
        fill: charcoal,
        padding: 8,
        strokeWidth: 0
      },
      labels: baseLabelStyles
    }
  }, baseProps),

This will apply stroke only on the required axis. You can also refactor it into a theme object and pass it to theme prop of component

Reference: https://formidable.com/open-source/victory/docs/victory-theme/
