### ISSUE TITLE
safari doesnt work as intended

### ISSUE THREAD

**Issue by omryr** [FormidableLabs/victory#467]
hi I implemented a chart in my website, it works perfectly in chrome and firefox but for some reason in safari it wont take up all the space, it sort of centers and keeps the ratio but much smaller than the other browsers.. i put it inside a div that is full screen length and the chart is taking up maybe 50% of the space in the center of the div instead of stretching, anyone encountered that behavior?

**Comment by imdpk** [comment]
+ 1

**Comment by anas10** [comment]
Same here I was using victory 0.9.0 and it was working on all browsers. Then when updating to the latest release I started having this issue as well.

**Comment by brotzky** [comment]
I've run into this issue as well. None of my graphs are loading correctly in Safari.

```
Error: Problem parsing d="M NaN, 85.875 m -5, 0
      a 5, 5 0 1,0 10,0
      a 5, 5 0 1,0 -10,0"
```

```
Error: Problem parsing d="M NaN, 88.8377723970944 m -4, 0
      a 4, 4 0 1,0 8,0
      a 4, 4 0 1,0 -8,0"
```

**Comment by brotzky** [comment]
I think my issue can be solved by this stackoverflow bug. It may not be related to Victory:

http://stackoverflow.com/a/25284429/3845614

I am indeed passing ("2012-03-20") in new Date().
