### ISSUE TITLE
VictoryAxis.tickValues does not allow text -> text overrides

### ISSUE THREAD

**Issue by cpnielsen** [FormidableLabs/victory#468]
I was following the getting started tutorial, and if you supply textual values for the X axis (like the "employee" example), it is not possible to provide a set of text tickValues - if so, nothing is rendered.

Is this intended?

In my case, the data I use has a GUID as the X axis value, but I have a way of calculating a better "human-readable" label and wanted to provide that through `tickValues` (rather than alter the incoming data).

**Comment by billcreative** [comment]
I'm not sure why tickValues aren't working but another way to get better tick labels is to use tickFormat. Use an array:

`tickFormat={["One", "Two", "Three"]}`

Or you can pass a function and use the index to grab data. I believe you have to shift index (-1):

``tickFormat={(d) => `yourLabel with ${yourData[d-1].guid}` ``

Hope this helps.

**Comment by boygirl** [comment]
@billcreative This is a confusing aspect for the tutorial that I will correct. `tickValue` specifies _where_ the ticks should be placed on the axis, and `tickFormat` specifies how they should be formatted. So if you have qualitative data like:

`data={[ {x: "cat", y: 1}, {x: "dog", y: 2}, {x: "bird:, y: 3} ]}`

and you supply` tickValues={["a", "b", "c"]}` they wont be found in the the string mapping, and wont be displayed. I should probably make the reverse situation (numeric ticks and string tickValues) not work. I'm really sorry for the confusion. I'll update the tutorial.

**Comment by billcreative** [comment]
I see, this is my second day playing around with Victory so still learning the inner workings! Appreciate the heads up 👍

**Comment by boygirl** [comment]
@cpnielsen ^^

@billcreative sorry, I @'ed the wrong person!

**Comment by cpnielsen** [comment]
@boygirl It makes sense, as you said the tutorial is just really confusing on this point.
