### ISSUE TITLE
VictoryVoronoiTooltip doesn't fire onMouseMove and onMouseOut

### ISSUE THREAD

**Issue by daywee** [FormidableLabs/victory#469]
Hi, I am using events in VictoryChart with VictoryScatter and VictoryVoronoiTooltip. I want to be able to change color of VictoryScatter point when label is shown. OnMouseClick and onMouseMove events are fired properly, but onMouseOver and onMouseOut are not. When i attach events directly to VictoryVoronoiTooltip everything works just fine. 

Thanks for help.

**Comment by boygirl** [comment]
@daywee the `onMouseOver` and `onMouseOut` events are being masked by the `defaultEvents` provided by `VictoryTooltip`. You can read about using custom events with tooltips in this guide http://formidable.com/open-source/victory/guides/tooltips. Also, you use case is very common, so I have added a `active` prop to all the data primitives that is also triggered with the tooltips. All functional styles / prop are now evaluated with `(datum, active)` as args, so you will be able to change the color of the scatter point without publishing `onMouseOver` events of your own, just with `style={{data: {fill: (datum, active) => active ? "red" : "black"}}` This new functionality is released in `victory0.15.0` (released yesterday). I'm still finishing up the docs
