### ISSUE TITLE
Minor breaking typo in Readme - import Victroy instead of Victory

### ISSUE THREAD

**Issue by AlexHandy1** [FormidableLabs/victory#47]
tried to send a quick pull request to fix this but didn't let me.

**Comment by boygirl** [comment]
Thanks! I'll figure out why it's not allowing PRs from outside of our org as part of this ticket too.

**Comment by exogen** [comment]
@AlexHandy1 Hmm, did you create a fork to push the PR to? If you're outside the org, you need to push to a different remote (like your fork) and open the PR pointing to that. (We even need to do this at Formidable sometimes before a repo's permissions are set up for everyone.)

If you forked and it still didn't work, then something's messed up for sure!

/cc @boygirl

**Comment by AlexHandy1** [comment]
@exogen @boygirl 

Ah yes, didn't fork it, sorry, presume that was the issue.

**Comment by coopy** [comment]
PR open: https://github.com/FormidableLabs/victory/pull/51
