### ISSUE TITLE
Theme tooltip flyout styles aren't displaying

### ISSUE THREAD

**Issue by billcreative** [FormidableLabs/victory#471]
Any styles added to flyout in a theme:

```JavaScript
tooltip: assign({
    style: {
      ...
      flyout: {
        stroke: "red",
        strokeWidth: 2,
        fill: "#fff",
        pointerEvents: "none",
      }
    },
...
```

don't seem to apply. Is this the correct way to style all tooltips or is there another way?

**Comment by boygirl** [comment]
@billcreative You're right, these are only getting applied from `VictoryVoronoiTooltip` I'll get this fixed. In the meantime, you can apply styles directly to tooltips like:

```
labelComponent={
  <VictoryTooltip
    flyoutStyle={{stroke: "red"}}
    cornerRadius={0}
    pointerLength={20}
  />
}
```

**Comment by billcreative** [comment]
@boygirl that's good, I thought I was going mad :) Excellent work 👍
