### ISSUE TITLE
domainPadding doesn't appear to be pixel based

### ISSUE THREAD

**Issue by billcreative** [FormidableLabs/victory#472]
In the documentation for `<VictoryChart/>` the documentation states 

> The `domainPadding` prop specifies a number of pixels of padding to add the beginning or end of a domain.

However when the chart is sized at the default size

> _default (provided by default theme):_ `width={450} height={300}`

The`domainPadding` does not seem to be pixels. In fact, if you specify `x: [20, 20]` and compare that with `x: [40, 20]` you'll notice the side that's supposed to be 20px has reduced.

I may be missing something about the way charts are drawn so excuse any misunderstanding.

**Comment by boygirl** [comment]
@billcreative You're good at catching edge cases. My logic on this one was wrong. Padding the domain affects how much padding needs to be applied to the domain as a percentage.

**Comment by billcreative** [comment]
Perfect. Thanks for the information :)

**Comment by billcreative** [comment]
Hey @boygirl, could you explain what the `domainPadding` is a percentage of? When set to 100 I can't seem to find out how the number is calculated. Sorry for all the questions.

**Comment by boygirl** [comment]
@billcreative domain padding should be given in number of pixels which will be translated into an amount of padding to add to the domain (in data value). So the amount the domain will be padded by actually depends on the percentage of the range the number of pixels of domain padding represents. My adjustment looks like it solves one bug, and introduces another (as identified by @brycepavey). Zero values are no longer aligned to the axis when domain padding is applied to a chart that has both positive and negative values.

**Comment by sharno** [comment]
Any updates on this? I haven't been able to adjust domain padding properly.
It weirdly stops working on the left side after reaching 100 if I specify it to be `{ x: [100, 200] }`
Any value bigger than 100 for the left side doesn't add any more padding. While adding more to the right side works properly.

**Comment by JussiIvbar** [comment]
Also waiting for an update on this.

**Comment by boygirl** [comment]
Fixed for most situation in [`victory@35.8.0`](https://github.com/FormidableLabs/victory/blob/main/CHANGELOG.md#3580-2021-05-19)
