### ISSUE TITLE
unexpected behaviour(positioning) of svg child elements 

### ISSUE THREAD

**Issue by getorca** [FormidableLabs/victory#473]
Child elements like VictoryArea always seem to have an uncontrollable position and sizing in comparison to parent svg

**Comment by boygirl** [comment]
@getorca Victory uses responsive SVGs by default, maybe that's where you're running into an issue? All components also have default width / height / and padding provided by their default themes. You can define these props for more control. I'm going to close this issue for now, but I'm happy to re-open it if you can provide a more specific example of something behaving in an unexpected way.
