### ISSUE TITLE
Using tickValues or tickFormat breaks VictoryAxis with horizontal VictoryBar

### ISSUE THREAD

**Issue by Zerim** [FormidableLabs/victory#484]
This example of an inverted chart with a VictoryBar and a non-Victory bar works okay: https://jsfiddle.net/zcy1kmej/.

Supplying tickValues, however breaks the layout of the chart, as shown here: https://jsfiddle.net/oyfvwa6y/

Additionally, note how in this example, using tickValues alongside tickFormat seems to result in incorrect values being supplied to tickFormat: https://jsfiddle.net/8gdhogzn/

Even stranger, note how in the last example `tickValues` is being supplied to the **dependent axis**, resulting in the tick values showing up on the y-axis. However, in the prior example (without tickFormat), setting `tickValues` on the **independent axis**  results in the tick values showing up on the y-axis. 

This relates to the overall difficulties of inverting axis, as mentioned in: https://github.com/FormidableLabs/victory/issues/109

**Comment by Zerim** [comment]
Update: I was able to get around this by using the `tickFormat` prop instead of the `tickValues` prop, and passing it into a different axis based on whether my axis are "inverted". 

It still seems inconsistent that some things get automatically swapped for you when you set `horizontal=true` on a VictoryGroup, and others do not... I guess this makes sense, however, when you consider that VictoryGroup is only responsible for reconciling domain, etc. so maybe VictoryChart should also have a `horizontal` prop.

**Comment by Awem** [comment]
@Zerim Can you please provide an example of a horizontal Bar Chart with tickFormat for the axes? I just wasn't able to make it work.
