### ISSUE TITLE
VictoryZoom Breaks when Zooming using Scrollwheel mouse

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/victory#485]
The _VictoryZoom_ and _VictoryZoomContainer_ components can get stuck in an inoperable state when zooming using a scrollwheel. Have not tested on MacOS, but can confirm this is happening on Chrome in a Windows environment.

**Notes from original reporter:**
- Does not break in Firefox, Firefox scroll behaves differently than in Chrome
- Happens when "scrolling quickly" (zooms a lot faster/farther each tick)
- User's scrollwheel is set to 3 ticks

**Steps to Reproduce:**
1. View first example here on Windows/Chrome - https://formidable.com/open-source/victory/guides/pan-and-zoom/
2. Using a scrollwheel mouse, try zooming in/out quickly and notice the example gets "stuck" like the provided image
3. No user input is able to recover from this, the page must be reloaded. (Not sure if there are console errors present, I'm reporting on behalf of another user)

![pasted_image_at_2017_02_01_11_52_am_360](https://cloud.githubusercontent.com/assets/1633837/22534157/0003f26e-e8a7-11e6-9ba5-aa555f518433.png)

It might be that the scrollwheel event is firing too often and this event may need to be throttled?

**Comment by kylecesmat** [comment]
Fixed in #429 🎉

**Comment by chrisbolin** [comment]
@boygirl do we want to keep this open for now, until we test the zoom-limiting?

**Comment by chrisbolin** [comment]
Tested with new victory-chart `16.1.2` and it works on Win 8, Win 10, and OS X 🎉. Closing for now.
