### ISSUE TITLE
Voronoi cells with zero areas keep throwing react errors

### ISSUE THREAD

**Issue by kumarharsh** [FormidableLabs/victory#486]
When I'm passing data to a voronoi tooltip with data points where some of them have the same value, for example `{x: 0, y: 0}`, then this error is shown in console:

```
Error: <path> attribute d: Expected number, "M  Z".
```

**Comment by boygirl** [comment]
VictoryVoronoi cant work with non-unique datasets. `VictoryVoronoiContainer` which will be released later this week will work with multiple datasets and non-unique data.

**Comment by kumarharsh** [comment]
Thank you for the update. Looking forward to it...
