### ISSUE TITLE
VictoryScatter doesn't display anything in Firefox if input data is array of arrays

### ISSUE THREAD

**Issue by inkybutton** [FormidableLabs/victory#487]
Hi,
I'm plotting a graph using VictoryScatter with Victory 0.16. The input data is an array of arrays. Here's the code:
`//inside render()`
`var data = [[0,3],[1,5]];`
`return (<VictoryScatter data={data} x={0} y={1} />);`

This chart works in WebKit, but this error is thrown in Firefox, and nothing is rendered:
`TypeError: CSS2Properties doesn't have an indexed property setter for '0'`
This is coming from inside React code, here's part of the call stack:
`CSSPropertyOperations.setValueForStyles()
 CSSPropertyOperations.js:187
ReactDOMComponent.Mixin._updateDOMProperties()
 ReactDOMComponent.js:886
ReactDOMComponent.Mixin.mountComponent()
 ReactDOMComponent.js:522
ReactReconciler.mountComponent()
`

However, if the input data is an array of data objects then it works in Firefox without problems. This code should work in Firefox:
`//inside render()`
`var data = [{x:0,y:3},{x:1,y:5}];`
`return (<VictoryScatter data={data} x="x" y="y" />);`

**Comment by boygirl** [comment]
I'm closing this issue as "wontfix". Data should be given as an array of objects.
