### ISSUE TITLE
How to clear previous styles after an event

### ISSUE THREAD

**Issue by ShMcK** [FormidableLabs/victory#489]
How can one go about clearing previous styles after a event mutation is triggered?

This would create the effect of a single selected bar at one time.

An example from the docs where each click creates another orange colored bar with the label "hey", without ever clearing out the previous existing orange colored bars. Clicking around results in all of the bars become orange with the word hey, rather than highlighting a single bar a time.

```js
events={[
  {
    target: "data",
    eventHandlers: {
      onClick: () => {
        return [
          {
            mutation: (props) => {
              return {
                style: Object.assign({}, props.style, {fill: "orange"})
              };
            }
          }, {
            target: "labels",
            mutation: () => {
              return {text: "hey"};
            }
          }
        ];
      }
    }
  }
 ]}
```

**Comment by boygirl** [comment]
@ShMcK you can clear all the props set by previous events by returning null. Check out this guide on events: http://formidable.com/open-source/victory/guides/events

**Comment by ShMcK** [comment]
Thank you for your quick response. Returning null does clear the other styles.

However, it also logs an error on each click.

```
Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at Bar.getBarWidth (bar.js:59)
    at Bar.render (bar.js:81)
    at ReactCompositeComponent.js:796
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:746)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
```

**Comment by boygirl** [comment]
@ShMcK I'll check on this. In the meantime, you might try returning `{style: undefined}` to clear just the props you were altering

**Comment by alvaromb** [comment]
Sorry to jump into an old issue. I'm struggling with the exact example that @ShMcK describes, however I cannot find any way to reset label styles when I select any bar of the `VictoryBar` component.

I want to highlight the label of a bar when I select the bar, but when I select any other, I want to return the previously selected label to the initial state.

Do you have any full example of this @boygirl?

**Comment by redzacool** [comment]
did you find any answer to this issue @ShMcK ?

**Comment by ZahidRasheed** [comment]
Anyone found a solution for this. I am stuck with exactly similar case where I would like to have a single selected bar.
