### ISSUE TITLE
VictoryZoomContainer and multiple dependent axes

### ISSUE THREAD

**Issue by HalHaig** [FormidableLabs/victory#492]
How do we get VictoryZoomContainer to work with a chart with multiple dependent axes?

**Comment by boygirl** [comment]
@HalHaig you can only have one zoom container per chart, and it will control the domain for all the components nested within it. If you have multiple axes, I'm assuming you need multiple domains on the same chart. To do that I think I would try something like creating one `VictoryGroup` that has `VictoryZoomContainer` as its `containerComponent`, and then using the `onDomainChange` callback on `VictoryZoomContainer` to alter the  x value of the domain of the second `VictoryGroup` or `VictoryAxis` component. Let me know if you can't get it to work correctly, and I'll see what I can do to support you.
