### ISSUE TITLE
Mark private methods

### ISSUE THREAD

**Issue by DerekMaffett** [FormidableLabs/victory#494]
In most of our files, private method extractions aren't explicitly notated as such and are publicly available. This is relatively easy to understand for React components since only the lifecycle methods are truly "public" but it becomes especially difficult in other files to see what things are part of the public interface and what parts are simply internal refactors. 

I would suggest at a minimum that we mark private methods as `_privateMethod` to indicate that they can be refactored without breaking functionality by accident. A harder line would be to only export public functions and leave private methods unaccessible outside the module, but I don't think we need this extensive a change right now. Simply marking the methods would clarify the intentions of each module.

**Comment by boygirl** [comment]
fixed by moving to named exports
