### ISSUE TITLE
VictoryArea and "null"

### ISSUE THREAD

**Issue by ShMcK** [FormidableLabs/victory#496]
Is there a way to show gaps in data in VictoryArea.

VictoryArea does not handle null, and instead renders it as 0.

Other efforts to apply multiple area graphs on the same chart (split by gaps) result in the graphs being layered exactly on top of each other, rather than along unique points on the x axis. This can be seen by the area graph opacity fill become lighter and lighter the more area graphs are being rendered.

**Comment by boygirl** [comment]
@ShMcK I'll implement this change in the next version. Thanks for pointing it out.
