### ISSUE TITLE
NSNumber cannot be converted to NSString - victory-pie-native

### ISSUE THREAD

**Issue by edo1493** [FormidableLabs/victory#498]
Hi, 

I am trying to use victory-pie-native on RN40.0, whenever I pass an array of objects, I get this. Each object has different properties and I have set for x and y, two of them, but there is a property ID, which I don't use that creates this issue (301 is the object id). 

"JSON value '301' of type NSNumber cannot be converted to NSString"

I was wondering if id was a reserved word? Thanks.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-native#51
