### ISSUE TITLE
styles as functions of x and y

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#50]
example

```
style={{
  data: {
    fill: (x, y) => x < 50  && y < 10 ? "blue" : "red"
  }
}}
```

**Comment by jonathanchu** [comment]
If this was added to a Release milestone, does that mean support for this exists currently?

**Comment by boygirl** [comment]
This is supported, though the api changed slightly from what you see here. Functional styles look like:

```
style={{
  data: {
    fill: (datum) => datum.x < 50  && datum.y < 10 ? "blue" : "red"
  }
}}
```

**Comment by jonathanchu** [comment]
Cheers, thanks for confirming @boygirl! :beers:
