### ISSUE TITLE
Red colorScale has the same color twice

### ISSUE THREAD

**Issue by valscion** [FormidableLabs/victory#502]
Hiya!

I found out that the red color scale has [the color `#B02928` twice](https://github.com/FormidableLabs/victory-core/blob/v14.0.1/src/victory-util/style.js#L53):

```
 red: ["#611310", "#7D1D1D", "#B02928", "#B02928", "#D86B67"]
```

This might result in charts with no visual distinction between two different values.

Is this a bug? I could whip together a PR to fix this, if you could tell me what you'd like the colors to be.

**Comment by boygirl** [comment]
Yes, this is a bug. Would you be willing to suggest another color scale? The current one is somewhat arbitrary.

**Comment by valscion** [comment]
Hmm, would the red scale used by ColorBrewer work? http://colorbrewer2.org/#type=sequential&scheme=Reds&n=5

```
#fee5d9
#fcae91
#fb6a4a
#de2d26
#a50f15
```

<img width="114" alt="screen shot 2017-03-01 at 22 22 23" src="https://cloud.githubusercontent.com/assets/482561/23479577/9417fd56-fecd-11e6-9427-aba2a4fda996.png">

**Comment by boygirl** [comment]
@valscion I think the light pink might get pretty invisible. What about dropping the lightest color and adding #750b0e (10% darker than your last shade)?

**Comment by valscion** [comment]
I don't think the light pink is too invisible, and actually prefer that one compared to the darker version. Here's a reference pic of a stacked bar chart with these two variations:

![screen shot 2017-03-02 at 10 14 06](https://cloud.githubusercontent.com/assets/482561/23498615/207feeda-ff31-11e6-99da-8d2ced6900c5.png)

![screen shot 2017-03-02 at 10 13 47](https://cloud.githubusercontent.com/assets/482561/23498616/2084720c-ff31-11e6-849e-821e88d47cef.png)

What do you think?

**Comment by boygirl** [comment]
It looks good with bars, but with lines: 

lighter:
<img width="430" alt="screen shot 2017-03-02 at 11 38 29 am" src="https://cloud.githubusercontent.com/assets/3719995/23523896/6d185e74-ff3d-11e6-89e3-c30e6d6c0d78.png">

darker: 
<img width="426" alt="screen shot 2017-03-02 at 11 41 00 am" src="https://cloud.githubusercontent.com/assets/3719995/23523906/75ecf10e-ff3d-11e6-9621-6b2459884491.png">

**Comment by valscion** [comment]
Yeah I asked my friend who has trouble seeing low contrast items and she had trouble seeing the lighter versions lightest line.

So let's do as you say 😁. I'll send a PR today

**Comment by valscion** [comment]
Sorry, didn't get to it yesterday but there is a fix now: https://github.com/FormidableLabs/victory-core/pull/213
