### ISSUE TITLE
VictoryZoomContainer: First mouse event after changing zoomDomain prop causes the zoom to change back to initial position

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/victory#506]
Placeholder issue. Will fill in more details later.

![zoomcontainer-glitch](https://cloud.githubusercontent.com/assets/1203949/23550709/596bc65e-000a-11e7-8176-76b3eb875bdc.gif)

**Comment by mindjuice** [comment]
Note that you can see the same effect in the Victory "brush and zoom" example here:

https://formidable.com/open-source/victory/guides/brush-and-zoom/

1. Zoom in on the top graph with the mouse.
2. Move the domain brush a noticeable distance in the bottom graph.
3. Zoom in on the top graph again.

It step 3, the domain will jump back to where it was at the end of step 1.

**Comment by boygirl** [comment]
I believe this was fixed by @chrisbolin in ~`victory@0.19.0`
