### ISSUE TITLE
VictoryZoomContainer with animation behaves inconsistently and doesn't initially render

### ISSUE THREAD

**Issue by chriskurzeja** [FormidableLabs/victory#507]
I've been working on a chart with animation - it uses the VictoryZoomContainer to do a periodic pan when a certain number of visible points are displayed on the chart. I'm having two issues with this that I'm struggling to solve. There's a JSFiddle [here](https://jsfiddle.net/chris_kurzeja_flextrade/t6o8jo6t/4/). Note: there are a ton of svg issues that aren't there when the code is run outside of JSFiddle.

Issue 1 - when the chart is first drawn (after a brief 'loading' screen which replaces our in app version) the axes are drawn but the VictoryLines aren't shown until you click on the chart.

Issue 2 - the chart animation is a little strange - I expect the change in zoomDomain to animate all of the lines and axes together - this isn't always the case. I also only want it to animate on the zoomDomain change as we slice the dataset once we reach a certain number of points. Is this something I'll be able to do? It seems to trigger an animation when we slice the off screen values and update the xDomain (which is when the background moves like crazy).

Any thoughts would be appreciated.

**Comment by chriskurzeja** [comment]
This is an alternate fiddle that uses an implementation that mostly works - https://jsfiddle.net/chris_kurzeja_flextrade/277esyur/ - I believe #503 may address this

**Comment by boygirl** [comment]
I believe this is fixed, but I'm happy to re-open if the issue is persisting for anyone.
