### ISSUE TITLE
VictoryGroup offset prop doesn't work as expected

### ISSUE THREAD

**Issue by sto3psl** [FormidableLabs/victory#509]
Per documentation the offset prop in VictoryGroup should work like this: 

> The offset prop derermines the number of pixels each element in a group should be offset from its original position of the on the independent axis. In the case of groups of bars, this number should be equal to the width of the bar plus the desired spacing between bars.

While implementing a Chart with grouped bars I noticed that the bars overlap when `offset` and `width` of the bar are the same value. In my case I don't spacing between the grouped bars.

You can see it in this jsfiddle https://jsfiddle.net/hhemaj3m/. 

![bildschirmfoto 2017-03-07 um 16 41 58](https://cloud.githubusercontent.com/assets/5798652/23664149/0a3d8c22-0355-11e7-83c7-720765173b34.png)

Is that the expected behaviour or a bug?

**Comment by sto3psl** [comment]
Follow up: This is more ore less just a question. When I add axes to the chart, the bars are not aligned to the labels which is expected because the bars are offset from `VictoryGroup`. Is it in any way possible to align the position of the grouped bars with the labels on the x-axis?

![bildschirmfoto 2017-03-07 um 18 11 23](https://cloud.githubusercontent.com/assets/5798652/23668753/470d36e0-0362-11e7-9b3e-6ef7e8ad883e.png)

I would like to have it like on the bars for ***one***, but for every group of bars and their label.  
Also a fiddle https://jsfiddle.net/g1pv77xm/.

**Comment by boygirl** [comment]
@sto3psl yes, this looks like a systematic error, and possibly related to [this issue](https://github.com/FormidableLabs/victory/issues/345) you commented on related to rounding path values. I will try to address these two together.
