### ISSUE TITLE
VictoryLegend in version 0.17.0 is always anchored to the top left

### ISSUE THREAD

**Issue by jhdielman** [FormidableLabs/victory#510]
VictoryLegend in version 0.17.0 is always anchored to the top left and doesn't seem to change. Is there a way to make this float? I have a scrollable chart and I want to be able to see the legend at all times.

**Comment by boygirl** [comment]
@jhdielman `VictoryLegend` takes `x` and `y` props for positioning, but you will have to update those manually when you scroll your chart. I'm closing this issue for now, but I'm happy to re-open it if that doesn't solve your issue. You can also ask questions in the [gitter channel](https://gitter.im/FormidableLabs/victory)

**Comment by jhdielman** [comment]
Many thanks @boygirl. Unfortunately, the x and y props don't seem to make a difference.

**Comment by boygirl** [comment]
Okay, I'll check it out

**Comment by zsherman** [comment]
+1
