### ISSUE TITLE
Starting y-axis at 0 instead of the value calculated from the data

### ISSUE THREAD

**Issue by jayster55** [FormidableLabs/victory#512]
As you can see below I can't find a way to center the data starting at 0 in order to compare the scale. I was wondering how I would go about this?

![screen shot 2017-03-10 at 10 18 55 am](https://cloud.githubusercontent.com/assets/16628810/23800680/4ef8ca2a-057b-11e7-8935-f222a7488d83.png)

**Comment by boygirl** [comment]
@jayster55 You will want to set a domain on your chart component like:
```
<VictoryChart domain={{y: [0, 4000]}}>
  <VictoryLine/>
  ...
</VictoryChart>
```
The [gitter channel](https://gitter.im/FormidableLabs/victory) is a great resource for questions like this.

**Comment by bramvbilsen** [comment]
Sorry for opening this again, but I am still confused on how to achieve this. I tried setting the `domain` and `tickValues` properties for my Y-axis, but the problem persists. The Y axis still starts from 0.
