### ISSUE TITLE
VictoryPie does not display percentage value for each slice

### ISSUE THREAD

**Issue by quangkhoa** [FormidableLabs/victory#513]
It would be nice to have a property on VictoryPie to determine whether the percentage value for each slice should be displayed.

Currently the `Slice` component only has the data just enough to render the slice, and not the total value in order to work out the percentage. Perhaps the percentage could be calculated and passed into the slice, which will then decide whether to display it or not.

**Comment by lejager** [comment]
Has anyone managed to do this? I'm working on implementing it, and not sure the right approach. Is there a way to pass in a label to the slice component, or do I need to create a custom component based on slice? Any insight is much appreciated.

**Comment by boygirl** [comment]
@lejager are you interested in adding this feature to Victory? If so the answer is more complex. If you need to add it it in your own app, you would do some math on your data to figure out the sum of all your y data values, and then add a label prop like `labels={(datum) => `${datum.y / myTotal}%`}`

**Comment by dakahn** [comment]
I'm down to work on this @boygirl

**Comment by boygirl** [comment]
@dakahn sorry for the delay. 

I think the best way to implement this feature is actually to calculate the percentage for all data points and add it to the altered data object. Then a user wanting to display percentage in their pie could do so like `labels = (datum) => `${datum.percent}%``

To get started, check out how `VictoryArea` alters data: https://github.com/FormidableLabs/victory/blob/master/packages/victory-area/src/helper-methods.js#L4

You should also take a look at our contribution guide: https://github.com/FormidableLabs/victory/blob/master/CONTRIBUTING.md

Thanks for helping out!

**Comment by boygirl** [comment]
I think this feature is best implemented as a data pre-processing step. Something like: calculating the sum of all your y data values, and then adding a labels prop like `labels={(datum) => ${datum.y / myTotal}%}`
