### ISSUE TITLE
VictoryCursorContainer

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#514]
Cursors with configurable labels similar to 
https://status.postmarkapp.com/

**Comment by boygirl** [comment]
http://bl.ocks.org/benjchristensen/2657838

**Comment by seddonm1** [comment]
This would be super useful as the VictoryVoronoiContainer for multiple lines doesn't really work well from a UX perspective.

**Comment by boygirl** [comment]
released in `victory@0.19.1`
