### ISSUE TITLE
Victory not working with next.js

### ISSUE THREAD

**Issue by alikhani** [FormidableLabs/victory#516]
I'm trying to try out victory with next.js and can't get it working.
Next.js goes into an infinite error loop and keeps throwing 
`TypeError: Cannot read property 'props' of undefined` on add-events. [On this line](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/add-events.js#L81)

example: [next-victory](https://github.com/alikhani/next-victory)

**Comment by boygirl** [comment]
@alikhani I'm happy to throw a check in for that line, but I'm wondering whether there's a larger issue with the inheritance inversion pattern I'm using in `add-events`. [This article has a great write up of the  inheritance inversion pattern](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e#.fjmd1hfzy)

**Comment by alikhani** [comment]
It works fine now after the patch the next people did.
