### ISSUE TITLE
Unknown prop `clipWidth` on <g> tag

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#526]

**Comment by newtriks** [comment]
@boygirl thank you for this, unfortunately using `0.18.3` the error remains in the console for me?
If there is anything else I can provide to help diagnose I'd be happy help.

![screen shot 2017-03-28 at 13 44 28](https://cloud.githubusercontent.com/assets/31971/24405455/d3d41926-13bc-11e7-873a-f993f612bac5.png)

**Comment by matejstrasek** [comment]
This should be reopened.

**Comment by JacksonToomey** [comment]
I am also using 0.18.3 and still have this error, only when I use the animation prop.

**Comment by sto3psl** [comment]
You should check in the new version 0.18.4. It is gone.

**Comment by JacksonToomey** [comment]
I just upgraded to 0.18.4 and it's still there

**Comment by boygirl** [comment]
@JacksonToomey this bug has been such a hydra! I thought I'd finally put it to rest in `0.18.4`. Can I ask you to delete all your victory node modules and npm install again?

**Comment by JacksonToomey** [comment]
@boygirl Did that and the error is gone.

**Comment by newtriks** [comment]
I can confirm this is now fixed for the 0.18.4 release.
