### ISSUE TITLE
Option to disable VictoryPie label

### ISSUE THREAD

**Issue by peterhadlaw** [FormidableLabs/victory#528]
I'm using the new `VictoryLegend` and I was wondering if there is a proper way to disable the rendering of labels via the `labelComponent` on `VictoryPie`. Using `labelComponent={null}` causes a fatal error

**Comment by boygirl** [comment]
@peterhadlaw try `labels={() => null}` instead

**Comment by ShaikhKabeer** [comment]
It's not working in case of `<VictoryLine>`

**Comment by andion** [comment]
@ShaikhKabeer I guess you can always style it, right?  `style={{ labels: { display: "none" } }}`

**Comment by dcorrea80** [comment]
@ShaikhKabeer I was having trouble with the <VictoryLine> as well, and applying a style like @andion suggested didn't work for me. I was able to fix this (not as cleanly as I would've liked) by adding my own CSS overrides, but I think this is still an open issue.
.VictoryContainer svg text {display: none;}  //Removes the labels
.VictoryContainer svg g text {display: block} //Preserves the axis information, if needed.

**Comment by SushanRajShakya** [comment]
In my case, I used a blank custom element.

`labelComponent = { <span></span> }`

Still a hack and would like a better solution as 

`<VictoryLabel active={false}/>`
