### ISSUE TITLE
Bubble Charts?

### ISSUE THREAD

**Issue by nikolay-g** [FormidableLabs/victory#534]
Does Victory support [bubble charts](https://en.wikipedia.org/wiki/Bubble_chart)?

**Comment by boygirl** [comment]
Yes. You can create a bubble chart using the [`bubbleProperty`](https://formidable.com/open-source/victory/docs/victory-scatter#bubbleproperty) prop on `VictoryScatter`, or but passing in your own function of data to the [`size`](https://formidable.com/open-source/victory/docs/victory-scatter#size) prop as in the example.
