### ISSUE TITLE
VictoryBrushContainer when using multiple axis

### ISSUE THREAD

**Issue by mleonard87** [FormidableLabs/victory#535]
I'm attempting to render a graph with multiple axes and have followed your [multiple axes example](http://formidable.com/open-source/victory/recipes/multiple-axes/)

You also state that you cannot use multiple axes within a VictoryChart and as such I have used a `<svg>` element to wrap the various components.

How can I go about using a `VictoryBrushContainer` with this? The examples say that a brush needs to go into a `containerComponent` of a `VictoryChart` but as I don't have one I'm not sure where to put it.

Thanks, Mike.

**Comment by boygirl** [comment]
@mleonard87  all Victory Components use a `containerComponent` prop. You can supply `VictoryBrushContainer` to a different component like `VictoryGroup` or even something like `VictoryLine`. Here's a similar example to what you are trying to accomplish using `VictoryVoronoiContainer` instead. https://jsfiddle.net/boygirl/0uaox6gL/3/
