### ISSUE TITLE
Victory Container events don't work with a non-standalone chart

### ISSUE THREAD

**Issue by jamieparkinson** [FormidableLabs/victory#539]
The active state doesn't get 'switched on' consistently when using `VictoryVoronoiContainer` for a `VictoryChart` with `standalone={false}` like this: https://jsfiddle.net/pzkofefm/2/. It seems like it only registers when the cursor is hovering over the elements in the chart - an issue I never had when using the old `VictoryVoronoi`.

Have I missed something in terms of other props that need to be set?

**Comment by boygirl** [comment]
@jamieparkinson You're right, this is not operating as expected. I'll look into it today.

**Comment by chrisbolin** [comment]
hmm, I saw something similar to this while working on https://github.com/FormidableLabs/victory-chart/pull/453 and breaking things. I'll take a look, too

**Comment by chrisbolin** [comment]
it seems like it fails if you simply wrap the `<VictoryChart>` in an `svg`, regardless of what the `standalone` prop is

**Comment by chrisbolin** [comment]
Ahh, I think I found the problem @boygirl. When the `containerComponent` prop is added, `standalone` seems to be overridden: even with `standalone=false` VictoryChart still renders a wrapping svg, so you have two: one in user-land (that's why it was `standalone=false`) and one added by the container component.

**Comment by chrisbolin** [comment]
I added some logging to `VictoryZoomContainer` and can confirm that the container's defaultEvents's eventHandlers don't fire as they should...
![mar-27-2017 15-04-12](https://cloud.githubusercontent.com/assets/2822048/24344980/832917ae-1300-11e7-8157-f172e1033081.gif)

**Comment by jamieparkinson** [comment]
@chrisbolin nice bug-hunting! I am working my way into the victory codebase so I can try to help with stuff like this myself :slightly_smiling_face:

**Comment by chrisbolin** [comment]
This affects all "evented" containers (VictoryVoronoiContainer, VictoryBrushContainer, VictorySelectionContainer, and VictoryZoomContainer) so I updated the title

**Comment by SenhorBardell** [comment]
Any updates on this one? Still having issues on Victory Group Cursor wrapped with Svg

**Comment by boygirl** [comment]
This one is a wontfix. Evented containers only work with `standalone={true}`
