### ISSUE TITLE
victory-chart demo has lots of console errors

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory#541]
While loading the demos from current `master` of `victory-chart`, I got upwards of 100 console errors and warnings while clicking though the 17 demo links. Most of the errors were duplicates, and seem to boil down to these unique errors...

- `This is an empty dataset.`
- `Area requires at least two data points.`
- `Warning: setState(...): Can only update a mounted or mounting component.`
- `Error: <svg> attribute viewBox: Expected number, "0 0 undefined undefi…".`
- `VictoryLine needs at least two data points to render properly.`
- `Uncaught TypeError: _victoryUtil.Collection.allEqual is not a function at Candle.shouldComponentUpdate (candle.js:44)`

**Comment by chrisbolin** [comment]
This makes it hard to see if you broke something when changing the library, or just playing with the components.

**Comment by SamSamskies** [comment]
@boygirl is this still an issue? I'm not seeing any console errors.
