### ISSUE TITLE
Possible loss of functionality with the new VictoryVoronoiContainer

### ISSUE THREAD

**Issue by kumarharsh** [FormidableLabs/victory#542]
Hello, I just upgraded the library, and started getting the warning that VictoryVoronoi might be deprecated / removed in future, and that I should move to VictoryVoronoiContainer. I tried doing the same, and while I really liked the simplicity it provides, I have run into a problem which I don't see a solution for.

See, I had a scatter-graph, and was using a VictoryVoronoi overlay on top of the VictoryScatter component to handle mouse-events. These mouse events were: `hover` over a point to add a `hover` class, and `click` on a point to activate it and call an `onChange` function. Now, with VictoryVoronoiContainer, while the hover functionality is easy to implement, how do I implement the *click* functionality?

One option is to add the `onClick` for each `dataComponent` of the `VictoryScatter`, but then only the data point is clickable, but the nearby areas are not (nearby areas are defined as areas which fall under the point's voronoi field, but are not covered by the data point's bounds itself). This is not ideal, as I'd like the benefits of voronoi (larger hit-area) which are available on hover for the click event too.

Another minor issue is that earlier, I had applied a `cursor:pointer` style to the voronoi overlay so that user could get an idea that the area was clickable. But with the new API, I don't know if that's possible.

**Comment by boygirl** [comment]
@kumarharsh 

`VictoryVoronoiContainer` behaves a little differently than `VictoryVoronoi` in that the voronoi areas are never rendered, only calculated. As such, you wont be able to add new behaviors to the areas themselves, but you can add behaviors to the parent svg. You will want to use the `onActivated` callback to capture the current closest data (which will include the data itself as well as the childName and event key). That will be used to create the target for your `onClick` mutation. 
I made you a quick example. https://jsfiddle.net/boygirl/xq5L9k1u/

I agree that it's a bit more annoying than with `VictoryVoronoi`, but the performance should be better as you aren't rendering the unnecessary voronoi areas.

**Comment by kumarharsh** [comment]
@boygirl - yes, I agree to all your points - the container is a very good approach. It's just that I wasn't able to figure out this (now rather obvious) interaction. Thanks for the working demo to illustrate your point - you're awesome :-)

Also, once I've understood now, I find it not annoying at all, and in fact rather better - my code is also shorter.

**Comment by antonvasin** [comment]
@boygirl was struggling with this kind of problem myself and was relieved to find someone with similar issue, so thank you for explaining this bit. jsfiddle example is 404 though. Any chance of reuploading it?
