### ISSUE TITLE
VoronoiTooltip duplicates the labels in tooltip

### ISSUE THREAD

**Issue by alikhani** [FormidableLabs/victory#545]
When using VictoryVoronoiContainer with multiple groups of line and scatter the it duplicates the labels in the tooltip. I guess it's for line and scatter that has the same value. How can I disable one of them or specify that only the group label should be in the tooltip?

example: https://jsfiddle.net/alikhani/pwqcL300/

**Comment by boygirl** [comment]
Here's a temporary work around for those waiting on a solution:

Broken:
https://jsfiddle.net/boygirl/h9Luw9wk/

work around:
https://jsfiddle.net/boygirl/wwfsjy52/

**Comment by yogeshR5** [comment]
+1
@boygirl  i got same issue what i have to do now?

**Comment by boygirl** [comment]
We added a `voronoiBlacklist` prop. It can be used like so:
```
<VictoryChart
  containerComponent={
    <VictoryVoronoiContainer
       labels={(d) => d.y}
       voronoiBlacklist={["line1", "line2"]}
    />
  }
>
  <VictoryGroup data={myData}>
    <VictoryLine name="line1"/>
    <VictoryScatter/>
  </VictoryGroup>
  <VictoryGroup data={myOtherData}>
    <VictoryLine name="line2"/>
    <VictoryScatter/>
  </VictoryGroup>
</VictoryChart>
```
