### ISSUE TITLE
Tooltip and chart label simultaneously

### ISSUE THREAD

**Issue by nicmesan** [FormidableLabs/victory#551]
Hello. Is there a way to render tooltips and labels on the Victory Pie simultaneously? Since when I use the labelComponent prop containing the VictoryTooltip inside VictoryPie, the regular labels disappear from the chart.

Thanks in advance!

**Comment by boygirl** [comment]
@nicmesan the fiddles referenced in this issue should help you. https://github.com/FormidableLabs/victory/issues/554

**Comment by kumarharsh** [comment]
@boygirl it seems like all your fiddles are gone. Usually, this wouldn't be much of a problem, but in cases like this issue, it's critical to have a working sample for reference.

**Comment by Kebie** [comment]
Would really like to know how to do this. Please re-put up the jsfiddles please.

**Comment by boygirl** [comment]
Sorry about that. I had to re-write all the fiddles. Here's a new version: https://jsfiddle.net/boygirl/ytq13Lfk/

**Comment by jdalegonzalez** [comment]
There is a problem with the fiddle in that if the label itself is hovered, the tooltip piece disappears.  This isn't much of a problem with the fiddle you've supplied but is a problem if the size of the label is bigger or the area being labeled is smaller.  Is there a fix for this?  Something with defaultEvents maybe?

**Comment by seantcanavan** [comment]
@boygirl that fiddle is extremely helpful thank you so much for providing it. I made a small modification for my own purposes but there's still a black outline being rendered in the center label. Would you know how to hide that?

Fiddle here: https://jsfiddle.net/sqg4xL2y/

**Comment by Faizan-e-Muhammad** [comment]
Using stroke: "white" would remove the black outline.

**Comment by TeddyBurnsides** [comment]
I posted [here](https://github.com/FormidableLabs/victory/issues/1584#issuecomment-1481704831) a somewhat hacky way to accomplish this.
