### ISSUE TITLE
victory themes

### ISSUE THREAD

**Issue by sibelius** [FormidableLabs/victory#552]
is there any repo with victory themes?

or an `awesome victory`?

I would like to have a  `recharts` theme for victory, anybody did something like this?

**Comment by boygirl** [comment]
@sibelius we currently have only two themes. You can see them here https://github.com/FormidableLabs/victory-core/tree/master/src/victory-theme. I would be happy to create an additional repo that could be optionally included with Victory. Would you help populate it?

**Comment by boygirl** [comment]
I'm going to close this issue due to lack of continued interest

**Comment by sibelius** [comment]
you can create new themes using this tool

https://github.com/narinluangrath/victory-gui
