### ISSUE TITLE
incorrect rendering stroke rendering for bar graph

### ISSUE THREAD

**Issue by asurabhi** [FormidableLabs/victory#553]
There is a bug in stroke rendering for bar graph. Works fine on mac chrome. Bug exists for firefox(mac), chrome(windows) and safari(mac). Please refer to screen shot for preview of the defect. Here i used strokeWidth 4 here.
![stroke-rendering-bug](https://cloud.githubusercontent.com/assets/5525378/24739633/982a723a-1aba-11e7-93e8-34a8f19b6163.jpeg)

**Comment by boygirl** [comment]
@asurabhi thanks for pointing this out

**Comment by asurabhi** [comment]
@boygirl thanks for the prompt response

**Comment by boygirl** [comment]
This seems to no longer be an issue

Safari
<img width="512" alt="screen shot 2017-05-23 at 4 11 16 pm" src="https://cloud.githubusercontent.com/assets/3719995/26380287/8a201586-3fd2-11e7-988a-1bea5a747b92.png">

Firefox
<img width="420" alt="screen shot 2017-05-23 at 4 11 33 pm" src="https://cloud.githubusercontent.com/assets/3719995/26380295/91cc9e26-3fd2-11e7-8ca1-59e456205ee5.png">
