### ISSUE TITLE
Multiple VictoryAxis

### ISSUE THREAD

**Issue by seddonm1** [FormidableLabs/victory#555]
It is currently not possible to have a second 'mirrored' VictoryAxis on a VictoryChart. 

Expected behaviour would be to create a second 'Y' axis where the orientation was set so that a line graph values are easier to interpret against the axis.

Logical design is:
```
<VictoryChart>
  <VictoryAxis dependentAxis=false/>  
  <VictoryAxis dependentAxis=true orientation="left"/>
  <VictoryAxis dependentAxis=true orientation="right"/>
</VictoryChart>
```

**Comment by boygirl** [comment]
At the moment it is expected that the user will compose mutli-axis charts manually, as most users who want multiple y axes want separate domains for each. VictoryChart currently enforces a domain for each of its children. I will leave this issue open as a feature request / discussion.

1) Should `VictoryChart` only limit the number of _independent_ axes?

2) Should children of `VictoryChart` be allowed to determine their own domains when the `domain` prop is set?
  - in this case, how should `VictoryChart` reconcile the domains of its children? How will it know which children belong with which axis? Possibly `VictoryGroup`?

**Comment by boygirl** [comment]
As of `victory@0.21.0` multiple _dependent_ axes are allowed in `VictoryChart`.
All children of `VictoryChart` are still forced to use the same domain, so multi-axis data should be normalized and them plotted. The appearance of different domains should be achieved by scaling the displayed `tickValues` for each axis using the `tickFormat` function.

**Comment by marlti7** [comment]
react native  has same problem? can you update to 0.21.0

**Comment by jplanders** [comment]
I too need to take advantage of this on react-native.

**Comment by 2metres** [comment]
Trying to recreate [this multi axis example](https://formidable.com/open-source/victory/guides/custom-charts/) from the docs using the VictoryTheme

When I wrap the example code in a VictoryChart + Theme I get this result which does not appear to use the theme: 

https://codesandbox.io/s/gifted-proskuriakova-ulk0s

If I try to replace the `<g />` with a `<VictoryGroup />` I get the theme styles but the multi-domain stuff stops work:

https://codesandbox.io/s/hungry-brahmagupta-8mtne

**Could provide an example of how to do multi-axis stuff and theming?**
