### ISSUE TITLE
Combined Victory Container support [Feature Request]

### ISSUE THREAD

**Issue by zsherman** [FormidableLabs/victory#556]
Thanks for the hard work and and awesome lib! One request would be the ability to combine multiple containers at the same time. One use case I ran into was the desire to combine the `VictoryZoomContainer` with functionality from `VictoryVoronoiContainer`, but they don't seem to play well together.

**Comment by zsherman** [comment]
One step ahead of me 😄, I didn't even notice this https://github.com/FormidableLabs/victory-chart/commit/f4584e686b6434a301e84bb418cfdd9bf3856e7f.

**Comment by JarLowrey** [comment]
Did you figure out how to do this in @zsherman ?
