### ISSUE TITLE
Primitive components have `undefined` props on initial render

### ISSUE THREAD

**Issue by splawndive** [FormidableLabs/victory#562]
Hi, I have a chart on my company's website using Victory version 15.0.0.  I recently tried to add default props to some of the chart's custom components, and noticed that if, say, the custom grid line component being used is given default props such as `const defaultProps = {
  active: false,
  compact: false,
  index: 0,
  x1: 0,
  x2: 0,
  y1: 0,
};`,
then x1, x2, y1 (etc...) props that victory calculates and passes down to the component never get assigned to the props, and instead their values are always 0.  If I mark these props as "required" in the PropTypes, the props are undefined on the first render, and a warning is output to the console because of this. 
The same problem happens on all other custom components.  This is causing us some linting issues.  Is there a proper way to get around this?

**Comment by boygirl** [comment]
@splawndive Victory will prioritize props set on primitive components like `Line` rather than overriding them, which is why setting default props on these components won't work as you want. We're also making extensive use of `cloneElement` which may be causing the `undefined` values on the first render. I'll look into that part, but for now, are you opposed to dropping the "required" from your PropTypes?

**Comment by splawndive** [comment]
Hey, thanks for the response.  I'm perfectly okay with not using required props right now, the temporary solution we have to pass linting is to set each default prop to undefined.  Totally just feels wrong but hey, everything's working hah.  

I'm still a little bit confused about  
> Victory will prioritize props set on primitive components like Line rather than overriding them

I console.log some of the props coming into a custom component that I made called `CustomTick` that gets passed to the VictoryAxis component as its `tickComponent` prop, and when that custom component has the default prop for the "y1" (or any of the other x-y coordinate props), all of the ticks along the y-axis get rendered at the top of the svg.

**Comment by walshie4** [comment]
👋 any movement here?

**Comment by becca-bailey** [comment]
I'm going to close this for now since we are working on some larger issues around state management and props that will most likely fix this issue.
