### ISSUE TITLE
Strange visualization in 

### ISSUE THREAD

**Issue by arpetti** [FormidableLabs/victory#563]
I'm using [html2canvas](https://github.com/niklasvh/html2canvas) to print a bar graph, but the result is not properly rendered, with grid, axis and labels duplicated.

![screen shot 2017-04-16 at 21 31 45](https://cloud.githubusercontent.com/assets/3751374/25075481/265608c4-22ec-11e7-89ce-df9d43d3785c.png)

The implementation of the graph is as follow:

`<VictoryChart
          animate={{ duration: 2000, easing: "linear" }}
          theme={VictoryTheme.material}
          domainPadding={20}
        >
          <VictoryAxis
            label="Faixas de Notas"
            tickValues={[0, 1, 2, 3, 4, 5]}
            tickFormat={["0", "40", "80", "120", "160", "200"]}
            style={{
              axisLabel: { fontSize: 12, padding: 30, fill: "grey" },
              ticks: { stroke: "grey" },
              tickLabels: { fontSize: 12, padding: 5 }
            }}
          />
          <VictoryAxis
            label="Alunos"
            dependentAxis
            style={{
              axisLabel: { fontSize: 12, padding: 35, fill: "grey" },
              ticks: { stroke: "grey" },
              tickLabels: { fontSize: 12, padding: 10 }
            }}
          />
          <VictoryBar
            labelComponent={
              <VictoryTooltip
                cornerRadius={2}
                pointerLength={5}
                flyoutStyle={{
                  stroke: "tomato"
                }}
              />
            }
            data={data.statistics.hst.y_axis[this.props.data.prop]}
            labels={data.statistics.hst.y_axis[this.props.data.prop]}
            style={{ data: { width: 15 }, labels: { fontSize: 12 } }}
            events={[
              {
                target: "data",
                eventHandlers: {
                  onMouseOver: () => {
                    return [
                      {
                        target: "data",
                        mutation: () => ({
                          style: { fill: "tomato", width: 15 }
                        })
                      },
                      {
                        target: "labels",
                        mutation: () => ({ active: true })
                      }
                    ];
                  },
                  onMouseOut: () => {
                    return [
                      {
                        target: "data",
                        mutation: () => {}
                      },
                      {
                        target: "labels",
                        mutation: () => ({ active: false })
                      }
                    ];
                  }
                }
              }
            ]}
          />
        </VictoryChart>`

Any suggestion?

**Comment by boygirl** [comment]
@arpetti This is a guess, but you might have better luck if you make your chart non-responsive. You can do this by adding `containerComponent={<VictoryContainer responsive={false}/>}` to `VictoryChart`. You cal also try turning off the animation. Let me know if that helps.

**Comment by arpetti** [comment]
@boygirl thank you for your reply. 

I followed your suggestions, but without chance. The graph is rendered even worst. 

![screen shot 2017-04-21 at 11 03 54](https://cloud.githubusercontent.com/assets/3751374/25281131/c48faa1a-2682-11e7-8aa7-3fc4cb2daf72.png)
I've tried all the combinations with and without Container, Animations, Responsiveness, Themes, but the result doesn't change.

**Comment by boygirl** [comment]
@arpetti I'm really sorry this isn't working for you. It looks like multiple slightly different renders are being captured. This might have something to do with Victory's use of `cloneElement` to alter chart children. You might try to tie your capture to a later react lifecycle method like `componentDidMount` or set a timeout in your html2canvas options.
