### ISSUE TITLE
Categories are not working properly with horizontal stacked bars

### ISSUE THREAD

**Issue by acarl** [FormidableLabs/victory#565]
I am trying to build a horizontal bar chart and am having issues with the automatic calculation of tickValues for the VictoryAxis.

Here is an image of the issue in question.
![chart-without-tick-values](https://cloud.githubusercontent.com/assets/3051619/25091636/328c9b0a-2358-11e7-99e9-67db672a6727.png)

Clearly I am having an issue telling Victory which dataset to use for the automatic calculation of the tickValues, but I am not sure how to correctly change it.

Below is a simplification of the code I am using.

``` jsx
var React = require('react');
var VictoryBar = require('victory').VictoryBar;
var VictoryChart = require('victory').VictoryChart;
var VictoryAxis = require('victory').VictoryAxis;
var VictoryStack = require('victory').VictoryStack;

var StackedTest = function(props) {

  var data = [
    {
      user: 'John',
      apples: 50,
      oranges: 10
    },
    {
      user: 'Jane',
      apples: 5,
      oranges: 20
    }
  ];

  return (
    <VictoryChart domainPadding={20}>

      <VictoryAxis />
      <VictoryAxis dependentAxis />

      <VictoryStack
        horizontal={true}
        categories={data.map(function(datum) {return datum.user})}
        >

        <VictoryBar
          horizontal={true}
          data={data}
          x="user"
          y="apples"
          />

        <VictoryBar
          horizontal={true}
          data={data}
          x="user"
          y="oranges"
          />

      </VictoryStack>

    </VictoryChart>

  );

};

module.exports = StackedTest;
```

I was able to get it working by hard coding the tick values.
``` jsx
<VictoryAxis tickValues={[20, 40, 60]} />
<VictoryAxis dependentAxis />
```
![chart-with-tick-values](https://cloud.githubusercontent.com/assets/3051619/25091752/b5c9f530-2358-11e7-9e71-0084b7ab6e16.png)

Is there an easier way to do this or something I am missing in the definition of VictoryAxis? I really don't want to have to dynamically calculate the tick values outside of Victory for every chart.

**Comment by boygirl** [comment]
@acarl `categories` should be given as an object with `x` and `y`. https://jsfiddle.net/boygirl/5ohsfz6c/

However, it does look like there's a bug with horizontal data with categories. I will change the title of this issue to reflect that.

**Comment by acarl** [comment]
Thanks! I can see the bug you are talking about when I change your example to a horizontal bar chart.
https://jsfiddle.net/5ohsfz6c/2/
It only shows data for John.

I didn't realize you needed to specify categories as an object. The example given in the documentation has an array of strings.
https://formidable.com/open-source/victory/docs/victory-stack/#categories

In the mean time would you recommend I calculate the tickValues manually or is there a better workaround before a bug fix?

**Comment by boygirl** [comment]
@acarl you can do something like this in the meantime: https://jsfiddle.net/boygirl/5ohsfz6c/3/

I'll open an issue in our docs repo to fix the issue you mention.

**Comment by acarl** [comment]
That should work nicely. Thanks for your help.

**Comment by aleksey-shmatov** [comment]
This bug is still there but I am not able to access fiddle with workaround, can you repost it please?

**Comment by acarl** [comment]
I see the same issue with the JSFiddle. Here is a working version based on my first example. I can't remember if this was different from the JSFiddle, but it works.

``` jsx
var React = require('react');
var VictoryBar = require('victory').VictoryBar;
var VictoryChart = require('victory').VictoryChart;
var VictoryAxis = require('victory').VictoryAxis;
var VictoryStack = require('victory').VictoryStack;

var StackedTest = function(props) {

  var data = [
    {
      user: 'John',
      apples: 50,
      oranges: 10
    },
    {
      user: 'Jane',
      apples: 5,
      oranges: 20
    }
  ];

  return (
    <VictoryChart domainPadding={20}>

      <VictoryAxis
        tickFormat={function(tick) {return tick}}
        />

      <VictoryStack horizontal>

        <VictoryBar
          data={data}
          x="user"
          y="apples"
        />

        <VictoryBar
          data={data}
          x="user"
          y="oranges"
        />

      </VictoryStack>

      <VictoryAxis
        dependentAxis
        tickValues={[1, 2]}
        tickFormat={['John','Jane']}
        />


    </VictoryChart>

  );

};

module.exports = StackedTest;
```

**Comment by sibelius** [comment]
we should use https://codesandbox.io/ instead of `jsfiddle`

**Comment by boygirl** [comment]
I believe this is fixed in the latest version, so I'm going to close this issue.
