### ISSUE TITLE
Duplicate key bug when using createContainer

### ISSUE THREAD

**Issue by zsherman** [FormidableLabs/victory#566]
I'm using `createContainer` to combine voronoi and zoom functionality but I'm seeing a duplicate key issue when combining multiple charts which causes only the first to be rendered.

Here's the warning:

```
warning.js:36 Warning: flattenChildren(...): Encountered two children with the same key, `.$events-chart`. Child keys must be unique; when two children share a key, only the first child will be used.
```

And here's a shot of the component tree (notice the duplicated `area-area-parent` keys):

![screenshot 2017-04-18 15 28 34](https://cloud.githubusercontent.com/assets/1152279/25149296/e86f3f06-244b-11e7-94d6-1eb8cd3eb197.png)

**Comment by rodrigooler** [comment]
@zsherman I am having the same problem.

![screen shot 2017-04-19 at 12 59 41 pm](https://cloud.githubusercontent.com/assets/5496931/25189632/18f4a2e2-2500-11e7-9311-414b3dc6d8a0.png)

**Comment by chrisbolin** [comment]
Thanks so much for reporting this! I'll look into it later today

**Comment by chrisbolin** [comment]
@rodrigooler @zsherman i'm still struggling to reproduce this. what is the hierarchy of your chart? e.g. in the `create-container-demo.js` https://github.com/FormidableLabs/victory-chart/blob/master/demo/components/create-container-demo.js I have four different charts that mix and match children:

- VictoryChart
  - VictoryLine
  - VictoryLine
  - VictoryLine

- VictoryChart
  - VictoryGroup
    - VictoryLine
    - VictoryScatter

- VictoryChart
  - VictoryGroup
    - VictoryScatter
    - VictoryScatter

- VictoryStack
  - VictoryBar
  - VictoryBar
  - VictoryBar

**Comment by chrisbolin** [comment]
also, is the `victory-chart` version you have `18.2.1` or `18.2.0`. we made a pretty big change to the `createContainer` internals between those two; if you can test against `18.2.1` that'd be 💯 

sorry for the hassle!

**Comment by chrisbolin** [comment]
are you using events? if so, could you list those out too? i think the event creation process might be what's causing the duplicate keys (and my demos didn't have custom events, so I wouldn't have caught the same error)

**Comment by zsherman** [comment]
hey @chrisbolin I'll see if I can reproduce with `18.2.1`, if memory serves it was specifically the combination of voronoi and zoom that caused the issue, something like:

`createContainer('voronoi', 'zoom')`

**Comment by chrisbolin** [comment]
thanks @zsherman! If you are comfortable sharing, I'd love to see as much of your code as possible. It's sometimes hard to reverse-engineer from the React debugger :P And if you'd rather share it privately you can email me at `chris.bolin@formidable.com`

**Comment by boygirl** [comment]
@chrisbolin were you able to reproduce this issue?

**Comment by chrisbolin** [comment]
@boygirl i wasn't. but because both @zsherman and @rodrigooler there has to be something there...
