### ISSUE TITLE
Failed prop type: domainPadding

### ISSUE THREAD

**Issue by BrRenat** [FormidableLabs/victory#567]
Failed prop type: Invalid prop `domainPadding` supplied to `VictoryChart`.
```
<VictoryChart
      height={200}
      theme={VictoryTheme.material}
      padding={20}
      domainPadding={{
        x: [5, 5],
        y: [0, 10],
      }}
      containerComponent={
        <VictoryVoronoiContainer />
      }
>
....
</VictoryChart>
```

**Comment by sto3psl** [comment]
This is working fine for me ([fiddle](https://jsfiddle.net/5g20p8vd/243/)). Could you write which victory version you are using? Maybe a jsfiddle would help to reproduce your problem.

**Comment by BrRenat** [comment]
victory version "0.18.4"
victory-chart version "18.2.0"

**Comment by joshuahenson** [comment]
It looks like that's caused by having duplicate numbers in the array.
Does changing `x: [5, 5]` to `x: 5` accomplish what you are looking for?
