### ISSUE TITLE
audit tags / npm versions

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#57]
make sure there is a tag for every version

**Comment by boygirl** [comment]
npm versions: `[ '0.0.1', '0.0.2' ]`

tags: `v0.0.2`

missing tags: `v0.0.1`

**Comment by cpb** [comment]
This one is little harder than FormidableLabs/victory-pie#23 ... Ross starts the repo on July 16, but 0.0.1 is published on July 7th. That said, 0.0.2 isn't published until November.

Should the august work be included in the 0.0.1 tag? or just the init commit 6c3072765e3029263eb0d9f4d2b5b65dbbc2f072 ?
