### ISSUE TITLE
How to center graph within container? (VictoryChart & VictoryLines within VictoryZoomContainer)

### ISSUE THREAD

**Issue by c0d3ster** [FormidableLabs/victory#570]
As far as I can tell from the documentation, there is no way to adjust the position of your chart within the container component, and this is an issue for the spacing of my label.  I would like my graph to be centered rather than shoved to the left of the svg container.

The documentation on layouts states: 

> The  width and height props determine the width and height of the containing svg. By default VictoryContainer renders responsive containers with the viewBox attribute set to viewBox="0, 0, width, height" and width="100%", height="auto"

however, there seems to be no way to edit the two 0 values in the viewBox for x and y offset through props or styles.  If I am incorrect, please inform me of how I may do so! If not, I think this would be a great feature to have implemented because my label overlaps large number on the y-axis, and adding more padding pushes the label out of the graph area.

**Comment by boygirl** [comment]
@c0d3ster are you not able to achieve the result you want by adding asymmetric padding to your chart (_i.e._ `padding={{left: 50, right: 25}}`)? Maybe I'm missing something. I would definitely be willing to add an `offset` prop to `VictoryContainer` if necessary.

**Comment by c0d3ster** [comment]
@boygirl I can make the graph centered using asymmetric padding, but it'd be nice if there was a way to center the graph without having a block of empty space in the top and right.  It just looks a little odd because my graph is in a modal and the width of the modal extends into empty space.  I will likely leave it with asymmetric padding for now, but I still think control of the graph within the svg element would be a nice feature.
