### ISSUE TITLE
How to hide VictoryTooltip after mouse out

### ISSUE THREAD

**Issue by clopes-ventureoak** [FormidableLabs/victory#571]
https://jsfiddle.net/2zxnhL70/

I have a strange behaviour here, when i move out the mouse from the bars, the tooltip does not disappear, only disappears when another one is visible. Am i doing anything wrong here? How can I fix this?
Thanks

**Comment by boygirl** [comment]
@clopes-ventureoak thanks for the repro. Your code all looks correct. This looks like a bug on our end.

**Comment by njtrettel** [comment]
+1
@boygirl any updated status on this?

**Comment by jeradrose** [comment]
I also was wondering about this. Looks like even the examples on [the guide](http://formidable.com/open-source/victory/guides/tooltips) have the issue -- at least the ones not using a `VictoryVoronoiContainer`. A workaround I've found is to use a `VictoryVoronoiContainer`, but the downside to this, is that any part of tooltip that is outside of the chart, it gets cropped (if there's not enough padding).

**Comment by eddywashere** [comment]
From what I could tell, it looks like `VictoryPortal` is not updating. I added a `onMouseOut` event to log the props and I can see that active is false for `labels` but `VictoryPortal` doesn't pick up the change.

Workaround: I'm able to get around this by adding a ref to the container in VictoryChart `containerComponent={<VictoryContainer ref={this.saveContainerRef} />}`, then calling `this.containerRef.portalRef.forceUpdate()` when needed (onMouseOut event).

**Comment by jeradrose** [comment]
@eddywashere's solution worked for me.

**Comment by MartinMattyZahradnik** [comment]
I agree with eddywashere that `VictoryPortal` is not updating. For me was the solution to use `this.forceupdate(`). I am not happy to do this but for now seems to be easiest solution. Give it a try maybe it will save you a lot of headache :)

`onMouseOut: () => [
              {
                target: 'data',
                mutation: () => {},
              },
              {
                target: 'labels',
                mutation: () => {
                  this.forceUpdate();
                  return { active: false };
                }
              },
            ],`

**Comment by sindhu465** [comment]
Could you please elaborate how to do it 
I need it immediately

**Comment by sindhu465** [comment]
have a strange behaviour here, when i move out the mouse from the bars, the tooltip does not disappear, only disappears when another one is visible.

Could you please help me how to disappear the tooltip on mouseout??
