### ISSUE TITLE
Add y0 data accessor prop to components with baselines (VictoryArea and VictoryBar) 

### ISSUE THREAD

**Issue by tijp** [FormidableLabs/victory#581]
Currently I'm researching what charting library would be most suitable for our application and this library looks very promising.

We have a use case where we need to create a Range Area with min and max values together with a line chart that shows the average. It looks something like the image below.
![image](https://cloud.githubusercontent.com/assets/9055401/25847346/1208696c-34b6-11e7-9aa5-6131cac3fd1c.png)

Is it possible to create Range Area charts with Victory?
Thanks!

**Comment by mindjuice** [comment]
You should be able to achieve a channel with `<VictoryStack>` and two `<VictoryArea>`s.  Set the fill of the bottom area to transparent.

**Comment by boygirl** [comment]
Here's a fiddle :)
https://jsfiddle.net/boygirl/tL01p8b1/

**Comment by mindjuice** [comment]
Cool, that's even simpler.  The `_y0`  bit seems like something you just have to know from the source code though.  I don't see any mention of it in the docs for `VictoryArea`.  I found it in `victory-core/src/victory-primitives/area.js`.  Should it be documented?

Side note: I'm just getting started on a new project which will use Victory quite heavily -- love what you've created so far!

**Comment by tijp** [comment]
Thank you both, looks very good!
Also I agree with @mindjuice (and his side note 😃 )

**Comment by boygirl** [comment]
@tijp @mindjuice you're right, this should be a lot easier to do. I've re-opened this issue as "add y0 data accessor prop for components with baselines"
