### ISSUE TITLE
Automatic bar widths

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#586]
from @Thom1729
```
function barWidths(N, space) {
    const unit = 1/(N+1);
    const barFraction = 1/(space+1);
    return {
        barWidth: unit*barFraction,
        barSpacing: unit*(1 - barFraction),
        domainPadding: unit*(1 - barFraction/2),
    };
}

const { barWidth, domainPadding } = barWidths(myDomainValues.length, 1/4);

<VictoryChart
    height={height}
    width={width}

    domainPadding={{x: width*domainPadding }}
>
    <VictoryBar
        data={ myData }
        style={{ data: { width: width*barWidth } }}
    />
</VictoryChart>
```

**Comment by Thom1729** [comment]
Note: the implementation above takes in a single proportion parameter, `space`, which is the ratio of space to bar width. For example, if space = `1/3`, then the padding between and around bars will be one third of the bar width. Some similar computations (such as `d3Scale.scaleBand`) would produce that same output with an input of `1/4`, which is interpreted as padding / ( bar width + padding ). Personally, I prefer the former approach, but reasonable people may differ.

Expanding that former approach, this might be a nicer interface:

```js
function barWidths(N, {
    bar=1,
    padding=1,
    innerPadding=null,
    outerPadding=null,
}) {
    const inner = innerPadding !== null ? innerPadding : padding;
    const outer = outerPadding !== null ? outerPadding : padding;
    const total = N*bar + (N-1)*(inner) + 2*(outer);

    return {
        barWidth: bar/total,
        barSpacing: inner/total,
        domainPadding: (outer + bar/2)/total,
    };
}

const { barWidth, domainPadding } = barWidths(myDomainValues.length, { padding: 1/4 });
// Equivalent to:
const { barWidth, domainPadding } = barWidths(myDomainValues.length, { bar: 4 });
```

It might not even be that much more complicated to just use the full CSS Flexbox algorithm, providing the equivalent of `flex-basis` and `flex-grow`. Supporting pixel values would also be nice, allowing for instance bars that stretch to width and are always separated by 1px.

As far as integration, one idea would be to have a `layoutStrategy` attribute:

```js
<VictoryBar={ myData } layoutStrategy={{x: BarLayout({ padding: 1, bar: 4 }) }}/>
```

`VictoryBar` could take the computed width and padding values, multiply them by its own width, and use them as defaults for its `style` and `domainPadding`. This sort of injection would allow users to implement a wide variety of "easy-button" layout strategies without cluttering up the core, almost like enhanced theming.

Also, there is a bug in my original example. The `width` value there referred to the width of the entire chart. However, we actually need the width of the cartesian area, excluding the axes and any padding. Offhand, I'm not sure how to compute this simply and automatically. It might be easier in an internal implementation.

**Comment by boygirl** [comment]
After thinking more about this, I think this makes most sense as something external to Victory. It will otherwise be complicated to implement because it needs to alter `domainPadding` as well as bar width, which is typically under the control of VictoryChart. I'm not keen on mixing bar specific logic into the VictoryChart wrapper. I think instead, I will turn this idea into an example for the docs.
