### ISSUE TITLE
Improve basic documentation

### ISSUE THREAD

**Issue by BrodaNoel** [FormidableLabs/victory#589]
Hi all.

I guess you should add a "Charts" page, that show a thumbnail for each Chart, and a link for each of them.

For example, I don't know what is a https://formidable.com/open-source/victory/docs/victory-candlestick/, and will be really helpful to have a picture of this.
One page with all graphs so it's easier to find what I'm looking for.

**Comment by boygirl** [comment]
@BrodaNoel we're already in the middle of a big docs overhaul, and we've added a gallery. We're finishing up content, but it should be deployed some time next week.
