### ISSUE TITLE
Bug in Material theme

### ISSUE THREAD

**Issue by BrodaNoel** [FormidableLabs/victory#590]
Hi guys!.

Check those colors lines (Legend is OK):
<img width="524" alt="screen shot 2017-05-16 at 2 20 08 am" src="https://cloud.githubusercontent.com/assets/1837969/26090921/4524f126-39de-11e7-970d-311bf37e1308.png">

This is the code:
```
              <VictoryChart theme={VictoryTheme.material}>

                <VictoryLine
                  data={this.data}/>

                <VictoryLine
                  data={this.data2}/>

                <VictoryLegend
                  data={[{ name: 'Retweets' }, { name: 'Favorites' }]}/>
              </VictoryChart>
```

If I add `theme={VictoryTheme.material}` in the VictoryLine, the issue still there.

**Comment by boygirl** [comment]
@BrodaNoel I think this is actually an issue with VictoryStack / VictoryGroup. It looks like the `colorScale` defined in the theme is being used only for fills and not for strokes.

**Comment by BrodaNoel** [comment]
Could it be a bug in the Theme, instead of the components?

**Comment by ch3rn0v** [comment]
@BrodaNoel I think wrapping VictoryLine components in a VictoryStack component should work. For example please consider this fiddle: https://jsfiddle.net/ch3rn0v/7cgkt94r/2/ .
P. S. I'm new to the Victory library, so I can't guarantee that this is a proper solution.
