### ISSUE TITLE
victory-chart npm start warning

### ISSUE THREAD

**Issue by dishui** [FormidableLabs/victory#594]
when running npm start, I get the following in the console:

WARNING in ./~/enzyme/build/react-compat.js
Module not found: Error: Cannot resolve module 'react-test-renderer/shallow' in /Users/vn0ibsb/development/formidablelabs/victory-chart/node_modules/enzyme/build
 @ ./~/enzyme/build/react-compat.js 134:33-71
webpack: Compiled with warnings.

**Comment by chrisbolin** [comment]
with a fresh `npm install` on `master`, I cannot reproduce this.
