### ISSUE TITLE
Animating line charts don't render in Microsoft Edge 40.15063.0.0

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#598]
Issue and reproduction from @slavasitnikov
https://jsfiddle.net/q4Lvfr95/

**Comment by kumarharsh** [comment]
Seems to be working fine for me:

![image](https://cloud.githubusercontent.com/assets/760112/26548424/bd1c3cf8-4491-11e7-9d80-df53326e2a9a.png)

**Comment by boygirl** [comment]
Thanks!
