### ISSUE TITLE
prevent scaling of text font size on tooltip label

### ISSUE THREAD

**Issue by danfernand** [FormidableLabs/victory#601]
Hi, love victory. I have a question on the font size of labels in tooltips.

Is there a way for them not to be subject to viewBox resizing. Small visualizations end up with really small font size.

This is also a question for visualizations that are large, font size keeps on getting bigger.

There is a d3 solution for this - https://bl.ocks.org/veltman/5cd1ba0b3c623e7b5146

Thanks for all your help!

**Comment by boygirl** [comment]
@danfernand unfortunately this is a problem with how SVG scales text generally. I recommend adapting the example you mention. You can add a resize handler to your window, and update the `fontSize` in your axis label styles when it fires. Unfortunately this is not something that will be included in Victory.
