### ISSUE TITLE
How to test Victory Chart using Jest?

### ISSUE THREAD

**Issue by dinnayu** [FormidableLabs/victory#603]
When I try using Jest for unit test, I got this error:

/node_modules/victory-native/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import {
 ^^^^^^
    SyntaxError: Unexpected token import

Is there any suggestion for this?

**Comment by mindjuice** [comment]
`import` is not supported by ES5, so it sounds like you don't have Jest configured to convert your ES6 to ES5 (or TypeScript to ES5 if you're using that).

See here for configuring Jest to work with Babel: https://facebook.github.io/jest/docs/getting-started.html#using-babel

**Comment by boygirl** [comment]
see also: https://github.com/FormidableLabs/victory#jest-snapshots

**Comment by gre** [comment]
you can fix it by using `transformIgnorePatterns` config

example

```
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!victory-native)/"
    ]
  },
```
