### ISSUE TITLE
Domain padding is not working for bar charts with single data point

### ISSUE THREAD

**Issue by kumarharsh** [FormidableLabs/victory#604]
It seems like the `domainPadding` property is being completely ignored when there is only one bar in the chart. This causes the solo bar in the chart to stick out of the bounds of the chart's y-axis.

![image](https://cloud.githubusercontent.com/assets/760112/26548317/2f760078-4491-11e7-972a-739c0204ec62.png)

Here is a small reproducible sample to highlight the issue:
https://jsfiddle.net/yjjr4wb9/3/

**Comment by boygirl** [comment]
I believe this was fixed in the latest release (0.21.3)
