### ISSUE TITLE
0.19.0 breaks brushing

### ISSUE THREAD

**Issue by tehwalris** [FormidableLabs/victory#607]
The example provided in the [brushing demo](https://formidable.com/open-source/victory/guides/brush-and-zoom/) does not work correctly in Victory 0.19.0 and 0.20.0, but is fine in 0.18.0.

Specifically, when resizing the brush area to be wider, if you move the mouse too fast, it will stop brushing (as if you had released the mouse button). If you move the mouse very slowly this works fine.

I noticed that Victory draws two nested `<svg>` elements (with identical props) instead of one in the bad versions. I haven't investigated further.

**Comment by chrisbolin** [comment]
thanks @tehwalris! i can see this, too. we'll check it out 👍

**Comment by chrisbolin** [comment]
fixed it. PR https://github.com/FormidableLabs/victory-chart/pull/475. look for it in a release in the near future.
