### ISSUE TITLE
VictoryLine graph is not applying the theme.

### ISSUE THREAD

**Issue by Domthegrom** [FormidableLabs/victory#617]
I took the grayScale theme and modified it with new colors and created a file named `theme.js` and I grab that new theme as  `theme={Theme}`. It works perfectly find for my VictoryPie chart but the customized theme won't apply to my VictoryLine chart? Any idea why it may not be applying properly. Here is the modified `Line theme` and `Pie theme` code: https://gist.github.com/Domthegrom/86192dadd67978be8403020db1479d44  the new colors:`const colors = ["#1bc98e", "#1ca8dd"];` this is how it looks in my `line.js` file:
```jsx
<VictoryChart>
    <VictoryLine
      containerComponent={<VictoryContainer title={title} />}
      theme={Theme}
      width={Dimensions.get("window").width / 2}
      padding={15}
      labelRadius={40}
      labelComponent={
        <VictoryLabel
          textAnchor="middle"
          verticalAnchor="start"
          style={{ fontSize: 10 }}
        />
      }
      {...props}
    />
  </VictoryChart>;
```

![screen shot 2017-06-09 at 11 53 26 am](https://user-images.githubusercontent.com/23178405/26983597-53592ac0-4d0a-11e7-8510-387209b17f56.png)

**Comment by chrisbolin** [comment]
hey @Domthegrom! The VictoryLine's line color is defined here in your styles:
```jsx
style: {
        data: {
          fill: "transparent",
          stroke: charcoal, // <-------
          strokeWidth: 2,
        },
...
```

Note that the line uses `stroke`, not `colorScale`.
