### ISSUE TITLE
Default Animations Not Overridable + y Exit animations not working

### ISSUE THREAD

**Issue by browniefed** [FormidableLabs/victory#618]
If you take a look at the second demo here http://formidable.com/open-source/victory/guides/animations the returning of `y: 0` from `before` no longer animates the bar away. It just modifies the style and that's it.

Returning `_y: 0` will cause the bar to animate away.

I assume this was an unintentional change?

Additionally specifying something like `animate={{duration: 100}}` will subsequently only effect `onExit` and `onEnter` it doesn't effect `onLoad` animations.

I've experienced most of these through `victory-native` however it seems they are effecting the web version as well.

**Comment by boygirl** [comment]
So, this one is a little awkward. This step is happening after data processing. Actual rendered elements are altered by the ~private data variables `_x`, `_y` etc. which we create from the data accessor props and the data object. We never alter incoming user data `x`, `y` etc. I will update the docs to reflect this. Sorry for the confusion.

**Comment by browniefed** [comment]
Thanks. Just curious if this was due to an update recently?
Also I assume returning `_y` private overrides will continue to be the accepted way of animating via mutations?

Asking since I was developing some screencasts for `victory-native` and had to stop as I what I was noticing this issue that didn't align with the docs.

**Comment by boygirl** [comment]
Yes, unfortunately I think returning private overrides will be how to define custom transitions. I know it's a little inelegant. This was a somewhat recent change, but the docs are also a bit behind.

**Comment by browniefed** [comment]
Sounds good, not an issue just don't want to develop videos and mislead people. Thanks for the info
