### ISSUE TITLE
Create `builder init` templates in `builder-victory-component`

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#62]
- file structure
- boilerplate
- docs boilerplate

Depends on https://github.com/formidablelabs/builder/issues/7 and https://github.com/FormidableLabs/victory/issues/49

**Comment by coopy** [comment]
See FormidableLabs/builder-react-component#33 and previous PRs with init stuff.

**Comment by boygirl** [comment]
With fewer repos, this no longer seems necessary.

**Comment by ryan-roemer** [comment]
While not this ticket, all end user boilerplate should be controlled by either `builder-init` or `denim` depending on the scenario.
