### ISSUE TITLE
Events on children prevent VictorySharedEvents from working

### ISSUE THREAD

**Issue by amaschas** [FormidableLabs/victory#621]
What I'm trying to do: create a chart with multiple line plots overlayed with multiple scatter plots that provide parts of a tooltip behavior. When a user hovers over a data point, a tooltip will appear with the values for all of the plots, and all of the scatter plots that share the X axis value will be visible. The way I've gone about this is to stick the scatter plots in a VictoryGroup, and use shared events to target all of the plots when onMouseOver triggers for one of them. I then add a VictoryTooltip with a custom flyout to each scatter plot.

The documentation doesn't really cover this scenario, so I'm not sure what the intended behavior here is. I have a VictorySharedEvents wrapper a series of VictoryScatter charts. I can successfully define events on the shared events wrapper and the mutations occur. However, as soon as I define additional events on any children, the shared events no longer happen. Configuring a tooltip on the children also kills an of the shared events.

[edit] Just discovered that if I change the shared event to an "onClick", it works, so it appears to be a collision on the "onMouseOver" event definition.

**Comment by boygirl** [comment]
Yes, `onMouseOver` and `onMouseOu`t are already defined on tooltips, and when you add these to a chart you need to be aware of how they will interact with the events you already have defined. Check out this guide on using tooltips with other events: https://formidable.com/open-source/victory/guides/tooltips#tooltips-with-other-events

A similar thing will be true for shared events and events on individual components. The individual component events will nuke events defined on VictorySharedEvents. The safest thing to do would be to define all of your events on the event prop for VictorySharedEvents. You can reference specific children by name if you need special events for only particular children. I'm going to close this issue, but let me know if you need help getting your dashboard working properly :)
