### ISSUE TITLE
[VictoryZoomContainer] - Don't preventDefault on scroll event when allowZoom={false}

### ISSUE THREAD

**Issue by ottis** [FormidableLabs/victory#622]
Hi There!

I've come across an issue with the VictoryZoomContainer (maybe an improvement rather than an issue). When using it with the flag allowZoom set to false i.e. stop manipulation via wheel events, it still traps the event by using evt.preventDefault(). The issue i'm hitting is I want to manipulate the zoom outside of the chart from another component but still allow a natural scrolling of the page.

My suggestion is to only preventDefault if allowZoom is enabled e.g.

```
onWheel: (evt, targetProps, eventKey, ctx) => { // eslint-disable-line max-params
        if (targetProps.allowZoom) {
          evt.preventDefault();
        }

        const mutations = ZoomHelpers.onWheel(evt, targetProps, eventKey, ctx);

        if (mutations.id !== this.wheelMutationId) { // eslint-disable-line
          this.wheelMutationId = mutations.id; // eslint-disable-line
          return mutations.mutations;
        }

        return undefined;
      }
```

If you are happy with this change i'll create a Pull Request. 

Cheers! 😄

**Comment by boygirl** [comment]
@ottis this looks like a PR I would happily approve :)

**Comment by ottis** [comment]
@boygirl PR created here https://github.com/FormidableLabs/victory-chart/pull/481 😄

**Comment by boygirl** [comment]
released!

**Comment by Hypnosphi** [comment]
Looks like this is an issue again with `33.1.1`
