### ISSUE TITLE
How to get onclick data with VictoryArea

### ISSUE THREAD

**Issue by jeradrose** [FormidableLabs/victory#623]
If I use `onclick` with `VictoryBar`, I'm able to get to the clicked bar's data via `props.data` and `props.key` (which returns the unique key of the item within `props.data`):

    <VictoryBar
        data={this.props.databaseLoadMetrics.map(metric => {
            return {
                x: new Date(metric.startTime),
                y: metric.totalCpuTimeMilliseconds
            }
        })}
        events={[{
            eventHandlers: {
                onClick: (event, props) => {
                    console.log(props);
                }
            }
        }]}
    />

However, if I try to do this with a `VictoryLine` or `VictoryArea`, `props.key` always returns "all" which isn't helpful.

Do I need to do something else to access the clicked data point (and by data point, I'm referring to the same data point used on the tooltip with `VictoryVoronoiContainer` and `VictoryTooltip`)?

**Comment by boygirl** [comment]
@jeradrose yes, you should use `VictoryVoronoiContainer` to get this data when you are working with `VictoryLine` or `VictoryArea`. For these components, only one element is rendered for the entire data set, so only one event trigger exists, and you get the props that correspond to "all". Here's an example of using custom `onClick` events with `VictoryVoronoiContainer` https://jsfiddle.net/boygirl/r2hk38sd/

**Comment by jeradrose** [comment]
@boygirl that's what I was looking for. Thanks so much for the quick, helpful response!
