### ISSUE TITLE
VictoryBrushContainer selection handles are dropped when moving outside selection

### ISSUE THREAD

**Issue by jeradrose** [FormidableLabs/victory#625]
I've noticed that the `VictoryBrushContainer` has a bug, in that while you are resizing the selected area or moving it around, if you move to where the cursor is outside the selected area before it has a chance to catch up and redraw it, the selection handles are dropped.

This is particularly true when resizing, and doesn't take much to drop the handle, or when the resize handle is close to the edge of the selection window.

I don't believe it's browser specific, as I've been able to repro it on both Chrome 58 and Firefox 53 (on Windows 10, build 14393.1198).

Here is a repro of the [`VictoryBrushContainer` sample](https://formidable.com/open-source/victory/docs/victory-brush-container/).

![victorybrushcontainer-handlebug](https://user-images.githubusercontent.com/743963/27494995-3b5da314-581e-11e7-90dc-2935b9a8c853.gif)

**Comment by chrisbolin** [comment]
hey @jeradrose! that's for the heads up :) this was actually fixed very recently in `victory@0.21.0`, but our docs page is still at `victory@0.20.0` -- moving too fast :P

**Comment by chrisbolin** [comment]
you've encouraged me to move on the docs PR that upgrades the victory version. and also to ensure that the fix is documented in our Changelogs :)

**Comment by chrisbolin** [comment]
alright, if you reload the [VictoryBrushContainer sample](https://formidable.com/open-source/victory/docs/victory-brush-container/) things should behave properly. thanks again for the heads up, @jeradrose!
