### ISSUE TITLE
VictoryScatter does not add clip-path for domain

### ISSUE THREAD

**Issue by thurber** [FormidableLabs/victory#627]
First, thanks so much for the awesome library!

I've found that the `<VictoryScatter/>` component does not fully respect the `domain` property of itself or of a parent `<VictoryChart/>`, in that points will still be rendered outside the edges of the domain. By contrast, the `<VictoryLine/>` component utilizes a `clip-path` attribute on the rendered group to hide the path outside of the domain.

See for example the screenshot below. The `<g/>` element with `clip-path` is the `<VictoryLine/>`, while the very next `<g/>` element is the group of points for `<VictoryScatter/>` with no clip-path.

![image](https://user-images.githubusercontent.com/5023771/27595335-3fd2cf50-5b11-11e7-95d1-68b8c8e35beb.png)

**Comment by boygirl** [comment]
@thurber that is the default behavior for components like `VictoryScatter`. Only continuous data components like `VictoryLine` and `VictoryArea` render a clip-path by default. You can change this behavior by adding `groupComponent={<VictoryClipContainer/>}` to `VictoryScatter`. I'm going to close this issue for now, but let me know if that addition doesn't solve your specific problem.
