### ISSUE TITLE
VictoryAnimation Applies Animation to Incorrect Properties

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/victory#632]
Noticing a rendering issue where a string is rendered without a `0` if its located at the hundredths position. This is using the `VictoryScatter` component when passing an array of strings to the labels prop. Attached is a visual, will work on a repro as well as upgrading victory.

**Using VictoryScatter component from `Victory@0.19.0`**

![victory-label-bug](https://user-images.githubusercontent.com/1633837/27745326-c509d0a2-5d77-11e7-8d73-b9d443d1a327.gif)

![screen shot 2017-06-30 at 9 32 29 am](https://user-images.githubusercontent.com/1633837/27745332-c8b1417c-5d77-11e7-841f-d0fb815310aa.png)

Note the strings at position `4` and `9` are affected, indicating to me its only present when the value contains a `0` at the hundredths position.

**update**
I realized early on it's not the Label itself, but the props that are passed to `labelComponent`. VictoryAnimation appears to be modifying a value within `datum` that is should not be modifying

**Comment by kylecesmat** [comment]
Sorry for the mis-direction opening/closing. I thought this was something within my application but _something_ within victory is modifying this `datum.labelData.data` property...

The data prop passed to `VictoryScatter` looks like this:
![screen shot 2017-06-30 at 12 09 23 pm](https://user-images.githubusercontent.com/1633837/27750643-90c2b2c6-5d8d-11e7-9932-f583a8ed7d3e.png)

`VictoryScatter` is using `VictoryTooltip` as a `labelComponent`. Then, logging the props passed to the `labelComponent` on `VictoryTooltip`, I see this output:
![screen shot 2017-06-30 at 12 09 46 pm](https://user-images.githubusercontent.com/1633837/27750687-c0f746c8-5d8d-11e7-924e-21fc6dd10706.png)

**Comment by kylecesmat** [comment]
I traced this to animation being the culprit here... For some reason, when `VictoryScatter` had an animation set, the animation would modify `datum.labelData.data`. Which, because it was a string and not a number, resulted in some weird outcomes... I'm unable to get a reproduction going exactly, but if @boygirl or @chrisbolin want to pair I can show where the issue is happening.

I ended up seeing this when I logged the value of the `data` prop from when I passed it to `VictoryScatter`.

With the `animation` prop set on `VictoryScatter`:
![screen shot 2017-06-30 at 1 00 32 pm](https://user-images.githubusercontent.com/1633837/27752912-2c73e8e8-5d98-11e7-97cf-dab3fdc8b9e6.png)

Once I removed the animation prop:
![screen shot 2017-06-30 at 1 31 28 pm](https://user-images.githubusercontent.com/1633837/27752976-7c5a866e-5d98-11e7-96a4-96e664e19678.png)

**Comment by boygirl** [comment]
I believe this is a bug in how `d3-interpolate` deals with strings :/

**Comment by boygirl** [comment]
So we can change this line 
https://github.com/FormidableLabs/victory-core/blob/master/src/victory-animation/util.js#L17

and then force strings to numbers

**Comment by boygirl** [comment]
Or try to address the bug in d3: https://github.com/d3/d3-interpolate/blob/master/src/string.js

**Comment by boygirl** [comment]
I opened a bug in d3-interpolate: https://github.com/d3/d3-interpolate/issues/40

**Comment by chrisbolin** [comment]
this looks very similar to https://github.com/FormidableLabs/victory/issues/315 - should we just keep one of them open?

**Comment by boygirl** [comment]
yes, I think they are the same underlying issue. I think my preference would be to actually figure out how we want to solve this and create an issue around the solution and close and reference both of these.
The question is really whether we should:
a) write a custom string interpolator
b) stop trying to interpolate strings

**Comment by boygirl** [comment]
It will be necessary to manually format number strings that contain commas, but leading zeros will no longer be dropped

**Comment by kylecesmat** [comment]
Thanks @boygirl for the discussion and shedding light on the history of this issue. It makes sense to me that the leading zero issue is happening, because string interpolation is weird and _shouldnt be encouraged_.

In my eyes, the real issue is that thelabelData object was even being interpolated, but there seems to be history here where putting data/functions within the `data` prop is unsafe. I think @chrisbolin proposed a good solution here, so we'll track the outcome of this within our application and refactor how we are passing this `labelData` information if needed https://github.com/FormidableLabs/victory/issues/642

**Comment by boygirl** [comment]
@kylecesmat do you think we ought to turn off string interpolation all together rather than stripping commas prior to interpolation? I'm kind of leaning in that direction. 

Another proposed solution: 

We have a custom object interpolator already. We could apply different logic for what should be interpolated from inside an object. I have to check on what the consequences would be for style objects vs. data objects :/

**Comment by kylecesmat** [comment]
Turning off string interpolation would be a good _default_ I believe? It's unreliable to interpolate strings, we should specify that values must be numbers. I can't think of a use-case that would make transforming strings acceptable?
