### ISSUE TITLE
Threshold lines

### ISSUE THREAD

**Issue by jeradrose** [FormidableLabs/victory#633]
I have a `VitctoryBar` or `VictoryArea` graph, and am wondering if it's possible to add lines or background shading for various thresholds on the graph. I.e. if a bar exceeds Y, it exceeds the threashold.

Here's an example I grabbed off Google:

![vertical line](https://camo.githubusercontent.com/96a17081306ec1f86b45d9ecb3f1a0b5bd6532b4/687474703a2f2f7777772e6e61747572652e636f6d2f6e636c696d6174652f6a6f75726e616c2f76312f6e382f696d616765732f6e636c696d617465313236352d66312e6a7067)

**Comment by boygirl** [comment]
@jeradrose yep, you can add lines like those with `VictoryLine`

`<VictoryLine y={() => 50}/>` will be enough to create the line, The label is a little trickier. I suggest something like 

```
<VictoryLine 
  y={() => 50} 
  samples={1}
  labels={["", "50%"]}
  labelComponent={<VictoryLabel renderInPortal dx={20} dy={-20}/>}
  />
```
