### ISSUE TITLE
VictoryZoomContainer and negative data makes confusing x-axis

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory#635]
[Demo](https://jsfiddle.net/chrisbolin/3tc49693/)

![jul-03-2017 13-28-52 - zero axis](https://user-images.githubusercontent.com/2822048/27791162-046beca2-5ff4-11e7-933b-3defafc25871.gif)

By default, VictoryChart will make an axis at y=0 when data contains negative points. However, this is confusing when you zoom to a different location, as the axis doesn't move to stay with y=0.

**Comment by beccanelson** [comment]
This appears to have been fixed in a more recent release. 

https://codesandbox.io/s/elated-worker-l0u3y?file=/src/App.js
