### ISSUE TITLE
Vue version

### ISSUE THREAD

**Issue by nickmessing** [FormidableLabs/victory#636]
Since vue.js support JSX it should be not very hard to port Victory to it, is it okay if I will do that? Are you interested in keeping it under `FormidableLabs` organization?

**Comment by chrisbolin** [comment]
hey @nickmessing! as long as you follow victory's [MIT license](https://github.com/FormidableLabs/victory/blob/master/LICENSE.txt), have at it! We don't have a lot of VueJS expertise, so I'm not sure if we'd be the best place for a Vue port of Victory to live. But don't let that hold you back. Thanks for checking, and good luck -- oh, and let us know how it goes!
