### ISSUE TITLE
Having HTML code in data, makes chart crash when animate is on. 

### ISSUE THREAD

**Issue by vilrolf** [FormidableLabs/victory#638]
https://jsfiddle.net/p33zxf9a/

Having any HTML-code in data, crashes the chart if animation is on. 
`Cannot convert a Symbol value to a number`

**Comment by chrisbolin** [comment]
as a note, this relates in some ways to https://github.com/FormidableLabs/victory/issues/459; essentially, the `data` array isn't a safe place to keep arbitrary things

**Comment by boygirl** [comment]
Also note that Victory will try to interpolate any values stored on the data object during animation. Even if you stringify that bit of html, there's no guarantee that it will not be altered during animation (for instance, if the html string contains numbers). If you need bits of html tied to individual data elements, the better solution would be to store the html elsewhere, and keep some look up on the data object. I'm closing this issue as a wont fix, but please let us know if we can help you find a different solution
