### ISSUE TITLE
proposed: `dataKeys` prop

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory#642]
Victory manipulates the `data` prop in a few ways; e.g. calling functions in the data objects (#459), interpolating the values in the data objects (#632, #638), and trying to use arbitrary data as styles (#610).

A fix in User Land code might look like this:

```jsx
const complicatedData = [
  {x: 0, y: 17, label: <span>!</span>, func: () => alert()},
  ...
];

const dataKeys = ["x", "y"];
const cleanedData = complicatedData.map(d => _.pick(d, dataKeys));

<VictoryLine data={cleanedData}/>
```

We could instead do that filtering for the user if they so desired:

```jsx
<VictoryLine data={complicatedData} dataKeys={["x", "y"]}/>
```

Would that be a decent idea? Or is it too complicated a solution? (Or too small a problem?)

**Comment by chrisbolin** [comment]
Another approach might be whitelisting style attributes, and leaving the rest alone. See #610.

**Comment by beccanelson** [comment]
Since there hasn't been any discussion on this issue in a few years, I'm going to close this for now in an effort to clean up some of our older issues. Let me know if it needs to be re-opened!
