### ISSUE TITLE
Provide both x and y coordinate values to the onChange handler, irregardless of whether the dimension attribute is set or not

### ISSUE THREAD

**Issue by ch3rn0v** [FormidableLabs/victory#647]
Currently I don't see a way to track the `VictoryCursorContainer`'s current position when `dimension` is set.
For example, if `dimension="x"` is set, we can find out the cursor's current position in the x axis, but its position in the y axis is unknown.<br/>
I suggest to provide both x and y coordinate values to the `onChange` handler, irregardless of whether the `dimension` attribute is set or not.<br/>
<br/>
The origin of this issue is that I would like to move the label of the `VictoryCursorContainer`, changing its `cursorLabelOffset` value. But if I don't know it's `y` coordinate, I can't calculate the corresponding offset.<br/>
Please correct me if I'm wrong. Thank you.

**Comment by chrisbolin** [comment]
hey @ch3rn0v! author of the VictoryCursorContainer here. thanks so much for submitting this.

First off you are correct: `value` in the `onChange` handler is the same type as `defaultCursorValue`:

> The prop should be a point (an Object with x and y properties) for 2-dimensional cursors, or a number for 1-dimensional cursors.

(from the [docs](https://formidable.com/open-source/victory/docs/victory-cursor-container/))

It was an oversight that `onChange` is not better documented. I'll fix that!

We could do exactly as you and change the type of the value. I am slightly loath to do that straight away for two reasons: (1) it would be breaking change and (2) I want to understand your use-case more, because it might mean something more fundamental about VCC needs to change.

So in service to that, could you tell me more about what you'd like to do? How would you like to move the cursor's label? (i.e. would you like it to always be at the top or bottom?)

**Comment by ch3rn0v** [comment]
Hello @chrisbolin! Thanks for prompt response.
>I want to understand your use-case more

Let's take a look at this example: https://ch3rn0v.github.io/game-of-life/ (I only tested its appearance on Win10/Google Chrome latest/2560x1080, so may be buggy in other environments).

In the bottom right you can see a graph made with the help of your library. When I hover the graph near its top border, part of the label's text happens to be displayed outside of the graph. Same for the bottom border. And same was true for the horizontal offset untill I created this workaround: https://github.com/ch3rn0v/game-of-life/blob/master/src/Game/GameChart.js#L35 .

So the ideal solution for this particular case would be to dynamically calculate the label's offset in a way that will prevent the label to be moved away from the graph. Or produce warning that there is not enough space.
It's also interesting that if we move the label around it may happen to be slightly covered by the user cursor, so it would be great to make additional offset for such case (for devices with cursor).

Another possible solution is to provide the user with the neccessary data so that she/he would be able to decide what to do with it on her/his own.

>it would be breaking change

Regarding this part I also agree with your position and I wouldn't suggest this change unless there was a warning in the README file:

>Be prepared for breaking changes!

**Comment by chrisbolin** [comment]
thanks @ch3rn0v! I have an idea of a pretty painless solution. let me put something together

**Comment by chrisbolin** [comment]
@ch3rn0v check out https://jsfiddle.net/chrisbolin/zhars37g/

You can use (cursorLabelComponent)[https://formidable.com/open-source/victory/docs/victory-cursor-container/#cursorlabelcomponent] to precisely place the label. I think that'd be much more preferable than manipulating this label component.

**Comment by chrisbolin** [comment]
you could also make `y` static. i quite like the look of that: https://jsfiddle.net/chrisbolin/zhars37g/6/

also, you can hide mouse cursor just using css. i also did that in this demo ^

**Comment by chrisbolin** [comment]
(sorry for all the comments)

x and y in the label context are svg coordinates, not data coordinates. Which is really convenient, as you don't need to check for max/min data values.

**Comment by chrisbolin** [comment]
Going to close this for now for tracking purposes. Totally happy to reopen it if `cursorLabelComponent` doesn't provide a good solution!

**Comment by ch3rn0v** [comment]
@chrisbolin thank you for prompt response and live examples! `cursorLabelComponent` does provide the solution for my case. I even (mistakenly) thought that it's a new Victory component :)

I have one question though, if you don't mind.

>x and y in the label context are svg coordinates, not data coordinates. Which is really convenient, as you don't need to check for max/min data values.

I guess it is, yet in this particular case I would like to also have data coordinates. And since I don't know how to get them, I created this workaround:
_// return the object instead of just text:_
https://github.com/ch3rn0v/game-of-life/blob/master/src/Game/GameChart.js#L41
_// and parse it to get both text and data horizontal coordinate:_
https://github.com/ch3rn0v/game-of-life/blob/master/src/Game/GameChartCursorLabel.js#L6

Could you please tell if I'm doing this wrong? I'm also sorry if this is an inconvenient place to post this question.
