### ISSUE TITLE
"domainPadding" not working when "domain" is set

### ISSUE THREAD

**Issue by jonathanchu** [FormidableLabs/victory#648]
It seems that when setting an explicit `domain` the `domainPadding` prop is not respected anymore.  I've made a quick gif demonstrating this issue in a VictoryBar with the live demo:

![victory-charts-domain-and-domain-padding-issue](https://user-images.githubusercontent.com/66164/28138332-6e11c510-671e-11e7-8db1-95be1544d0c1.gif)

**Comment by sbcreates** [comment]
It seems this is still an issue, or at least I'm having the same problem (could be user error ;) but I figured I'd try to see what's going on here). I'm using Victory Charts version 24.5

The chart I'm making renders data based on the time range selected by the user along with whether they want to see transfers or transactions for that date range. 

The first image has the default date range (start of day to now) and it has no data as there were no transfers/transactions made. It has the right domain padding for the x axis only and doesn't show six ticks though six could fit nicely with the space given. 

If I click a date range where there is data to show, the domain padding is wrong (see second image)

The domain padding doesn't seem to do anything for the y axis. Even if I change my code to explicitly note the domain padding for the x and y.


![screen shot 2018-05-11 at 9 32 53 am](https://user-images.githubusercontent.com/30477884/39926836-6d994e68-54fe-11e8-93ee-c0d85924ca19.png)

![screen shot 2018-05-11 at 9 40 55 am](https://user-images.githubusercontent.com/30477884/39927200-78c006b4-54ff-11e8-8dce-22b2f6af0d4c.png)


```
  <VictoryChart
    height={320}
    width={470}
    name={chartName}
    scale={{ x: 'time', y: 'linear' }}
    domain={domain}
    domainPadding={{x: 35}}
    animate={{ duration: 1000, onLoad: { duration: 500 } }}
    containerComponent={<VictoryVoronoiContainer />}
  >
    <VictoryAxis
      // x-axis
      tickCount={6}
      tickFormat={(t) => formatLocalChartTicks(dateRange, t)}
      style={{
        axis: { stroke: 'rgba(36, 55, 78, 0.7)', strokeWidth: 1 },
        tickLabels: {
          fill: 'rgba(36, 55, 78, 0.7)',
          fontSize: 10,
          fontFamily: 'Lato, sans-serif',
          angle: 315,
          verticalAnchor: "middle",
          textAnchor:'end',
          padding: 4,
        },
        ticks: { size: 4, stroke: 'rgba(36, 55, 78, 0.7)', strokeWidth: 1 },
      }}
    />
    <VictoryAxis
      dependentAxis
      tickCount={6}
      tickFormat={(t) => t.toString()}
      style={{
        axis: { stroke: 'transparent', strokeWidth: 1 },
        grid: { stroke: '#ebecee', strokeWidth: 1 },
        tickLabels: {
          fill: 'rgba(36, 55, 78, 0.6)',
          fontSize: 9,
          fontFamily: 'Lato, sans-serif'
        },
        // ticks: { size: 5, stroke: 'rgba(36, 55, 78, 0.7)', strokeWidth: 1 },
      }}
    />
    <VictoryScatter
      size={(datum, active) => (active ? 5 : 2)}
      data={data}
      x={xValue}
      y={yValue}
      labelComponent={
        <VictoryTooltip
          style={{
            fontSize: 9,
            fill: 'rgba(36, 55, 78, 0.7)',
            fontFamily: 'Lato, sans-serif',
          }}
          cornerRadius={2}
          flyoutStyle={{
            fill: 'white',
            stroke: 'rgba(36, 55, 78, 0.7)',
            strokeWidth: 0.5
          }}
        />
      }
      {...props}
    />
  </VictoryChart>
```
