### ISSUE TITLE
Feature request: syncing with external interaction

### ISSUE THREAD

**Issue by chris-cooper** [FormidableLabs/victory#652]
Hi,

We're rendering a cross section line graph using victory chart alongside a 3D map view of the same cross section line.  We've been able to hack in an interaction such that when you hover over the chart the orange dot on the map updates to show the location referred to.  This is done by updating the dot within the label render function which is [implemented via a cursor](https://github.com/FormidableLabs/victory/issues/631).  What would be great is if we could have some hooks to provide 2 way interaction in a supported way e.g.

* provide callbacks for e.g. `onShowLabel()`, `onHideLabel()`, `onLabelUpdate()` (or something) so we can update the 3D map when the user moves in/out/over the chart.
* provide an external way of controlling the cursor label so when a user moves/hovers over the line on the 3D map the cursor moves on the victory chart accordingly

![peek 2017-07-14 07-46](https://user-images.githubusercontent.com/484870/28189928-c5458814-686b-11e7-8d65-03094bd8f882.gif)

**Comment by boygirl** [comment]
@chris-cooper 
`VictoryCursorContainer` has an `onChange` function that could accomplish this interaction (chart -> 3D map). There is also a `defaultCursorValue` prop that can be used to manually set the cursor value. You could update this prop in some event handler you would be calling from your 3D component.
