### ISSUE TITLE
Difficulties with overriding VictoryLabel

### ISSUE THREAD

**Issue by larseen** [FormidableLabs/victory#660]
Cant seem to override the `VictoryLabel` in `VictoryAxis`.

None of the props passed trough `axisLabelComponent={<VictoryLabel angel={22}/>}` is registered.

Example:
```
      <VictoryChart theme={VictoryTheme.material} domainPadding={{ x: 20 }}>
        <VictoryAxis
          scale="time"
          axisLabelComponent={<VictoryLabel angel={22}/>}
        />
        <VictoryAxis
          dependentAxis
          axisLabelComponent={<VictoryLabel angel={22}/>}
        />
        <VictoryBar
          scale="time"
          animate={{
            duration: 300,
            onLoad: { duration: 1000 },
            easing: 'back',
          }}
          style={{
            data: { stroke: '#c43a31', fill: '#B6F0FF' },
            parent: { border: '1px solid #ccc' },
          }}
          data={modifiedData}
        />
      </VictoryChart>
```

**Comment by boygirl** [comment]
You have a typo in your example. The prop should be `angle` not `angel`. I'm closing this issue for now, but I'll re-open it if your problem persists.

**Comment by jenessawhite** [comment]
@boygirl I actually am having the same issue (but with correct spelling)
`      <VictoryChart domainPadding={15}>
        <VictoryAxis
          style={ this.props.crossAxisStyles }
          axisLabelComponent={<VictoryLabel angle={22} />}
          animate={{
            duration: 2000,
            easing: "bounce"
          }}
        />
        <VictoryAxis dependentAxis
          style={ this.props.dependentAxisStyles }
        />
        <VictoryBar
          data={ this.props.data }
          style={this.props.barStyles}
        />
      </VictoryChart>`

**Comment by matthew-socialcore** [comment]
I'm having the same issue as well:



    <VictoryChart
        theme={VictoryTheme.material}>

        <VictoryLine
            data={graphData}
        />
        <VictoryAxis
            axisLabelComponent={<VictoryLabel dx={10} dy={20} />} />
        <VictoryAxis dependentAxis
            tickFormat={(t) => `${Math.round(t)}`}
        />
    </VictoryChart>

The `dx` and `dy` in my axisLabelComponent are not being respected.

**Comment by matthew-socialcore** [comment]
So it turns out I was using the wrong property: I was trying to customize the tick labels, but was using `axisLabelComponent`.

Using `tickLabelComponent` fixed my issue.

I only realised my mistake after finding this issue:
https://github.com/FormidableLabs/victory/issues/948

Basically, it seems for `axisLabelComponent` to do something, you need to specify the `label` property on your `VictoryAxis` component.
