### ISSUE TITLE
VictoryChart sorting data

### ISSUE THREAD

**Issue by SouroucheHF** [FormidableLabs/victory#661]
Hi guys,

I'm trying to make victoryChart working with a different sorting x axis than default.

Here is my dataset : 
`[{x: 3, y: 3000}, {x: 1, y: 1000}]`

But when I passed this data to victoryChart, it sort automatically the data to put the x=1 before everyone else and I just want the chart displaying the data like I serve them to it.

I've tried lot of combinations with sortKey props or custom charts but I can't figure it out.

Someone can help me please :) ?

Thanks.

**Comment by boygirl** [comment]
@SouroucheHF if you want to re-order the data, you could make all of your x values strings rather than numbers. Then Victory will treat it as categorical data, and respect the order that the data comes in.

**Comment by SouroucheHF** [comment]
Hi @boygirl, thank you verymuch for your quick response. Really mate, I appreciate.

But there is still something who diving me crazy. I can't figure out why when I feed the chart with strings, tickCount doesn't seem to work anymore.

It is a expected behavior ?

Thanks.
