### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by aaroncrawford** [FormidableLabs/victory#663]
Hi all - thanks for this great plugin and the work you put into it.

Browsing through the docs I found a couple errors :

1. [Link](https://formidable.com/open-source/victory/guides/tooltips/) : References VictoryVoronoiTooltip and links to a 404.  Maybe put in a note that it's deprecated and people should use the new container object?
2. [Link](https://formidable.com/open-source/victory/docs/victory-voronoi-container) : The labels example is singular, should be plural - example: label={(d) => "y: " + d.y}

Thanks again.

**Comment by boygirl** [comment]
@aaroncrawford thanks! I'm moving this issue to our docs repo.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#395
