### ISSUE TITLE
all lodash uniqueid executions just keep increasing on server-side

### ISSUE THREAD

**Issue by emattias** [FormidableLabs/victory#664]
I have a server side rendered app using next.js. When I output a simple graph:
```
    <VictoryChart>
      <VictoryLine />
    </VictoryChart>
```
 I get this error:

>warning.js?d2430c2:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ="victory-container-**1**-title victory-cont
 (server) ="victory-container-**4**-title victory-cont

The id that is different from the client and server just keeps increasing on the server for every re-render. I the id is generated [here](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-container/victory-container.js#L48) using the `uniqueId()` function from lodash. This problem probably exists in for every part of victory using `uniqueId()` in this way. This is a similar issue: https://github.com/FormidableLabs/victory/issues/613 It was solved by making it possible to provide the id instead using a prop. 

- Maybe all ids of this type in victory.js can be overriden with an id prop? 
- I haven't tried out server rendering victory js charts more that this yet. Is Victory developed with universal rendering in mind?

**Comment by boygirl** [comment]
@emattias thanks for this issue. I'll add an optional prop for setting a deterministic id.

**Comment by emattias** [comment]
@boygirl Sounds good, thanks! Do you see any other potential problems with server rendering victory charts?
