### ISSUE TITLE
[Discussion] ImmutableJS

### ISSUE THREAD

**Issue by ericschaal** [FormidableLabs/victory#668]
Hey!
Has anyone found a way to use an ImmutableJS List with Victory-*
(without using toJS conversions)

Thanks!

**Comment by ryan-roemer** [comment]
Can you help describe what changes we would need to make to Victory to support ImmutableJS without actually taking it as a dependency?

**Comment by ericschaal** [comment]
I'll try to make a pull request by the end of next week.

**Comment by ericschaal** [comment]
Hey,
From what I saw,
Most changes must be done in victory-core/victory-utils/data.js.
Giving a Immutable JS List to a Victory Component will fail in `getData(props)`  inside data.js when checking for the length of the data prop (`.size` must be used instead of `.length`). Also any `isArray` check should be adapted (check for `data.__proto__["@@__IMMUTABLE_LIST__@@"]`? ) in subsequent function calls. Finally, properties of Immutable DS must be accessed using `.get('propName')` or `.getIn('propName', 'propName1', ...) `instead of` .propName` or `.propName.propName1`.

**Comment by corradio** [comment]
Any news here?

**Comment by boygirl** [comment]
support for immutable data added in `victory@0.24.4`
