### ISSUE TITLE
Pie labels clipped by svg

### ISSUE THREAD

**Issue by ir-fuel** [FormidableLabs/victory#669]
This is the React code

```
          <VictoryPie
            colorScale={[mainColor, "#424242"]}
            style={{
              data: {stroke: "grey"},
              parent: {border: "none"}
            }}
            data={todayData}
          />
```

This is the generated html
```
<svg width="400" height="400" role="img" aria-labelledby="victory-container-2-title victory-container-2-desc" viewBox="0 0 400 400" overflow="visible" style="border: none;width: 100%;height: 100%;">
	<svg width="400" height="400" role="img" aria-labelledby="victory-container-2-title victory-container-2-desc" viewBox="0 0 400 400" style="border: none; width: 100%; height: 100%;">
		<g>
			<path d="M9.184850993605149e-15,-150A150,150,0,0,1,80.3167620933683,126.68550716967303L0,0Z" role="presentation" transform="translate(200, 200)" shape-rendering="auto" style="fill: rgb(235, 124, 92); stroke: grey; padding: 10px; stroke-width: 1;"/>
			<path d="M80.3167620933683,126.68550716967303A150,150,0,1,1,-2.7554552980815446e-14,-150L0,0Z" role="presentation" transform="translate(200, 200)" shape-rendering="auto" style="fill: rgb(66, 66, 66); stroke: grey; padding: 10px; stroke-width: 1;"/>
			<text dx="0" dy="4.97" x="363" y="153">
				<tspan x="363" dx="0" text-anchor="start" style="fill: rgb(37, 37, 37); font-size: 14px; font-family: &quot;Gill Sans&quot;, &quot;Gill Sans MT&quot;, Ser&#xAD;avek, &quot;Trebuchet MS&quot;, sans-serif; stroke: transparent; padding: 20px; letter-spacing: normal;">171 Reserved</tspan>
			</text>
			<text dx="0" dy="4.97" x="37" y="247">
				<tspan x="37" dx="0" text-anchor="end" style="fill: rgb(37, 37, 37); font-size: 14px; font-family: &quot;Gill Sans&quot;, &quot;Gill Sans MT&quot;, Ser&#xAD;avek, &quot;Trebuchet MS&quot;, sans-serif; stroke: transparent; padding: 20px; letter-spacing: normal;">246 Available</tspan>
			</text>
		</g>
	</svg>
	<g/>
</svg>
```

This is the generated image

<img width="457" alt="screen shot 2017-07-23 at 22 51 00" src="https://user-images.githubusercontent.com/1573715/28502755-ae65f526-6ff9-11e7-8cd7-d0fb820e4044.png">

Is it normal that the parent svg bounds don't take the labels into account?

**Comment by boygirl** [comment]
@ir-fuel the `padding` prop is something you can set manually to increase the space between your pie and the edges of the svg. If you'd like your labels to overflow the svg, you have a couple options:

1) Change parent styles: `style={{ parent: { overflow: "visible" } }}`
2) Render your pie labels in the portal `labelComponent={<VictoryLabel renderInPortal/>}`
(this will not work if you are using a non-victory `containerComponent` or setting `standalone={false}`)

**Comment by bgold0** [comment]
@boygirl is there anyway you can show an example of #2 for rendering in portal? I tried the following but it looks like my labels are still getting cut off.

	<VictoryPie
	    width={width}
	    height={height}
	    data={formattedData}
	    style={{ labels: { padding: 30 } }}
	    colorScale={['navy', 'orange', 'gold', 'tomato', '#DFE4EA']}
	    labelComponent={<VictoryLabel renderInPortal />}
	/>
