### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by janusch** [FormidableLabs/victory#67]
Great project, I am very much looking forward to see victory mature.

Right now there seems to be a problem with viewing the example pages in IE11 and FF42.

In IE11 a warning says: "Unsupported CSS property "size" in component "Victory Axis""

In FF42 within the playgroundPreview "Error: Invariant Violation: ReactCompositeComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object."

Which browsers are you planning to support?

Keep up the good work!

EDIT:
After investigating a little more, I can say that a bar chart with a couple of axis displays in IE11 just fine. 
Sadly Firefox does not display anything and throws with a `Type Error: 0 is read only`

**Comment by boygirl** [comment]
@janusch thanks for bringing this to our attention. We are hoping to support the usual: chrome, firefox, safari, opera, and IE9+ (maybe IE11+ given the recent news from microsoft). We have our work cut out for us!

Fortunately (unfortunately?) We're only seeing this problem with our docs tool [ecology](https://github.com/FormidableLabs/ecology).  The components themselves do work in Firefox (with a couple warts). I'll open an issue on Ecology to address this problem.

**Comment by janusch** [comment]
That sounds great!
Even though you write victory is in early alpha I have decided to use it for a bunch of relatively simple, in therms of interaction, graphs.

I'll keep reporting issues, if I think they can help you with the development.

Victory is such a fresh breath of air in for visualizations, after fiddling with either low-level d3 or complex abstractions like plotly.js

**Comment by mdramos** [comment]
Are there any known bugs in firefox? Currently the VictoryChart is not working for me (the Lines are bunched together to the left of the chart)

**Comment by janusch** [comment]
Hey @mdramos,
it works fine for me in firefox. If you have a gist or bin with your code I might be able to have a look. Does it show in the other browsers just fine?

**Comment by mdramos** [comment]
@janusch hey sorry, this was fixed with #123
