### ISSUE TITLE
Updating from 0.21.2 => 0.21.3, BIG fonts

### ISSUE THREAD

**Issue by jacargentina** [FormidableLabs/victory#675]
There is some breaking change on the fonts?

Attaching the screenshot
![very-big-font](https://user-images.githubusercontent.com/517228/28641288-18478cca-7225-11e7-8e83-4df29badef06.jpg)

The "datos" and "log" labes are very BIG!

**Comment by boygirl** [comment]
@jacargentina yes. `VictoryLegend` had inconsistent responsive styling with other victory components. `width: "100%", height: "100%"` was added to parent styles for `VIctoryLegend` in the last release. Your changes in font size can be corrected by altering parent styles or by turning off responsive behavior on VictoryLegend's containerComponent

**Comment by jacargentina** [comment]
@boygirl where is the migration path on the change log ?

![img_2384](https://user-images.githubusercontent.com/517228/28645850-5f433a1a-7235-11e7-98fd-37e8ab8468cf.PNG)

**Comment by boygirl** [comment]
You're right, it should be included under 272. I'll amend the log
