### ISSUE TITLE
Tooltip doesnt appear until a zoom is triggered+Error in debugger on mouse over (0.21.3)

### ISSUE THREAD

**Issue by prestond123** [FormidableLabs/victory#676]
Tooltip doesn't appear until a zoom is triggered.

This error apear in log on mouse over chart:
Uncaught TypeError: Cannot read property 'x' of undefined
at https://npmcdn.com/victory@0.21.3/dist/victory.min.js:1:202637

 _at victory.js:20458:130 in unminified_

(for props.dimension related to zoomDomain)

Fiddle here: https://jsfiddle.net/egksprb9/2/

**Comment by boygirl** [comment]
Fixed by https://github.com/FormidableLabs/victory-chart/pull/502
