### ISSUE TITLE
Text misaligned on left-oriented tooltip when using dy prop

### ISSUE THREAD

**Issue by zwright** [FormidableLabs/victory#680]
If I set the dy prop on a left-oriented VictoryToolTip, the tooltip text is not shifted with the rest of the container. I've attached a screenshot with dy set to 10, e.g.

<VictoryTooltip orientation={"left"} dx={10} dy={-10} />

![tooltip_text_problem](https://user-images.githubusercontent.com/1536965/28690392-0059ee92-72e7-11e7-942d-0b93768972db.png)

Thanks!

**Comment by boygirl** [comment]
I believe this issue is fixed in the latest version
