### ISSUE TITLE
Applying styles to victory label

### ISSUE THREAD

**Issue by shrynx** [FormidableLabs/victory#681]
i have small concern, 
from what i can gather from  
http://formidable.com/open-source/victory/docs/victory-label#style , 
it says if i provide style as an **object** then it will apply to `<text>` and if i give it as an **array of objects** it will be applied to each corresponding `<tspan>`

But in practice it doesn’t happen that way, i am not able to apply any styles on wrapper `<text>`
Also, from the code one can infer the same.
https://github.com/FormidableLabs/victory-core/blob/master/src/victory-label/victory-label.js#L243-L255

Did i interpret the docs wrong or is it a bug ?

PS: i have a usecase for applying styles to `<text>` rather than `<tspan>` because of a weird FireFox bug 
https://codepen.io/anon/pen/GvpmXO
They render different in chrome and firefox

**Comment by boygirl** [comment]
@shrynx you're right, this is a mistake in the docs. VictoryLabel always renders a a tspan, and styles are applied there rather than on the text wrapper. I will open an issue in the docs to correct this.

**Comment by boygirl** [comment]
I don't want to add a prop for distinguishing between text and tspan styles, but I would re-write the rendering so that when only one line of content is given, only a text element will be rendered, rather than text + tspan, and all of the styles would be applied there. Would that solve your use case?

**Comment by shrynx** [comment]
@boygirl Wow, that was fast ! Thanks for the response.
I totally understand on not adding an extra prop.
but even making content single line doesn't help.
See: https://codepen.io/shrynx/pen/YxyQPE
chrome renders properly but **firefox** shifts the `tspan` out of `svg` when applied ` writing-mode: vertical-lr;`

**Comment by shrynx** [comment]
@boygirl i got what you meant, i can't put it in one line currently, but i added a class, so that i can change with css (not ideal, but till ff issue fixes i am good to go)

Closing the issue
