### ISSUE TITLE
Start and end tick not showing

### ISSUE THREAD

**Issue by themre** [FormidableLabs/victory#683]
Hi,
I tried LineChart and I noticed that on X and Y axis there is no starting tick. So if my data is [0, ... 1000], I don't see 0 and 1000 on X axis. Same for Y. How can I achieve this to show them? Besides providing `tickValues`, but there I have to provide all ticks.

**Comment by boygirl** [comment]
Unfortunately there is no guarantee about what your tickValues will be unless you manually provide the tickValue array. When this is not provided, Victory will default to the ticks that d3 determines are optimal for your domain and range. 

In addition, please note that 0 tick values are filtered out if your axes cross. To prevent this behavior, set `crossAxis={false}` on the axis that should display zero.
