### ISSUE TITLE
Victory Chart is giving below mentioned error while rendering and render does not complete

### ISSUE THREAD

**Issue by vaibhavswarnkar** [FormidableLabs/victory#685]
I am getting the below-mentioned error while Chart is being rendered. If I remove the Victory imports the error is gone.

`Uncaught TypeError: Cannot read property 'apply' of undefined
    at Object.<anonymous> (bootstrap f7977ec…:23)
    at __webpack_require__ (bootstrap f7977ec…:603)
    at fn (bootstrap f7977ec…:127)
    at Object.<anonymous> (util.js:6)
    at __webpack_require__ (bootstrap f7977ec…:603)
    at fn (bootstrap f7977ec…:127)
    at Object.<anonymous> (victory-animation.js:19)
    at __webpack_require__ (bootstrap f7977ec…:603)
    at fn (bootstrap f7977ec…:127)
    at Object.<anonymous> (index.js:5)
(anonymous) @ bootstrap f7977ec…:23
__webpack_require__ @ bootstrap f7977ec…:603
fn @ bootstrap f7977ec…:127
(anonymous) @ util.js:6
__webpack_require__ @ bootstrap f7977ec…:603
fn @ bootstrap f7977ec…:127
(anonymous) @ victory-animation.js:19
__webpack_require__ @ bootstrap f7977ec…:603
fn @ bootstrap f7977ec…:127
(anonymous) @ index.js:5
__webpack_require__ @ bootstrap f7977ec…:603
fn @ bootstrap f7977ec…:127
(anonymous) @ index.js:6
__webpack_require__ @ bootstrap f7977ec…:603
fn @ bootstrap f7977ec…:127
(anonymous) @ LineChart.js:2
(anonymous) @ 0.index.min.js:31251
__webpack_require__ @ bootstrap f7977ec…:603
fn @ bootstrap f7977ec…:127
(anonymous) @ 0.index.min.js:31850
__webpack_require__ @ bootstrap f7977ec…:603
fn @ bootstrap f7977ec…:127
(anonymous) @ ComponentHandler.js:313
(anonymous) @ bootstrap f7977ec…:156
webpackJsonpCallback @ bootstrap f7977ec…:39
(anonymous) @ 0.index.min.js:1`

**Comment by boygirl** [comment]
Closing, but I will re-open if this can be reproduced
