### ISSUE TITLE
How to use gradients as fill?

### ISSUE THREAD

**Issue by Connorelsea** [FormidableLabs/victory#688]
How would I go about filling the color of the sections of a chart, such as a pie chart, with a gradient. https://formidable.com/open-source/victory/docs/victory-pie

I can do `fill="#fff"` or `theme={[...etc]}` but how can I implement gradient pie chart sections?

Thanks!

**Comment by boygirl** [comment]
@Connorelsea here's a similar example using a gradient for a line stroke. 
https://jsfiddle.net/boygirl/rxc9tr9j/

**Comment by jenskuhrjorgensen** [comment]
@boygirl Can you also use an svg gradient to style VictoryPie? If yes; would you mind providing an example?

**Comment by boygirl** [comment]
@jenskuhrjorgensen here you go: https://jsfiddle.net/boygirl/3mL9rjb5/

**Comment by jenskuhrjorgensen** [comment]
@boygirl Thank you for the quick response :D 

I should maybe have stated that I'm working in react native. If your solution can be translated directly to react native I've done the following, but it doesn't work for the VictoryPie, only the polygon:

```
import React, {Component} from 'react';
import {
    View,
} from 'react-native';
import {Defs, LinearGradient, Polygon, Stop, Svg} from "react-native-svg";

export default class Test extends Component {
    render() {
        return(
            <View>
                <Svg style={{width: "100%", height: 200}}>
                    <Defs>
                        <LinearGradient id="gradient1"
                                        x1="0%" y1="0%" x2="0%" y2="100%"
                        >
                            <Stop offset="0%" stopColor="blue"/>
                            <Stop offset="100%" stopColor="red"/>
                        </LinearGradient>
                    </Defs>
                    <Polygon fill="url(#gradient1)" points='0,0 15,0 0,71'/>
                </Svg>
                <VictoryPie
                    height={300}
                    width={300}
                    colorScale={[
                        "url(#gradient1)",
                    ]}
                    data={[1]}
                />
            </View>
        )
    }
}
```

**Comment by kieuquang1110tt** [comment]
Guys, Have any example for react native typescript? Pls help.

**Comment by ZoltanSzokodi** [comment]
@kieuquang1110tt did you find a solution?
