### ISSUE TITLE
Add `props` argument for all container callbacks

### ISSUE THREAD

**Issue by emattias** [FormidableLabs/victory#691]
I want to position my own HTML elements using `VictoryVoronoirContainer` to calculate hover areas. 

I can define an `onActivated` callback function but I can't get the correct scaled position for my elements since my `onActivated` callback [only gets an array of the closest points](https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/voronoi-helpers.js#L122) with their unscaled data values and I don't have access to the scale prop (since my `onActivated` callback function is not defined in a component that get the scale prop).

Is there a way to access the scale functions in code that is not defined in a component that gets them as a prop?

If there isn't, my suggestion is that you get the scale prop as an argument to the `onActivated` function. Does that make sense? Or should just all the props be included as an argument to the callback function to achieve maximum flexibility? 🤔 

I might be able to create this PR if you can say what you think is the best way to achieve this, with your broader knowledge of how this is best achieved @boygirl

**Comment by boygirl** [comment]
@emattias that makes sense. I can add `props` as the second argument for `onActivated`. I will update the title of this issue to reflect that.

**Comment by emattias** [comment]
Here's a PR that does this: https://github.com/FormidableLabs/victory-chart/pull/506

**Comment by emattias** [comment]
Shouldn't the props be sent to all callback functions? Like `onDomainChange` etc. So that you can do everything that you might need with the values you get.

**Comment by boygirl** [comment]
@emattias yes. I've updated the title of this issue to reflect that.
