### ISSUE TITLE
VictoryLine: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by droganov** [FormidableLabs/victory#693]
Victory version 0.21.3

Line example (http://formidable.com/open-source/victory/docs/victory-line):
```
<VictoryChart>
  <VictoryLine
    data={[
      { x: 1, y: 2 },
      { x: 2, y: 3 },
      { x: 3, y: 5 },
      { x: 4, y: 4 },
      { x: 5, y: 7 }
    ]}
  />
</VictoryChart>
```

Fails with:
![image](https://user-images.githubusercontent.com/1375299/28918151-e8a475b4-7850-11e7-9fc7-4349aa9d6747.png)

**Comment by boygirl** [comment]
I can't reproduce this issue via npm installed or built / minified versions of victory. Fiddle here: https://jsfiddle.net/boygirl/ya162ypa/

I suggest deleting node_modules and trying a fresh npm install.

I'm closing this issue for now, but I'll re-open it if that doesn't solve your problem

**Comment by droganov** [comment]
@boygirl Deleting node_modules and then running yarn did not help.

Node version 6.3.0.

"react": "^15.3.2"
"babel-core": "^6.24.1",
"babel-loader": "^7.0.0",
"babel-plugin-transform-class-properties": "^6.24.1",
"babel-plugin-transform-decorators-legacy": "^1.3.4",
"babel-polyfill": "^6.23.0",
"babel-preset-es2015": "^6.24.1",
"babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",

**Comment by droganov** [comment]
@boygirl I was able to find the cause — add-events.js conflicts with sugar npm (https://github.com/andrewplummer/Sugar)

**Comment by droganov** [comment]
upgrading sugar helped, I think we can close this.
