### ISSUE TITLE
Events problem on React Native

### ISSUE THREAD

**Issue by DylanFayant** [FormidableLabs/victory#696]
Hello!

I've a problem in React Native, i've made a customized Bar Chart for my application but I can't add events. The point is I want to make a custom Tooltips to show the value of the bars. But when I add the Tooltips functionality, nothing happens on the click. 
So I tried to get the basics examples on my project by cleaning old things. I tried tooltips and events (on click...) but nothing happens. It looks like every events are disabled. 

Thank you for your help.

**Comment by boygirl** [comment]
@DylanFayant Victory's event system doesn't have any hard-coded events, so we don't do any mapping between web events like `onClick` and native events like `onPressIn`. Does it work if you use native events like `onPressIn` rather than `onClick`?

**Comment by DylanFayant** [comment]
Hello! Thank you for your reply! 

I'll try with the on press solution but the purpose of my application is to show a bar diagram to represent the benefits of my users for each day of there weeks and my problem is that I want to do something like the Tooltips (when we click on a bar we have a bubble thats appear on the top of the bar with the y value) but customized (It must appear on an half black/yellow bubble and with an icon on the top... I didn't found how to do it and the Tooltips doesn't work on my tries (react native last version on Android). 

Thank you again for your help! 

Sincerely yours.
