### ISSUE TITLE
Docs site: better example of importing Victory components

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/victory#70]
Right now, when we describe how to use Victory, we rely on commented-out code in the ecology playground:
```
// import { VictoryPie } from "victory"
<VictoryPie/>
```
We should put a non-commented-out `import` statement in its own code block above ecology, or find another way to demonstrate usage without relying on dead code.

/cc @boygirl--if you feel like tinkering with this one, go for it!

**Comment by coopy** [comment]
@david-davidson Do you feel like tackling this before the meetup tomorrow?
