### ISSUE TITLE
VictoryZoomContainer allowZoom=false won't pan (but will zoom) in 0.21.4

### ISSUE THREAD

**Issue by medmunds** [FormidableLabs/victory#704]
It seems like `<VictoryZoomContainer allowZoom={false} dimension="x" zoomDomain={{x: ...}}/>` has some odd behavior in Victory 0.21.3 and 0.21.4: attempting to drag the chart area snaps the zoom out to the full x domain, rather than panning through the x axis as expected. The same code seems to work fine with Victory 0.21.2: dragging keeps a fixed zoom level and pans along x.

Demonstration:
Working w/ Victory 0.21.2: https://jsfiddle.net/medmunds/m28x72dz/1/
Broken w/ Victory 0.21.3: https://jsfiddle.net/medmunds/m28x72dz/

```jsx
      <VictoryChart 
        containerComponent={
          <VictoryZoomContainer 
            dimension="x" 
            zoomDomain={{x: [20, 35]}}
            allowZoom={false}
            />}>
        <VictoryAxis/>
        <VictoryAxis dependentAxis/>
        <VictoryBar data={data}/>
      </VictoryChart>
```

(I haven't yet looked into what change might be causing this.)

**Comment by medmunds** [comment]
OK, likely introduced with FormidableLabs/victory-chart#496.

A workaround is to set the VictoryZoomContainer's (undocumented, internal-use-only?) zoomActive prop to true. I'm guessing maybe zoomActive should get initialized by comparing zoomDomain to the full domain?

Workaround demo (v/ Victory 0.21.3): https://jsfiddle.net/medmunds/m28x72dz/2/

**Comment by boygirl** [comment]
@medmunds thanks for tracking down this bug. I'll try to get a fix out before Monday :)

**Comment by medmunds** [comment]
@boygirl thanks for the fix!
