### ISSUE TITLE
Add cornerRadius prop for `VictoryBar`

### ISSUE THREAD

**Issue by ricardoalvarenga101** [FormidableLabs/victory#705]
Is possible Corner Rounded in Victory Bar?

**Comment by boygirl** [comment]
right now there isn't a simple way to make rounded bars, but you can hack something together with styles. Try adding `strokeLinejoin: "round", strokeWidth: 6` to your bar styles. I'll also look into adding a cornerRadius prop for VictoryBar

**Comment by mindjuice** [comment]
Drive-by comment.  I currently have no use for this, but if I did, I imagine would only want the top corners rounded for positive values and the bottom corners rounded for negative values.  There would also be the case of a stacked graph to consider (and possibly ignore) where the interior bars stay square and the exterior one gets rounded.
