### ISSUE TITLE
How to disable 'touch-action: none' for VictoryContainer, on mobile-web

### ISSUE THREAD

**Issue by Cheonsoon** [FormidableLabs/victory#708]
Hi, on developing mobile-web app using this lib, after placing charts inside some page, charts turned auto to be untouch, unscrollable. It's bad for UE. So, I would like to restyle the VictoryContainer, by these screeshots below.
![image](https://user-images.githubusercontent.com/1361794/29132663-92aeb184-7d63-11e7-8023-e7d545e59b26.png)
![image](https://user-images.githubusercontent.com/1361794/29132722-b503ac80-7d63-11e7-99b1-a75f91d13d3f.png)
And it turns out that only the 'style.width' works, while 'style.touchAction' not work, at all.

**Comment by boygirl** [comment]
@Cheonsoon sorry about that. This style was assed to support touch events on containers, but I should make it overrideable by user styles. I'll get the fix in today :)

**Comment by boygirl** [comment]
fix released in `victory-core@17.2.3`. You should be able to pick up this change with a fresh npm install of Victory. If you need this change in the dist version of Victory, you will need to wait until the next release of the main Victory package (~ next week)

**Comment by Cheonsoon** [comment]
Ok, ok. Thanks for your super fast reply as well as issue handling. And it turns out that restyling of 'style.touchAction' works as it should be, now ~~
