### ISSUE TITLE
VictoryContainer crashes when used with create-container

### ISSUE THREAD

**Issue by emattias** [FormidableLabs/victory#711]
After the `containerId` fix containers assume that a props object exists which it doesn't when using `createContainer` function.

[This](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-container/victory-container.js#L49) is the affected line. Either we add a `!props || ` in the begining of the line or add so that a props object exists. What do you think @boygirl?

**Comment by emattias** [comment]
Here's a PR fixing this crash: https://github.com/FormidableLabs/victory-core/pull/289

**Comment by boygirl** [comment]
fix released in `victory-core@17.2.5`
