### ISSUE TITLE
`<VictoryGroup/>` offset not working with `scale="time"`?

### ISSUE THREAD

**Issue by timhwang21** [FormidableLabs/victory#713]
Hi, I've run into an issue when using `<VictoryGroup/>` with a `<VictoryAxis/>` that is scaled by time.

All code was [tested here](https://formidable.com/open-source/victory/docs/victory-group/).

Example 1: linear scale with offset works as expected:

![screen shot 2017-08-14 at 11 36 40 am](https://user-images.githubusercontent.com/5831434/29279132-de70810e-80e4-11e7-886b-575c68661f22.png)

```javascript
<VictoryChart>
  <VictoryAxis orientation="bottom" scale="linear"/>
  <VictoryGroup offset={30}
    colorScale={"qualitative"}
  >
    <VictoryBar
      data={[
        { x: 1, y: 1 },
        { x: 2, y: 2 },
        { x: 3, y: 3 },

//        { x: new Date(2018,1,1), y: 1 },
//        { x: new Date(2018,1,2), y: 2 },
//        { x: new Date(2018,1,3), y: 3 },
      ]}
    />
    <VictoryBar
      data={[
        { x: 1, y: .5 },
        { x: 2, y: 1 },
        { x: 3, y: 1.5 },

//        { x: new Date(2018,1,1), y: .5 },
//        { x: new Date(2018,1,2), y: 1 },
//        { x: new Date(2018,1,3), y: 1.5 },

      ]}
    />
  </VictoryGroup>
</VictoryChart>
```

However, switching the data values to the commented out values and changing the scale to `time` causes issues: the bars are not rendered.

![screen shot 2017-08-14 at 11 38 01 am](https://user-images.githubusercontent.com/5831434/29279185-0e757fc6-80e5-11e7-9416-3f21b570abb0.png)

Additionally, the following errors are logged:

<img width="721" alt="screen shot 2017-08-14 at 11 39 05 am" src="https://user-images.githubusercontent.com/5831434/29279249-4024e6d8-80e5-11e7-93ee-587edad51ccb.png">

```javascript
<VictoryChart>
  <VictoryAxis orientation="bottom" scale="time"/>
  <VictoryGroup offset={30}
    colorScale={"qualitative"}
  >
    <VictoryBar
      data={[
//        { x: 1, y: 1 },
//        { x: 2, y: 2 },
//        { x: 3, y: 3 },

        { x: new Date(2018,1,1), y: 1 },
        { x: new Date(2018,1,2), y: 2 },
        { x: new Date(2018,1,3), y: 3 },
      ]}
    />
    <VictoryBar
      data={[
//        { x: 1, y: .5 },
//        { x: 2, y: 1 },
//        { x: 3, y: 1.5 },

        { x: new Date(2018,1,1), y: .5 },
        { x: new Date(2018,1,2), y: 1 },
        { x: new Date(2018,1,3), y: 1.5 },

      ]}
    />
  </VictoryGroup>
</VictoryChart>
```

Setting `offset={0}`, however, resolves these errors:

![screen shot 2017-08-14 at 11 39 55 am](https://user-images.githubusercontent.com/5831434/29279268-4ee00c3e-80e5-11e7-86ea-1eccb398f11e.png)

Am I missing something? Any help would be appreciated. Thanks!

**Comment by CharukaK** [comment]
Hi, I also have a problem regarding placing the offsets I need to create a dynamic chart that should look like this:
![screenshot from 2017-09-22 11-57-03](https://user-images.githubusercontent.com/18122888/30731804-2f32a592-9f8d-11e7-9cf2-54332009eeaa.png)

But with the VictoryGroup component with offset sometimes the bar positions gets messed up sometimes appearing beyond y-axis and placing ontop of another value and so on, Do you know any way to fix this? Thanks.

**Comment by boygirl** [comment]
@timhwang21 I'm not able to reproduce this issue in the latest version of victory. Do be sure that you are setting `scale={{ x: "time" }}` on your top level `VictoryChart` component

@CharukaK unfortunately you will need to set your offset manually
