### ISSUE TITLE
Hiding axis in polar lines

### ISSUE THREAD

**Issue by bjonnh** [FormidableLabs/victory#715]
When I use 

```
 <VictoryGroup polar width={size.width} height={size.height}>
   <VictoryLine polar data={data} />
 </VictoryGroup>

``` 

The graph doesn't show

```
 <VictoryChart polar width={size.width} height={size.height}>
   <VictoryLine polar data={data} />
 </VictoryChart>
 

```
Works, but I don't want the Axis displayed. Is there any other way to do it?

**Comment by boygirl** [comment]
@bjonnh it looks like I might have a domain bug in `VictoryGroup`. 

You can accomplish what you need with just

`<VictoryLine polar data={data} width={size.width} height={size.height}/>` without using `VictoryGroup`

**Comment by bjonnh** [comment]
Really nice thanks!
