### ISSUE TITLE
The data field doesn't support TypedArray objects

### ISSUE THREAD

**Issue by mindjuice** [FormidableLabs/victory#716]
If you have your data in a `TypedArray` like `Float32Array`, Victory can't display it.

```jsx
  render() {
    const data = Float32Array.from([0, 10, 8, 15])
    return (
      <VictoryChart>
        <VictoryLine data={data} />
      </VictoryChart>
    )
  }
```

The following error is shown in the console:

```bash
proxyConsole.js:56 Warning: Failed prop type: Invalid prop `data` of type `object` supplied to `VictoryLine`, expected `array`.
    in VictoryLine (created by LineGraph)
    in LineGraph (created by VisualizationPanelImpl)
```

I haven't looked into this enough yet to know if just changing the `PropTypes` definition will be enough or if there would need to be any code changes.

The motivation for this is that I'm getting my data from Apache Arrow buffers, which come in `TypeArray`s, and I would prefer not to have the overhead of converting them to normal JS arrays.

Happy to help with implementing this if it's something you're interested in adding.

**Comment by boygirl** [comment]
@mindjuice the example you give won't work without using x and y data accessors with `VictoryLine`, but changing the PropTypes definition would be enough to remove that warning. If you are interested in implementing this change you should add a custom PropTypes validator in this file: https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/prop-types.js
and change the props definition here: https://github.com/FormidableLabs/victory-chart/blob/master/src/helpers/common-props.js#L11 and in `victory-pie`

**Comment by mindjuice** [comment]
Thanks.  I'll try to look at this over the weekend.

**Comment by mindjuice** [comment]
Wasn't able to look at this yet.  I might just convert the data until I see if it's actually a performance issue.  If that happens, I can revisit this.
