### ISSUE TITLE
Tooltip Styling inside VictoryVoronoiContainer

### ISSUE THREAD

**Issue by aaroncrawford** [FormidableLabs/victory#719]
I'm having an issue styling fills on tooltips inside a VictoryVoronoiContainer.  It's not responding to any of the declarations inside the tooltip namespace.  I have a gist here of my theme object :

https://gist.github.com/aaroncrawford/13f4c2e427245e9db3e48886fe3accd4

Lines 191 and 199 are set to red and they're having no effect.  I'm not sure which property would set the tooltip background fill.  Attached image of the tooltip showing as black.
<img width="626" alt="screen shot 2017-08-17 at 2 25 50 pm" src="https://user-images.githubusercontent.com/3203500/29429921-037c9026-8358-11e7-9c01-858822365d20.png">

Am I just not using the correct property, or is this a bug?  When I set the style parameter on VictoryVoronoiContainer, it works.  I just wanted to move this out of the style param and into our general theme.

Thanks!

**Comment by boygirl** [comment]
@aaroncrawford this issue is fixed, but not yet released. It will be a breaking change, so I want to bundle it with some others before releasing.

**Comment by aaroncrawford** [comment]
Thank you!
