### ISSUE TITLE
Tooltips showing all the time in VictoryLine inside ZoomContainer

### ISSUE THREAD

**Issue by pzehle** [FormidableLabs/victory#723]
So, I'm following the documentation on the website, where by the way doesn't actually show a way to put tooltips in line charts inside a zoom container. Anyway, I'm trying to do it, but I get the next result:

![screen shot 2017-08-21 at 16 43 43](https://user-images.githubusercontent.com/27866874/29524647-a6efb8b0-8690-11e7-9f14-3e4af5e479a1.png)

My code is as follows:

```
<VictoryChart
	theme={VictoryTheme.material}
	animate={{duration: 600}}
	height={250}
	style={chartStyle}
	containerComponent={
		<VictoryZoomContainer
			responsive={true}
			dimension="x"
			zoomDomain={this.state.zoomDomain}
			onDomainChange={this.handleZoom.bind(this)}
			title={this.state.selectedFilters.analyte + ' - ' + this.state.selectedFilters.unit + ' / Visits'}
			labelComponent={<VictoryTooltip />}
		/>
	}>
	<VictoryLine
		style={{data: {stroke: '#0063BE'}}}
		data={this.state.graphTier1}
	/>
	{this.state.compareSegments ?
		<VictoryLine
			style={{data: {stroke: '#FF4F00'}}}
			data={this.state.graphTier2}
		/> :
		null
	}
</VictoryChart>
<VictoryChart
	theme={VictoryTheme.material}
	animate={{duration: 600}}
	padding={{top: 0, left: 20, right: 20, bottom: 30}}
	height={60}
	style={chartStyle}
	containerComponent={
		<VictoryBrushContainer
			responsive={true}
			dimension="x"
			selectedDomain={this.state.selectedDomain}
			onDomainChange={this.handleBrush.bind(this)}
			title={'Visits'}
		/>
	}>
	<VictoryAxis
		tickValues={undefined}
		tickFormat={undefined}
	/>
	<VictoryLine
		style={{data: {stroke: '#0063BE'}}}
		data={this.state.graphTier1}
	/>
	{this.state.compareSegments ?
		<VictoryLine
			style={{data: {stroke: '#FF4F00'}}}
			data={this.state.graphTier2}
		/> :
		null
	}
</VictoryChart>
```

Everything is working correctly, the problem is that I'm getting the labels shown all the time, as shown in the image above.

Is there a way to do this?

Thanks!

**Comment by boygirl** [comment]
@pzehle 

You'll want to create a hybrid container with zoom and voronoi behaviors (to provide tooltip targets). Here's an example you can follow: https://formidable.com/open-source/victory/docs/create-container#example

**Comment by pzehle** [comment]
Thank you very much, I didn't find a way to do it. I tried it and it's working.

**Comment by sindhu465** [comment]
Could you please let me know how to remove Tooltips showing all the time in VictoryLine inside ZoomContainer

**Comment by jmitchell33** [comment]
How did you resolve this issue?  I'm having the same problem with the tooltips showing all the time inside the ZoomContainer.

**Comment by sindhu465** [comment]
I am not working on that now.So,I don’t remember exactly but I made some changes below:
onMouseOut:()=>
