### ISSUE TITLE
Errors when using 'Victory' with React@16

### ISSUE THREAD

**Issue by mzygmunt** [FormidableLabs/victory#724]
Hello,
I noticed following errors when I updated my React to version 16 (beta):
![image](https://user-images.githubusercontent.com/13297558/29572669-417187de-875d-11e7-92e3-4c8cf5175e5a.png)

**Comment by ajosephjohnson** [comment]
I also received these errors:

VictoryAxis.componentWillMount(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.

**Comment by boygirl** [comment]
@mzygmunt @ajosephjohnson Thanks for pointing this out. I'll get a fix out in the next version

**Comment by Unimate** [comment]
@boygirl, still has warnings on React Native, how can I solve it? 
My dependencies: 
 "victory-chart": "23.0.1",
 "victory-core": "19.0.3",
 "victory-native": "0.14.0",
 "victory-pie": "13.0.1"
