### ISSUE TITLE
Stacked Bar Graph Width Issue

### ISSUE THREAD

**Issue by l3roken** [FormidableLabs/victory#725]
I am having an issue with a stacked bar chart.  Once I get enough groups, the width of the group is rendered too wide.  

![image](https://user-images.githubusercontent.com/5069857/29587286-1fc7161c-8753-11e7-9cd2-004f5c345afd.png)

Here is a jsfiddle with the same issue:
https://jsfiddle.net/l3roken/3ndjLucv/

**Comment by sibelius** [comment]
@l3roken can you provide the function that you used?

it could help more people

@boygirl I think we can close this

or should victory handle this as well?
