### ISSUE TITLE
VictoryGroup on Safari using Dates

### ISSUE THREAD

**Issue by joshphiggins** [FormidableLabs/victory#728]
I'm having trouble getting Victory Group to work correctly only in Safari and only if x value is a Date.
I'm on v10.1.2  of Safari (latest).  

[Working Fiddle](https://jsfiddle.net/joshphiggins/m9kuuz7x/3/)
<img width="503" alt="screen shot 2017-08-24 at 11 58 16 am" src="https://user-images.githubusercontent.com/13538940/29675571-8be004aa-88c3-11e7-859e-eec111b4535b.png">

[Not working Fiddle](https://jsfiddle.net/joshphiggins/abehk4nd/4/)
<img width="502" alt="screen shot 2017-08-24 at 11 59 39 am" src="https://user-images.githubusercontent.com/13538940/29675630-ba2a2f02-88c3-11e7-9c5c-6c3fbdeb3df1.png">

I've got no issues in Chrome or if the values don't include a Date.  If I remove the VictoryGroup component and just give the data to the Line and Scatter components directly, it works fine on Safari.  

Below is another example my original chart that and error message I get from Safari console. It looks like there's NANs getting calculated in the path.  
[Another Example](https://bancmetrics.firebaseapp.com/)
<img width="1010" alt="screen shot 2017-08-24 at 12 04 42 pm" src="https://user-images.githubusercontent.com/13538940/29675918-9debc192-88c4-11e7-9671-4d5acbec5453.png">

**Comment by BenjaminRCooper** [comment]
https://github.com/FormidableLabs/victory/issues/438 - may help buddy

**Comment by ovarunendra** [comment]
+1
