### ISSUE TITLE
VictoryLegend's x and y props do not work in latest version 0.21.5

### ISSUE THREAD

**Issue by liweifeng2** [FormidableLabs/victory#729]
VictoryLegend's x and y props work well in version 0.21.0, but no effect in version 0.21.5.
```
<svg width={200} height={200} viewBox={"0 0 200 2000"}>
  <VictoryPie
    standalone={false}
    ...
  />
  <VictoryLegend
    standalone={false}
    data={legendData}
    x={50}
    y={30}
    symbolSpacer={2}
    gutter={2}
  />
</svg>
```

**Comment by boygirl** [comment]
@liweifeng2 thank you for pointing this out. Improvements to `VictoryLegend` are coming in `0.22.0`. I will make sure this is addressed for that release.
