### ISSUE TITLE
VictoryGroup color propType to support function

### ISSUE THREAD

**Issue by Olliebaba** [FormidableLabs/victory#732]
I am building a chart which has multiple lines, scatter dots for each data point and a tooltip hover over for every scatter dot. I encountered 'z-indexing' issues where the tooltips were hidden behind other descendant siblings following [the example in the gallery](https://formidable.com/open-source/victory/gallery/voronoi-tooltips-grouped). (Change second data point of first Victory group to `{x: 2, y: 0.5}` then hover to see the overlap.) So I tried combining the data and making a single scatter group. The `color` prop on Victory group is applied to each scatter dot so I realized I could pass a function to dynamically set the color in the same way as VictoryScatter can take a function for `size`. This works perfectly but throws a propType error, that color must be a string. Can this prop's propTypes be switched to `oneOf([string, func])`?

**Comment by boygirl** [comment]
@Olliebaba sorry for the delay. I will make this change in an upcoming version :)
