### ISSUE TITLE
VictoryTooltip not line up exactly on top of label on VictoryPie

### ISSUE THREAD

**Issue by Kerumen** [FormidableLabs/victory#733]
I use a `<CustomLabel />` on my `VictoryPie` to render both the label and the tooltip. The label seems good but the tooltip is off.

<img width="310" alt="screen shot 2017-08-29 at 15 17 23" src="https://user-images.githubusercontent.com/5436545/29822909-551812ce-8ccd-11e7-86cd-df9f66a057bc.png">

```jsx
<VictoryPie
  data={data}
  width={260}
  height={260}
  padding={0}
  innerRadius={75}
  labelRadius={95}
  padAngle={2}
  labelComponent={<CustomLabel />}
/>
```

```jsx
class CustomLabel extends Component {
  static defaultEvents = VictoryTooltip.defaultEvents

  render() {
    const { datum, text, y, style } = this.props
    return (
      <g>
        <VictoryLabel
          {...this.props}
          text={datum.y < 5 ? '' : `${Math.floor(datum.y)}%`}
        />
        <VictoryTooltip
          {...this.props}
          text={`${text}\n${datum.y}%`}
          orientation="top"
          pointerLength={5}
          height={40}
        />
      </g>
    )
  }
}
```

**Comment by ivanaxel** [comment]
cool

**Comment by boygirl** [comment]
@Kerumen the x, y position of the tooltip is at the tip of the pointer. It looks like it is hitting the bottom edge of the underlying text element rather than the center. You might correct this by changing the verticalAnchor in VictoryLabel. Does this address your issue, or am I missing something?

**Comment by Kerumen** [comment]
For this one yes, but the bottom one is good and the left one is off but not by the same offset.
I tried `verticalAnchor="start"`. It seems a bit better but the left one is still off-positioned and the right label is too close from the middle-edge.

<img width="329" alt="screen shot 2017-09-01 at 19 58 24" src="https://user-images.githubusercontent.com/5436545/29981944-f5250b76-8f4f-11e7-989f-8ce53f0f53a0.png">

Same screenshot without `verticalAnchor`:

<img width="309" alt="screen shot 2017-09-01 at 20 00 21" src="https://user-images.githubusercontent.com/5436545/29982037-588e6fc2-8f50-11e7-886e-685d0929b82c.png">

All the labels are good on this one, but tooltips are messed up.

**Comment by Kerumen** [comment]
@boygirl It's resolved?
