### ISSUE TITLE
Can I change dot for a comma on label axis?

### ISSUE THREAD

**Issue by rccorreia** [FormidableLabs/victory#735]
I am from a culture where comma is used to represent a decimal number. Example: 10.5 is represented like 10,5, and 1,000 is 1.000
Is there a way to change the culture of the chart?

**Comment by boygirl** [comment]
@rccorreia yes, you can format the labels on your axis with the `tickFormat` prop. It takes a function like `tickFormat={(tick) => yourLocalizationFunction(tick)}`. When a tick format is not specified, Victory defers to d3 to format ticks. https://github.com/d3/d3-scale#continuous_tickFormat
