### ISSUE TITLE
Add ability to set VictoryLegend symbol size via theme propery

### ISSUE THREAD

**Issue by danny-andrews** [FormidableLabs/victory#736]
It [looks like](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-legend/helper-methods.js#L107) the size of the symbol in a `VictoryLegend` component is either derived from the `font-size` or from the `symbol.size` property of the datum. It would be nice if this was configurable via the `VictoryTheme`, as is symbol type.

Probably something as simple as:
```js
legend: {
    style: {
      data: {
        type: 'square',
        size: 16,
      },
    },
  }
```

And then in [victory-legend/helper-methods.js](https://github.com/FormidableLabs/victory-core/blob/90fe2b0/src/victory-legend/helper-methods.js#L107):
```js
size: dataStyle.size || getSymbolSize(datum, fontSize),
```

I'd be happy to make a PR if this seems like a good approach.

**Comment by boygirl** [comment]
@danny-andrews 

Good timing. I'm actually in the middle of a big legend overhaul. I'll make sure this functionality gets in.

**Comment by danny-andrews** [comment]
Splendid. :)
