### ISSUE TITLE
Theme color palette

### ISSUE THREAD

**Issue by kserjey** [FormidableLabs/victory#737]
I think that it would be great if it will be able to set/override/get theme color palette.

**Comment by boygirl** [comment]
@kserjey you can override `colorScale` on any of the components that take that prop (`VictoryPie`, `VictoryGroup`, `VictoryStack`). I feel like I might be missing something about the feature you're asking for though. Can you explain in greater detail the expected behavior you're after.

**Comment by kserjey** [comment]
Can I change color of all charts types? I think it will be great if I can override primary color like this: `MaterialTheme.primaryColor = '#DEDEDE'`.

**Comment by boygirl** [comment]
@kserjey themes in Victory are just plain objects. The best thing to do would be to write your own theme generator. Here's some more information on themes: https://formidable.com/open-source/victory/guides/themes/

I'm going to close this issue. I like your idea, but I don't think it's something that's general enough to warrant including in the library.
