### ISSUE TITLE
Call data accessor functions with both `datum` and `index`

### ISSUE THREAD

**Issue by kserjey** [FormidableLabs/victory#738]
I try to get index in X prop `(datum, idx) => idx + 1`, but sometimes it is undefined. Is it normal?

**Comment by boygirl** [comment]
@kserjey data accessors are only called with `datum` not with `index`. I will update the title of this issue and add the feature request label.

**Comment by fernandatoledo** [comment]
Hi @boygirl do you have any updates on this feature? I couldn't find it in the backlog, thank you! 😄
