### ISSUE TITLE
VictoryPie.componentWillMount(): Assigning directly to this.state is deprecated (warning)

### ISSUE THREAD

**Issue by CaryLandholt** [FormidableLabs/victory#741]
Using react 16 rc1 and seeing the following warning message in the browser console
```
Warning: VictoryPie.componentWillMount(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.
```

Any ideas?
Thanks!

**Comment by zackify** [comment]
Getting it too for a few weeks now

**Comment by boygirl** [comment]
I'm closing this as a duplicate of https://github.com/FormidableLabs/victory/issues/724

**Comment by CaryLandholt** [comment]
Ahh. Didn't see that an issue already existed. Cheers!
