### ISSUE TITLE
Unexpected behavior animating bars

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#742]
From @walidvb
Animating (top bar disappears): 
![image](https://user-images.githubusercontent.com/3719995/30176847-a264efa6-93b8-11e7-8da3-30dc7580eb4d.png)

not animating:
![image](https://user-images.githubusercontent.com/3719995/30176861-ac14cfbc-93b8-11e7-9a3f-bd835539dd75.png)

supporting gist: https://gist.github.com/walidvb/836e611f47f71b86d944c6f95f445f2a

**Comment by walidvb** [comment]
Made some changes(mostly cosmetic), updated the gist.
Also, I think it is worthy of noting that I am printing 4 charts, and that they seem to have different buggy behaviours:
<img width="1291" alt="screen shot 2017-09-08 at 16 10 48" src="https://user-images.githubusercontent.com/810604/30215756-3c92f714-94b1-11e7-82a7-83ba607f902d.png">

The issue can be viewed [here](http://connectworks.io/walid?animate=true) or  [here](http://connectworks.io/walid?animate=false)

**Comment by boygirl** [comment]
I believe this issue is fixed, but please reopen if I am mistaken
