### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by carlosgg93** [FormidableLabs/victory#743]
It's posible to do horizontall scroll in a victory chart with victory bars?

ex: if I have 100 victory bars and only i want show 25, the rest will be hidden and when you will do horizontall scroll shows the others victory bars

**Comment by boygirl** [comment]
@carlosgg93 yes, you can use `VictoryZoomContainer` for this. You would set `allowZoom={false}` so that the chart would only pan. Then set an initial `zoomDomain` prop so that only your initial 25 bars are included. You can read more about `VictoryZoomContainer` here https://formidable.com/open-source/victory/docs/victory-zoom-container

**Comment by carlosgg93** [comment]
@boygirl Thanks!!

**Comment by rishabhbhatia** [comment]
@carlosgg93 @boygirl Could someone share a minimal example. I have it working on iOS but for some reason the scroll won't work on android devices. My chart code is below.

```
           <VictoryChart
              domainPadding={40}
              containerComponent={
                <VictoryZoomContainer
                  allowZoom={false}
                  zoomDomain={{x: [moment().startOf('week').subtract(6, 'hours').toDate(), moment().endOf('week').add(6, 'hours').toDate()]}}
                />
              }
            >
              <VictoryAxis
                tickFormat={(x) => (moment(x).format('Do'))}
              />
              <VictoryAxis dependentAxis
                tickFormat={(y) => (`$${y}`)}
              />
              <VictoryBar
                x="bookingTime"
                y="tripAmt"
                data={earnings}
                labels={(d) => (`$${d.y}`)}
                alignment="middle"
              />
            </VictoryChart>
```

**Comment by ShaikhKabeer** [comment]
Is horizontal bar chart scrolls  if there is already scroll for screen ?

**Comment by ShaikhKabeer** [comment]
The scrolling is too slow for Horizontal Bar Chart. Any solution for this @boygirl

**Comment by ShaikhKabeer** [comment]
Any update on this ?

**Comment by LuggPort-Thomas** [comment]
Click will not happen

**Comment by hntddt123** [comment]
Any update for onPanDomainHandler?

**Comment by Mohini1693** [comment]
@boygirl  - Any update on this?  Moreover, can I link the VictoryZoomContainer scrolling with a horizontal scrollbar (so that application users know about the scrolling feature)?

**Comment by stanislav-sidorov-empeek** [comment]
![screencast 2022-12-03 17-41-50](https://user-images.githubusercontent.com/79838991/205449372-d6246dff-70a7-4327-9e62-773b526369b9.gif)
`class App extends React.Component {

  constructor() {
    super();
    this.state = {};
  }

  handleZoom(domain) {
    this.setState({selectedDomain: domain});
  }

  handleBrush(domain) {
    this.setState({zoomDomain: domain});
  }

  render() {
    return (
      <div>
          <VictoryChart
            width={550}
            height={300}
            
            containerComponent={
              <VictoryZoomContainer responsive={false}
                zoomDimension="x"
                allowZoom={false}
                allowPan
                zoomDomain={this.state.zoomDomain}
                onZoomDomainChange={this.handleZoom.bind(this)}
              />
            }
          >
            <VictoryBar
              style={{
                data: {stroke: "tomato"}
              }}
              data={[
                {x: new Date(1982, 1, 1), y: 125},
                {x: new Date(1987, 1, 1), y: 257},
                {x: new Date(1993, 1, 1), y: 345},
                {x: new Date(1997, 1, 1), y: 515},
                {x: new Date(2001, 1, 1), y: 132},
                {x: new Date(2005, 1, 1), y: 305},
                {x: new Date(2011, 1, 1), y: 270},
                {x: new Date(2015, 1, 1), y: 470}
              ]}
            />

          </VictoryChart>

          <VictoryChart
            width={550}
            height={40}
            scale={{x: "time"}}
            domainPadding={{ x: [10, 10]}}
            padding={{top: 0, left: 50, right: 50, bottom: 30}}
            
            containerComponent={
              <VictoryBrushContainer responsive={false}
                brushDimension="x"
                brushDomain={this.state.selectedDomain}
                allowDrag
                
                allowDraw
                brushStyle={{stroke: "transparent", fill: "black", fillOpacity: 1}}
                brushComponent={<rect rx="5" ry="5" width="5"/>}
                onBrushDomainChange={this.handleBrush.bind(this)}
              />
            }
            style={{
    background: { fill: "#c0c0c0" }
  }}
  backgroundComponent={<Background rx="5" ry="5"/>}
          >
            <VictoryAxis
              tickValues={[
                new Date(1985, 1, 1),
                new Date(1990, 1, 1),
                new Date(1995, 1, 1),
                new Date(2000, 1, 1),
                new Date(2005, 1, 1),
                new Date(2010, 1, 1),
                new Date(2015, 1, 1)
              ]}
              style={{ 
  axis: { display: "none" }, 
  labels: { display: "none" }, 
  ticks: { display: "none" }
}}
              tickFormat={(x) => null}
            />
            <VictoryBar
              style={{
                data: {stroke: "transparent", fill: 'transparent'}
              }}
              data={[
                {x: new Date(1982, 1, 1), y: 125},
                {x: new Date(1987, 1, 1), y: 257},
                {x: new Date(1993, 1, 1), y: 345},
                {x: new Date(1997, 1, 1), y: 515},
                {x: new Date(2001, 1, 1), y: 132},
                {x: new Date(2005, 1, 1), y: 305},
                {x: new Date(2011, 1, 1), y: 270},
                {x: new Date(2015, 1, 1), y: 470}
              ]}
            />
          </VictoryChart>
      </div>
    );
  }
}
ReactDOM.render(<App/>, mountNode)`

**Comment by stanislav-sidorov-empeek** [comment]
![screencast 2022-12-03 20-37-08](https://user-images.githubusercontent.com/79838991/205456634-c9f190b1-665e-4560-8658-a535991dd77b.gif)


```class App extends React.Component {

  constructor() {
    super();
    this.state = {};
  }

  handleZoom(domain) {
    this.setState({selectedDomain: domain});
  }

  handleBrush(domain) {
    this.setState({zoomDomain: domain});
  }

  render() {
    return (
      <div style={{ display: 'flex' }}>
          <VictoryChart
            width={550}
            height={300}
            
            containerComponent={
              <VictoryZoomContainer responsive={false}
                zoomDimension="x"
                allowZoom={false}
                allowPan
                zoomDomain={this.state.zoomDomain}
                onZoomDomainChange={this.handleZoom.bind(this)}
              />
            }
          >
            <VictoryBar
            horizontal
              style={{
                data: {stroke: "tomato"}
              }}
              
              data={[
                {x: 100, y: 125},
                {x: 200, y: 257},
                {x: 300, y: 345},
                {x: 400, y: 515},
                {x: 500, y: 132},
                {x: 600, y: 305},
                {x: 700, y: 270},
                {x: 800, y: 470}
              ]}
            />

          </VictoryChart>
<div style={{ height: 250 }}>
          <VictoryChart
            width={25}
            height={250}
            
            
            padding={{top: 0, left: 15, right: 0, bottom: 0}}
            
            containerComponent={
              <VictoryBrushContainer responsive={false}
                brushDimension="x"
                brushDomain={this.state.selectedDomain}
                allowDrag
                allowResize
                allowDraw
                brushStyle={{stroke: "transparent", fill: "black", fillOpacity: 1}}
                brushComponent={<rect rx="5" ry="5" width="5"/>}
                onBrushDomainChange={this.handleBrush.bind(this)}
              />
            }
            style={{
    background: { fill: "#c0c0c0" }
  }}
  backgroundComponent={<Background rx="5" ry="5" x="15" y="0"/>}
          >
            <VictoryAxis
              
              style={{ 
  axis: { display: "none" }, 
  labels: { display: "none" }, 
  ticks: { display: "none" }
}}
              tickFormat={(x) => null}
            />
            <VictoryBar
            horizontal
              style={{
                data: {stroke: "transparent", fill: 'transparent'}
              }}
              
              data={[
                {x: 100, y: 125},
                {x: 200, y: 257},
                {x: 300, y: 345},
                {x: 400, y: 515},
                {x: 500, y: 132},
                {x: 600, y: 305},
                {x: 700, y: 270},
                {x: 800, y: 470}
              ]}
            />
          </VictoryChart></div>
      </div>
    );
  }
}
ReactDOM.render(<App/>, mountNode)```

**Comment by techiekarthick** [comment]
Y axis should be fixed and scroll only x axis using scrollView ? Is it possible in victory native

**Comment by leviit9x** [comment]
any update this ?

**Comment by RavirajParab44** [comment]
Is it possible to  not allow the scrollbar width to be manipulated such that you have a natural scroll?

**Comment by Rogue2806** [comment]
**Check this**
https://medium.com/@rg24275/creating-a-scrollable-bar-chart-with-custom-scrollbar-pointers-using-react-and-victory-29d3d41045ec
