### ISSUE TITLE
Render tick labels below negative bars

### ISSUE THREAD

**Issue by naveedehmad** [FormidableLabs/victory#747]
When we have negative data, `x-axis` tick values should be rendered below the chart and not on top of the bars where the axis is:

<img width="325" alt="screen shot 2017-09-11 at 8 54 38 pm" src="https://user-images.githubusercontent.com/1432549/30284165-931077a4-9733-11e7-9693-c05ace72deed.png">

The tick values `a` and `b` should be below the chart. Is there an option for that? Like this:

<img width="566" alt="screen shot 2017-09-11 at 8 58 28 pm" src="https://user-images.githubusercontent.com/1432549/30284314-023f182e-9734-11e7-9a6f-4b2441506761.png">

**Comment by boygirl** [comment]
@naveedehmad you can use the `offsetY` prop on `VictoryAxis` to move your dependent axis down to the bottom of your chart like in the second image. You can read more about it here: https://formidable.com/open-source/victory/docs/victory-axis#offsety

**Comment by Lelith** [comment]
is there a way to calculate the offset based on the data? i don t have any domain for my y axis.

**Comment by boygirl** [comment]
Check out this example of negative aware tick labels https://codesandbox.io/s/v6zzl6jl77

**Comment by Lelith** [comment]
awsome thank you for your quick reply, that helped me a lot!

**Comment by alisman** [comment]
@boygirl we've been struggling with the following. If there's negative data, the x axis is place at zero, which brings the tick labels along with it.  We want the labels and probably the axis too to be at the bottom of the chart.  Is there a simple way?

![image](https://user-images.githubusercontent.com/186521/39725951-7ded3ecc-521b-11e8-978c-11977f2e7527.png)

**Comment by wieringen** [comment]
I also would like to know how to do this.

**Comment by Clafouti** [comment]
@alisman did you try to simply put something like:
```
<VictoryAxis
  offsetY={10}
/>
```

And then play a little bit with the value of the offset.

**Comment by alisman** [comment]
@Clafouti Yes, I hadn't realized that the offset was relative to the y axis.  So this is indeed the solution to this issue.

**Comment by nazimjamil** [comment]
> @Clafouti Yes, I hadn't realized that the offset was relative to the y axis. So this is indeed the solution to this issue.

Definitely works, but you lose your zero value axis. I suppose we'd need to compose another axis just for that 😅
