### ISSUE TITLE
VictoryBar - TypeError: CSS2Properties doesn’t have an indexed property setter for ‘0’ in Firefox

### ISSUE THREAD

**Issue by franciscofabian** [FormidableLabs/victory#748]
In Firefox VictoryBar with this data format:
 `<VictoryBar
  data={[[0, 1], [1, 1], [2, 3], [3, 1]]}
  x={0}
  y={1}
/>` gives the error **TypeError: CSS2Properties doesn’t have an indexed property setter for ‘0’**, it doesn't happen with VictoryLine or VictoryScatter, or with the usual data format:
 `<VictoryBar
  data={[
    {employee: "Jane Doe", salary: 65000},
    {employee: "John Doe", salary: 62000}
    ...
  ]}
  x="employee"
  y="salary"
/>`
It doesn't happen either in Chrome.

**Comment by franciscofabian** [comment]
This seems to be common problem with react:
https://medium.com/@abhaytalreja/react-typeerror-css2properties-doesnt-have-an-indexed-property-setter-for-0-4acea43facd5

**Comment by franciscofabian** [comment]
@boygirl is there anybody looking into this issue?

**Comment by naveedehmad** [comment]
Steps to reproduce:

Open this Jsfiddle in Firefox:
https://jsfiddle.net/csrrguaa/

Chart will not render. Looking into console reveals this error:

`TypeError: CSS2Properties doesn't have an indexed property setter for '0'`

**Comment by boygirl** [comment]
We are no longer applying arbitrary attributes from the data object onto styles, so this issue should be fixed.
