### ISSUE TITLE
VictoryTooltip is not recognized in typescript

### ISSUE THREAD

**Issue by ShenAdrada** [FormidableLabs/victory#751]
is VictoryTooltip compatible in typescript? 
I tried to npm install, but still it's an error

![screenshot_6](https://user-images.githubusercontent.com/26157352/30361313-d7d4117e-9888-11e7-8ea9-a57ea83e035b.png)

![screenshot_2](https://user-images.githubusercontent.com/26157352/30361401-603246ee-9889-11e7-807a-6ebc59d7fa0c.png)

**Comment by boygirl** [comment]
@ShenAdrada Sorry, we don't maintain typings for Victory. Also, you should be able to include `VictoryTooltip` directly from `victory` rather than `victory-core`.

**Comment by ShenAdrada** [comment]
> Also, you should be able to include VictoryTooltip directly from victory rather than victory-core.

it's an error. It says the 'Module 'victory' has no exported member 'VictoryTooltip'. '

**Comment by ryan-roemer** [comment]
You can see the commonjs and ESM exports of `VictoryTooltip` in:

- https://unpkg.com/victory@0.22.2/lib/index.js (commonjs)
- https://unpkg.com/victory@0.22.2/es/index.js (ESM)

If you've got an actual build error, please open a new issue with a full stack trace and ideally a reproduction repository for us to help see what's wrong. Thanks!
