### ISSUE TITLE
tooltips are overlapped by adjacent charts

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#752]
When several Victory charts are rendered next to each other, they still each have their own portal component, so elements rendered into one portal may still be overlapped by elements in another Victory chart. 
![image](https://user-images.githubusercontent.com/3719995/30454556-96582086-9951-11e7-9648-86db8015658f.png)

See supporting fiddle: 
https://jsfiddle.net/naveenkr/fhavqbza/2/

**Comment by boygirl** [comment]
@naveenblipp the solution to this is going to be moving from pure svg rendering to a tree that looks like so

```
<div style={styles.parent}>
  <svg viewBox>
   {chart stuff}
  </svg>
  <div zIndex={99} position="relative" marginTop={calculatedPercentage}>
   <svg viewBox>
    {portal stuff}
   </svg>
  </div>
</div>
```
It's a little hacky, but I couldn't figure out a better way to keep the relative positioning of the portal in sync with the chart svg. This is going to be a breaking change for some people's parent styles. I'm going to put this work in with some other small breaking changes for containers. I expect it to all be finished and released early next week.

**Comment by naveenblipp** [comment]
Thanks @boygirl Let me know if I can test using your experimental branch.

**Comment by camsjams** [comment]
This is more of a slight breaking modification, as any chart that is rendered inside of standard `svg` tags are now broken, as a `div` is inside of the `svg`. This is a pretty damaging change to many of my charts.

**Comment by camsjams** [comment]
@boygirl the above issue I had is solved by using `standalone={false}` on the elements in question (thus removing the `VictoryContainer`.

Custom chart crisis averted!

**Comment by CharukaK** [comment]
I have the same issue with VictoryLegend component
![33961611-bd2e65d4-e074-11e7-87eb-2d8ca969d07a](https://user-images.githubusercontent.com/18122888/34516540-3e938f22-f09d-11e7-80d8-ee0ffc124e57.png)

I tried the standalone false option but it doesn't work in my case

**Comment by boygirl** [comment]
@CharukaK Try wrapping your legend in `VictoryPortal`
