### ISSUE TITLE
Point symbols only render correctly when x and y values are whole numbers

### ISSUE THREAD

**Issue by cbranch101** [FormidableLabs/victory#753]
Something strange seems to be going on with the path functions that render symbols inside of point

`<Point symbol="diamond"/>`
<img width="828" alt="screen shot 2017-09-18 at 10 53 56 am" src="https://user-images.githubusercontent.com/1420404/30551379-e3d04828-9c5f-11e7-8018-ba52e5bfd521.png">

`<Point symbol="plus"/>`
<img width="723" alt="screen shot 2017-09-18 at 10 54 08 am" src="https://user-images.githubusercontent.com/1420404/30551456-1a59c4d2-9c60-11e7-9001-79240938ff6b.png">
"/>

The only shape that seems to work correctly is circle

An example of how I'm providing the point component

```
<VictoryScatter
    dataComponent={
        <Point
            symbol="plus"
            shapeRendering="auto"
            style={{ fill: "black" }}
        />
    }
/>

```

**Comment by cbranch101** [comment]
In fact you can see the same problem in the demo in the docs for [Victory Scatter](http://formidable.com/open-source/victory/docs/victory-scatter#data)

Both the square and circle are warped

![screen shot 2017-09-21 at 12 10 33 pm](https://user-images.githubusercontent.com/1420404/30708896-fe47dd20-9ec5-11e7-8f52-66ff10989ad2.png)

**Comment by cbranch101** [comment]
After some digging, I think this only happens when the x or y values for the point aren't a whole number

**Comment by boygirl** [comment]
@cbranch101 thank you for looking into this. We started rounding path values to prevent sub-pixel rendering, but I think this is causing error and distortion.

**Comment by cbranch101** [comment]
@boygirl Yep, I think that's what it was. PR inbound to `victory-core` that I think will address this.
