### ISSUE TITLE
VictoryAnimation and VictoryTransition are throwing A LOT of setState warnings to the console due to setTimeout which is not being cleared on componentWillUnmount

### ISSUE THREAD

**Issue by HydraOrc** [FormidableLabs/victory#754]
If you unmount your component while the animation is in progress, you will stuck in an endless loop showing this warning:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the VictoryAnimation component.`

This happens due to setTimeout which is not being cleared on componentWillUnmount.

**Comment by hansoksendahl** [comment]
I also ran into this issue, when re-rendering a component wrapped in `<VictoryAnimation />`.
