### ISSUE TITLE
Tooltips leave artefacts on surrounding page

### ISSUE THREAD

**Issue by prestond123** [FormidableLabs/victory#755]
Tooltips are leaving artefacts on surrounding html (panel header below).
![panelproblem](https://user-images.githubusercontent.com/26113279/30690841-6d3b5f26-9ebd-11e7-8e77-e89850b620c5.PNG)

Sometimes tips appear half under and over items
![tooltip_artefacts](https://user-images.githubusercontent.com/26113279/30736891-75fc994e-9f7c-11e7-99af-583dec05e430.png)

**Comment by prestond123** [comment]
On the panel header.

**Comment by prestond123** [comment]
I have tried to reproduce in a fiddle But **COULD NOT**,  
but here is the fiddle - I'll keep tweaking to try to get the same behavior we see in our real app.
https://jsfiddle.net/wovvss1c/6/

**Comment by boygirl** [comment]
@prestond123 what version of Victory are you using in your app?

**Comment by prestond123** [comment]
Glad you ask, I forgot we moved onto 21.5 - I've updated the fiddle (as this was 21.3)  
Still cannot reproduce.
https://jsfiddle.net/wovvss1c/8/
Thanks

**Comment by prestond123** [comment]
Any ideas how i can solve this would be appreciated,  thanks.

**Comment by prestond123** [comment]
Read that this is a bug in webkit.  I have fixed by setting:
-webkit-backface-visibility: hidden; 
on the parent div.  This stops the artefacts, but also stops the tool tip ever being seen over the div with this set on.
