### ISSUE TITLE
Randomly Generated ID in VictoryClipContainer breaks Storyshots

### ISSUE THREAD

**Issue by cbranch101** [FormidableLabs/victory#762]
When trying to load a chart inside of a [storyshot](https://github.com/storybooks/storybook/tree/master/addons/storyshots), everything seems to work fine, except for the random id generated right [here](https://github.com/FormidableLabs/victory-core/blob/2559e96e3eec6636ac1033c2b2982b4fd2023d8e/src/victory-clip-container/victory-clip-container.js#L38-L43). 

This random id ensures that the storyshot has to be updated every time it runs, essentially rendering it useless.

**Comment by boygirl** [comment]
released in `victory@0.23.0`
