### ISSUE TITLE
Correct way to dynamically add/delete chart components from VictoryGroup?

### ISSUE THREAD

**Issue by rudasoftware** [FormidableLabs/victory#763]
I am developing a data-vis app with rather large data sets. To make the data useful, I've split the data into various "slices" which can be viewed individually or superimposed on the same graph. The data is controlled with a multiselect box, which triggers the modification of an array of data sets stored in `state`.

Displaying the initial data set works fine, including animation. Changing between single sets of data works as well. But, selecting multiple data sets causes problems when selecting a different combination of data sets. The animation seems to get "confused". Sometimes only the most recently added dataset animates in, and then the existing ones snap to their new values (if the dependent axis domain changes). Sometimes, the data gets "stuck" if you select fewer data sets, and it doesn't actually change until you select a single data set again. At that point, though, the animation is permanently broken. The data changes, but there is no easing.

To display the data, I map over the array of data sets something like this:
```jsx
<VictoryGroup>
  { this.state.dataSets.map((dataSet, i) => (
    <VictoryScatter
      data={dataSet}
      key={ this.props.columnLabels[this.state.columnIndexes[i]] }
    />
    ))
  }
</VictoryGroup>
```
The `columnLabels` array is a stable list of all possible data categories. The `columnIndexes` array indexes correspond to the indexes of the data sets, and the values are the indexes into `columnLabels` the correspond to that data set. That was probably a very confusing explanation... (Perhaps I should just duplicate the label and store it on the actual data set in the `state` array.) The point is, though, this `key` SHOULD be stable. I.e. a data set should get the same key any time it is selected, regardless of the order.

Is this the proper way to dynamically add charts to a `VictoryGroup`? Is this behavior tested? Is there another way I should know about?

**Comment by rudasoftware** [comment]
UPDATE: I checked the console, and I'm getting a million of these errors:
`
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the VictoryAnimation component.
`
This leads me to believe that Victory components are not expected to pop in and out of existence. Is what I'm trying to do simply not supported by the current state of the library?

**Comment by rudasoftware** [comment]
Using latest version on npm, 0.22.2

**Comment by rudasoftware** [comment]
#754 
Seems to be related

**Comment by beccanelson** [comment]
Since there hasn't been any discussion on this issue in a few years, I'm going to close this for now in an effort to clean up some of our older issues. Let me know if it needs to be re-opened!
