### ISSUE TITLE
Tooltip appears behind the other VictoryLine in a VictoryGroup

### ISSUE THREAD

**Issue by Kerumen** [FormidableLabs/victory#768]
<img width="807" alt="screen shot 2017-09-28 at 10 11 14" src="https://user-images.githubusercontent.com/5436545/30956078-3f804c26-a436-11e7-95d1-562c655ddd14.png">

When I hover the lowest line, the tooltip appears behind the top one. I tried to use the prop `renderInPortal` but it doesn't work. It also does nothing to remove the `containerComponent`.

This is my markup:

```
<VictoryChart
  width={1120}
  height={400}
  theme={VictoryTheme.material}
  domainPadding={50}
  containerComponent={<VictoryVoronoiContainer />}
>
  <VictoryAxis dependentAxis tickFormat={x => `${x / 1000}k`} />
  <VictoryAxis
    tickValues={range(19, 34)}
    tickFormat={x => toMonthYearShort(getDateFromAbsMonth(x))}
  />
  {tags.map(({ periods }) =>
    <VictoryGroup
      data={periods}
      x="absMonth"
      y="value"
      labels={d => d.y}
      labelComponent={<VictoryTooltip renderInPortal />}
    >
      <VictoryLine />
      <VictoryScatter />
    </VictoryGroup>
  )}
</VictoryChart>
```

**Comment by Kerumen** [comment]
If I move `labels` and `labelComponent` on the `VictoryVoronoiContainer` it works better but it displays 2 times the data?

<img width="785" alt="screen shot 2017-09-28 at 10 29 43" src="https://user-images.githubusercontent.com/5436545/30956682-621e5abe-a438-11e7-8623-943a94834244.png">

Markup:
```
<VictoryChart
  width={1120}
  height={400}
  theme={VictoryTheme.material}
  domainPadding={50}
  containerComponent={
    <VictoryVoronoiContainer
      labels={d => d.y}
      labelComponent={<VictoryTooltip renderInPortal />}
    />
  }
>
  <VictoryAxis dependentAxis tickFormat={x => `${x / 1000}k`} />
  <VictoryAxis
    tickValues={range(19, 34)}
    tickFormat={x => toMonthYearShort(getDateFromAbsMonth(x))}
  />
  {tags.map(({ periods }) =>
    <VictoryGroup
      data={periods}
      x="absMonth"
      y="value"
    >
      <VictoryLine />
      <VictoryScatter />
    </VictoryGroup>
  )}
</VictoryChart>
```

**Comment by boygirl** [comment]
@Kerumen I'm not able to reproduce the issue you're seeing with overlapping tooltips, at least in the latest version:
<img width="556" alt="screen shot 2017-10-10 at 6 23 14 pm" src="https://user-images.githubusercontent.com/3719995/31418004-228cdea2-ade8-11e7-8022-9332bf4dcaba.png">

https://jsfiddle.net/boygirl/qzyerv0e/

**Comment by bochen2014** [comment]
thanks @boygirl for your example.  any idea how we can prevent showing 2 tool tips at the same time? 

![image](https://user-images.githubusercontent.com/8207081/60418680-e66b6900-9c26-11e9-98c5-2bfe692bae83.png)
