### ISSUE TITLE
Add allowPan functionality to VictoryZoomContainer

### ISSUE THREAD

**Issue by andykitch** [FormidableLabs/victory#769]
I have used createContainer to create a zoom & selection container. When I click and drag in this container, it (understandably) doesn't know whether to pan the view (zoom container) or select data (selection container). Adding the allowPan functionality would allow me to switch the panning off, allowing only selection of data within the container.

Happy to create a fiddle if this helps!

**Comment by boygirl** [comment]
@andykitch good timing. I'm working on container changes right now. I'll add this to the upcoming release.
