### ISSUE TITLE
Animations Mutate data unexpectedly

### ISSUE THREAD

**Issue by tomciopp** [FormidableLabs/victory#770]
I'm running into an issue where if I animate a chart some UUIDs that get passed in become mutated when I try to run an event on them. Since the UUIDs are used for transitioning URLs, my application breaks instead of returning the intended behavior. Based on my debugging I believe the issue is with d3-interpolation. 

Here is the example of what is going wrong. I am transitioning from a state that has this data

    x = [
      {noteId: "dc2e2e9e-7996-4bb2-b9f6-78267c1ff5d1"}, 
      {noteId: "ecc6a2e2-472c-4e77-8755-d9d0ba3cbeaa"}
    ]

To one that has the following data:
    
    y = [
      {noteId: "d5fec62c-1ff1-4324-99ea-021aa92d097e"}
    ]

If we run that data through the interpolate function provided by D3 we get the following output:

    [{noteId: "dNaNfecNaNcNaNffNaNNaNNaNeaNaNaaNaNdNaNe"}]

Without following the rest of the execution, when the data gets back to me I see the noteId with the following data being returned. 

    data = {noteId: "d5fec62c-1ff1-4324-99ea-21aa92d97e"}

The noteId is now missing the zeros which matched the NaN fragments around that area of "021" and "097" which are truncated to 21 and 97 respectively. 

I believe the quickest fix for this would be to pass in a clone of any elements to any third party functions since I don't think we want the possibility of mutation at all when it comes to data returned from an event. Lodash has a `cloneDeep` function that should be perfect for this solution. Let me know if you have any questions and I will do my best to answer them.

**Comment by beccanelson** [comment]
This is most likely happening because `d3.interpolate` is being called on the entire data object, which includes these UUIDs. There might be some room for improvement here around this interpolation, and giving the user more control over which properties are interpolated.

**Comment by becca-bailey** [comment]
I'm closing this in favor of a larger overhaul of transitions and animations. https://github.com/FormidableLabs/victory/issues/2104
