### ISSUE TITLE
Is there a way to resize CustomChart?

### ISSUE THREAD

**Issue by gavrilenco** [FormidableLabs/victory#772]
Created custom chart using this example http://formidable.com/open-source/victory/guides/custom-charts, how can resize it? I get 450*300 width and height. Changing viewbox props doesn't solve the problem as proportions remain the same. Folks, any thoughts?

**Comment by boygirl** [comment]
@gavrilenco the chart will resize, but the _aspect ratio_ will remain constant. If you want the aspect ratio to change on resize, you will need to setup a resize handler on your window, and tie your `width` and `height` props to that.

**Comment by gavrilenco** [comment]
@boygirl Hey! Thanks for answer! Actually I wanted to know if I can change aspect ratio on component init, like set it once (change default).
