### ISSUE TITLE
Logarithmic interpolation

### ISSUE THREAD

**Issue by BrRenat** [FormidableLabs/victory#774]

**Comment by boygirl** [comment]
@BrRenat 

Victory uses d3-shape for interpolating curves / areas. You can read about the supported interpolation types here: https://github.com/d3/d3-shape#curves. "Logarithmic" is not an option for interpolation.

If you're looking for a log _scale_ for your chart, that _is_ supported. Just add `scale={{ y: "log" }}` or something to your `VIctoryChart` component. 

I'm going to close this issue for now, but please comment if you have other questions or requests.
