### ISSUE TITLE
VictoryBar style.data.width is inconsistently applied

### ISSUE THREAD

**Issue by michaelbridge** [FormidableLabs/victory#776]
Bars previously displayed with equal width and spacing instead of the 'striped' effect below.  Change occurred between versions 0.18.0 and 0.18.1.

![screen shot 2017-10-03 at 10 24 01 am](https://user-images.githubusercontent.com/6562899/31130484-8659873c-a825-11e7-9315-ecdf852d12e5.png)

**Correct Example with 0.18.0**
https://jsfiddle.net/br1ek3k2/11/ 

**Incorrect Example with 0.18.1**
https://jsfiddle.net/br1ek3k2/12/

**Comment by cjtafoya** [comment]
+1

**Comment by cjtafoya** [comment]
@boygirl any updates on this? Definitely seems to be a core library bug post 0.18.0 (clean js example above)

**Comment by jurajhrib** [comment]
+1

**Comment by hdwatts** [comment]
+1, any update on this?
