### ISSUE TITLE
Add a `containerRef` prop for those who need a reference to the rendered chart

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#781]
Supports exporting to pdf etc. 

Implementation: 

A prop on `VictoryContainer` (and all the containers that extend it) called `containerRef` takes a function. The ref will be applied to the outermost element that Victory renders.

Usage:
```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.logContainerRef = this.logContainerRef.bind(this);
  }

  componentDidMount() {
    this.logContainerRef();
  }

  logContainerRef() {
    console.log(this.containerRef);
  };

  render() {
    return (
      <VictoryBar
         containerComponent={
            <VictoryContainer containerRef={(ref) => { this.containerRef = ref; }}/>
         }
     />
   );
 }
}
```

**Comment by boygirl** [comment]
@esutton 

I expect this change to be released in main victory this week, but not in victory-native until some time next week.

**Comment by esutton** [comment]
@boygirl Thank you so much!

**Comment by boygirl** [comment]
released in `victory@0.23.1`. Look for this in the next victory native release as well. ~ next week

**Comment by esutton** [comment]
Thank you.

I have not tried it yet but I assume this should work with the new containerRef exposed:

```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.logContainerRef = this.logContainerRef.bind(this);
  }

  componentDidMount() {
    this.logContainerRef();
  }

  logContainerRef() {
    console.log(this.containerRef);
  }

  render() {
    return (
      <VictoryBar
        containerComponent={
          <VictoryContainer containerRef={(ref) => {
            this.containerRef = ref;

            setTimeout(() => {
              this.containerRef.svgRef.toDataURL((base64) => {
                console.log(base64);
              });
            }, 500);
          }}
          />
        }
      />
    );
  }
}


```

**Comment by arieldf** [comment]
@boygirl @esutton I have tried your exact example above and I get the following error: Uncaught TypeError: Cannot read property 'toDataURL' of undefined at setTimeout

I have tried for quite some time to understand the issue, but without any luck. Do you know what could be the issue?

**Comment by bgold0** [comment]
@arieldf @boygirl I too get this same issue. Anyone have any thoughts?

**Comment by n1th1l** [comment]
Any update on this? `TypeError: Cannot read property 'toDataURL' of undefined`
