### ISSUE TITLE
How to hide the labels representing the x-value at the bottom on VictoryCharts?

### ISSUE THREAD

**Issue by danieldelouya** [FormidableLabs/victory#785]
How to hide the labels representing the x-value at the bottom on VictoryCharts?

**Comment by NgoKnows** [comment]
You should be able to do something along the lines of `<VictoryAxis tickFormat={() => ''} />`

**Comment by NgoKnows** [comment]
By default VictoryChart will include two axis, so you will have to explicitly include `VictoryAxis` within `VictoryChart` so that you can pass props to it.

**Comment by danieldelouya** [comment]
Using `<VictoryAxis tickFormat={() => ''} />` hides all labels. How can i keep the labels on the Y axis and hide them on the x axis? Can't find anything in the docs about this

**Comment by NgoKnows** [comment]
1. Same way as hiding the x-axis, on the y-axis component, you can use the tickFormat prop, `tickFormat={(datum) => datum.y.toFixed(2)}`
2. Check out the `tickCount` and `tickValues` props on `VictoryAxis`
3. I think 2 might help with this. Also could do something with `tickFormat` as well.

**Comment by boygirl** [comment]
@NgoKnows Thanks for jumping in on this. I'm going to close this issue now.

**Comment by danieldelouya** [comment]
Thanks for the help :)

**Comment by lnanhkhoa** [comment]
Thanks for help, too.

**Comment by ShaikhKabeer** [comment]
How can I hide the values/label showing data on line chart ?

**Comment by SamMatthewsIsACommonName** [comment]
@ShaikhKabeer  did you figure how to do this? I'm trying to hide the x value from showing on a bar graph above the bar itself

**Comment by priyanga2496** [comment]
How to represent minute values for x axis which can also adjusts as per the current hour
