### ISSUE TITLE
Using VictoryPie inside VictoryTootip

### ISSUE THREAD

**Issue by alishir** [FormidableLabs/victory#786]
Is it possible to create custom victorytooltip that shows an other victorychart? for example if use hover mouse over a point in scatter chart, a new pie chart pops up as a tooltip.

**Comment by boygirl** [comment]
@alishir yes it is! You would create a custom tooltip component. You can read about examples for creating custom data components here: https://formidable.com/open-source/victory/guides/custom-components#creating-new-components and more about how to customize VictoryTooltip specifically here https://formidable.com/open-source/victory/guides/tooltips#customizing-tooltips
