### ISSUE TITLE
Tooltips in VoronoiContainer stay showing after leaving chart

### ISSUE THREAD

**Issue by cbranch101** [FormidableLabs/victory#793]
![oqovj1qnty](https://user-images.githubusercontent.com/1420404/31556195-867c0942-b009-11e7-8cec-92dcceac7db4.gif)

Is this the intended behavior? We have multiple charts at the same time, so we end up in situations where that can be multiple tooltips on the screen at once and it looks really cluttered.

**Comment by kujon** [comment]
I've noticed this issue as well. It only seems to be happening with React 16 and tooltips rendered in a portal.
