### ISSUE TITLE
labelComponent not rendering when data set is only two

### ISSUE THREAD

**Issue by kmasila00** [FormidableLabs/victory#798]
Ive come across a very specific issue. The label component isnt rendering when there are only two data points. I am attaching a label key to the data point. It seems to work fine for any other length of data points. The pictures of my graph are below.

![screen shot 2017-10-17 at 3 11 43 pm](https://user-images.githubusercontent.com/17914022/31684611-555cbd96-b34e-11e7-822e-b2c7700050e9.png)
![screen shot 2017-10-17 at 3 11 27 pm](https://user-images.githubusercontent.com/17914022/31684614-585098c4-b34e-11e7-9b57-5bc1fabaaa33.png)

I tried testing this out on the Live Preview provided in the docs and its seems to work properly

<img width="1222" alt="screen shot 2017-10-17 at 3 44 26 pm" src="https://user-images.githubusercontent.com/17914022/31685795-3c0dccb4-b352-11e7-816f-9aeb92512e69.png">

I am writing the component the same way.

<img width="493" alt="screen shot 2017-10-17 at 3 44 55 pm" src="https://user-images.githubusercontent.com/17914022/31685793-36e9675c-b352-11e7-8e13-0c4c5bdbf1d4.png">

I inspected using React dev tools and it seems as though the whole element is not rendering when there are two data points.

<img width="1314" alt="screen shot 2017-10-17 at 3 13 28 pm" src="https://user-images.githubusercontent.com/17914022/31684764-c9dd7bf6-b34e-11e7-8efb-756cdf980675.png">

<img width="1376" alt="screen shot 2017-10-17 at 3 13 59 pm" src="https://user-images.githubusercontent.com/17914022/31684766-cdb74112-b34e-11e7-8f67-9a8e8447528a.png">

The top image has 4 data sets and the bottom has only two and you can see that the Victory Label component is disappearing. 

Is this a bug with the library or am i doing something wrong. I appreciate any help i can get. Thank you

**Comment by boygirl** [comment]
@kmasila00 this is very odd. I believe this is a bug in the library

**Comment by boygirl** [comment]
I believe this is fixed
https://codesandbox.io/s/5vy6lvypln
