### ISSUE TITLE
How to change axis value color

### ISSUE THREAD

**Issue by vikkya** [FormidableLabs/victory#800]
i wanted to change my axis color value X-Axis(5, 10, 15) . By default its black. as my background is black i cant see the axis value color.
for VictoryBar and VictoryLine
![victory](https://user-images.githubusercontent.com/26187350/31719394-e9c390e4-b430-11e7-89ef-e647aeeec9ea.png)

**Comment by ecnaidar** [comment]
@vikkya https://stackblitz.com/edit/react-mkphkm
Very helpful https://formidable.com/open-source/victory/docs/victory-axis#style
You also might consider creating common theme https://formidable.com/open-source/victory/guides/themes

**Comment by amit13091992** [comment]
any solutions for customizing axis value colors??
