### ISSUE TITLE
Grid of material theme is rendered after children

### ISSUE THREAD

**Issue by haskellcamargo** [FormidableLabs/victory#802]
Using `VictoryChart` with `theme={ VictoryTheme.material }` makes the grid of the chart to be rendered **after** the components. This makes the grid overflow the children of the chart because the `z-index` of `svg` is controlled by the order of the elements.

### Screenshot

![image](https://user-images.githubusercontent.com/7553006/31771065-681f7bdc-b4b9-11e7-809d-5de313d08073.png)

### Example

```js
<VictoryChart theme={ VictoryTheme.material }>
  <VictoryLine data={ data } />
</Victory>
```

**Comment by boygirl** [comment]
@haskellcamargo this is expected behavior.

`VictoryChart` renders its default axes _after_ any explicitly provided child components. To change this behavior, explicitly add your axes _before_ your children like so:
```
<VictoryChart>
  <VictoryAxis/>
  <VictoryAxis dependentAxis/>
  <VictoryLine/>
  ...
</VictoryChart>
```
