### ISSUE TITLE
VictoryStack does not scale properly when children have varying number of datapoints

### ISSUE THREAD

**Issue by JStrohm-10e** [FormidableLabs/victory#805]
https://jsfiddle.net/1os2460L/1/

When using a stacked VictoryArea, the it does not expand properly if the VictoryArea components do not have the same number of data points.  In the image below you can see the data is getting cut off.

```
<VictoryChart>
  <VictoryStack>
    <VictoryArea
      data={[{x: 2, y: 3}, {x: 3, y: 20}]}
    />
    <VictoryArea
      data={[{x: 1, y: 1}, {x: 2, y: 4}, {x: 3, y: 5}]}
    />
    <VictoryArea
      data={[{x: 1, y: 3}, {x: 2, y: 2}, {x: 3, y: 6}]}
    />
  </VictoryStack>
</VictoryChart>
```

<img width="657" alt="screen shot 2017-10-20 at 12 13 42 pm" src="https://user-images.githubusercontent.com/32072924/31838097-2dc10712-b590-11e7-89ea-a92b58115bb9.png">

However when there are the same number of data points, it behaves fine:
```
<VictoryChart>
  <VictoryStack>
    <VictoryArea
      data={[{x: 1, y: 0}, {x: 2, y: 3}, {x: 3, y: 20}]}
    />
    <VictoryArea
      data={[{x: 1, y: 1}, {x: 2, y: 4}, {x: 3, y: 5}]}
    />
    <VictoryArea
      data={[{x: 1, y: 3}, {x: 2, y: 2}, {x: 3, y: 6}]}
    />
  </VictoryStack>
</VictoryChart>
```
<img width="654" alt="screen shot 2017-10-20 at 12 18 34 pm" src="https://user-images.githubusercontent.com/32072924/31838289-f9720e92-b590-11e7-90cb-8202fb1cbd7d.png">

**Comment by abologna-r7** [comment]
Same here.

##Context
I have the need to use dynamically rendered bars, lines, areas as the following (ommiting some code for simplicity):

```js
<VictoryChart
   scale={{x: "time"}}
   padding={{ right: 50, bottom: 50, left: 50, top: 50 }}
   theme={styles.chartTheme}
   width={width}
   height={500}
   containerComponent={<VictoryVoronoiContainer/>}
   animate={{ duration: 1000, easing: "expOut" }}>
   <VictoryAxis dependentAxis />
   <VictoryStack>
   {
      Object.keys(data).map((key, index) => {
         return (
            <VictoryArea key={key} data={allDates} {...props} />
         )
      })
   }
   </VictoryStack>
</VictoryChart>
```

While doing so it seems that the charts are not being calculated correctly and somehow it messes up the rest of the stacked items.

Also, data not always the same size on each iteration... Maybe related to what @JStrohm-10e is talking about... if not I'll open another issue.

![image](https://user-images.githubusercontent.com/8812471/32693508-b1a337e0-c6f1-11e7-81ff-4e9c38c47ce5.png)

**Comment by abologna-r7** [comment]
So, for the time being, I'll keep using recharts (Recharts.org) which addresses the StackArea differently and so far it's working with less re-rendering but still, their tooltip keeps rerendering the chart which for lots of data points is bad.
