### ISSUE TITLE
VictoryChart inside scrollview blocks scroll gesture on Android

### ISSUE THREAD

**Issue by danieldelouya** [FormidableLabs/victory#807]
On iOS everything works fine. On Android the chart completely blocks the scrollview gesture. How can i fix this?

**Comment by liuruizhe728** [comment]
How can you fix it?

**Comment by ShaikhKabeer** [comment]
@danieldelouya , I'm also facing this issue. Please help

**Comment by ReggaePanda** [comment]
@danieldelouya do you have a workaround?

**Comment by lorenzosfarra** [comment]
I would like to add a (in my opinion) more clean solution, as reported [here](https://github.com/FormidableLabs/victory-native/issues/143#issuecomment-323137671).
Just for reference, the comment suggests to add `pointerEvents="none"` to the surrounding `View`.
