### ISSUE TITLE
VoronoiContainer + Label = Tooltips not working

### ISSUE THREAD

**Issue by Ribesg** [FormidableLabs/victory#810]
Somehow when having a label in the chart, the tooltip system is no longer working correclty, showing only one (random?) tooltip when hovering the entire chart.
https://codesandbox.io/embed/vyykx3jp77

Also note that after some testing, when the "randomly selected" tooltip shown is for a data point with x=0, the app crashes!

**Comment by alikhani** [comment]
Adding a `voronoiDimension="x"` in your `VictoryVoronoiContainer` fixes your first issue..

There is a weird issue when x is 0 or 1 though where the tooltip has two points...

**Comment by Ribesg** [comment]
Yes, it acts weirdly when x=0 or x=1, x=0 can event crash the app.

I'm adding this other weird behavior: https://codesandbox.io/embed/8k008wn9ll
I'm not sure if it's related.
