### ISSUE TITLE
Chart data is not bound by axis ticks

### ISSUE THREAD

**Issue by nclaw** [FormidableLabs/victory#811]
We would like to have our chart data to always stay between the axis ticks, given that:

- We cannot hardcode tickValues for the vertical axis
- Chart height must be adjusted when browser window is resized; chart width should stay constant
- Vertical axis should display different number of ticks depending on size of its parent container - _see screenshot below_

<img width="1174" alt="screen shot 2017-10-27 at 11 56 55 am" src="https://user-images.githubusercontent.com/11022691/32085685-544f1d60-bb1c-11e7-9bfc-08e85e1bcdb3.png">

On the screenshot above the same chart displayed on three cards, first card is in expanded state while the other two are collapsed.

If you will take a look at the first card you'll notice that one of the bars is crossing the top most axis tick, if possible we would like to avoid this and always contain chart bars between the first and last axis ticks similar to how it looks on the _screenshot below_.

<img width="1174" alt="screen shot 2017-10-27 at 12 43 13 pm" src="https://user-images.githubusercontent.com/11022691/32085909-89558fac-bb1d-11e7-9241-8b1d5d34252a.png">

So far we have tried the following:

**Idea #1** - Add a secondary dependent axis with bounding tick values:

```
  let upperBoundary = 1000

  # primary dependent axis
  <VictoryAxis
    dependentAxis
    tickFormat={x => x}
    tickCount={tickCount}
    crossAxis={false}
  />

  # secondary dependent axis
  <VictoryAxis
    dependentAxis
    tickValues={[0, upperBoundary]}
    crossAxis={false}
  />
```

This would work if we knew the upperBoundary tick value for each of our data sets which is not achievable at this stage.

**Idea #2** - Set domain on the dependent axis:

```
  # attempt to calculate the next tick value from our data
  const getNewUpperBoundary = () => {
    const highestDataPoint = Math.max(...data.map(item => item.value));
    const delta = highestDataPoint / (tickCount - 1);
    return highestDataPoint + delta ;
  }

  <VictoryAxis
    dependentAxis
    domain={[0, getNewUpperBoundary()]}
    tickFormat={x => x}
    tickCount={tickCount}
    crossAxis={false}
  />
```

We had some success with this solution depending on what data set we provide to our chart, unfortunately in some cases this solution adds an additional tick when it is not needed - see collapsed graph on the _screenshot below_.

<img width="1174" alt="screen shot 2017-10-27 at 1 32 35 pm" src="https://user-images.githubusercontent.com/11022691/32085921-95c63304-bb1d-11e7-96e3-371391b5a5ec.png">

It would be ideal if we could get the real axis tick values and the delta/step between them instead of using our approximation (like in getNewUpperBoundary function above), that way we would be able to accurately calculate the next tick.

Any pointers / ideas would be much appreciated.

**Comment by boygirl** [comment]
@nclaw This is a tough one. Without knowing the extent of your data beforehand, it will be very difficult to achieve the result you are looking for. If you do know your minimum and maximum data points, I would suggest calculating your tickValues ahead of time, and then filtering them as you change the window size. That would be the only _guaranteed_ way to achieve your desired result.

You might try adding a generous domainPadding like `VictoryChart domainPadding={{ y: [0, 50] }}...` That should make it more likely for your data to always be within your ticks.

I'm going to close this issue, but please let me know if you can think of some addition to the `VictoryAxis` api that would make your life easier. It sounds like you might be suggesting adding a `tickStep` prop, but I'm not sure that would actually solve the issue you're seeing.

**Comment by Sparragus** [comment]
Adjusting the `domainPadding` worked for me. :)

**Comment by chriszrc** [comment]
@boygirl @Sparragus right, domainPadding will save you, however if your charts are responsive and can we rendered at dramatically different widths, you'll still have the same problem. I think something like the "constrainToVisibleArea" that's been added for the tooltips. There's almost never a reason why anyone would want their bars outside of the axes-
