### ISSUE TITLE
Multiple spaces between text in a tickFormat.

### ISSUE THREAD

**Issue by Kebie** [FormidableLabs/victory#812]
I am trying to put leading spaces between two strings in a tick and I am hitting a problem in the conversion to SVG/HTML (they are being ignored in the tspan tag) and not being able to use &amp;nbsp; cause they just show up as text. I have tried the unicode value for the a space as well.

```
<VictoryAxis
        tickFormat={(t, i) => `${data[i].bar}  ${("      "+data[i].value).slice(-5)}%`}
        style={style.yStyle}
        dependentAxis
  />
```

What I want:
![screen shot 2017-10-27 at 3 26 24 pm](https://user-images.githubusercontent.com/1324411/32127370-3faff604-bb2b-11e7-8358-5fbf7ed6f055.png)

What I got:
![screen shot 2017-10-27 at 3 26 30 pm](https://user-images.githubusercontent.com/1324411/32127379-48d8f622-bb2b-11e7-9dbf-7228d104d626.png)

I think it has something to do with setting xml:space="preserve" somewhere but I am not a SVG/XML expert and don't know if this possible to set on Ticks. Any tips or solutions would be appreciated.

**Comment by boygirl** [comment]
@Kebie sorry for the delay. Try using strings with an explicit non-breaking space character like:
```
tickFormat={ () => `Three \xa0\xa0\xa0 spaces`}
```
