### ISSUE TITLE
Linking Victory Legend to Data Sets

### ISSUE THREAD

**Issue by jakebern** [FormidableLabs/victory#814]
How do you reference the specific VictoryBars / data sets from the legend?  ie. I can't out how to reuse the "name" set in VictoryBar in VictoryLegend (see below, where write "name: keys[n]" in each component).  How do you ensure each name / color ordering in VictoryLegend data matches the ordering of your data sets?   Thanks!

    <VictoryLegend
        data={[ { name: keys[0] }, { name: keys[1] } ]}
    />
    
    <VictoryStack>
    <VictoryBar
        data={sorted[keys[0]]}
        x={0}
        y={1}
        name ={keys[0]}
      />
    <VictoryBar
        data={sorted[keys[1]]}
        x={0}
        y={1}
        name = {keys[1]}
    />
    </VictoryStack>

**Comment by boygirl** [comment]
@jakebern There aren't any automatic associations between VictoryLegend and the data it represents. Instead, rely on consistency in naming, and in how you use props like `colorScale` Here's an example of wiring up a legend to data sets: 

https://jsfiddle.net/boygirl/n92Lnsy3/

I'm going to close this issue, but let me know if you have more questions.
