### ISSUE TITLE
Add default label padding to prevent errors in VictoryLegend 

### ISSUE THREAD

**Issue by Clafouti** [FormidableLabs/victory#817]
Hi,

I'm trying to create a customized and while doing so I encountered a bunch of errors:
<img width="544" alt="capture d ecran 2017-10-31 a 15 31 42" src="https://user-images.githubusercontent.com/7141072/32229544-5c870ab4-be51-11e7-8de8-b92c0d832d8d.png">

In this example, I've only used the gray theme object you provide here: https://formidable.com/open-source/victory/guides/themes with no change at all.
I copy/pasted that file, imported 'assign' from 'lodash' and exported the theme object to use inside another file.

What am I doing wrong here ? Do I need to specify other styles ? If so, is there a documentation about every style I should specify ?

**Comment by boygirl** [comment]
@Clafouti that is unexpected. Can you try logging what your theme object looks like? You should get an object roughly like 
```
{
  area: {
   height: 350,
   padding: 50
   width: 350,
   style: {
     data: {...},
     labels: {...}
   }
  },
  axis: {
  ...
  }
  ...
}
```
If that isn't what you're getting, I would check your export / import. You shouldn't need to do anything special with styles to get it to work.

**Comment by Clafouti** [comment]
@boygirl thanks for the fast reply.

I've tried to create a minimal example here: https://codesandbox.io/s/l2kyvp3qm9

With the exported theme I got 4 errors that look approximately the same as those I have in my project. If I remove the exported and use the "default" one (which should be the same if I correctly understood) everything is fine.

It seems that everything goes banana because of the VictoryLegend component. I'm probably doing something wrong but I can't find where.

Let me know if you need a bigger/cleaner example.

**Comment by boygirl** [comment]
@Clafouti thanks for providing more information! This is actually _two_ issues :)
1) the docs need to be updated to use a new version of the default theme that includes a legend name space
2) legend calculations need default label padding to prevent errors when nothing is defined in the theme.

I'm going to change the title of this issue to reflect 2), and open an issue in the docs for 1).

**Comment by boygirl** [comment]
btw, here's the update default theme: https://github.com/FormidableLabs/victory-core/blob/master/src/victory-theme/grayscale.js

**Comment by Clafouti** [comment]
@boygirl Thanks for the updated theme ! I just tried it and can confirm that it works like a charm. Thank you.
