### ISSUE TITLE
dataComponents won't render with the same eventKey

### ISSUE THREAD

**Issue by clairefreehafer** [FormidableLabs/victory#818]
I am trying to render two VictoryPies, and set a VictorySharedEvent so that when hovering over a slice in one pie, it and one or more slices on the other pie will change color. To do this, I am manually setting the eventKeys for each set of data (i.e. `data={[{ x: 'Yes', y: 237, eventKey: 'yes' }, ...]`), giving some sets the same eventKey as others within the same pie. But doing this will only render one of the slices for each eventKey. It seems that the key for each Slice component is generated from the eventKey (mine are "undefined-data-yes" in this case), so when I keep the eventKeys at their default values (incrementing numbers) all slices are rendered. Is there any way to get around this and have duplicate eventKeys?

Here is a recreation of the problem: https://codesandbox.io/s/o57nl1rrr9

**Comment by boygirl** [comment]
@clairefreehafer currently, no. Event keys are iterated over when determining props for components. The example you provide makes me want to change how this works, though. I think this will be a straightforward change, but I will update this issue early next week and let you know.

**Comment by becca-bailey** [comment]
I'm going to close this for now, since we don't currently have plans to implement this.
