### ISSUE TITLE
Changes in zooming behaviour since v0.22.0

### ISSUE THREAD

**Issue by OliverM** [FormidableLabs/victory#820]
Hi,

I've a line chart contained inside a combined voronoi and zoom container. The zoom container has a `minimumZoom` and a `zoomDomain` set, and the zooming `dimension` set to `x` only.

This works fine in 0.22.0 but in the latest version the zooming dimension zooms in both `x` and `y`, even though the `dimension` prop is still set only to `x`. 

I know the library's in alpha so I'm not sure if this is a bug or a change in API. I can provide much more detail if needed!

Thanks for a great library.

Oliver.

**Comment by NgoKnows** [comment]
All of the changes are listed in `CHANGELOG.md`, this should be what you are looking for https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#0230-2017-09-30.

You should only need to change `dimension` to `zoomDimension`

**Comment by OliverM** [comment]
That sorted it, thanks for the pointer @NgoKnows
