### ISSUE TITLE
Programatically clear brush domain

### ISSUE THREAD

**Issue by JRGranell** [FormidableLabs/victory#823]
Hi,

I'm currently using the brush container to allow a user to select an area. I would like to be able to clear the selected area from outside the chart. Our scenario is that we have a number of charts that allow selections to be made and then have a reset button that should clear them all.

The ideal solution I believe would allow me to clear the `brushDomain` property used as part of the brush container, preferably mutating through using the event handling system. This prop is not available outside the chart component, and as far as I'm aware the only way to hook into the event handling system, in order to mutate this prop, is via an event handler. 

However as no mouse event is fired as the reset occurs outside the chart area, so it is not possible to detect when some high component has told me to reset the chart.

I have tried to use a custom brush / handle component and passing in a custom prop, however any change to a custom prop is not passed down (is the component cached with its initial props?).

Thanks for any advice or suggestions.

**Comment by boygirl** [comment]
@JRGranell Hi there, 

The latest release of Victory added a prop called `externalEventMutations`. You can read more about it here: https://formidable.com/open-source/victory/guides/events/#external-event-mutations

You should be able use it to trigger a change to the brush domain. You would target `"parent"` and mutate `currentDomain` to programmatically clear the brush domain

**Comment by JaxGit** [comment]
I suppose this is not working for victory-native as RN only knows ref system instead of childName?

**Comment by JaxGit** [comment]
Is this working for victory-native as well?

**Comment by JaxGit** [comment]
Excuse me @boygirl , I tried on victory-native v0.17.3 demo containers-view.js, however it seems the prop `currentDomain ` only shows in `onBrushDomainChange ` `targetProps `  instead of `mutation `  function parameters: 
```
  removeMutation() {
    this.setState({
      externalMutation: undefined
    });
  }

  onBrushDomainChange(currentDomain, targetProps) {
    console.log(targetProps);
    this.curDomainX = currentDomain.x;
  }

  onTouchEnd() {
    // try to snap to closest tick
    this.curDomainX = this.curDomainX.map(x => round(x));

    this.setState({
      externalMutation: [{
        childName: "brush",
        target: "parent",
        eventKey: "all",
        mutation: (props) => {
          console.log(props);
          return {currentDomain: {x: this.curDomainX}};
        },
        callback: this.removeMutation.bind(this),
      }]
    });
  }

  render() {
    return (
      <ScrollView
        ...
      >
        ...
        <VictoryChart
          externalEventMutations={this.state.externalMutation}
          containerComponent={
            <VictoryBrushContainer
              ...
              name="brush"
              brushDimension="x"
              brushDomain={{ x: [1, 4] }}
              onBrushDomainChange={this.onBrushDomainChange.bind(this)}
              onTouchEnd={this.onTouchEnd.bind(this)}
            />
         ...
```

May I ask how to mutate this?
