### ISSUE TITLE
Axis label/Points showing as object in react native

### ISSUE THREAD

**Issue by sahilpandya** [FormidableLabs/victory#826]
Hi,

I am trying to use victory-native module, I resolved all errors according to readme, But my axis label are showing as object object. I am attaching screen shot below. Please help me to resolve these issue

<img width="320" alt="screen shot 2017-11-02 at 5 56 10 pm" src="https://user-images.githubusercontent.com/13818308/32427851-af5fad36-c2e8-11e7-9fff-12d83d261ff5.png">

and here is one of the code from example which i am trying to use.
`<VictoryLine height={300} domain={[0, 5]} padding={75} data={[ {x: 0, y: 1}, {x: 1, y: 3}, {x: 2, y: 2}, {x: 3, y: 4}, {x: 4, y: 3}, {x: 5, y: 5} ]} interpolation="cardinal" labels="LINE" style={{ data: { stroke: "#822722", strokeWidth: 3 }, labels: {fontSize: 12} }} />`

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-native#183
