### ISSUE TITLE
VictoryTooltip Clipped by edge of chart

### ISSUE THREAD

**Issue by purplecones** [FormidableLabs/victory#827]
If a `VictoryTooltip` is shown close to the edge of chart, it might get clipped.

![2017-11-06 11 41 21](https://user-images.githubusercontent.com/136654/32452879-c93ffd5a-c2e8-11e7-9ee5-35fddc6df8f6.gif)

Is it possible for the `VictoryTooltip` to be rendered outside of the chart container?

**Comment by Utzel-Butzel** [comment]
You most probably have to add `overflow: visible` to the svg container. Or remove `clip-path` if existing.
https://stackoverflow.com/questions/1572587/allow-svg-graphics-to-overflow-outside-the-containing-svg-element

**Comment by purplecones** [comment]
You're right. Looks like normalize.css was applying this rule:
```css
svg:not(:root) {
    overflow: hidden;
}
```

which was messing with the svg container.

**Comment by huyph** [comment]
any idea if it is possible to add `overflow: visible` to the svg container using victory prop `style={...}`? https://codesandbox.io/s/jjp8p0751w
