### ISSUE TITLE
innerRadius as a percent of radius

### ISSUE THREAD

**Issue by mcrummey** [FormidableLabs/victory#832]
The documentation shows an example of this, but it is failing.  
https://formidable.com/open-source/victory/docs/victory-pie/#innerradius

innerRadius as a percentage of radius would be extremely helpful.  I don't even know how to guess at how many pixels the innerRadius needs to be.

**Comment by wachunga** [comment]
Just starting to get familiar with victory. Seems like there are a few items like this (and automatic domainPadding) that would improve developer experience a lot.

**Comment by erick2014** [comment]
Hey I would like to work on this guys, or at least try haha

**Comment by boygirl** [comment]
Now that we have both `radius` and `innerRadius` and both may be given as functions, this requested feature no longer makes sense.
