### ISSUE TITLE
Axis labels offset issue

### ISSUE THREAD

**Issue by rk85097** [FormidableLabs/victory#834]
**Hi,** 

New to Victory Charts, all my axis labels comes out with offset. 
What am I missing?

<img width="62" alt="screen shot 2017-11-10 at 15 08 40" src="https://user-images.githubusercontent.com/5455346/32659877-347ab6c6-c629-11e7-8a9a-d071c20270af.png">

**Code:**
` <Svg width={400} height={400}>
  <VictoryAxis dependentAxis
    width={400}
    height={400}
    domain={[0, 100]}
    theme={VictoryTheme.material}
    standalone={false}
  />
</Svg>`

**Thanks!**

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-native#182
