### ISSUE TITLE
Use VictoryLine in Label component on MouseOver?

### ISSUE THREAD

**Issue by ajits731** [FormidableLabs/victory#836]
This is my Victory code, What I'm trying to do is to manipulate labelComponent to render VictoryLines on MouseOver On each node. A node is connected to few other nodes.
![qa](https://user-images.githubusercontent.com/25746981/32765792-2455f4fc-c932-11e7-848e-16580804fee5.jpg)

`<VictoryChart
                        domain={{x: [1989, 2020], y: [0, 12]}}
                        containerComponent={<VictoryVoronoiContainer/>}
                      >
                       <VictoryScatter
                       style={{
                          data: {fill: "tomato"}, labels: {fill: "tomato"}
                        }}
                        size={(datum, active) => active ? 5 : 3}
                        labels={(d) => d.y}
                        labelComponent={<VictoryTooltip/>}
                        data={all_data}
                        />
</VictoryChart>`

**Comment by boygirl** [comment]
@ajits731 that's an interesting problem! There are a couple things you could try

1) Render all the lines you want ahead of time, but make them transparent. Change their styles when you hover a particular point. Depending on how complicated the relationship between your lines and points is, you could just use functional styles with the `active` prop for this like `style={{ data: { stroke: (datum, active) => active ? "red" : "transparent" } }}`. You may have to dig into events. Here's a guide that can help: https://formidable.com/open-source/victory/guides/events

2) Create a custom `labelComponent` that would render both `<line/>` elements and a label. You can read about custom components here: https://formidable.com/open-source/victory/guides/custom-components/  Your label components will have access to the scale of the chart, so you will be able to translate data into svg coordinate space and determine the correct props for your lines.

I'm going to close this issue, but reach out to me directly in the [gitter channel](https://gitter.im/FormidableLabs/victory) if you need additional help.
