### ISSUE TITLE
render about labelComponents

### ISSUE THREAD

**Issue by x86kernel** [FormidableLabs/victory#840]
i wish labelComponents is not render when it is null

Although when give labelComponents props to some Victory Graph like

```
<VictoryPie
   labelComponents={<div text={ null } />}
/>

```
or

```
<VictoryPie
  labelComponents={<div text='undefined' />}
/>
```

is also not rendering labelComponents, but I think

```
<VictoryPie
  labelComponents={ null }
/>
```

is much easier.

What do you think about this? I will open pull request for this

**Comment by boygirl** [comment]
@x86kernel the much easier thing to do would be to just set all your labels to null when you don't want to render anything like `labels={() => null}`

**Comment by x86kernel** [comment]
@boygirl Oh, Thanks!
