### ISSUE TITLE
Bar Chart render 'toggles' itself from l->r then r->l

### ISSUE THREAD

**Issue by MikeB2012** [FormidableLabs/victory#842]
In a static page the rendering of a bar chart toggles itself from left->right to right->left and back ... sometimes ie. x-axis days increasing from left to right and then toggling to days decreasing from left to right.  The labeling remains correct and the data array is not changing. There is no obvious action or state that causes the change, just sitting there it spontaneously changes.  Anyone else had this problem?

**Comment by boygirl** [comment]
@MikeB2012 that's a new one! Can you reproduce this issue in a fiddle?

**Comment by MikeB2012** [comment]
Thanks for the quick reply but nope I'll close this.  Took me a while to find it but found a mutable operation in a render.  Lessons learned: less ambiguous variable names, read docs (array.reverse() mutates array), don't put ops like that in the render function ... what a day :-/
