### ISSUE TITLE
Trigger for manually clearing selections in VictorySelectionContainer.

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#843]
Currently, clearing a selection is tied to mouse events. It is desirable to manually clear selections.

**Comment by mbilokonsky** [comment]
Leaving a comment to track this. Having a hard time reasoning about how best to implement this.

**Comment by boygirl** [comment]
@mbilokonsky After spending some time with this issue yesterday, I think the correct solution involves adding support for externally triggered events in Victory's event system. I have to revise my  estimate about when this issue will be complete. I'll shoot for the week _after_ thanksgiving instead.

**Comment by boygirl** [comment]
use `externalEventMutations`: https://formidable.com/open-source/victory/guides/events/#external-event-mutations

**Comment by mazenchami** [comment]
@exogen @mbilokonsky were either of you able to get this working? if so, could you share what you put together?
