### ISSUE TITLE
font size not changing in VictoryLegend

### ISSUE THREAD

**Issue by aditya-simplecrm** [FormidableLabs/victory#844]
<VictoryLegend
                              x={5} y={5}
                              orientation="horizontal"
                              data={legendData}
                              standalone={false}
                              gutter={10}
                              itemsPerRow={3}
                              style={{ border: { stroke: "none" }, title: { fontSize: 8 } }}
                            />

**Comment by boygirl** [comment]
@aditya-simplecrm this has been fixed. Here's a working example: https://codesandbox.io/s/xovqm2zl6w

**Comment by tuulemall** [comment]
@boygirl Is it possible to change the style of the labels in the legend? I tried writing label:{fontSize:10, fill:'red'} everywhere with no success.

**Comment by boygirl** [comment]
@tuulemall I believe the namespace is `labels` instead of `label`. Give that a shot
