### ISSUE TITLE
Enabling animation causes slowness on line chart

### ISSUE THREAD

**Issue by tacomanator** [FormidableLabs/victory#847]
I have a line chart with about 3000 points total (multiple lines). The chart is pretty fast without animations but becomes very sluggish when animations are enabled. Not only the animations, however, the tooltips become very sluggish as well.

Demonstration: https://jsfiddle.net/tacomanator/3gLazk66/2/

Notice how hovering the line is quite fast, until animations are toggled on.

**Comment by tgoldenberg** [comment]
I'm also having this issue, particularly if you have the mouse over the area that is going to be rendered by the animation. Maybe it should disable the tooltips while in animation?

**Comment by walternicholas** [comment]
Same issue here.

I've been trying to hack together a fix which will disable tooltips while animating as tgoldenberg suggested above, but with no luck so far.

**Comment by elyobo** [comment]
In my case the slowness is definitely related to mouse hover (I do have a rather heavy tooltip); disabling tooltips during animation may help.

**Comment by beccanelson** [comment]
I believe this one is related to #1997. There are currently some issues around Victory kicking off animations and re-rendering when animations are enabled, but a chart isn't changing state (like if it is just showing/hiding a tooltip).

**Comment by becca-bailey** [comment]
Closing in favor of this larger issue https://github.com/FormidableLabs/victory/issues/2104
