### ISSUE TITLE
Tooltips stuck at the far right end of a horizontal bar

### ISSUE THREAD

**Issue by jeghers** [FormidableLabs/victory#849]
Greetings, I'm trying to add Tooltips to a horizontal stacked bar chart. The Tooltips ONLY appear at the far right end of the bar, which looks really weird, especially since the bars can have pretty long horizontal length. Any way I can make the Tooltip follow the mouse? The would look much nicer.

Or, alternately, is there a way for the tooltip to be nicely centered over the middle of the bar?

**Comment by younitee** [comment]
is there a resolution to this?  it is made especially weird when using a VictoryStack

**Comment by boygirl** [comment]
@jeghers @younitee 

This issue was just fixed in the latest version `victory@0.27.1`

**Comment by jeghers** [comment]
Too late. Moved on long ago.

**Comment by CharukaK** [comment]
@boygirl is there a sample of how to achieve this or a documentation explaining the props?
