### ISSUE TITLE
Tooltip inside text position is not coming right.

### ISSUE THREAD

**Issue by sahilpandya** [FormidableLabs/victory#852]
Hi, 
I am using VictoryVoronoiContainer for render tooltip but in tooltip text is not coming on right position. I am attaching screen-shot.

My `"victory-native": "^0.16.1","react-native": "0.40.0" and "react-native-svg": "5.1.8"`.
<img width="255" alt="screen shot 2017-11-17 at 11 50 59 am" src="https://user-images.githubusercontent.com/13818308/32932233-a7a0721c-cb8d-11e7-8d63-7ac046ac05c0.png">

**Comment by boygirl** [comment]
@sahilpandya `victory-native@~0.16.0` should be used with `react-native-svg@^6.0.0`. That should fix your offset issue.

**Comment by sahilpandya** [comment]
react-native-svg@^6.0.0 is not support react-native@0.40 version.
