### ISSUE TITLE
How to get tooltip to trail on Top of chart?

### ISSUE THREAD

**Issue by tgoldenberg** [FormidableLabs/victory#853]
I would like to have a tooltip that trails on the **bottom** of the chart. I have been able to get one to trail on the top of the chart with the following code. Any suggestions welcome!

```
<VictoryChart
    				theme={victoryTheme}
    				height={layout.height}
    				width={layout.width}
    				className="investments-chart"
    				domain={{ y: layout.yaxis.range }}
    				padding={{ top: 10, bottom: 15, left: 0, right: 65 }}
    				domainPadding={0}
  					containerComponent={
  						<VictoryVoronoiContainer
  							voronoiDimension="x"
  							portalZIndex={99999}
  							labelComponent={(
  								<VictoryTooltip y height={40} width={100} dy={5} orientation="bottom" />
  							)}
  							labels={(d) => `${formatCashNumbers(d.y)}\n${moment(d.x).format('ddd, MMM D YYYY')}\n${moment(d.x).format('h:mm a')}`}
  						/>
  					}
    			>
```

**Comment by boygirl** [comment]
@tgoldenberg you should be able to accomplish this very similarly to how your top tooltips are working. Set `orientation="top"` and `y={layout.height - padding.bottom}` on your tooltip. I'm going to close this issue for now, but I'll reopen it if you can't get that working.
