### ISSUE TITLE
Expose width/height of `VictoryLegend`?

### ISSUE THREAD

**Issue by rudasoftware** [FormidableLabs/victory#854]
I'd like to be able to compute the width and height of a `VictoryLegend` component, based on the current values of its labels to make sure I have enough padding allotted for it in the wrapping `VictoryChart`.

Is there a way to expose the relevant calculations as static methods?

**Comment by bgold0** [comment]
@boygirl Could you explain how to use this?

I try to use it in the following fiddle but I am getting a `width: NaN, height: NaN`

https://jsfiddle.net/803xmr24/4/

**Comment by malutanpetronel** [comment]
it looks I still get NAN

  const legendData = [
    { name: 'one' }, { name: 'two' }, { name: 'three' }
  ];
  const legendDimensions = VictoryLegend.getDimensions(
    {
      data: legendData,
      style: {
        fontSize: '12px'
      }
    }
  )
  useEffect(() => {
    console.warn(legendDimensions)
  }, [])

![image](https://user-images.githubusercontent.com/5830216/192967081-d505ad19-5205-457a-82a4-7ce7f12ef9ed.png)
