### ISSUE TITLE
In VictoryBrushContainer, clicking outside the brushed area brushes the whole domain

### ISSUE THREAD

**Issue by jmansor** [FormidableLabs/victory#855]
Steps:

* Go to https://formidable.com/open-source/victory/guides/brush-and-zoom/
* Change the brush domain.
* Click outside the brushed area in the bottom chart.
* The brushed area extends to cover the whole domain.

Is this the expected behavior? Is there any way to prevent this?

**Comment by boygirl** [comment]
@jmansor this is expected behavior, but I would be willing to add a prop to change it.

**Comment by jmansor** [comment]
Thanks for the response, I've seen some d3 examples like this one:

https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

with the same behavior. Yet, I think it would be nice to have a way to deactivate this, so that clicks outside the brushed areas has no effect.

Makes sense?

**Comment by mariogarcia** [comment]
Would it be possible to override the behavior through the `eventHandlers` attribute ?

**Comment by xrado** [comment]
@boygirl It would be nice to have an option to prevent this, maybe trough onBrushDomainChange when returning false, or leave brush untouched if only click happens.

**Comment by code4arpit** [comment]
@boygirl  I too stuck with this scenerio. Can we expext some good solution on this. I don't want to brush my whole chart when user clicked outside the brushed area. It is very annoying when we apply brush container on top of graph.
For example : https://formidable.com/open-source/victory/docs/victory-brush-container/

**Comment by boygirl** [comment]
Proposed solution:  
Add a new prop called `defaultBrushArea` that will accept options "all", "none", and "disable". Default behavior will be to select "all" to prevent the breaking change. Setting this prop to "none" will cause the brush area to be cleared when the user clicks outside of the brushed region. Setting the prop to "disable" will mean that clicks outside of the brushed region will have no effect on the brush. ETA April 4 2018. For those following this issue, please comment before April 2 if this solution is insufficient for your needs.

**Comment by code4arpit** [comment]
@boygirl I think you meant ETA May 4th and need to comment before May 2nd ?

**Comment by boygirl** [comment]
Yes! Sorry!

**Comment by code4arpit** [comment]
Hi @boygirl -> For better clarity on prop  "disable", i'm taking below example:-
Suppose my x-axis lies between 1-10 and y-axis between 1-20. If I brush my chart for 2-5 for domain X and If i clicked at other region but within the graph, let' say at coordinate (x= 7,y =15) , in this case it SHOULD NOT brush the whole area as we are setting the prop as "disable".
