### ISSUE TITLE
Scale Breaks and Log Scaling

### ISSUE THREAD

**Issue by JarLowrey** [FormidableLabs/victory#857]
I have data with [extreme value differences](https://ux.stackexchange.com/questions/36408/how-to-visualize-data-with-extreme-value-differences) and need to utilize a log scale or a scale break. Is there a standard way to do this in Victory? I am using a line graph and need to somehow communicate to users the large break in data values, which I don't think can be done by preprocessing the data somehow.

**Comment by boygirl** [comment]
@JarLowrey Victory doesn't have a built in way to accomplish scale breaks, but log scales are supported. Add something like `scale={{ y: "log" }}` to `VictoryChart`

**Comment by JarLowrey** [comment]
Are scale breaks on any roadmap? Can I request this feature?
