### ISSUE TITLE
Separate Axis Ticks than Data

### ISSUE THREAD

**Issue by KjellConnelly** [FormidableLabs/victory#859]
I have a VictoryChart which contains a couple VictoryAxis components and a VictoryArea. There are times when I have many data points (about 30), but only want to have the 5 categories showing, and 5 vertical lines. Otherwise, it’s way too crowded. 

I was able to get 5 categories by setting the categories to different blank strings[“”,” “,”  “,...] which is a bit of a weird workaround. But I can’t seem to figure out how to only have 5 vertical lines (using VictoryTheme.material). 

Any ideas? Can this even be done? Or do I need to make a custom chart?

**Comment by boygirl** [comment]
@KjellConnelly you will want to use the `tickValues` and `tickFormat` props on `VictoryAxis` A custom chart should not be necessary. Here's more information: https://formidable.com/open-source/victory/docs/victory-axis/#tickvalues
