### ISSUE TITLE
Add point to position in Line/Area chart when hovered

### ISSUE THREAD

**Issue by tgoldenberg** [FormidableLabs/victory#860]
How would I do something like the following? 

Particularly, how would I add an icon on the line when hovered over it? Thank you for any suggestions! 

<img width="666" alt="screenshot 2017-11-28 17 41 30" src="https://user-images.githubusercontent.com/10930134/33384517-3c0660fa-d4f4-11e7-9ce4-53151503dd7a.png">

**Comment by tgoldenberg** [comment]
So I was able to do this with a custom `Flyout` component (below), but the question still remains: How to render multiple Voronai Container tooltips? As shown above in the screenshot, there are effectively 3 moving tooltips - the top, bottom, and dot, as well as the verticle line that connects them. Any thoughts on how to have multiple Voronai tooltips? It seems that `labelComponent` does not take in an Array, but only a single Tooltip element.

```
class DotFlyout extends React.Component {
	render() {
		const { x, y, orientation } = this.props;

		return (
			<g>
				<circle cx={x} cy={y} r="5" stroke={Colors.brandTransparent} strokeWidth={1.5} fill="white"/>
			</g>
		);
	}
}
```

**Comment by walternicholas** [comment]
You can have your custom Flyout component draw the dot, the line, and the tooltip above and below.

**Comment by tgoldenberg** [comment]
Yep, that's how I did it, though I needed a custom `<Label />` component as well. Thanks!

**Comment by asibilia** [comment]
@tgoldenberg I realize this thread is pretty old, but I'm trying to implement something very similar, would you mind explaining how you were able to correctly size the colored background of your labels? I don't think `width` is exposed through the `VictoryLabelProps` so I'm struggling to position the background correctly.

I assume your custom labels look something like:

```
{/* top label */}
<g>
    <rect
        x={x - width / 2} <--- where does width come from
        y="0"
        height={} <--- ?
        width={} <--- ?
    />
    <text
        x={x - width / 2}
        y="0"
    >
        {props.text}
    </text>
</g>
```
