### ISSUE TITLE
Gutter not creating space between vertical legend rows

### ISSUE THREAD

**Issue by tacomanator** [FormidableLabs/victory#862]
According to `VictoryLegend` [docs](https://formidable.com/open-source/victory/docs/victory-legend):

> When orientation is vertical, gutters are the space between rows.

Currently gutter space is applied between columns instead of rows, regardless of orientation. Can be reproduced on [website](https://formidable.com/open-source/victory/docs/victory-legend) using orientation vertical with large gutter:

```jsx
<VictoryLegend x={125} y={50}
  orientation="vertical"
  gutter={300}
  style={{ border: { stroke: "black" } }}
  data={[{ name: "One" }, { name: "Two" }, { name: "Three" }]}
/>
```

<img width="703" alt="legend" src="https://user-images.githubusercontent.com/63794/33496906-cec7c90a-d680-11e7-914c-e2b6302f35e6.png">

Great job on this library guys!

**Comment by ebrillhart** [comment]
Seconding this!

**Comment by exogen** [comment]
One additional TODO here is to update the docs
