### ISSUE TITLE
Items in horizontal VictoryLegend have different spacing/margin

### ISSUE THREAD

**Issue by nlazarov** [FormidableLabs/victory#864]
The bug that I found is with the spacing between items in a legend when the labels have different sizes. Here is an example - https://codesandbox.io/s/z66jn11j4.

The spacing between the first and the second item is bigger that the spacing between the second and the third.

I would expect the spacing between the different items to be equal.

**Comment by boygirl** [comment]
@nlazarov legend items are placed to accommodate labels of varying lengths automatically. This is done by _approximating_ text size. Discrepancies between actual and approximate text sizes grow with character count, unfortunately. What you're seeing is an artifact of that approximation. 

The solution would be to improve our approximation (https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/textsize.js) or to actually render and measure each text element. I am very hesitant to implement the latter.

**Comment by nlazarov** [comment]
Thanks for the explanation @boygirl. Is the layout reflow and the performance hit related to it that stops you from considering the measuring approach?

For my case I guess recreating the legend outside the chart using HTML+CSS would also work.

**Comment by beccanelson** [comment]
This issue is most likely related to some more general issues with legend spacing and the fact that legend spacing only works with specific character sets. 

Related issue: https://github.com/FormidableLabs/victory/issues/531

**Comment by becca-bailey** [comment]
Closing in favor of this larger issue https://github.com/FormidableLabs/victory/issues/2108
