### ISSUE TITLE
Change [cornerRadius] prop to support rounding edges on both sides

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#867]
_From @FranciscoMurias on November 17, 2017 9:28_

It would be extremely useful to change the `cornerRadius` prop to also support objects like these: 
`cornerRadius={{ top: 10, bottom: 10 }}`
The corner radius only being applied on top atm, and it would give users a greater element of customizability to their graphs.

This would allow for graphs like this:

![pasted_image_at_2017_11_14_11_19_am-1](https://user-images.githubusercontent.com/21249529/32940235-05ffab66-cb7a-11e7-98e7-c410009285b7.png)

At the moment we can only do this:

![screen shot 2017-11-16 at 6 19 11 pm](https://user-images.githubusercontent.com/21249529/32940241-098b4588-cb7a-11e7-9ebb-9ae7213ad192.png)

This would also be extremely useful in the pieChart graph for situations like this:

![pasted_image_at_2017_11_14_11_19_am-2](https://user-images.githubusercontent.com/21249529/32940271-1ad91eb4-cb7a-11e7-917b-207e27f084cb.png)

Being able to define either a global corner radius for the start and end point of a graph, or give it a object setting each individual edge is a cool option to have ;)

_Copied from original issue: FormidableLabs/victory-native#191_

**Comment by boygirl** [comment]
Implementation:
```
cornerRadius: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.shape({
      top: PropTypes.number, bottom: PropTypes.number
    })
  ])
```
When given as a single number it will apply only to the top corners to avoid the breaking change.

**Comment by nthegedus** [comment]
Sorry but I didn't get how do I implement this. Someone could explain?

I need to use cornerRadius on top and bottom too.

**Comment by alansutherland** [comment]
@boygirl please give an example of how we implement this, your code just shows what you're changing on the core code
