### ISSUE TITLE
[Victory Pie] Ability to specify sort order 

### ISSUE THREAD

**Issue by naveenblipp** [FormidableLabs/victory#870]
`<VictoryPie />` supports `sortKey` to sort the data for rendering the pie chart, very useful feature. 
However it doesn't allow us to specify the sortOrder, this always sorts in ascending order (probably because of loadash's sortBy)

The use case we have requires the descending order. One way for us is to supply sorted data to pie, but do you think it makes sense to support sortOrder as well? 

Thanks!

**Comment by boygirl** [comment]
@naveenblipp 

I would accept PRs that add an `sortOrder` prop and reverse the collection returned by lodash `sortBy` when set to "descending".

**Comment by naveenblipp** [comment]
Thanks @boygirl  Let me take a stab at this one.

**Comment by naveenblipp** [comment]
Hey @boygirl 

Created couple of PRs to add `sortOrder` prop for `victory-pie`
FormidableLabs/victory-core#322
https://github.com/FormidableLabs/victory-pie/pull/160
