### ISSUE TITLE
How do I increase Line Height within VictoryTooltip

### ISSUE THREAD

**Issue by tkiethanom** [FormidableLabs/victory#871]
Is there a built in way to increase the line height or line spacing inside of a VictoryTooltip that has multiple lines? In my codesandbox sample I'm unable to find a way to do that. 

https://codesandbox.io/s/ko5x69z9ov

**Comment by boygirl** [comment]
@tkiethanom you can do it like this:

```
const tooltip = (
  <VictoryTooltip 
   labelComponent={<VictoryLabel lineHeight={2}/>}
   style={[{ fontSize: 10 }, { fontSize: 15 }]} 
  />
);
```

**Comment by tkiethanom** [comment]
@boygirl This works great thanks!

Updated sandbox https://codesandbox.io/s/6jpqxqzk5w

I used style lineHeight to add spacing around each line.
