### ISSUE TITLE
How to set VictoryChart width same as container width ?

### ISSUE THREAD

**Issue by sovanjana** [FormidableLabs/victory#872]
I'm using flex for my container and I want VictoryChart width = 100% and height = 100% ...
```
<VictoryChart
  domainPadding={20}
  height={300}  // this should be 100% so that it acquire the container height
  width={1300}  // his should be 100% so that it acquire the container width
>
  // . . .
</VictoryChart>
```

**Comment by sovanjana** [comment]
@

**Comment by boygirl** [comment]
@sovanjana Victory renders into responsive containers by default using the `viewBox` attribute. This causes it to maintain a specific aspect ratio while trying to fill your container as much as it can. The aspect ratio is controlled by the width and height props. You can alter those as the size of your container changes, or set `responsive={false}` and set a manual width and height. Here's a description: https://formidable.com/open-source/victory/docs/faq/#how-can-i-change-the-size-of-my-chart
