### ISSUE TITLE
"Stuck Victory Chart" - Multiples rendering of Portal prop while using Victory Chart

### ISSUE THREAD

**Issue by haris-ramzan** [FormidableLabs/victory#876]
@boygirl here it is my issue, I have verify the re-rendering of Victory Chart prop. For my team, this is by far the biggest problem right now. It makes our app unstable. I have tried "why-did-you-update" module to check which prop of the component re-render frequently.So, the ```Portal``` prop comes from Victory Chart to stuck my app page. 
Here is my Victory Chart Implementation :
```
<VictoryChart
      scale={{ x: 'time', y: 'linear' `}}
      height={127}
      containerComponent={<VictoryVoronoiContainer />}
      style={{ parent: { display: 'block' } }}
     >
<VictoryArea
      data={ChartData}
      interpolation="natural"
      labelComponent={<VictoryTooltip />}
     />
</VictoryChart>
```

Versions are : 
"victory": "0.24.3",
"why-did-you-update": "0.1.0",
"react": "16.2.0",
"react-dom": "16.2.0"

**Comment by boygirl** [comment]
@haris-ramzan Thank you for this issue. I'll try to figure out why that's continuously re-rendering

**Comment by stefvhuynh** [comment]
hello @haris-ramzan, i can't seem to reproduce your issue. i have copied your code and checked for unwarranted re-renders and i don't see anything. is there something happening with your `ChartData` prop? perhaps it's changing unexpectedly?
