### ISSUE TITLE
Polar VictoryArea requires 2 data points

### ISSUE THREAD

**Issue by JarLowrey** [FormidableLabs/victory#878]
# Bugs and Questions

### Checklist

* [ ]x This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x ] I am using the latest version of Victory

* [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using a polar VictoryArea, 2 data points are required. Only 1 data point should work (in my opinion) for a polar graph, since everything is relative to center. Workaround: add another data point at 0,0. However, this messes up the ToolTip, so ToolTip must be suppressed if X or Y are this certain dummy value. This does not seem to be possible.

### Reprodution

Scroll down to the `polar` section of the [`VictoryArea`](http://formidable.com/open-source/victory/docs/victory-area/#data) docs. In the live-editable code, paste in `[{"x":1,"y":2},{"x":2,"y":3}]` instead of `sampleData`. Then try `[{"x":2,"y":3}]`. This will display NaN.

**Comment by boygirl** [comment]
@JarLowrey a single data point isn't generally appropriate for `VictoryArea`. You can selectively suppress the tooltip like this:

`labels={(datum) => datum.x === 0 && datum.y === 0 ? null : "yourFormattedLabel"`
