### ISSUE TITLE
Victory Website Doc Links Do Not Work In New Tabs/Windows

### ISSUE THREAD

**Issue by foxmicha** [FormidableLabs/victory#879]
### The Problem

Links throughout the documentation are not setup properly. At some point the docs were put within an "open-source/victory" folder but the links within these docs have not been updated to reflect that. For example:

https://formidable.com/open-source/victory/docs/victory-bar/

The first link is to the Victory Chart page but it links to this address:

 https://formidable.com/docs/victory-chart

This returns a 404 on navigation, making navigating through the docs frustrating.

### Reproduction

Attempt to click any link found within the docs pages. The sidebar appears to have been updated but the links within each doc is not.

I'm sorry to open this on Github, but I couldn't find a more suitable place to make this known.

**Comment by foxmicha** [comment]
Correction: The links work within the same browser window or tab but do no work when attempting to open the links in a new tab.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#482
