### ISSUE TITLE
Polar VictoryChart cannot pan

### ISSUE THREAD

**Issue by JarLowrey** [FormidableLabs/victory#880]
# Bugs and Questions

### Checklist

* [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ x] I am using the latest version of Victory

* [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have set up zoom & voronoi (tooltips) but I have noticed that in a polar graph you cannot pan. Attempting to do so just zooms in/out. Is there any way to get this working?

```js
const VictoryZoomVoronoiContainer = createContainer("zoom", "voronoi");
<VictoryChart
        polar                
        containerComponent={
            <VictoryZoomVoronoiContainer
                allowPan //doesnt work
                ...
```

**Comment by boygirl** [comment]
@JarLowrey Yes, Currently zoom functionality for polar charts is limited to center only zooming, and panning is disabled. The reason this hasn't been implemented yet is because of confusion on my end about how panning should work for polar charts. Can you give some detail about your use case, and how the panning should work.

**Comment by JarLowrey** [comment]
I have data that has drastically different magnitudes that I would like to display on the same chart. I believe a polar/radar chart is best for this data due to the content. 

Some data extends out to the edges, others are very close to the origin, others are somewhere in-between. The user should be able to inspect them all and hover over to read the Tooltip.  Users should be able to zoom in, pan to the large data, zoom in further, pan to the small data.

**Comment by JarLowrey** [comment]
Also, is there any way to speed up zoom speed? Scrolling on a polar graph is way too slow. I'm currently trying to scale the difference in `domain` and `this.state.zoomDomain` between calls of  `handleDomainChange`, but am not having much luck with it.

**Comment by beccanelson** [comment]
Since there hasn’t been any discussion on this issue in a few years, I’m going to close this for now in an effort to clean up some of our older issues. Let me know if it needs to be re-opened!
