### ISSUE TITLE
Polar VictoryChart does not add new categories with new data

### ISSUE THREAD

**Issue by JarLowrey** [FormidableLabs/victory#881]
# Bugs and Questions

### Checklist

* [x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ x] I am using the latest version of Victory

* [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using a radar/polar VictoryChart, if you have categorical data then the chart will not reorganize if the user adds more data. In my app the user sequentially selects different products, which may or may not have certain attributes. Only the attributes/categories in the first data selection are visible on the chart.

**Comment by boygirl** [comment]
@JarLowrey can you provide a simple reproduction of this issue in a [code sandbox](https://codesandbox.io/s/m3xo745x2x)?

**Comment by JarLowrey** [comment]
Sorry I didn't have time yesterday. Here's a perfect example of what I'm talking about - https://codesandbox.io/s/8l8zqxv6n9 You can see that changing the displayed areas after 500ms does not affect the axis categories

**Comment by becca-bailey** [comment]
This is not reproducible in the latest version of Victory. Here's an updated sandbox: https://codesandbox.io/s/interesting-firefly-6swws?file=/src/App.js.
