### ISSUE TITLE
Some areas of some points in VictoryScatter is not responsive to mouse over events

### ISSUE THREAD

**Issue by ersinciftci** [FormidableLabs/victory#882]
# Bugs and Questions

### Checklist

* [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of Victory

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a simple VictoryScatter and I make a div in the page visible in `onMouseOver` handler of the points and make it invisible in `onMouseOut`. So I expect it to stay visible while I move the mouse over a single point. But some points has some random areas (sometimes the center, sometimes the upper half etc.) that behaves like an empty area, and when the mouse goes there, it fires `onMouseOut` even though the mouse is still over the point.

### Reproduction

You can see it in https://codesandbox.io/s/j72lqkoqk5. There is an invisible vertical and a horizontal line in the center that makes `Test` text on the bottom disappear when the mouse is over those areas. But it's not always the same pattern, different charts with different data have different invisible area patterns. Sometimes more than half of the point's visible area is unresponsive to mouse over events.

**Comment by boygirl** [comment]
@ersinciftci sorry for the delay

What's going on is that the mouse is hovering over transparent grid lines. You can fix this behavior in a couple of ways.

1) add `pointerEvents: "none"` to your grid styles like so: https://codesandbox.io/s/40wn42yj69
2) Make sure your axes are rendered _before_ the rest of the components so that the gridlines end up _under_ the scatter points like so: https://codesandbox.io/s/1rv39nw7xq

**Comment by ersinciftci** [comment]
@boygirl apparently my issue was rendering a VictoryLine *after* the VictoryScatter (I was rendering the axes before it), so it was interrupting the mouse events in a kind of random fashion. Your answer helped me to figure it out, thanks!
