### ISSUE TITLE
How to remove strokeWidth from Candles in Candlestick?

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#886]
_From @kesha-antonov on December 25, 2017 19:42_

# Bugs and Questions

### Checklist

* [x] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of `victory-native`

* [x] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm trying to remove borders of Candles in Candlestick. If I set ```style={{data:{strokeWidth: 0}}}``` then Wicks will disappeared. So I see that strokeWidth apply to Candle and Wicks in the same time. Can you separate them in different props please?

### Reproduction

1) Open https://formidable.com/open-source/victory/docs/victory-candlestick/#style
2) Set ```strokeWidth=0```

Before:

![screen shot 2017-12-25 at 22 41 48](https://user-images.githubusercontent.com/11584712/34342555-d8abb718-e9c4-11e7-94db-cb3ee80f9ba2.png)

After:

![screen shot 2017-12-25 at 22 41 53](https://user-images.githubusercontent.com/11584712/34342556-dcc269e6-e9c4-11e7-82ca-22f3e14352f7.png)

_Copied from original issue: FormidableLabs/victory-native#224_

**Comment by boygirl** [comment]
@kesha-antonov I am going to move this issue to the main victory library and label it as a feature request

**Comment by kesha-antonov** [comment]
Thanks!

**Comment by boygirl** [comment]
Changes:
- Render the wick in two line segments so that it never appears to go through the box
