### ISSUE TITLE
Fix the brush container gallery (Easy fix :) )

### ISSUE THREAD

**Issue by jbockerstette** [FormidableLabs/victory#887]
This is an easy one.

The gallery http://formidable.com/open-source/victory/gallery/brush-zoom/
is broken. I followed that example and had a very tough time finding the problem. Long story short, the source code `victory-chart/demo/components/victory-brush-container-demo.js` is correct and does not have the flaw. Please update your gallery to use 
`victory-chart/demo/components/victory-brush-container-demo.js`

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#485
