### ISSUE TITLE
Tooltip gets cutoff if any animation is running on component

### ISSUE THREAD

**Issue by ovarunendra** [FormidableLabs/victory#889]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When I use the `VictoryTooltip` and any `animation` is running on the component, my tooltip is getting cut-off from the svg. 
<img width="538" alt="screen shot 2018-01-03 at 1 26 26 pm" src="https://user-images.githubusercontent.com/6458789/34513126-8badf1dc-f08c-11e7-8677-3290b12989ec.png">

If I remove the Animation component then its working fine.
Note: It is working fine with version `0.19.0` with animation also.

### Reproduction

Please use the below jsFiddle which has the reproduction code
[https://jsfiddle.net/vpsingh016/v6jpugk3/3/](https://jsfiddle.net/vpsingh016/v6jpugk3/3/)

**Comment by boygirl** [comment]
This issue has been resolved.
