### ISSUE TITLE
Allow VictoryVoronoiContainer diagram to ignore charts that are only for annotation purposes

### ISSUE THREAD

**Issue by petekp** [FormidableLabs/victory#890]
# Feature Request

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist
* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

`VictoryVoronoiContainer` currently generates a diagram using the data from all child charts. This poses a problem when one of the child charts is intended for annotation purposes. For example, I have two chart-types, `VictoryBar` and `VictoryLine`. The bar chart is intended to be interactive and to show tooltips using VictoryVoronoiContainer's `labelComponent` prop. The line chart is merely annotative and is not intended to be interactive and it would be preferred that it not affect the voronoi diagram at all.

A potential solution might be to provide a boolean `annotation` or `voronoiIgnore` prop on child components that `VictoryVoronoiContainer` will skip when constructing the diagram.

### Reproduction
https://codesandbox.io/s/vkym9565y

**Comment by boygirl** [comment]
I think my preferred implementation would be to add a `voronoiBlacklist` prop to `VictoryVoronoiContainer`. The prop would take an array of strings corresponding to the `name` prop on each child. Children with names matching those in the blacklist will not be taken into account when calculating a voronoi diagram or matching.
