### ISSUE TITLE
Displaying smallest tick value without using tickValues when using VictoryAxis

### ISSUE THREAD

**Issue by huyph** [FormidableLabs/victory#891]
### Checklist

* [ X ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [ X ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ X ] I am using the latest version of Victory

* [ X ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

By default (without specifying `tickValues={[...]}`), the smallest value on VictoryAxis does not show.
![screen shot 2018-01-04 at 2 22 21 pm](https://user-images.githubusercontent.com/3280795/34553643-405fb06a-f15b-11e7-8cf2-ebb4a03d18e6.png)

I can work out values for `tickValues`, but then these tick values won't be auto created when zooming in and out, with `VictoryZoomVoronoiContainer` (`VictoryZoomVoronoiContainer = createContainer('zoom', 'voronoi');`)

### Reproduction
https://codesandbox.io/s/p3wqv6o73m where value 0 does not display.

**Comment by boygirl** [comment]
@huyph This is a default behavior that you can override by setting `crossAxis={false}` on your axis components

**Comment by huyph** [comment]
Ah right. Thanks @boygirl
