### ISSUE TITLE
Allow VictoryLabel to render multiple text inline

### ISSUE THREAD

**Issue by matt-hernandez** [FormidableLabs/victory#893]
### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I would like for there to be an option to have `VictoryLabel` render multiple `</tspan>` elements inline as opposed to on a new line.

I'm currently making a bar chart based off this design:

(screenshot from Sketch)
![screen shot 2018-01-09 at 4 43 50 pm](https://user-images.githubusercontent.com/7357877/34747371-9ebde1ee-f55d-11e7-98a4-9a677f020558.png)

So I have two chunks of text: "% of Target", "44% for 2017". My first impulse was to use `Victory Label`. I wrote this jsx:

```jsx
<VictoryLabel x={15} y={20}
  text={[ '% of target', '44% for 2017' ]}
  style={[{ fill: '#000' }, { fill: '#6128ff' }]}
/>
```

The rendered output looks like this:

(screenshot from Chrome)
![screen shot 2018-01-09 at 4 56 21 pm](https://user-images.githubusercontent.com/7357877/34747476-0fe9aa92-f55e-11e7-9b93-6a982b0814d6.png)

Maybe there could be a `inline` attribute to tell `VictoryLabel` to render inline instead of multiline.

**Comment by parkerziegler** [comment]
FYI @matt-hernandez [this PR](https://github.com/FormidableLabs/victory-core/pull/328) took care of this issue. You should see the prop added in a future release of Victory.
