### ISSUE TITLE
Add cursorDimension in VictoryVoronoiContainer

### ISSUE THREAD

**Issue by cosio55** [FormidableLabs/victory#894]
# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Hello and first of all I would like to thank you A LOT on this amazing library. I don't really know if this is a feature request or just a question and I haven't found the answer yet in the docs. I'm using the VictoryVoronoiContainer on a chart, and it works great, but I would love to get the cursorDimension as you can do in VictoryCursorContainer, because I'm using this on a react-native project and it would be great to have a line that gives you feedback on where exactly is your finger pointing, because sometimes you can't really see the whole label.

**Comment by boygirl** [comment]
@cosio55 you can use the `createContainer` helper to make a container with both voronoi and cursor behaviors. You can read more about it here: https://formidable.com/open-source/victory/docs/create-container/
