### ISSUE TITLE
VictoryBar cornerRadius incorrect when value is 0 or small

### ISSUE THREAD

**Issue by CherishIt** [FormidableLabs/victory#895]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

VictoryBar cornerRadius incorrect when value is 0 or relatively small.

### Reproduction
![screen shot 2018-01-10 at 6 50 04 pm](https://user-images.githubusercontent.com/14925238/34768920-2bc9088c-f637-11e7-8f1a-0f8dcb1054a4.png)

https://codesandbox.io/s/8pyq1m1pw2

**Comment by manjula91** [comment]
Can I work on this ?

**Comment by boygirl** [comment]
Thank you!

**Comment by hernquist** [comment]
There is no way using a function with cornerRadius?
