### ISSUE TITLE
Allow theme to style independent axis separately from dependent axis

### ISSUE THREAD

**Issue by dlopuch** [FormidableLabs/victory#896]
# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Unless there's a detail I didn't see in the default themes, it seems that a theme's `axis` is used by BOTH the independent and dependent axes. It would be great if you could style the two separately.

Use cases include:
- Instead of a full grid, do only horizontal lines (eg `dependentAxis.style.grid = null` while `independentAxis.style.grid = {...}` )
- Color x-axis tickLabels differently than y-axis tickLabels
- Minimal styling: Don't draw axis on y-axis, draw it on x

Suggested API: allow theme to have two new attributes: `independentAxis` and `dependentAxis`. They get merged with existing `axis` styling for shared attributes (and backwards compatibility).

Workaround is just passing custom styling to each `<VictoryAxis style={...} />`, but that kinda defeats the purpose of having a unified theme.

**Comment by boygirl** [comment]
@dlopuch this is already possible. Use the `dependentAxis` and `independentAxis` namespaces in your theme object. They will be merged with any styles in the `axis` namespace

**Comment by dlopuch** [comment]
Works perfectly as expected, thanks.

Is this documented anywhere?  Would be helpful to add an example of this to the [default](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-theme/grayscale.js) [themes](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-theme/material.js) or even add this as a note to the [Axis.dependent](http://formidable.com/open-source/victory/docs/victory-axis/#dependentaxis) prop documentation.  The theming documentation and guide don't really provide any details beyond the example themes.
