### ISSUE TITLE
Add static functions to `getDimensions` of components

### ISSUE THREAD

**Issue by rudasoftware** [FormidableLabs/victory#898]
When assembling a more complex chart (with multiple titles/labels not derived directly from `data`, legends that can appear in different places depending on user input, etc.), increasingly complicated layout calculations are necessary to keep everything aligned.

I really dislike hard-coding magic values. When something changes on my end (e.g. different font size or padding) or on the users' end (e.g. string of a longer length than previously encountered), the rounds of manual tuning are tedious and discourage rapid iteration.

It would be amazing to have static methods to call (perhaps accepting relevant component prop values) to pre-calculate the size (if only the bounding box) of components like `VictoryLegend` or a `VictoryAxis` including its `tickLabels`

**Comment by jjenzz** [comment]
@boygirl whenever I call `VictoryLegend.getDimensions({ data, itemsPerRow })` I get `NaN` back for `height` and `width`. How do I use this static method?
