### ISSUE TITLE
Add Option to Have Tooltip Follow Mouse

### ISSUE THREAD

**Issue by mattoni** [FormidableLabs/victory#899]
As discussed on gitter, it would be great to have an option to allow a tooltip to have the same behavior for single data points as it does for multi: follow the mouse on hover. Otherwise, we need to manually add a bunch of events and inflate the codebase.

Thanks!

**Comment by boygirl** [comment]
add `x` and `y` label mutations when set to true

**Comment by parkerziegler** [comment]
@mattoni @boygirl Am I getting the behavior right here? Essentially, the tooltip follows the mouse on single points as well as multi-points, rendering the value of the active Voronoi point. I introduced a new prop called `bindTooltipToMouse` that's just a simple `boolean`. Removing this prop leaves the behavior as is. Let me know thoughts and I can put in a PR for it if it seems like it meets everyone's needs.

![formidable-victory-bind-tooltip-to-mouse](https://user-images.githubusercontent.com/19421190/35076703-8e4c39da-fbae-11e7-8427-faaca38e5f8a.gif)

**Comment by parkerziegler** [comment]
Here's [the repo](https://github.com/parkerziegler/victory-chart) for reference. [And the lines to pay attention to](https://github.com/parkerziegler/victory-chart/blob/1aeb52ba688e873746c694a324fb20dd5fa99426/src/components/containers/victory-voronoi-container.js#L116-L149). Essentially, if the `bindTooltipToMouse` prop is `true`, we have the label position track the mouse position exactly even when `points.length < 2` (i.e. single points!). We can add more flexibility to this prop based on what you think is best @mattoni and @boygirl. Please also let me know if I'm missing major parts of the feature request.

**Comment by mattoni** [comment]
Any update on this @boygirl

**Comment by parkerziegler** [comment]
@boygirl Let me know if you want me to put a PR in for this – could find time this weekend for it! 🎉

**Comment by mattoni** [comment]
Did this end up getting pulled in?

**Comment by mattoni** [comment]
Follow up, how can I make the tooltip follow the mouse but NOT stop at the svg width? The tooltip component doesn't seem to want to go outside the boundaries and bumps up against it instead of following the mouse.

**Comment by boygirl** [comment]
This has been added to `VictoryVoronoiContainer` but does only work with mouse move events within the chart area

**Comment by minimalistech** [comment]
Hi @parkerziegler  I can't get this functionality to work on iOS, am I missing something? The tooltip only shows up on tap. I am using victory-native 34.1.0 with the following code:

        <VictoryChart
          width={Dimensions.width}
          height={300}
          theme={theme}
          containerComponent={ 
            <VictoryVoronoiContainer 
              cursorLabel={({ datum }) => {datum.x,datum.y} } 
              bindTooltipToMouse={true} 
            /> 
          }
        >
          <VictoryLine
            labelComponent={<VictoryTooltip renderInPortal={false} />}
            data={data}
          />

          <VictoryScatter 
            data={data}
            size={3}
          />

        </VictoryChart>

Thanks!
