### ISSUE TITLE
How to use json data from props to VictoryPie

### ISSUE THREAD

**Issue by vikkya** [FormidableLabs/victory#900]
This is my Json data format: [data](http://api.myjson.com/bins/no07h) .

i'm using VictoryPie . with sample data
 data={[
                  { x: "Desktop", y: 35 },
                  { x: "Tablet", y: 40 },
                  { x: "Mobile", y: 55 }
                 ]}

how can i fit my json data into VictoryPie data. any help please.

**Comment by boygirl** [comment]
@vikkya you can use the data accessor props to map your json field names to x and y like this:
`x="deviceName"`. You can read more about data accessors here: https://formidable.com/open-source/victory/guides/data-accessors/

**Comment by vikkya** [comment]
Thank you team @boygirl it worked. :)
