### ISSUE TITLE
For a multiline VictoryLabel, I would like to have different lineHeights per line.

### ISSUE THREAD

**Issue by sbcreates** [FormidableLabs/victory#902]
# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I would like to create a pie chart that is styled like this:

![image](https://user-images.githubusercontent.com/30477884/35001969-250abcce-fab6-11e7-994b-299d182af8a1.png)

I can create multiline text and I can style each line of text individually with its own color and font size. However, I can't individually apply line height for each line and it's resulting in spacing issues because of the different font sizes.

-------------------

```
      <VictoryPie
          standalone={false}
          height={600}
          width={600}
          data={data}
          colorScale={['green', 'lightgray']}
          innerRadius={225}
          labelRadius={700}
          style={{ labels: { fontSize: 20, fill: 'black' } }}
      />
      <VictoryLabel
          textAnchor="middle"
          //lineHeight={[{1.22}, {2}, {3}, {1}]} <-- doesn't work
          x={300} y={300}
          style={[{ fontSize: 50, fill: '#203648' }, { fontSize: 70, fill: 'green' }, { fontSize: 30, fill: 'gray' }, { fontSize: 30, fill: 'gray' }]}
          text={[title, remaining, 'remaining', 'of ' + total]}
      />
```

![image](https://user-images.githubusercontent.com/30477884/35002265-2067fc94-fab7-11e7-8e9e-41168a719fc0.png)
This is what I currently have. I would like to customize spacing between the lines of text. The `title` and `remaining` spacing is off and I cannot currently figure out how to correct it.

**Comment by boygirl** [comment]
@sbcreates This is most easily accomplished by using multiple VictoryLabel components.
