### ISSUE TITLE
How to achieve labels on top of bar of bar chart

### ISSUE THREAD

**Issue by vikkya** [FormidableLabs/victory#905]
Hi,

I'm trying to get my labels top of bars of bar chart. i tried this [https://jsfiddle.net/1Lu96jq0/3/](https://jsfiddle.net/1Lu96jq0/3/)/ but im not able to get the desired output as needed. i have also attached a image as i need.  i also tried `labelComponent={<VictoryLabel  dx={-15} dy={-30} />}` but this is not working as needed. Maybe im using it in wrong way.
![barchart](https://user-images.githubusercontent.com/26187350/35041477-ee1e2d72-fbaa-11e7-9bdc-5cb7a2e7a5dd.png)
Can u please help me.

**Comment by boygirl** [comment]
@vikkya you will want to alter the x value on your VictoryLabel.  Something like this: https://jsfiddle.net/wdsqbby7/

**Comment by vikkya** [comment]
thanks @boygirl  Team great help
