### ISSUE TITLE
VictoryBrushAxis

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#906]
`VictoryBrushAxis` will render an axis component with an active brush area rendered on top of the axis line. The brushing behavior will be similar to the in `VictoryBrushContainer`, except it will only brush in a single dimension (the dimension of the axis). `VictoryBrushAxis` will make it possible to render multiple, independent brush components on a single chart, and to control the exact placement of each brush. This d3 example shows how multiple brushes may be useful: 
https://bl.ocks.org/jasondavies/1341281

Details: 

`VictoryBrushAxis` will render an axis as usual, with a brush-able rectangular area drawn over the axis line. The brush area will span the entire length of the axis, and will have a width defined by a prop `brushWidth`. The brush area will be styled with the namespace `brushArea` and will have default events:
- `onMouseOver` and `onMouseOut` will set ` active` on the brush area component (enabling hover styles)
- `onMouseDown`, `onMouseMove` and `onMouseUp` will control the brushing behavior. These events will be very similar to those in `VictoryBrushContainer`. Code will be reused as much as possible

When a brush is active, `VictoryBrushAxis` will render a rectangular brush with handles. These will be styled with the namespaces `brush` and `brushHandles` respectively. 

When the size of the brush changes, the function `onBrushDomainChange` will be fired with arguments `newDomain` and `props`

Limitations: 

Because `VictoryBrushAxis` will not know about other `VictoryChart` children, any child mutations that should result from a brush domain change will need to be handled external to the `VictoryBrushAxis` component. This can be done via the `onBrushDomainChange` callback, and the `externalEventMutations` prop on `VictoryChart`.

**Comment by boygirl** [comment]
Updates:

Rather than `VictoryBrushAxis`, a more general `VictoryBrushLine` component will be created. This component may be used in place of any `<Line/>` component. (i.e. `axisComponent`, `gridComponent`). It will render the original line, as well as `brushArea`, `brush` and `brushHandle` components. The events on this component will be registered to the appropriate target with the `type` prop. Components that currently use the `Line` prop will be altered to provide `type`, `dimension` and `scale`

**Comment by manjula91** [comment]
Is anyone working on this stuff?

**Comment by boygirl** [comment]
Yes, this is currently in progress and should be released next week

**Comment by manjula91** [comment]
cool :)

**Comment by boygirl** [comment]
released in `victory@^0.25.0`
