### ISSUE TITLE
Is there some way to apply a Text/View inside of a VictoryPie component?

### ISSUE THREAD

**Issue by obetomuniz** [FormidableLabs/victory#907]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Question

I want to know if is possible add that `99%` inside of my pie chart. 

![group](https://user-images.githubusercontent.com/1680157/35285465-97de5b8c-0044-11e8-9e72-7a598943bff0.png)

**Comment by boygirl** [comment]
@obetomuniz yep! Check out this example in our gallery: https://formidable.com/open-source/victory/gallery/victory-pie-center-label/

**Comment by obetomuniz** [comment]
Thanks @boygirl! 😀

**Comment by prajwalbhatia** [comment]
This page is not found...Please tell me how to achieve this?

**Comment by obetomuniz** [comment]
Check it out @prajwalbhatia https://formidable.com/open-source/victory/gallery/victory-pie-with-center-label

**Comment by prajwalbhatia** [comment]
@obetomuniz Thank you so much for responding so quick :-)

**Comment by sorxrob** [comment]
> Check it out @prajwalbhatia https://formidable.com/open-source/victory/gallery/victory-pie-with-center-label

can we also use custom component instead of `VictoryLabel`?

**Comment by yocheved-check-in** [comment]
> > Check it out @prajwalbhatia https://formidable.com/open-source/victory/gallery/victory-pie-with-center-label
> 
> can we also use custom component instead of `VictoryLabel`?

did you found an answer for this?

**Comment by jforaker** [comment]
The example isn't documented correctly - please see https://snack.expo.io/Ch5Uon3vI for a working implementation. 

My guess after some trial and error is you have to wrap the Chart and Label in an `<Svg />`

**Comment by jforaker** [comment]
@yocheved-check-in you can pass in a labelComponent prop, like [this](https://formidable.com/open-source/victory/guides/custom-components/)

```js

  <VictoryBar
    data={[
      {x: 1, y: 3, label: "Alpha"},
      {x: 2, y: 4, label: "Bravo"},
      {x: 3, y: 6, label: "Charlie"},
      {x: 4, y: 3, label: "Delta"},
      {x: 5, y: 7, label: "Echo"},
    ]}
    labelComponent={
      <MyComponent/>
    }
  />
```
