### ISSUE TITLE
VictoryPie chart using LinearGradient is drawing gradient with wrong angle.

### ISSUE THREAD

**Issue by obetomuniz** [FormidableLabs/victory#908]
# Bugs and Questions

### Checklist

* [] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Question

I want to use LinearGradient with VictoryPie chart. I can do it, but the gradient degree angle is not correct in some cases, I need to know the exact startAngle and endAngle that each item in my data list represent inside of the pie chart tto define the gradient direction properly. Is it possible?

This is the expected behavior: (e.g. the "green to yellow" gradient is using a hard coded setting to have the degree angle of 25 (something like down-right to left-top). The others as you can see are just top to down gradient)
![e2a48749-81cf-48cf-8b5d-3ef570a70f55](https://user-images.githubusercontent.com/1680157/35295607-ab327fe4-0060-11e8-8e4a-a557cc0848a9.jpeg)

**Comment by boygirl** [comment]
@obetomuniz to do this, you will want to create a wrapper for your `<Slice/>` component. You will then inspect the props coming in. The `slice` prop has information about the relevant angles. Here's a guide on wrapping components and creating custom components: https://formidable.com/open-source/victory/guides/custom-components/#wrapping-components

**Comment by obetomuniz** [comment]
Wow! Thanks again @boygirl! I'll use this references and tips.

**Comment by obetomuniz** [comment]
@boygirl I was able to capture the startAngle of each slice using a wrapper in the Slice primitive, but It is not possible to use this approach to set the gradient direction using the animate property. It's flicking the animation depending of the startAngle position once I only capture the final startAngle when the animation end. Do you have any suggestion to capture the final startAngle/endAngle of each slice before start the animation?
