### ISSUE TITLE
VictoryLine with gradient fill around it.

### ISSUE THREAD

**Issue by alishir** [FormidableLabs/victory#909]
Would you please help me to plot something like attached image:
![image](https://user-images.githubusercontent.com/978306/35336249-f983eed6-012c-11e8-8f89-c0e4f130fadd.png)

**Comment by boygirl** [comment]
I believe this was addressed in the gitter channel. The solution is quite similar to creating a gradient fill: https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory

An `feOffset` should be used instead: https://www.w3schools.com/graphics/svg_feoffset.asp
