### ISSUE TITLE
Add a clickhandler with evt coords

### ISSUE THREAD

**Issue by ringzhz** [FormidableLabs/victory#91]
I'd like to add a click-listener to a VictoryChart so that I can register an onClick handler method.
I would like for the event to contain a coordinates attribute which contains the click's {x,y}.

I'd be glad to contribute this myself if you prefer. Any pointers on where to start?

**Comment by boygirl** [comment]
@ringzhz coming up with a flexible pattern for adding event handlers is already on our [roadmap](https://github.com/FormidableLabs/victory/blob/master/ROADMAP.md). We have a bit more work to do before I will be able to point to anything shovel ready on this task.

**Comment by zsherman** [comment]
@boygirl was this closed because it was implemented? If so I'm having trouble figuring out where to find it.
