### ISSUE TITLE
More control over multi-point tooltip labels

### ISSUE THREAD

**Issue by Ashwin117** [FormidableLabs/victory#913]
I have a graph with multiple Y axis. When I construct my Tooltip, I see an example with all the Y points appearing on my tooltip. But how do I also get the x data point to show up there as well?

**Comment by boygirl** [comment]
@Ashwin117 The labels in your tooltip are determined by whatever `labels` function you are using, so you should have complete control over this. 

An example in our gallery shows only y points because the `labels` function is:
```
labels={(d) => `y: ${d.y}`}
```
if you change your labels function to something like 
```
 labels={(d) => `x: ${d.x},  y: ${d.y}`}
```
you will see your x values too.

**Comment by Ashwin117** [comment]
Sorry, I should've been more explicit. I am aware of the `labels` function. With this approach, you've suggested, you can indeed come up with a ``x: ${d.x},  y: ${d.y}`}` solution. Great. But what I want is something like this

```
x: "foo"
y1: "bar"
y2: "xyz"
```

I can't get the x label to appear once. I want the x data point to show up in the list once instead of repeating multiple times with the corresponding y value. The reason? Well, product requirement and saving space.

**Comment by Ashwin117** [comment]
Please reopen this issue

**Comment by boygirl** [comment]
@Ashwin117 in this case you can write a custom label component for `VictoryTooltip` that will inspect and alter the incoming array of text. I will additionally open and rename the title of this issue.

**Comment by Ashwin117** [comment]
@boygirl Thanks for re-opening the issue. Do you have an example of the custom label component you're speaking of to make this happen? Thanks.

**Comment by Ashwin117** [comment]
Is there an update for this? Thanks.

**Comment by boygirl** [comment]
@Ashwin117 as of the latest release the `labels` prop on `VictoryVornoiContainer` is called with the following arguments when it is a function: `point`, `index`, `points`. This should give you the control you are looking for.

**Comment by BenoitBotton** [comment]
@Ashwin117 what was your solution in the end? I am at my wits end trying to achieve the same thing:
here is my label
![image](https://user-images.githubusercontent.com/10010115/197782883-f2b87486-85b7-45c7-85ad-3977244ffe9f.png)
I want to change it to have Radius ....  at the top, like a title but can't find how so far.

thanks
