### ISSUE TITLE
BrushContainer wrong behavior when mixing drag n drop and domain changes

### ISSUE THREAD

**Issue by mariogarcia** [FormidableLabs/victory#917]
### The Problem

Dragging and moving manually the brush container around makes it to lose the start/end references. I have two graphs, one general view with a brush container, and a detailed view above. Every time the brush container changes the upper graph changes to. That's is changed via the component state.

Both graphs are also affected by the events of various buttons that are intended to move the brush forward and backward the available data.

Everything works as intended until the moment we use the drag n drop behavior of the brush container. Then the brush stop responding properly to the buttons actions.

### Reproduction

![wrong_behavior](https://user-images.githubusercontent.com/1414131/35804120-b0d804e4-0a76-11e8-954b-c810e34e79fe.gif)

Sandbox with working example [here](https://codesandbox.io/s/5k3rz4m0nx) 

- Use the `forwards` button to  make the brush container to move along the timeline until the end and then use the `backwards` button to make it go until the beginning.
- Now move forwards until a certain point and then press reset. It will go back to the beginning, perfect.
- Now things start behaving weird. Drag the brush container to somewhere in the timeline and then use the `backwards` button to make it go to the beginning.
- At some point, it will stop responding properly. Even using the reset button doesn't work. It's like the last dropped point remained in the memory of the brush container.

**Comment by boygirl** [comment]
@mariogarcia this is because interacting with the brush will set `brushDomain` on internal state which will always override props. If you want to trigger external changes to `brushDomain` you can do so using the new `externalEventMutations` prop. You can read about it here: https://formidable.com/open-source/victory/docs/common-props/#externaleventmutations

**Comment by mariogarcia** [comment]
Oh thanks for the pointer @boygirl
