### ISSUE TITLE
d3 v4

### ISSUE THREAD

**Issue by killercup** [FormidableLabs/victory#92]
Right now you [say](https://github.com/FormidableLabs/victory/blob/0f024b54d9e8a1cff04ad497ee1b0bca5ef35e9b/d3-dependencies.md) that you depend on the whole d3 package, but are tracking what is _actually_ used (or at least you try). Just yesterday I noticed that d3 will be split into several small packages for the next version (4.0): https://github.com/d3

Are there any plans to switch to these new packages?

**Comment by boygirl** [comment]
@killercup we've actually already tried a couple times, and had to abandon the project due to various issues with the rollup build / polyfills. We decided to wait for the packages to mature a bit, but depending on a smaller subset of d3 is definitely on our to-do list.

**Comment by mbostock** [comment]
The polyfills have all been removed, FYI.

**Comment by boygirl** [comment]
thanks @mbostock! I'll try to drop those in this week

**Comment by boygirl** [comment]
This change has been made for the alpha release :)
