### ISSUE TITLE
VictoryChart does not continue updating scale as prop changes beyond first change

### ISSUE THREAD

**Issue by humphreybc** [FormidableLabs/victory#922]
### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When passing the `scale` prop to `<VictoryChart />`, the chart's scale will update once, but stop updating after the first change. What I'd expect to happen is that the scale keeps changing as the prop changes.

### Reproduction

Here's the reproduction in a sandbox: https://codesandbox.io/s/k557xmm00r

```jsx
import React from 'react';
import { render } from 'react-dom';
import { VictoryAxis, VictoryChart, VictoryLine } from "victory";


class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { scale: "linear" }
  }

  componentDidMount() {
    this.timerId = window.setInterval(() => { 
      this.setState({ scale: this.state.scale === "linear" ? "sqrt" : "linear" })
    }, 1000);
  }

  render() {
    return (
      <div>
        <VictoryChart scale={this.state.scale}>
          <VictoryLine />
        </VictoryChart>
        <div>{this.state.scale}</div>
      </div>
    )
  }
};
 
render(<App />, document.getElementById('root'));
```

**Comment by boygirl** [comment]
@humphreybc this was occurring because Victory's shouldComponentUpdate logic was using a comparison that returned `true` when both values were functions without comparing them. As of `victory@0.27.0` the comparison returns false when functions are not identical.
