### ISSUE TITLE
VictoryVoronoiContainer does not correctly calculate active elements for grouped charts

### ISSUE THREAD

**Issue by JayFields** [FormidableLabs/victory#926]
I've noticed that `VictoryVoronoiContainer` does not correctly calculate active elements when `VictoryScatter` is grouped with `VictoryLine`. I found that this bug in my own code but see that it is also exhibited in the [Voronoi Tooltips with Grouped Components gallery demo](https://formidable.com/open-source/victory/gallery/voronoi-tooltips-grouped/).

### Demo
Notice that when I move my mouse around -2 on the y-axis the dots become active. Then, when I mouse over the dots themselves, the tooltip appears but the dots do not change to the active style.

![voronoi_bug](https://user-images.githubusercontent.com/36304992/36039138-a5111256-0d8f-11e8-81fb-83b6dac1d9d6.gif)

**Comment by vientang** [comment]
To add to this issue, the tooltip doesn't activate when hovering over the 4th red dot. It appears that `VictoryVoronoiContainer` activates the other dots just fine.

**Comment by vientang** [comment]
So I was able to resolve my issue by removing pointerEvents from `VictoryLine`. 

`<VictoryLine style={{data: {pointerEvents: 'none'} }} />`

@JayFields Since the size of the dot is determined by its active state, you'll need to add mouse events to `VictoryScatter` to make `active` true. Not really sure why the first dot is active though.
```
<VictoryGroup
   labels={(d) => `y: ${d.y}`}
   labelComponent={<VictoryTooltip style={{ fontSize: 10 }} />}
   data={[
              { x: 1, y: 3 },
              { x: 2, y: 1 },
              { x: 3, y: 2 },
              { x: 4, y: -2 },
              { x: 5, y: -1 },
              { x: 6, y: 2 },
              { x: 7, y: 3 }
   ]}
 >
            <VictoryLine style={{data: {pointerEvents: 'none'} }} />
            <VictoryScatter
              size={(d, a) => {return a ? 8 : 3;}}
              events={[{
                 target: 'data',
                 eventHandlers: {
                    onMouseEnter: () => ({
                       target: 'data',
                       mutation: (dataProps) => ({
                          ...dataProps,
                          active: true
                     }),
               }),
               onMouseLeave: () => ({
                  target: 'data',
                  mutation: (dataProps) => ({
                      ...dataProps,
                      active: false
                  }),
                }),
               onMouseMove: () => ({
                   target: 'data',
                   mutation: (dataProps) => ({
                      ...dataProps,
                      active: true
                   }),
                 }),
            },
    },
]} />
          </VictoryGroup>
```
