### ISSUE TITLE
automatically adjust the y axisLabel padding based on the length of the tick labels of the y-axis

### ISSUE THREAD

**Issue by scottdickerson** [FormidableLabs/victory#929]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.
If I have large values for the ticks of the y axis I am forced to manually adjust the padding of the y axisLabel to keep the y-axis label from overlapping the tick values.

### Reproduction
See this sandbox:
https://codesandbox.io/s/3lx2v5w51

![image](https://user-images.githubusercontent.com/6663002/36170044-cac6b154-10c3-11e8-8bc1-877219713827.png)

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests
I would like for the padding to be automatically adjusted so that the label is always readable, no matter how large the y-axis tick labels are.
### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@scottdickerson I will add the feature request label, but it will still be necessary to manually adjust the overall chart padding to accommodate long labels.

**Comment by boygirl** [comment]
I think I have to close this one as a won't fix.
