### ISSUE TITLE
Cannot set the stroke style for the baseline stroke of a VictoryArea graph

### ISSUE THREAD

**Issue by scottdickerson** [FormidableLabs/victory#931]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I would like to set a baseline stroke color for the VictoryArea graph, but cannot seem to accomplish this style:
![image](https://user-images.githubusercontent.com/6663002/36231035-3450ee12-11a2-11e8-9f74-94ab20f85bd9.png)

I have set stroke colors but only the top line receives them.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description
Can I set some property on the Area graph to get the baseline stroke to pickup the stroke style?

**Comment by walternicholas** [comment]
Simple hack solution: draw the bottom line separately with VictoryLine.

**Comment by boygirl** [comment]
+1 for the solution suggested by @walternicholas 

`VictoryArea` currently only draws a top line, and for most charts this is the desired behavior.
