### ISSUE TITLE
How do I put the x label in between two ticks?

### ISSUE THREAD

**Issue by Ashwin117** [FormidableLabs/victory#933]
I'm aiming to do something like this (This pic is not from a Victory JS graph)

<img width="133" alt="screen shot 2018-02-16 at 1 44 16 am" src="https://user-images.githubusercontent.com/16282701/36301813-fec278c8-12ba-11e8-8609-9fa8d322229a.png">

How do I do this? I looked at docs around textAnchor, style, alignment, etc, but it all seems a bit too confusing.

**Comment by boygirl** [comment]
@Ashwin117 you can use the `dx` prop on `VictoryLabel` to offset the label from its normal position. Here's an example: https://codesandbox.io/s/kw4zv6norr
