### ISSUE TITLE
Poor performance with VictoryBar & VictoryTooltip

### ISSUE THREAD

**Issue by Eseb** [FormidableLabs/victory#935]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Using a `VictoryBar` with many (> 150) bars and `VictoryTooltip` for on-hover labels, performance is quite bad as you hover over different bars.

### Reproduction

Here is an example with ~200 datapoints: https://codepen.io/Eseb/pen/aqjRNy

# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I'm trying to use `VictoryBar` to draw a histogram. When we have a lot of underlying data, we might generate up to 250 bars which doesn't seem unreasonable.

I want to have `VictoryTooltip`s for each of my bars so you can see their values on hover.

As you move from one bar to another to see their values, performance is really bad when there are a lot of them. My investigation suggests that the `shouldComponentUpdate` overhead is one of the big causes of this.

Is there something I'm doing wrong here? Have you guys got a way around this problem?
Would moving Victory's components to `PureComponent` help?

**Comment by ryan-roemer** [comment]
Did a quick performance profile of the CodePen and main think I noticed is a lot of time is spent in: https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/collection.js#L112-L148 -- `checkEquality()`

![screen shot 2018-02-23 at 9 28 01 am](https://user-images.githubusercontent.com/445557/36607590-dde6a068-187b-11e8-9da8-db90fab3ccb2.png)

I think we could profile this function a bit more and see if there are some perf improvements that still pass all unit tests for correctness.

**Comment by chrisbolin** [comment]
addressed in https://github.com/FormidableLabs/victory-core/pull/351.
released in `victory-core@21.1.5`.
