### ISSUE TITLE
Path Transitions for VictoryLine

### ISSUE THREAD

**Issue by carloscpda** [FormidableLabs/victory#936]
# Question

### The Problem

Is it possible to implement or reproduce this: https://bost.ocks.org/mike/path/
There is a related issue [here](https://github.com/FormidableLabs/victory-native/issues/90) but I cannot understand the solution.

**Comment by rsredsq** [comment]
Any suggestions?

**Comment by Yaweii** [comment]
Anyone has any thoughts? I am getting stuck on this as well

**Comment by Yaweii** [comment]
@carloscpda @rsredsq Hi sorry for bothering you. I am trying to build the path transitions line chart and I've been getting stuck on this for days. Would you mind sharing some thoughts or ideas? Much appreciated!

**Comment by beccanelson** [comment]
As far as I know, Victory should already be able to handle path transitions as long as you handle updating the data in state and passing it into Victory. Here is an example of how this might be done with `VictoryLine`.

https://codesandbox.io/s/victory-line-transition-example-1xcxg

Is there some other specific behavior you are looking for?
