### ISSUE TITLE
TickCount is not valid with a axis scale of time

### ISSUE THREAD

**Issue by anthony-ngu** [FormidableLabs/victory#937]
# Bugs and Questions

### Checklist

* [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am attempting to set a tickCount in order to make sure that we always have at least 12 ticks (one per month) in an axis that is scaled for time but I am receiving this error:

TypeError: t.range is not a function
Function.scale.ticks
node_modules/victory-core/node_modules/d3-scale/src/time.js:111
  108 |       t;
  109 |   if (r) t = t0, t0 = t1, t1 = t;
  110 |   t = tickInterval(interval, t0, t1, step);
> 111 |   t = t ? t.range(t0, t1 + 1) : []; // inclusive stop
  112 |   return r ? t.reverse() : t;
  113 | };
  114 | 

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

* [X] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I would like this feature to be enabled for time scales if possible. Thanks!

**Comment by code4arpit** [comment]
@anthony-ngu - You can find the solution of this problem at https://github.com/FormidableLabs/victory/issues/993
