### ISSUE TITLE
Styles for VictoryAxis labels aren't updating correctly

### ISSUE THREAD

**Issue by vmazare** [FormidableLabs/victory#940]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The styles for VictoryAxis labels aren't updating correctly. I'm trying to apply a certain style to a label based on the wrapper component's state which works for the initial render and the first update, but it doesn't work for the next updates - when the wrapper component's state changes I'm passing the correct `style` prop to VictoryAxis but the label doesn't get updated.

Note: I was able to work around this by passing a random prop to VictoryAxis to make sure it's re-rendered every time I need it to, which solves the problem.

### Reproduction

Bug - https://codesandbox.io/s/qxzjo40zr6
Workaround (hopefully it helps to investigate this) -  https://codesandbox.io/s/j39ym1vy1y

**Comment by boygirl** [comment]
@vmazare 

This is actually a nasty one that has to do with how our `shouldComponentUpdate` logic handles equality checking. It's untenable to evaluate every function within this logic, so we return `true` so long as values are both functions. It would be safer to return `false`, but this would potentially result in unnecessary rerenders and a performance decline.

The intent of functional styles is to change in result to changing _data_, so this edge normally doesn't get hit. It but that kind of breaks down for `VictoryAxis`. I need to think more about how best to resolve this.

**Comment by eballeste** [comment]
workaround helped!

**Comment by boygirl** [comment]
This issue is fixed in `victory@0.27.0`
