### ISSUE TITLE
Change the position of flyout pointer

### ISSUE THREAD

**Issue by gokulramesh71** [FormidableLabs/victory#941]
As of now, the pointer in flyout is set to come in the center of the the flyout. Is there a way to change that?

**Comment by boygirl** [comment]
Currently no. There is an issue that has been open for a long time to add pointer offset and pointer angle props for `Flyout` and `VictoryTooltip`. It will be some finicky svg path calculating. It hasn't been in high demand, but I will link this issue to it, and prioritize.
