### ISSUE TITLE
Unexpected tooltip appears when rendering a previously rendered dataset.

### ISSUE THREAD

**Issue by lgerndt** [FormidableLabs/victory#945]
Problem summary: VictoryPie - unexpected tooltip appears when rendering a previously rendered dataset.

Background:  We implement "drill down" functionality in our pie chart, meaning when user clicks a slice, we then render the data contained within that slice as a new pie chart (re-render the current chart with new data).  Above the chart we render a breadcrumb which contains the datasets the user has clicked into, so user can click a breadcrumb 'link' to re-view that data.

The problem:  User moves mouse over a slice, tooltip appears (and this is the one that re-appears later, unexpectedly), user proceeds to click the slice, the tooltip disappears as expected, the chart gets re-rendered with new dataset, a new breadcrumb link appears above the chart, the user clicks one of the breadcrumbs above, the chart gets re-rendered with that dataset, and then (WHY?) the tooltip that originally appeared re-appears.  Now I know Victory displays the tooltip until user mouses out, but in this scenario, Victory will never get a "mouseOut" event because user didn't mouse out, they clicked.  It's as if VictoryPie is keeping track of datasets it has rendered and is saving the active tooltip with that dataset.

I hope this makes sense.  I need it to stop :). I searched through all the issues here and could not find a solution.

**Comment by lgerndt** [comment]
Update: I got this resolved inadvertently by turning on animation.  I had it turned off.  When I click a slice, the chart is re-rendered with new data animatedly, causing the tooltips to disappear.  So it's still an issue for the case of animation: off.  But I wouldn't expect people to disable animation, so feel free to close this.

**Comment by lgerndt** [comment]
Be sure to turn off animation before testing this, it helps to reproduce the bug.

**Comment by boygirl** [comment]
@lgerndt I'm sorry for the long delay. I believe this is actually expected behavior. Mutations caused by Victory's event system are kept when props change so that you can do things like see a highlighted point move during an animation. You can use the `externalEventMutation` prop to clear mutations at the same time you trigger a new dataset, or you can manually set very different eventKeys for your new dataset, that will keep mutations from being reapplied.
