### ISSUE TITLE
Tooltips rendering issues when using VictorySharedEvents, VictoryPie and VictoryLegend

### ISSUE THREAD

**Issue by iprignano** [FormidableLabs/victory#947]
### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm trying to use `VictoryPie` and `VictoryLegend` together to make an interactive Pie chart, which should display a custom tooltip when either a section of the pie chart or one of the legend entries are hovered. Basically this but with tooltips showing on each hover event:

[See .gif here (~2.5MB)](https://user-images.githubusercontent.com/3172763/37652910-5ee21880-2c3d-11e8-92d8-d1c73892c4b6.gif)

I wrapped the two components with `VictorySharedEvents` and passed the needed mouse event handlers to it. It seems to work (almost) correctly, but there's one annoying bug: when hovering on the labels on the left, the tooltips show on the pie chart – but after moving the mouse over the corresponding pie section (showing the tooltip again), hovering the labels won't trigger the tooltip again. 

It's probably easier to show it than trying to explain it:

[See .gif here (~3.5MB)](https://user-images.githubusercontent.com/3172763/37653340-dcf0e5c0-2c3e-11e8-860d-c8de5b9f9357.gif)

I've tried to dig up a bit in the library code but I couldn't find anything that could explain this. Any help would be much appreciated.

### Reproduction

Here's the sandbox where you can reproduce the problem:
https://codesandbox.io/s/vy8206o0n3

**Comment by boygirl** [comment]
@iprignano thank you for the reproduction. I'm sorry for such a long delay. I was able to reproduce your issue with the latest version of Victory. I will work on fixing it in the coming week.

**Comment by iprignano** [comment]
No problem at all. Thank you very much for your work!
