### ISSUE TITLE
Cannot access data point on victory line onMouseOver

### ISSUE THREAD

**Issue by stuthib** [FormidableLabs/victory#949]
I have a line chart, and I am trying to get a custom tooltip. But I would need the 'x' value so I can display the appropriate 'y' value. I am unable to access this data.
This is my code ,

<VictoryLine
          standalone={false}
          style={{
            data: {
              stroke: trend_color,
              strokeWidth: 1
            },
            //axis: {stroke: "purple"}
            labels: {fill: "#fff"}
          }}
          data={line_data_formatted}
          events={[{
            target: "data",
            eventHandlers: {
              onMouseOver: (evt, props) => {
                //this.showToolTip(evt,evt.clientX, evt.clientY);
                console.log(evt, props);
              },
            }
          }
        ]}
        />

Can anyone please tell how to get the co-ordinate values?

**Comment by boygirl** [comment]
@stuthib VictoryLine is a single element, so it will only have a single event target for the entire line. Because of this, VictoryLine does not automatically associate an event with a _single_ data point. You can check out `VictoryVoronoiContainer` to solve your problem.
