### ISSUE TITLE
Bars are not showing properly

### ISSUE THREAD

**Issue by ShaikhKabeer** [FormidableLabs/victory#950]
Hello all,

I have used "victory-native" library in my app. In one of my screen, there is Horizontal Bar Chart having lots of data. Due to no of data, the bars not showing properly. I have applied BarRatio={0.8} property to VictoryBar to show some distance between two bars but it is not working.  

<VictoryChart 
containerComponent=
        {
        <VictoryZoomContainer 
          allowZoom={false} 
          allowPan={true}       
          zoomDomain={{y: [0, 5]}}/>
        }
  theme={VictoryTheme.material}
  domainPadding={10}
>
<VictoryBar
   barRatio={0.7}
   horizontal
    style={{ data: { fill: "#c43a31" } }}
    data={[
                          { x: 1, y: 2},
                          { x: 2, y: 3},
                          { x: 3, y: 5},
                          { x: 4, y: 4},
                          { x: 5, y: 6},
                          { x: 6, y: 2},
                          { x: 7, y: 3},
                            { x: 8, y: 5},
                          { x: 9, y: 4},
                          { x: 10, y: 6},
                          { x: 11, y: 2},
                          { x: 12, y: 3},
                          { x: 13, y: 5},
                          { x: 14, y: 4},
                          { x: 15, y: 6},
                          { x: 16, y: 6},
                          { x: 17, y: 2},
                          { x: 18, y: 3},
                          { x: 19, y: 5},
                          { x: 20, y: 4},
                          { x: 21, y: 6},
                          { x: 22, y: 2},
                          { x: 23, y: 5},
                          { x: 24, y: 4},
                          { x: 25, y: 6},
                          { x: 26, y: 2},
                          { x: 27, y: 3},
                          { x: 28, y: 5},
                          { x: 29, y: 4},
                          { x: 30, y: 6},
                          { x: 31, y: 2},
                          { x: 32, y: 3},
                          { x: 33, y: 5},
                          { x: 34, y: 4},
                          { x: 35, y: 6},
                          { x: 36, y: 6},
                          { x: 37, y: 2},
                          { x: 38, y: 3},
                          { x: 39, y: 5},
                          { x: 40, y: 4},
                          { x: 41, y: 6},
                          { x: 42, y: 2}, 
                          { x: 43, y: 5},
                          { x: 44, y: 4},
                          { x: 45, y: 6},
                          { x: 46, y: 2},
                          { x: 47, y: 3},
                          { x: 48, y: 5},
                          { x: 49, y: 4},
                          { x: 50, y: 6}
                        ]}
  />
</VictoryChart>

**Comment by boygirl** [comment]
@ShaikhKabeer I'm going to close this issue, but I will re-open if you can provide more information.
