### ISSUE TITLE
Unable to set property 'fill' of undefined or null reference

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [FormidableLabs/victory#952]
# Bugs and Questions

### Checklist

* [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x ] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Some users are experiencing a typeError crash 'Unable to set property 'fill' of undefined or null reference' 
in:

div in g in VictoryBar in svg in div in VictoryContainer in VictoryChart

### Reproduction

I think this is due to a conditional label I have for the Victory bar:

````

      <VictoryChart
        theme={SincTheme}
        padding={{
          top: 0,
          bottom: 20,
          left: 40,
          right: 20,
        }}
        domainPadding={{ x: 5 }}
        height={this.props.overallSummary ? 170 : 100}
        domain={{ y: [0, 1.1 * highestNumber] }}
      >
        <VictoryAxis />
        <VictoryAxis
          dependentAxis
          // tickFormat specifies how ticks should be displayed
          tickFormat={y => `${y} hrs`}
        />
        <VictoryBar
          alignment="start"
          cornerRadius={1}
          style={{
            labels: { fill: 'white', fontSize: 5 },
          }}
          labels={d => (d.hours > 0 ? d.hours : '')}
          name="Bar"
          x={xLabel}
          y={yLabel}
          data={data}
          labelComponent={data.length <= 7 ? <VictoryLabel dy={20} dx={10} /> : <div />}
        />
      </VictoryChart>

````
Is there a better way to display no label component conditionally than what I'm currently doing maybe? Thanks

**Comment by SamMatthewsIsACommonName** [comment]
Sorry I'm quite sure the problem would be setting the style on the victoryBar rather than the VictoryLabel Component.
I'm going to move the style there and hopefully this will fix it. Please feel free to close this and I can see if it happens again after this change.

**Comment by boygirl** [comment]
@SamMatthewsIsACommonName I think there's an issue with your `labelComponent` too. When your conditional returns a div, you will end up with errors related to rendering non-svg elements within an svg.

**Comment by SamMatthewsIsACommonName** [comment]
@boygirl good point! Have changed to an empty svg element. Thanks
