### ISSUE TITLE
How to make a VictoryLine with open ends in Polar VictoryChart?

### ISSUE THREAD

**Issue by manikandanraj** [FormidableLabs/victory#953]
# ~~Bugs and~~ Questions
Is there a way to leave the ends not meet in a `VictoryLine` drawn in a `polar` `VictoryChart`?

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I have a `VictoryLine`, drawn in a `polar` `VictoryChart`, right now ends of the lines meet. Is there a way to leave it open?

![image](https://user-images.githubusercontent.com/26248876/37953247-f699207e-31bf-11e8-8370-b92ee56cabc6.png)

### Reproduction
Sandbox - https://codesandbox.io/s/2ov7xp2qqy

**Comment by boygirl** [comment]
@manikandanraj You want to add the `openCurve` prop to the data component supplied to VictoryLine like so:
`dataComponent={<Curve openCurve/>}`
