### ISSUE TITLE
Infra: Re-enable pull_request only builds in Travis.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/victory#957]
As part of our Chromatic work, we disabled this:

```yml
branches:
  only:
    - master
```

which only builds on `TRAVIS_EVENT_TYPE` of `pull_request` because we need to trigger Chromatic on `push` requests. Unfortunately this means we now build on every push to any branch, whether a PR is open or not in addition to the PR builds.

Task

- [ ] Figure out some travis hackery to limit double building to _only_ open PRs.
- [ ] Track if Chromatic switches to `pull_request` events instead.

References:

- https://github.com/FormidableLabs/victory-pie/pull/173

**Comment by boygirl** [comment]
Fixed in the latest version of chromatic
