### ISSUE TITLE
Invalid prop `data` of type `object` supplied to `VictoryLabel`, expected `array`

### ISSUE THREAD

**Issue by farzadmf** [FormidableLabs/victory#958]
Hi,

I'm VERY confused with what's happening. I'm receiving the following error:

```
Invalid prop `data` of type `object` supplied to `VictoryLabel`, expected `array`
```

What I have is very simple like this:
```ts
public render() {
  return (
    <vic.VictoryChart>
      <vic.VictoryBar
        data={[
          { x: 0, y: 100 },
          { x: 1, y: 150 },
          { x: 2, y: 200 },
          { x: 3, y: 50 },
          { x: 4, y: 500 },
        ]}
        labelComponent={
          <vic.VictoryLabel text={d => d.y} />
        }
      />
    </vic.VictoryChart>
  );
}
```

Can you PLEASE help me, I have no idea what's happening here

**Comment by boygirl** [comment]
@farzadmf rather than `labelComponent={<vic.VictoryLabel text={d => d.y} /> }`, you need to define a `labels` prop on `VictoryBar` like `labels={(d) => d.y}`

**Comment by farzadmf** [comment]
Thank you @boygirl for replying. Actually, the code I wrote here was a *very* simplified version of what I was trying to do. I think I have to use `VictoryLabel` because I need to shift the labels vertically (am I right that it can only be done using a label component and not `labels` property)?

So, what can I do considering what I mentioned?
