### ISSUE TITLE
Animated stacked bar: removing stacks is wrong, seems to be delayed by one render

### ISSUE THREAD

**Issue by dlopuch** [FormidableLabs/victory#960]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Make a stacked bar chart powered by some dynamic data source.

When you change the number of stacks in your underlying data source, the number of stacks changes as expected.  Good.

Now turn on animation (`animate={{ duration: 500 }}`).

Now when the number of stacks change in the underlying data source, the chart does NOT update the number of stacks.  It seems to be delayed by one render (see example).

This only seems to be when you **remove** stacks.  Adding stacks seems to be fine.

### Reproduction

https://codesandbox.io/s/7376kj86p0

Here we start with some stacked data.  Pressing the "-1", "Randomize Stacks", or "+1" buttons just filters the initial data source to show/hide some stacks.

When it's in animate mode, you can see the bug.  When you turn off animate mode, the stacks change correctly (though sometimes it does get stuck in buggy mode... if it does, toggle it a few more times).

**Comment by boygirl** [comment]
@dlopuch Thank your for reporting this and including such a helpful reproduction. I apologize for the long delay. I will look into a fix in the coming week.

**Comment by stam** [comment]
I still have this issue. Is this something you think new contributors could fix?

**Comment by becca-bailey** [comment]
Closing in favor of this larger issue https://github.com/FormidableLabs/victory/issues/2104
