### ISSUE TITLE
VictoryLine conflict with Collections.JS

### ISSUE THREAD

**Issue by ecann** [FormidableLabs/victory#961]
### The Problem

Using Collections.JS breaks VictoryLine. Collections.JS shims Array with the function `all`. This causes the following line to fail in add-events.js: `const key = this.dataKeys && this.dataKeys[index] || index;`. The key ends up containing a function instead of a string which ultimately causes the function to return `undefined`.

https://github.com/FormidableLabs/victory-core/blob/41d665a5c41b9900efe66f654a14dcce187f38d0/src/victory-util/add-events.js#L154

The array is accessed with the string `"all"`, which conflicts with the shimmed method when using Collections.JS. 

### Reproduction

https://codesandbox.io/s/p9nqj7pyrm

**Comment by ryan-roemer** [comment]
Thanks for the issue -- can we get a little more information.

- The codesandbox fails for a `collections` dependency when I open it. Can you check it?
- Is `Array.prototype.all` _supposed_ to be a supported thing in ECMAscript or is `Collections.JS` just monkey-patching things in non-standard ways?
- Can you explain the arguments passed to `getComponentProps(component, type, index) {}` and the value of `this.dataKeys` that would have to exist to hit this issue?

Thanks!

**Comment by ecann** [comment]
Collections patches the method `all` on to the Array object. For VictoryLine, `getComponentProps` is called with the following arguments: `const dataProps = this.getComponentProps(dataComponent, "data", "all");`. See https://github.com/FormidableLabs/victory-core/blob/41d665a5c41b9900efe66f654a14dcce187f38d0/src/victory-util/add-events.js#L197

For standard VictoryLine charts, the problematic line in `getComponentProps` then attempts to access the `dataKeys` array with the string `"all"`.  The expected result is that the response from the array will be undefined, and `key` will be set to `"all"`.

It's true that the `all` function is not standard on Array, but the line `const key = this.dataKeys && this.dataKeys[index] || index;` could be rewritten to be more resilient while supporting `"all"` as an argument to that function. Rather than accessing the array with a string and assuming no `all` property is defined.

This would allow VictoryLine and Collections to coexist.

**Comment by boygirl** [comment]
@ryan-roemer @ecann `this.dataKeys` corresponds to the eventKeys that are registered for any given component. Continuous components like `VictoryLine` and `VictoryArea` use the special eventKey "all" rather than data indices since they render a single element for a given data set. But now that you've pointed it out, I think `this.getComponentProps(dataComponent, "data", "all")` is only working because of a default in `events.js`. I should be finding the array element rather than accessing by index. I'll dig into this more.

**Comment by Hypnosphi** [comment]
@boygirl did you get a chance to take a look at that? Can I help maybe?

**Comment by alamothe** [comment]
The issue still persists in 2021.
