### ISSUE TITLE
VictoryAxis tickLabelComponent props documentation possibly inaccurate

### ISSUE THREAD

**Issue by ecbrodie** [FormidableLabs/victory#963]
It appears that the documentation for [VictoryAxis tickLabelComponent](https://formidable.com/open-source/victory/docs/victory-axis/#ticklabelcomponent) may be inaccurate. Specifically, the part that mentions the props that are sent by Victory to the props of the `tickLabelComponent`.

The documentation says that there will be a `tick` prop sent to the `tickLabelComponent`. However, in my application, I have noticed that my custom `tickLabelComponent` is actually being a `text` prop instead of a `tick` prop. I believe that the specific part of Victory's source code that may be causing a bug is [here](https://github.com/FormidableLabs/victory-chart/blob/cc846e7909b815b806e21f19e54eb32f608a5354/src/components/victory-axis/helper-methods.js#L237). Notice that `getTickLabelProps()` is being called with its final parameter being the result of a call to `tickFormat`. The name of this parameter is `text`. Then inside of `getTickLabelProps()`, the `text` parameter is simply inserted into the returned Object as its `text` key via shorthand notation.

As an outsider, I am unsure of whether the implementation of the source-code is the true intention of the `<VictoryAxis>` component's design and thus the documentation is outdated. Or if the documentation is the source of truth and thus the code is buggy. Anyway, I hope this issue helps get things clarified and save developers time in understanding how to work with the Victory API. I'd be glad to contribute a PR to fix, but I just need to hear back first from an expert.

FWIW, my project is depending on the latest versions of Victory, which are at the time of writing:

* `victory-chart v25.2.2`
* `victory-core v21.1.5`

**Comment by boygirl** [comment]
@ecbrodie Thank you for bringing this up. The documentation is incorrect. The `tick` value itself will be sent to `tickLabelComponent` via `VictoryLabel`'s `datum` prop. The value sent as `text` will be the string (or array of strings) returned from evaluating the `tickFormat`  I will move this issue to the victory-docs repo and track it there.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#521
