### ISSUE TITLE
VictoryGroup Tooltip on Hover over does not Align with Cursor

### ISSUE THREAD

**Issue by Dominic-Pace** [FormidableLabs/victory#965]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When passing data prop into VictoryGroup component hovering over the graph does not act as intended. As you can see via screenshots or going into the documentation page below, the tooltip does not align with the cursor.

<img width="1440" alt="victory issue" src="https://user-images.githubusercontent.com/12464763/38518895-d9e08118-3c03-11e8-81fa-9dc7b33100ed.png">
https://formidable.com/open-source/victory/gallery/voronoi-tooltips-grouped/

I've been playing around with this for a couple of days now and the problem seems to lie within the VictoryGroup component itself. It seems to be a more serious issue when there are two or more datasets being graphed.

### Reproduction

1. Navigate to: https://formidable.com/open-source/victory/gallery/voronoi-tooltips-grouped/
2. Hover over the graph to highlight both data points on the x-axis. 

**Expected Results**: When hovering over the x-axis there should be a tooltip for both data points corresponding to the cursor location. 

**Actual Results**: When hovering over the x-axis the tooltip does not correspond to cursor location.

**Comment by boygirl** [comment]
this issue has been resolved in the latest version
