### ISSUE TITLE
Bigger area Victory Group Click

### ISSUE THREAD

**Issue by banken7393** [FormidableLabs/victory#967]
# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

I have a VictoryGroup component with several VictoryBar components. I would be great to have some container over the diferent bars to make the click functionality more friendly, triggering the click event when you click bettween bars for example. 
![onclick](https://user-images.githubusercontent.com/15122696/38612470-136d99c8-3d87-11e8-8ed3-40e0e2493002.jpg)

**Comment by boygirl** [comment]
@banken7393 

You can check out `VictoryVoronoiContainer` for larger hover areas. Otherwise you might try rendering an additional wide, transparent bar over each group and adding your click events there.

**Comment by banken7393** [comment]
@boygirl thanks. I have rendered and additional victory group over the firs one and It works. just to know. there is an easy way to render a victory bar overloading the overflow parameter to solve the problem?
