### ISSUE TITLE
RN 0.54 / React 16.3 deprecation warnings for componentWillReceiveProps, componentWillMount

### ISSUE THREAD

**Issue by peacechen** [FormidableLabs/victory#968]
Preface:  I'm using victory-native, but digging down into the dependencies shows that the relevant code is in victory-core.  However that repo doesn't have Issues enabled, so I'm posting here.

# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: VictoryArea, VictoryAxis, VictoryChart, VictoryGroup, VictoryLine, VictorySharedEvents, VictoryStack, VictoryZoomContainer, VictoryBar

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks

Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: VictoryArea, VictoryAxis, VictoryChart, VictoryGroup, VictoryLine, VictorySharedEvents, VictoryStack, VictoryBar
```

The fixes are actually simple and maintain backward compatibility.
Replace `componentWillMount` with `componentDidUnmount` (or move to the constructor).
Replace `componentWillReceiveProps` with `componentDidUpdate` and tweak logic appropriately.

In the rare case that `getDerivedStateFromProps` is necessary, a polyfill can be used to maintain backwards compatibility.
See https://github.com/reactjs/react-lifecycles-compat

### Reproduction

Upgrade to React 16.3+ (and/or RN 0.54+ if running a native project)

# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by boygirl** [comment]
@peacechen this is related to planned changes in React 16.3 in anticipation of async render compatibility. Victory is planning forward compatibility. I opened a new issue for tracking here: https://github.com/FormidableLabs/victory/issues/969
