### ISSUE TITLE
VictoryAxis with unicode labels overlap in react native [android]

### ISSUE THREAD

**Issue by sushantkrraut** [FormidableLabs/victory#970]
# Bugs and Questions

### Checklist

 `victory-native` specific issue on andriod.
victory-native": "^0.17.4"

### The Problem

I am using victory axis with a simple bar chart with unicode labels in an android application using victory-native. The unicode characters overlap in react native in android application. It seems that the width of each character is not properly calculated. It works great on browser (and in sandbox). The character which gets trimmed has a larger width than other characters.

The unicode chars (labels) : अप्रैल, मार्च, फ़रवरी, जनवरी, दिसम्बर, नवम्बर

Usage: 

<VictoryAxis
                                        style={{ axis: { stroke: "#737373" } }}
                                        theme={VictoryTheme.material}
                                        tickFormat={this.state.labels}
                                    />

seen as

![image](https://user-images.githubusercontent.com/29725582/38675985-37377cc0-3e77-11e8-9671-d14cb46f2bfc.png)

### Reproduction

works in a sandbox.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-native#296
