### ISSUE TITLE
Feature Request: Handle labelRadius for multiple <VictoryLabel> elements.

### ISSUE THREAD

**Issue by blb451** [FormidableLabs/victory#971]
It would be nice to handle the case for <VictoryPie> where you have multiple labels with different radius. For example, I was using a <VictoryPie> with a custom `labelComponent` creating something along these lines:

<img width="456" alt="screen shot 2018-04-12 at 1 00 51 pm" src="https://user-images.githubusercontent.com/20449732/38703800-1985a256-3e59-11e8-8f74-30bd6fecac31.png">

```
const CustomLabel = props => (
  <g>
    <VictoryLabel
      {...props}
      style={[
        { textAlign: 'center' },
        { textAlign: 'center', fontWeight: 'bold' }
      ]}
    />
    <VictoryLabel {...props} text={d => `${d.z}%`} />
  </g>
);`
```

And it would have been nice to be able to either specify an array for `labelRadius`, or pass that as props down to <VictoryLabel> as opposed to making calculations based on angles to pass to offsets.

```
 dx={
    Math.sin(
     (props.slice.endAngle - props.slice.startAngle) / 2 +
        props.slice.startAngle
    ) * 50
  }
  dy={
    -(
      Math.cos(
        (props.slice.endAngle - props.slice.startAngle) / 2 +
          props.slice.startAngle
      ) * 50
    )
  }
```

**Comment by boygirl** [comment]
I believe this issue is solved in latest victory
