### ISSUE TITLE
Animation doesn't work with custom data component

### ISSUE THREAD

**Issue by farzadmf** [FormidableLabs/victory#973]
Hi,

I'm trying to draw a line chart "in front of" my axes, and changing the order in `VictoryChart` didn't seem to change the ordering, and the axes were always drawn on top of the line:

```ts
const xAxis = <VictoryAxis ... />;
const yAxis = <VictoryAxis ... />;
const line = (
  <VictoryLine
    animate={{
      delay: 500,
      onLoad: {
	duration: 500,
      }
    }}
    ...
  />;
);

const chart = (
  <VictoryChart>
    {xAxis}
    {yAxis}
    {this.props.drawLine && line}
  </VictoryChart>
);
```

I'm not sure if it affects anything, but, as you may have noticed, I'm drawing the line based on a `boolean` value, which is set after some activity.

Since the order didn't work, I decided to use `VictoryPortal` for my line to bring it to the front:

```ts
const line = (
  <VictoryLine
    animate={{
      delay: 500,
      onLoad: {
	duration: 500,
      }
    }}
    dataComponent={<VictoryPortal><Curve /></VictoryPortal>}
  />;
);
```

Now, my animation doesn't seem to have any effect. Is there a way to animate my chart that's using a custom data component?

**Comment by becca-bailey** [comment]
Closing in favor of #2104
