### ISSUE TITLE
Tick Value for Origin Pos on Y Axis

### ISSUE THREAD

**Issue by Ericky14** [FormidableLabs/victory#975]
How do I add a tick value for 0 automatically?

This is not rendering a tick value for position 0 on the Y axis.
```
<VictoryAxis
  dependentAxis
  tickFormat={(x) => x}/>
```

**Comment by boygirl** [comment]
If you're using `VictoryAxis` within `VictoryChart` it will set the `crossAxis` prop to true. You can change this behavior by setting is directly on `VictoryAxis`. You can read about the prop here: https://formidable.com/open-source/victory/docs/victory-axis/#crossaxis
