### ISSUE TITLE
areVictoryPropsEqual freezes browser for minutes at a time

### ISSUE THREAD

**Issue by michaelbridge** [FormidableLabs/victory#977]
I have not been able to recreate this issue in codepen or a minimal repo, however I have encountered it intermittently across numerous charts.

Why does victory attempt a deep comparison of incoming props in areVictoryPropsEqual?  Isn't this counter to the fundamental way in which React is designed? As the developer, I already manage the render tree so Victory only re-renders when necessary.  

**Can an option be added to disable areVictoryPropsEqual?**

**Comment by boygirl** [comment]
@michaelbridge We're recently updated this method to be much more performant. What version of Victory are you using that is causing the browser to freeze?

**Comment by michaelbridge** [comment]
I tested with 25.7 and the issue was still present, though I haven't tested with 26.0.

Strangely, this sometimes happens with modest data sets on the order of ~5-10 rows.

**Comment by boygirl** [comment]
@michaelbridge can you add a small code example? I'm also not sure what you mean by rows. Can you tell me roughly how many data points you're rendering when you encounter this issue?

**Comment by michaelbridge** [comment]
This is happening with <10 data points (i.e., very small data sets).  I haven't been able to reliably reproduce with a minimal code example, unfortunately.

**Comment by michaelbridge** [comment]
Nothing whatsoever.  The only clue I can provide is I have been able to 'fix' the issue by implementing a very tight componentShouldUpdate on the parent container to VictoryChart.

**Comment by boygirl** [comment]
I'm closing this issue since there have been changes in sCU logic. I will re-open if your issue persists in the `victory^0.27.0`
