### ISSUE TITLE
standardize undefined checking

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#978]
Currently we have a mix of `foo === undefined` and `typeof foo === "undefined"`

We need to pick one or the other, or use` _.isUndefined`

fyi, lodash uses `foo === undefined`. https://github.com/lodash/lodash/blob/master/isUndefined.js

@ryan-roemer please arbitrate.

**Comment by ryan-roemer** [comment]
I'm cool with what lodash does :)

**Comment by boygirl** [comment]
Standardized on `foo === undefined`
