### ISSUE TITLE
Add warning when postinstall fails (NPMv2 issue)

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#98]
Consider removing `postinstall` step in order to open up `npm` 2 compatibility again.

https://github.com/FormidableLabs/victory/pull/95 removed Node versions other than `5` from the Travis run, in order to ensure `npm` v3 is used in the install step. This is because of https://github.com/FormidableLabs/builder/issues/35.

This has consequences – ​_not_​ doing postinstall means you must:

1. give up `git` dependencies / installations; **OR**
2. have to commit `lib` to source

There is a lot more detail in https://github.com/FormidableLabs/formidable-react-component-boilerplate/issues/56.

**Comment by coopy** [comment]
@ryan-roemer has a strawman solution for this:

1. Underlying archetype (`builder-victory-component`) swaps out the existing [`npm:postinstall`](https://github.com/FormidableLabs/builder-victory-component/blob/master/package.json#L16) shell invocation with `cd lib || builder run build-lib` (to simplify)
2. Each implementing `ROOT` project (and the boilerplate) updates `package.json` updates the [`postinstall` script](https://github.com/FormidableLabs/victory-line/blob/master/package.json#L17) to say `cd lib || builder run npm:postinstall`.

This will take care of the problem with `builder` not being available for any project that's being `npm install`ed using a bad `npmv2`. This will _not_ take care of the problem when `git install`ing or `git clone`ing, since `lib/` isn't part of the repo.

**Comment by coopy** [comment]
Potential compromise: Can we prompt user to upgrade to `npmv3` if the `postinstall` fails in this way?

**Comment by ryan-roemer** [comment]
> Potential compromise: Can we prompt user to upgrade to npmv3 if the postinstall fails in this way?

That's a lot of tooling that should be (1) Windows / Mac compatible and (2) can't rely on any npm installs to have succeeded because of the very nature of the problem.

I think with the `cd lib || builder run npm:postinstall` protection solving _all_ of "from npm" installs, the folks who are doing a `git` install can probably do just fine with a README.md warning or such (?)

**Comment by ryan-roemer** [comment]
@coopy -- I take that back. Amazingly this works on Mac and Windows (tried XP):

```sh
cd lib || builder run npm:postinstall || echo 'POSTINSTALL FAILED: If using npm v2, please upgrade to npm v3. See bug https://github.com/FormidableLabs/builder/issues/35' && exit 1
```

But, you'll need to update all the Victory projects to have this exact string (it can't be abstracted to builder, because in our failure scenario builder / archetype didn't install :wink: )

**Comment by coopy** [comment]
Awesome, thanks for testing that @ryan-roemer!

**Comment by knowbody** [comment]
can we go forward and add this warning to all the victory components?

**Comment by coopy** [comment]
Yes.
mån 4 jan. 2016 kl. 07:24 skrev Mateusz Zatorski <notifications@github.com>:

**Comment by knowbody** [comment]
warnings are added now, so closing this.
