### ISSUE TITLE
VictoryTooltip Custom Flyout Z-Index

### ISSUE THREAD

**Issue by Ericky14** [FormidableLabs/victory#981]
How to change the z position of a custom flyout component?

This is what it looks like
<img width="371" alt="screen shot 2018-04-18 at 11 03 08 pm" src="https://user-images.githubusercontent.com/21248862/38969227-2fbb6980-435d-11e8-8e3d-8ae56a3abe1f.png">

And this is what it looks like if I set the z-index of the `TextWrapper` to a different value. (Keep in mind Im hovering the same bar)
<img width="496" alt="screen shot 2018-04-18 at 11 07 23 pm" src="https://user-images.githubusercontent.com/21248862/38969259-54af6728-435d-11e8-87ec-ac8170e4d34f.png">

Custom flyout component html:
```
             <g style={{ pointerEvents: 'none' }}>
                <foreignObject
                    x={x + 9}
                    y={y - 182}
                    width='250'
                    height='200'>
                    <Wrapper>
                        <TextWrapper>
                            Everything in here functions as a normal html element and can be styled with CSS
                        </TextWrapper>
                    </Wrapper>
                </foreignObject>
            </g>
```

**Comment by sibelius** [comment]
can you use `renderInPortal` ? http://formidable.com/open-source/victory/docs/victory-tooltip/#renderinportal

**Comment by boygirl** [comment]
Closing this issue, but I will re-open if the suggested `renderInPortal` fix is not sufficient

**Comment by pavan1992** [comment]
same issue ..  @Ericky14  did u find any solution

**Comment by patelgaurav4u** [comment]
same issue with "victory-native": "^35.3.1"
