### ISSUE TITLE
Setting VictoryBar horizontal={true} renders stacked bars

### ISSUE THREAD

**Issue by rweller59** [FormidableLabs/victory#985]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I've got a sample barchart with multiple datasets that I need to render horizontally. With horizontal=false, chart renders as expected (datasets grouped next to each other). When I set horizontal=true, bars are rendered horizontally but they are now stacked. Also, with horizontal=false, bar spacing no longer applies - removing renders vertical barchart as expected.

### Reproduction
      <VictoryChart theme={VictoryTheme.material} domainPadding={{ x: 50 }} width={400} height={400}>
        <VictoryAxis tickValues={[1,2,3,4,5,6,7,8,9,10]}
        />
        <VictoryGroup colorScale={"qualitative"} offset={5} style={{ data: { width: 5 } }}>
          <VictoryBar horizontal={true} data={data1}/>
          <VictoryBar horizontal={true} data={data2}/>
          <VictoryBar horizontal={true} data={data1}/>
          <VictoryBar horizontal={true} data={data2}/>
        </VictoryGroup>
      </VictoryChart>

# Feature Requests

### Checklist

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment]
@rweller59 Try setting `horizontal` on `VictoryGroup` instead or on each bar
