### ISSUE TITLE
Zoom and Brush containers do not register mouse events on transparent background

### ISSUE THREAD

**Issue by naub** [FormidableLabs/victory#987]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Zoom and Brush containers function correctly when a mouse event is initiated on a data (or axis) element, but not when initiated (or transferred to) the container background. This is however not reproducible in a vanilla sandbox environment, so I suspect it is a CSS condition that is specific to my use case. Unfortunately my environment is impractical to replicate in a standalone testcase. I realise that this makes it hard to reproduce the problem, but I'm hoping you SVG experts might know which CSS or other environment variable might cause this behaviour.

**Comment by boygirl** [comment]
@naub that's definitely a weird one. Victory's containers render in the following structure:

```
<div style={defaults({}, yourParentStyles, { pointerEvents: "none", positioningStuff })}>
  <svg style={{ pointerEvents: "all", positioningStuff }}>
   ... all your chart stuff
  </svg>
  <div style={{ zIndex, positioningStuff}}>
     <svg style={{ overflow: "visible" }}>
         ... Victory's portal and anything that you've rendered into it _i.e._ tooltips
    </svg>
  </div>
</div>
```
I think the only CSS things that could cause what you're seeing would be setting `pointerEvents` or `touchAction` in your parent styles. You might also check your CSS rules for any `:nth-child` selectors or `!important` rules. 

I hope that helps! I'm going to close this issue, as it seems very specific to your app, but I'm happy to answer any more questions you might have.
