### ISSUE TITLE
Website Chart Examples do not Load

### ISSUE THREAD

**Issue by hibearpanda** [FormidableLabs/victory#988]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Gallery / example charts are not being loaded. Console outputs `cannot read call of undefined`.

### Reproduction

Just go to the [gallery](http://formidable.com/open-source/victory/gallery/).

**Comment by boygirl** [comment]
@hibearpanda yes, we are fighting with this gatsby issue: https://github.com/gatsbyjs/gatsby/issues/1043 I'm sorry for the inconvenience.

**Comment by tyson-kubota** [comment]
Seems to be fixed now! @boygirl , thanks for the rebuild/dedeploy.
