### ISSUE TITLE
How to get axis coordinate value to place custom label below or adjacent to axis?

### ISSUE THREAD

**Issue by code4arpit** [FormidableLabs/victory#990]
I am in requirement to place custom labels below to x-axis and ajacent to y-axis. For example : If my x-axis range falls between 1 to 10 then I need to put a label between 1 to 3 ,another in between 4 to 6 and last one between 6 to end of x axis. How could I get the coordinate of 1 ,3,4,,6 and last axis cooridinate.

I remember it is posisble in D3 when we defined x or y axis using domain and range.

How it is possible using Victory library.

Thanks and Regards
Arpit Jain

**Comment by boygirl** [comment]
@code4arpit if you add the labels as children of `VictoryChart` they will be provided with a `scale` prop from `VictoryChart` that you can use to translate your desired data positions into x, y coordinates. Here's an example you can use to get started:
https://codesandbox.io/s/k5mlyl60rr

**Comment by code4arpit** [comment]
Awesome.. Thanks a lot.
