### ISSUE TITLE
VictoryBar no longer accepts bar widths as of 0.26.0

### ISSUE THREAD

**Issue by Eseb** [FormidableLabs/victory#992]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

`VictoryGraph` used to allow for a `data` field of `width` which controlled individual bar widths. This no longer works as of 0.26.0.

### Reproduction

Same code, different versions: [0.25.7](https://codepen.io/Eseb/pen/yjaqvW) and [0.26.0](https://codepen.io/Eseb/pen/RyGBQL).

# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Since this is not a major version increment this seems like it's a bug—this should be a backwards-compatible update.

**Comment by boygirl** [comment]
@Eseb Victory is using pre v1 semver, so minor version bumps should be considered breaking as described here: https://github.com/FormidableLabs/victory#important. The breaking changes that caused the bump to `0.26.0` are described here: https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md.

For your specific bug, the upgrade path will be to add to your styles:

```
styles={{
  data: { 
    width: (d) => d.width
  }
}}
```

**Comment by Eseb** [comment]
Cheers, I'll change it over.
