### ISSUE TITLE
VictoryBoxPlot doesn't support functional values for stroke styles.

### ISSUE THREAD

**Issue by jdalegonzalez** [FormidableLabs/victory#994]
# Bugs and Questions

### Checklist

* [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of Victory

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Although you can use functional values for the fill styles in VictoryBoxPlot, none of the stroke values work with functional styles.

### Reproduction

In any of the "editable source" windows on the victory site, try the following....
```
<VictoryBoxPlot
  minLabels
  maxLabels
  data={[
    { x: 1, y: [1, 2, 3, 5] },
    { x: 2, y: [3, 2, 8, 10] },
    { x: 3, y: [2, 8, 6, 5] },
    { x: 4, y: [1, 3, 2, 9] }
  ]}
  style={{
    min: { stroke: (d) => "tomato" },
    max: { stroke: "orange" },
    q1: { fill: (d) => "tomato" },
    q3: { fill: "orange" },
    median: { stroke: "white", strokeWidth: 2 },
    minLabels: { fill: "tomato" },
    maxLabels: { fill: "orange" }
  }}
/>
```
Notice that while the q1 area is still filled, the min stroke is now missing.

**Comment by boygirl** [comment]
This fix will be released on Friday :)
