### ISSUE TITLE
`strokeLinejoin` style being stripped out from data styles in VictoryBar

### ISSUE THREAD

**Issue by ebrillhart** [FormidableLabs/victory#995]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I created a few bar charts a few months back with data styles including `strokeLinejoin: round`, which worked great. Those charts no longer have rounded ends, and the style isn't present in the DOM inspector, although I can add it there and it renders as expected. It seems like it may be getting stripped out of the whitelisted style attributes being passed to the svg components.

### Reproduction

Reproduction of the issue [here](https://codesandbox.io/s/61jv4jqyrr).

**Comment by chrisbolin** [comment]
possibly addressed by https://github.com/FormidableLabs/victory-core/pull/364. released in victory-core 22.0.0 and victory 0.26.0. Emma will check it out

**Comment by boygirl** [comment]
Indeed, this should be solved by https://github.com/FormidableLabs/victory-core/pull/364. I'm going to close this issue, but @ebrillhart if you're still hung up on this, please pester me.
