### ISSUE TITLE
Unable to use a function to set the width of each element of a polar chart

### ISSUE THREAD

**Issue by RichardFevrier** [FormidableLabs/victory#998]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When we are using a `VictoryBar` nested in a `VictoryChart` type `polar` we are not able to use a function to set the width in the `style` attribute

### Reproduction

You can reproduce this directly in the editor [https://formidable.com/open-source/victory/guides/polar-charts/#creating-polar-charts](https://formidable.com/open-source/victory/guides/polar-charts/#creating-polar-charts) by replacing the code with this one :

```
<VictoryChart polar
  domain={{ x: [0, 360] }}
  height={400} width={400}
>
  <VictoryBar
    style={{ data: { fill: "#c43a31", width: (d) => 50 }}} // <= here is the problem
    data={sampleDataPolar}
  />
</VictoryChart>
```

You can play by removing the `polar`keyword and see the difference.

**Comment by omorhefere** [comment]
How did you fix this?

**Comment by boygirl** [comment]
@omorhefere this was fixed with a change in the library. If you're still seeing this issue, please let me know what version of Victory you're using. A code snippet or reproduction in code sandbox also helps a lot.
